### ISSUE TITLE
Helm should check that a cluster has the min. k8s version and supports extensions used in a chart

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1001]
Today there is no way for Helm to check that a chart will work in a specific cluster. @adamreese pointed out that it might be possible to go through the manifests and verify that the cluster supports the types and extensions used in the chart.

If this validation is already done by the Kubernetes API, it may not be the job of Helm.

**Comment by technosophos** [comment]
Here's what I am thinking:

We make a change to the `Charts.yaml` file to support specifying `apiVersion` constraints per chart:

```
name: myChart
#...
kubernetesVersion: ">1.2.1"     # SemVer range that must be satisfied. Default is '*' (any)
requires:
  - v1   # this will be implicit, and default.
  - batch/v1                        # A few built-ins
  - extensions/v1beta1
  - foo.example.com/v1    # Custom 3rd party extension
```

## kubernetesVersion

This indicates that the remote cluster (the cluster in which Tiller is running) must meet this specific set of version constraints. SemVer ranges (a la https://github.com/Masterminds/semver) are allowed here.

The default is to accept any Kubernetes version.

As this is not feature detection, it should only be used when the `requires` filters cannot adequately express a requirement. (e.g., if there is a known bug in a version, and that bug would cause the chart to fail regardless of whether the apiVersion is correct)

## requires

As the name indicates, all extensions specified in this list are _required_. All specified versions must exist. (You can see the list of these on your cluster by running `kubectl api-versions`)

These requirements will be processed by Tiller prior to the templating step (that is, at the beginning of the install request). A chart and all of its subcharts must have their required extensions satisfied. If not, the result will be an error indicating which requirements are not satisfied.

**Comment by prydonius** [comment]
I think this makes a lot of sense, however, it seems like it would be safer and easier to just extract the list of required API extensions from the chart templates themselves. That way the chart developers don't need to maintain the list in the Chart.yaml file.

**Comment by technosophos** [comment]
Oh, that's an interesting idea. I don't see any reason why we couldn't do that. Are there any weird edge cases it could cause (e.g. where a chart didn't explicitly state a dependency on something, but actually required it)? If not, let's do it the way you suggest, @prydonius 

Should we keep the `kubernetesVersion` explicit version range?

**Comment by prydonius** [comment]
Can't really think of any edge cases right now, we might need to be careful in detecting the api versions used - for example if a chart decides conditionally to use a Replication Controller instead of a Deployment based on a value. That may mean we want to validate this after the templating step.

> Should we keep the `kubernetesVersion` explicit version range?

I'm not sure if there is much need for it, since checking the API versions should be enough in most cases. However, it also doesn't hurt to have the option there if, like you said, there was a bug in a specific version of Kubernetes.
