### ISSUE TITLE
Helm should provide some method to verify chart behavior

### ISSUE THREAD

**Issue by tmc** [kubernetes/helm#1002]
It should be straightforward to put charts under some sort of CI system to verify chart behavior.

Perhaps somethings `bats` inspired?

Checking that a chart comes up and can respond to a particular port in a particular way could be a tactic for verifying behavior.

**Comment by technosophos** [comment]
Thinking off the cuff... one thing we might be able to do is add a `test` hook that could execute a job after `post-install` that verifies certain things about a cluster.

Then running `helm install --run-test foo` (or something like that) could execute the tests, whereas the default behavior (`helm install foo`) would be to not run the test hook.

**Comment by technosophos** [comment]
Thinking about this more, I'm wondering what information we'd want to pass into a test fixture for validation. Would the chart plus rendered manifest be enough?

**Comment by technosophos** [comment]
This feature is now provided by Helm 2.2.0's `helm test` command.
