### ISSUE TITLE
Proposal: canonical path for icon files.

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1034]
Some applications may display icon files for Helm charts (for example, service catalog and marketplace web UIs). At one point, we had an `icon:` directive in the `Chart.yaml`, but removed it because it was never particularly well-defined. However, there is a clear need to associate icons with charts.

There are three possibilities for doing this:

1. Add a `icon: URL` directive in the Chart.yaml file, and require the value to be a URL to a remote resource.
2. Specify a canonical file name for icons (`icon.svg` or `icon.png`), and suggest that packagers put the icon inside of the chart.
3. Add an `icon: PATH_OR_URL` directive in Chart.yaml

For the sake of simplicity and (network) security, I am in favor of option 2. I'd suggest that we support both PNG and SVG formats, and look in the chart root for `icon.svg` or `icon.png`. I suggest that we also provide guidelines on sizing for PNG images.

Since neither Helm nor Tiller directly use images, this would likely be more a matter of documentation than anything else.

**Comment by runseb** [comment]
The problem with 2. is that if you read the index.yaml file you will need to extract the icon from the packaged chart to build up your marketplace display. Hence download the entire chart.

So I am actually in favor of 1.

PS: What we have done so far is to have our own map from the chart name to a local icon . It is not that bad after all.

**Comment by technosophos** [comment]
Oh, I suppose we could have an option 4, which would be to place the icon file in the repo alongside the tgz file.

I see what you mean about 2. Requiring apps to fetch and unpack the tarball in order to get the image is maybe a bit of a burden.

**Comment by technosophos** [comment]
So right now, momentum is leaning toward Option 1: Add a URL field (`icon: FULL_URL`).

**Comment by jstrachan** [comment]
By going with 1: we make it easy for all readers of chart index.yaml / Chart.yaml to have a URL they can use without any magic/scanning logic. 

For chart creators, the tool which packages and publishes the chart (or the repository) could take care of uploading the icon somewhere and filling in the full URL? So it might be for publishes it may look like `2:` its just the tool fills in `1:` for you?
