### ISSUE TITLE
Make “helm init” idempotent

### ISSUE THREAD

**Issue by stapelberg** [kubernetes/helm#1041]
I’m using helm as part of some automation (to run a loadtest) and would welcome the `helm init` command to be idempotent.

Currently, when running `helm init` multiple times, it fails on any run but the first:
```
$ helm init
$HELM_HOME has been configured at $HOME/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!

$ helm init
$HELM_HOME has been configured at $HOME/.helm.
Error: error installing: deployments.extensions "tiller-deploy" already exists

$ echo $?
1
```

This results in my automation having to run `kubectl delete rc --namespace=kube-system tiller-rc`, then retry `helm init`, which is ugly use of an implementation detail.

Instead, the expected result would be for helm to return with exit code 0 when the initialization succeeded — and in my opinion, initialization was successful when helm was already previously initialized :).

What do you think?

**Comment by stapelberg** [comment]
…and just after I wrote this, I realized that `tiller-rc` is no longer a thing, rather I now need to use `kubectl delete deployment --namespace=kube-system tiller-deploy`. This already broke once before, so I’d really like to get rid of this implementation detail.

**Comment by technosophos** [comment]
Will the `--client-only` flag not work for you?

**Comment by technosophos** [comment]
I'm looking into the possibility of catching the error for `"tiller-deploy" already exists` and special-casing that. /cc @michelleN

**Comment by stapelberg** [comment]
> Will the --client-only flag not work for you?

I don’t see how that would help. Without the tiller, I cannot use any `helm install` commands:

```
$ helm init --client-only
$HELM_HOME has been configured at $HOME/.helm.
Not installing tiller due to 'client-only' flag having been set
Happy Helming!

$ helm install rlt       
Error: could not find tiller
```

**Comment by technosophos** [comment]
I understand. Downgrading from an error to a warning in that case seems appropriate. I'll see what I can do.

**Comment by technosophos** [comment]
Got it in just in time for Alpha.3. Thanks for taking the time to clarify the issue for me.

**Comment by stapelberg** [comment]
Thanks for the quick fix!

**Comment by Kostkingdom** [comment]
Im running a demo for a class.  When I type helm init, I get a error: Unauthorized.  Anyone have a fix for this?
