### ISSUE TITLE
Change “helm install --replace” to delete any existing release with that name

### ISSUE THREAD

**Issue by stapelberg** [kubernetes/helm#1042]
Currently, to make `helm install` idempotent, I check for the exit code and call `helm delete`, followed by another `helm install` attempt.

I was wondering about your thoughts on whether helm could include that functionality itself, possibly in form of a `helm replace` command?

**Comment by technosophos** [comment]
We talked about this as the default for `helm install --replace`. But at the time, we decided not to have anything automatically delete resources because it seems a likely source of mistakes/confusion.

We'd be open to reconsidering. I don't think we've really weighed out the pros and cons.

**Comment by devth** [comment]
Not sure if this should be a separate but:

I'd really like to have something more akin to `kubectl apply`. I'm changing releases all the time, and need to be able to apply those changes without caring if it's a fresh install or an upgrade. Zero downtime is more important than anything, and I can already encode that in Kubernetes itself. Helm doesn't need to attempt to manage it for me.

@technosophos we discussed this a bit on Slack: `helm install --upgrade` or `helm upgrade --install`. How about just `helm apply`?

In the meantime, I'm fighting Helm hard, and doing things like [this](https://github.com/devth/helm-docker/blob/master/helm_install_or_upgrade). Maybe I'm missing something around idiomatic/intended usage.
