### ISSUE TITLE
helm init --host is unclear/not working

### ISSUE THREAD

**Issue by rimusz** [kubernetes/helm#1047]
`helm init --host master_ip` does not work. 
is that not implemented yet?

**Comment by adamreese** [comment]
I see how that is unclear.  Host is if you have a custom connection to the tiller grpc (dev mode, custom service), not kubernetes host.  

Running `helm init` without setting `--host` will use the same options set in `kubeconfig`.

**Comment by rimusz** [comment]
right, but about when I'm passing `kubeconfig` to `kubectl` case?
did not found a way to connect helm

**Comment by adamreese** [comment]
you can also use `KUBECONFIG=/whatever/foo helm init`

**Comment by rimusz** [comment]
@adamreese that did the trick, thanks
is that documented?

**Comment by rimusz** [comment]
cannot get helm->tiller working on my kube apps, no `scout` anymore in coreos releases 👎

**Comment by technosophos** [comment]
There is at least one known issue with CoreOS. #966
