### ISSUE TITLE
Validate Kubernetes yaml on install / upgrade

### ISSUE THREAD

**Issue by devth** [kubernetes/helm#1050]
When running `helm install` or `helm upgrade` it'd be useful to validate K8S yaml. That way I wouldn't have to continually install/delete a release while working on a large set of charts with lots of potential for typos/errors in the yaml.

**Comment by philips** [comment]
@devth So I understand: The invalid yaml is caused by bad template substitution, bad charts, or either?

**Comment by devth** [comment]
Bad charts, meaning: Helm was able to do the substitution, but it resulted in K8S manifests that did not adhere to K8S' spec. When Helm applies these, it results in an error at the K8S level, which produces a somewhat obscure error in Helm which is then presented to the user.

**Comment by philips** [comment]
Makes sense.

**Comment by michelleN** [comment]
thanks for submitting this. keep running into the same problem as well @devth 
cc/ @vaikas-google

**Comment by vaikas-google** [comment]
So, I've been looking into this. There's three ways that I can see do it, we could run kubectl --validate either on the client or server. Or we could use some of the kube validation code (as in link that in to client/server). I'm now investigating how the kubectl implements the validate / dry-run flag to see if I could leverage it. The first two seem bad based on how it's done as we do not want to tie the validation to the compile / kubectl release time vs. what the cluster is actually running. For example, an older version of helm should still work against a newer version of cluster and a newer version of helm shouldn't validate things that the older cluster doesn't support.

**Comment by adamreese** [comment]
kubectl --validate uses a schema file to validate against so I don't think the compile time will be a factor

**Comment by vaikas-google** [comment]
Ack. I still think we should not require the client to have kubectl? And we probably don't want to require kubectl on the server side, right? So, let me see how reusable it is?

**Comment by vaikas-google** [comment]
I got this up and running, and the tests are passing locally, but failing on circle ci. I wonder if it can't fetch the schemas for the validation and that is what's failing. 
It's failing with things like this:
2016-09-23 04:24:58.991294 I | Failed install perform step: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: getsockopt: connection refused
--- FAIL: TestInstallReleaseWithValidationWorksForValid (0.00s)

**Comment by vaikas-google** [comment]
Trying to see if I can just add the schema file to testdata directory and have the tests just use that (for cached schemas).

**Comment by vaikas-google** [comment]
@michelleN @adamreese 
Please take a look at the proposed changes, local unit tests work, but for some reason it's failing in the circle CI and I'll figure that out, but in the meantime, see if this is what you had in mind.

**Comment by ahawkins** [comment]
Note that `--dry-run` does not catch _all_ validation errors. It allowed something like those inside a container `env`:

```yaml
- name: FOO
   # This should fail because the spec states values must be strings, but it's given here as an number.
   value: 234132413284732
```

**Comment by technosophos** [comment]
2.2.0 now validates all manifests using the kubectl validator before anything is installed. Marking this closed.
