### ISSUE TITLE
Securely supply secrets via prompt on install/upgrade

### ISSUE THREAD

**Issue by devth** [kubernetes/helm#1053]
I'd like to be able to specify secret fields keys in a `values` file so that I can keep track of all my values in one place, but instruct Helm prompt me for that field's value similar to `read -s secret` when I install/upgrade or otherwise try to use that value and it's been marked as a secret and not yet set.

Somewhat related to #982 except that I want Helm to detect that the values haven't been set and prompt me for them.

Other ideas? The overall goals are:
1. avoid keeping track of which secrets I need to manually specify
2. avoid storing secrets in plaintext/base64 in my charts

**Comment by technosophos** [comment]
This hasn't been ruled out as a feature yet, but AFAIK nobody has proposed how we'd implement it.

Two options may be:

1. Handle this with a plugin
2. Add a `prompt` template function, which would work like `default`, but would prompt the user to enter an unsuplied value:

```
{{ prompt "type a password" | .Values.password }}
```

**Comment by whitecolor** [comment]
This probably should be out of scope of helm, and implemented via scripts.

**Comment by thomastaylor312** [comment]
This issue has been inactive for more than 30 days and there is a new issue (linked above) that has a proposal to implement it, so I am closing this issue.
