### ISSUE TITLE
Helm now easily installable via brew cask.

### ISSUE THREAD

**Issue by tback** [kubernetes/helm#1060]
Just so you know: `brew cask install helm` will now install helm and tiller on os x amd-64. 
https://github.com/caskroom/homebrew-cask/pull/23825

**Comment by macat** [comment]
👍  nice!

**Comment by technosophos** [comment]
Fabulous! Thanks!

**Comment by technosophos** [comment]
@tback I was asked today why the cask installs `tiller`, too. I didn't have a good answer for that.

Also, we're thinking about opening an issue to add `brew cask install helm` to the README. That sound good to you?

**Comment by tback** [comment]
@technosophos: Unfortunately I don't have a good reason to install tiller on the local machine. I'm very new helm and packaging go binaries for cask is easy, so I wrote the cask and installed what the package provided. 

Let's discuss this: 

If tiller on the local machine has _any_ value for the target audience (or a significant part of it) I want to install it. What is the target audience? Obviously it's not helm developers - they'll need to checkout and build it themselves. I reckon it is rather the people who want to start packaging for helm/kubernetes right now.

I learned that `helm init` will install tiller in the cluster. (I use [minikube](https://github.com/kubernetes/minikube) via cask for my helm experiments btw.) When I wrote my first charts I didn't need tiller.

Could someone who's more familiar with helm chip in on this? Right now I'm thinking that I should rather remove it. As soon as this thread cools down without a reason to keep it I will remove tiller from the cask. Does that sound good to you?

**Comment by technosophos** [comment]
@tback thanks for PRing the README change.

On OSX, I think the main use case for Helm is to use `helm init` and let it install Tiller. I, too, use minikube on OSX. The only time I run `tiller` directly is for development stuff.

So I guess my opinion is that we should default to just installing `helm`. If we get lots of feedback asking for `tiller`, maybe we could add that back in. That said, there's certainly no _harm_ in leaving Tiller in the release (other than inflating download size). So I'm open to whatever you think is best.

If you'd like to just hold off on changing this until `2.0.0-alpha.4`, that's fine. We're just really grateful that you put all of this together. Anything that makes it easier for people to use Helm is tremendously valuable to us.

**Comment by tback** [comment]
Cask downloads the release tarball anyway. So removing tiller won't save bandwidth. 
The readme states to install both helm and tiller I'd kind of expect to get both from cask too. This reduces the decision to this: Users will have something on their system they expect but don't need vs. Users don't have something on their system they expect but don't need. The latter case is worse in the still somewhat experimental context of helm because users cannot (as easily) play with tiller to see for themselves.

I'll leave it in.

**Comment by technosophos** [comment]
Cool. Again, thanks! I'm closing out this issue since there's nothing more to do.
