### ISSUE TITLE
Improve readability of client outputs

### ISSUE THREAD

**Issue by bmelville** [kubernetes/helm#107]
Currently our client outputs are just dumps of JSON responses from the service. We really want something much more beautiful for our users. For example, GCP Deployment Manager shows something like this for a deployment create:

$ gcloud deployment-manager deployments create d --config experimental/bmelville/ha-service/example.yaml
Waiting for create operation-1447888523552-524d8d11ee501-4c0b42a2-daf5e9dc...done.
Create operation operation-1447888523552-524d8d11ee501-4c0b42a2-daf5e9dc completed successfully.
NAME                         TYPE                             STATE      ERRORS
d-lb-fr                      compute.v1.forwardingRule        COMPLETED  -
d-lb-hc                      compute.v1.httpHealthCheck       COMPLETED  -
d-lb-tp                      compute.v1.targetPool            COMPLETED  -
d-service-us-central1-f-as   compute.v1.autoscaler            COMPLETED  -
d-service-us-central1-f-igm  compute.v1.instanceGroupManager  COMPLETED  -
d-service-us-central1-f-it   compute.v1.instanceTemplate      COMPLETED  -

It also shows errors appropriately.

**Comment by zmerlynn** [comment]
+1. I was about to file an issue on `dm deploy` output being unusable.

**Comment by jackgr** [comment]
Adding this issue to MVP as a fit and finish item. Most if not all of the commands have clean output, but someone needs to take a pass and make sure they look good.
