### ISSUE TITLE
Tiller in a bad state / unable to decode

### ISSUE THREAD

**Issue by devth** [kubernetes/helm#1084]
I think I got my Tiller in a bad state. This might be hard to repro, so I'll just describe what I did:

I did a dry run install of my release.

I tried to install a release with my own release name. An error occurred:

```
failed: [unable to decode "": [pos 121]: json: expect char '"' but got char 'n', unable to decode "": [pos 121]: json: expect char '"' but got char 'n', unable to decode "": [pos 121]: json: expect char '"' but got char 'n']
```

Not sure what that means.

I run `helm ls` and no releases exist.

I try to install again and it errors, saying the release already exists.

I delete the Tiller pod to clear all releases from memory.

Do a fresh `helm install` and things are good.

I've encountered this 2-3 times now while working on various charts. Once I see a "unable to decode ..." error, I'm not sure how to recover without deleting the Tiller pod then re-installing all my charts.

It seems to happen when something in my K8S manifest is incorrect and causes an error when getting applied, but I think "unable to decode" is masking the problem, so it's hard to figure out.

Related to https://github.com/kubernetes/helm/issues/1035

```
helm v2.0.0-alpha.3
```

**Comment by technosophos** [comment]
I think the current version of `helm ls` is not showing releases whose state is `FAILED`. There's an issue to add `--all` and `--deleted` flags (#973) that would help this case a lot.

**Comment by technosophos** [comment]
FWIW, the error `failed: [unable to decode "": [pos 121]: json: expect char '"' but got char 'n', unable to decode "": [pos 121]: json: expect char '"' but got char 'n', unable to decode "": [pos 121]: json: expect char '"' but got char 'n']
` indicates that a quotation mark was expected somewhere in the YAML. We're working on improving some of this output.

**Comment by devth** [comment]
Thanks @technosophos. It seems that once I accidentally introduce a yaml error during a helm upgrade, it's stuck in that state. After fixing the yaml by reverting to a known good state, the error remains the same. Do I need to delete the release?

**Comment by devth** [comment]
Can't delete the release either. Tiller logs when I try:

```
2016-08-25 17:42:59.885674 I | Using reaper for deleting foo
2016-08-25 17:42:59.903093 I | uninstall: Failed deletion of "foo-staging": yaml: line 56: did not find expected ',' or ']'
```

Where is this being stored and how do I reset the state?

**Comment by technosophos** [comment]
Oh. Hmmm... that is a nasty problem. I'll CC @michelleN on this. I think we just missed a verification step in `upgrade`.

In other news, `helm list --failed` and `helm list --deleted` are now in master.

**Comment by devth** [comment]
Great! Except I can't `helm list` either because:

```
helm list
2016/08/25 16:27:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
```

**Comment by urzds** [comment]
I got stuck in what I believe to be the same problem:
```
# helm ls --all
crazy-armadill
dapper-maltese
eating-oyster
enervated-gupp
full-hummingbi
loopy-bumblebe
morbid-deer
operatic-salam
queenly-skunk
ringed-platypu
whimsical-slot
# for r in $(helm ls --all) ; do helm delete $r ; done
Error: [unable to decode "": [pos 484]: json: expect char '"' but got char '{', unable to decode "": [pos 1144]: json: expect char '"' but got char '{', unable to decode "": [pos 384]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 1144]: json: expect char '"' but got char '{', unable to decode "": [pos 384]: json: expect char '"' but got char '{', unable to decode "": [pos 484]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 480]: json: expect char '"' but got char '{', unable to decode "": [pos 380]: json: expect char '"' but got char '{', unable to decode "": [pos 1140]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 1144]: json: expect char '"' but got char '{', unable to decode "": [pos 484]: json: expect char '"' but got char '{', unable to decode "": [pos 384]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 384]: json: expect char '"' but got char '{', unable to decode "": [pos 484]: json: expect char '"' but got char '{', unable to decode "": [pos 1144]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 1159]: json: expect char '"' but got char '{', unable to decode "": [pos 499]: json: expect char '"' but got char '{', unable to decode "": [pos 384]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 372]: json: expect char '"' but got char '{', unable to decode "": [pos 1132]: json: expect char '"' but got char '{', unable to decode "": [pos 472]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 484]: json: expect char '"' but got char '{', unable to decode "": [pos 384]: json: expect char '"' but got char '{', unable to decode "": [pos 1144]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 380]: json: expect char '"' but got char '{', unable to decode "": [pos 480]: json: expect char '"' but got char '{', unable to decode "": [pos 1140]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 1159]: json: expect char '"' but got char '{', unable to decode "": [pos 384]: json: expect char '"' but got char '{', unable to decode "": [pos 499]: json: expect char '"' but got char '{']
Error: [unable to decode "": [pos 384]: json: expect char '"' but got char '{', unable to decode "": [pos 1159]: json: expect char '"' but got char '{', unable to decode "": [pos 499]: json: expect char '"' but got char '{']
```

Installing new releases also fails. It seems I cannot do anything anymore. Even `kubectl --namespace=kube-system delete deployments/tiller-deploy && helm init` does not rescue me, as the broken releases will reappear after a few seconds.

**Comment by urzds** [comment]
The problem appears to be that `helm install` uploads everything in the release's folder and then chokes on it.

I looked at the configmaps (with random names, not hinting at tiller) it created, specifically at the `release` data. It contains the end results from template substitution in `templates/*.yaml`, but also all files in the release directory (including the not-substituted templates, binary and JSON files). The substituted templates do not contain any JSON anymore (I base64 escaped everything, to exclude them as a possible cause), so I conclude that tiller/helm has a problem with the other files that happen to be lying around.

**Comment by technosophos** [comment]
I believe this is now solved. At this point, failed YAML parses _should not_ prevent a deletion event (though you will still get the YAML error as output).
