### ISSUE TITLE
install instructions on releases page

### ISSUE THREAD

**Issue by jfrazelle** [kubernetes/helm#1087]
It would be nice if in each release there were instructions on how to easily install, for example coreos does this well with etcd: https://github.com/coreos/etcd/releases

**Comment by philips** [comment]
@jfrazelle The most recent release gets close to doing this: https://github.com/kubernetes/helm/releases/tag/v2.0.0-alpha.4

However, the script is a little broken, at least for me, I think it should be:

```
export HELM_OS=darwin; wget https://github.com/kubernetes/helm/releases/download/v2.0.0-alpha.4/helm-v2.0.0-alpha.4-$HELM_OS-amd64.tar.gz && tar -zxvf helm-v2.0.0-alpha.4-$HELM_OS-amd64.tar.gz && cd $HELM_OS-amd64
```

cc @technosophos

**Comment by janetkuo** [comment]
Coping my comments in #1184:

> 
Consider adding a `&&`:
```console
$ HELM_OS=linux && wget https://github.com/kubernetes/helm/releases/download/v2.0.0-alpha.4/helm-v2.0.0-alpha.4-$HELM_OS-amd64.tar.gz && tar -zxvf helm-v2.0.0-alpha.4-$HELM_OS-amd64.tar.gz && cd $HELM_OS-amd64
```
or simply remove `$HELM_OS`:
```console
$ wget https://github.com/kubernetes/helm/releases/download/v2.0.0-alpha.4/helm-v2.0.0-alpha.4-linux-amd64.tar.gz && tar -zxvf helm-v2.0.0-alpha.4-linux-amd64.tar.gz && cd linux-amd64
```

**Comment by philips** [comment]
@technosophos can we do this for alpha.5. We really should fixup alpha.4 too.

**Comment by technosophos** [comment]
Fixed on Alpha.4, and will do the same with Alpha.5.

I just used @janetkuo 's version (which was essentially @philips's version). Thanks!
