### ISSUE TITLE
lint: add rule for warning against non-deterministic resource name lengths

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1093]
See https://github.com/kubernetes/helm/issues/1071#issuecomment-241122293

The helm generated `.Release.Name` is now limited to 14 characters, so a service can safely use a name with the release name if it's `<= 10` characters.

To make it easy for chart developers to check for this, we could add a lint warning when a service name is `>= 10` for `.Release.Name = ""`.

/cc @technosophos @lachie83

**Comment by technosophos** [comment]
Do we want to do this now that Kubernetes upstream has more reasonable length allowances?

**Comment by technosophos** [comment]
I'm closing for now. Re-open if we still feel there is a need for this.
