### ISSUE TITLE
Helm in an inconsistent state after botched deployment

### ISSUE THREAD

**Issue by wstrange** [kubernetes/helm#1094]
Helm version Alpha.3. 

I had an error in my chart. Not sure the specifics are relevant, but the error was that a volume name did not match up with the volume specification (i.e. not a syntax error, something that only Kube would likely catch).

The chart was partially deployed (configmap, secrets, etc. all got deployed), but helm did not create a release name. 

helm list does not show anything, so there is nothing that I can run a helm delete on.

If I attempt to redeploy the Chart, helm errors out again - because some components of the chart are already present. 

Perhaps there needs to be a  helm install --force option ? 
Or a helm delete -f chart-name  - which attempts to identify the components and clean them up?

**Comment by wstrange** [comment]
OK - I may have to walk this back..

I did not read the error message carefully, but I now see that helm install fails, but it does print a release name as part of the error.  The release does not show up with helm list - but I gather that is fixed in master.

I honestly can't recall if my original error printed the release name or not, so I think this can be closed until I can confirm.

**Comment by michelleN** [comment]
@wstrange - I think this might be much easier to debug fix with #973 gets resolved. Were you able to successfully run a `helm delete [RELEASE]`?

**Comment by technosophos** [comment]
`helm list --all` and `helm list --failed` are not on master, so for the time being I'll close this issue.
