### ISSUE TITLE
helm status [deleted-release] should not result in an error

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#1095]
```
helm [(detached from brian/master)*]$ bin/helm delete winning-quoll
helm [(detached from brian/master)*]$ bin/helm status winning-quoll
Error: release: not found
```

Have we discussed the status of a deleted release? I'd like to at least see something like "This release was deleted" and maybe a timestamp. Any thoughts?

**Comment by prydonius** [comment]
I think the expected behaviour here would be something like:

```
$ helm status winning-quoll
Last Deployed: Tue Jul 26 16:35:58 2016
Status: DELETED
```

i.e. just updating Status to show that it's been deleted.

**Comment by technosophos** [comment]
Same goes for failed releases. They should be displayed.
