### ISSUE TITLE
helm package with a lint flag

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#1119]
It would be nice to have `helm package [chart] --lint`. Lint a chart before packaging it.

**Comment by joe2far** [comment]
Should such an option fail (i.e. not package the chart), if the chart has errors or warnings?

**Comment by michelleN** [comment]
@joe2far I figure it would fail if there chart has any errors but not on warnings (like the lint command).

**Comment by prydonius** [comment]
I'm wondering if it actually makes sense to have this option, do you see much value over just running `lint` before `package`? The downside of this approach is that there will be differing implementations, and this one may not support all the options `lint` does (for example, the `--strict` flag).

Just my two cents.

**Comment by technosophos** [comment]
I see what @prydonius is saying. Is there anything gained by doing `helm package --lint` over `helm lint && helm package`? I do like the idea of streamlining things, but as I think about it, I'm wondering if we're streamlining one area only to make another more complex. I know @joe2far  already has a PR open for this. Maybe he'd like to weigh in on this.

**Comment by joe2far** [comment]
I also see @prydonius point, as it:
- adds complexity to the package logic
- support for "--lint", "--lint-strict" and future lint flags would be needed on the pkg cmd
- and it does not add much over usage of the 2 cmds
 (I am happy to abandon the PR for this to be closed)

The area I was concerned with, is packaging a  chart which has lint errors, that prevents it from being installed. It would better to discover these errors when packaging the chart and not when it fails to install. Also, linting a chart is typically performed before deciding to packaging it, but integrating linting into packaging while having a separate lint will just add needless complexity.

**Comment by technosophos** [comment]
I am going to mark this as `wontfix` and close it. Thanks again @joe2far for the work you did on this.
