### ISSUE TITLE
helm update doesn't update the pods of rc's or daemonset's

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#1120]
when we do a `helm upgrade` the deployment, rc and daemon set are updated and since deployment take care of the pods to be updated they are fine but rc and daemon set pods are not upgraded.

**Comment by technosophos** [comment]
Does Kubernetes itself automatically re-deploy pods on update of RC/DS?

**Comment by kmala** [comment]
no..it doesn't...i think this more sort of an enhancement request than an issue.

**Comment by technosophos** [comment]
This was implemented with the `--restart-pods` flag.

**Comment by omerlh** [comment]
With a newer version of helm, use `--recreate-pods` flag to achieve the same result.
