### ISSUE TITLE
Proposal: reset/resync the state of a release

### ISSUE THREAD

**Issue by devth** [kubernetes/helm#1125]
I think it's important to be able to reset/resync the state of a Helm release with what is actually running in Kubernetes.
## Why
1. I updated a resource outside of Helm
2. The release's state has become corrupt

2 is the particularly important reason. If/when there's a bug in a Helm release, it's pretty easy (in my experience) to get the release in a bad state. When this happens you'll experience one or more of these problems:
1. Can no longer upgrade a chart because it errors:
   
   ```
   Error: Looks like there are no changes for NAME
   ```
   
   Regardless of actual changes.
2. Can no longer upgrade a chart because it thinks the resources don't exist, even when they do:
   
   ```
   helm upgrade NAME --values VALUES CHART_DIR
   Error: UPGRADE FAILED: [No resource with the name onyx-dashboard found.,
   No resource with the name onyx-dashboard found.,
   No resource with the name es-data found.,
   No resource with the name es-data found.,
   No resource with the name elasticsearch found.,
   No resource with the name elasticsearch found.,
   No resource with the name elasticsearch-lb found.,
   No resource with the name es-client found.,
   No resource with the name es-secret found.,
   No resource with the name elasticsearch-discovery found.,
   No resource with the name postgres found.,
   No resource with the name postgres-headless found.,
   No resource with the name postgres-lb found.,
   No resource with the name postgres-config found.,
   No resource with the name postgres found.,
   No resource with the name postgres-console found.,
   No resource with the name es-master found.]
   ```
3. Can no longer get the status of a release:
   
   ```
   helm status NAME
   Error: no objects passed to create
   ```

When this happens, the only way I've found to fully reset things is to delete the release's ConfigMap and all the K8S resources, then do a fresh install. This of course isn't an option if you're already serving traffic and need to ensure zero downtime.
## How

Maybe this could work like:

```
helm reset RELEASE
```

This deletes the `release` data in the release's ConfigMap, then instructs Tiller to rebuild that data from all the existing resources associated with `RELEASE`.

Or maybe you don't want to expose/promote this functionality, so make it a little harder: manually go edit the release's ConfigMap, deleting the `release` key/value. Tiller notices and rebuilds its state automatically, restoring the `release` k/v with the new state. This seems to add a nice level of resiliency to Tiller (better than a panic!).
## Other possible benefits
- Ease migration between storage drivers
- Begin to support the notion of importing existing resources into a new release (like when you already have a ton of infra in K8S and you want to start using Helm to manage it)
- Restore my sanity

**Comment by jstrachan** [comment]
this just came up on slack; maybe a `helm upgrade` should work like editing a Deployment; it creates a new version of the ConfigMap (like the Deployment controller creates a new ReplicaSet) then we could have a `helm rollback` command

**Comment by technosophos** [comment]
I'm bumping this to the 2.1 release because the core team doesn't have bandwidth. But if anyone wants to give this a try, I would _love_ to see it happen.

**Comment by mikebryant** [comment]
I'd also like to consider the use-case where we have existing resources that we want to adopt as part of a helm release.
e.g. I've brought up a self-hosted cluster with bootkube, but I want to manage the kubelet daemonset and the kube-apiserver deployment as part of a helm release.

Currently trying to do an install that has the same names as existing resources errors out saying they already exist.

**Comment by technosophos** [comment]
A new tool called `chartify` my help ya'll out: https://github.com/appscode/chartify by @TamalSaha 

Let me know if this isn't meeting the needs expressed in this ticket. Otherwise, I'll probably close this one out.

**Comment by kuroneko25** [comment]
Does https://github.com/appscode/chartify solve the problem of using Helm with existing resources in k8s?

**Comment by technosophos** [comment]
@kuroneko25 I believe that was roughly the intent.

**Comment by devth** [comment]
One use case I don't think `chartify` addresses is moving multiple charts that have already been installed into a single umbrella parent chart.

**Comment by bacongobbler** [comment]
alternative proposal: #2730
