### ISSUE TITLE
add --context option

### ISSUE THREAD

**Issue by damoon** [kubernetes/helm#1127]
Currently i am using kubectl to deploy stuff. With --context i select the cluster+authentication to use.
I would like to be able to to the same with helm.
Currently, for actions on different clusters, i need to set the current context again and again or create manually maintained .kube/config files and point to them with KUBECONFIG.

**Comment by technosophos** [comment]
I started exploring this issue last week. Looks like we should be able to do it.

**Comment by philips** [comment]
@damoon I am not following what you want here. Are you saying you want helm to use the kubectl context or you want helm to have its own context flag?

**Comment by technosophos** [comment]
Per the conversation in slack from back then, the ask is that we make it possible to point to a specific context that is declared inside of the Kubernetes context configuration. And we do that by adding a `--context STRING` option. (Correct me if I'm wrong, @damoon)

Helm uses the Kube config file at `$KUBECONFIG` to get its context, and it then authenticates to the API server using the appropriate credentials. But right now, it only uses the default context.

**Comment by damoon** [comment]
https://github.com/kubernetes/helm/issues/1127#issuecomment-246529122 exactly describes my use case.
I have access to three kubernetes clusters. When i tried to use helm instead of kubectl directly, it involved a lot of manual work to set the cluster to use. i could have used mulitple kubeconfig files (and manually maintained/sync those on changes) or tried to remember to set and reset the default each time i wanted helm to use a different cluster. Both are not nice options and kubectl already found a solution with --context.
