### ISSUE TITLE
Helm delete deployment fails when components have already been removed

### ISSUE THREAD

**Issue by csaintc** [kubernetes/helm#1133]
I have a chart `test` which defined two resources: an endpoint and a service.

I deleted the components helm was managing using `kubectl delete endpoint test`.

Now when I try to delete the deployment, it gives me an error:
```
10084 ◯  helm delete joyous-sheep
Error: endpoints "test" not found
```

version:
```
10083 ◯  helm version
v2.0.0-alpha.3
```

**Comment by spiddy** [comment]
I have the same error.

IMO, helm should continue with the deletion of the rest resources, and delete the release from the system afterwards.

Currently if a resource is deleted, the release cannot be removed using helm unless you go and delete the ConfigMap directly from Kubernetes.

**Comment by michelleN** [comment]
Replicated this exactly using the endpoint/service pair. Looking deeper now! 👀

**Comment by michelleN** [comment]
@csaintc fixed this. Let me know if you have any issues.
