### ISSUE TITLE
Helm status improvements and fixes

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#1134]
First of all, the `helm status` command is super useful :), but using it, I noticed a couple of issues:
- Alignment: It would be great if we could align the columns in the context of every resource.
- Namespace value not shown: Reproduced in GKE and Minikube with the Helm's latest version in master. 
- Resources order: the order of the resources can change in consequent calls to `helm status`. Basically in some cases you can for example get services before deployments and vice-versa. This can be annoying if you use this command to find for example the public IP of the services,

Output example.

```
helm status giggly-hound
Last Deployed: Thu Sep  1 14:09:40 2016
Namespace: 
Status: DEPLOYED

Resources:
==> v1/Secret
NAME                TYPE      DATA      AGE
giggly-hound-odoo   Opaque    2         4m
giggly-hound-postgresql   Opaque    1         4m

==> v1/Service
NAME                CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
giggly-hound-odoo   10.0.0.103   <pending>     80/TCP    4m
giggly-hound-postgresql   10.0.0.247   <none>    5432/TCP   4m

==> extensions/Deployment
NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
giggly-hound-postgresql   1         1         1            1           4m
giggly-hound-odoo   1         1         1         0         4m
```

**Comment by vaikas-google** [comment]
Yeah, the alignment is a bit wonky. It uses the kubectl to print things out, and I was hoping it would actually like you know, align them :) I'll take a look and see what can be done. Could manually spin through each resource and find the longest and set the tabs that way, but was hoping for something a bit cleaner.

Interesting on the namespace, I thought it just pulls it from the Release.Namespace, but perhaps that's not the case. I'll take a looksie...

I could sort the keys for the resource types so they would at least be alphabetical. But I'm curious why does the order of entries matter for finding the public ip for a service? Wouldn't you just find the entry for:
 - v1/Service and then go from there.

But, even then, I think we should support more structure in this output for easier parsing, perhaps something like -o json that would actually give the json representation of the resources. But if there's value in making sure the order is preserved, that's a much quicker fix and I can do that.

**Comment by vaikas-google** [comment]
Yeah, so the Namespace is indeed pulled from the Release stashed in the persistence:
https://github.com/kubernetes/helm/blob/master/cmd/tiller/release_server.go#L194
and it's used to query the k8s for the resources, so interesting that it's not being preserved through the client.

**Comment by vaikas-google** [comment]
Is the server also running the code from the master? I added the namespace feature after that, wonder if the container hasn't been updated to it yet. When I run tiller locally and connect to it, namespace is filled in.

**Comment by migmartri** [comment]
> Is the server also running the code from the master? I added the namespace feature after that, wonder if the container hasn't been updated to it yet.

@vaikas-google, you are right. My client was updated but my server was not. I apologize for that.  

Definitely having this https://github.com/kubernetes/helm/issues/761 will help.

**Comment by technosophos** [comment]
Alignment issue is now captured in #1593, which means I think we can now close this one.

**Comment by MPV** [comment]
Sorting is covered in #3127.
