### ISSUE TITLE
performUpdate does not mark a release as FAILED on failure

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1137]
If an update fails, the release itself is not marked FAILED. I'm not positive about this, but it seems to me that at that point, the release is in a failed state. _Unless_ the failed update simply results in a still-running original version, in which case DEPLOYED is the right status code.

**Comment by technosophos** [comment]
@michelleN can you verify which is the current behavior?

**Comment by michelleN** [comment]
At the moment, it's performing an update. If there is an error in Kube, it returns the error without modifying the release object's status. 
This is a probelm. Correct behavior should be. 
1.) Update the resources
2) If there is an error updating, mark old release as superseded and current release as failed.

In the current state, we're only updating statuses when there is no failure. :(

```

	if err := s.performKubeUpdate(originalRelease, updatedRelease); err != nil {
		return nil, err
	}

	// post-upgrade hooks
	if !req.DisableHooks {
		if err := s.execHook(updatedRelease.Hooks, updatedRelease.Name, updatedRelease.Namespace, postUpgrade); err != nil {
			return res, err
		}
	}

	originalRelease.Info.Status.Code = release.Status_SUPERSEDED
	if err := s.env.Releases.Update(originalRelease); err != nil {
		return nil, fmt.Errorf("Update of %s failed: %s", originalRelease.Name, err)
	}

	updatedRelease.Info.Status.Code = release.Status_DEPLOYED

	return res, nil
```
