### ISSUE TITLE
Add an `--update` flag to `helm repo add`

### ISSUE THREAD

**Issue by nicr9** [kubernetes/helm#1141]
Currently we have no way to change the URL for a repository:

```
$ bin/helm repo add test http://charts.test.com
Error: The repository name you provided (test) already exists. Please specify a different name.
```

It would be nice for scripting purposes for `helm repo add` to be able to update repository details (if that repository has already been registered):

```
$ bin/helm repo add --update test http://charts.test.com
test has been updated
```

**Comment by technosophos** [comment]
I commented on #1142, but I think this is a good idea.

**Comment by nicr9** [comment]
Thanks @technosophos !

:grinning:

**Comment by technosophos** [comment]
One of the other Helm devs suggested that maybe the update behavior really shouldn't need a flag. Maybe it should just be the default. I'll see if @jackfrancis or @michelleN have anything to add on that front.
