### ISSUE TITLE
Add description to helm search output

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/helm#1149]
We should add the chart description to the helm search output. Something like:

```
$  helm search ""
kubernetes-charts/alpine-0.1.0.tgz                       This is just for testing!
kubernetes-charts/mariadb-0.3.0.tgz                   A production ready MariaDB installation
```

**Comment by technosophos** [comment]
Done in Alpha.5. I also included the description in the search index, so if you, for example, search for `mysql`, `mariadb` will show up (though lower on the list because of the weighting algorithm).
