### ISSUE TITLE
Use 'stable' and 'incubator' names for official repositories

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1151]
As @viglesiasce and @michelleN discussed in Slack, we should setup `stable` and `incubator` as default repos in Helm (pointing to the k8s buckets for [kubernetes/charts](https://github.com/kubernetes/charts) - currently only `stable` exists).

/cc @migmartri @jackfrancis as this is also what we decided on using for the Helm UI.

**Comment by technosophos** [comment]
I think all we need to implement this are the correct base URLs for those repositories.
