### ISSUE TITLE
Cask version appears to be incorrect

### ISSUE THREAD

**Issue by devth** [kubernetes/helm#1152]
```bash
/usr/local/Caskroom/helm/2.0.0-alpha.4/darwin-amd64/helm version
v2.0.0-alpha.2+868b82c
```

This looks incorrect ☝️ . Compare to a fresh build on master:

```bash
$GOPATH/src/k8s.io/helm/bin/helm version
v2.0.0-alpha.4+36606cf

**Comment by viglesiasce** [comment]
I also reproduced this with the release tarball.

**Comment by michelleN** [comment]
cc/ @adamreese

**Comment by adamreese** [comment]
Sorry for the late post, this was fixed a few days ago.  New tarballs are up on the release page.
