### ISSUE TITLE
command to list all the charts in a repository?

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#1156]
I've created a helm repository with lots of the fabric8 microservices:
http://fabric8.io/helm/

I can search all repositories but I figured it might be interesting to list the apps in a repo? 

something like
```
helm charts [repoName]
```
If not repo name it'd list all the charts for all repos otherwise it'd just filter those ones in the given repository name. I was assuming it'd just show the latest version too, not all versions.

Thoughts? Happy to submit a PR if folks think its a good idea

**Comment by michelleN** [comment]
I like this a lot. Would love to see a PR for this @jstrachan.

**Comment by technosophos** [comment]
I think the name `helm charts` is going to be used for managing chart dependencies. But I agree with the idea @jstrachan suggests, and would love to see it implemented.

**Comment by spiddy** [comment]
Related to #1148

**Comment by technosophos** [comment]
This is now implemented with `helm search`:

- `helm search` will show all charts
- `helm search stable/` will show all charts in the `stable` repository.

**Comment by schollii** [comment]
I'm not finding how to get all versions of a chart. Eg helm search stable/my-chart only prints the latest. There should be a flag to get all versions. We have multiple deployments that use different versions.

**Comment by bacongobbler** [comment]
Use `helm search repo stable/wordpress --versions` if you want to view all versions of a particular chart (`helm search stable/wordpress --versions` if you're on Helm 2).

**Comment by schollii** [comment]
Sorry I somehow missed that option to the search command, thanks for info.

**Comment by timothyclarke** [comment]
For those coming here with helm 3
Try `helm search repo <repo name>` eg `helm search repo stable`
