### ISSUE TITLE
install a chart from a repository or URL in one command?

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#1158]
the current `helm install` command assumes the chart is on the local file system.

Given a chart - say one of these: http://fabric8.io/helm/ - I figured it'd be nice to have a 1 liner to install the chart. Something like:

```
helm install http://central.maven.org/maven2/io/fabric8/devops/apps/chaos-monkey/2.2.247/chaos-monkey-2.2.247-helm.tar.gz
```

Then if the parameter to helm install is a URL, it'd download the chart to a temporary folder somewhere and then install it? This would make it super easy for anyone to install a chart from any URL on the internet.

Another option for folks who wish to install the repo first could be something like:
```
helm repo add fabric8 https://fabric8.io/helm
helm install fabric8/chaos-monkey
```
which would use the `fabric8` repository and find the latest version of the `chaos-monkey` chart and download that?

I guess the complexity of this last example is the ambiguity between a local folder and a chart in a repository; so maybe a custom arguments are required?
```
helm install --repo=fabric8 chaos-monkey
```
which would force the `chaos-monkey` argument to be interpreted as a name in the repository versus a local folder?

Happy to submit a PR if folks want

**Comment by michelleN** [comment]
Currently, you can install a chart by passing in a url to the `helm install` command.
For example, try `helm install http://storage.googleapis.com/kubernetes-charts/alpine-0.1.0.tgz` This will do something slightly different than what you're saying here. It will do a `fetch` and save the packaged chart to your local directory and then install that. It doesn't download to a temp directory like you mentioned.

I really like your idea of being able to install the latest version of the chart with referencing the version. That's a much a better user experience that what we currently have. Definitely think being able to do `helm install fabric8/chaos-monkey` is very valuable.

**Comment by jstrachan** [comment]
I guess the URL only works if (i) you have added the repository already and (ii) the URL points to the canonical path of a chart within that repository? 

e.g. this fails for me:
```
$ helm install http://central.maven.org/maven2/io/fabric8/forge/packages/cd-pipeline/2.3.27/cd-pipeline-2.3.27-helm.tar.gz
Error: file "http://central.maven.org/maven2/io/fabric8/forge/packages/cd-pipeline/2.3.27/cd-pipeline-2.3.27-helm.tar.gz" not found
```

**Comment by technosophos** [comment]
^^ That is a bug. It should be allowed to download a chart by URL alone.

For the other stuff, I think what you said makes perfect sense. If you have a second, would you mind weighing in on the proposal for streamlining some of this? #1198 You might also be interested in the related search issue #1199.

Currently, the ambiguity of `helm install fabric8/chaos-monkey` is resolved as follows:

- If a repo named `fabric8` already exists, look there first
- Otherwise, treat the file as `./fabric8/chaos-monkey`

If you definitely want a local path, you can short-circuit by prepending `./`: `helm install ./fabric8/chaos-monkey`

**Comment by jstrachan** [comment]
I think we can mark this one as closed now - it all seems to work perfectly here; whether the URL is part of an installed repository or not. Alpha 5 is looking good thanks!
