### ISSUE TITLE
repository: index checksum field improvements

### ISSUE THREAD

**Issue by philips** [kubernetes/helm#1166]
The [repo index file](https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md#the-index-file) has a field called `checksum`. After reading through the code that generates/verifies this file I think we need to change it in a few ways based on lessons learned in OCI, AppC, and Docker Images.

0. Use a hash that isn't sha1 ([as it uses today](https://github.com/kubernetes/helm/blob/master/pkg/repo/repo.go#L173)), even though it has performance problems compared to sha512 most systems in the ecosystem are using sha256.
1. The field should be probably be renamed Digest based on the pretty standard [hashFn(input) -> digest language](https://en.wikipedia.org/wiki/Cryptographic_hash_function)
2. The field should describe the cryptographic hash used to generate the digest in a well-known format, e.g. (sha256:cafecafecafe) to future proof the system, this is what OCI and AppC do.
3. The [doc](https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md#the-index-file) describing the index file should be clear about the algorithms used and the digest serialization format. We can borrow from OCI: https://github.com/opencontainers/image-spec/blob/master/descriptor.md#digests-and-verification

Does this all seem reasonable? I can work up a PR.

**Comment by michelleN** [comment]
These suggestions make sense. A PR would be great. Thank you.

**Comment by philips** [comment]
Sounds good. I will do that.

We need to discuss this issue as well so the system makes sense
holistically https://github.com/kubernetes/helm/issues/1167

**Comment by technosophos** [comment]
This will definitely bring the `index.yaml` format into parity with the provenance and requirements packages. So I'm for it.

**Comment by technosophos** [comment]
This change was included in #1197, too.
