### ISSUE TITLE
fix: Helm should emit an error when it cannot find a directory in a chart tgz

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#1171]
I figured out why the charts I created don't install, the tarballs put the`Chart.yaml` inside the root of the `.tgz` file, not in a child folder. e.g.

```
# this one works
$ tar tf alpine-0.1.0.tgz
alpine/Chart.yaml
alpine/values.yaml
alpine/templates/alpine-pod.yaml
alpine/README.md

# this one doesn't
$ tar tf chaos-monkey-2.2.247.tgz
templates/
templates/chaos-monkey-svc.yml
templates/chaos-monkey-configmap.yml
templates/chaos-monkey-deployment.yml
Chart.yaml
README
```

Which then leads to:

```
$ ./bin/helm install fabric8/chaos-monkey-2.2.247.tgz
Downloading chart from: http://central.maven.org/maven2/io/fabric8/devops/apps/chaos-Fetched fabric8/chaos-monkey-2.2.247.tgz to /workspace/go/src/k8s.io/helm/chaos-monkey-2.2.247.tgz
Error: chart metadata (Chart.yaml) missing
```

Which had me quite confused for a while as when I opened the tgz file i found the`Chart.yaml` file ;). (Also on a mac double clicking on a `.tgz` file generates the same folder layout ;)

I figure other folks may make the same mistake as me :) At the very least we should make it really obvious that a chart.tgz must include a single child folder inside for the Chart.yaml.

Right now the code assumes there's always 1 level deep folder:
https://github.com/jstrachan/helm/blob/96de0e35aa2eda4869a72de31570b59a4aa36a07/pkg/chartutil/load.go#L87

I wondered about adding a check first for a file called "Charts.yaml" and if so generating a warning that the chart should be in "foo/Charts.yaml" but still parsing it; otherwise then stripping the first folder from the file names?

Happy to submit a PR - just wondered which way folks preferred - accepting both styles of tarball layout; warning if no folder present - or always rejecting? At the very least we could give a really descriptive message of why the tarball should be rejected

**Comment by jstrachan** [comment]
I just submitted a PR that accepts a tgz with the Chart.yaml inside `Chart.yaml` or `foo/Chart.yaml` generating a warning if charts of the former are used. I figured its easy to accept slightly-wrongly packaged chart.tgz but we can then encourage folks towards the correct packaging

**Comment by philips** [comment]
Did you generate this accidentally? I feel like we should be super strict with formats to make sure tooling can be consistent.

**Comment by technosophos** [comment]
Here's the "light" spec for the chart format: https://github.com/kubernetes/helm/blob/master/docs/charts.md#the-chart-file-structure

The expectation is that the chart is always in a directory, that the directory name is always the name of the chart (e.g. matches `name:` in Chart.yaml), and that the Chart.yaml file is always inside of that directory.

Sounds like there's a bug somewhere that is not enforcing the directory part correctly.

**Comment by jstrachan** [comment]
@philips I generated them accidentally; I didn't see any docs at the time on that there should be a folder in the tar or what it should be called

@technosophos thanks -  the docs are extremely clear about the layout of charts on your local file system - they just don't say much about the layout of the tzg file. With hindsight I guess its obvious that the chart folder should be included in the tgz - I suspect though others will make the same mistake I made - so at the very least we should warn that the tgz file is invalid if it doesn't contain the directory

**Comment by kbriggzi** [comment]
> Here's the "light" spec for the chart format: https://github.com/kubernetes/helm/blob/master/docs/charts.md#the-chart-file-structure
> 
> The expectation is that the chart is always in a directory, that the directory name is always the name of the chart (e.g. matches `name:` in Chart.yaml), and that the Chart.yaml file is always inside of that directory.
> 
> Sounds like there's a bug somewhere that is not enforcing the directory part correctly.

oh sadness broken link

**Comment by joejulian** [comment]
It was no longer relevant.
