### ISSUE TITLE
connection error to tiller pod 

### ISSUE THREAD

**Issue by MahipalRao** [kubernetes/helm#1183]
Trying to install alpine. I am using v2.0.0-alpha.4 
and executed 
helm --host localhost:44134 install docs/examples/alpine
The continuous output is

2016/09/12 22:49:58 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:44134: getsockopt: connection refused"; Reconnecting to "localhost:44134"

Environment is ubuntu 16.04 and kubernetes provider is localhost
What could be the solution ?

**Comment by technosophos** [comment]
Do other commands like `helm list` work?

**Comment by MahipalRao** [comment]
No helm list is not working. The error from helm list is as follows
E0913 07:30:00.111409   31887 portforward.go:327] an error occurred forwarding 36708 -> 44134: error forwarding port 44134 to pod tiller-deploy-500364655-uowdh_kube-system, uid : unable to do port forwarding: socat not found.
2016/09/13 07:30:00 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing

**Comment by michelleN** [comment]
wonder if this is related to #966

**Comment by fibonacci1729** [comment]
Could you verify tiller is running within your local kubernetes cluster? something like ```kubectl get pods -o wide``` should provide sufficient info.

**Comment by MahipalRao** [comment]
michelleN:
installed socat. now the error is different.
`helm --host localhost:44134 list`
`2016/09/15 20:54:20 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:44134: getsockopt: connection refused"; Reconnecting to "localhost:44134"
2016/09/15 20:54:22 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:44134: getsockopt: connection refused"; Reconnecting to "localhost:44134"`

fibonacci1729
tiller runs without restarts. once the helm command executed ( helm install alpine ) the tiller pod it restarts and goes in to crashloopbackoff  
`kubectl get pods -o wide --namespace=kube-system`

`NAME                            READY     STATUS    RESTARTS   AGE       IP           NODE`
`tiller-deploy-500364655-tevmd   1/1       Running   0          5h        172.17.0.6   127.0.0.1`


Is it required to run tiller in helm namespace?

**Comment by MahipalRao** [comment]
This looks like reproducible in other environments too. I had one more setup and the result is same.
Procedure is simple, build kubernetes with command  
`hack/local-up-cluster.sh`
Helm is also same way. 
`make bootstrap build`
`HELM_HOST=localhost:44134 bin/helm init`
The result is 
_machine-desktop:~/go/src/k8s.io/helm$ HELM_HOST=localhost:44134 bin/helm list
2016/09/19 00:11:13 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:44134: getsockopt: connection refused"; Reconnecting to "localhost:44134"
2016/09/19 00:11:15 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:44134: getsockopt: connection refused"; Reconnecting to "localhost:44134"_

FWIW installed socat. 
tiller is getting deployed in kube-system namespace.
@technosophos: tried to use namespace option from 727 issue It did not allow to use that option.
> Tiller can be installed into default, but you have to use the -n -s flags: helm init -n default -s

What else can be done? tried with iptables ( disabling/enabling etc ). result is not different.
appreciate any help.

**Comment by sindhuragarapati** [comment]
I am facing a similar issue. I am getting the following error on executing helm install docs/examples/alpine. Any hint about what is going wrong would be great.

 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp :60185: connectex: The requested address is not valid in its context."; Reconnecting to ":60185"

**Comment by chrislovecnm** [comment]
We getting any traction on this? I think we are having the same problem with kubesolo.

**Comment by chrislovecnm** [comment]
cc @jroberts235

**Comment by technosophos** [comment]
@MahipalRao Can you run Tiller as a stand-alone binary?

```
$ tiller
```

Then you should be able to do `HELM_HOST=:44134 helm version` and see both Tiller and Helm.

I'm trying to figure out whether this is something with the gRPC client in Helm, or if it is an issue connecting through Kubernetes's API server.

Also, which version of Kubernetes are you using?

Since there are a few people commenting on this ticket, but I can't tell what exactly their conditions are, let me explain how the Helm tunneling works:

- Helm reads cluster info out of your Kube config, so by default it will use the API server it finds there
- If no host is set via $HELM_HOST or --host, it will tunnel through the API server to a tiller pod in the namespace `kube-system`
- If host _is_ set, it will attempt to directly contact the host at the given IP/port, and it will use raw gRPC.

So when you run `tiller` in the foreground (as I suggested above), you can at least remove the tunneling layer from the equation. That'll help us find whether it's related to the tunnel or the client lib.

**Comment by MahipalRao** [comment]
@technosophos  I did start tiller stand-alone. Sorry for the delay. Out put of `HELM_HOST=:44134 helm version` is 
`Client: &version.Version{SemVer:"v2.0.0-alpha.4", GitCommit:"2d449d3eb00bb7930436901fa657f05bfd57bf5c", GitTreeState:"dirty"}`
`Server: &version.Version{SemVer:"v2.0.0-alpha.4", GitCommit:"2d449d3eb00bb7930436901fa657f05bfd57bf5c", GitTreeState:"dirty"}`

And `helm list` works fine. 
If I helm init and  set HELM_HOST=<IP of Tiller> then it tries to create tunnel over ssl and tiller pod restarts. 
Kubernetes version is latest git pull v1.5.0-alpha

**Comment by technosophos** [comment]
Okay, I am trying to re-create this problem on an Ubuntu 16.04 box.

Here's what I've done so far:

- Install using the instructions here (and the apt repo): http://kubernetes.io/docs/getting-started-guides/kubeadm/
- Get Helm source and rebuild from scratch with `make bootstrap build`

So far, running Tiller in the foreground works fine. Next up, I'm going to try to connect to an in-cluster version.

**Comment by technosophos** [comment]
Alright, I'm having trouble reproducing with `kubeadm` for Kubernetes 1.4.0 on Ubuntu 16.04. So something must be different between the `hack/local...` scripts and the kubeadm process.

@MahipalRao Can you please try this for me, and then send me the error output?

```
$ hack/local-up-cluster.sh
$ cd $HELM_SRC
$ make bootstrap build
$ export HELM_HOST="" # Or just make sure this isn't set.
$ bin/helm init
```

I'm sure we're struggling with some early piece of the tunnel connection. I just can't figure out what that is.

**Comment by MahipalRao** [comment]
@technosophos 
`$bin/helm in` works fine and creates tiller pod successfully. But the `$bin/helm list` throws the error and tiller pod restarts. 
`bin/helm list` output
`2016/09/29 23:31:51 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing`

**Comment by adamreese** [comment]
When trying to replicate this issue I got a scheduler error.  Kubernetes was not detecting any nodes.  Is this the same issue you are experiencing?

```
% kubectl -n kube-system describe pod tiller-deploy-637859184-pv2ku
Name:		tiller-deploy-637859184-pv2ku
Namespace:	kube-system
Node:		/
Labels:		app=helm
		name=tiller
		pod-template-hash=637859184
Status:		Pending
IP:
Controllers:	ReplicaSet/tiller-deploy-637859184
Containers:
  tiller:
    Image:	gcr.io/kubernetes-helm/tiller:v2.0.0-alpha.5
    Port:	44134/TCP
    Liveness:	http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:	http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-1510b (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  PodScheduled 	False
Volumes:
  default-token-1510b:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-1510b
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  24s		9s		6	{default-scheduler }			Warning		FailedScheduling	no nodes available to schedule pods
```

**Comment by MahipalRao** [comment]
@adamreese  Scheduler is not allowed to launch any pods on master by default. If you nodes added then it will launch on nodes. 
Can you try 
`kubectl taint nodes --all dedicated- `
And then launch tiller.

**Comment by adamreese** [comment]
@MahipalRao TIL

**Comment by technosophos** [comment]
Any news on this one?

**Comment by technosophos** [comment]
The trail seems to have gone cold on this one. If anyone can reproduce this on Helm 2.1.0 or later, please update this ticket.

**Comment by SuperNami** [comment]
Maybe this is related in some way? https://github.com/kubernetes/helm/issues/1799

**Comment by technosophos** [comment]
Alright, since this one has gone dormant, I am marking it closed. Feel free to re-open if this problem still persists on 2.1.

**Comment by WillemMali** [comment]
I can partially reproduce this with helm 2.6.1, but the error is transient. Tiller startup time has gone up from ~20s to ~1m since previous versions, and during this waiting time the dashboard reports ` no nodes available to schedule pods `.

**Comment by vhosakot** [comment]
I saw the `Error: transport is closing` error too when I ran `helm install`, and after doing `rm -rf ~/.helm`, the error was not seen anymore. Guess deleting the helm cache (`rm -rf ~/.helm`) may resolve the error.
