### ISSUE TITLE
Add function for generating the name of the chart with the release name

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1186]
Currently most charts are using the `fullname` template (https://github.com/kubernetes/charts/pull/48/files#r77064762) to generate a 24-character names for K8S resources using the release name and name of the chart.

This seems like a good thing to standardise on, and Helm could provide a template function to generate this, or inject a value (in `.Release` or `.Chart`?)

Another issue with the template, is that template names are global, so charts should really be namespacing template names (e.g. `mariadb.fullname` rather than just `fullname`), otherwise there will be conflicts.

**Comment by technosophos** [comment]
Good idea. Do you have a suggestion for what the function would look like? Would we allow paramterization (`{{fullname .Release.Name}}`) or do it in a consistently automatic way with no params:`{{fullname}}`?

**Comment by prydonius** [comment]
I think the parameter it should accept is the override (i.e. the `.Values.nameOverride` in `{{- $name := default "prometheus" .Values.nameOverride -}}`). `{{.Release.Name}}-{{someName}}` should be the standard we impose, so I don't think `.Release.Name` should be parameterised.

**Comment by mgoodness** [comment]
I like the idea of replacing the `fullname` template with a function. Might want to discuss its format before implementing, though. As I mentioned in the [Charts best-practices issue](https://github.com/kubernetes/charts/issues/44), I've taken to reversing the order in which the application & release names appear.

**Comment by Rio** [comment]
Is there a way to override a sub chart's `fullname` function. I'm having conflicts with the mysql sub chart. In my `fullname` definition I've set chart name first like `mysql-myrelease` instead of `myrelease-mysql`. But sometimes it uses the sub chart's `fullname` function for the entire release and sometimes my parent chart's function. Any way to lock this?

**Comment by sstarcher** [comment]
My personal usage of fullname deviates slightly.  Instead of 

`.Release.name -  .Chart.Name` when the name of the release and the chart are the same I drop the name.

Chart - sensu
Release - sensu

The defaults would produce a service named `sensu-sensu` and in my case I produce `sensu`

**Comment by sander-su** [comment]
Can we at least create a values.fullnameOverride or something?
There are charts which would be deployed multiple times in a namespace and others once per cluster or once per namespace.
I now have prometheus-prometheus-server... adding the releaseName adds no value in this case, worse, it makes it less readable.

**Comment by sstarcher** [comment]
I have been using the following to handle @sander-su use case of dropping the Release name when it matches the chart.

```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if ne .Chart.Name .Release.Name -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s" $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

**Comment by mgoodness** [comment]
I've started adding @sstarcher's conditional to internal charts as well as community ones I maintain.

**Comment by previa** [comment]
Sorry,  I am new to golang and helm. I didn't understand the meaning of the following code.

{{- $name := default .Chart.Name .Values.nameOverride -}}
=> is this mean $name would be .Chart.Name by default and allow to be overwritten by .Values.name ?
{{- if ne .Chart.Name .Release.Name -}}
=> Is this mean  if .Chat.Name and .Release.Name is not equal ?

I have spend some time on document especially template doc (https://golang.org/pkg/text/template/)  but in vain. 

Thanks for any hint about this.

**Comment by prydonius** [comment]
@previa yes, both of your assumptions are correct

**Comment by bacongobbler** [comment]
We should definitely add @sstarcher's suggestion to `helm create` so that this becomes the de-facto for charts moving forward. If anyone wants to take a crack at a PR, please go for it! This is a fantastic feature to get your feet wet with helm. :)

**Comment by burdiyan** [comment]
I would suggest instead of strict equality check do something like:

```
{{- define "foobar.fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

So if my chart is called `foobar` and I release without providing the name: the full name would be `release-chart`.

But if I release with the name of `my-foo` or `foo` or anything with the word of `foo`, the full name would be the name of the release.

It seems unlikely people would specify release name manually without mentioning the actual application they are releasing. And in this case repeating the chart name would be redundant.

WDYT?

**Comment by mgoodness** [comment]
@burdiyan's proposal seems like a reasonable improvement on @sstarcher's original.

👍

**Comment by unguiculus** [comment]
Additionally, I'd add an option to override the fullname as the common chart does. See https://github.com/kubernetes/charts/blob/master/incubator/common/templates/_fullname.tpl#L20-L29.

**Comment by sstarcher** [comment]
You would set nameOverride.  I believe name should not be changed as it's suppose to be the chart name.

**Comment by ericfrancis** [comment]
@sstarcher gotcha. Thanks!
