### ISSUE TITLE
Evaluate commands/subcommands for consistency (Last Call for 2.0.0!)

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1196]
Once we exit Alpha.5, we won't be modifying any existing command names. This is a last call to suggest any changes to the commands/subcommands.

We're shooting for:

- consistency of patterns (e.g. `helm NOUN VERB` and `helm VERB`)
- terminology that matches _other package managers_ (not necessarily kubectl)
- low barrier of entry for commonly used things
- strategy for when to alias (e.g. should `helm search` be an alias to `helm charts search`
- and any related flags that should be changed to be consistent with the above

(This ticket is specifically about naming commands, not the functionality of various commands.)

/cc @prydonius @michelleN @viglesiasce @adamreese @migmartri @jackfrancis

**Comment by philips** [comment]
I have some thoughts on this issue: https://github.com/kubernetes/helm/issues/1174

**Comment by philips** [comment]
@technosophos I am curious about the `noun verb` pattern. That is opposite of kubectl, why?

**Comment by viglesiasce** [comment]
I put a sample draft of `noun verb` over in https://github.com/kubernetes/helm/issues/1174#issuecomment-248140981

**Comment by technosophos** [comment]
One that has been asked for is `helm update` -> `helm repo update`.
