### ISSUE TITLE
feat: Version not required for install, update commands

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1198]
Currently, to install a chart, a user must supply the chart and version:

```
$ helm install charts/nginx-1.2.3
```

Likewise with other commands like `helm upgrade`

To better follow the conventions of other package managers, version should not be required.

```
$ helm install charts/nginx
# installs latest nginx: nginx-1.2.3
```

Specifying version should be an explicit operation:

```
$ helm install charts/nginx --version 1.2.2
# installs older nginx 1.2.2
```

Additionally, it has been suggested that we bring back the idea of a default repository:

```
$ helm repo default charts
Repo 'charts' is now your default
$ helm install nginx
# installs charts/nginx 1.2.3
```

Analogous changes would be made of `helm upgrade`, too.

**Comment by jackfrancis** [comment]
@technosophos speaking to a default chart repo, do we have analogous commands that resemble the below?:

```
$ helm repo list
stable       https://github.com/kubernetes/charts (default)
incubator    https://github.com/kubernetes/charts/incubator
$ helm repo default
'stable' is the default repo
stable       https://github.com/kubernetes/charts
```

**Comment by technosophos** [comment]
We have a `helm repo list`, but no notion of a default
