### ISSUE TITLE
Either tiller binary is missing from release alpha4 release, or cask config is wrong.

### ISSUE THREAD

**Issue by numbsafari** [kubernetes/helm#1200]
The current binary for the [2.0.0-alpha4 release](https://github.com/kubernetes/helm/releases) doesn't contain the `tiller` binary, though the previous `-alpha3` release did.

Unfortunately, the `cask` configuration [still references it](https://github.com/caskroom/homebrew-cask/blob/c023b005d66d4cdcb3a714f7f803833bdd86eff1/Casks/helm.rb#L13).

This results in the following:

```
16:20 $ brew cask install helm
==> Downloading https://github.com/kubernetes/helm/releases/download/v2.0.0-alpha.4/helm-v2.0.0-alpha.4-darwin-amd64.tar.gz
Already downloaded: /Users/.../Library/Caches/Homebrew/Cask/helm--2.0.0-alpha.4.tar.gz
==> Verifying checksum for Cask helm
==> Symlinking Binary 'helm' to '/usr/local/bin/helm'
Error: It seems the symlink source is not there: '/usr/local/Caskroom/helm/2.0.0-alpha.4/darwin-amd64/tiller'
```
and
```
16:29 $ helm
-bash: helm: command not found
```

I'm not sure which of the two is incorrect, so I figured I'd open a ticket here.

**Comment by sgoings** [comment]
I don't believe it's necessary to ship the tiller binary since it is installed via a Kubernetes Deployment (which pulls an image out of a Docker registry): https://github.com/kubernetes/helm/blob/master/cmd/helm/installer/install.go#L80

I'm thinking that line of the cask just needs to be removed. Am I correct @adamreese?

**Comment by numbsafari** [comment]
I removed that line locally using `brew cask edit helm` and then `brew cask install helm` and it seems to have resolved the problem so far.

**Comment by technosophos** [comment]
Did you happen to file an upstream issue for that cask? The core team here does not maintain the brew formula. This looks like the last issue on that: https://github.com/caskroom/homebrew-cask/pull/24416

Thanks!

**Comment by numbsafari** [comment]
Thanks for the confirmation @technosophos. I opened a ticket over in cask-land and will try to submit a quick PR.

**Comment by technosophos** [comment]
Thanks!
