### ISSUE TITLE
Checksum for the binary releases

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/helm#1214]
Hi all

I am building a docker for helm, and it is our policy to validate the binary against a SHA.  Can we please include that in the releases that are cut?

Thanks

**Comment by technosophos** [comment]
Do you need a signature too, or just a checksum?

**Comment by chrislovecnm** [comment]
SHA256 would be AWESOME

**Comment by technosophos** [comment]
Cool. So I think that'd just be a matter of adding something like `shasum -a 256 bin/*` to the circle.yaml script. /cc @adamreese

**Comment by chrislovecnm** [comment]
@technosophos did we get this with the latest alpha?

**Comment by chrislovecnm** [comment]
This needs to be on the release page tab ... Can we reopen?

**Comment by r3lik** [comment]
Any plans to add a checksum to the downloads/releases page? This is the only software i've come across recently that doesn't provide it.

**Comment by r3lik** [comment]
please re-open

**Comment by bacongobbler** [comment]
Checksums are available, they're just not on the releases page. Tack on the .sha256 extension on anything you want. E.g. for

https://storage.googleapis.com/kubernetes-helm/helm-v2.9.0-rc5-darwin-amd64.tar.gz

Use

https://storage.googleapis.com/kubernetes-helm/helm-v2.9.0-rc5-darwin-amd64.tar.gz.sha256

We can re-opening this and make a note of it in the release notes going forward.

**Comment by bacongobbler** [comment]
Actually, we already implemented this starting with the [v2.8.0 release notes](https://github.com/kubernetes/helm/releases/tag/v2.8.0). We'll just have to make sure to continue adding those in for future releases. I've gone ahead and edited the release notes for v2.8.2 and v2.9.0-rc5 as we generally use the last patch release's release notes as a template for the next release.
