### ISSUE TITLE
make `list --all --long` the default

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/helm#1215]
I really wish `helm list` would default to `--all --long`.
Currently `helm list` is a bit useless imho:

```
$ helm list
$ helm list --all
old-newt
$ helm list --all --long
NAME    	VERSION	UPDATED                 	STATUS 	CHART      
old-newt	1      	Thu Sep 22 21:50:21 2016	DELETED	spark-0.1.0
```

**Comment by viglesiasce** [comment]
I'm all for this but with a slight tweak. I would have the default be `list --long`.

**Comment by sebgoa** [comment]
fine with that tweak

**Comment by technosophos** [comment]
And the name of the flag to generate the UNIX-friendly listing would be `--short` or `-q,--quiet`?

(The original reason for the minimal output was to match normal UNIX behavior like `ls`, but since then most of the other commands have opted for human-friendly over shell-script-friendly)
