### ISSUE TITLE
Releases and Namespaces

### ISSUE THREAD

**Issue by danny-waite** [kubernetes/helm#1219]
I'm not sure if this is a bug or a feature request however:

I have a chart, named `postgresql` and multiple namespaces such as `dev` `qa` `staging` and hence I want to install this chart in each of these namespaces.  Currently I'm using `{{ .Release.Name }}` in the manifests to set things like the `Deployment` and `Service` name which seems quite clean and logical and works until you of course try to install the chart into a second namespace.

The error is:
`Error: a release named \"postgresql\" already exists`

I could use `--values` to inject the required values (which I am currently using for other things) but I guess my question is, should a release name be unique to a namespace or global as it seems to be now? TIA

**Comment by technosophos** [comment]
You cannot name two releases the same thing. This is by design. Release name has to be cluster-unique.

Typically, we don't suggest using the chart name as the release name for that reason. The usual suggestion is to name your release a unique name for each installation. So it might be `helm install --name postgres-prod ...` vs `helm install --name postgres-stage ...`. You can also check out the `--name-template` flag.

**Comment by danny-waite** [comment]
thanks @technosophos yeah I expected as much, yeah I've played around with name templates too.  I've just implemented something similar to your suggestion, though I'm having to do some truncation due to the 14 character limit, any plans to change that?

**Comment by technosophos** [comment]
Ugh, I hate that limit. I would love to take it out. It's because the name field is limited by Kubernetes to 24 characters (for DNS), and we reserved 10 characters for appending data in generated resources. I'm still trying to figure out a way to out-maneuver that part of the system.

**Comment by technosophos** [comment]
So we discussed removing the 14 character limit, but decided that we'd not do that in time for the 2.0.0 release. A number of proposals are circulating about how we can do naming better, while still respecting the 24 character DNS limit. So I'm going to mark this one as closed and let the proposal issues be the driver for determining the name limits.

**Comment by danny-waite** [comment]
thanks for the progress @technosophos progress at least 👍
