### ISSUE TITLE
`helm version` returns error (built from HEAD)

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/helm#1223]
**The latest release:**
```console
$ helm version 
v2.0.0-alpha.4
```

**Built from head:**
```console
$ helm version 
Client: &version.Version{SemVer:"v2.0.0-alpha.4", GitCommit:"dbb84a1b9e57d14b816ff9c70c82c5232a8d0d89", GitTreeState:"dirty"}
Error: rpc error: code = 12 desc = unknown method GetVersion
```

**Comment by technosophos** [comment]
Can you use kubectl to see what version of Tiller you are using? I suspect that the installed version of Tiller might be older, and missing the GetVersion command that was recently added (Alpha.4)
