### ISSUE TITLE
canary `helm list` hangs

### ISSUE THREAD

**Issue by rimusz** [kubernetes/helm#1231]
running `helm list` just hangs and does not move forward

**Comment by technosophos** [comment]
What version of Kubernetes?

**Comment by rimusz** [comment]
tried on v1.3.7 and v1.4.0, hangs on both for me

**Comment by rimusz** [comment]
apologies I meant `helm list`, updated the issue :)

**Comment by fibonacci1729** [comment]
@rimusz, can you capture the logs from the tiller pod when it hangs?
```kubectl logs -f ${TILLER_ID} --namespace=kube-system```

**Comment by rimusz** [comment]
weird cannot reproduce it on the local install anymore, will check GKE later one

**Comment by rimusz** [comment]
GKE is fine with canary too, so will close this one
