### ISSUE TITLE
any plan on supporting using a centralized DM managing multiple K8s clusters?

### ISSUE THREAD

**Issue by xinzhangcmu** [kubernetes/helm#124]
My use case is as follows:

I am building a public PaaS with K8s, on which users can create and manage K8s clusters of their own in our platform. I am also thinking of using DM to let users create their apps. There are two ways of doing that:
- deploy a DM instance (all its components) onto each of the users K8s clusters, and passing the necessary K8s master info and access credentials to the resourcifier. 
- Deploy a single DM onto our own infrastructure (also running on K8s), which manages all users clusters.

The first proposal matches well with the current DM model, however I am concerned about the additional resource conception with these addons. For the second approach to work, I will probably have to change the current DM model quite a bit:
- the resourcifier can still use the same `kubectl` binary
- however, for each DM operation (I will be using it REST API instead of the `dm` tool), I need to be able to pass in the K8s master info along with each request, instead of binding that info with resourcifier during as flag values its startup.

I wonder if there is any plan to support that, or any suggestions on how to achieve this without diverging much from this upstream repo?

Thanks!

**Comment by jackgr** [comment]
Great timing, @xinzhangcmu.

We just met today with friends from another company about supporting DM for Ubernetes.

This feels like an issue that needs some thoughtful design discussion.

I think we need to learn more about Ubernetes. Where does the code that does the scheduling run? Wherever it runs, we might want to think about running an Uber DM there, alongside it. That DM might delegate deployment to a DM running in each cluster.

**Comment by xinzhangcmu** [comment]
Thanks @jackgr ! We are exactly doing Ubernetes. Just to provide a sample data point:

- We are running the control panel in a standalone Kubernetes (call it the master K8s)

- On that master K8s, we have our own components (running as pods and rc) that provide UI and API to help end users create and manage "user Kubernetes". This is "Where does the code that does the scheduling run? " in our case. 

- We have been developing our own *provisioner* that runs as a centralized instance on the master K8s to deploy apps on user Kubernete clusters. It takes config from users, translates them, and directly calls to the user Kubernetes master APIs for instantiation.

- Instead of delegating to a DM running in each user's cluster, what about letting the Uber DM directly talks to the master APIs of each cluster? In this way we won't have to consume additional resources for running DM in users clusters

**Comment by thomastaylor312** [comment]
This issue hasn't been active for more than a year, so we are going to close it. Should there be any more discussion, feel free to re-open this issue
