### ISSUE TITLE
Server is too old to know its version error

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/helm#1240]
Compiled the latest helm, then `helm init` on minikube.

then got:

```
$ helm version
Client: &version.Version{SemVer:"v2.0.0-alpha.4", GitCommit:"3437e5d6e5ed6f2d21edb6479e4670106a3da5fb", GitTreeState:"dirty"}
Error: server is too old to know its version
sebair: bin (master)$ kubectl logs tiller-deploy-1979772362-t4je0 --namespace=kube-system
Tiller is running on :44134
Tiller probes server is running on :44135
Storage driver is ConfigMap
```

**Comment by technosophos** [comment]
The reason this is happening is because `master` has a new API call that the last Tiller server did not. Doing a `helm init` will install Tiller Alpha.4.

If you'd like to run the `:canary` Tiller instance, you can just use the `-i $IMAGE` flag on `helm install`.

**Comment by technosophos** [comment]
This is fixed in Alpha.5
