### ISSUE TITLE
helm upgrade fails on "Looks like there are no changes..."

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/helm#1259]
When I have a chart with one Deployment and one Service and change the Deployment's template only, then helm upgrade fails:

```
/home/andrej/go/src/k8s.io/helm/bin/helm --debug upgrade --host localhost:44134  jittery-chimp   http://localhost/charts/users-0.3.0.tgz
Server: "localhost:44134"
Fetched http://localhost/charts/users-0.3.0.tgz to /tmp/users/users-0.3.0.tgz
Error: UPGRADE FAILED: Looks like there are no changes for users
```

Adding some simple debugging in pkg/kube/client.go:updateResource reveals that the original and updated Service are compared. Because they are equal, an error is returned.

Moreover, in another invocation of updateResource, the Service and Deployment are compared, which does not make much sense ;-)

I'm on v2.0.0-alpha.4.

**Comment by technosophos** [comment]
I believe that `master` already has a fix in for these. If you run off the canary build, do you still see these issues?

**Comment by andrejvanderzee** [comment]
I can confirm that this is solved in `master` branch.

Close.
