### ISSUE TITLE
fix: helm lint erroneously identifies NOTES.txt as an invalid extension

### ISSUE THREAD

**Issue by jfelten** [kubernetes/helm#1272]
See output below: 

helm lint ./
==> Linting ./
[ERROR] templates/NOTES.txt: file extension '.txt' not valid. Valid extensions are .yaml or .tpl

**Comment by adamreese** [comment]
This was fixed for the next release https://github.com/kubernetes/helm/issues/1161

**Comment by michelleN** [comment]
Going to close this issue since it has been resolved. Thanks @jfelten. Let us know if you see this again.
