### ISSUE TITLE
Stale docs: helm search

### ISSUE THREAD

**Issue by krancour** [kubernetes/helm#1273]
> When you first install Helm, it is preconfigured to talk to the official
Kubernetes charts repository. This repository contains a number of
carefully currated and maintained charts. This chart repository is named
`stable` by default.

> You can see which charts are available by running `helm search`:

> ```
$ helm search
stable/drupal
stable/jenkins
stable/mariadb
...
```

> With no filter, `helm search` shows you all of the available charts. You
can narrow down your results by searching with a filter:

> ```
$ helm search mysql
stable/mysql
stable/mariadb
```

Two issues with the above:

1. The default repository's name seems to have changed to `kubernetes-charts`

1. `helm search` without a filter yields an error:

```
$ helm search
Error: This command needs at least one argument (search string)
```

**Comment by technosophos** [comment]
What version of Helm are you running?

The name of the repo was just recently changed from `kubernetes-charts` to `stable`, and the output of the search command was also just recently changed. So that documentation is up to date with master, but _way_ ahead of Alpha.4.

**Comment by krancour** [comment]
Ahhh. I am on Alpha.4 and incorrectly assumed it to be closer to master than it is.
