### ISSUE TITLE
bug: chart dependencies requirements.yaml mentioned in developer.md do not work

### ISSUE THREAD

**Issue by jfelten** [kubernetes/helm#1277]
helm version
v2.0.0-alpha.4

Is requirements.yaml functionality present?

Managing Dependencies with requirements.yaml does not work.  Dependent charts in this file are not loaded. 

The commands: helm dependency update and helm dep up are not present:

helm dependency update
Error: unknown command "dependency" for "helm"
Run 'helm --help' for usage.

helm dep up
Error: unknown command "dep" for "helm"

Adding dependencies through the chart subdirectory does work.

**Comment by technosophos** [comment]
These are in master, but not in a released version. You can use the canary build of Helm if you'd like to try them out: https://github.com/kubernetes/helm/blob/master/docs/install.md#from-canary-builds

The `Alpha.5` release is probably going to be released on Friday.

**Comment by jfelten** [comment]
Thanks - Are there any open discussions on dependency management?  I have some questions about adding hooks that depend on completion of a dependent chart.  For example I would like to import jobs once a jenkins subchart is ready.

**Comment by jfelten** [comment]
I was unsuccessful using the canary version as well.  Can you add a working example requirements.yaml to the documentation?

Here is what I tried:
dependencies:
  - name: jenkins-0.1.0.tgz
    version: 0.1.0
    repository: http://storage.googleapis.com/kubernetes-charts

**Comment by technosophos** [comment]
Unsuccessful in what way? Can you tell me what happened? I'll take a look at the docs and see what we can do.

**Comment by technosophos** [comment]
Okay, trying to replicate this. Is this what you got?

```
⇒  helm dep up
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://localhost:8879/charts):
       	Get http://localhost:8879/charts/index.yaml: dial tcp [::1]:8879: getsockopt: connection refused
WARNING: Deprecated index file format. Try 'helm repo update'
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "tscharts" chart repository
Update Complete. ⎈Happy Helming!⎈
WARNING: Deprecated index file format. Try 'helm repo update'
Saving 1 charts
Downloading jenkins-0.1.0.tgz from repo http://storage.googleapis.com/kubernetes-charts
WARNING: chart jenkins-0.1.0.tgz not found in http://storage.googleapis.com/kubernetes-charts (skipped)%
```

**Comment by technosophos** [comment]
Ah, yes -- the docs are wrong. `name:` should be `jenkins`, not `jenkins-0.1.0`.

I also found a bug in the URL fetching, and am fixing that now.
