### ISSUE TITLE
bug: client version is incompatible

### ISSUE THREAD

**Issue by tallpauley** [kubernetes/helm#1283]
Downloaded helm canary client for OSX El Capitan and placed in PATH:
http://storage.googleapis.com/kubernetes-helm/helm-canary-darwin-amd64.tar.gz

Init w/ canary tiller image
```
$ helm init -i "gcr.io/kubernetes-helm/tiller:canary"
$ kubectl --namespace=kube-system get pods | grep tiller
tiller-deploy-610593871-5nmue                                    1/1       Running   0          47s
$ helm version
Client: &version.Version{SemVer:"test-release", GitCommit:"bcda0b8738c598134d5a76e36c15c989f4545683", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"test-release", GitCommit:"bcda0b8738c598134d5a76e36c15c989f4545683", GitTreeState:"dirty"}
```

Helm list
```
$ helm list
Error: client version is incompatible
```

**Comment by adamreese** [comment]
The `test-release` tag was cached in CI for some reason.  I have manually deleted the tag out of CircleCI.  New build is running now.

**Comment by adamreese** [comment]
Tested last canary.  Let me know if you have any other issues.  Thanks!!!

**Comment by tallpauley** [comment]
Thanks! It worked when I followed the same process I did before, but replaced my client binary with the latest.
