### ISSUE TITLE
Unable to helm repo update: "no API version specified"

### ISSUE THREAD

**Issue by tallpauley** [kubernetes/helm#1285]
I'm unable to do a `helm repo update`:
```$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "stable" chart repository (http://storage.googleapis.com/kubernetes-charts):
	no API version specified
Update Complete. ⎈ Happy Helming!⎈```

So that I get this when I do `helm search`:
```
helm search
WARNING: Repo "/Users/cmpauley/.helm/repository/cache/stable-index.yaml" is corrupt or missing. Try 'helm update':
	open /Users/cmpauley/.helm/repository/cache/stable-index.yaml: no such file or directory
WARNING: Repo "/Users/cmpauley/.helm/repository/cache/local-index.yaml" is corrupt or missing. Try 'helm update':
	open /Users/cmpauley/.helm/repository/cache/local-index.yaml: no such file or directory
```

Am I doing something wrong? ~~Also, it should say "Try helm repo update" not "helm update"~~ (looks like this was addressed)

My version:
```
$ helm version
Client: &version.Version{SemVer:"v2.0.0-alpha.4", GitCommit:"bcda0b8738c598134d5a76e36c15c989f4545683", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"v2.0.0-alpha.4", GitCommit:"bcda0b8738c598134d5a76e36c15c989f4545683", GitTreeState:"dirty"}
```

**Comment by technosophos** [comment]
I merged the fix for the above.
https://github.com/kubernetes/helm/pull/1282

So the latest canary ought to have that fixed now.

**Comment by tallpauley** [comment]
#1282 fixed it for me, thanks!
