### ISSUE TITLE
helm canary should pull canary tiller image

### ISSUE THREAD

**Issue by tallpauley** [kubernetes/helm#1291]
It would be nice if `helm init` w/ a canary client binary would grab the corresponding tiller image, instead of having to specify the image `helm init -i gcr.io/kubernetes-helm/tiller:canary`. Could be done by tagging all the images w/ the git hashes, and having canary deploy tiller image by hash.

**Comment by technosophos** [comment]
@adamreese should we consider this "closed" by #1363? Or were you planning to implement something more here?
