### ISSUE TITLE
add binary downloads for alpha 5 or later

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#1306]
it looks like the [alpha 5](https://github.com/kubernetes/helm/releases) release didn't come with the nice binary downloads from [alpha 4](https://github.com/kubernetes/helm/releases/tag/v2.0.0-alpha.4), any chance we can bring them back?

**Comment by rimusz** [comment]
hey guys, binaries would be nice to have :)

**Comment by chrislovecnm** [comment]
:facepalm ... binaries and checksum :rimshot ... arg

Here is me compiling a release.  Thanks for the work btw!

**Comment by adamreese** [comment]
They are uploaded to GCE, we'll get that on the release page.

Example: http://storage.googleapis.com/kubernetes-helm/helm-v2.0.0-alpha.5-darwin-amd64.tar.gz

**Comment by technosophos** [comment]
Updated the release page. Also have a PR in to update these on the README.
