### ISSUE TITLE
make bootstrap build no worky

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/helm#1310]
I assume this is a glide problem, but I do not really know.

```console
# clove @ clove-mbp in ~/Workspace/src/k8s.io/helm on git:master o [19:15:53] C:1
$ make bootstrap build
glide install --strip-vendor
[ERROR]	--strip-vendor cannot be used without --strip-vcs
make: *** [bootstrap] Error 1
```

Also, you are forced to have your source code in k8s.io directory.  I know that is proper go'ish path, but it at least needs to be documented.

**Comment by chrislovecnm** [comment]
Adding `--strip-vcs` seems to run

**Comment by adamreese** [comment]
your glide needs some updating.  `--strip-vcs` was depreciated.

https://github.com/Masterminds/glide/releases

**Comment by chrislovecnm** [comment]
@adamreese then you have a problem with your docs.  You list a min version of Glide 0.10.2 or later.  While I am running:

```console
$ glide -v
glide version 0.11.1
```

So what version is required?
