### ISSUE TITLE
helm init error

### ISSUE THREAD

**Issue by gl328518397** [kubernetes/helm#1329]
error installing: Get https://192.168.99.100:8443/api: dial tcp 192.168.99.100:8443: getsockopt: connection refused

**Comment by technosophos** [comment]
Is this Helm 2.0.0-Alpha.5?

What kind of Kubernetes cluster? GKE? Minikube?

**Comment by gl328518397** [comment]
thank you ,I have success by change kube config to my own master server .thanks .
