### ISSUE TITLE
error parsing YAML with long lines (e.g. ConfigMap / Secrets with big entries): bufio.Scanner: token too long

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#1330]
if your chart has a YAML file with a long line in it (e.g. a ConfigMap/Secret with an entry > 50K) then you get this error:
```
Error: release kissed-butterf failed: bufio.Scanner: token too long
```

this looks to be fixed in kubernetes 1.4.1
https://github.com/kubernetes/kubernetes/pull/30772

so I guess this will be resolved if we upgrade the glide.yaml to use the latest 1.4.1 of kubernetes?
https://github.com/kubernetes/helm/blob/master/glide.yaml#L25

**Comment by jstrachan** [comment]
here's a sample test case that should demonstrate the issue:
[console-2.2-SNAPSHOT-helm.tar.gz](https://github.com/kubernetes/helm/files/521611/console-2.2-SNAPSHOT-helm.tar.gz)

I'll hopefully have a URL version of this soon, next time I re-release our charts

**Comment by technosophos** [comment]
Yup, you were right. Updating to a newer version of k8s seems to have fixed it (or, at least, I can get your demo chart to make it past `helm install`.)

**Comment by jstrachan** [comment]
@technosophos many thanks!
