### ISSUE TITLE
charts-subdirectory when doing helm dependencies update is not created

### ISSUE THREAD

**Issue by triplem** [kubernetes/helm#1342]
If I execute the above mentioned `helm dependencies update` in a chart, which contains a valid requirements.yaml, but without a chart-subdirectory, I do get an error (no such file or directory). If I put an invalid file in this directory (so that it is later stored in git), I do get an error as well, that this file is invalid (the file was called .do-not-delete). 

Is this on purpose?

**Comment by technosophos** [comment]
That was by design, but I could probably make it ignore files that start with `.` and `_`. I suppose calling a `mkdir` call would also be fine.
