### ISSUE TITLE
helm commands error with "socat not found"

### ISSUE THREAD

**Issue by ligc** [kubernetes/helm#1371]
I am using the latest helm v2.0.0-alpha.5 in my Ubuntu 16.04 Kubernetes cluster, the installation went well, I downloaded the binary and installed helm using helm init without any problem. But when I tried to run any helm command, it returns with error "socat not found"

```
root@c910f04x19k07:~/linux-amd64# ./helm version
Client: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"a324146945c01a1e2dd7eaf23caf0e55fabfd3d2", GitTreeState:"clean"}
E1014 02:26:30.145559   16134 portforward.go:329] an error occurred forwarding 40276 -> 44134: error forwarding port 44134 to pod tiller-deploy-2117266891-e4lev_kube-system, uid : unable to do port forwarding: socat not found.
2016/10/14 02:26:30 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: rpc error: code = 13 desc = transport is closing
root@c910f04x19k07:~/linux-amd64# ./helm list
E1014 02:26:32.885226   16143 portforward.go:329] an error occurred forwarding 37008 -> 44134: error forwarding port 44134 to pod tiller-deploy-2117266891-e4lev_kube-system, uid : unable to do port forwarding: socat not found.
2016/10/14 02:26:32 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
root@c910f04x19k07:~/linux-amd64# 
```
The socat is installed on all the Kubernetes nodes:

```
root@c910f04x19k07:~/linux-amd64# kubectl get nodes
NAME                                STATUS    AGE
c910f04x19k08.pok.stglabs.ibm.com   Ready     23h
c910f04x19k09.pok.stglabs.ibm.com   Ready     23h
root@c910f04x19k07:~/linux-amd64# which socat
/usr/bin/socat
root@c910f04x19k07:~/linux-amd64# 

root@c910f04x19k08:~# which socat
/usr/bin/socat
root@c910f04x19k08:~# 

root@c910f04x19k09:~# which socat
/usr/bin/socat
root@c910f04x19k09:~# 

```

https://github.com/kubernetes/helm/issues/966 and https://github.com/kubernetes/helm/issues/1183 do not seem to help.

Any suggestion on what might be going wrong? Thanks.

**Comment by technosophos** [comment]
How'd you install Kubernetes? And which version of Kubernetes? I'll see if I can reproduce.

**Comment by ligc** [comment]
@technosophos  Thanks for the comments. I think I figured it out, I am running Kubernetes on Mesos, the kubernetes and mesos components are running in docker containers, the socat was not installed on the mesos-agent docker, after I installed the socat in the mesos-agent container, the helm command now works perfectly.   I am closing this issue.

root@c910f04x19k07:~/linux-amd64# ./helm version
Client: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"a324146945c01a1e2dd7eaf23caf0e55fabfd3d2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"4de5c4aa578ed9ca173aff472f00d2167ec59a88", GitTreeState:"dirty"}
root@c910f04x19k07:~/linux-amd64#

**Comment by sstarcher** [comment]
I'm hitting a similar issue.  Kubernetes running on CoreOS not in a docker container.  

```
Fetched stable/jenkins to jenkins-0.1.1.tgz
E1024 16:28:57.637673   40086 portforward.go:329] an error occurred forwarding 56784 -> 44134: error forwarding port 44134 to pod tiller-deploy-2434200834-v3ph3_kube-system, uid : unable to do port forwarding: socat not found.
2016/10/24 16:28:57 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
```

**Comment by sstarcher** [comment]
As pointed out in #966 my issue is I'm not running the kublet in a docker container

**Comment by zmoon111** [comment]
in my case, i did not `yum install -y socat` properly in my kubelet nodes. after installed it, error fixed.

**Comment by hobbytp** [comment]
In my case, I try to use the helm in my minikube, and the minikube I installed by using --vm-driver=none ( I run minikube start - -vm-driver=none in my centos7 VM). After I install helm, I failed to execute command " helm install xxx --name=xxx". The error msg is as below:
```
E0314 11:11:34.846462    9787 portforward.go:331] an error occurred forwarding 44073 -> 44134: error forwarding port 44134 to pod 97d6d90eb835f6e4211ef3fc6e0e168987bf0c961912cf8774a5c8692d905121, uid : unable to do port forwarding: socat not found.
```

**Comment by dullduck** [comment]
yes!run  'yum install -y socat' on every node can resolve this problem.

**Comment by akshayat** [comment]
> In my case, I try to use the helm in my minikube, and the minikube I installed by using --vm-driver=none ( I run minikube start - -vm-driver=none in my centos7 VM). After I install helm, I failed to execute command " helm install xxx --name=xxx". The error msg is as below:
> 
> ```
> E0314 11:11:34.846462    9787 portforward.go:331] an error occurred forwarding 44073 -> 44134: error forwarding port 44134 to pod 97d6d90eb835f6e4211ef3fc6e0e168987bf0c961912cf8774a5c8692d905121, uid : unable to do port forwarding: socat not found.
> ```
> The issue gone after I install socat
> 
> ```
> yum install -y socat
> ```
For ubuntu
`sudo apt-get install socat`

**Comment by AnikHasibul** [comment]
> For ubuntu
sudo apt-get install socat

great! worked for me :sunglasses:

**Comment by derik93** [comment]
> in my case, i did not `yum install -y socat` properly in my kubelet nodes. after installed it, error fixed.

I had used your method and sloved this problem. thanks
