### ISSUE TITLE
helm dependency update/build should create charts dir if it doesn't exist

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#1372]
Currently the `helm dependency update <chart>` fails when there is no charts sub-directory. It will be nice for the helm to create the directory if it doesn't exist.

**Comment by technosophos** [comment]
This was on canary, right? Can you give me the error message? I thought we fixed that on `master` earlier this week.

**Comment by kmala** [comment]
It is fixed on master.I was on alpha.5 and should have double checked before creating an issue.
