### ISSUE TITLE
tiller-deploy crashed when running helm install command

### ISSUE THREAD

**Issue by ligc** [kubernetes/helm#1378]
I am setting up helm in a kubernetes on mesos environment,  the helm installation was done successfully, I could run helm version,  helm search, but when I tried to run helm install to install a package, the tiller-deploy pod crashed and the helm command could not be finished. The helm list returns the same error.

The output of helm commands:
```
root@c910f04x19k07:~/linux-amd64# ./helm version
Client: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"a324146945c01a1e2dd7eaf23caf0e55fabfd3d2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"4de5c4aa578ed9ca173aff472f00d2167ec59a88", GitTreeState:"dirty"}
root@c910f04x19k07:~/linux-amd64# 
root@c910f04x19k07:~/linux-amd64# ./helm search
NAME                    VERSION DESCRIPTION                                       
stable/drupal           0.3.2   One of the most versatile open source content m...
stable/jenkins          0.1.0   A Jenkins Helm chart for Kubernetes.              
stable/mariadb          0.5.1   Chart for MariaDB                                 
stable/mysql            0.1.0   Chart for MySQL                                   
stable/redmine          0.3.2   A flexible project management web application.    
stable/wordpress        0.3.0   Web publishing platform for building blogs and ...
root@c910f04x19k07:~/linux-amd64#
root@c910f04x19k07:~/linux-amd64# ./helm install stable/mysql
Fetched stable/mysql to mysql-0.1.0.tgz
2016/10/17 03:18:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
root@c910f04x19k07:~/linux-amd64#

```

The output from kubectl logs -f tiller-deploy-2117266891-viuig --namespace=kube-system:

```
root@c910f04x19k07:~# kubectl logs -f tiller-deploy-2117266891-viuig --namespace=kube-system
Tiller is running on :44134
Tiller probes server is running on :44135
Storage driver is ConfigMap

Cannot initialize Kubernetes connection: the server has asked for the client to provide credentials2016-10-17 07:18:58.000613 I | Getting release "inclined-deer" (v1) from storage
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71f965]

goroutine 63 [running]:
panic(0x1ac5960, 0xc42000a030)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/unversioned.(*ConfigMaps).Get(0xc420309600, 0xc42024c150, 0x10, 0x1cb2683, 0x6, 0xc420063728)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/unversioned/configmap.go:58 +0x75
k8s.io/helm/pkg/storage/driver.(*ConfigMaps).Get(0xc4203707b0, 0xc42024c150, 0x10, 0xc42024c150, 0x10, 0xc42024c0a0)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:64 +0x62
k8s.io/helm/pkg/storage.(*Storage).Get(0xc4203707c0, 0xc42024c0a0, 0xd, 0xc400000001, 0xd, 0x1a1e2e0, 0xc42024c060)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:37 +0x160
main.(*releaseServer).uniqName(0xc4200240e8, 0x0, 0x0, 0x0, 0xc42015e210, 0xc420334160, 0xc4200639b0, 0x549a41)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:553 +0xd7
main.(*releaseServer).prepareRelease(0xc4200240e8, 0xc42022e640, 0x1, 0xc41ffee8d0, 0xc4202dfa50)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:598 +0x6e
main.(*releaseServer).InstallRelease(0xc4200240e8, 0x7fe258a8fa68, 0xc4202a4cc0, 0xc42022e640, 0x0, 0x2a75, 0x2a75)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:579 +0x67
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_InstallRelease_Handler(0x1c5bea0, 0xc4200240e8, 0x7fe258a8fa68, 0xc4202a4cc0, 0xc42022e5f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:747 +0x27d
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4202268c0, 0x2872400, 0xc42040c630, 0xc4202a65a0, 0xc420207320, 0x289dde8, 0xc4202a4c90, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:608 +0xc50
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4202268c0, 0x2872400, 0xc42040c630, 0xc4202a65a0, 0xc4202a4c90)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:766 +0x6b0
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420370aa0, 0xc4202268c0, 0x2872400, 0xc42040c630, 0xc4202a65a0)
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:419 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:420 +0xa3
root@c910f04x19k07:~# 
```

After the helm commands, if I run kubectl get pods, I could see that the tiller-deploy pod was restarted.

```
root@c910f04x19k07:~# kubectl get pod tiller-deploy-2117266891-viuig --namespace=kube-system 
NAME                             READY     STATUS    RESTARTS   AGE
tiller-deploy-2117266891-viuig   1/1       Running   3          19m
root@c910f04x19k07:~# 
```

**Comment by technosophos** [comment]
I haven't looked into this, yet, but there is an error there that I am wondering about:

`Cannot initialize Kubernetes connection: the server has asked for the client to provide credentials`

Tiller should be getting its credentials from the environment variables in the Pod. I wonder what's going on there.

**Comment by ligc** [comment]
HI @technosophos,  thanks for the respond. Here is the environment variables and the secrets mount information of the tiller-deploy pod, any suggestion on what might be going wrong?

root@c910f04x19k07:~/helm/bin# kubectl exec -it --namespace=kube-system tiller-deploy-2117266891-55qie -- /bin/sh
/ # env
HEAPSTER_PORT_80_TCP_PORT=80
KUBERNETES_PORT=tcp://20.0.0.1:443
KUBERNETES_SERVICE_PORT=443
HEAPSTER_PORT_80_TCP_PROTO=tcp
KUBE_DNS_SERVICE_PORT_DNS_TCP=53
HOSTNAME=tiller-deploy-2117266891-55qie
SHLVL=1
HOME=/root
MESOS_EXECUTOR_CONTAINER_UUID=09259459-4271-4e40-b7b2-b9ede59ca822
KUBE_DNS_SERVICE_HOST=20.0.0.10
HEAPSTER_PORT_80_TCP=tcp://20.0.0.60:80
KUBE_DNS_SERVICE_PORT=53
KUBE_DNS_PORT=udp://20.0.0.10:53
KUBERNETES_PORT_443_TCP_ADDR=20.0.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBE_DNS_PORT_53_TCP_ADDR=20.0.0.10
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
HEAPSTER_SERVICE_HOST=20.0.0.60
KUBE_DNS_PORT_53_UDP_ADDR=20.0.0.10
KUBE_DNS_PORT_53_TCP_PORT=53
KUBE_DNS_PORT_53_TCP_PROTO=tcp
KUBE_DNS_PORT_53_UDP_PORT=53
KUBE_DNS_SERVICE_PORT_DNS=53
KUBE_DNS_PORT_53_UDP_PROTO=udp
KUBERNETES_SERVICE_PORT_HTTPS=443
HEAPSTER_SERVICE_PORT=80
KUBERNETES_PORT_443_TCP=tcp://20.0.0.1:443
HEAPSTER_PORT=tcp://20.0.0.60:80
PWD=/
KUBERNETES_SERVICE_HOST=20.0.0.1
KUBE_DNS_PORT_53_TCP=tcp://20.0.0.10:53
KUBE_DNS_PORT_53_UDP=udp://20.0.0.10:53
HEAPSTER_PORT_80_TCP_ADDR=20.0.0.60
/ #
/ # mount | grep secret
tmpfs on /var/run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,relatime)
/ # ls /var/run/secrets/kubernetes.io/serviceaccount/
ca.crt     namespace  token
/ # cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt 
-----BEGIN CERTIFICATE-----
MIIDUDCCAjigAwIBAgIJAK7ILYuWXXkTMA0GCSqGSIb3DQEBCwUAMB8xHTAbBgNV
BAMMFDEyNy4wLjAuMUAxNDc1MTMzMjExMB4XDTE2MDkyOTA3MTMzMVoXDTI2MDky
NzA3MTMzMVowHzEdMBsGA1UEAwwUMTI3LjAuMC4xQDE0NzUxMzMyMTEwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4QCoB/gTH8a1vAhVpsq1o8yyzl/zW
A6j7cyPD6GQK0Dip45DxsbMtcdCZZ53Y7ZfgpcqAzYrGtkb4G8J8GeKUXEq03N4B
ztZ2JR+2+A7YRKYQ9cO6Nxt8afGHXyzB1UuaNcJwI9LMMPe0w1FXYU1ONLdvbqLK
C6Iof6DJ4uOMqtibeahJYEp+GXruJq4s5OxPfoKlpoPlGZc/FYW5JJwMjvKLAMQB
5M21/TOYq7ZZCKu8IV8yJF75Xu6GJJYPa2NSlSA4I3YOwlxz7Qq5Bjm65t647CWK
NO9uKg+duucoqEyfDiFKrUF2j2vabG8vRheshCtoyi6ycePsVVFfVTpPAgMBAAGj
gY4wgYswHQYDVR0OBBYEFOzzu3pjvOtOtgFMVXA5tEqXgWxyME8GA1UdIwRIMEaA
FOzzu3pjvOtOtgFMVXA5tEqXgWxyoSOkITAfMR0wGwYDVQQDDBQxMjcuMC4wLjFA
MTQ3NTEzMzIxMYIJAK7ILYuWXXkTMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgEG
MA0GCSqGSIb3DQEBCwUAA4IBAQA/vXjRIvaBG5wBoENoRsqihgxP5jG42E5fED1b
JukrwPznOM+/9Co/Q+fy5Xtq1UK2sAZhz4a7iJce/8BTIAfId2VFQ3VfusLg+EDA
NnmmRWipDLXuXe/Z3/ycH2JGJlEW0qF7fkdZUXIHhazRfMwqTHgF+IOGphQbK3vx
UZYUoKkwRcN3ZE3ubSo+mGBJnsgDas8MJlI3Z5VQaqChbYNj9n76dheJFnsFnDG2
pGaS5fd/Sl/FanFuwKTeOzgN8F+3XW4dMh2dFmeUj/EqfeUL8JwOZ227f19v+R1d
HjOiM5YmSmkrXWwopPpHbPaOxk17OOKWt9T8EXjFZ+Cop6sS
-----END CERTIFICATE-----
/ # cat /var/run/secrets/kubernetes.io/serviceaccount/token 
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLWRhYzhjIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI2YTdiMjk5OS02ODE2LTExZTYtYTcyMC00MmFlMGEwNDEzMDciLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.vL9K9lg4n2YEmkGN_RrqLkdHZ9tPNYSlIsX_NUiPNN3guhkYOH-IHMUPwYRbRO_t3-rqoboE9yJQnO2LyNV_cJyj9Bk1Jt1cmPZR_zAg93hDL0r6vj7TNEeTQprLniZPbDOLZWjRA_BZyPb2Nsz8OG4VJokhQsFuHJ_nm4_4kCAD7TwZeIBy5XlLRfRIw0M9JN3vrHnXPlNEfqVtfm1CMth6LkPWj6lxdsUD4ZMgmPCdtUe3EFareEbjEYWkdx5HEP1BOzgeQpz0lg4yJiZZB5KqjBllKO2dCRqX9B-lmLTaW3zUR24GCBXv4LaO2IdPP_TozM5ZhFs17EgOaSfwmw/ # 
/ # cat /var/run/secrets/kubernetes.io/serviceaccount/namespace 
kube-system/ #

**Comment by technosophos** [comment]
One quick way to test would be to `kubectl exec` into the Tiller pod, and then download `kubectl` and see if `kubectl` commands worked. (You might have to `apk update && apk add curl`)

The environment above looks correct. But the easiest way to test that the IPs and credentials are actually working is to use `kubectl` directly for that.

Can you try that and let me know whether it works?

**Comment by ligc** [comment]
HI @technosophos, here is the kubectl test result:

1. use the default configuration, kubectl could not run:
```
/ # kubectl get nodes
error: You must be logged in to the server (the server has asked for the client to provide credentials)
/ # 

```
2. set the 10.4.19.7:8888 as the kubectl server, then it works correctly

```
/ # kubectl --server 10.4.19.7:8888 get nodes
NAME                                STATUS    AGE
c910f04x19k08.pok.stglabs.ibm.com   Ready     1d
c910f04x19k09.pok.stglabs.ibm.com   Ready     1d
/ # 
```

**Comment by ligc** [comment]
HI @technosophos,  any suggestion on what might be going wrong in my configuration? I am being blocked by this issue. Your response will be appreciated.

**Comment by technosophos** [comment]
Can you set your local `kubectl` config to point to the server? I think `kubectl config view` is the way to get started with that.

**Comment by ligc** [comment]
HI @technosophos, here is my local kubectl configuration:

```
root@c910f04x19k07:~# kubectl config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.4.19.7/kubernetes
  name: cfc
contexts:
- context:
    cluster: cfc
    user: user
  name: cfc
current-context: cfc
kind: Config
preferences: {}
users:
- name: user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5NjI2ZDJkNjM2NjYzMmQ3MzY1NzI3NjY5NjM2NTJkNmI2NTc5NjkiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJjZmMtc2VydmljZSIsImV4cCI6MTQ3NzQ0ODM5NCwiaWF0IjoxNDc3NDQ0Nzk0LCJpc3MiOiJodHRwczovL21hc3Rlci5jZmMvYWNzL2FwaS92MS9hdXRoIiwicHJvamVjdHMiOlsiYWRtaW4iXSwic3ViIjoiYWRtaW4ifQ.JyQRRyK3i4EU1GlDlt1PaR25oh8mQ1DNzKEUrgIGnvm4hCvQt3BFyoJGqHuq5Xyic0RXKs8nOsABYcJJxAnnwrnSeQzgDY0s9GNXXdDEMZ1DerdonqYkiJigLzv0tuVAur-LewBSwXlhQ1NMtMoxbzw9kBphKJsj6j0bpxpnmoJwf38wC3wICMONdDuftgMXdKjdkWEnz2y10TLzzeJL4SUluEYDTOXKDTRKxpYbtSY7rRoEvYVoEJQfVFhrV66pwQ3BCtjQ64aRs4AHg5d-lSYJeFH3qQwiEiXaIyiUKV1tvZOvpXoPZkurOnccUBjmc8l3xTRjKukTy2G7NpRv2A
root@c910f04x19k07:~# 
```
With this configuration, I could run kubectl command locally without problem:

```
root@c910f04x19k07:~# kubectl get nodes
NAME                                STATUS    AGE
c910f04x19k08.pok.stglabs.ibm.com   Ready     6d
c910f04x19k09.pok.stglabs.ibm.com   Ready     6d
root@c910f04x19k07:~# 
```

**Comment by ligc** [comment]
After reinstalled my Kubernetes environment and updated to the latest helm beta.2 version, this problem goes way, probably the authentication stuff in my previous environment was messed up.  Thanks @technosophos for the help and pointing me to the right direction,  I am closing this issue.
