### ISSUE TITLE
When install fails in EC2 with a LB Service ELB is orphaned

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/helm#1382]
We have reproduced this issue with the latest release.  
1. try to install a broken chart with a service that is a `type: LoadBalancer`
2. Go into aws console and you will see an ELB that is not connect to the cluster, is not tagged, and is orphanned.

@jroberts235 did I miss anything?

**Comment by technosophos** [comment]
And if you do a `helm delete RELEASE_NAME --purge` the LB is not cleaned up?

**Comment by technosophos** [comment]
Is this still failing with Beta.2? I cleaned up some of the generic deletion logic, and am hoping this fixes some of the cloud provider-specific issues.

**Comment by chrislovecnm** [comment]
@technosophos we are going to test beta 5 and get back to you.  Thanks for the follow-up!

**Comment by technosophos** [comment]
Evidence seems to suggest that this was closed around beta-5. Please re-open if you reproduce with a new (>2.1.0) Helm.
