### ISSUE TITLE
Dependency update fetching wrong version

### ISSUE THREAD

**Issue by royjs** [kubernetes/helm#1383]
When the `dependency update` command fetches the required chart from the repo it always takes the latest one, not considering the specified version at all.

I took a look at the code and the problem seem to be here : https://github.com/kubernetes/helm/blob/master/cmd/helm/downloader/manager.go#L337
The loop returns even if the version was not found. I did a quick test locally and it behaves as expected when this line is removed.

**Comment by technosophos** [comment]
You are right. I'll remove that line.
