### ISSUE TITLE
helm list doesn't show a release after a failed upgrade.

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#1387]
helm list doesn't shown anything after a failed release. 
Steps to reproduce:
1) helm install <chart> succeeded.
2) helm list shows the release created above.
3) helm upgrade <release-name> <new-chart> failed.
4) helm list doesn't show anything.

**Comment by technosophos** [comment]
What does `helm list --all` or `helm list --failed` show?

**Comment by kmala** [comment]
both show the current release with FAILED status which is correct as it failed.

**Comment by technosophos** [comment]
The default filter for `helm list` will only show releases that are in the state DEPLOYED. So failed, deleted, superseded releases won't show up. You need to use a flag to see them.

**Comment by viglesiasce** [comment]
I think failed should show up. The flow for users shouldnt be that they are successful, things appear, then something gets borked and they cant find it anymore.

**Comment by kmala** [comment]
if the upgrade failed shouldn't the previous release be in a deployed state(helm doing the cleanup) or is it expected for the user to do a rollback manually to the previous successful release

**Comment by technosophos** [comment]
That seems reasonable. Lemme look into it

**Comment by technosophos** [comment]
@kmala We don't ever automatically rollback. We assume a user is better situated to know what to roll back to than we are.

**Comment by brian-vu** [comment]
Facing the same problem with helm v2.9.1 .
The `helm list` does not show any release but the release  was actually successfully deployed. I can get all resources with kubectl commands, all web-services also work well and be testable via browser. 
Step to be reproduce.  
1. helm install succeeded.
2. helm list shows the release created above.
3. helm upgrade failed.
4. helm list doesn't show anything.
5. kubectl get pods, kubectl get services, kubectl get deployments will show well working resources.
