### ISSUE TITLE
Minor corrections kebuctl commands in install.md

### ISSUE THREAD

**Issue by gegtot** [kubernetes/helm#1393]
File docs/install.md

This `kubectl delete deployment tiller-deployment -n kube-system`
Should be `kubectl delete deployment tiller-deploy --namespace kube-system `

This `kubectl get po -n kube-system`
Should be `kubectl get po --namespace kube-system`

**$ kubectl version**
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7+a2cba278", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"not a git tree", BuildDate:"2016-09-23T01:56:47Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

Thanks,
Georg

**Comment by technosophos** [comment]
Oh, you're right. The `-n` shortcut was added in a later version of kubectl (1.4?). So that would break for some people.

**Comment by gegtot** [comment]
Thanks! Just realized I was running kubectl 1.3.7...

2016-10-18 21:13 GMT+02:00 Matt Butcher <notifications@github.com>:
