### ISSUE TITLE
Add helm debug command

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/helm#1398]
In order to help service users issues better we should create a script that they can use in order to quickly provide maintainers with the info they need in order to debug their problem. It can start simple but could eventually become part of helm itself.

**Comment by michelleN** [comment]
yep. I'm in need of this more and more. Maybe a `helm health` command? I don't want to add another command if it's unnecessary though, so I'm wondering what people think about that. I think starting with a script sounds good.
What kinds of things would we check in this script?

cc/ @technosophos @adamreese

**Comment by technosophos** [comment]
I'm adding this to 2.1.0-Alpha.1 just to get it on the roadmap, but we can realistically do it anytime.

**Comment by technosophos** [comment]
This is still on the roadmap. Nobody's done it yet, though.

**Comment by technosophos** [comment]
Could we add this onto the `helm version` command, so that if they did something like `helm version --debug` it would print out the Helm, Tiller, Kubernetes versions, and any other info we need (like maybe iterate through the list of supported API objects or something)?

**Comment by rbwsam** [comment]
I took a shot at this one (see above) just showing kubernetes version info for now. I'm wide open to feedback.
