### ISSUE TITLE
helm delete doesn't delete all related resources if one is missing

### ISSUE THREAD

**Issue by sputnick** [kubernetes/helm#1399]
It seems that Kubernetes REST API (in k8s 1.4) doesn’t cascade its deleting of a Deployments which makes helm delete not work as expected.

**Reproducing:**
Deploy "stable/redmine" with "helm install stable/redmine". 
Then manually deleted one of the deployed Deployments with the k8s API.
Try running "helm delete thereleasename". It will think it successfully deleted everything but leaves behind the Pods and the ReplicaSet of the missing Deployment.

**What I wanted to happen:**
Helm delete should delete all the resources it created even if some of them are already deleted.

**Comment by technosophos** [comment]
This is a tough one. If Helm deploys a `deployment`, and the deployment creates a replica set and some pods, Helm only knows about the thing it deployed. I'm not sure we have a pattern that would work for finding resources that were created by a now-destroyed resource. Any ideas on how that could be done?

**Comment by viglesiasce** [comment]
I'm a bit confused on this one. I havent seen a deleted deployment leave around replicasets. What causes that to happen?

**Comment by sputnick** [comment]
@viglesiasce by deleting the Deployment via the REST API. Kubectl contains business logic that finds and deletes related ReplicaSet and Pods

**Comment by viglesiasce** [comment]
Ah!! Missed that detail. Thanks for the clarification. One way to workaround this (not saying its a fix) is to deploy each app into its own namespace. Then delete the entire namespace. AFAIK that logic for cleanup lives on the server side.

**Comment by sputnick** [comment]
@technosophos when the Deployment is delete the ReplicaSet still has the same name and annotations etc. so the reference to the release is there. Also since the ReplicaSet ALSO has MatchLabels set to the same as the Deployment the ReplicaSet is now the "top" controller that you patch to reduce Pod replicas to 0 (zero).

**Comment by sputnick** [comment]
@viglesiasce that's a sledgehammer when you only need a sponge for cleanup ;)

**Comment by spiddy** [comment]
That's related to https://github.com/kubernetes/kubernetes/issues/12143 & https://github.com/kubernetes/kubernetes/issues/19054. When kubernetes solves cascade delete (aka reaping) server-side it should be fairly easy to support this.

**Comment by technosophos** [comment]
Marked as 2.1 so we can revisit this after the 2.0 dev cycle is finished.

**Comment by technosophos** [comment]
Okay, so some of the deletion logic has been changed to prevent deletes from simply _stopping_. But it won't solve the exact case described here.

The cascading delete will not be solved in Helm. We're simply relying upon upstream Kubernetes to fix it. In the 1.5 release I believe this is done.

Marking this closed since there's nothing left for us to do.
