### ISSUE TITLE
feat: Add `helm repo index --recursive`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1401]
Add a `--recursive` flag to get `helm repo index` to traverse a deep directory structure.

Relates to #1328

**Comment by technosophos** [comment]
This might be slightly harder than the average starter, but it requires switching from a single-directory walk to a recursive walk in `pkg/repo.IndexDirectory`.

**Comment by fernandofederico1984** [comment]
any update on this issue?

**Comment by bacongobbler** [comment]
@fernandofederico1984 feel free to take it on if you're up for it!

@AmandaCameron I notice that you were working on this a bit. What is the status of that effort? Are you working on other projects or were there certain gotchas you found with the proposal?

**Comment by AmandaCameron** [comment]
@bacongobbler I'm pretty sure the code I have in the PR is working and usable going from my memory. I feel like I'm failing to communicate something somewhere though, or misunderstanding something that's being communicated to me, in the area of the PR, so I'm not sure what to do about it. I don't deal well with vocal communication, and the PR's gone silent since I tried to explain some stuff around it.

**Comment by michelleN** [comment]
Hey @AmandaCameron - Apologies again for the PR going silent. Let's get this merged asap. I've left a question about a test scenario on the PR itself.

**Comment by thomastaylor312** [comment]
I believe this was added in #1997. Closing.

**Comment by bjornbouetsmith** [comment]
Hi,

Something has regressed or was never implemented correctly I think - with the version I am running 3.7.2 recursion is not working at all.

I have a folder structure like this:
~~~
[ROOT]/packages/Infrastructure/dns
[ROOT]/packages/Infrastructure/mail
[ROOT]/packages/apps/multimedia
~~~
And so forth

When I run helm from the `[ROOT]` directory
`helm repo index ./packages`

helm generates a index file like this
~~~yaml
apiVersion: v1
entries: {}
generated: "2022-05-01T11:32:20.0869971+02:00"
~~~

If I move my `dns` & `mail`folders` from the structure above directly into `[ROOT]/packages` and then run the same index command, then helm correctly generate the expected index:
~~~yaml
apiVersion: v1
entries:
  bind9:
  - apiVersion: v1
    created: "2022-05-01T11:46:16.4494315+02:00"
    description: 'Helm chart for bind9 version: 1.0.0 - initial version '
    digest: a56fbf4157c1ed13667c6767059e3b7ad80648e876bde104621f061b95898e04
    keywords:
    - dns
    - bind
    - named
    name: bind9
    urls:
    - dns/bind9-1.0.0.tgz
    version: 1.0.0
  postfix-mta:
  - apiVersion: v1
    created: "2022-05-01T11:46:16.4494315+02:00"
    description: 'Helm chart for postfix mail relay version:1.0.3 - lock version to
      1.3.0 of docker image '
    digest: 601d37fabc41d70d8668c601c8341b6bd0f72044de96df4e2d86c80d19f360f3
    keywords:
    - postfix
    - mail
    name: postfix-mta
    urls:
    - mail/postfix-mta-1.0.3.tgz
    version: 1.0.3
generated: "2022-05-01T11:46:16.4463714+02:00"
~~~

So it seems like whoever made the patch did not really implement recursion - only implement support for nesting packages one level down.

So can we please get this re-opened to get proper recursion fixed?
