### ISSUE TITLE
Feature request - Add "helm serve" options for --all-repos and --remote-repo

### ISSUE THREAD

**Issue by sputnick** [kubernetes/helm#1404]
**Today you can:**
helm package aChartFolder/ 
And that adds the chart archive to ~/.helm/repository/local/ and updates a static index.yaml file in the same location. This becomes the repository that "helm serve" serves. This is great.

Helm serve also supports external repos via:
--repo-path string   The local directory path from which to serve charts. (default "/Users/eiki/.helm/repository/local")

**What I would like helm to do...:**
However it requires that your "--repo-path" contains an index.yaml file. For testing purposes this file can be cumbersome and redundant (helm generate) to create by hand and update.

I would like "helm server --repo-path" to auto generate a missing index.yaml file by recursively inspecting the folder in the --repo-path for Charts (folders and archives).

This index.yaml would simply live in RAM but possibly by adding another option i.e. "--save-index" it would write the file in the --repo-path (overwriting what was there before).

Optionally a third parameter could allow 'helm serve' to serve a list of all repo charts in one generated index.yaml i.e. "--all-repos' (from repositories.yaml) or by using multiple "--remote-repo=http://qstack.com...".

All these use cases would help test/build/deploy Chart repos and make "helm serve" a prime candidate to deploy repositories as a container (in k8s).

**Comment by sputnick** [comment]
Possibly relates to #1401

**Comment by technosophos** [comment]
I think it's going to be necessary to have `helm serve` generate an index.yaml file for sure. I've hit several test cases this morning where a stale `index.yaml` is causing `helm serve` to fail in interesting ways, and it seems the current work-around is to manually rebuild the index, which feels wrong.

**Comment by technosophos** [comment]
Related to #792

**Comment by sputnick** [comment]
Excellent 👍

**Comment by bacongobbler** [comment]
The feature requests listed here have all been solved with [chartmuseum](https://github.com/kubernetes-helm/chartmuseum) which I think is the repository server we want to recommend moving forward. It autogenerates the index.yaml based on the packages uploaded to the chart repository, removing the need to manage an index.yaml at all.

I'm going to close this as resolved as this project is now an official helm incubator project, but please re-open if this project doesn't solve your use case. Thanks! :)
