### ISSUE TITLE
helm sometimes fails when creating and using a new namespace in separate template YAML files in a Chart

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#1414]
this doesn't fail every time for me locally; but fails sometimes; so looks timing related. 

I've a chart which deploys a bunch of stuff, including creating a new namespace in one template YAML and using that namespace in another YAML file

```
helm repo add fabric8 https://fabric8.io/helm
helm install fabric8/fabric8-platform
```

I've seen this totally work once but I've also seen this happen a few times:

```
$ helm install fabric8/fabric8-platform
Fetched fabric8/fabric8-platform to fabric8-platform-2.2.10-helm.tar.gz
Error: release tufted-badger failed: namespaces "user-secrets-source-admin" not found
$ helm list
$
```

so am guessing this is an ordering issue of the YAML files inside a Chart. 

Historically when applying lots of YAML resources we sorted them in the [maven tooling for kubernetes](https://github.com/fabric8io/fabric8-maven-plugin). I wonder if Helm should do the same; load all resources and sort them before applying them? e.g. Namespaces first, then Secrets + ServiceAccounts + Services, then Deployments etc

I guess another workaround is to not have a separate YAML for the namespace and secret; but have a single YAML file for the Namespace and Secret to force ordering. 

Whats the best approach to ensure that resources get applied in the correct order so that YAML referencing other resources works reliably?

**Comment by technosophos** [comment]
If you're using Alpha.5, that should be fixed now. I found a bug in the ordering that was resulting in namespace records sometimes being sent too late. Beta.1, which will be out today, _should_ have that fixed.

**Comment by jstrachan** [comment]
ah great thanks @technosophos I just tried beta.1 and didn't see this error - but got this instead:
```
$ helm install fabric8-platform
NAME: insipid-pengui
Error: getting deployed release 'insipid-pengui': release: not found
```

I'll do a bit more testing to see if this is a one off

**Comment by technosophos** [comment]
@jstrachan Let me know about this one. I'm putting together the next round of Beta issues.
