### ISSUE TITLE
Support for custom namespace for the tiller deployment object (helm init)

### ISSUE THREAD

**Issue by djsly** [kubernetes/helm#1418]
In our kubernetes cluster, users have read/write access to their own namespace and specific group namespace (dev/qa/prod/canary/etc)

We would like to allow users from testing out newer version of Helm and Tiller in their own namespace. Hence allowing them to sanitize more recent versions before promoting them to the default kube-system namespace.

**Comment by technosophos** [comment]
I agree with this. It'll take some work to get it working, though. I've added it on the 2.1.0-Alpha.1 milestone, since that's the next feature dev cycle.
