### ISSUE TITLE
Add language in the CONTRIBUTING doc to explain how to become a core maintainer

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1432]
Long ago, we had official language about how to become a core contributor. We intentionally pulled it at one point, intending to replace it. But now that we are on the incubation track, we should revisit the issue and follow the community's best practices.

**Comment by technosophos** [comment]
Is this something you guys can help us with, @etune and @pwittrock ?

**Comment by pwittrock** [comment]
@grodrigues3 Ideas?

**Comment by technosophos** [comment]
I've now looked through all the Kubernetes and CNCF docs I can find, and cannot find anything that explicitly says how one becomes a core maintainer.

I did notice the OWNERS file in github.com/kubernetes/kubernetes, but couldn't find any info specifically on how they determined who was added to that.

Provisionally, I would suggest that we adopt a voting system, in which 2/3 majority of existing core maintainers must agree before a new member be added.

Current core maintainers are (alphabetically):

@adamreese (Deis)
@michelleN (Deis)
@migmartri (Bitnami)
@prydonius (Bitnami)
@technosophos (Deis)
@viglesiasce  (Google)
@vaikas-google (Google)

So a 2/3 majority would prevent any one company from acting unilaterally.

Additionally, I would suggest that the nomination is tracked as an issue, and that one person on that ticket will report on the results of a non-public vote.

**Comment by technosophos** [comment]
Add @thomastaylor312 to the list above.

**Comment by technosophos** [comment]
Related to #1906

**Comment by thomastaylor312** [comment]
@technosophos Do you want me to add the process you mention above as part of #2069?

**Comment by jascott1** [comment]
@technosophos Do we still want to add this to CONTRIBUTING or perhaps another doc?

**Comment by bacongobbler** [comment]
related issues: https://github.com/kubernetes/helm/issues/2792
