### ISSUE TITLE
Unable to delete charts

### ISSUE THREAD

**Issue by naveensrinivasan** [kubernetes/helm#1436]
I have created jenkins chart in minikube and when I try to delete it fails.

```
~ minikube  naveen@GuessWho  ~/temp/darwin-amd64 helm delete code-5
Error: no objects passed to create
~ minikube  naveen@GuessWho  ~/temp/darwin-amd64 k get deployment
NAME             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
code-5-jenkins   1         1         1            1           1d
~ minikube  naveen@GuessWho  ~/temp/darwin-amd64 helm version
Client: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"a324146945c01a1e2dd7eaf23caf0e55fabfd3d2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"4de5c4aa578ed9ca173aff472f00d2167ec59a88", GitTreeState:"dirty"}
```

**Comment by technosophos** [comment]
Would you mind re-testing this with Helm/Tiller Beta.2? I think we fixed the bug that was causing that.

**Comment by naveensrinivasan** [comment]
Nope didn't fix it.
```
~ minikube  naveen@GuessWho  ~/temp/darwin-amd64 ./helm delete odd-sponge
Error: deletion error count 1: no objects visited
~ minikube  naveen@GuessWho  ~/temp/darwin-amd64 ./helm version
Client: &version.Version{SemVer:"v2.0.0-beta.2", GitCommit:"8a5550d0c6785eaa94eac80e0c1d11a92c355a02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-beta.2", GitCommit:"8a5550d0c6785eaa94eac80e0c1d11a92c355a02", GitTreeState:"clean"}
```

**Comment by technosophos** [comment]
Can you drop in the output of `helm get $NAME`? (Feel free to redact if anything in there is sensitive).

**Comment by naveensrinivasan** [comment]
@technosophos I am getting `Error: release: not found`

**Comment by technosophos** [comment]
@naveensrinivasan what do the output of `helm list --all` and `helm history odd-sponge` show?

**Comment by naveensrinivasan** [comment]
```
~ minikube  naveen@GuessWho  ~/temp/darwin-amd64 ./helm list --all
NAME          	REVISION	UPDATED                 	STATUS  	CHART
amber-iguana  	1       	Sun Oct 16 21:10:17 2016	DEPLOYED	jenkins-0.1.0
code          	1       	Wed Oct 19 21:22:23 2016	DEPLOYED	jenkins-0.1.0
code-1        	1       	Wed Oct 19 21:24:38 2016	DEPLOYED	jenkins-0.1.0
code-2        	1       	Wed Oct 19 21:53:45 2016	DEPLOYED	jenkins-0.1.0
code-3        	1       	Wed Oct 19 21:56:49 2016	DEPLOYED	jenkins-0.1.0
code-4        	1       	Wed Oct 19 23:09:16 2016	DEPLOYED	jenkins-0.1.0
code-5        	1       	Thu Oct 20 15:49:32 2016	DEPLOYED	jenkins-0.1.0
code-play     	1       	Wed Oct 19 21:05:37 2016	DEPLOYED	jenkins-0.1.0
elevated-jagua	1       	Wed Oct 19 17:03:23 2016	DEPLOYED	jenkins-0.1.0
flippant-kanga	1       	Sun Oct 16 21:26:12 2016	DEPLOYED	jenkins-0.1.0
hoping-starfis	1       	Tue Oct 25 20:03:33 2016	DELETED 	jenkins-0.1.0
jenkins-play  	1       	Wed Oct 19 20:50:51 2016	DEPLOYED	jenkins-0.1.0
maudlin-anteat	1       	Tue Oct 25 20:00:10 2016	DELETED 	jenkins-0.1.0
odd-sponge    	1       	Tue Oct 25 20:04:23 2016	DELETED 	jenkins-0.1.0
ornery-woodpec	1       	Wed Oct 26 13:34:30 2016	DELETED 	jenkins-0.1.0
~ minikube  naveen@GuessWho  ~/temp/darwin-amd64 ./helm history odd-sponge
REVISION	UPDATED                 	STATUS 	CHART
1       	Tue Oct 25 20:04:23 2016	DELETED	jenkins-0.1.0
~ minikube  naveen@GuessWho  ~/temp/darwin-amd64 
```

**Comment by technosophos** [comment]
Are there any resources in Kubernetes that are still running, and are part of `odd-sponge`?

It may simply be that the error happened because the resources were all destroyed before the `helm delete` command.

**Comment by sjthespian** [comment]
I see that this was closed, was there ever a resolution? I'm running into the same issue even using the public charts (in this case jenkins). When I delete the resources manually with kubectl I get  into a state where I can't even get status for the chart.

`> helm list
NAME          	REVISION	UPDATED                 	STATUS  	CHART        
austere-frog  	1       	Thu Dec  8 14:09:29 2016	DEPLOYED	jenkins-0.1.4
elegant-crocod	1       	Thu Dec  8 14:34:40 2016	DEPLOYED	jenkins-0.1.4
jenkins-test  	1       	Thu Dec  8 14:00:04 2016	DEPLOYED	jenkins-0.1.4
lolling-kudu  	1       	Thu Dec  8 14:07:01 2016	DEPLOYED	jenkins-0.1.4
quaffing-prong	1       	Thu Dec  8 14:16:22 2016	DEPLOYED	jenkins-0.1.4

 helm delete quaffing-prong
Error: no objects passed to create

> helm status quaffing-prong 
Error: [configmaps "quaffing-prong-jenkins" not found, persistentvolumeclaims "quaffing-prong-jenkins" not found, deployments.extensions "quaffing-prong-jenkins" not found, services "quaffing-prong-jenkins" not found, secrets "quaffing-prong-jenkins" not found]

> helm history quaffing-prong
REVISION	UPDATED                 	STATUS  	CHART        
1       	Thu Dec  8 14:16:22 2016	DEPLOYED	jenkins-0.1.4

> helm get quaffing-prong
REVISION: 1
RELEASED: Thu Dec  8 14:16:22 2016
CHART: jenkins-0.1.4
USER-SUPPLIED VALUES:
Master:
  image: us.gcr.io/xxxxxxxx/jenkins

COMPUTED VALUES:
Agent:
  Cpu: 200m
  Image: jenkinsci/jnlp-slave
  ImageTag: 2.52
  Memory: 256Mi
Master:
  AdminUser: admin
  Component: jenkins-master
  ContainerPort: 8080
  Cpu: 200m
  Image: gcr.io/kubernetes-charts-ci/jenkins-master-k8s
  ImagePullPolicy: Always
  ImageTag: v0.5.0
  Memory: 256Mi
  Name: jenkins-master
  ServicePort: 8080
  ServiceType: LoadBalancer
  SlaveListenerPort: 50000
  image: us.gcr.io/xxxxxxxx/jenkins
Persistence:
  AccessMode: ReadWriteOnce
  Enabled: true
  Size: 8Gi
  StorageClass: generic

HOOKS:
MANIFEST:

---
# Source: jenkins/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: quaffing-prong-jenkins
data:
  config.xml: |-
    <?xml version='1.0' encoding='UTF-8'?>
    <hudson>
      <disabledAdministrativeMonitors/>
      <version>2.7.3</version>
      <numExecutors>0</numExecutors>
      <mode>NORMAL</mode>
      <useSecurity>true</useSecurity>
      <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
        <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
      </authorizationStrategy>
      <securityRealm class="hudson.security.LegacySecurityRealm"/>
      <disableRememberMe>false</disableRememberMe>
      <projectNamingStrategy class="jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy"/>
      <workspaceDir>${JENKINS_HOME}/workspace/${ITEM_FULLNAME}</workspaceDir>
      <buildsDir>${ITEM_ROOTDIR}/builds</buildsDir>
      <markupFormatter class="hudson.markup.EscapedMarkupFormatter"/>
      <jdks/>
      <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
      <myViewsTabBar class="hudson.views.DefaultMyViewsTabBar"/>
      <clouds>
        <org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud plugin="kubernetes@0.8">
          <name>default</name>
          <templates>
            <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
              <name>default</name>
              <image>jenkinsci/jnlp-slave:2.52</image>
              <privileged>false</privileged>
              <alwaysPullImage>false</alwaysPullImage>
              <command></command>
              <args></args>
              <remoteFs>/home/jenkins</remoteFs>
              <instanceCap>2147483647</instanceCap>
              <label></label>
              <nodeSelector></nodeSelector>
              <resourceRequestCpu>200m</resourceRequestCpu>
              <resourceRequestMemory>256Mi</resourceRequestMemory>
              <resourceLimitCpu>200m</resourceLimitCpu>
              <resourceLimitMemory>256Mi</resourceLimitMemory>
              <volumes/>
              <envVars/>
              <annotations/>
              <imagePullSecrets/>
            </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
          </templates>
          <serverUrl>https://kubernetes.default</serverUrl>
          <skipTlsVerify>false</skipTlsVerify>
          <namespace>default</namespace>
          <jenkinsUrl>http://quaffing-prong-jenkins:8080</jenkinsUrl>
          <jenkinsTunnel>quaffing-prong-jenkins:50000</jenkinsTunnel>
          <containerCap>10</containerCap>
          <retentionTimeout>5</retentionTimeout>
        </org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud>
      </clouds>
      <quietPeriod>5</quietPeriod>
      <scmCheckoutRetryCount>0</scmCheckoutRetryCount>
      <views>
        <hudson.model.AllView>
          <owner class="hudson" reference="../../.."/>
          <name>All</name>
          <filterExecutors>false</filterExecutors>
          <filterQueue>false</filterQueue>
          <properties class="hudson.model.View$PropertyList"/>
        </hudson.model.AllView>
      </views>
      <primaryView>All</primaryView>
      <slaveAgentPort>50000</slaveAgentPort>
      <label></label>
      <nodeProperties/>
      <globalNodeProperties/>
      <noUsageStatistics>true</noUsageStatistics>
    </hudson>
---
# Source: jenkins/templates/home-pvc.yaml

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: quaffing-prong-jenkins
  annotations:
    volume.alpha.kubernetes.io/storage-class: "generic"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: jenkins/templates/jenkins-master-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quaffing-prong-jenkins
  labels:
    heritage: "Tiller"
    release: "quaffing-prong"
    chart: "jenkins-0.1.4"
    component: "quaffing-prong-jenkins-master"
  annotations:
    "helm.sh/created": "1481235382"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "quaffing-prong-jenkins-master"
  template:
    metadata:
      labels:
        heritage: "Tiller"
        release: "quaffing-prong"
        chart: "jenkins-0.1.4"
        component: "quaffing-prong-jenkins-master"
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
              {
                  "name": "copy-default-config",
                  "image": "gcr.io/kubernetes-charts-ci/jenkins-master-k8s:v0.5.0",
                  "command": ["cp", "-n", "/var/jenkins_config/config.xml", "/var/jenkins_home"],
                  "volumeMounts": [
                      {
                          "name": "jenkins-config",
                          "mountPath": "/var/jenkins_config"
                      },
                      {
                          "name": "jenkins-home",
                          "mountPath": "/var/jenkins_home"
                      }
                  ]
              }
          ]'
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: quaffing-prong-jenkins
          image: "gcr.io/kubernetes-charts-ci/jenkins-master-k8s:v0.5.0"
          imagePullPolicy: "Always"
          args: [ "--argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)",  "--argumentsRealm.roles.$(ADMIN_USER)=admin"]
          env:
            - name: JAVA_OPTS
              value: ""
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quaffing-prong-jenkins
                  key: jenkins-admin-password
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: quaffing-prong-jenkins
                  key: jenkins-admin-user
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: slavelistener
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            -
              mountPath: /var/jenkins_home
              name: jenkins-home
              readOnly: false
            -
              mountPath: /var/jenkins_config
              name: jenkins-config
              readOnly: true
      volumes:
      - name: jenkins-config
        configMap:
          name: quaffing-prong-jenkins
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: quaffing-prong-jenkins
---
# Source: jenkins/templates/jenkins-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: quaffing-prong-jenkins
  labels:
    heritage: "Tiller"
    release: "quaffing-prong"
    chart: "jenkins-0.1.4"
    component: "quaffing-prong-jenkins-master"
  annotations:
    "helm.sh/created": "1481235382"
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 50000
      targetPort: 50000
      name: slavelistener
  selector:
    component: "quaffing-prong-jenkins-master"
  type: LoadBalancer

---
# Source: jenkins/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: quaffing-prong-jenkins
  labels:
    app: quaffing-prong-jenkins
    chart: "jenkins-0.1.4"
    release: "quaffing-prong"
    heritage: "Tiller"
type: Opaque
data:
  
  jenkins-admin-password: "xxxxx=="
  
  jenkins-admin-user: "xxxxx="

`

**Comment by aegixx** [comment]
Very similar issue here - had a bad helm template syntax that I fixed and I _think_ maybe an upgrade attempt happened while one was already in-progress.  Right now, if I run a `helm delete`, I get the same old syntax error that is no longer present: ```
╰─⚡ helm delete kapacitor-provisioning --purge
Error: error validating "": error validating data: [found invalid field env for v1.PodSpec, found invalid field labels for v1.PodTemplateSpec, found invalid field name for v1.PodTemplateSpec]
```
Here's the history, which may show the problem: ```
╰─⚡ helm history kapacitor-provisioning
REVISION	UPDATED                 	STATUS    	CHART                                 	DESCRIPTION
1       	Fri Sep 22 15:49:16 2017	SUPERSEDED	kapacitor-provisioning-0.0.1          	Install complete
2       	Fri Sep 22 16:04:35 2017	SUPERSEDED	kapacitor-provisioning-0.0.2-0+f154325	Preparing upgrade
3       	Fri Sep 22 16:25:00 2017	SUPERSEDED	kapacitor-provisioning-0.0.2-0+f154325	Upgrade complete
4       	Fri Sep 22 16:35:30 2017	SUPERSEDED	kapacitor-provisioning-0.0.2-0+02d9d66	Upgrade complete
5       	Fri Sep 22 16:49:03 2017	DEPLOYED  	kapacitor-provisioning-0.0.2-0+961a3f9	Upgrade complete
```
