### ISSUE TITLE
dependency update: lockfile changed even if no version changes

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1438]
My `requirements.lock` contains a `generated` key which changes every time `helm dep update` is run, even if there are no changes to the version of the dependency.

This requires me to manually checkout the changes if I only fetched dependencies to test the chart, but haven't made any changes to the dependencies. Should the `generated` key be removed?

**Comment by prydonius** [comment]
Alternatively, keep it, but only update it if a version has changed.

**Comment by prydonius** [comment]
cc @databus23 @technosophos

**Comment by technosophos** [comment]
I'll fix it to only overwrite the existing lock if the hash has changed.
