### ISSUE TITLE
helm dependency update returns 0 for failed update

### ISSUE THREAD

**Issue by coffeepac** [kubernetes/helm#1439]
All *nix systems return a non-zero error code when the command fails.  I expect the same behavior from helm when an dependency update fails.  

Steps to repro:
- create a requirements.yaml for an upstream dependency that doesn't exist
- run 'helm dependency update --debug \<chart name\>'

   actual output:
```
bash-4.3# linux-amd64/helm dependency update --debug kafka
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "atlas" chart repository
...Unable to get an update from the "local" chart repository (http://localhost:8879/charts):
	Get http://localhost:8879/charts/index.yaml: dial tcp: i/o timeout
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading zookeepers from repo http://atlas.cnct.io
WARNING: entry not found (skipped)
```
- run 'echo $?'

  actual output:
```
bash-4.3# echo $?
0
```
  expected output:
```
bash-4.3# echo $?
1
```

**Comment by technosophos** [comment]
We've been treating download failures on `helm dependency update` as warnings, not errors. And warnings emit an exit code of 0. Based in your feedback, I'm wondering if we should consider download failures to be an error instead.

**Comment by coffeepac** [comment]
I would consider a download failure to be a helm error, the operation as a whole has not created the desired state of a fully satisfied parent package.  its probably not helm's fault but that doesn't mean we succeeded.  

I hit this while setting up a CI pipeline for a chart with a dep.

**Comment by coffeepac** [comment]
awesome!  thanks!
