### ISSUE TITLE
using helm with kube-solo or kube-cluster on mac

### ISSUE THREAD

**Issue by ploef** [kubernetes/helm#1441]
Hi,

Did anybody succeed using helm with a kubernetes install on a mac? I used kube-cluster for this but keep getting errors using "helm init".

I think the config file is not in $HOME/.kube but in $HOME/kube-cluster/kube am I correct? So I'm setting $KUBECONFIG to that folder.

Unfortunately I get following error:

Error: error installing: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refused

Can anybody help me out here?

Kind regards,
Peter

**Comment by rimusz** [comment]
hey @ploef helm works with kube-solo, but not with kube-cluster yet.
CoroeOS does not come with socat anymore which is used by kubectl port-forward and helm.
I have added it kube-solo, and extra service for tiller, so helm now can communicate with tiller.

I'm going to add the helm support to kube-cluster next week.

**Comment by ploef** [comment]
Hi @rimusz,
Thanks for the quick response! I'll checkout kube-solo now and get back to kube-cluster next week.

**Comment by sandromello** [comment]
@ploef I'm using helm (v2.0.0-beta.1) with kube-solo without any problem. Maybe you have a problem with your kubeconfig, make sure that you're in the proper context using: `kubectl config use-context kube-solo`. When you type `ksolo shell` the $KUBECONFIG is set to `~/kube-solo/kube/kubeconfig`

**Comment by rimusz** [comment]
@ploef [Kube-Cluster](https://github.com/TheNewNormal/kube-cluster-osx/releases/tag/v0.5.2) lastest version got support for Helm too

**Comment by technosophos** [comment]
Are we ready to close this one?
