### ISSUE TITLE
helm upgrade --help wording

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#1443]
```
╰─±helm upgrade --help
This command upgrades a release to a new version of a chart.

The upgrade arguments must be a release and a chart. The chart
argument can a chart reference ('stable/mariadb'), a path to a chart directory
or packaged chart, or a fully qualified URL. For chart references, the latest
version will be specified unless the '--version' flag is set.
```

` The chart
argument can a chart reference ('stable/mariadb'), a path to a chart directory
or packaged chart, or a fully qualified URL. `

I think what you meant to say was `The chart argument can reference ('stable/mariadb'), a path to a chart directory, a packaged chart, or a fully qualified URL.`

**Comment by technosophos** [comment]
Thanks. You're right, that is confusing.
