### ISSUE TITLE
Installer script ssl cert broken

### ISSUE THREAD

**Issue by amingilani** [kubernetes/helm#1445]
The documentation [here](https://deis.com/docs/workflow/quickstart/install-cli-tools/) asks us to pipe a script to bash but the endpoint `https://get.helm.sh` doesn't have a valid ssl cert.

**Comment by technosophos** [comment]
I think this issue should be filed in the Helm Classic issue queue: https://github.com/helm/helm-classic/issues

**Comment by amingilani** [comment]
@technosophos consider waiting until the suggested action is taken before marking issues as closed, please.

New issue opened at: https://github.com/helm/helm-classic/issues/493
