### ISSUE TITLE
Helm chart provenance for organizations

### ISSUE THREAD

**Issue by vdice** [kubernetes/helm#1448]
## Summary

Helm's current mechanism for signing (and verifying) a chart is nicely described in the following [doc](https://github.com/kubernetes/helm/blob/master/docs/provenance.md).  

It is a [pgp](http://www.pgpi.org/doc/pgpintro/)-based signing approach (architected with [gpg](https://www.gnupg.org/) specifically in mind), resting on crypto-technology intended for _individuals_ who _interactively_ generate and maintain key pairs for securing their online presence and communications in general.  

Therefore, as an _organization_ consisting of multiple chart authors wishing to _non-interactively_ sign and release charts (via CI/CD) on a scheduled basis, we've found ourselves at a loss on how best to juggle security concerns with limited resources (and an aforementioned emphasis on automation) in order to end up with chart artifacts of proven integrity.
## Existing Concerns

~~Note the following pre-existing [concern](https://github.com/kubernetes/helm/issues/1447) with Helm's current implementation.~~  See also the following proposal in [kubernetes/charts](https://github.com/kubernetes/charts/issues/23) in which similar concerns/questions are raised.
## Practical logistics

A helpful example in how an organization might name signing key pairs, as well as where to place the respective public keys for verification, can be found in Red Hat's [approach](https://access.redhat.com/security/team/key).  

More difficult, however, is finding examples showing the topology of an organization's signing infrastructure -- or, rather, finding examples relevant to a smaller, OSS-oriented organization otherwise lacking in similar infrastructure.

Therefore, it may be useful to review potential signing approaches, along with their strengths and weaknesses, in the hopes that other organizations beginning to give thought towards establishing provenance for authored charts might benefit and/or, if already disciplined in this arena, inform as to best practices.
### A Maintainer/Release engineer manually signs the chart

_(Also succinctly described in the aforementioned kubernetes/charts [proposal](https://github.com/kubernetes/charts/issues/23))_

_Strengths:_ inline with intended use of foundational crypto-technology, reasonably secure, no/little infrastructure needed

_Weaknesses:_ manual effort required, not conducive to higher frequency chart releases, public key may need updating
- _After_ a chart has been approved for release by CI/CD and/or QA, the project maintainer elected to be the official signatory would:
  - sign with their own pgp/gpg private key,
  - upload public key to key servers and point doc(s) to these, if not already
  - commit the resulting `*.prov` file to the repo containing the rest of the chart material
  - initiate (automated) mechanism for releasing signed chart, potentially including:
    - uploading signed chart material to a staging host
    - tasking an agent with pulling down the public key linked to via doc(s) and placing into a local public keyring
    - fetching release chart from staging
    - confirming `helm verify <chart>` results in success
    - kicking off mechanism to copy signed chart material from staging to production
### A designated machine signs the chart

_Strengths:_ most secure, possibility to mesh nicely with CI, public signing key should rarely require updating

_Weaknesses:_ heavily dependent on resources/infrastructure, potentially the most expensive
- There are varying levels of isolation/protection of said machine possible (see [Microsoft's detailed examples](https://msdn.microsoft.com/en-us/library/windows/hardware/dn653556))
- An [HSM](https://en.wikipedia.org/wiki/Hardware_security_module) is the standard machine type; potentially in form of cloud service (see [AWS CloudHSM](https://aws.amazon.com/cloudhsm/))
- Ideally, from our organization's perspective, signing agent would be minimally networked to CI so that:
  - once chart is approved for release, CI makes request to signing agent
  - signing agent signs chart material, sends back to CI
  - CI continues with release process as mentioned above
### Multiple CI servers possess signing authority

_Consider the case of an organization already hosting/maintaining their own (Jenkins or other) CI infrastructure._

_Strengths:_ CI/automation already in place, public signing key should rarely require updating

_Weaknesses:_ Varying degrees of sub-optimal security, may require additional resources/infrastructure
- It may be desired to grant signing capabilities to a (sub)set of CI servers/nodes.  To do so, a few potential ways:
  - Store encrypted organizational signing key in service/location available to authorized agents.
    - CI agents can then dynamically access and temporarily store key(s) for signing, destroying key material immediately afterwards.
    - If signing key(s) need rolling, this is done at the store/service level (read: CI agents need not be tended)
    - Options include:
      - hosting/maintaining own secret store (see [Vault](https://www.vaultproject.io/), requires non-trivial effort if not already in place)
      - using cloud-based tool (see AWS-based [Credstash](https://github.com/fugue/credstash))
      - going straight to cloud-based service (see HSM-backed [AWS KMS](https://aws.amazon.com/kms/))
  - One-time transfer of encrypted signing key(s) to all elected agents
    - Although this requires no additional resources/tooling, hosting of the same private key semi-permanently in multiple places would be sub-optimal from a security standpoint
    - Not conducive to the use of dynamically-provisioned CI agents
    - If signing key(s) need rolling, CI agents will need to be tended to.
## Concluding thoughts

Surely we aren't the only organization with similar considerations.  Please chime in where relevant!
- What scenario would other Helm chart-authoring organizations potentially entertain for signing their charts?  (Perhaps one of the above, a hybrid involving multiple or even a solution involving instrumentation/systems not yet considered?)  
- Is a CI-centric approach to securely signing charts compatible with Helm's current implementation?  If no, or if not without non-negotiable compromises, what are some ways in which Helm's mechanism might be improved to support such endeavors?

**Comment by technosophos** [comment]
Thanks for this huge write-up!

I think there are a few relevant questions that teams should ask when designing their signature system:

- What are we asserting by signing a chart? Are we saying something about the quality of the chart? Are we merely making claims about which person/thing packaged it?
- Is signing something that is centralized or decentralized? E.g. do we want to have only one person/thing with the authority to sign, or allow multiple things? Debain, for example, views signing as a task necessarily done by many people, while Red Hat appears (based on the link above) to take a more centralized approach.

More references:

The model I initially implemented was based on Debian's model. Unfortunately, the Debian policy is a little spread out. You can piece most of it together from the Developer's Reference: https://www.debian.org/doc/manuals/developers-reference/index.en.html

This blog explains more the nuts and bolts of Debian's signing model:
http://blog.packagecloud.io/eng/2014/10/28/howto-gpg-sign-verify-deb-packages-apt-repositories/

And Arch Linux actually has a comparison across several Linux distros, though the details of exactly the org structure are lacking: https://wiki.archlinux.org/index.php/DeveloperWiki:Package_signing

Finally, today I committed a change to the docs to show how to use Keybase.io for signing:
https://github.com/kubernetes/helm/blob/master/docs/provenance.md#using-keybaseio-credentials

**Comment by vdice** [comment]
@technosophos thank you for presenting the clarifying questions above as well as providing  background references on Helm's provenance model.  Truly helpful!

For the [Deis Workflow](https://deis.com/workflow/) team, we've pursued a centralized signing approach (specifically handled by a dedicated CI node) so that consumers of Workflow and associated component release charts are assured the chart about to be installed is the same chart we've stamped with approval.  

Perhaps other organizations might find it useful to learn about the direction we pursued, so please see https://github.com/deis/workflow/issues/585#issuecomment-259489914 for more details and a brief overview of the infra setup.  A blog post should be arriving shortly, as well.

Excited to help inform how the Helm provenance feature might evolve in the near future.  Thus far, it's proven to be a solid and delightfully intuitive tool.
