### ISSUE TITLE
--set option not parsing as boolean

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#1449]
Original issue is on the kubernetes/charts repo: https://github.com/kubernetes/charts/issues/138

The output of the manifest and computed values is correct, however, a conditional in the template to create a PVC is not being parsed correctly because it creates the PVC even if I set the value of persistence.enabled to false on the command line using the --set flag.

```
$ helm version
Client: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"58be8c9fce50f0657425443b83307ba91789b794", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"05c04bccae63c6392ec0cb0e27790650167279f0", GitTreeState:"clean"}
```

**Comment by prydonius** [comment]
I suggest going through options passed through set with the strconv package (ignoring any errors and falling back to a string). The question is, should we just try to parse booleans or integers also? Order also becomes important, because 1 and 0 can be parsed as booleans.
