### ISSUE TITLE
bug: client version is incompatible

### ISSUE THREAD

**Issue by resnostyle** [kubernetes/helm#1459]
Did a brew cask install helm. 
Init w/ canary tiller image

helm init -i "gcr.io/kubernetes-helm/tiller:canary"

`$HELM_HOME has been configured at $HOME/.helm.
Warning: Tiller is already installed in the cluster. (Use --client-only to suppress this message.)
Happy Helming!`

 kubectl --namespace=kube-system get pods | grep tiller
`tiller-deploy-637859184-rsix4                         1/1       Running   0          8d`

helm version

`Client: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"05c04bccae63c6392ec0cb0e27790650167279f0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"4de5c4aa578ed9ca173aff472f00d2167ec59a88", GitTreeState:"dirty"}
`

helm list
`Error: client version is incompatible`

**Comment by technosophos** [comment]
Alpha.5 and Beta.1 are incompatible. You can upgrade Tiller following the directions on https://github.com/kubernetes/helm/blob/master/docs/install.md#deleting-or-reinstalling-tiller.

**Comment by technosophos** [comment]
I'm closing this since I don't think there are any more actions associated with it. Feel free to re-open if you're still having version-related problems. Thanks!
