### ISSUE TITLE
issues with validateNoMissingValues linter (template: unexpected EOF)

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1463]
This linter rule extracts each template fragment (`{{.*}}`) in a given template file and executes it on it's own to determine if it is empty (`<no value>` or empty).

This doesn't work if the fragment creates a block (`if`, `else`, `range`), since these cannot be executed independently - the parser expends an `end` fragment. Currently, the linter is designed to ignore the `if` and `else` cases, but ignoring `range` can cause the following issue:

```
  {{- range .Values.alertmanager.ingress.hosts }}
    - host: {{ .hostName }}
  {{- end -}}
```

In the above example, `.hostName` is an element within the context of `.Values.alertmanager.ingress.hosts`, however since `{{ .hostName }}` is executed independently, the linter incorrectly reports that this value is empty.

Potential solutions:
1. Update the linter to correctly deal with control flow
   
   This would mean doing the right thing with `if`, `else`, and `range` by ignoring blocks based on conditionals, or changing context within `range` blocks.
2. Render the whole template and look for keys that are empty, or set to `<no value>`.
   
   This would simplify the linter logic, and also correct the conditional flow issues. However, it will be harder for the user to link back a snippet of rendered template to the template fragments that rendered it.
3. Remove the linter rule
   
   It might be simpler to just remove this linter rule, since:
   1. empty values can be intentional (at least empty string, not `<no value>`
   2. some empty values might cause issues that could be picked up by the yaml validator or the kubernetes validator anyway

cc @mgoodness @technosophos @migmartri

**Comment by prydonius** [comment]
Another issue I found related to this linter:

```
  joomla-password: {{ randAlphaNum 10 | b64enc | quote }}
```

```
[WARNING] templates/secrets.yaml: template: tpl:1:28: executing "tpl" at <b64enc>: wrong number of args for b64enc: want 1 got 0
```

**Comment by migmartri** [comment]
Thanks @prydonius 

Some of those linter rules came up based on my personal preference and were based the Chart examples that existed by then. 

As you stated in your examples, supporting advanced goTemplates syntax (present in most of the current Charts) might be difficult to maintain and costly.

Taking into account that from my observation, this specific linter rule has not proved its usefulness yet, I vote for disabling it.

**Comment by technosophos** [comment]
I'm good with disabling it for now, and perhaps investing some more time in it later.

**Comment by nrvmodi** [comment]
I have same issue and issue was indentation
