### ISSUE TITLE
helm init fails due to lack of context in kubeadm install

### ISSUE THREAD

**Issue by jberkus** [kubernetes/helm#1467]
1. install a kubernetes cluster using kubeadm, according to the kubeadm documentation at: http://kubernetes.io/docs/getting-started-guides/kubeadm/

2. Install helm binary on master node of the cluster

3. attempt to helm init

4. get error:

-bash-4.2# helm init
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/repository/repositories.yaml 
Creating /root/.helm/repository/local/index.yaml 
$HELM_HOME has been configured at $HOME/.helm.
Error: could not get kubernetes client: could not get kubernetes config for context '': invalid configuration: no configuration has been provided

This is apparently because the default kubernetes config is blank:

-bash-4.2# kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []

... but it seems like Helm should work out of the box with a new kubeadm cluster.

**Comment by jberkus** [comment]
Alternately, you could document this as follows:

"Copy /etc/kubernetes/admin.conf to .kube/config in your homedir, before running helm init"

**Comment by technosophos** [comment]
I just ran a few tests, and I see that this is a regression in Beta.2. I think the recent change in Kubernetes base context does not have a default URL. /cc @adamreese .

**Comment by adamreese** [comment]
looks like kubeadm will not setup kubeconfig for you 
ref: http://kubernetes.io/docs/getting-started-guides/kubeadm/#optional-control-your-cluster-from-machines-other-than-the-master
