### ISSUE TITLE
bug: Tests fail if tmp dir is on different block device than source dir

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1472]
It looks like there are symlinks that are created between source testdata files and a temp dir. Symbolic links cannot be created across block devices, so if `tmp/` is on a different block device than `$GOPATH/src/k8s.io/helm`, the tests will fail like this:

```
--- FAIL: TestRepoIndexCmd (0.00s)
	repo_index_test.go:39: link testdata/testcharts/compressedchart-0.1.0.tgz /tmp/helm-872511156/compressedchart-0.1.0.tgz: invalid cross-device link
```

**Comment by technosophos** [comment]
I believe @poopoothegorilla is working on this one.

**Comment by poopoothegorilla** [comment]
Yep I will get to this ASAP
