### ISSUE TITLE
feat: Support GnuPG gpg-agent for signing

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1475]
It was suggested by @vdice that we add support for `gpg-agent` for command that take `--sign`.

**Comment by technosophos** [comment]
I'm tinkering with a branch to do this, but it won't get merged until after 2.0.0 final.

**Comment by technosophos** [comment]
This _might_ get closed, since it can now be done via the Helm gpg plugin

**Comment by technosophos** [comment]
Removing this from milestone and closing in favor of https://github.com/technosophos/helm-plugins

**Comment by MatthiasLohr** [comment]
Sorry for bringing up dead cows, but is there an existing working solution for this? https://github.com/technosophos/helm-plugins is outdated, plugin moved to https://github.com/technosophos/helm-gpg, seems to be unmaintained (last commit April 2017) and no working solution to find.

Any remarks here or things I missed?

**Comment by bacongobbler** [comment]
see https://github.com/helm/helm/issues/7599
