### ISSUE TITLE
readme download links point to alpha5 release

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#1477]
Instead of the new beta2 release

**Comment by technosophos** [comment]
Is this the README inside of the downloaded tarball?

**Comment by jchauncey** [comment]
No sorry here's the link - https://github.com/kubernetes/helm#install

Its in the main readme of the kube/helm repo

**Comment by technosophos** [comment]
This must be a GitHub caching error. Mine shows up with Beta.2, and I even downloaded to check the version. I grabbed the source and it is showing Beta.2 in all of the links.

**Comment by jchauncey** [comment]
I might have just misread the link last night. Sorry bout that
