### ISSUE TITLE
[Feature Request] helm package should have --version flag

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#1480]
We all know that the version of a package is derived from the `Chart.yaml`. However, if you are wanting to deliver a new chart artifact for each commit pushed to master changing that file is rather cumbersome (modifying a file in CI is dangerous and having to change that file for each commit seems inefficient). 

Instead, it would be very useful to have a `--version` flag which would be part of the `helm package` command. This would allow us to override the value in `Chart.yaml` within a CI environment without mucking up the workspace.

**Comment by technosophos** [comment]
@jchauncey Just to make sure I am reading this right, you'd want that change to be written to disk, too, right?

In other words, I would be able to do this:

```console
$ grep version Chart.yaml
version: 1.2.3
$ helm package --version 2.3.4 .
$ grep version Chart.yaml
version: 2.3.4
```

Does that look correct?

**Comment by jchauncey** [comment]
Yup that's awesome

**Comment by technosophos** [comment]
After some debate, I think the current feature will go in with this functionality:

For some package `foo`, `helm package --version 1.2.3 foo` will...

- Generate a package named `foo-1.2.3.tgz`
- Set `version: 1.2.3` _INSIDE_ of `foo-1.2.3`
- Leave the outside `foo/Chart.yaml` alone

This will prevent CI/CD systems (the envisioned customer of this feature) from choking on a dirty repo after a package command is run.
