### ISSUE TITLE
docs: Projects related to Helm

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1482]
We should probably try to add a page for projects related to Helm, like Fabric8 and Schelm. The idea is to help people who are developing with Helm. Anyone have some tools to add?

**Comment by technosophos** [comment]
Also to add: Monocular and the Kubernetes Dashboard.

**Comment by sputnick** [comment]
Qstack by Greenqloud is getting Kubernets and Helm support. I'm working on that.

**Comment by technosophos** [comment]
Tools:

- Chartify: https://github.com/appscode/chartify
- https://github.com/andrewstuart/vim-kubernetes
- https://gitlab.com/tmaintz/landscaper
- https://github.com/AcalephStorage/rudder

Plugins:

- https://github.com/adamreese/helm-tiller

Blogs/Articles:

- https://medium.com/@enxebre/releasing-backward-incompatible-changes-kubernetes-jenkins-plugin-prometheus-operator-helm-self-6263ca61a1b1#.e0c7elxhq
- http://www.slideshare.net/Diacode/cicd-with-kubernetes-helm-wercker-madscalability

**Comment by technosophos** [comment]
This should replace the earlier Landscaper link

**Comment by technosophos** [comment]
Plugins:

- Helm Template plugin https://github.com/technosophos/helm-template

Docs:

- Style guide by @so0k https://gist.github.com/so0k/f927a4b60003cedd101a0911757c605a

**Comment by technosophos** [comment]
Also for docs: https://medium.com/@gajus/the-missing-ci-cd-kubernetes-component-helm-package-manager-1fe002aac680#.o8w0b3xux

**Comment by sgoings** [comment]
https://github.com/skuid/helm-value-store

**Comment by sgoings** [comment]
https://github.com/roboll/helmfile
