### ISSUE TITLE
[Feature Request] Custom linting rules

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#1495]
I think it could be incredibly useful to have the ability create custom linting rules. This would allow a team/orginization to enforce certain styles or even fields on charts they create. For instance I could see a team wanting certain annotations set of each chart that maybe supply a version string or build tag etc... Maybe they want to make sure a certain environment variable is always set?

I'm not even sure where to begin on how you might implement this, however, I really like how foodcritic did it - https://github.com/customink-webops/foodcritic-rules/blob/master/rules.rb

I think teams would define their own global lint rules but I also speculate that you might want per repo lint rules also. 

Thoughts?

**Comment by technosophos** [comment]
I wonder if this is a possible stretch-case for the current plugin system

**Comment by technosophos** [comment]
This needs a proposal, if anyone wants to write one. The idea would be to make it possible to flag a plugin as containing a linting rule.

**Comment by thomastaylor312** [comment]
Marking this as keep open in case someone wants to write a proposal. This issue should be closed if a proposal is created.

**Comment by kyleschlosser** [comment]
I opened #2694 as a proposal for this issue. Per the comments above, this issue can close.

**Comment by thomastaylor312** [comment]
Closing this in favor of #2694.
