### ISSUE TITLE
-n flag has counter-intuitive effect

### ISSUE THREAD

**Issue by krancour** [kubernetes/helm#1497]
After reviewing documentation and help, it's clear that `-n` is shorthand for `--name` and is used to specify a release name, _however_, since `kubectl` has recently (as of 1.4?) adopted `-n` as shorthand for `--namespace`, I would wager that lots of people end up tripped up by that difference.

Could I suggest that, consistent with `kubectl`, `-n` be used as shorthand for `--namespace` and that specifying a release name can be achieved instead by providing an optional second argument to `helm install`?

cc @technosophos @michelleN

**Comment by technosophos** [comment]
Yes, it is too bad that things worked out that way. Unfortunately, we can't change that until Helm 3.0 (SemVer commitments), and I don't know that we'll do it even then. Copying the flags from `kubectl` is not one of the design goals for us.

**Comment by krancour** [comment]
@technosophos you know me... you know I respect semver. But if new Helm isn't GA yet, doesn't the opportunity to change that still exist?

> Copying the flags from kubectl is not one of the design goals for us.

I'm not suggesting it should be, but I suspect enough confusion / accidents will happen that it's worth considering some better parity for this particular case.

**Comment by technosophos** [comment]
We committed to not change/remove flags from beta.1 onwards.

**Comment by krancour** [comment]
That's unfortunate, but understood. Thanks for discussing.
