### ISSUE TITLE
Show INFO linter message if no iconURL provided

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#1501]
Hi,

As explained [here](https://github.com/kubernetes/charts/issues/124), at Monocular, we plan on showing the list of Charts with its icons attached. 

In order to have an UI that it is not full of "default images" we might want to encourage people to submit their charts including an icon_url.

This could be done showing an INFO message in the linter if this value is empty. What do you think @prydonius?

**Comment by lachie83** [comment]
I would also like to add https://github.com/kubernetes/charts/issues/171 to this issue. Currently suggestion is to have something like `helm lint -v` which adds recommendations. Thoughts?

**Comment by prydonius** [comment]
I think there is a suggestion level for the linter, which was intended for these purposes. I think it's fine to show suggestions by default without a verbose flag, but I don't have a strong opinion there.

**Comment by mcallaghan-geotab** [comment]
We find the `INFO` log level a bit annoying. If one has no use for `icon`, there seems to be no way to suppress it?
Is there a recommendation to include the `icon` key/value perhaps with a `null` or *empty* value as a workaround?
