### ISSUE TITLE
Make dm client feel more like kubectl

### ISSUE THREAD

**Issue by bmelville** [kubernetes/helm#152]
I think the dm client should look and feel more like kubectl. Right now it has a bunch of random verbs so is pretty hard to understand and use.

I'm thinking more like this style of commands:

dm deploy <deployment-name> -t <template-path | type>
dm delete <deployment-name>
dm get deployments
dm get deployments <deployment-name>
dm get manifests --deployment <deployment-name>
dm get manifests <manifest-name> --deployment <deployment-name>
dm get type-instances
dm get type-instances <type>
dm get templates <git-repo>

**Comment by jackgr** [comment]
Down graded priority given the number of more pressing issues on our plate.
