### ISSUE TITLE
feature: verify chart without needing tiller

### ISSUE THREAD

**Issue by vdice** [kubernetes/helm#1520]
As a consumer of a signed helm chart wanting a minimal check to verify the provenance of said chart, and without needing a tiller deployment (or k8s cluster at all), it would be useful for a `helm install --verify <signed chart> --dry-run` invocation to run client-side only.  (Whereas even with `--dry-run`, a tiller deployment is necessary).

Or, perhaps `helm verify <signed chart>` could be modified to fetch the associated `.prov` file if it is not found locally?

(Either option of course includes the expectation that the public key associated with the signed chart exists in an accessible keyring at verification time.)

**Comment by technosophos** [comment]
Could you use `helm fetch --verify` to do this?

**Comment by vdice** [comment]
@technosophos indeed!  Thank you for the command suggestion.  Closing.
