### ISSUE TITLE
Upgrading helm client to latest version should work for all server versions?

### ISSUE THREAD

**Issue by brandoncole** [kubernetes/helm#1523]
We have several K8s clusters, each running different versions of Helm / Tiller on the servers right now.  Specifically we are running clusters with server versions:

* v2.0.0-beta.2
* v2.0.0-alpha.5

From a tooling perspective, our DevOps pipeline and developers would like to just use the latest version of the client to avoid working with specific versions of `helm` per cluster.  As it stands now if you use something like:

`brew cask uninstall --force helm && brew cask install helm`

To always ensure you have the latest, the `rc-2` will not work with either of these and results in the following errors:

```
Brandons-MBP:clusters brandoncole$ helm list
Error: client version is incompatible
Brandons-MBP:clusters brandoncole$ helm version
Client: &version.Version{SemVer:"v2.0.0-rc.2", GitCommit:"f8037c83c647b56d9ef42d0d5254e5fc563e3048", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-beta.2", GitCommit:"8a5550d0c6785eaa94eac80e0c1d11a92c355a02", GitTreeState:"clean"}
...
Brandons-MBP:clusters brandoncole$ helm list
Error: client version is incompatible
Brandons-MBP:clusters brandoncole$ helm version
Client: &version.Version{SemVer:"v2.0.0-rc.2", GitCommit:"f8037c83c647b56d9ef42d0d5254e5fc563e3048", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-alpha.5", GitCommit:"4de5c4aa578ed9ca173aff472f00d2167ec59a88", GitTreeState:"dirty"}
```

Is there a simple workaround or is this as expected?  @chrislovecnm any thoughts?

**Comment by chrislovecnm** [comment]
@technosophos / @michelleN I know one of you is in Seatle right now.  This is my ask :)

We and others are going to have an environment where your tooling is going to have SLAs around it.  Our SLAs are pretty lofty, just think lots of nines.  How do we get this sorted out, documented, and baked in so that our users, as in OSS community users, don't hit this problem again?

How can we help your team?

**Comment by technosophos** [comment]
For the most part, what you are experiencing is the ultra-strict guidelines on versioning in regards to pre-releases (Alpha, Beta, and RC).

The current rules for compatibility are:

For `X.Y.Z-PRERELEASE+BUILD`:

- BUILD does not impact compatibility at all
- Per the SemVer 2 spec, if a version has a PRERELEASE flag, it is incompatible with everything but an identical version. This includes RC pre-releases.
- `Z` releases are considered compatible
- `X` and `Y` releases are currently considered incompatible

So...

- `2.0.0-alpha.1` ONLY matches `2.0.0-alpha.1`
- 2.0.0 and 2.0.999999 are compatible
- 2.0.0 and 2.1.0 are currently incompatible (we may change this. We figured we'd start strict)
- 2.0.0 and 3.0.0 are incompatible

Hopefully, that means that as soon as 2.0.0 comes out, your lives should get easier.

As we work on 2.1.0, we'll test our assumptions about compatibility across minor (feature-only) releases.

**Comment by brandoncole** [comment]
Thanks @technosophos - that helps to explain this.  We're on the cutting edge so we've pretty much been using alpha and rc pre-release builds only.  So as long as the major.minor.patch versioning works as expected, when we get to those we should be good to go.  Thanks for the info.

**Comment by technosophos** [comment]
We've been testing this with the 2.0.0/2.0.1 branches, and I believe all is working as I described above. So I'll mark this as closed.

**Comment by markhu** [comment]
I got stuck on this error:

    Error: incompatible versions client[v2.7.2] server[v2.6.1]

Fix/workaround was to run this:

    helm init --upgrade

As faintly hinted by the output of running `helm init` which said.

> Warning: Tiller is already installed in the cluster.
> (Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)

That parenthetical statement is actually the important part. An additional warning should highlight the version mismatch, and suggest more strongly to run `--upgrade`.

**Comment by bacongobbler** [comment]
Am I safe to assume this was on Azure?

**Comment by markhu** [comment]
My `incompatible versions` issue was on MacOS where my `kubernetes-helm` was installed via HomeBrew.

**Comment by bacongobbler** [comment]
righto, but which cloud provider were you deploying tiller to? :)

**Comment by markhu** [comment]
AWS.

**Comment by dmaze** [comment]
My team is hitting exactly the issue @markhu described above: developers are running `brew upgrade` to get routine updates, getting a newer Helm client package, and then getting messages they don't understand like

```
Error: incompatible versions client[v2.9.0] server[v2.8.0]
```

Can Helm make a reasonable effort to interoperate with older versions of itself?  This gets to be a big issue when we have multiple clusters and multiple users and Homebrew is the principal path to getting a Helm client binary.

**Comment by yuchaoran2011** [comment]
Still happening even today. Did a `brew upgrade` just now and it broke `helm`, now getting `Error: incompatible versions client[v2.10.0] server[v2.9.1]`. @technosophos Can you re-open this issue?

**Comment by technosophos** [comment]
I left a long explanation of why we do things the current way on #4549

**Comment by ahaurat** [comment]
I had the same error as @yuchaoran2011
```
$ helm list
Error: incompatible versions client[v2.10.0] server[v2.9.1]
```

Updating the server wasn't an option for me so I needed to `brew install` a previous version of the client. I hadn't previously installed client[v2.9.1] (or any previous client version) and thus couldn't just `brew switch kubernetes-helm 2.9.1`. I ended up having to follow the steps in this SO answer: https://stackoverflow.com/a/17757092/2356383

Which basically says

- Look on Github for the correct `kubernetes-helm.rb` file for the version you want (2.9.1 in my case): https://github.com/Homebrew/homebrew-core/search?q=kubernetes-helm&type=Commits
- Click the commit hash (`78d6425` in my case)
- Click the "View" button to see the whole file
- Click the "Raw" button
- And copy the url: https://raw.githubusercontent.com/Homebrew/homebrew-core/78d64252f30a12b6f4b3ce29686ab5e262eea812/Formula/kubernetes-helm.rb

Now that I had the url for the correct `kubernetes-helm.rb` file, I ran the following:
```
$ brew unlink kubernetes-helm
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/78d64252f30a12b6f4b3ce29686ab5e262eea812/Formula/kubernetes-helm.rb
$ brew switch kubernetes-helm 2.9.1
```

Hope this helps someone.

**Comment by damien-roche** [comment]
It is difficult to accept that people are automatically upgrading working server versions when using the client. Why is this the recommended approach? What if the server upgrade breaks something in the cluster? Seems extremely naive to trigger a server upgrade every time before using the client.
