### ISSUE TITLE
Template rendering problem this parse int values defined in a vars configaration file.

### ISSUE THREAD

**Issue by dreyk** [kubernetes/helm#1524]
I have template that looks like this:
```
{{ $i,$t := range until .Values.Count }}
  bla bla bla
 {{ end }}
```

And configuration like this vall.yaml:
```
Count: 3
```

Rendering template doesn't work because .Values.Count  parsed from yaml file as float64, but "until" function required int64.

**Comment by technosophos** [comment]
Does using `toInt64` work? `range toInt64 .Values.Count | until`

**Comment by dreyk** [comment]
Function "toInt64" not defined. There is int64 function.
But It doesn't work.
```
{{range $i,$t := until (int64 .Values.count)}}
bla bla
{{end}
```
at <.Values.count>: wrong type for value; expected int; got int64

**Comment by dreyk** [comment]
My not very good and not very short workaround:
```
{{range $i,$t := until (atoi (printf "%d" (int64 .Values.count)))}}
bla bla bla
{{end}}
```
It will be perfect to have "int" function like "int64".

**Comment by dreyk** [comment]
I have added following pull request for it.
https://github.com/Masterminds/sprig/pull/19

**Comment by technosophos** [comment]
I merged that into Sprig. I'll update Helm to the latest version of Sprig right after 2.0.0.
