### ISSUE TITLE
helm install issues using stackpointcloud

### ISSUE THREAD

**Issue by archyufa** [kubernetes/helm#1525]
Trying to deploy helm charts on top of stackpointcloud.io K8s version 1.4.4

"helm init" works as expected. 
However "helm install <package name>" fails with following error:
#helm install redis
E1109 12:16:40.577442   20283 portforward.go:329] an error occurred forwarding 56957 -> 44134: error forwarding port 44134 to pod tiller-deploy-488961084-799ry_kube-system, uid : unable to do port forwarding: socat not found.
Error: transport is closing.

**Comment by technosophos** [comment]
This should be resolved by https://github.com/kubernetes/helm/issues/1507
