### ISSUE TITLE
Provide feedback during potentially long-running operations

### ISSUE THREAD

**Issue by sgoings** [kubernetes/helm#1526]
Fairly large charts can take a while for an operation (install/upgrade) to complete. For example, when upgrading [deis workflow](https://github.com/deis/workflow), helm doesn't give any output for 30-90 seconds while kubernetes resources are coalescing behind the scenes.

Any sort of progress indicator (indeterminate or determinate) during operations where helm is interacting with the kubernetes cluster would be 👍 .

**Comment by jchauncey** [comment]
Current Usecase:

If I am using helm to roll out new releases of my application I may want to use the `pre-install/pre-upgrade` hooks to build out to perform a database backup and then a subsequent liquibase migration. Both of these operations could possibly take several minutes to complete during which the client provides no feedback of its current status. 

Request:
During a `helm install/upgrade` of which there are hooks being used the helm list should log what is currently happening. Such as `running pre-install hook foo` or `running post-upgrade hook bar`. This also is useful for people who are running these types of commands from CI systems where they may want to see visual feedback on where their install/upgrade process.

**Comment by caleb15** [comment]
/reopen

Waiting around for a deploy without knowing what's happening is not great, to say the least. You could manually inspect pods while the deploy is happening, of course, but it would be much nicer if it was done automatically. Coming from ansible and terraform, where deploys are verbose to a fault, to helm, where deploys are almost totally silent, is quite a difference. There's definitely a happy medium to be found somewhere.
