### ISSUE TITLE
Remove/increase release name character limit

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#1528]
The 14 character release name limit was imposed in 
https://github.com/kubernetes/helm/issues/1071 due to a problem in many charts truncating names to 24 characters to create valid DNS names for services.

As of Kubernetes [v1.4.0-alpha.3](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v140-alpha3), service names of up to 63 characters are now supported, so the limitation is no longer necessary.

The only blocker to removing or increasing the release name limit is whether we want to continue supporting < 1.4 for this particular issue. Given it's sporadic and depends on the chart, we may want to delegate dealing with release name truncation to the chart developer. For example, most of the charts in [kubernetes/charts](https://github.com/kubernetes/charts) state they require > 1.4 with PVC provisioning.

cc @technosophos @viglesiasce

**Comment by gtaylor** [comment]
There was so much work that happened in 1.4 that I subjectively would hate to complicate things in the name of supporting a version that will probably fall off quickly. The PVCs alone are reason enough to just call 1.3 a wash, IMO.

There are still probably lots of 1.3 clusters out there in the wild, but there's a lot of incentive to get upgraded. There might be some short-term pain by requiring 1.4, but helm 2.x doesn't have a stable release yet. Now would be the time to say no to 1.3 if we were going to do it.

**Comment by sputnick** [comment]
+1

**Comment by prydonius** [comment]
@technosophos would we be able to get this in for 2.0.0?

**Comment by technosophos** [comment]
I think this mainly just involves removing the hard limit in one place, but it may break backward compatibility. That said... it breaks an anti-pattern that I _really_ don't want to propagate. Lemme feel out the Helm channel and see what people think
