### ISSUE TITLE
Feature request: -o json

### ISSUE THREAD

**Issue by sputnick** [kubernetes/helm#1534]
Barring no restful api for Tiller (and some logic only in helm cli) we have resorted to wrapping helm cli as "restful service". This works fine but some commands like "list", "search", "status"... are not very machine readable. It would be great to have a json output option like kubectl does with "-o json".

**Comment by jbehling** [comment]
We definitely need this. Right we're driving kubectl directly from Jenkins to do rolling updates, migrating to helm will help reduce a lot of the complexity involved scenarios where there are multiple deployments to update, however losing machine parseable output defeats the purpose.

**Comment by technosophos** [comment]
I think we could refactor the client output layer to have formatters for each command, with the default being "text" and other options being "yaml" and "json".

**Comment by TerraTech** [comment]
@sputnick It was a bit of a surprise that Tiller didn't have a full on RESTful remote API.  Have you published any of your RESTful work yet because we are looking at having to go down this road as well.

**Comment by technosophos** [comment]
@TerraTech  Does this meet your needs? https://github.com/AcalephStorage/rudder

**Comment by kjpopov** [comment]
-o yaml will be also great! 👍

**Comment by tcolgate** [comment]
`-o go-template` from kubectl would be handy too (but json is probably the minimum)

**Comment by rchakra3** [comment]
Is this still required and could I work on it? I'm looking for something to work on as a new contributor :)

**Comment by bacongobbler** [comment]
I think https://github.com/kubernetes/helm/pull/2950 handles `helm list` but you could take a look at that PR and port it over to other relevant commands!

**Comment by TerraTech** [comment]
/remove-lifecycle stale

bump

**Comment by bacongobbler** [comment]
Implemented via #3923. Any other top-level commands where --format makes sense should open a new ticket. Thanks!
