### ISSUE TITLE
Error with script install

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/helm#1542]
The script is using the sha, and running the script on Linux 64bit is failing. Used the script today.

**Comment by technosophos** [comment]
What was the error?

**Comment by BeauVrolyk** [comment]
Chris, we're having trouble understanding what the problem is. What's the low-down?  Errors? etc...??

**Comment by sgoings** [comment]
@chrislovecnm might your issue be resolved via #1553?

**Comment by michelleN** [comment]
reproduced on centos

**Comment by chrislovecnm** [comment]
👍

**Comment by technosophos** [comment]
@chrislovecnm We merged #1553. Does that fix it for you?

**Comment by chrislovecnm** [comment]
Yep
