### ISSUE TITLE
Move kubernetes-charts location

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#1543]
Currently, stable charts are pointed at https://storage.googleapis.com/kubernetes-charts. This puts it on a sub-path. Instead, can we move it to https://kubernetes-charts.storage.googleapis.com. This is top level and works today.

It would also ease the transition to a custom kubernetes domain.

**Comment by mattfarina** [comment]
I put a PR up at #1545.

**Comment by mattfarina** [comment]
FYI, docs at https://cloud.google.com/storage/docs/xml-api/reference-uris

**Comment by michelleN** [comment]
cc/ @viglesiasce @prydonius

**Comment by mattfarina** [comment]
Note, I'm going to make another change for the endpoint to be `https://` instead of `http://`.

**Comment by mattfarina** [comment]
#1545 has been updated. Ready for reviewer eyes.
