### ISSUE TITLE
Endpoint that returns a 404

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#1544]
In the code there are a few times `http://storage2.googleapis.com/kubernetes-charts/alpine-1.0.0.tgz` is referenced to. There is no comment about why this endpoint is being used and that URL returns a 404 and no package.

Should this be changed or a comment put in so the next person who stumbles on it understands?

**Comment by technosophos** [comment]
Yeah, we should at least comment that to explain it. Maybe we could point it to an existing chart, too.

**Comment by mattfarina** [comment]
I'm happy to comment it if I knew what was going on. Is it just to support showing an array of items at work?

**Comment by technosophos** [comment]
So `storage2` URLs are just there for tests and examples. There's no such thing, but since we changed `url: <string>` to `urls: <[]string>` we added those to illustrate.
