### ISSUE TITLE
feature request: Iterate line-by-line through a `{{.Files}}` object in a template

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1548]
It would be really nice to be able to do something like this in a template:

```
{{range .Files.EachLine "my/text/file"}}
  {{.}}
{{end}}
```

That would make it possible to process file lines before printing them in templates.

Pretty sure that would be a fairly minor change to https://github.com/kubernetes/helm/blob/master/pkg/chartutil/files.go

**Comment by prydonius** [comment]
+1 this could be pretty handy!

**Comment by technosophos** [comment]
Maybe it should be called `Lines()`

**Comment by technosophos** [comment]
Closed by #1666 YAY!
