### ISSUE TITLE
Need ability in templates to detect whether the current release is an upgrade

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/helm#1554]
A good amount of charts are randomly generating passwords when they are run. This causes issues when upgrading charts, causing passwords to be regenerated. 

What I would like to see is something along the lines of:

{{- if .Release.Upgrade }}
{{- end }}

Another approach could be to expose the release number:
{{- if .Release.Revision == 1 }}
{{- end }}

**Comment by viglesiasce** [comment]
From charts repo: https://github.com/kubernetes/charts/issues/217

**Comment by prydonius** [comment]
In the upgrade case, are you envisioning that the deployment of the secret be skipped so that it isn't overwritten?

**Comment by prydonius** [comment]
Another possibility to solving the issue in kubernetes/charts#217 would be to support dynamically generated values in some way, so that you could template `.Values.password = {{ random_password }}`, and then the upgrade could merge the original values with what's provided in the upgrade.

**Comment by technosophos** [comment]
I'm thinking that we should put both release number and something like `Upgrade` both on the  `{{.Release}}` object.
