### ISSUE TITLE
helm CLI incorrectly splits on commas even when quoted

### ISSUE THREAD

**Issue by aegixx** [kubernetes/helm#1556]
When using the `helm` command and overriding values using `--set`, if the key value contains a comma, the value is halted there.

I'm assuming the entire argument is being split on commas, regardless of escaping or quotes.

Testing:
```
$ helm install kubernetes-charts/mysql --set mysqlUser="test_mysqluser,blah,dee,dah" --dry-run --debug | grep test_mysqluser
```
RETURNS
```
          value: "test_mysqluser"
```

**Comment by rimusz** [comment]
I can confirm got cut by this bug yesterday too

**Comment by aegixx** [comment]
If someone can point me in the right direction (where in the code is this handled?) - I'll take a look at creating a PR.  To me, it looks like an issue @ https://github.com/kubernetes/helm/blob/master/cmd/helm/install.go#L268

If someone can confirm if I'm at least thinking correctly.

**Comment by technosophos** [comment]
@aegixx That is the correct location. That whole parser needs to be rewritten to be more robust. There's another issue with dots being unescapable. A PR would be awesome.

**Comment by databus23** [comment]
Instead of writing a better parser for handling the splitting accounting for quotes why not allow to specify `--set` multiple times? I realise this is a breaking change but would be cleaner and easier to maintain IMO.

**Comment by aegixx** [comment]
Unfortunately this won't help for my issue. I'm setting environment variables that have a longer string that just happens to contain a comma. Multiple sets won't help with that specific issue. 

--Bryan




On Fri, Nov 18, 2016 at 5:40 PM -0600, "Fabian Ruff" <notifications@github.com> wrote:












Instead of writing a better parser for handling the splitting accounting for quotes why not allow to specify --set multiple times? I realise this is a breaking change but would be cleaner and easier to maintain IMO.

**Comment by technosophos** [comment]
The unfortunate thing, @databus23, is that we can't break backward compatibility, and Option 2 would break the existing behavior.

**Comment by mcandre** [comment]
> we can't break backward compatibility

helm already breaks compatibility with the tiller, just bump major and fix this

**Comment by dominik-bln** [comment]
For anyone else coming up on this issue, there is a workaround by escaping the commas with a backslash:

https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set

Just as a side note, we still believe that this a very unintuitive behaviour that needs a fix. Our use case right now was LDAP credentials, which naturally contain commas, but it also seems very problematic for autogenerated passwords, that might accidentally contain a comma.

**Comment by whereisaaron** [comment]
Just been banging my head against this with helm 2.8.2. You can now have multiple '--set' arguments, so the old comma syntax can (or should) be deprecated. It was always clunky and I stopped using it as soon as multiple '--set' worked. However it is still the case that as soon as I have a comma in the value helm splits it and borks the deployment. No amount of quoting seems to work around it.

Could we ensure we deprecate the commas (maybe with a warning message) in 2.9.x, and not include it in 3.x?

**Comment by whereisaaron** [comment]
Although I couldn't find any mention or example in the document, reading the improved parsing code, you can 'escape' a comma, e.g. `pass\,word` and bypass the splitting. So `--set 'my.password=pass\,word'` will work until the comma splitting can be deprecated.

**Comment by kvolkovich-sc** [comment]
> About the comma-separated key value pairs, having the option to turn comma-separation off would be nice, as we need to specify strings with multiple commas in them (eg. mongo connection strings), and escaping these from within shell scripts/CD tooling/environment variables can be a pain.

@dsample ®

**Comment by rcjsuen** [comment]
Trying to define the cron schedule on the command line but this is making things more difficult than it needs to be. :(

**Comment by darkn3rd** [comment]
This is not a good user experience.  For an escape, I had to do something like this:

```bash
helm install dev dgraph/dgraph \
  --set alpha.extraEnvs[0].name=DGRAPH_ALPHA_WHITELIST \
  --set alpha.extraEnvs[0].value='10.0.0.0\/8\,172.16.0.0/12\,192.168.0.0\/16'
```

**Comment by FilBot3** [comment]
> This is not a good user experience. For an escape, I had to do something like this:
> 
> ```shell
> helm install dev dgraph/dgraph \
>   --set alpha.extraEnvs[0].name=DGRAPH_ALPHA_WHITELIST \
>   --set alpha.extraEnvs[0].value='10.0.0.0\/8\,172.16.0.0/12\,192.168.0.0\/16'
> ```

Just spent 4 days beating my head against the desk to find this. I will try this next. I ended up writing out to a temp file then telling helm to use a second `--values` file. This does seem like it's still an issue.

**Comment by vpapidokha** [comment]
Still in the same situation.

**Comment by FilBot3** [comment]
> Still in the same situation.

you should put your contents into a YAML file and provide it as an extra --values file. See: https://github.com/helm/helm/issues/1556#issuecomment-928177543

**Comment by vpapidokha** [comment]
> > Still in the same situation.
> 
> you should put your contents into a YAML file and provide it as an extra --values file. See: [#1556 (comment)](https://github.com/helm/helm/issues/1556#issuecomment-928177543)

Thanks a lot. I've escaped comas and this helped. It would be too harsh to create a separate values file just for one parameter.

But I will be glad if someone will add the mention of this behavior to docs. Because I didn't find specific info on this.

**Comment by very-doge-wow** [comment]
Not quite sure how https://github.com/Nordix/helm/commit/54eb73b4239a2ec144085f569774aea14a6c6674 is supposed to fix this and I still encounter this issue when using helm v3.14.2.

Is it just me?

**Comment by Yakuza-UA** [comment]
> Not quite sure how [Nordix@54eb73b](https://github.com/Nordix/helm/commit/54eb73b4239a2ec144085f569774aea14a6c6674) is supposed to fix this and I still encounter this issue when using helm v3.14.2.
> 
> Is it just me?

No, it’s not just you. I’ve just spent good few hours pulling my hair out in attempt to troubleshoot this. Everything worked in dev environment where I deploy using Docker Compose, but once I’ve pushed to Test AKS using helm… it stopped. Thought there was a problem with connectivity to LDAP server but it was a coma in a user DN. omg I can’t believe it

**Comment by danrspencer** [comment]
I just spent a while fighting this one myself, the best solution I found that I've not seen suggested yet is to echo out the YAML values and pipe it into Helm, e.g.

```
echo -e "
hello:
   world: earth,mars,jupiter
" | helm install . --values -
```

Annoying for setting a single values but if you're setting lots it's probably actually clearer than many `--set` flags.
