### ISSUE TITLE
impossible to set string values on the command line that look like floats 

### ISSUE THREAD

**Issue by databus23** [kubernetes/helm#1558]
I have a template which contains this:
```
{{.Values.image.repository}}:{{.Values.image.tag}}
```
trying to do `helm install --set image.tag=20161115.1` yields this:
```
hub.global.cloud.sap/monsoon/monsoon-dashboard:2.0161116e+07
```

trying to do `helm install --set 'image.tag="20161115.1"'` yields this:
```
hub.global.cloud.sap/monsoon/monsoon-dashboard:"20161115.1"
```

I think the problem lies in [cmd.helm.typedVal](https://github.com/kubernetes/helm/blob/62df1ad3588e8d4791423aec19d46bc383438c4f/cmd/helm/install.go#L293).

Seems to to me as it stands passing a string that looks like a float via cli args is not possible atm.

**Comment by jchauncey** [comment]
Have you tried doing that with no quotes around image.tag? so `--set image.tag=20161115.1`

**Comment by databus23** [comment]
@jchauncey yes, see above. That's were it all started.

**Comment by technosophos** [comment]
I particularly "like" how it helpfully converts the presumed float to scientific notation!

@databus23 does it make the most sense to you if we simply added support for quotes? Other options would be:

- Revert to treating all --set params to strings (which caused problems for some)
- Allow explicit casts (`--set foo=string(1.23)`)
- Create a bunch of flags for different primitives: `--setInt`, `--setString`, etc

**Comment by aegixx** [comment]
Related to #1556

**Comment by TerraTech** [comment]
@technosophos I ran into this yesterday by trying to:  helm install foo --set mnum="05"
I wanted "05" to be a string and not a float.

My +1 would be for >>  _Allow explicit casts (--set foo=string(1.23))_

I think adding a bunch of different primitives is bloated solution for something that would be rarely needed.  Having the ability to reach into the toolbox and using an inline cast would provide a streamlined interface and grant access to the full range of types.

**Comment by peay** [comment]
@technosophos can you say a few words about what is the final solution to this issue implemented by #1576? I've been having the same issue in `v2.1.0`.

**Comment by technosophos** [comment]
@peay we are still tracking the float issue in #1707. There are a few hacky work-arounds there, but we don't have a final solution yet.

**Comment by peay** [comment]
Ah, hadn't found this one. The replace workaround should do the job, thanks!

**Comment by arturo-c** [comment]
@technosophos I created a pr for this issue https://github.com/kubernetes/helm/pull/3599, I went with option 3, let me know if its a viable solution.

**Comment by todaywasawesome** [comment]
This is still a real issue that should be resolved. For anyone looking for a workaround, I'm adding letters to any character. In my use case, instead of referencing images based on their commit SHA, I'm adding their branch name. So instead of `5937127` I do `master-5937127`
