### ISSUE TITLE
Show/filter helm releases by namespace

### ISSUE THREAD

**Issue by spiddy** [kubernetes/helm#1563]
As a use case I'd like to be able to deploy charts on separate namespaces and have a way to `helm list` a specific namespace. Currently there is no easy way of doing that.

I don't want to clutter helm list with more columns but this seems an important info on a multi-namespace cluster. Maybe we can add this with an optional flag (something similar to `kubectl -o wide` - related to #1534 on formatting subject).

A filtering field could be something of sort:

`helm list -n kube-system`

in order to show only releases inside the kube-system namespace.

**Comment by ligc** [comment]
We also have a use case that needs to list the helm releases for a specific namespace.

**Comment by spothala** [comment]
Even i need to check whether a release exists under a specific namespace.

**Comment by larryrensing** [comment]
i'll take this one on

**Comment by technosophos** [comment]
Assigned to @larryrensing . GitHub is not cooperating, so I temporarily assigned to myself.
