### ISSUE TITLE
docs: Overview of CI/CD and Config Management setups

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#1564]
On several occasions I've been asked for some practical guidance on setting up different CI/CD and configuration management systems for Helm. Would be good to create a doc that captures some of the workflows.

Examples:

- Signing charts in Jenkins https://deis.com/blog/2016/workflow-helm-charts-signed/
- Croc-Hunter Jenkins deployment https://github.com/lachie83/croc-hunter

**Comment by bacongobbler** [comment]
I think there's some other blog posts we have planned to help shed some of our usage with uploading Workflow's charts to S3. If anyone wants to read some DSL, it's available here: https://github.com/deis/jenkins-jobs/blob/master/jobs/component_chart_publish.groovy

**Comment by technosophos** [comment]
Also this one: https://medium.com/@enxebre/gitlab-consumer-driven-contracts-helm-and-kubernetes-b7235a60a1cb#.xwp1y4tgi

**Comment by technosophos** [comment]
Should also add Rudder: https://github.com/AcalephStorage/rudder

**Comment by v1k0d3n** [comment]
@technosophos it might take me a little while, but I could probably take this one as we work through our project. if you want to assign it to me?

**Comment by technosophos** [comment]
Sure. Consider it yours.

**Comment by thomastaylor312** [comment]
I might be able to add an example to this one we finish our CI/CD setup with helm

**Comment by v1k0d3n** [comment]
Thanks @technosophos! @thomastaylor312 want to collaborate? I'm sure we can break this issue up into a few different commits. :)

**Comment by thomastaylor312** [comment]
@v1k0d3n: Mine is still in flight right now, but I would love to contribute back once we have smoothed things out. I can also help review anything 😄

**Comment by technosophos** [comment]
A great new post on this: https://medium.com/@gajus/the-missing-ci-cd-kubernetes-component-helm-package-manager-1fe002aac680#.o8w0b3xux
