### ISSUE TITLE
plus(+) sign is interpreted as space in the path part of URLs by amazon

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#1565]
This issues is only for the charts hosted on the amazon where if we have plus(+) sign in the path it is interpreted as space and the helm commands(fetch,dependency,install) fail because of it. This adds certain restrictions to using proper semver(http://semver.org/)  for the version which allows plus sign to add build metadata.
related issue on amazon https://forums.aws.amazon.com/thread.jspa?threadID=55746

**Comment by rbwsam** [comment]
According to that amazon forum thread encoding the URL works fine. Would it be a terrible idea to encode all URLs used by helm commands?
