### ISSUE TITLE
Issue warning when requirements.yaml has something that charts/ doesn't?

### ISSUE THREAD

**Issue by lachie83** [kubernetes/helm#1567]
Helm will happily install a chart without the requirements being available in charts/. Please issue a warning when that is the case.

**Comment by technosophos** [comment]
There are several ways we could do this, but my preference would be to attempt to do it on the client side as follows:

- `helm package` would warn if it detected requirements.yaml entries were missing from chart
- `helm install` would warn if the chart is a directory, and the same condition obtains (req in file, not in dir)
- `helm upgrade` would implement the same as `helm install`

If we must, we could add logic in Tiller to do this check. Currently, Tiller is blissfully unaware of the requirements.yaml file, though it does have access to it.

**Comment by prydonius** [comment]
@technosophos your proposal sounds good to me, I'm not sure there's much benefit in offloading the check to Tiller.

**Comment by micahhausler** [comment]
Could you throw in a `--strict` option (similar to `helm lint`) that would fail if a dependency wasn't avaialable?

**Comment by wilkers-steve** [comment]
If no one objects, I'll take a shot at this one.  I'll work on getting a PR together by the end of the week

**Comment by technosophos** [comment]
@wilkers-steve any update on this?

**Comment by technosophos** [comment]
Via Slack, @wilkers-steve says he is still working on this.
