### ISSUE TITLE
Helm appears to choke on some config maps with large file resources. 

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/helm#1571]
Example: https://gist.github.com/andrewhowdencom/49e17febad8afa418fe96cc30416bc17

Command: 
```
$ helm install grafana --name=grafana --set='adminUser=trustmebro,adminPassword=hahanope'
Error: parse error in "grafana/templates/boards.cm.yaml": template: grafana/templates/boards.cm.yaml:1792: function "container_name" not defined
```

**Comment by technosophos** [comment]
I believe the reason is because this looks to the Tiller renderer like a Go Template directive:

https://gist.github.com/andrewhowdencom/49e17febad8afa418fe96cc30416bc17#file-gistfile1-txt-L1889

And Tiller does not have a function named `container_name`

**Comment by andrewhowdencom** [comment]
Ah, neat! I probably should have caught that. I'll be more mindful of this in future.

**Comment by technosophos** [comment]
Should we close this?

**Comment by andrewhowdencom** [comment]
I think yes. I will work out how to escape them, and create a pull request for the docs (if there isn't already).
