### ISSUE TITLE
bug: `helm inspect values chart > values.yaml` adds fetched output

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes/helm#1574]
Using Helm v2.0.0, when I run `helm fetch values chart > values.yaml`, I see this on the header:

```
><> helm inspect values stable/jenkins | head -n 1
Fetched stable/jenkins to jenkins-0.1.0.tgz
```

I expected that to be displayed on stderr so that piping it would give me a 1:1 representation of the values.yaml file in the repo

**Comment by technosophos** [comment]
Yeah, that should be fixed.
