### ISSUE TITLE
Helm 2.0.0 does not support StatefulSet

### ISSUE THREAD

**Issue by alanmeadows** [kubernetes/helm#1581]
The following manifest, which deploys fine under kubectl from v1.5.0-beta.1 does not work with helm-2.0.0-beta2.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.1", GitCommit:"8c6525e891be1c44cbdd6fcf53097a3adb11d68c", GitTreeState:"clean", BuildDate:"2016-11-18T22:06:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.1", GitCommit:"8c6525e891be1c44cbdd6fcf53097a3adb11d68c", GitTreeState:"clean", BuildDate:"2016-11-18T22:01:26Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

Example of a manifest that deploys under kubectl 1.5.0:

```
$ head -5 /tmp/q.yaml 
---
apiVersion: apps/v1beta1
kind: StatefulSet
```

This results in the following tiller error:

```
~/gopath/src/k8s.io/helm/bin$ ./tiller
Tiller is listening on :44134
Probes server is listening on :44135
Storage driver is ConfigMap
2016-11-22 18:36:58.784560 I | Getting release "dangling-spong" (v1) from storage
2016-11-22 18:36:58.804081 I | Executing pre-install hooks for dangling-spong
2016-11-22 18:36:58.804119 I | Hooks complete for pre-install dangling-spong
2016-11-22 18:36:59.226764 I | warning: Release "dangling-spong" failed: unable to decode "": no kind "StatefulSet" is registered for version "apps/v1beta1"
2016-11-22 18:36:59.226810 I | Create release "dangling-spong" (v1) in storage
2016-11-22 18:36:59.275063 I | Failed install perform step: release dangling-spong failed: unable to decode "": no kind "StatefulSet" is registered for version "apps/v1beta1"
```

apps_v1beta1.json appears to be missing entirely from k8s.io/helm/vendor/k8s.io/kubernetes/api/swagger-spec

This is a K8s v1.5 change (v1alpha PetSets to v1beta1 StatefulSet) that is coming it would be good to support apps/v1beta1 resources to begin working with it.

**Comment by technosophos** [comment]
Can you do me a favor and run `kubectl` to list the Kubernetes API endpoints? The error you are getting above is not the one I would have assumed. Basically, that notice is indicating that there is no registration endpoint for stateful sets. I'm wondering if Kube 1.5 has some compatibility layer that is basically translating between PetSets and StatefulSets.

For relevant background: Tiller uses the 1.4 API (since it's current stable). When it comes to supported resource kinds, it queries the API endpoint on Kubernetes, but it sets the user agent to 1.4. If k8s has backward compatibility code for PetSets, it may be getting in the way here.

**Comment by enisoc** [comment]
Could be because of https://github.com/kubernetes/kubernetes/pull/35840

**Comment by janwillies** [comment]
FWIW, if I compare kubectl-1.3 and 1.5 `kubectl api-versions` against an 1.5-apiserver I get different results (notably apps/v1beta1 added)

**Comment by technosophos** [comment]
I think @enisoc is right about these being related. As we upgrade the internal library from k8s 1.4 to 1.5, I am hoping this gets fixed.

**Comment by adamreese** [comment]
1.5 support in now merged

**Comment by BugRoger** [comment]
Is it possible that this change breaks `PetSets` in a 1.4.6 cluster? The same chart works fine with Helm 2.0.2. I'm getting the following error:

```
Error: UPGRADE FAILED: failed decoding reader into objects: unable to decode "": no kind "PetSet" is registered for version "apps/v1alpha1"
```

Using 

```
kubectl version                                                                                                                                                 1 ↵
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6.monsoonctl.v201612081525", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"201612081525", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.6-1+530ad0e577004a", GitCommit:"530ad0e577004a2f2b3c5ab620af72957e686a78", GitTreeState:"clean", BuildDate:"2016-12-05T14:26:14Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version                                                                                                                                                    0 ↵
Client: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
```

**Comment by alanmeadows** [comment]
I'm somewhat surprised for this to be the case, the 1.5 internal library is supposed to be backward compatible?

**Comment by alanchchen** [comment]
I've encountered similar error.

```
helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
```

```
helm install -n myapp kubernetes/myapp
Error: release myapp failed: unable to decode "": no kind "PetSet" is registered for version "apps/v1alpha1"
```

**Comment by technosophos** [comment]
Our plan has been to suggest people use 2.0.x for working with Kubernetes 1.4 rather than try to compensate for Kubernetes' breaking its API with no internal work-around. If we start down the path of maintaining Kubernetes backward compatibility hacks in Tiller, things will get pretty yucky pretty fast.

Sorry. I think this PetSet->StatefulSet thing has been a learning experience for all of us, and has definitely led to wasted hours.
