### ISSUE TITLE
should helm assume dynamic PV is setup for a cluster? or should we offer PV help in the CLI?

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#1583]
its going to be common for Charts to have `PersistentVolumeClaim` resources. Though the actual `PersistentVolume` will change based on the cluster (e.g. different cloud providers).

If a cluster has no dynamic PV enabled; Charts with PVCs won't startup properly - which could lead to odd errors for the user (they may not know much about PV / PVCs). 

I wonder if we need to have some kind of lifecycle in helm that waits to really start the Chart until the PV requirements are met? I guess with cloud native we have to assume anything could go down or not be available at any time; but I wonder if we might want to make suitable PVs being available as a requirement before an app can really be started? (e.g. telling the user the dynamic PV or static PVs that are required to be able to run the app).

Or at least worse case provide a reasonable UI to help diagnose which apps haven't started due to PV issues etc.

**Comment by technosophos** [comment]
I wonder if there is a good way for us to create a `Capabilities` object and inject that into a template so that the template author could do something automatic:

```
{{ if .Capabilities.PV }}
# Set up PVC
{{ else }}
# Use an emptydir or something
{{end}
```

Other things we could expose would be the APIs (e.g. `batch/v1beta1`). What else?

Would that make it easier to solve this particular problem? /cc @viglesiasce @prydonius

**Comment by technosophos** [comment]
We have yet to figure out a way to do this programmatically. It does not appear that Kubernetes gives any cues about how the PV/PVC subsystem is setup.

**Comment by bacongobbler** [comment]
labelling as question/support until we have a more solid discussion around how we can fix this programmatically. Things that pop off the top of my head:

- this may eventually get fixed upstream with better PV management tooling
- a plugin may be a good way to create PVs on-the-fly before a `helm install`?

**Comment by jstrachan** [comment]
I've noticed charts often solve this these days by allowing PVC storage annotations & sizes to be configured in the values.yaml - which seems a reasonable solution to me.

**Comment by prydonius** [comment]
Yes, I don't believe this is needed anymore with the abstractions PVCs and StorageClasses provide. I think we can close this out.
