### ISSUE TITLE
feature request: shell auto-completion like kubectl and gcloud

### ISSUE THREAD

**Issue by MikeLeonard** [kubernetes/helm#1584]
Hi

kubectl and gcloud both have easy bash-completion as they have the 'completion' command
More info [here](http://kubernetes.io/docs/getting-started-guides/kubectl/)

Could this be added to helm? Is there any auto-completion at the moment, I couldn't find any?

Thanks

**Comment by technosophos** [comment]
There's a PR opened for this: https://github.com/kubernetes/helm/pull/1484

That PR is sort of on hold, though for no particularly good reason. But if you want to look at the description of the issue and give some feedback, I'd be happy to try to accelerate that PR again.

**Comment by technosophos** [comment]
If you're up for testing it... https://github.com/kubernetes/helm/blob/master/scripts/completions.bash

**Comment by technosophos** [comment]
Closed by #1484
