### ISSUE TITLE
Disable hooks not working with upgrade

### ISSUE THREAD

**Issue by royjs** [kubernetes/helm#1590]
The --disable-hooks doesn't work when doing an `helm upgrade`.
 It does work with a `helm upgrade --install` when actually doing an install.

I tested the problem locally and was able to fix it with a simple line.
It seems that in the [client.go](../blob/master/pkg/helm/client.go#L133) file it's missing a `req.DisableHooks = h.opts.disableHooks` after line 133

Without this the setting is lost and is never sent to tiller.

**Comment by technosophos** [comment]
Good catch. Thanks.
