### ISSUE TITLE
helm install output isn't alligned

### ISSUE THREAD

**Issue by rothgar** [kubernetes/helm#1593]
When running `helm install` the output for sections is space aligned but not lined up in columns because resource name lengths are different. This isn't a big deal but sometimes hard to read output for things that have many columns (e.g. services)
Here's an example after installing workflow.
![selection_015](https://cloud.githubusercontent.com/assets/371796/20689070/707396f6-b578-11e6-8bf7-6c5ca8fd44b6.png)

**Comment by technosophos** [comment]
That formatting seems to come from the kubectl library. We should probably manually re-parse it and use the same Table UI that we use elsewhere. So the place to do that would be `cmd/helm/status.go`
