### ISSUE TITLE
Add support for automated Windows build

### ISSUE THREAD

**Issue by rodcloutier** [kubernetes/helm#1596]
It would be nice to have an automated build for Windows.

**Comment by technosophos** [comment]
@rodcloutier mainly what we need is someone to test for us. We had built Windows binaries in the past, but none of us currently run Windows, so testing fell by the wayside.

**Comment by rodcloutier** [comment]
Non problem, we can test on our side. There will be several members of my team members using helm on Windows on a regular basis.  This is why @secat Submitted what we found earlier today to make helm work on Windows.

**Comment by technosophos** [comment]
Okay, I opened a PR that adds windows/amd64 builds. As soon as it gets merged, canary builds will be automatically created. Then we'll have some actual builds to test.

**Comment by mattfarina** [comment]
What about using [AppVeyor](https://www.appveyor.com/) to do windows CI alongside Circle?

**Comment by technosophos** [comment]
Okay, when I merged #1601, this was closed. But the canary builds are now building for Windows.
