### ISSUE TITLE
proposal: fromYaml function

### ISSUE THREAD

**Issue by vreon** [kubernetes/helm#1604]
This would allow chart authors to load data structures from files, so they can reduce repetition in templates. It's sort of possible to do this today via `values.yaml`, but that can mislead chart users into thinking the data is configurable.

**Comment by technosophos** [comment]
Assuming a YAML file like this (`foo.yaml`):

```yaml
foo: bar
```

I'm figuring this would be implemented like this:
```
{{ $data := .Files.Get "foo.yaml" | fromYaml }}
{{ $data.foo }}
```

And the output would be:

```
bar
```

This would also make it possible to parse YAML inline, which solves a certain (hopefully rare, hopefully temporary) case where YAML blobs need to be passed in globals.

**Comment by technosophos** [comment]
Any input @prydonius @viglesiasce @lachie83 ?
