### ISSUE TITLE
Can't connect to GKE kubernetes cluster with fresh install

### ISSUE THREAD

**Issue by csaintc** [kubernetes/helm#1630]
# Helm version

```
10118 ◯  helm version                                                                                                                                                                                   ⏎
Client: &version.Version{SemVer:"v2.0.1", GitCommit:"dc87ea8dd0111164c720fd13b4eb8a905f97ac62", GitTreeState:"clean"}
Error: cannot connect to Tiller
```
# K8 version:
```
1.4.6
```

# The issue
When i try and do an install, I get the message:
```
10110 ◯  helm list
Error: Error forwarding ports: error upgrading connection: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-[redacted]"?
```

Please advise

**Comment by technosophos** [comment]
(We all discussed this in Slack. Just "officially" following up here.)

Helm uses the Kubernetes proxy. The thing to test is `kubectl proxy`. If that doesn't work, Kubernetes is not quite configured properly. It might be an issue with local Kube config, or it might be something on the Kubernetes API server.

We should probably add this to install_faq.md. I'll mark this as a `starter` for anyone who feels like doing that.

**Comment by gianrubio** [comment]
@technosophos similar issue here, I created a new cluster and forgot to move the new config to ~/.kube. Only reading this issue I figured out what was wrong.

When I run the kubectl I get the error
```
$ kubectl get pods
Unable to connect to the server: x509: certificate signed by unknown authority
```

I guess a verbose message could solve the issue, same as

```
$ helm version
Client: &version.Version{SemVer:"v2.0.0", GitCommit:"51bdad42756dfaf3234f53ef3d3cb6bcd94144c2", GitTreeState:"clean"}
Error: cannot connect to Tiller. Do you have connection to your kubernetes cluster? 

```
