### ISSUE TITLE
--values flag not working anymore with upgrade command

### ISSUE THREAD

**Issue by royjs** [kubernetes/helm#1631]
The 2.0.1 version broke the `--values` flag of the `upgrade` command. When I use a values file it returns the following error:
`Error: failed to parse configs.yml: error unmarshaling JSON: json: Unmarshal(non-pointer map[string]interface {})`

The problem is with Unmarshal on [line 174 of the upgrade.go file](../blob/master/cmd/helm/upgrade.go#L174) The 2nd argument needs to be a pointer.

The line should be `if err := yaml.Unmarshal(bytes, &base); err != nil {`

**Comment by technosophos** [comment]
Ugh. My mistake. I'll PR the fix right away.

**Comment by technosophos** [comment]
Alright, I owe you an _INSERT DRINK OF CHOICE_ for that one. So sorry.

**Comment by royjs** [comment]
Thanks for the quick fix. Hopefully it will be merged and released soon :)
