### ISSUE TITLE
Support symbolic directory links

### ISSUE THREAD

**Issue by Dominik-K** [kubernetes/helm#1639]
To use different charts together as subcharts, it would be good to "import" their folders via symbolic directory links. Currently Helm returns: `Error: error reading charts/grafana read /Users/.../charts/grafana: is a directory`

**Comment by databus23** [comment]
Thought about this as well. I think using symlinks would be super useful for developing complex charts with many subcharts that use `requirements.txt`. For development all subcharts could by temporary symlinked to a local checkout of the subchart (which may even be in the same repository, [cough](https://github.com/sapcc/openstack/helm)). When everything works the changes to required charts are already in the right place and just need to by commited.

**Comment by technosophos** [comment]
What should happen if `charts/` has symlinks and a user runs `helm package`?

**Comment by databus23** [comment]
Well packing the symlink itself not helpful so I would find it useful if package would follow symlinks and slurp everything like `tar -L` (unix) or `tar --dereference` (GNU).

**Comment by Dominik-K** [comment]
I didn't thought about packaging, yet. In this case, symlinks would confuse the packaging idea. The subcharts are dependencies of the package, so they shouldn't be included in the package itself. My use case is in the developing stage, not meant for publishing. Packaging is about the latter, right?

So, to better handle both cases, I think a `localPath` field to the requirements.yaml file will fit better. The path should be relative with links to upwards directory, as well.

What do you think?

**Comment by kfox1111** [comment]
+1 to localPath option in requirements.yaml. That would solve an issue kolla-kubernetes is having. Would make the build system much cleaner.

**Comment by technosophos** [comment]
Can someone mock up an example of usage here?

**Comment by kfox1111** [comment]
See github.com/openstack/kolla-kubernetes/helm

Packages under microservices depend on kolla-common.

Stuff in services dir will depend on microservices packages.

Being able to put a relative path dependency from microservice directly to the chart for the kolla-common would make for much easier builds. Helm dep up would just cp -a to the chart subdir.

**Comment by jascott1** [comment]
@thomastaylor312 Can we close this since we have relative paths in requirements and #2010 was merged?

**Comment by thomastaylor312** [comment]
@jascott1 Yessir, that sounds like a plan. Thanks for bringing this back up

**Comment by bacongobbler** [comment]
re-opening due to #2938. The PR that fixed this ticket introduced a library that uses a BSD+patents license which is in direct conflict with Apache v2's license.

A good writeup on the situation is here (on React, but the discussion is also relevant for Helm): http://writing.jan.io/2017/08/19/understanding-the-facebook-vs-asf-license-kerfuffle.html

**Comment by Vrtak-CZ** [comment]
Is there any chance to get symlink support back in 2.7.x ?

**Comment by thomastaylor312** [comment]
@Vrtak-CZ If someone is willing to write up some code to handle it, we would love to merge that in, but it will probably difficult for anyone from the core team to get to it

**Comment by balboah** [comment]
@Vrtak-CZ @thomastaylor312 PR waiting!

**Comment by thomastaylor312** [comment]
Thanks @balboah!
