### ISSUE TITLE
Helm is converting my git tag to exponential form

### ISSUE THREAD

**Issue by colemickens** [kubernetes/helm#1643]
I use a git short commit hash as my docker tag. I pass it to `helm install` as a `--set` parameter.

`$ git describe --always` = `58467965`

`helm install ./polykube --set image.registry="colemickpoly58467965-microsoft.azurecr.io",image.tag="58467965",nameOverride="polykube",image.username="xyz",image.password="abc"
`

Unfortunately, it's rendered out in exponential form:

`failed to "StartContainer" for "aspnet-nginx" with ErrImagePull: "couldn't parse image reference \"colemickpoly58467965-microsoft.azurecr.io/polykube-aspnet-api-nginx:5.8467965e+07\": invalid reference format"`

`Image:              colemickpoly58467965-microsoft.azurecr.io/polykube-aspnet-api-nginx:5.8467965e+07`

Suspected as related: https://github.com/kubernetes/helm/pull/1451 (cc: @michelleN)

**Comment by colemickens** [comment]
It seems to happen even when the git commit short hash has the alpha hex characters in it. I suspect this was only working for me for a while since I was actually using `git describe --always --dirty` and my workspace was in progress and thus the git commit hash was actually `c573904-dirty`  and didn't get parsed as an int.

**Comment by databus23** [comment]
I think this is the same as https://github.com/kubernetes/helm/issues/1558.
This should have been fixed with: https://github.com/kubernetes/helm/pull/1576 which is in `2.0.1`.
What version of helm are you running?

**Comment by colemickens** [comment]
I was on `2.0.0`. I'll try with `2.0.1` this evening.

**Comment by colemickens** [comment]
Haven't repro'd it yet on `2.0.1` or `2.0.2`. Closing this.

**Comment by borekb** [comment]
We're seeing this in Helm 2.5.0, for example, `$ helm upgrade --set image.tag="9275389"` produces image tag `9.275389e+06`.

**Comment by rdpa** [comment]
Also seeing this in helm 2.6.1

`$ helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}`

**Comment by holybit** [comment]
Can we re-open this issue? It's not fixed.

In my case, seeing this below on `--set image.tag=5997578`:

```bash
$ kubetctl describe po msj-treasure-map-msj-treasure-map-192172122-dnb80
...
Events:
  Type     Reason         Age               From                                    Message
  ----     ------         ----              ----                                    -------
  Normal   Scheduled      1m                default-scheduler                       Successfully assigned msj-treasure-map-msj-treasure-map-192172122-dnb80 to ip-10-253-13-113.ec2.internal
  Warning  InspectFailed  15s (x9 over 1m)  kubelet, ip-10-253-13-113.ec2.internal  Failed to apply default image tag "596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-uwsgi:5.997578e+06": couldn't parse image reference "596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-uwsgi:5.997578e+06": invalid reference format
  Warning  InspectFailed  15s (x9 over 1m)  kubelet, ip-10-253-13-113.ec2.internal  Failed to apply default image tag "596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-nginx:5.997578e+06": couldn't parse image reference "596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-nginx:5.997578e+06": invalid reference format
  Warning  FailedSync     15s (x9 over 1m)  kubelet, ip-10-253-13-113.ec2.internal  Error syncing pod, skipping: [failed to "StartContainer" for "msj-treasure-map-uwsgi" with InvalidImageName: "Failed to apply default image tag \"596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-uwsgi:5.997578e+06\": couldn't parse image reference \"596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-uwsgi:5.997578e+06\": invalid reference format"
, failed to "StartContainer" for "msj-treasure-map-nginx" with InvalidImageName: "Failed to apply default image tag \"596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-nginx:5.997578e+06\": couldn't parse image reference \"596297932419.dkr.ecr.us-east-1.amazonaws.com/msj-trmap-nginx:5.997578e+06\": invalid reference format"
```

```bash
$ helm version                                                                                                                                                                             
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
Hey @holybit! #1707 tracks the issue where --set parses integers as scientific notation. Would you mind tacking on your comment there? Thanks!
