### ISSUE TITLE
Can not install chart from local folder on windows

### ISSUE THREAD

**Issue by sergik** [kubernetes/helm#1644]
Error when try install chart from local folder.
When try:
`helm install kong --name kong`
result:
`Error: release kong failed: no objects visited`
![image](https://cloud.githubusercontent.com/assets/358684/20928147/7dc6e8ea-bbd5-11e6-9b14-bdc6b68aff73.png)

**Comment by technosophos** [comment]
Related to #1645?

**Comment by technosophos** [comment]
I believe that the recent Windows patches (esp. #1645) have now fixed this issue. Please re-open if you can reproduce this with the Helm canary version.
