### ISSUE TITLE
Build helm binaries natively on darwin

### ISSUE THREAD

**Issue by databus23** [kubernetes/helm#1649]
This is a follow-up to a quick chat in Slack.

Currently helm builds its release binaries using CircleCI on linux. Unfortunately cross-compiled darwin binaries have subtle gotchas that hit mostly corporate environments.

Quoting [my comment on anther project](https://github.com/concourse/concourse/issues/601#issue-172635066)

> At least on darwin this has two side effects:
> * Custom CA's added to keychain are not picked up by fly (https://github.com/docker/machine/issues/491#issuecomment-73776254)
> * statically linked go binaries use the pure go solver as explained here (https://golang.org/pkg/net/)
>
>In our corporate environment statically linked darwin binaries are a constant cause of trouble. We run an internal CA for all intranet sites which does not work because of the first effect.
> The second is a problem for some major vpn clients (e.g. Big IP F5, Cisco) because the resolver reads the /etc/reslv.conf directly. Those VPN clients don't modify the resolv.conf when connecting to the corporate network but rather hook into the native darwin resolver to inject the corporate nameservers. Statically linked go binaries therefore can't resolve any corporate hostnames because they end up using the DNS servers from the local network where the VPN client is located.

One idea that was discussed on Slack was to maybe switch from a brew cask to an official  brew formula as those get build native on darwin.

**Comment by databus23** [comment]
Turns out there is already a `kubernetes-helm` formula in the brew-boneyard 💀 : https://github.com/Homebrew/homebrew-boneyard/blob/master/kubernetes-helm.rb

**Comment by technosophos** [comment]
Wow! That was super early! I wonder what it would take to get that formula back in.

**Comment by technosophos** [comment]
Anyone have an update to this? I agree that it would be nice to have it build in regular homebrew. But I don't have the time to get this done.

**Comment by databus23** [comment]
Seems line this fixed itself: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-helm.rb

**Comment by technosophos** [comment]
Marking this closed, since Homebrew fixed it.
