### ISSUE TITLE
Create a Service definition for using Tiller in-cluster

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#1659]
We are wanting to talk to tiller from within an existing cluster where tiller is already running. We have tossed around a few different solutions but would like to get some feedback:

- Find the pod ip using a service token and asking the kube-api
- Create a service definition that exposes a clusterip so we can talk to it using the cluster ip.

Thoughts? opinions?

**Comment by technosophos** [comment]
We've talked a lot about adding a service. And, in fact, we've encouraged people to do this when dealing with the problem you're talking about. The other way would be to use label selectors to find the pod. But it's tough to trust that that information will be accurate for a long period of time.

**Comment by ahawkins** [comment]
We will have the exact same problem shortly. My plan is to:

> Create a service definition that exposes a clusterip so we can talk to it using the cluster ip.

**Comment by jchauncey** [comment]
@ahawkins yeah thats what we did as well.

@technosophos Do you think this is something helm could add by default?

**Comment by technosophos** [comment]
We've talked about adding a service by default, but it's not been done. Would be a fairly basic PR, I think.

**Comment by technosophos** [comment]
I re-titled this as a feature, added it to the triage queue, and marked it "starter".

Really, all that would need to be done to implement this is to modify `cmd/helm/installer/install.go` to also install a Service definition.

**Comment by jchauncey** [comment]
@technosophos thanks =)
