### ISSUE TITLE
helm history shows which revision a rollback was rolled to.

### ISSUE THREAD

**Issue by Miyurz** [kubernetes/helm#1661]
As one tries to rollback to a previous release, it does mention that rollback is successful. It would be nice in

>  helm history

 for it to show which version it has been rolled back to.

Something like

Rev
1
2
3
4
5 => 2

where Revision 5 is nothing but actually release 2(that it was rolled back to)

**Comment by technosophos** [comment]
Yeah, that is a good idea. Let me see if I can figure out how to implement that.

**Comment by technosophos** [comment]
To do this, I'm adding a `DESCRIPTION` column with output like this:

```
⇒  helm history vetoed-sponge
REVISION	UPDATED                 	STATUS    	CHART       	DESCRIPTION
1       	Tue Jan 10 14:23:38 2017	SUPERSEDED	alpine-0.1.0	Install complete
2       	Tue Jan 10 14:23:51 2017	SUPERSEDED	alpine-0.1.0	Upgrade complete
3       	Tue Jan 10 14:24:20 2017	DEPLOYED  	alpine-0.1.0	Rollback to 2
```
