### ISSUE TITLE
Make helm tolerant of trailing / vs no trailing / for repositories

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/helm#1664]
The default Helm repo is https://kubernetes-charts.storage.googleapis.com/. In some cases charts are submitted with reference to https://kubernetes-charts.storage.googleapis.com without the trailing slash and this causes `helm dep up` to fail as it cannot find the correct repository. I think we should call the repos equivalent if the trailing slash is the only difference. 

Example PR test failure:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/202/pull-charts-e2e/330/

**Comment by technosophos** [comment]
I thought we fixed this in 2.0.2. Is that the version you are using?

**Comment by viglesiasce** [comment]
I was on 2.0.0. Will retest.

**Comment by viglesiasce** [comment]
I was able to reproduce this on v2.1.0 while trying to test the [owncloud chart pr](https://github.com/kubernetes/charts/pull/301):

+ helm dep up
Error: no repository definition for http://storage.googleapis.com/kubernetes-charts. Try 'helm repo add'
 viglesias  dev-f340    ~  git  charts  pr-301  ❓  $  helm version
Client: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}

**Comment by viglesiasce** [comment]
I take it back... this is related to the URL being just different.
