### ISSUE TITLE
Helm delete fails on first unsuccessful delete

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/helm#1665]
While testing PRs I often install 5-10 charts at a time and then turn them down when I'm done testing all of them. 

I often use the following syntax to delete them:
```shell
$ helm delete --purge loopy-eel knobby-gnat dangling-snake
```

While syntactically correct, this method of cleanup often fails because one of the charts has an issue with delete. Since these appear to be processed serially, if the first chart fails to delete the rest never get a chance to leave this earth. 

I would expect that each delete would be attempted and its status reported. Something like:

```shell
$ helm delete --purge loopy-eel knobby-gnat dangling-snake
Failed to delete loopy-eel
Deleted knobby-gnat
Failed to delete dangling-snake
```

**Comment by technosophos** [comment]
Yeah, that makes sense. Do we have any other tools we can look at to see which direction they go on this issue?

**Comment by bacongobbler** [comment]
this looks like a great ticket for a first-time contributor!

**Comment by mansimarkaur** [comment]
Hi! I would like to work on this issue as my first contribution.

**Comment by bacongobbler** [comment]
Awesome! Let us know if you're having any troubles. We're always available to help in Slack in the #helm-dev channel if you have any dev-related questions. :)

**Comment by bacongobbler** [comment]
it looks like #2871 already addresses this problem, so @bonhamjp's already beat you to the punch. Sorry!

**Comment by mansimarkaur** [comment]
I'm glad somebody else solved it already. I'll look for more issues. Thanks :)
