### ISSUE TITLE
Multiple YAML document support

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#1669]
I'm writing a Helm chart for a distributed system. I have something like ~20 deployments and services to create that all share the same structure. I have templates that look this:

```yaml
{{- range $pod := .Values.topology.pods }}
{{- if $pod.service_type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" $ }}-{{ $pod.name | replace "_" "-" }}-app
  labels:
    app: {{ template "fullname" $ }}-{{ $pod.name | replace "_" "-" }}-app
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
spec:
  selector: 
    labels:
      app: {{ template "fullname" $ }}-{{ $pod.name | replace "_" "-" }}-app
    type: {{ $pod.service_type }}
    ports:
      {{- range $container := $pod.containers }}
      {{- if $container.ports }}
      - name: {{ $container.name }}
        protocol: TCP
        targetPort: {{ $container.ports.container }}
        port: {{ $container.ports.service }}
      {{- end }}
      {{- end }}
{{- end -}}
{{- end -}}
```

However when I try to install I get errors like:

```
helm install --name k2 --namespace test ./
Error: release k2 failed: [unable to decode "": [pos 205]: json: expect char '"' but got char '{', unable to decode "": [pos 189]: json: expect char '"' but got char '{', unable to decode "": [pos 187]: json: expect char '"' but got char '{', unable to decode "": [pos 187]: json: expect char '"' but got char '{', unable to decode "": [pos 187]: json: expect char '"' but got char '{', unable to decode "": [pos 189]: json: expect char '"' but got char '{', unable to decode "": [pos 189]: json: expect char '"' but got char '{', unable to decode "": [pos 197]: json: expect char '"' but got char '{', unable to decode "": [pos 203]: json: expect char '"' but got char '{', unable to decode "": [pos 189]: json: expect char '"' but got char '{', unable to decode "": [pos 191]: json: expect char '"' but got char '{', unable to decode "": [pos 191]: json: expect char '"' but got char '{', unable to decode "": [pos 185]: json: expect char '"' but got char '{']
make: *** [install] Error 1
```

Note that `helm lint` passes. Our multiple YAML documents in the same template supported or how should I approach my requirements?

**Comment by databus23** [comment]
Last time I checked helm had problems with the leading `---` separator which would be a bug IMO.
Can you try if it works when you leave the first `---` away?

**Comment by technosophos** [comment]
That error does not look like it's related to a streamed YAML doc. It looks like it's a validation error where you have a scalar instead of a dictionary (`""` instead of `{}`).

Perhaps starting with a simpler document might help narrow down the issue. But @databus23 is right: if there is a problem with doc stream support, that's an error.

**Comment by ahawkins** [comment]
> That error does not look like it's related to a streamed YAML doc. It looks like it's a validation error where you have a scalar instead of a dictionary ("" instead of {}).

Confirm. The error message doesn't indicate that it's a problem in _my_ YAML, not something somewhere else. If the error told me it was in my manifest then that would be more helpful.

I can confirm that multiple documents work as expected.

**Comment by vaddisrinivas** [comment]
I have  a similar problem where I need to add ```___``` any recommendations there?
