### ISSUE TITLE
read helmignore from user's home directory

### ISSUE THREAD

**Issue by majewsky** [kubernetes/helm#1674]
Git recognizes `~/.gitignore` (in addition to `$repo/.gitignore`) for file patterns that are specific to the user rather than the repo, e.g. editor backup/swap files. `helmignore` should work the same way.

**Comment by technosophos** [comment]
That's a great idea, @majewsky. I could see implementing one of two ways:

1. Put the file in `$HELM_HOME` (`.helm/helmignore`)
2. Put it in the user's root like `.gitignore`.

Are there any advantages to doing this one way over another?

Also, IIRC, the precedence order is that `$HOME/.gitignore` is processed first, then the repo's `.gitignore` is processed, right?

**Comment by majewsky** [comment]
Regarding git, the authoritative information resource is [`man:gitignore(5)`](https://linux.die.net/man/5/gitignore). Actually, I just realize that `$HOME/.gitignore` is not actually the default; it's `$HOME/.config/git/info/exclude`. (I configured the former path in my `$HOME/.gitconfig`.)

Since there is already a `$HELM_HOME` (thanks for making me aware), I suggest we put it in there. Maybe as `.helm/ignore`? `.helm/helmignore` looks like it's approved by the department of redundancy department.

**Comment by technosophos** [comment]
This is slightly harder than your average starter... but... I'll mark it starter anyway

**Comment by technosophos** [comment]
I'm going to remove this from 2.3.0 since it seems now to be dependent on #2094

**Comment by technosophos** [comment]
Moving this back to the backlog since it hasn't seen any movement since Feb.

**Comment by majewsky** [comment]
/remove-lifecycle stale

I guess...
