### ISSUE TITLE
Hook reuse errors

### ISSUE THREAD

**Issue by thomastaylor312** [kubernetes/helm#1679]
In the documentation for chart hooks, it says that a hook can be reused by adding multiple hook names in the annotation like so:

```
annotations:
    "helm.sh/hook": post-install,post-upgrade
```

However, when I try to upgrade a release, I get the following error (from the Tiller log):

```
release_server.go:862: Executing post-upgrade hooks for kafka-dev
release_server.go:877: warning: Release "kafka-dev" pre-install kafka/templates/post-deploy.yaml failed: jobs.batch "kafka-dev" already exists
```

Am I doing something wrong or is this a bug?

**Comment by technosophos** [comment]
The `name:` field on the defined thing (pod, job, whatever) has to be unique. Otherwise, k8s fails when it gets two things with the same name.

**Comment by thomastaylor312** [comment]
@technosophos: That is what I figured 😄 So how can I reuse a hook then? Because if it is the same job with `"helm.sh/hook": post-install,post-upgrade`, by nature it is going to have the same name

**Comment by technosophos** [comment]
I've used the `randAscii` template command to generate a random suffix for a name.

**Comment by thomastaylor312** [comment]
That sounds like a good idea. Thanks for the help @technosophos!
