### ISSUE TITLE
How to run Helm without Kubernetes?

### ISSUE THREAD

**Issue by majewsky** [kubernetes/helm#1684]
I want to work on my Helm charts (so the only thing I need is `helm install --dry-run` to see how it renders the templates), but I'm on the road and thus nowhere near a Kubernetes cluster. Helm refuses to do any work when not near a Tiller, and Tiller refuses to start when not near a Kubernetes.

This situation is seldom enough that I won't bother setting up a Kubernetes cluster on my local system. Is there a trick that I can do to get the template rendering to work?

**Comment by technosophos** [comment]
When it comes to chart development, the `helm lint` command should work without Kubernetes. Otherwise, Helm depends on Tiller for `install` and so on.

I believe you can run Tiller locally with `--storage memory`, and not require Kubernetes. But it won't really be able to do anything.

I've been thinking of writing a Helm plugin that would simply fake an environment and let you render the templates (something like `helm template render ./my/chart`).

**Comment by majewsky** [comment]
@technosophos Thanks for the suggestions.

1. `helm lint` indeed works without Tiller (and I've fixed a few lint errors in my charts just now).

2. `tiller --storage memory` starts up, but it fails when I try to `helm install --dry-run` to it. Helm reports `Error: transport is closing` and Tiller says

```
2016/12/15 10:55:07 storage.go:37: Getting release "funny-zebu" (v1) from storage
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8bb0c5]

goroutine 39 [running]:
panic(0x1563940, 0xc420012130)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset.(*Clientset).Discovery(0x0, 0x9, 0x17035e6)
        /home/stefan.rtree/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/clientset.go:170 +0x5
k8s.io/helm/pkg/tiller.(*ReleaseServer).renderResources(0xc420146000, 0xc42006cc00, 0xc42004bad0, 0xa, 0xc420394610, 0xc420394520, 0x5, 0xc42004bad0, 0x0, 0x0, ...)
        /home/stefan.rtree/src/k8s.io/helm/pkg/tiller/release_server.go:746 +0x386
k8s.io/helm/pkg/tiller.(*ReleaseServer).prepareRelease(0xc420146000, 0xc42011f9f0, 0xc42009cb01, 0xc4200de0f0, 0xc4202fa000)
        /home/stefan.rtree/src/k8s.io/helm/pkg/tiller/release_server.go:656 +0x1ad
k8s.io/helm/pkg/tiller.(*ReleaseServer).InstallRelease(0xc420146000, 0x7fe709dacc60, 0xc420463aa0, 0xc42011f9f0, 0x0, 0x12ba5, 0x12ba5)
        /home/stefan.rtree/src/k8s.io/helm/pkg/tiller/release_server.go:618 +0x78
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_InstallRelease_Handler(0x16bdae0, 0xc420146000, 0x7fe709dacc60, 0xc420463aa0, 0xc42011f9a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/stefan.rtree/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:749 +0x27d
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4202fa000, 0x21f1f40, 0xc42009cb40, 0xc4200de0f0, 0xc420462b40, 0x21cdf88, 0xc420463920, 0x0, 0x0)
        /home/stefan.rtree/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:638 +0xc14
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4202fa000, 0x21f1f40, 0xc42009cb40, 0xc4200de0f0, 0xc420463920)
        /home/stefan.rtree/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:796 +0x6b0
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4204a40a0, 0xc4202fa000, 0x21f1f40, 0xc42009cb40, 0xc4200de0f0)
        /home/stefan.rtree/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:449 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/stefan.rtree/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:450 +0xa3
```

I can spin this out into a separate issue if this needs further investigation.

3. A `helm template render` command would be exactly what I'm looking for. :)

**Comment by intlabs** [comment]
@technosophos, a `helm template render` command/plugin would make me very happy! I'll need to try the `tiller --storage memory` but I'm currently running minikube on my laptop just so I can run `tiller install --debug --dry-run`, which seems a bit excessive :)

**Comment by technosophos** [comment]
There is definitely no way to dry-run without a Kubernetes cluster. What dry-run does is send the request to the server for template rendering.

We'll keep working on the `helm template render` idea.

**Comment by munnerz** [comment]
👍 for the `helm template render` idea - it'd make it far easier to debug issues when creating charts, and would make helm charts more portable if a user doesn't want to use helm/tiller in their cluster, but does want to use some of the well-defined charts on their cluster.

**Comment by kuroneko25** [comment]
This would be tremendously helpful! i.e. if I want to leverage just the template engine instead of letting helm manage the entire release process.

**Comment by technosophos** [comment]
Here's the plugin: https://github.com/technosophos/helm-template

I'm going to close this issue, but feel free to re-open if there's something here I missed.

**Comment by jaytaylor** [comment]
Update for the uninitiated: Helm now comes with the `template` command bundled and usable without needing to install a plugin!

**Comment by jayunit100** [comment]
Does that mean that you can install a helm chart in an airgapped network ?

**Comment by senorhesles** [comment]
One issue I've run into is trying to template/lint things that reference `.Capabilities` locally without tiller/kubernetes. For example:
```
{{- if (eq .Capabilities.KubeVersion.Platform) "linux/amd64" -}}
true
{{- end -}}
```
fails with `helm lint` locally. Is there any support for providing "mock" values for `.Capabilities` values locally?
