### ISSUE TITLE
How to `get` a failed release?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/helm#1689]

**Comment by colemickens** [comment]
```
azdev  /m/p/h/c/c/c/polykube  master ● ?  ✘  helm get polykube-release0 
Error: release: not found

azdev  /m/p/h/c/c/c/polykube  master ● ?  ✘  helm list
NAME                    REVISION        UPDATED                         STATUS  CHART
polykube-release0       10              Thu Dec 15 04:11:01 2016        FAILED  polykube-0.1.0  
```

I have a script that either does and install or an upgrade depending on if a release has been done previously.

**Comment by technosophos** [comment]
Can you tell me what version of Helm you're on? `helm get` should be able to return a failed release, AFAIK. If it's still not, as of 2.1.0, then there's a lingering bug in there.

**Comment by colemickens** [comment]
I think there might still be a bug...

```
 azdev  ~/c/c/polykube  master ● ?  ✘  helm get polykube-release0
Error: release: not found
 
 azdev  ~/c/c/polykube  master ● ?  ✘  helm list
NAME                    REVISION        UPDATED                         STATUS  CHART
polykube-release0       1               Thu Dec 15 13:44:19 2016        FAILED  polykube-0.1.0

 azdev  ~/c/c/polykube  master ● ?  helm version
Client: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
```

**Comment by technosophos** [comment]
Marked this for the next bug release.

**Comment by technosophos** [comment]
Okay, I just went to look at the code, and it jogged my memory.

If you want to get a release that is not currently running, you have to specify the release number:

```
$ helm get --revision 1 polykube-release0
```

By default, `helm get` will only return data for successfully deployed releases for backward compatibility reasons (for scripts that were using `helm get` to check if a release was successful).

**Comment by colemickens** [comment]
That makes it rather hard to implement the logic I'm seeking. "Is there any release, then do an upgrade".

Could we have `helm get polykube-release0 --all` ?

**Comment by technosophos** [comment]
I'm not totally sure what workflow you are after here. What would `--all` do differently than `helm history`? What information are you trying to get?

If what you are after is doing an install-or-upgrade, you could do that with `helm upgrade --install`, which will do an install if it finds nothing to upgrade.

**Comment by technosophos** [comment]
Just checking to see if this issue is still alive for you

**Comment by colemickens** [comment]
I think `helm upgrade --install` is what I needed. Can't remember if I implemented/tested it, but let's close for now. Thank you.
