### ISSUE TITLE
Helm rejects version numbers with build info that are valid according to the SemVer 2 standard

### ISSUE THREAD

**Issue by itamarst** [kubernetes/helm#1698]
I'm building a Continuous Deployment pipeline. As such, I want charts/packages to include the git commit hash in their version; incrementing chart version numbers is less meaningful.

SemVer 2 has a mechanism for this, where versions can be `1.0.0+<build-info>`: http://semver.org/#spec-item-10

Helm however does not support this part of the SemVer 2 standard:

> Error: UPGRADE FAILED: Service "tracereader" is invalid: [metadata.labels: Invalid value: "tracereader-1.0.0+a056a76": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345')

**Comment by itamarst** [comment]
As a workaround I used prerelease versions (`1.0.0-a056a76`) instead of build versions (`1.0.0+a056a76`).

**Comment by technosophos** [comment]
I don't think this is directly related to SemVer so much as to a constraint on Kubernetes manifest file content.

That error is Kubernetes complaining that `+` is an invalid string in a `metadata.label` value. I didn't know `+` was illegal in a value. Can you paste in here the `metadata.labels` section of whatever resource that is?

**Comment by itamarst** [comment]
Problem is that the default Helm chart structure embeds versions in the metadata, I guess:

```
itamarst@hexagon:/tmp $ helm create test
Creating test
itamarst@hexagon:/tmp $ more test/templates/service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"   <---- HERE
... etc. ...
```

**Comment by magicmoose** [comment]
I ran into the same problem. 
But you have access to that file. So you could set something else  as label. For example strip the metadata from the semvar since it is not a distinguishing part of the version anyway.

**Comment by technosophos** [comment]
I think maybe we should change the default chart to do something like `{{ .Chart.Version | replace "+" "_" }}`. I'm adding this as a bug fix for 2.1.4.

/cc @prydonius

**Comment by technosophos** [comment]
To be more specific, this is just a change to the `defaultDeployment` and `defaultService` constants at the top of `pkg/chartutil/create.go`

**Comment by lachie83** [comment]
I'm willing to pick this up
