### ISSUE TITLE
.Release information does not get pushed to sub-charts

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/helm#1701]
I noticed that .Release  info like name, namespace etc is available for the main chart but is not visible in a sub-chart, so if I try to find out a namespace by referencing .Release.namespace I got empty string.

**Comment by technosophos** [comment]
Okay, so I just did a test and cannot reproduce. Here's what I did:

```
$ helm create testrelease
$ cd testrelease/charts
$ helm create testdep
$ vi testdep/templates/deployment.yaml
# Add a label like this: release: "{{ .Release.Name }}-{{ .Release.Namespace }}"
$ cd ../../ # back to the parent of testrelease
$ helm install testrelease
# created fantastic-beetle in namespace default
$ helm get fantastic-beetle
```

In the output of the last command, I saw this for the nested deployment:

```
# Source: testrelease/charts/testdep/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fantastic-beetle-testdep
  labels:
    chart: "testdep-0.1.0"
    release: "fantastic-beetle-default"
```

Can you point me toward a case where this doesn't work, and I'll see if I can reproduce that? Thanks.

**Comment by sbezverk** [comment]
I have a little bit more complex scenario:
parent/templates/common macro
parent/chart/microservice/template/template-1.yaml

template-1.yaml includes common_macro where I try to access .Release.Namespace where I still see the problem. If you are interested I can setup webex session and show live what is happening.

**Comment by sbezverk** [comment]
Passing .Release into macro solved the issue. Thank you. Serguei
