### ISSUE TITLE
Integrate helm and dm

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#171]

**Comment by jackgr** [comment]
Restating this requirement as integration of helm and dm. Based on discussions at the hackathon this week, we are going to replace the dm command line tool with helm, and helm will talk to dm running in the cluster to implement any client side commands that require server side functionality.

**Comment by bobbyrullo** [comment]
Does this mean that the current template format is deprecated and will instead use helm?

**Comment by jackgr** [comment]
@bobbyrullo Yes. Stay tuned.

**Comment by jackgr** [comment]
This is done now.
