### ISSUE TITLE
Make it easier to embed helm in another Go app

### ISSUE THREAD

**Issue by gtaylor** [kubernetes/helm#1712]
I'm working on a simple staging system that would benefit from embedding some of helm's functionality. I wanted to try to embed helm so that the user doesn't need to know anything about helm (it'd be an implementation detail that didn't need exposing).

As I sat down to pick some pieces out of the client package, I quickly ran into the fact that almost all of the tunnel-to-tiller functionality is private. This makes perfect sense, given the youth of helm and probably not wanting to expose such a thing just yet.

I'd like to suggest that we eventually move this into pkg and provide a public interface. In an perfect world, I can:

- Fire up a tunnel.
- Call the equivalent of a `helm package`, `helm install`, and `helm delete` from my application without having to resort to hacking something up with os/exec.
- Also probably query for releases and their states from my application.

We've already got something like this implemented on our own, but realized that we had poorly reinvented helm. Since we are trying to keep this thing as simple as possible, not asking our users to download `kubectl` and `helm` in addition to our client would go a long way towards making a nice experience!

An alternative would be to write a helm plugin, but I'm not sure that it makes sense to wrap a staging system _in_ helm.

**Comment by technosophos** [comment]
I don't think we'd object at all to turning the tunnel logic into a package. Thoughts, @adamreese ?

Most of the other stuff you should be able to easily accomplish with `pkg/helm`.

**Comment by gtaylor** [comment]
I'd be glad to chip in a blog post or some examples if we can get this working. 

I had looked at trying to figure this out with client-go + helm, but it looks like the tunneling part of client-go is still in progress. I got a bit confused at the difference between the unversioned kubernetes/kubernetes API and client-go, so my personal attempts at doing this have fallen short thus far.

The other thing that made me hesitate is not knowing when/whether helm will move to client-go itself.

Getting back on topic, I think being able to easily embed helm could lead to some really interesting possibilities. At Reddit, I envision us having a chart repo for all of our dependencies. Each of our services will have a sub-directory with some staging-specific info, plus a chart for the service itself. We'd be able to link in dependencies and dynamically generate the equivalent of values.yaml for a very nice staging experience. An additional benefit is that we can re-use our production charts in staging.

**Comment by technosophos** [comment]
@bacongobbler are you still working on migrating the tunnel logic to a separate package?

**Comment by bacongobbler** [comment]
Yep! I actually have a working implementation. Lemme PR that.

**Comment by gtaylor** [comment]
Happy to test and help review this weekend!

**Comment by bacongobbler** [comment]
#1882 :)

**Comment by gtaylor** [comment]
Thanks for your work, @bacongobbler !
