### ISSUE TITLE
Is helm waiting for dependencies to be up and running?

### ISSUE THREAD

**Issue by andersla** [kubernetes/helm#1713]
I have a problem with my helm install of a database application sometimes fails because it can not find a running postgresql server.
I deploy postgresql chart as dependency (in the charts subdirectory).
It seem that sometimes postgresql doesn't have the time to start listen before my application is deployed and wants to use postgresql.
Anyone have a suggestion how to avoid this race?
Is Helm waiting to deploy the main chart until the dependencies are up and running.
Maybe postgresql service is not listening the first seconds pod is running due to initialization?

**Comment by technosophos** [comment]
No, Helm does not have built-in logic for waiting for a pod to become operational. "Success" is defined as successfully submitting the resources to Kubernetes for deployment.

There are a few common patterns to accomplish what you're asking. The most popular at the moment is to add an "init container" to you app's pod definition, where that init container simply waits until the DB is ready, and then exits cleanly. That actually solves other lifecycle problems as well, so it is considered a good practice. (Example: Database crashes, then app crashes. When app comes back up, it goes into a waiting state for the database to accept connections again.)

**Comment by nebril** [comment]
@andersla there is an ongoing work to support this behaviour in Helm by integrating it with AppController (https://github.com/Mirantis/k8s-AppController). The integration demo will be shown on Kubernetes sig-apps meeting in Jaunary.

Disclaimer - I am working on said integration.

**Comment by andersla** [comment]
Great! Currently I solved it with an `init-containers`, as suggested by @technosophos:

```
apiVersion: v1
kind: ReplicationController
metadata:
    name: {{.Values.galaxy_metadata_name}} 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.galaxy_label_app}}
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
          [
            {
              "name": "postgres-listener",
              "image": "alpine",
              "imagePullPolicy": "IfNotPresent",
              "command": [
                "sh", "-c",
                "for i in $(seq 1 200); do nc -z -w3 postgresql-for-galaxy 5432 && exit 0 || sleep 3; done; exit 1"
              ]
            }
          ]
    spec:
      .....
```

**Comment by technosophos** [comment]
Closing for now. Re-open if necessary.

**Comment by martin-patsov** [comment]
Combined with: 
https://github.com/docker-library/postgres/issues/146
and
https://medium.com/@xcoulon/initializing-containers-in-order-with-kubernetes-18173b9cc222
everything worked great!

**Comment by patsevanton** [comment]
Really need this feature
