### ISSUE TITLE
Doesn't place nicely with RBAC when unable to create namespaces

### ISSUE THREAD

**Issue by mariusgrigoriu** [kubernetes/helm#1714]
Tiller checks for the existence of a namespace by attempting to create one anyway. On my cluster, users are unable to create namespaces any helm install fails to RBAC.

It would be better if Tiller attempted to Get a namespace and then create it if it didn't exist.

**Comment by TamalSaha** [comment]
@mariusgrigoriu , I am proposing reimplementing Tiller using Kube 3rd part objects. https://github.com/kubernetes/helm/pull/1717

That should solve this issue too.

**Comment by technosophos** [comment]
Merged @mariusgrigoriu 's patch to fix this issue, so I'm marking as closed.
