### ISSUE TITLE
library values

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#1719]
I've been following a pattern where i have a subchart called <x>-common that contains templates that are just macro libraries. nothing directly launched. They are then instantiated in the parent chart, using the parent charts values. This is working great.

But one pain point is, if I want to put default values for the macro's in, they need to go into each parent chart. this can be difficult to maintain the values files.

I would like to see a new values.yaml file called inherited_values.yaml (or something to that effect), that are used for this use case. They work like normal values but. they get automatically added to the parent chart's values when assembling rather then getting namespaced by the subchart name. parents values takes precedence.

This would allow for helm charts to be build in much more modular ways while still providing a nice user api.

**Comment by technosophos** [comment]
Is this a duplicate of or alternative to  #1883? If not, would you mind clarifying the different use cases?

**Comment by kfox1111** [comment]
Looks like a dup. closing.
