### ISSUE TITLE
Cannot connect to Tiller from a Docker container

### ISSUE THREAD

**Issue by adamniedzielski** [kubernetes/helm#1723]
I'm using `minikube` to run a Kubernetes cluster on my machine. I have a Docker container that is running in the privileged mode. I want to use Helm to configure the cluster from the Docker container. `helm init` succeeds and Tiller is installed in the cluster. `helm version` fails with `Error: cannot connect to Tiller`.

`helm version --debug` executed on the host:

```
Created tunnel using local port: '63036'
SERVER: ":63036"
Client: &version.Version{SemVer:"v2.0.0", GitCommit:"51bdad42756dfaf3234f53ef3d3cb6bcd94144c2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.2", GitCommit:"afcab3bb4f45478772a853e0d98306fda0a7af34", GitTreeState:"clean"}
```

`helm version --debug` inside the container

```
Created tunnel using local port: '34392'
SERVER: "localhost:34392"
Client: &version.Version{SemVer:"v2.0.2", GitCommit:"afcab3bb4f45478772a853e0d98306fda0a7af34", GitTreeState:"clean"}
rpc error: code = 14 desc = grpc: the connection is unavailable
Error: cannot connect to Tiller
```

Any ideas why I cannot connect to the cluster? I'm not sure if it is my mistake (most probable) or a bug in Helm itself.

**Comment by technosophos** [comment]
Can you try setting `HELM_HOST` to point to the Tiller server?

**Comment by leopoldodonnell** [comment]
We're using a docker container as well - same issue, but have a workaround:

Just add `--net=host` to your docker run and you should be out of trouble. Here's what our run looks like:

```bash
docker run -ti --rm  -v $HOME/.aws:/root/.aws -v $PWD:/share -v $HOME/.ssh:/root/.ssh \
   -v $HOME/.minikube:$HOME/.minikube \
   -v $HOME/.kube:/root/.kube \
   -v /var/run/docker.sock:/var/run/docker.sock \
   --net=host \
   --entrypoint /bin/sh \
   my-image
```

**Comment by adamniedzielski** [comment]
@technosophos Thank you for your response! Yes, I tried setting `HELM_HOST`. As far as I understand when you set `HELM_HOST`, Helm will not attempt to create the tunnel. At least this is what the logs show. In this case I would have to run Tiller on my own, but I don't want to do that. Does it make sense?

@leopoldodonnell Thanks a lot for the workaround! I'll report back when I get a chance to try it out.

**Comment by technosophos** [comment]
Any update on whether upgrading Docker fixed it?

**Comment by technosophos** [comment]
I guess I'll close this one for now. Feel free to re-open if necessary.

**Comment by jkamenik** [comment]
I just ran into this problem running `1.13` version I think.  Upgrading to the beta version worked.

```
Version 17.03.0-ce-mac1 (15587)
Channel: beta
05a8abd304
```

**Comment by zioalex** [comment]
Hi guys I have a similar problem. I cannot get helm to speak with a Tiller on a k8s cluster from a docker container!

It works without any problem from the host where docker is running.
The K8S communication is working in the container and even helm init:

`bash-4.3# helm init --debug
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        image: gcr.io/kubernetes-helm/tiller:v2.6.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
      nodeSelector:
        beta.kubernetes.io/os: linux
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  ports:
  - name: tiller
    port: 44134
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: ClusterIP
status:
  loadBalancer: {}
$HELM_HOME has been configured at /root/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!`

But then I run the version:
`bash-4.3# helm version --debug
[debug] Created tunnel using local port: '45513'

[debug] SERVER: "localhost:45513"

Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
`

And it cannot connect. I disabled the FW to be sure that it cannot interfere... But nothing.

some SW version.
docker 17.06.1-ce
kubectl Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
helm 2.6.0 / 2.6.1

Any help would be really appreciated.

**Comment by cindy06** [comment]
same issue at here:
helm version --debug
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller

**Comment by gordyf** [comment]
I'm having a problem with Helm v2.6.2 running in a Docker container:

```
/ # helm version --debug
[debug] Created tunnel using local port: '36975'

[debug] SERVER: "localhost:36975"

Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
E1011 22:45:06.754136     100 portforward.go:178] lost connection to pod
[debug] context deadline exceeded
Error: cannot connect to Tiller
```

However, if I manually create the tunnel:

`kubectl port-forward --namespace kube-system tiller-deploy-1936853538-mzps3 44134:44134&
Forwarding from 127.0.0.1:44134 -> 44134`

Then I can sorta get it to work, by connecting to 127.0.0.1:

```
# helm version --host "127.0.0.1:44134" --debug
[debug] SERVER: "127.0.0.1:44134"

Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Handling connection for 44134
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
```

But not by connecting to localhost:

```
# helm version --host "localhost:44134" --debug
[debug] SERVER: "localhost:44134"

Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
```

I am able, however, to telnet to that port on localhost and type nonsense at the gRPC interface:

```
# telnet localhost 44134
Handling connection for 44134
Hello, I am typing at a GRPC interface.
Connection closed by foreign host
```

The tiller logs show:

`2017/10/11 22:47:47 transport: http2Server.HandleStreams received bogus greeting from client: "Hello, I am typing at a "`

Why is helm unable to connect to localhost when other tools are able to do so?

**Comment by kylebyerly-hp** [comment]
Does your dns server have someone using localhost.searchdomain? Some go binaries and I believe alpine/muslc seem to honor the lookup of localhost.searchdomain first, then localhost to 127.0.0.1. That's, unfortunately, a valid hostname and the 'correct' behavior. There's a draft RFC to make this behave as expected: https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06

Couple solutions of the top of the head: replace localhost with 127.0.0.1 everywhere in the go code OR disable search domains on every client host.

**Comment by gordyf** [comment]
Oh man, that's exactly what it is. Who decided that was a good idea?! :) Thanks so much for that tip.
