### ISSUE TITLE
helm package fails without local repository

### ISSUE THREAD

**Issue by sunshinekitty** [kubernetes/helm#1732]
The `package` command in helm will fail without a configured local repository.  I'm building a chart repository with Jenkins and don't require this, it would be nice if it did not error out.

Errors:
```
helm package ./dir
> Error: open /home/jenkins/.helm/repository/local: no such file or directory
mkdir -p /home/jenkins/.helm/repository/local
helm package ./dir
> Error: open /home/jenkins/.helm/repository/local/index.yaml: no such file or directory
```

Work-around:
```
mkdir -p /home/jenkins/.helm/repository/local
cat <<EOF > /home/jenkins/.helm/repository/local/index.yaml
apiVersion: v1
entries: {}
generated: 2016-12-19T11:33:32.034887011-06:00
EOF
< go about your business >
```

**Comment by sunshinekitty** [comment]
thanks, this works too

**Comment by technosophos** [comment]
Cool! That's good to know. Thanks. I'm closing this issue out, since I don't think there's additional work.

Thanks again!

**Comment by zak905** [comment]
I encountered this issue while migrating from helm 2 to 3. I had to copy the old `index.yaml` from `repository/local` in the old helm folder and copy it to `~/.cache/helm/repository/local-index.yaml`
