### ISSUE TITLE
Where is "definitive information about safely upgrading Helm and Tiller"?

### ISSUE THREAD

**Issue by dzavalkinolx** [kubernetes/helm#1755]
This page https://github.com/kubernetes/helm/blob/master/docs/install_faq.md#upgrading says that

> The Installation Guide has definitive information about safely upgrading Helm and Tiller.

However, link to Installation Guide is broken. Probably it refers to https://github.com/kubernetes/helm/blob/master/docs/install.md but there is no “definitive information about safely upgrading Helm and Tiller" either. Detailed upgrade documentation is much desired and it also includes information on version compatibilities. For example, can I upgrade from my current version v2.0.0-rc.2 directly to latest version 2.1.3 or I need to upgrade first to some intermediate version?

**Comment by technosophos** [comment]
Thanks. Yeah, we should improve that section and fix the broken link as well. There's a starter issue covering part of this, but not all. #1704
