### ISSUE TITLE
Helm client tries to replace values which are in comments

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/helm#1760]
If config file contains such comment for example:
```
# port: "{{ .Values.service.port }}"
```

and there is no value `service` present, the client errors while performing operation.

**Comment by technosophos** [comment]
Oh! Now I understand! The solution is to do `{{/* .Values.service.port */}}` to tell the template engine to ignore.

**Comment by technosophos** [comment]
I am going to mark this as closed. Feel free to re-open if necessary.

**Comment by jowparks** [comment]
I just ran into this issue as well, it seems counter intuitive that you need two sets of comments to prevent rendering. Don't you think it makes more sense to not render anything in a comment?

**Comment by bacongobbler** [comment]
The rendering order is

1. text/template (evaluating the `{{`)
2. YAML

Because the template engine runs before it's serialized into YAML, the second pair of comments are necessary.

You could wrap the entire line in an `{{ if` block to prevent rendering comments if that's what you mean.
