### ISSUE TITLE
execute "make bootstrap build" command failed

### ISSUE THREAD

**Issue by luoxiaoxun** [kubernetes/helm#1762]
When I execute "make bootstrap build" command, It shows the following error:

glide install --strip-vendor --strip-vcs 
[WARN]	The --strip-vcs flag is deprecated. This now works by default.
[WARN]	The name listed in the config file (k8s.io/helm) does not match the current location (.)
[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/aokoli/goutils 9c37978a95bd5c709a15883b6242714ea6709e64!
[INFO]	--> Found desired version locally github.com/asaskevich/govalidator 7664702784775e51966f0885f5cd27435916517b!
[INFO]	--> Found desired version locally github.com/Azure/go-ansiterm 70b2c90b260171e829f1ebd7c17f600c11858dbe!
[INFO]	--> Found desired version locally github.com/blang/semver 31b736133b98f26d5e078ec9eb591666edfd091f!
[INFO]	--> Found desired version locally github.com/coreos/go-oidc 5644a2f50e2d2d5ba0b474bc5bc55fea1925936d!
[INFO]	--> Found desired version locally github.com/coreos/pkg fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8!
[INFO]	--> Found desired version locally github.com/cpuguy83/go-md2man a65d4d2de4d5f7c74868dfa9b202a3c8be315aaa!
[INFO]	--> Found desired version locally github.com/davecgh/go-spew 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d!
[INFO]	--> Found desired version locally github.com/dgrijalva/jwt-go 01aeca54ebda6e0fbfafd0a524d234159c05ec20!
[INFO]	--> Found desired version locally github.com/docker/distribution cd27f179f2c10c5d300e6d09025b538c475b0d51!
[INFO]	--> Found desired version locally github.com/docker/docker b9f10c951893f9a00865890a5232e85d770c1087!
[INFO]	--> Found desired version locally github.com/docker/engine-api dea108d3aa0c67d7162a3fd8aa65f38a430019fd!
[INFO]	--> Found desired version locally github.com/docker/go-connections f549a9393d05688dff0992ef3efd8bbe6c628aeb!
[INFO]	--> Found desired version locally github.com/docker/go-units 0bbddae09c5a5419a8c6dcdd7ff90da3d450393b!
[INFO]	--> Found desired version locally github.com/docker/spdystream 449fdfce4d962303d702fec724ef0ad181c92528!
[INFO]	--> Found desired version locally github.com/emicklei/go-restful 89ef8af493ab468a45a42bb0d89a06fccdd2fb22!
[INFO]	--> Found desired version locally github.com/evanphx/json-patch 465937c80b3c07a7c7ad20cc934898646a91c1de!
[INFO]	--> Found desired version locally github.com/exponent-io/jsonpath d6023ce2651d8eafb5c75bb0c7167536102ec9f5!
[INFO]	--> Found desired version locally github.com/ghodss/yaml 73d445a93680fa1a78ae23a5839bad48f32ba1ee!
[INFO]	--> Found desired version locally github.com/go-openapi/jsonpointer 46af16f9f7b149af66e5d1bd010e3574dc06de98!
[INFO]	--> Found desired version locally github.com/go-openapi/jsonreference 13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272!
[INFO]	--> Found desired version locally github.com/go-openapi/spec 6aced65f8501fe1217321abf0749d354824ba2ff!
[INFO]	--> Found desired version locally github.com/go-openapi/swag 1d0bd113de87027671077d3c71eb3ac5d7dbba72!
[INFO]	--> Found desired version locally github.com/gobwas/glob bea32b9cd2d6f55753d94a28e959b13f0244797a!
[INFO]	--> Found desired version locally github.com/gogo/protobuf e18d7aa8f8c624c915db340349aad4c49b10d173!
[INFO]	--> Found desired version locally github.com/golang/glog 44145f04b68cf362d9c4df2182967c2275eaefed!
[INFO]	--> Found desired version locally github.com/golang/groupcache 02826c3e79038b59d737d3b1c0a1d937f71a4433!
[INFO]	--> Found desired version locally github.com/golang/protobuf df1d3ca07d2d07bba352d5b73c4313b4e2a6203e!
[INFO]	--> Found desired version locally github.com/google/gofuzz bbcb9da2d746f8bdbd6a936686a0a6067ada0ec5!
[INFO]	--> Found desired version locally github.com/gosuri/uitable 36ee7e946282a3fb1cfecd476ddc9b35d8847e42!
[INFO]	--> Found desired version locally github.com/howeyc/gopass 3ca23474a7c7203e0a0a070fd33508f6efdb9b3d!
[INFO]	--> Found desired version locally github.com/imdario/mergo 6633656539c1639d9d78127b7d47c622b5d7b6dc!
[INFO]	--> Found desired version locally github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75!
[INFO]	--> Found desired version locally github.com/jonboulle/clockwork 72f9bd7c4e0c2a40055ab3d0f09654f730cce982!
[INFO]	--> Found desired version locally github.com/juju/ratelimit 77ed1c8a01217656d2080ad51981f6e99adaa177!
[INFO]	--> Found desired version locally github.com/mailru/easyjson d5b7844b561a7bc640052f1b935f7b800330d7e0!
[INFO]	--> Found desired version locally github.com/Masterminds/semver 59c29afe1a994eacb71c833025ca7acf874bb1da!
[INFO]	--> Found desired version locally github.com/Masterminds/sprig 69011c0cd9b4d2e0733c4d9e2c8e2a5a0d0a2f2f!
[INFO]	--> Found desired version locally github.com/mattn/go-runewidth d6bea18f789704b5f83375793155289da36a3c7f!
[INFO]	--> Found desired version locally github.com/mitchellh/go-wordwrap ad45545899c7b13c020ea92b2072220eefad42b8!
[INFO]	--> Found desired version locally github.com/pborman/uuid ca53cad383cad2479bbba7f7a1a05797ec1386e4!
[INFO]	--> Found desired version locally github.com/PuerkitoBio/purell 8a290539e2e8629dbc4e6bad948158f790ec31f4!
[INFO]	--> Found desired version locally github.com/PuerkitoBio/urlesc 5bd2802263f21d8788851d5305584c82a5c75d7e!
[INFO]	--> Found desired version locally github.com/russross/blackfriday 300106c228d52c8941d4b3de6054a6062a86dda3!
[INFO]	--> Found desired version locally github.com/satori/go.uuid 879c5887cd475cd7864858769793b2ceb0d44feb!
[INFO]	--> Found desired version locally github.com/shurcooL/sanitized_anchor_name 10ef21a441db47d8b13ebcc5fd2310f636973c77!
[INFO]	--> Found desired version locally github.com/Sirupsen/logrus 51fe59aca108dc5680109e7b2051cbdcfa5a253c!
[INFO]	--> Found desired version locally github.com/spf13/cobra f62e98d28ab7ad31d707ba837a966378465c7b57!
[INFO]	--> Found desired version locally github.com/spf13/pflag 5ccb023bc27df288a957c5e994cd44fd19619465!
[INFO]	--> Found desired version locally github.com/technosophos/moniker 9f956786b91d9786ca11aa5be6104542fa911546!
[INFO]	--> Found desired version locally github.com/ugorji/go f1f1a805ed361a0e078bb537e4ea78cd37dcf065!
[INFO]	--> Found desired version locally golang.org/x/crypto 1f22c0103821b9390939b6776727195525381532!
[INFO]	--> Found desired version locally golang.org/x/net e90d6d0afc4c315a0d87a568ae68577cc15149a0!
[INFO]	--> Found desired version locally golang.org/x/oauth2 3c3a985cb79f52a3190fbc056984415ca6763d01!
[INFO]	--> Found desired version locally golang.org/x/sys 8f0908ab3b2457e2e15403d3697c9ef5cb4b57a9!
[INFO]	--> Found desired version locally golang.org/x/text 2910a502d2bf9e43193af9d68ca516529614eed3!
[INFO]	--> Found desired version locally google.golang.org/appengine 4f7eeb5305a4ba1966344836ba4af9996b7b4e05!
[INFO]	--> Found desired version locally google.golang.org/grpc b7f1379d3cbbbeb2ca3405852012e237aa05459e!
[INFO]	--> Fetching cloud.google.com/go.
[INFO]	--> Fetching gopkg.in/inf.v0.
[INFO]	--> Fetching gopkg.in/yaml.v2.
[INFO]	--> Fetching k8s.io/kubernetes.
[WARN]	Unable to checkout cloud.google.com/go
[ERROR]	Update failed for cloud.google.com/go: Cannot detect VCS
[WARN]	Unable to checkout k8s.io/kubernetes
[ERROR]	Update failed for k8s.io/kubernetes: Cannot detect VCS
[WARN]	Unable to checkout gopkg.in/inf.v0
[ERROR]	Update failed for gopkg.in/inf.v0: Cannot detect VCS
[WARN]	Unable to checkout gopkg.in/yaml.v2
[ERROR]	Update failed for gopkg.in/yaml.v2: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
make: *** [bootstrap] Error 1

It seems that cannot fetch the package, but I cannot figure out the reason

**Comment by technosophos** [comment]
You might just need to remove the `vendor/` directory and then re-run `make bootstrap`.

Those errors usually are a result of a transient network outage where Glide can't contact the remote server to fetch the latest version.

**Comment by luoxiaoxun** [comment]
I remove vendor directory and re-run command, but still the same error@technosophos

**Comment by technosophos** [comment]
Does `go get cloud.google.com/go`work? (It won't solve the problem, but it might help identify the problem.

**Comment by luoxiaoxun** [comment]
When execute `go get cloud.google.com/go` command, it return the following error:

Fetching https://cloud.google.com/go?go-get=1
https fetch failed: Get https://cloud.google.com/go?go-get=1: x509: certificate signed by unknown authority
package cloud.google.com/go: unrecognized import path "cloud.google.com/go" (https fetch: Get https://cloud.google.com/go?go-get=1: x509: certificate signed by unknown authority)

@technosophos

**Comment by luoxiaoxun** [comment]
It seems to be ssl problem of git, I change to another way, git clone the repo into gopath directory which skip ssl verify, and then mv the directory into ~/.glide/cache/src directory and rename the directory, finally rerun the `make bootstrap build` command which seems ok! @technosophos

**Comment by technosophos** [comment]
Wow. That's a strange one. Glad you figured it out.

I am going to close this issue. Feel free to open it if you have more related problems.

**Comment by foxish** [comment]
For someone running into this, it may also because newer versions of git don't automatically follow 301 redirects.
`git config --global http.https://gopkg.in.followRedirects true` restores the old behavior
