### ISSUE TITLE
pod cannot running after execute "helm init" command

### ISSUE THREAD

**Issue by luoxiaoxun** [kubernetes/helm#1764]
I am following with the helm docs, install helm client first(I already had k8s cluster which version is 1.3) and then execute "helm init" command which seems ok, but when I execute "get pod" , the tiller pods does not running, then execute "describe pod" which show the pod is unhealthy, but when I execute "docker logs", it show nothing.
Anyone has meet the same problem?

**Comment by technosophos** [comment]
Which version of Helm are you using? I'm not sure that Helm 2.1 will run on Kubernetes 1.3. Helm 2.0.3 might, though.

**Comment by luoxiaoxun** [comment]
helm version is 2.1.3

**Comment by luoxiaoxun** [comment]
I change helm version to 2.0.2, but still have this problem@technosophos

**Comment by luoxiaoxun** [comment]
I got it, it seems that the container start too slow. The pod run successfully after enlarging the failureThreshold and initDelaySeconds. @technosophos, thank you for your help~!

**Comment by technosophos** [comment]
Great! I am marking this resolved. Feel free to re-open if you need.
