### ISSUE TITLE
PROPOSAL: Add `--upgrade` option to `init` enabling client to upgrade tiller if already installed

### ISSUE THREAD

**Issue by mortenlj** [kubernetes/helm#1782]
We're using helm in a continuous deployment pipeline, so the first step is to execute `helm init` to make sure tiller is installed in the cluster. Most of the time, tiller is already installed, so we get the expected warning about tiller already being installed, which is annoying but easy enough to ignore.

However, when we upgrade to new versions of helm, it would be useful if we at the same time could upgrade tiller. Currently we would need to detect the difference in version, then manually delete tiller, and then run `helm init` again.

It would be better if `helm init` could take an option `--upgrade`, which would make helm check the version of tiller, and upgrade to a matching version if it's not already up-to-date.

**Comment by technosophos** [comment]
This makes sense to me.
