### ISSUE TITLE
feature idea: validate integrity of deployed release

### ISSUE THREAD

**Issue by majewsky** [kubernetes/helm#1785]
I'd like to have an extended version of `helm status` that verifies that the resources are still in the state that Helm has deployed.

Background: I've deployed my resources with Helm, and while I was debugging, I flipped on some environment variable by editing the Deployment with `kubectl edit`. I forgot to flip the switch back after I was done, and a few days later, I was confused why stuff wasn't working as usual. I only found the debugging switch in the wrong position after quite some time of printf-debugging.

Since Helm already has the compiled resources stored in its own configmaps, it should not be that hard to perform a diff of these against the active resources, should it? It could also be useful to have a quiet version of the diff that just reports equality in its exit code (similar to `diff -q`) for use in monitoring.

**Comment by michelleN** [comment]
hey @majewsky I'm working on a feature (for the 2.2.0 release) that might be useful in this context. It is the `helm test <release>` feature: https://github.com/kubernetes/helm/issues/1163
The idea is you can pre-define some definitions of what success means for your release and what is means for your release to be in a good state. For example, you might define a job or pod with a series of tests. Then, we look at the exit status of the container(s) to see if the test was a success or failure. 
The last test run results will show up in the `helm status` output.

Do you think this might be helpful in your scenario?

**Comment by bacongobbler** [comment]
`helm test` has been implemented so I think this is safe to close.
