### ISSUE TITLE
How to change k8s api server address which tiller will connect

### ISSUE THREAD

**Issue by luoxiaoxun** [kubernetes/helm#1791]

**Comment by luoxiaoxun** [comment]
When I run `helm install` command, helm client print the following error:
`Error: transport is closing`
I find that the reason is tiller cann't connect to k8s api-server 
`Cannot initialize Kubernetes connection: Get http://localhost:8080/api: dial tcp: i/o timeout2017-01-06 01:24:51.414332 I | storage.go:94: Listing all releases with filter`
Because my k8s api-server neither run in container nor bind to localhost, which run in vm and bind to specific address.
How to change k8s api server address which tiller will connect? @technosophos

**Comment by iamzhout** [comment]
try to set **KUBERNETES_MASTER** in pod ENV, and tiller should use this setting as apiserver address for communication.

**Comment by luoxiaoxun** [comment]
It's ok now, thank you for your help~! @iamzhout

**Comment by adamreese** [comment]
looks like this is resolved, reopen if there is still an issue
