### ISSUE TITLE
support kubectl apply's --purge flag in helm upgrade

### ISSUE THREAD

**Issue by chancez** [kubernetes/helm#1793]
`kubectl apply` learned a new flag:

```
...
  # Note: --prune is still in Alpha
  # Apply the configuration in manifest.yaml that matches label app=nginx and delete all the other resources that are
not in the file and match label app=nginx.
  kubectl apply --prune -f manifest.yaml -l app=nginx
...
      --prune=false: Automatically delete resource objects that do not appear in the configs and are created by either
apply or create --save-config. Should be used with either -l or --all.
      --prune-whitelist=[]: Overwrite the default whitelist with <group/version/kind> for --prune
```

Being able to use this behavior with `helm upgrade` would be great.

**Comment by adamreese** [comment]
helm will prune by default.  We get around the prune issue by storing the release as a whole object.  That allows tiller to calculate what needs to be pruned.

**Comment by chancez** [comment]
I don't understand how helm could ever safely prune by default. If it did, then what would happen to resources not managed by helm within a namespace helm is installing a chart to?

**Comment by adamreese** [comment]
It would leave them if they are not part of the release being deleted.

**Comment by chancez** [comment]
I'm not talking about deleting a release. Im talking about running `helm upgrade` and it deleting resources which are not in the new upgrade's payload effectively.

**Comment by adamreese** [comment]
sorry, i meant to say upgrade

**Comment by nandant** [comment]
@adamreese , does this pruning work when the we reduce the number of replicas in a deployment? I just tested this for a deployment where I reduced replicaCount of the managed pods from 3 to 1, but the helm upgrade did not delete the other 2 pods.

**Comment by technosophos** [comment]
@nandant So you increased the replica count by changing a value in the helm chart, then later reduced the replica count in the helm chart? Or were you doing some of these steps with kubectl?

**Comment by adamreese** [comment]
@nandant the pruning done by a 'reaper' object which queries for related resources using label selectors and removes them.  This is kubernetes native and helm doesn't add any functionality on top.

https://github.com/kubernetes/kubernetes/blob/0ebedded7d3e711bd7a286c83b2f44764874afbf/pkg/kubectl/stop.go#L415

**Comment by technosophos** [comment]
Given the built-in behaviors in Helm 2.2.0 and Kubernetes >= 1.5.1, is there anything left to do for this issue?

**Comment by bacongobbler** [comment]
nope.
