### ISSUE TITLE
arm builds

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#1804]
Any chance we could get a helm build for arm 32? Kubernetes is up and running on the platform now.

**Comment by technosophos** [comment]
Good timing. We merged this last week! #1722 2.2.0 will be the first version with ARM builds.

**Comment by ravishivt** [comment]
Nice work on the arm support.  Could we also get arm64 support?  😄

**Comment by technosophos** [comment]
Closed via #1722 and #1839

**Comment by dsvensson** [comment]
Would be nice with release binaries as well, compiling on a raspberry pi is kind of boring. Don't have any other machine at hand atm.

**Comment by vielmetti** [comment]
@dsvensson - i can get you a 64-bit Arm system through the Works on Arm project. See https://github.com/worksonarm/cluster/issues/new to fill out a request.

**Comment by bacongobbler** [comment]
ARM client release binaries are available, just not tiller releases.

e.g. for 2.9.1 it's available [here](https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-arm.tar.gz) ([checksum](https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-arm.tar.gz.sha256))

**Comment by kfox1111** [comment]
tiller would be nice. any plans on that? being able to hand out cheep kubernetes single node clusters that fit in your pocket that support helm would be pretty cool. :)

**Comment by dsvensson** [comment]
@vielmetti @bacongobbler I would have expected to find the Helm binaries here:

https://github.com/kubernetes/helm/releases

**Comment by vielmetti** [comment]
@dsvensson - there is a set of Tiller and Helm builds (unofficial) for mulitarch, including arm, at https://github.com/jessestuart/tiller-multiarch from @jessestuart .

**Comment by bacongobbler** [comment]
I've added all permutations of the release artifacts into #3975, which we can start documenting when we cut new releases of Helm. We have builds available for the following architectures:

- MacOS amd64
- Linux amd64
- Linux i386
- Linux arm
- Linux arm64
- Linux ppc64le
- Windows amd64

There are no current plans to release multi-arch images for Tiller, though in helm 3 tiller's being removed so there won't be the need to support multi-arch images in that case.

**Comment by jmreicha** [comment]
@bacongobbler Any timeline on when Helm 3 will be ready?

**Comment by bacongobbler** [comment]
We're currently in code cleanup mode and haven't made any significant changes to helm 3 other than removing tiller and a few other things knocked off the proposals. We have not committed to a timeframe for when helm 3 is planned to be released. :slightly_smiling_face:

**Comment by devinrsmith** [comment]
I'm able to install the arm build of helm, but the default tiller image didn't seem to be compatible with arm (after using `helm init`).

```
$ k logs tiller-deploy-5dc46c877-fhccs --namespace=kube-system
standard_init_linux.go:211: exec user process caused "exec format error"
```

To fix this, I had to run `helm init --tiller-image=jessestuart/tiller` (https://github.com/jessestuart/tiller-multiarch).

For reference:

```
$ docker images | grep tiller
jessestuart/tiller                   latest              64b3249d73c9        16 hours ago        78.6MB
gcr.io/kubernetes-helm/tiller        v2.14.1             ac22eb1f780e        4 weeks ago         94.2MB
```

```
$ uname -a
Linux odroidxu4 4.14.127-odroidxu4 #7 SMP PREEMPT Tue Jun 25 21:14:12 CEST 2019 armv7l GNU/Linux
```
