### ISSUE TITLE
Feature request: `helm install --wait`

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes/helm#1805]
Currently `helm install` guarantees that the chart has been deployed, but not that the pods have necessarily come up and are available. The premise behind this flag is to get helm to wait until all of the pods are up and available.

**Comment by bacongobbler** [comment]
cc @thomastaylor312

**Comment by thomastaylor312** [comment]
Thanks for creating this @bacongobbler! I'm working on the solution for it

**Comment by valentin2105** [comment]
In my case, I need this because when I create a all in one Chart (pv,pvc,deploy,svc...) Helm deploy all-in-one and my Pods requiered volume don't get scheduled and stay in ContainerCreating state. 
It's because the PVC wasn't in BOUND state when pods get scheduled.

If Helm can wait for the PVC to be bound. It would be awesome. 🥇

**Comment by thomastaylor312** [comment]
@valentin2105 Are you saying that you want Helm to wait to schedule your `Deployment` until the PVC is bound? Just wanted to clarify

**Comment by valentin2105** [comment]
Yeah because Kubernetes schedule pods before PVC is bound and pods stay in ContainerCreating mode.. (after minutes K8 kill them & recreate them).
If Helm can wait the Bound state, the deployment would be ready directly.

**Comment by viglesiasce** [comment]
This would simplify the CI for charts as well. Thanks for biting it off @thomastaylor312!

**Comment by bacongobbler** [comment]
@valentin2105 I'd imagine that's something to be solved by a different use case. From how I understand this is the equivalent of someone doing a `helm install && kubectl get po -w`, then waiting until the pods are finished.

**Comment by thomastaylor312** [comment]
@valentin2105: I agree with @bacongobbler on this one. That would be a different feature request. I can still check wait for when the volumes are bound, but it won't wait to deploy pods. My current plan was to wait for pods, volumes, and services (to get an external IP address if they are a load balancer)

**Comment by valentin2105** [comment]
@thomastaylor312 Thanks, I think I need another workaround. :)

**Comment by urzds** [comment]
@valentin2105 I think your problem is described in kubernetes/kubernetes#28962

**Comment by iamzhout** [comment]
If this feature would be implemented, it would be of much help!  wanted +1 :)

**Comment by bacongobbler** [comment]
@iamzhout see #1820

**Comment by iamzhout** [comment]
thanks @thomastaylor312 @bacongobbler, glad to see this feature being implemented.

**Comment by luoxiaoxun** [comment]
I have two question:
(1) Why not implement wait function for uninstall step and petset type?
(2) Is it suitable for perform function use object selector as an option to get pods and then use length of pod items to determine resource is ok. For example, if replica of one deployment object is 3, if one pod is running and other two pods haven't been created when perform function  judge, it will determine the deployment resource is  ok ~!
@bacongobbler

**Comment by bacongobbler** [comment]
@luoxiaoxun good questions. Feel like making a PR to address those things? Might also want to review and input your feedback on #1820.
