### ISSUE TITLE
Wrappers logs/attach/exec for release

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/helm#1810]
I think it would be convenient to have wrappers around `kubectl` `logs/attach/exec` commands for release related pods/containers without need to use `kubectl get pods`, prior to using `kubectl` commands.

**Comment by technosophos** [comment]
This would be a great Helm plugin! I would definitely use something like this.

**Comment by whitecolor** [comment]
Does helm support plugin system?

**Comment by technosophos** [comment]
Yeah. We added it in 2.1. We're just getting started developing useful plugins. Here are the current docs: https://github.com/kubernetes/helm/blob/master/docs/plugins.md

The nice thing is that you can actually write plugins in whatever language you want. So things like this might be easy to do with a shell script plugin.

**Comment by bacongobbler** [comment]
For anyone interested in looking for this workflow, They should look at https://github.com/Azure/draft. It uses Helm under the covers but provides convenience commands around a helm release such as `draft logs`, and `draft connect`.

**Comment by whitecolor** [comment]
@fejta-bot Rotten, hah? You are the rotten bot!
