### ISSUE TITLE
tiller installation fails

### ISSUE THREAD

**Issue by Masber** [kubernetes/helm#1821]
Hi,

I am trying to install tiller on centos7.3 and kubernetes 1.3.0 and repo [virt7-docker-common-release] but the installation fails:

```
[root@kub2 linux-amd64]# kubectl --version
Kubernetes v1.3.0
[root@kub2 linux-amd64]# kubectl get pods -o wide --namespace kube-system
NAME                            READY     STATUS             RESTARTS   AGE         IP            NODE
tiller-deploy-741207433-inddr   0/1       CrashLoopBackOff   5          <invalid>   172.30.67.2   kub2.local
[root@kub2 linux-amd64]# helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Error: cannot connect to Tiller
[root@kub2 linux-amd64]#
```

this the output I get from describe:

```
[root@kub2 linux-amd64]# kubectl describe pod tiller-deploy-741207433-inddr --namespace kube-system
Name:           tiller-deploy-741207433-inddr
Namespace:      kube-system
Node:           kub2.local/192.168.20.11
Start Time:     Fri, 13 Jan 2017 18:59:38 +1100
Labels:         app=helm
                name=tiller
                pod-template-hash=741207433
Status:         Running
IP:             172.30.67.2
Controllers:    ReplicaSet/tiller-deploy-741207433
Containers:
  tiller:
    Container ID:               docker://4e397379c1ffbd646833ee04420ca71f688a0b92d20a93749e140879c0224c64
    Image:                      gcr.io/kubernetes-helm/tiller:v2.1.3
    Image ID:                   docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:a5919b5a2a837fc265aeeb639413c653427332544c3a590bc8ed74370905d87a
    Port:                       44134/TCP
    State:                      Waiting
      Reason:                   CrashLoopBackOff
    Last State:                 Terminated
      Reason:                   Error
      Exit Code:                2
      Started:                  Fri, 13 Jan 2017 19:11:18 +1100
      Finished:                 Fri, 13 Jan 2017 19:11:28 +1100
    Ready:                      False
    Restart Count:              8
    Liveness:                   http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:                  http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:              <none>
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
No volumes.
QoS Tier:       BestEffort
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath           Type            Reason          Message
  ---------     --------        -----   ----                    -------------           --------        ------          -------
  11m           11m             1       {kubelet kub2.local}    spec.containers{tiller} Normal          Pulling         pulling image "gcr.io/kubernetes-helm/tiller:v2.1.3"
  11m           11m             1       {kubelet kub2.local}    spec.containers{tiller} Normal          Pulled          Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.1.3"
  11m           11m             1       {kubelet kub2.local}    spec.containers{tiller} Normal          Created         Created container with docker id 312a5d6bade4
  11m           11m             1       {kubelet kub2.local}    spec.containers{tiller} Normal          Started         Started container with docker id 312a5d6bade4
  11m           11m             1       {kubelet kub2.local}    spec.containers{tiller} Normal          Created         Created container with docker id 2ff3fa07b081
  11m           11m             1       {kubelet kub2.local}    spec.containers{tiller} Normal          Started         Started container with docker id 2ff3fa07b081
  11m           11m             1       {kubelet kub2.local}    spec.containers{tiller} Normal          Killing         Killing container with docker id 2ff3fa07b081: pod "tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  11m           11m             2       {kubelet kub2.local}                            Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 10s restarting failed container=tiller pod=tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)"

  11m   11m     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Created         Created container with docker id a80df9539156
  11m   11m     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Started         Started container with docker id a80df9539156
  11m   11m     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Killing         Killing container with docker id a80df9539156: pod "tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  11m   11m     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Created         Created container with docker id 96ddd81f775b
  11m   11m     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Started         Started container with docker id 96ddd81f775b
  10m   10m     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Killing         Killing container with docker id 96ddd81f775b: pod "tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  10m   10m     5       {kubelet kub2.local}                            Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 40s restarting failed container=tiller pod=tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)"

  10m   10m     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Created         Created container with docker id a670b0954eb6
  10m   10m     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Started         Started container with docker id a670b0954eb6
  9m    9m      1       {kubelet kub2.local}    spec.containers{tiller} Normal  Killing         Killing container with docker id a670b0954eb6: pod "tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  9m    8m      9       {kubelet kub2.local}                            Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=tiller pod=tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)"

  8m    8m      1       {kubelet kub2.local}    spec.containers{tiller} Normal  Created         Created container with docker id 92a100440cbd
  8m    8m      1       {kubelet kub2.local}    spec.containers{tiller} Normal  Started         Started container with docker id 92a100440cbd
  8m    8m      1       {kubelet kub2.local}    spec.containers{tiller} Normal  Killing         Killing container with docker id 92a100440cbd: pod "tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  8m    5m      14      {kubelet kub2.local}                            Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=tiller pod=tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)"

  5m    5m      1       {kubelet kub2.local}    spec.containers{tiller} Normal  Created                 Created container with docker id 29e6ad038757
  5m    5m      1       {kubelet kub2.local}    spec.containers{tiller} Normal  Started                 Started container with docker id 29e6ad038757
  5m    5m      1       {kubelet kub2.local}    spec.containers{tiller} Normal  Killing                 Killing container with docker id 29e6ad038757: pod "tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  25s   25s     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Created                 Created container with docker id ec97a8145e8c
  25s   25s     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Started                 Started container with docker id ec97a8145e8c
  11m   23s     8       {kubelet kub2.local}    spec.containers{tiller} Normal  Pulled                  Container image "gcr.io/kubernetes-helm/tiller:v2.1.3" already present on machine
  23s   23s     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Created                 Created container with docker id 4e397379c1ff
  23s   23s     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Started                 Started container with docker id 4e397379c1ff
  23s   23s     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Killing                 Killing container with docker id ec97a8145e8c: pod "tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  11m   23s     10      {kubelet kub2.local}                            Warning MissingClusterDNS       kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  11m   13s     10      {kubelet kub2.local}    spec.containers{tiller} Warning Unhealthy               Readiness probe failed: Get http://172.30.67.2:44135/readiness: dial tcp 172.30.67.2:44135: getsockopt: connection refused
  11m   13s     10      {kubelet kub2.local}    spec.containers{tiller} Warning Unhealthy               Liveness probe failed: Get http://172.30.67.2:44135/liveness: dial tcp 172.30.67.2:44135: getsockopt: connection refused
  13s   13s     1       {kubelet kub2.local}    spec.containers{tiller} Normal  Killing                 Killing container with docker id 4e397379c1ff: pod "tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)" container "tiller" is unhealthy, it will be killed and re-created.
  5m    12s     26      {kubelet kub2.local}                            Warning FailedSync              Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=tiller pod=tiller-deploy-741207433-inddr_kube-system(9d3bbe2e-d96e-11e6-a71d-0050568da433)"

  11m           12s             56      {kubelet kub2.local}    spec.containers{tiller} Warning BackOff         Back-off restarting failed docker container
  <invalid>     <invalid>       1       {default-scheduler }                            Normal  Scheduled       Successfully assigned tiller-deploy-741207433-inddr to kub2.local
[root@kub2 linux-amd64]#
```

Any suggestion?

**Comment by technosophos** [comment]
Okay, first, I think you have an incompatible combination of Kubernetes and Helm. If you can't upgrade Kubernetes to 1.5, you should probably downgrade Helm to 2.0.2. There were some breaking changes between Kube 1.4 and 1.5 APIs.

Second, are you able to get anything running in this cluster? If you can get a pod running, log into it, and dump it's environment (`$ env`), that might help. It looks like not all of the networking came up. It might just be that DNS is not all working inside the cluster.

**Comment by bacongobbler** [comment]
For an example of a running tiller deploy via vagrant: https://gist.github.com/bacongobbler/1eeece8982412c13965166a7149e35dc

Notice in the pod's environment that the KUBERNETES_SERVICE_* envvars are correctly set to the master API:

```
><> k --namespace kube-system exec tiller-deploy-3299276078-dn18b env | grep KUBERNETES_SERVICE
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_HOST=10.247.0.1
```

And cluster DNS is working and responsive:

```
><> k --namespace kube-system exec tiller-deploy-3299276078-dn18b cat /etc/resolv.conf
search kube-system.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.247.0.10
options single-request-reopen
options ndots:5
```

I don't think this is a problem with helm, per se.

**Comment by iamzhout** [comment]
From below event, it seems that the kubelet startup option on node `kub2.local` is missing option like `--cluster-dns=10.96.0.10`.

```  
11m   23s     10      {kubelet kub2.local}                            Warning MissingClusterDNS       kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
```

**Comment by Masber** [comment]
ok I just changed from installing kubernetes manually to using kubeadm, the version now is 1.5.1 and I can go further

**Comment by willise** [comment]
Have the save problem as you.  The issue's description is just identical. I have strugled serveral days on this problem :-(.

`(kube-master) ~ # helm version`
`Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Error: cannot connect to Tiller
`

`(kube-master) ~ # kc version`
`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"a55267932d501b9fbd6d73e5ded47d79b5763ce5", GitTreeState:"clean", BuildDate:"2017-04-14T13:36:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}`

These two images both works badly.
`(kube-master) ~ # dc images | grep tiller`
`gcr.io/kubernetes-helm/tiller                         canary              6306de12bf3f        10 hours ago        70.6 MB
gcr.io/kubernetes-helm/tiller                         v2.4.1              44db9e64605b        8 days ago          70.3 MB`

I have already tested my k8s cluster with other RC yamls which contains simple probes. The result shows as my expect. 

Any help will be appreciated. @Masber @technosophos

**Comment by technosophos** [comment]
@willise Can you please dump the `kubectl describe` info for your Tiller? What does the output of `helm init` say?

**Comment by willise** [comment]
@technosophos Here comes my detailed info. In addition, the environment is  two VMs on VBOX as a master which also runs kubelet and a node. Each VM has three nics which are Host-only, NAT and Bridged adapter. 

**(kube-master) ~ # helm init**
$HELM_HOME has been configured at /root/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!


**(kube-master) ~ # kcm get pods**
NAME                             READY     STATUS             RESTARTS   AGE
tiller-deploy-3210876050-w1sft   0/1       CrashLoopBackOff   3          1m


**(kube-master) ~ # kcm logs tiller-deploy-3210876050-w1sft**
Error from server: Get https://kube-master:10250/containerLogs/kube-system/tiller-deploy-3210876050-w1sft/tiller: dial tcp 127.0.0.1:10250: getsockopt: connection refused


**(kube-master) ~ # kcm describe pod tiller-deploy-3210876050-w1sft**
Name:		tiller-deploy-3210876050-w1sft
Namespace:	kube-system
Node:		kube-master/10.0.3.15
Start Time:	Sun, 14 May 2017 00:09:58 +0800
Labels:		app=helm
		name=tiller
		pod-template-hash=3210876050
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-3210876050","uid":"9c74f13a-37f6-11e7-88c9-080...
Status:		Running
IP:		172.17.81.2
Controllers:	ReplicaSet/tiller-deploy-3210876050
Containers:
  tiller:
    Container ID:	docker://f3ff06a78ae70f0bcca9eafdafa88b15ae3f72fbb89eb40de8c4c2e5daedd91d
    Image:		gcr.io/kubernetes-helm/tiller:v2.4.1
    Image ID:		docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:cbe82d1748af14359cd6d2d07efd32007f69be23b8833d095995d0ea0dceb40a
    Port:		44134/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Sun, 14 May 2017 00:11:36 +0800
      Finished:		Sun, 14 May 2017 00:11:36 +0800
    Ready:		False
    Restart Count:	4
    Liveness:		http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:	kube-system
    Mounts:		<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:	<none>
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  2m		2m		1	default-scheduler				Normal		Scheduled	Successfully assigned tiller-deploy-3210876050-w1sft to kube-master
  2m		2m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Created		Created container with docker id f9ad9343a089; Security:[seccomp=unconfined]
  2m		2m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Started		Started container with docker id f9ad9343a089
  2m		2m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Started		Started container with docker id 53eb0cdc6648
  2m		2m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Created		Created container with docker id 53eb0cdc6648; Security:[seccomp=unconfined]
  2m		2m		3	kubelet, kube-master				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 10s restarting failed container=tiller pod=tiller-deploy-3210876050-w1sft_kube-system(9c7675c7-37f6-11e7-88c9-0800277f3bd9)"

  2m	2m	1	kubelet, kube-master	spec.containers{tiller}	Normal	Created		Created container with docker id b9ca2641cd26; Security:[seccomp=unconfined]
  2m	2m	1	kubelet, kube-master	spec.containers{tiller}	Normal	Started		Started container with docker id b9ca2641cd26
  2m	2m	2	kubelet, kube-master	spec.containers{tiller}	Warning	Unhealthy	Liveness probe failed: Get http://172.17.81.2:44135/liveness: dial tcp 172.17.81.2:44135: getsockopt: connection refused
  2m	2m	2	kubelet, kube-master	spec.containers{tiller}	Warning	Unhealthy	Readiness probe failed: Get http://172.17.81.2:44135/readiness: dial tcp 172.17.81.2:44135: getsockopt: connection refused
  2m	2m	2	kubelet, kube-master				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 20s restarting failed container=tiller pod=tiller-deploy-3210876050-w1sft_kube-system(9c7675c7-37f6-11e7-88c9-0800277f3bd9)"

  1m	1m	1	kubelet, kube-master	spec.containers{tiller}	Normal	Created		Created container with docker id f5f05309d78b; Security:[seccomp=unconfined]
  1m	1m	1	kubelet, kube-master	spec.containers{tiller}	Normal	Started		Started container with docker id f5f05309d78b
  1m	1m	4	kubelet, kube-master				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 40s restarting failed container=tiller pod=tiller-deploy-3210876050-w1sft_kube-system(9c7675c7-37f6-11e7-88c9-0800277f3bd9)"

  2m	1m	5	kubelet, kube-master	spec.containers{tiller}	Normal	Pulled			Container image "gcr.io/kubernetes-helm/tiller:v2.4.1" already present on machine
  2m	1m	6	kubelet, kube-master				Warning	MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  1m	1m	1	kubelet, kube-master	spec.containers{tiller}	Normal	Created			Created container with docker id f3ff06a78ae7; Security:[seccomp=unconfined]
  1m	1m	1	kubelet, kube-master	spec.containers{tiller}	Normal	Started			Started container with docker id f3ff06a78ae7
  2m	4s	15	kubelet, kube-master	spec.containers{tiller}	Warning	BackOff			Back-off restarting failed docker container
  1m	4s	6	kubelet, kube-master				Warning	FailedSync		Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=tiller pod=tiller-deploy-3210876050-w1sft_kube-system(9c7675c7-37f6-11e7-88c9-0800277f3bd9)"

**Comment by willise** [comment]
@technosophos Here comes my detailed info. In addition, the environment is two VMs on VBOX as a master which also runs kubelet and a node. 

(kube-master) ~ # helm init
$HELM_HOME has been configured at /root/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!


(kube-master) ~ # kcm get pods
NAME                             READY     STATUS             RESTARTS   AGE
tiller-deploy-2954955751-t1z8p   0/1       CrashLoopBackOff   3          1m



(kube-master) ~ # kcm logs tiller-deploy-2954955751-t1z8p



(kube-master) ~ # kcm describe pod tiller-deploy-2954955751-t1z8p
Name:		tiller-deploy-2954955751-t1z8p
Namespace:	kube-system
Node:		kube-master/192.168.0.4
Start Time:	Sun, 14 May 2017 02:22:43 +0800
Labels:		app=helm
		name=tiller
		pod-template-hash=2954955751
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-2954955751","uid":"27b10ea0-3809-11e7-b575-080...
Status:		Running
IP:		172.17.81.2
Controllers:	ReplicaSet/tiller-deploy-2954955751
Containers:
  tiller:
    Container ID:	docker://5043f8831cea171d23d0e1294ebcba4df19f154d8bddc33f4e202f01b351bd58
    Image:		tiller:v2.4.1
    Image ID:		docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:cbe82d1748af14359cd6d2d07efd32007f69be23b8833d095995d0ea0dceb40a
    Port:		44134/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	2
      Started:		Sun, 14 May 2017 02:23:59 +0800
      Finished:		Sun, 14 May 2017 02:24:03 +0800
    Ready:		False
    Restart Count:	4
    Liveness:		http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:	kube-system
    Mounts:		<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:	<none>
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  2m		2m		1	default-scheduler				Normal		Scheduled	Successfully assigned tiller-deploy-2954955751-t1z8p to kube-master
  2m		2m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Created		Created container with docker id d7b6651c079e; Security:[seccomp=unconfined]
  2m		2m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Started		Started container with docker id d7b6651c079e
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Created		Created container with docker id d715ed4ad3db; Security:[seccomp=unconfined]
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Killing		Killing container with docker id d7b6651c079e: pod "tiller-deploy-2954955751-t1z8p_kube-system(27b1eca3-3809-11e7-b575-0800277f3bd9)" container "tiller" is unhealthy, it will be killed and re-created.
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Started		Started container with docker id d715ed4ad3db
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Killing		Killing container with docker id d715ed4ad3db: pod "tiller-deploy-2954955751-t1z8p_kube-system(27b1eca3-3809-11e7-b575-0800277f3bd9)" container "tiller" is unhealthy, it will be killed and re-created.
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Started		Started container with docker id cbd2c4d3046c
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Created		Created container with docker id cbd2c4d3046c; Security:[seccomp=unconfined]
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Started		Started container with docker id 9303fe3f7b34
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Killing		Killing container with docker id cbd2c4d3046c: pod "tiller-deploy-2954955751-t1z8p_kube-system(27b1eca3-3809-11e7-b575-0800277f3bd9)" container "tiller" is unhealthy, it will be killed and re-created.
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Created		Created container with docker id 9303fe3f7b34; Security:[seccomp=unconfined]
  1m		1m		1	kubelet, kube-master	spec.containers{tiller}	Normal		Killing		Killing container with docker id 9303fe3f7b34: pod "tiller-deploy-2954955751-t1z8p_kube-system(27b1eca3-3809-11e7-b575-0800277f3bd9)" container "tiller" is unhealthy, it will be killed and re-created.
  1m		59s		3	kubelet, kube-master				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 20s restarting failed container=tiller pod=tiller-deploy-2954955751-t1z8p_kube-system(27b1eca3-3809-11e7-b575-0800277f3bd9)"

  2m	46s	5	kubelet, kube-master	spec.containers{tiller}	Normal	Pulled			Container image "tiller:v2.4.1" already present on machine
  2m	46s	6	kubelet, kube-master				Warning	MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  46s	46s	1	kubelet, kube-master	spec.containers{tiller}	Normal	Started			Started container with docker id 5043f8831cea
  46s	46s	1	kubelet, kube-master	spec.containers{tiller}	Normal	Created			Created container with docker id 5043f8831cea; Security:[seccomp=unconfined]
  1m	42s	7	kubelet, kube-master	spec.containers{tiller}	Warning	Unhealthy		Liveness probe failed: Get http://172.17.81.2:44135/liveness: dial tcp 172.17.81.2:44135: getsockopt: connection refused
  42s	42s	1	kubelet, kube-master	spec.containers{tiller}	Normal	Killing			Killing container with docker id 5043f8831cea: pod "tiller-deploy-2954955751-t1z8p_kube-system(27b1eca3-3809-11e7-b575-0800277f3bd9)" container "tiller" is unhealthy, it will be killed and re-created.
  2m	42s	7	kubelet, kube-master	spec.containers{tiller}	Warning	Unhealthy		Readiness probe failed: Get http://172.17.81.2:44135/readiness: dial tcp 172.17.81.2:44135: getsockopt: connection refused
  1m	6s	8	kubelet, kube-master	spec.containers{tiller}	Warning	BackOff			Back-off restarting failed docker container
  42s	6s	5	kubelet, kube-master				Warning	FailedSync		Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 40s restarting failed container=tiller pod=tiller-deploy-2954955751-t1z8p_kube-system(27b1eca3-3809-11e7-b575-0800277f3bd9)"
