### ISSUE TITLE
tiller:v2.1.3 image in gcr.io has a bad mediaType

### ISSUE THREAD

**Issue by duglin** [kubernetes/helm#1824]
See: https://github.com/docker/docker/issues/30083

In talks with the gcr.io guys they said that the image was uploaded with the bad mediaType (text/html) and are suggesting that the image be rebuilt and repushed. They'd also like to track down how this happened to begin with, which would be good, but I think getting an image that Docker v1.14 can download up there quickly would be good since its being released soon.

**Comment by technosophos** [comment]
Thanks for the heads-up. I'll put this on the roadmap for the next release.

**Comment by viglesiasce** [comment]
This can be fixed by changing the docker version to >1.11.0 here:
https://github.com/kubernetes/helm/blob/master/circle.yml#L3

**Comment by cblecker** [comment]
It looks like 1.10.0 is the latest version CircleCI supports 😞 .

Ref:
https://discuss.circleci.com/t/support-docker-versions-newer-than-v1-9-1/7789
https://github.com/circleci/docker/issues/6

**Comment by technosophos** [comment]
@prydonius pointed this out: https://github.com/docker/docker/issues/30083

But we seem to be in a really awkward position, where CircleCI is stuck on Docker 1.10 while 1.13 _definitely_ has this issue.

**Comment by cblecker** [comment]
This may be a dumb question, but:
CircleCI is using a version of Docker they released [almost a year ago](https://discuss.circleci.com/t/docker-1-10-0-is-available-beta/2100). Is there anything binding kubernetes/helm to use CircleCI, as opposed to another CI service like Travis ([who uses the official docker repos](https://docs.travis-ci.com/user/trusty-ci-environment/#Docker), so they have the latest version available)? It looks like this may have even been worked on recently, in #1672.

**Comment by technosophos** [comment]
We moved from Travis to CircleCI because of the resource restrictions on the Kubernetes org (we had to wait up to 3 hours for a build to even start). We toyed with going back not too long ago.

But... no, there is no reason why we can't switch to another CI provider.

**Comment by technosophos** [comment]
I am told that Docker fixed this in 1.13.1. The first RC is here: https://github.com/docker/docker/releases/tag/v1.13.1-rc1

If anyone has a chance to test that and confirm the fix, please let me know. Otherwise, we'll probably wait until the 1.13.1 final release comes out in a week.

**Comment by prydonius** [comment]
Just upgraded to 1.13.1-rc1 and can confirm it's fixed:

```
# before upgrade
$ docker version
...
 Version:      1.13.0
...
$ docker pull gcr.io/kubernetes-helm/tiller:v2.1.3
Error response from daemon: target is unknown

# after upgrade
$ docker version
...
 Version:      1.13.1-rc1
...
$ docker pull gcr.io/kubernetes-helm/tiller:v2.1.3
v2.1.3: Pulling from kubernetes-helm/tiller
985c5f84712b: Already exists
83826658bfb8: Pull complete
Digest: sha256:a5919b5a2a837fc265aeeb639413c653427332544c3a590bc8ed74370905d87a
Status: Downloaded newer image for gcr.io/kubernetes-helm/tiller:v2.1.3
```

**Comment by technosophos** [comment]
Yes! Fantastic!
