### ISSUE TITLE
helm times out on installs and upgrades

### ISSUE THREAD

**Issue by seanknox** [kubernetes/helm#1826]
Hey all—since upgrading to v2.1.3, all `helm install` and `helm upgrade` commands time out, while the operations appears to be executed by k8s:

```
$ helm install --namespace acceptance -n acceptance able-rails -f acceptance.yaml
Error: timed out waiting for the condition
```
In this case, all the relevant k8s objects appears to be created just fine, but `helm` itself doesn't return success.  Same thing on upgrades.

**Comment by technosophos** [comment]
If you set `--timeout` to be some big number, does it still timeout? We did merge a change (namely, adding `--timeout`) that could have impacted this by setting a lower default.

**Comment by iamzhout** [comment]
@seanknox I suspect the way you did to "upgrading to v2.1.3", would you please show result of `helm version`?

**Comment by seanknox** [comment]
helm version:
```
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
```

timeout occurs after five minutes:

```
❯ time helm upgrade  demo1 ~/src/charts/able-rails -f ps.yaml
Error: UPGRADE FAILED: timed out waiting for the condition
helm upgrade demo1 ~/src/charts/able-rails -f ps.yaml  
0.09s user 0.03s system 0% cpu 5:02.41 total
```

So, I'm wondering what event(s) are still ongoing that helm would be waiting. Do you have ideas on how to debug further?

**Comment by seanknox** [comment]
In this particular case, I think this might be related to a job that executes as a `post-upgrade` hook. The chart in question is for a Rails app and runs a [DB migration](http://guides.rubyonrails.org/active_record_migrations.html) on release upgrades. At some release point in the past, the job pod had issues and never completed successfully.

During this below chart upgrade, all new k8s objects were created except jobs. helm appeared stuck again. I deleted all old chart jobs and upon the last job being deleted, the helm CLI returned with an "release already exists" error. With the bad jobs out of the way, subsequent upgrades appear to be working.

```
[seanknox:~/src/ablehealth/charts]$ helm upgrade demo1 ~/src/ablehealth/charts/able-rails -f demo1.yaml --set ImageTag="06bbf3b7"
Error: UPGRADE FAILED: release: already exists
[seanknox:~/src/ablehealth/charts]$ helm upgrade demo1 ~/src/ablehealth/charts/able-rails -f demo1.yaml --set ImageTag="06bbf3b7"
Release "demo1" has been upgraded. Happy Helming!
LAST DEPLOYED: Thu Jan 26 13:40:57 2017
NAMESPACE: demo1
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                                TYPE                             DATA      AGE
demo1-private-registry-1485466857   kubernetes.io/dockerconfigjson   1         7s
demo1-ssl-1485466857   Opaque    2         7s
demo1-redis   Opaque    1         6d

==> v1/Service
NAME          CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
demo1-redis   10.3.0.91    <none>        6379/TCP   6d
demo1-able-rails   10.3.0.147   a6715eae7bd28...   80:30515/TCP,443:32101/TCP   49d

==> extensions/Deployment
NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
demo1-able-rails-worker   1         1         1            1           49d
demo1-redis   1         1         1         1         6d
demo1-able-rails-web   1         2         1         1         49d
```

I think I can close this issue, but before I do, any other insight y'all have?

**Comment by technosophos** [comment]
That makes sense. Jobs have bitten us before for this same reason.

**Comment by seanknox** [comment]
Roger. Thanks @technosophos!

**Comment by IamViditAgarwal** [comment]
I am facing the same issue. @seanknox . I tried ur way by deleting all the Pre-Pullers but facing the same issue
