### ISSUE TITLE
`helm upgrade --install` does not work when you garbage-collect old releases

### ISSUE THREAD

**Issue by majewsky** [kubernetes/helm#1829]
In https://github.com/kubernetes/helm/blob/672d014ccd3f965883e4713e36388f7b15734b97/cmd/helm/upgrade.go#L132, the `--install` flag to `helm upgrade` decides whether to upgrade or install by looking for version 1 of the release in question. That's all nice until you start to garbage-collect old releases, in which case you will get

```
Release "example" does not exist. Installing it now.
Error: a release named "example" already exists
```

cc @thgrs  who found the issue on our side

**Comment by technosophos** [comment]
What do you mean "garbage collect" old releases? Is that manually deleting old ConfigMaps?

I think this could be fixed by just sending a list or history request instead (at line 132). I think that is altogether more robust than what we were doing in that block you pointed out. Does that sound good to you?

Maybe like this: https://github.com/kubernetes/helm/blob/672d014ccd3f965883e4713e36388f7b15734b97/cmd/helm/history.go#L86

**Comment by majewsky** [comment]
> What do you mean "garbage collect" old releases? Is that manually deleting old ConfigMaps?

We're not doing it manually anymore, but yes, that's what I mean: https://github.com/sapcc/kubernetes-operators/tree/master/helm-garbagecollector

The rationale is the same as with the `revisionHistoryLimit` on a Kubernetes Deployment object. We deploy a quite large chart (https://github.com/sapcc/openstack-helm), and once a few hundred releases had accumulated in our staging env, many Helm operations (and many kubectl operations, even) got really sluggish because the few hundred configmaps occupy an impressive amount of space in the etcd. I don't have the exact numbers, but I have been told that our k8s's etcd's disk footprint had grown to 3-4 GB (with 8 GB being the limit at which etcd would start to break down), and we had a lot of failed raft proposals and leader elections going on in the etcd cluster because of that. Now that garbage collection is in place, we're back down to 500 MB and everything is running smoothly again.

The ideal solution, in fact, would be if Helm releases had a `revisionHistoryLimit` like Kubernetes deployments do, so we can do away with our custom garbage collector.

**Comment by technosophos** [comment]
Okay, I'm dropping this onto the 2.3.0 release and we'll fix the history request.

The secondary issue of limiting revision history is one we should also explore, but that probably won't make it into the 2.3.0 release.

**Comment by technosophos** [comment]
I opened a fix for the main issue, and also opened a separate feature request (#1081) to track your feature request.
