### ISSUE TITLE
Suggest to enlarge default resource name char length limit to 63

### ISSUE THREAD

**Issue by iamzhout** [kubernetes/helm#1831]
The default resource name length when running `helm create` is limited to [24 chars](https://github.com/kubernetes/helm/blob/master/pkg/chartutil/create.go#L170), 
suggest to enlarge it to 63 chars as kubernetes 1.4 should have already supported this by [this PR](https://github.com/kubernetes/kubernetes/pull/29523).

**Comment by iamzhout** [comment]
Since this is a minor change, I have submitted a PR (https://github.com/kubernetes/helm/pull/1830) for this,  please help to check if this is suitable for merge.

**Comment by technosophos** [comment]
Thanks. I am marking this as closed with #1830 , which I just merged.

Thank you for the PR.

**Comment by iamzhout** [comment]
@technosophos My pleasure, thanks for this great project. :)
