### ISSUE TITLE
is it necessary to add 'helm reset' to revert what init does?

### ISSUE THREAD

**Issue by iamzhout** [kubernetes/helm#1832]
As title, just like `kubeadm reset`, is it necessary to add `helm reset` to revert the change that init does:

1. clean the client
2. remove the tiller deployment in kubernetes cluster

**Comment by technosophos** [comment]
We could do this. What are the pros and cons of deleting the client's `HELM_HOME`? Do the uninstallers of normal tools destroy the local config dir? I'm not sure.

**Comment by iamzhout** [comment]
So maybe we can add some option and make its default behavior is to remove tiller deployment, such as `--client-only`, `--server-only`, `--both`, etc.

**Comment by technosophos** [comment]
Closed by #1850
