### ISSUE TITLE
proposal: add condition and tags fields to requirements entries

### ISSUE THREAD

**Issue by jascott1** [kubernetes/helm#1837]
## Problems

  1. Currently there is no simple way to selectively enable/disable sub-charts. This limitation makes composing with charts (e.g. choosing from more than one type of db) difficult and spawns workarounds such as template wrapping.
  2. Currently there is no simple way to selectively install groups of sub-charts. This limitation makes composing with charts (e.g. installing a minimal 'compute-kit' subset of charts ) more difficult.   

Note: Both are addressed here because they operate similarly and likely need changes in the same place in the code. Also, Tags would likely depend on the chart's 'enabled' status.

## "Condition" field

The conditional field attempts to solve problem 1.

Add an optional field "condition" to chart.yaml and requirements.yaml entries. The value of this field would be a YAML path in dot notation (e.g. mariadb.enabled). The YAML path is then looked up in the parent charts values and if found with a value of false (actual false, not just falsy) the relevant chart is not loaded. If the path does not exist or is not explicitly false, the chart is loaded as normal. 

````
# parent/requirements.yaml
    dependencies:
       - name: subchart1
	  repository: http://localhost:10191
	  version: 0.1.0
	  condition: subchart1.enabled
````

````
# parent/values.yaml
    subchart1:
       enabled: false

````

In the above example, the chart 'subchart1' would NOT be loaded since its condition value exists in the parent's values and returns false.

## "Tags" field

This attempts to solve problem 2.

Add an optional field "tags" to chart.yaml and requirements.yaml entries. The value of this field would be a YAML list of one or more "tags". 

````
# parent/requirements.yaml
    dependencies:
      - name: subchart1
        repository: http://localhost:10191
        version: 0.1.0
        condition: subchart1.enabled
        tags:
          - front-end
          - subchart1
      - name: subchart2
        repository: http://localhost:10191
        version: 0.1.0
        condition: subchart1.enabled
        tags:
          - back-end
          - subchart2
````

In values.yaml, "tags" field is introduced as a new top level key. The value of this key contains key/value pairs or a YAML list which specifies which groups of charts should be enabled/disabled based on their tag. Two possible approaches to formatting tags in the values.yaml are listed below.

````
# parent/values.yaml

# switch-like
tags:
  front-end: true
  back-end: false

# list-like
tags:
  - front-end
````

In the above "switch-like" example, all charts containing the tag "front-end" would be installed and those containing the "back-end" would not. In case of conflict, the "condition" value wins over "tags" which allows a group to be enabled (e.g. all "front-end" charts) and allows one or more unnecessary sub-charts in that group to be disabled or vice-versa. 
Some problems like how to resolve conflicting tags still need discussion. 

Additionally the tags could be specified as a special set parameter using the CLI

````
# using the command line
helm install --set tags.front-end=true,tags.back-end=false
````

## Complex use cases with condition logic

To achieve very complex use cases where sub-charts are re-used with different values within the same release, we should discuss the pros/cons of allowing the condition field to contain logic.

### Logic in condition field options

1. follow a convention
   a. given a list of yaml paths, use the first one that resolves
   b. use a format like k8s labels, something like  - {key: environment, operator: NotIn, values: [dev]}
   c. ?

2. allow TPL access, can access templates and template functions

3. run arbitrary golang >:)

### Example complex use case

Two umbrella charts (who are themselves a member of a global umbrella) each have many sub-charts, some of which need to be enabled/disabled based on logical AND/OR of other keys. Furthermore, charts at any level can have more than one instantiation with different values. 

*charts*
rootChart
-subchart1
--subchartA 
---subchartZ (conditionally enable/disable from values)
---subchartY(enable if peer subchartZ is enabled and mykey is disabled )
--subchartB
-subchart2 
--subchartA (disabled)
--subchartB (enabled with different values that other B chart)
---subchartZ (conditionally enable/disable from values)
---subchartY(enable if peer subchartZ is enabled and mykey is disabled )

**Comment by thomastaylor312** [comment]
@jascott1 Sorry this took a bit for me to get to. Just for clarification, are you wanting to choose one over the other or is this a proposal to implement both of them?

**Comment by jascott1** [comment]
This is a proposal to implement both together. Im working on some complex use cases right now. Please share your thoughts. Thanks Thomas!

**Comment by prydonius** [comment]
@jascott1 there is a discussion on this in #1568, although I'm not sure if you intended to create this issue to surface the proposal in https://github.com/kubernetes/helm/issues/1568#issuecomment-264145982?

**Comment by jascott1** [comment]
Yes I created this to surface @syhol's idea and then tags were an idea added by @technosophos

**Comment by technosophos** [comment]
I am in favor of this proposal. I think it very cleverly solves some real-world problems that have surfaced several times.

I have a few specific comments on specific issues you raised.

### List vs Switch

Regarding _list vs. switch, I'm slightly in favor of switches because it does make it easy to manage. With lists, there's always a question of whether the intent is to replace the list or modify the list. With switches, you can deal with just one item at a time.

That is, say we have a chart with five tags, all of which are on by default. Turning off one tag feels easier with _switch_ syntax: `--set tags.foo=false`. The _list_ syntax would be `--set tags={bar,baz,blarg,zap}` (or, turning on all the tags that aren't `foo`).

Analogously, when merging two YAML files (`values.yaml` and `-f myvals.yaml`), it's much easier to merge switches:

Values.yaml:
```yaml
tags:
  foo: false
  bar: false
  baz: true
  zap: true
```

myvals.yaml:
```yaml
tags:
  baz: false
  bar: true
```

Seems like the expected output is pretty simple to compute:

```yaml
tags:
  foo: false
  bar: true
  baz: false
  zap: true
```

But, truth be told, we could make either work.

### Conditions

I wouldn't mind punting on conditions initially, but if we added them, I think I would suggest ruling out sending values YAML files through the template engine. It gets pretty confusing for users to understand multiple template runs, and which runs have which values available to them.

I like keeping in mind some available options for this.

### Nested charts

One thing we will need to decide is how to handle scoping for nested charts. Do we treat the `tags` object like `global` and pass it down unmodified to children? Or do we try to scope tags the same way we scope regular values?

With conditions, I'm a little concerned about how we would resolve these relatively. Say we have this graph:

```
mychart/
  - charts/
    - worker1/
      - charts/
        - mysql/
    - worker2/
      - charts/
        - mysql/
```

In the chart above, we have two instances of MySQL being created -- one for worker1, and one for worker2. How do we disable worker1's MySQL without disabling worker2's? How does that look at the top level (e.g. in `mychart/values.yaml`) versus in the subchart (`mychart/charts/worker1/values.yaml`)?

Looking forward to adding this feature. I think it's going to be really helpful.

**Comment by kfox1111** [comment]
Two thoughts. Kolla-kubernetets is using a nested value sturcture now to make it easy to set a value more generically and hit a bunch of subcharts, and then set values more specifically to affect fewer.

This ends up with a search path like:
if defined at Values.foo, use that.
if defined at globals.kolla.mysubchart.foo, use that.
if defined at globals.kolla.allcharts.foo use that.

So it would be nice if the conditional value to lookup, was at least a list, with this same behavior.

I can see some strong benifit to being able to call out to macro's to use for the conditionals. Users could then use the same logic inside the templates as in the conditionals. It may or may not require some real heavy lifting in the engine though. not sure how it is architected currently.

As for whether subcharts get the parents values or not, raw, I think currently I'd like to see it not. but I could see some cases where it should... so kind of a hard thing to decide... Perhaps it should be a field in Charts.yaml and support both ways? Then it can be set as needed per chart.

**Comment by jascott1** [comment]
@technosophos By using globals we have been able to create nested values structure that results in the following except I have added the enabled and rabbitmq properties (but they are doable). 

````
COMPUTED VALUES:
global:
  kolla:
    all:
      kubernetes_entrypoint: true
      rabbitmq:
          all:
              port: 5672
              mgmt_port: 15672
          ...
    neutron:
      enabled: true
      # this is optional
      rabbitmq:
          all:
              port: 5672
              mgmt_port: 15672
          ...


To @kfox1111 's point, we could check global.neutron.rabbitmq and then fallback to global.kolla.all.rabbitmq by using a list of those YAML paths as the condition. We are already doing this using gotpl. To implement that now we would need to consider the future use and if we are ok with assuming a condition field containing a list will be treated this way (first one that exists wins). It might be a good start and allow us to add functionality later.

**Comment by technosophos** [comment]
So in the `condition` field, `,` would be treated as an OR?

This is the situation I was thinking about when I suggested that we might want some operators, since I could also imagine someone wanting to specify an AND or NOT condition there. And maybe it would be as simple as considering ',' to be OR, '^' to be NOT ('!' is a control character in YAML), and '&' to be AND.

One thing to keep in mind as we design this: At the time that we have to evaluate the conditions on the `requirements.yaml` file, we will have only the following pieces of information available to us:

- The merged contents of `-f` and `--set`
- The files in the top-level chart, including `values.yaml`

Globals, for example, can't be fully populated until _after_ we've figured out which charts to include. So only the globals in the top-level chart would be available in this context. (That's not a show stopper at all -- just wanted to point out that some users could get confused by this).

**Comment by jascott1** [comment]
@technosophos Good point about globals. Also I like the simple logic operator idea. Here are some examples

````
condition: ke1,key2^key3

key1 exists OR key2 exists AND NOT key3
````

````
condition: key1&key2,key3^key4

key1 AND key2 exist OR key3 AND NOT key4
````
````
condition: ^key1,key2

NOT key1 exist OR key2 exist
````

````
condition: key1,key2,&key3

the ,& above should throw error imo
````

In my original work, loading a chart is only skipped when the path exists and value is actual false. This means unless explicitly disabled, charts always load. Now though if we have above logic, a condition such as "^key1" (NOT key1) would mean what if key1=true in values?

**Comment by thomastaylor312** [comment]
@jascott1 With that third example, it would probably be clearer to require parens. So `^(key1,key2)`. As you have it written, it seems like `NOT key1 exists or key2 exists`

**Comment by kfox1111** [comment]
@technosophos: What I was suggesting is something different then an or for ','

Say you have these values:
globals:
  kolla:
     all:
        enabled=true
     mythingIcareabout:
         enabled=false

ordering the list like:
globals.kolla.mythingicarabout.enabled,globals.kolla.all.enabled

I want the value of mythingicareabout to be the value, as it exists. if its true or false, thats the value if it exists.

If the entry is not defined at all, then it consideres the value of globals.kolla.all.enabled next.

Neither and, or or, has that behaviour. Does that make sense?

**Comment by jascott1** [comment]
@thomastaylor312 I did mean "NOT key1 exists or key2 exists" as an example to think thru. kfox1111 and others have also suggested parens, what do you think this style?

````
(global.a,global.b)&(global.c) 
global.a OR global.b result AND global.c
````

@kfox1111 not sure im getting you on last comment. what you said is the same as how we've been defining OR. 

````
globals.kolla.mythingicarabout.enabled,globals.kolla.all.enabled
use first if it exists else use second if it exists
````

**Comment by kfox1111** [comment]
so, or would be first defined value, not the logic, true if a or b is true? What if someone wanted a logical 'or' operator?

I'm a little worried this will turn into its own language all on its own. would it be better to just use a gotl macro? Then we can reuse the whole gotl engine for logic.

**Comment by jascott1** [comment]
@kfox1111 Right, OR on key existence not key value was the original idea. Maybe shows some of the confusion we might get when users try to grok it. Im also worried about the increase in complexity. By  "What if someone wanted a logical 'or' operator?" i take you mean operate on the value. If we start down that road then we would have to discuss "truthiness/falseness". ( in a "post truth" era :) 

YAML has a false so the original idea was that charts are enabled unless a specific path exists and is explicitly false. Then charts that have conditions could be used independently ignoring the condition altogether if no keys existed with false. Now we are talking about a more conventional (and intuitive) 'end result of combining a bool-ish expressions' so using a condition at all becomes more invasive.

**Comment by jascott1** [comment]
@technosophos Although the tpl approach has those downsides you mentioned is it possibly the lesser of two evils for conditions here? We don't have to invent/write/preach another system and tpl is documented and full featured (we are already using it for conditions).
Tags: I think we want nested tags for the complex use case and it seems like we could re-use the nested globals approach, is that the case?

**Comment by jascott1** [comment]
re: Tags

Anyone have any problems with the following statement:

"A chart will be loaded if at least one of its tags evaluates to true, unless overridden by a condition which evaluates to false"

````
#requirements.yaml
dependencies:
      - name: subchart1
        condition: subchart1.enabled
        tags:
          - front-end
          - subchart1
      - name: subchart2
        condition: subchart2.enabled
        tags:
          - back-end
          - subchart2
````
````
# values.yaml
tags:
  front-end: true
  back-end: false
  subchart2: true
````

In above example subchart2 chart is effectively enabled since the "subchart2" tag is true despite its other tag "back-end" being false. If the condition "subchart2.enabled" evals to false then the chart would NOT be loaded no matter what its tags are set to.

**Comment by jascott1** [comment]
The above PR #1917 introduces basic functionality for tags and conditions, each of which is in its own function. If we are happy with the approach it should be easy to add more advanced processing. Currently for conditions it only does 'first valid path wins' from comma delimited list of YAML paths. For tags, only the top parent's values is considered and only the root key "tags:". Tags under "globals:" are not implemented.

**Comment by jascott1** [comment]
Also, only requirements.yaml is searched for tags and conditions, Chart.yaml is not currently used (a change from original implementation). If requirements.yaml is supposed to represent developer intent (version choice etc) then it seems appropriate to only use that file and leave chart alone.
