### ISSUE TITLE
helm install --dry-run writes to current directory

### ISSUE THREAD

**Issue by ljnelson** [kubernetes/helm#1841]
Hello; thanks for a great product.  I'm psyched to see where this all goes.

It is possible I'm missing something in some documentation somewhere, but I was surprised to note that this:
`helm install --dry-run --debug stable/mongodb`
…caused the Mongo chart to show up in tarball form in the directory from which I ran `helm`.  Is this by design?

Transcript in case it's useful:

    LANELSON-mac:helm-work-area LANELSON$ pwd
    /Users/LANELSON/crap/helm-work-area
    LANELSON-mac:helm-work-area LANELSON$ helm version
    Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
    LANELSON-mac:helm-work-area LANELSON$ kubectl config current-context
    minikube
    LANELSON-mac:helm-work-area LANELSON$ ls -al
    total 0
    drwxr-xr-x    2 LANELSON  staff    68 Jan 19 15:56 .
    drwxr-xr-x  121 LANELSON  staff  4114 Jan 19 15:34 ..
    LANELSON-mac:helm-work-area LANELSON$ helm install --dry-run stable/mongodb
    NAME:   filled-leopard
    LANELSON-mac:helm-work-area LANELSON$ ls -al
    total 8
    drwxr-xr-x    3 LANELSON  staff   102 Jan 19 15:57 .
    drwxr-xr-x  121 LANELSON  staff  4114 Jan 19 15:34 ..
    -rw-r-xr-x    1 LANELSON  staff  3396 Jan 19 15:57 mongodb-0.4.4.tgz
    LANELSON-mac:helm-work-area LANELSON$

**Comment by technosophos** [comment]
That is by design (though perhaps it's not the best design).

When you do an install of a remote chart, it first fetches that chart to a local destination, then unpacks the chart (in memory) and sends it to the server. Essentially, it is equivalent to doing `helm fetch foo` followed by `helm install foo`.

Honestly, I no longer remember what the original reasoning was. But to maintain backward compatibility, we can't change it now. We probably could add a `--clean` flag (or something like that) and remove the file at the end of the command run. Thoughts on that?

**Comment by ljnelson** [comment]
I hear you in principle on the backwards compatibility issue, but my issue was with the `--dry-run` option.  Surely changing things for at least _this_ case (using `$TMP`, even, or some such) wouldn't break anything?  Dry runs really IMHO should be entirely idempotent.

**Comment by technosophos** [comment]
I'd be open to a PR that added this for `--dry-run`. I think I can safely mark it as a starter.

**Comment by vbmade2000** [comment]
Can I try working on this issue

**Comment by thomastaylor312** [comment]
I think #2142 is related to this one. There is a PR landing for it: #2558

**Comment by thomastaylor312** [comment]
Closed with #2558
