### ISSUE TITLE
Docs reference defunct "stable" repository

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/helm#1847]
Recommend replacing occurrences with "kubernetes-charts"

Particularly with the quickstart, noobs may be discouraged from proceeding

E.g. docs/quickstart.md

    helm install stable/mysql

E.g. docs/using_helm.md

Multiple occurrences

**Comment by prydonius** [comment]
Hey @DazWilkin, `stable` is the correct repository, and `kubernetes-charts` is defunct (see https://github.com/kubernetes/charts). If you're getting `kubernetes-charts` when running `helm repo list` you probably need to `rm ~/.helm` and re-run `helm init`.

**Comment by DazWilkin** [comment]
I'm likely an edge-case (a Googler on a Googler machine using GKE) so please don't spend much more time on this. I'd originally:

```
curl \
https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get \
> get_helm.sh
chmod +x get_helm.sh 
./get_helm.sh 

```

In order to use helm as my user rather than root, I moved then chown'd helm but this appears to make no difference.

Per prydonius@, I removed helm and restarted:

```
helm init
$HELM_HOME has been configured at $HOME/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message.)
Happy Helming!
```
```
helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kubernetes-charts" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
```

BUT:

```
helm search
NAME                           	VERSION	DESCRIPTION           
kubernetes-charts/chaoskube    	0.3.1  	A Helm chart for chaoskube
kubernetes-charts/chronograf   	0.1.0  	Chart for Chronograf
kubernetes-charts/cockroachdb  	0.2.0  	CockroachDB Helm chart for Kubernetes.
...
```

and then I discovered:

```
helm repo list
NAME             	URL                                            
kubernetes-charts	http://storage.googleapis.com/kubernetes-charts
```

**Comment by DazWilkin** [comment]
Used Stackpoint to create a cluster on DigitalOcean.

This works as you describe.

For this issue, the "stable" repository is used:

```
helm search
NAME                	VERSION	DESCRIPTION                   
stable/chaoskube    	0.3.1  	A Helm chart for chaoskube
stable/chronograf   	0.1.0  	Chart for Chronograf
stable/cockroachdb  	0.2.0  	CockroachDB Helm chart for Kubernetes.
```

```
helm repo list
NAME  	URL                                              
stable	https://kubernetes-charts.storage.googleapis.com/
local 	http://127.0.0.1:8879/charts  
```

and the password decoding issue #1848 works correctly too... hmmm

Apologies for the runaround.

**Comment by technosophos** [comment]
Hey, if you still have that broken version around, can you run `helm version --client` and tell me what version you got? I wonder if there's a bug in the `get` script that is fetching an old version.

Thanks!

**Comment by DazWilkin** [comment]
Here you go:

```
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
```

I swapped repo's manually and it's mostly working:

```
helm repo remove kubernetes-charts
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
```

**Comment by technosophos** [comment]
I'm at a loss to explain how `glide init` would have produced a local repo cache with a name other than `stable`. The names are hard-coded into `cmd/helm/init.go` as far as I can tell.

**Comment by technosophos** [comment]
Okay, I _think_ it's safe to close this issue. Please let me know if you see it again.
