### ISSUE TITLE
kubernetes-charts/mysql: "To get your root password" instructions incorrect

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/helm#1848]
helm install kubernetes-charts/mysql

Conveniently attempts to help get the user connected with:
```
To get your root password run:

    printf $(printf '\%o' `kubectl get secret --namespace default $NAME -o jsonpath="{.data.mysql-root-password[*]}"`);echo
```

It's not entirely clear to me how this should work, but it doesn't.

1. In my installation, "data.mysql-root-password" is a string not an array
2. The string is base64 encoded

On Ubuntu and MacOS, the following command appears to be sufficient:

```
kubectl get secret --namespace default $NAME -o jsonpath="{.data.mysql-root-password}" \
| base64 --decode
```

**Comment by prydonius** [comment]
Thanks @DazWilkin this is related to https://github.com/kubernetes/charts/issues/366.

**Comment by technosophos** [comment]
Does this issue need to be re-filed at https://github.com/kubernetes/charts/issues ? I don't think there's anything we (the Helm devs) need to do to fix this, is there?

**Comment by prydonius** [comment]
@technosophos we will track the issue in kubernetes/charts#366, as it affects a number of charts. Since this is a documentation issue in chart notes, there is no action needed here.

**Comment by technosophos** [comment]
I am closing this version, then, so we don't have to track this issue twice. Thanks to both of you!
