### ISSUE TITLE
write up a document on forking/upstreaming changes to charts

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes/helm#1854]
This action item came out of the sig-apps meeting. Basically we want to spell out how if someone has made a change to a chart or to the application image itself (such as a redis proxy), how they can contribute that change back to the chart itself.

I'm fairly certain that this topic was brought up by @dhilipsiva at the meeting. If it was, would you mind elaborating more on what you'd like to see from this document?

**Comment by dhilipsiva** [comment]
Hey @bacongobbler, Apologies - I do not remember bringing up this point. I think this is someone else. 😛 

But I would very much love to have this Doc. It wasnt very straight forward when I wanted to my own charts in the past (Needed to add a minio chart).

**Comment by technosophos** [comment]
I know I am _really, really_ late to weigh in on this, but I believe this issue should be filed on Kubernetes Charts instead of here.

**Comment by bacongobbler** [comment]
this has been documented at https://github.com/kubernetes/charts.
