### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes/helm#1858]
MackBookPro:helm administrator$ make build
GOBIN=/Users/administrator/Codes/go/src/k8s.io/helm/bin go install  -tags '' -ldflags ' -X k8s.io/helm/pkg/version.Version=v2.1.0 -X k8s.io/helm/pkg/version.GitCommit=dcae753a2e61ef1ab7f0d628729f9ba57a0a64c4 -X k8s.io/helm/pkg/version.GitTreeState=dirty' k8s.io/helm/cmd/...
# k8s.io/helm/pkg/kube
pkg/kube/client.go:324: not enough arguments in call to strategicpatch.CreateTwoWayMergePatch
make: *** [build] Error 2

**Comment by technosophos** [comment]
Did you do `make bootstrap` first?

**Comment by technosophos** [comment]
The issue seems to have gone silent. Closing. Reopen if you still need support.
