### ISSUE TITLE
Removal of Persistent Volumes

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/helm#1875]
I understand that it is quite expected behavior of helm to delete all the resources that were created while installation, but isn't unsafe to remove persistent volumes (and claims as well)?

Maybe after release deletion I would like old volumes to be assosiated with newly created resources. What do you think?

**Comment by technosophos** [comment]
I was under the impression that we did not remove the underlying volume/claim. Is that right @viglesiasce ?

**Comment by whitecolor** [comment]
you mean anotation to PVC resource? But it is not very convenient with 3rd party charts right? For example what should be done with this chart https://github.com/kubernetes/charts/tree/master/stable/mongodb ?

**Comment by whitecolor** [comment]
@technosophos ?

**Comment by viglesiasce** [comment]
When using StatefulSets the PVCs will be left alone. 

If using the PVC template in the chart then it will be deleted. We should add resource-policy: keep to the charts where we think it should be implemented although deleting the release is an indication that you want all of the resources to be deleted.

**Comment by technosophos** [comment]
I guess the suggestion, then, is to fork charts and modify them on your own.

**Comment by viglesiasce** [comment]
...and then submit that change back as PR to the charts repo.

**Comment by technosophos** [comment]
I think we should probably make it a best-practice to add this annotation to every chart that uses a PVC:

```
"helm.sh/resource-policy": {{ default "keep" .Values.resourcePolicy }}
``` 

Or, if we prefer, the default can be "delete". But the idea is to make it so that there is always a clear path for the user to toggle this.

**Comment by InAnimaTe** [comment]
I do the like the model of letting the user define this via annotation. I think we might want to make the default to keep them around unless the annotation is set. The other question is how to handle a `--purge` here, as I'd think most users would expect EVERYTHING to be forcibly removed on purge. Although, what if I want all the rollback configsets removed but not my PVC?

**Comment by technosophos** [comment]
Yeah, I think we'd have to assume that if you say you want to keep the PVC, that means you don't ever want Helm to delete it.

**Comment by whitecolor** [comment]
Removal of PV creating via PVC is still controlled not by `heml`, it is defined by reclaim policy on PV, should be `Retain`, but setting it via PVC annotations is not supported yet.
