### ISSUE TITLE
Add `--reuse-values/--set/-f` merge feature to upgrade

### ISSUE THREAD

**Issue by dzavalkinolx** [kubernetes/helm#1878]
I have a CD server on separate server somewhere which doesn’t have `values.yaml` used to create chart. Also it has new image tag (artefact id). Now I need this script to update only one value in already running helm chart.

There is already function `reuseValues`: https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_server.go#L334-L349 but it will be called only id no values are provided on upgrade. What I need is a way to supply new `values.yaml` and some flag to tell tiller to reuse old values.

**Comment by technosophos** [comment]
So what you would like is to have `reuse-values` merge any provided values into the existing values?

In the short term, the work-around I have suggested for CI in the past is to `helm get values`, then append the replacement value to the end, then `helm upgrade` with the new values.

**Comment by thomastaylor312** [comment]
I think a good way to do this would be to add a `--reuse-values` flag to `upgrade`. I don't think the default behavior should be to merge the values because that might lead to some confusion. What do you think?

**Comment by jascott1** [comment]
@dzavalkinolx you might look at this plugin https://github.com/skuid/helm-value-store

**Comment by kfox1111** [comment]
I think there are a few different use cases I can think of here.

User wants to 'upgrade' a helm package in a way, such as:
package has a configmap version value. its initially set to 1. it has a bunch of other values the user wants to keep.
user uploads configmap version 2.
user: 'helm upgrade <releasename> foo --set configmap_version=2'

but, maybe the use case could be:
helm update <releasename> --set configmap_version=2 instead?

**Comment by technosophos** [comment]
Just to quickly explain the current logic:

On upgrade:

- if `--set` or `-f` are specified, those values are sent as the new values, and old values are ignored.
- if _no_ values are sent, the existing values are simply re-used unmodified
- if no values are sent, and `--reset-values` is supplied, the upgrade will revert to the chart's built-in values

There is currently no way to tell Tiller to merge `--set`/`-f` values with the last set of values. The work-around has been to use `helm get values`, and then modify those values, and re-submit with `helm upgrade -f`.

My understanding is that we are talking about adding `--reuse-values` to trigger a merge between `--set`/`-f` and Tiller's existing copy of the values.

**Comment by technosophos** [comment]
Closed by #2138

**Comment by rimusz** [comment]
👍  👍  👍 
really looking forward to use feature with v2.3.0
