### ISSUE TITLE
Large install/upgrade occasionally doesn't give full output 

### ISSUE THREAD

**Issue by mikejk8s** [kubernetes/helm#1881]
* k8s version: 1.5.2
* Helm version: 2.1.3

I've got a helm chart that has around 60 yaml files, some of which contain 3-4 k8s objects (so let's say about 130-150 total items being deployed by Helm) and 1 out of every 10 or so install and/or upgrades results in the output after an install or upgrade only showing a couple of items, always the same items. No pods, deployments, etc are displayed.

The install/upgrade still works perfectly fine and all items are accounted for when doing kubectl get pods/etc but helm status $release will only display the couple of items that were shown.

* Helm get output IS correct (every k8s object listed)
* Helm status output is not correct (only my service account and some configmaps)
* Tiller logs correlate with helm status and only show the couple of items as well

This isn't really an issue for me as everything does deploy properly, it does cause some commands to be less useful (helm status $release) I just wanted to let you guys know. 

Thanks! 

@michelleN 

Example of not-full output

```
LAST DEPLOYED: Thu Jan 26 14:33:13 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME          DATA      AGE
map1   1         8m
map2   1         8m

==> v1/ServiceAccount
NAME               SECRETS   AGE
secret1   1         8m
 
```

Full output
```
Release "dinky-shrimp" has been upgraded. Happy Helming!
LAST DEPLOYED: Thu Jan 26 14:08:19 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME          DATA      AGE
map   1         1h
map  1         1h
pod   2         1h
map   1         1h
map  1         1h
map  1         1h
map  1         1h

==> v1/ServiceAccount
NAME               SECRETS   AGE
account  1         1h

==> extensions/Deployment
NAME             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
pod   1         1         1            1           1h
pod   1         1         1         1         1h
pod  1         1         1         0         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod  1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod-   1         1         1         1         1h
pod   1         1         1         1         1h
pod  1         1         1         1         1h
pod  1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         37m
pod  1         1         1         1         1h
pod 1         1         1         1         1h
pod   1         1         1         1         31m
pod  1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod  1         1         1         0         1h
pod  1         1         1         1         1h
pod  1         1         1         1         1h
pod  1         1         1         1         1h
pod  1         1         1         0         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         1         1h
pod   1         1         1         0         1h
pod  1         1         1         1         1h
pod  1         1         1         1         1h
pod  1         1         1         1         1h
pod   1         1         1         1         1h

==> extensions/Ingress
NAME             HOSTS                                            ADDRESS           PORTS     AGE
pod   

==> v1/ReplicationController
NAME                   DESIRED   CURRENT   READY     AGE
rc   1         1         1         1h

==> v1/Pod
NAME                       READY     STATUS    RESTARTS   AGE
pod   0/1       Pending   0          9s
pod   2/2       Running   0         1h
pod   2/2       Running   0         1h
pod   1/1       Running   0         1h
pod   1/1       Running   0         1h
pod   0/1       Pending   0         9s
pod   1/1       Running   0         1h
pod   1/1       Running   0         1h
pod   1/1       Running   0         1h
pod   1/1       Running   0         1h
pod   2/2       Running   0         1h
pod   0/1       Pending   0         8s
pod   1/1       Running   0         1m
pod   2/2       Running   0         1h
pod   1/1       Running   0         1h
pod  1/1       Running   0         1h

==> v1/Service
NAME               CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
pod  
pod  
pod   
pod
pod  
pod   
pod   
pod   
pod   
pod   
pod   
pod   
pod  
pod  
pod  
pod 
pod  
pod  
pod   
pod   
pod
pod 
pod 
pod   
pod  
pod   
pod  
pod   
pod
pod  
pod  
pod  
pod  
pod
pod
pod
pod
pod   
pod  
pod   
pod 
pod 
pod  
pod  
pod   
pod   
pod   
pod 
pod  
pod
pod 
pod

==> autoscaling/HorizontalPodAutoscaler
NAME                              REFERENCE                            TARGET    CURRENT   MINPODS   MAXPODS   AGE
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa
hpa

==> v1/Secret
NAME                  TYPE      DATA      AGE
secret  Opaque    1         1h
```

**Comment by technosophos** [comment]
Is there anything in the Tiller logs? Specifically, are there any errors related to receiving bad data from Kubernetes API server?

**Comment by mikejk8s** [comment]
There are not.

This is a tillerlog with one of the tiny-outputs, specifically the one in my example in OP - what's interesting is that the last item is a pod that isn't in the output;

```
2017/01/26 21:36:21 release_server.go:872: Executing post-upgrade hooks for honorary-chipmunk
2017/01/26 21:36:21 release_server.go:899: Hooks complete for post-upgrade honorary-chipmunk
2017/01/26 21:36:21 storage.go:53: Updating "honorary-chipmunk" (v1) in storage
2017/01/26 21:36:22 storage.go:45: Create release "honorary-chipmunk" (v2) in storage
2017/01/26 21:36:23 storage.go:133: Getting release history for 'honorary-chipmunk'
2017/01/26 21:36:27 client.go:110: Doing get for: 'configmap1'
2017/01/26 21:36:27 client.go:110: Doing get for: 'configmap2'
2017/01/26 21:36:27 client.go:110: Doing get for: 'serivceaccount'
2017/01/26 21:36:27 client.go:110: Doing get for: 'pod'
```

I have another upgrade that worked fine right after this, and the difference I see is this is missing;

```
2017/01/26 21:36:13 release_server.go:872: Executing pre-upgrade hooks for honorary-chipmunk
2017/01/26 21:36:13 release_server.go:899: Hooks complete for pre-upgrade honorary-chipmunk
```

**Comment by mikejk8s** [comment]
Just a quick update, I did a fresh install of this on a minikube node to take my cluster out of the equation and immediately had the same issue with the very first install.

**Comment by technosophos** [comment]
Thanks for all of the additional info. I'm adding it to the queue to be fixed.

**Comment by technosophos** [comment]
Bumping this up to 2.2.1

**Comment by technosophos** [comment]
Alright, so I've tried several ways to reproduce this issue, and I can't do it on my cluster. I think it _might_ have to do with some particular resource constraint issue on the cluster.

Looking at the code that generates the stuff above, I can see that it basically works like this:

- Tiller compiles a list of all of the manifests it needs a status for.
- Tiller sends the entire list to Kubernetes
- Tiller gets the list, and then formats it using `kubectl` (`p :=kubectl.NewHumanReadablePrinter(kubectl.PrintOptions{}` )
- The result is sent back to the Helm client, which displays exactly what it gets.

My guess is that the objects returned from the query are not complete. But I don't know how that could be so, or how to fix.

https://github.com/kubernetes/helm/blob/master/pkg/kube/client.go#L182-L196

@adamreese is it possible that the release `obj` isn't totally populated by the time we run it through the printer?

Tested on:

Helm 2.2.3
Kube 1.5.4

**Comment by technosophos** [comment]
Bumped to 2.4.0 while we try to reproduce

**Comment by technosophos** [comment]
Removed from milestone, and switching to a Helm Wanted. At this point, the suspicion is that this is a GKE issue.

**Comment by bacongobbler** [comment]
Closing this ticket as inactive. I haven't seen any activity from the OP since January. It's *very* likely that  Helm, Kubernetes **or** GKE itself has fixed this issue since then.

Please re-open if this issue is still seen against the latest version of Helm, and if so, please provide a reference implementation or a reproducible test case so we can test against this bug. Thanks! :)
