### ISSUE TITLE
Chartutil refers to non-existing dependency

### ISSUE THREAD

**Issue by alban23** [kubernetes/helm#1891]
Hi, 

apologies if I got it wrong.

In line 31 in https://github.com/kubernetes/helm/blob/master/pkg/chartutil/capabilities.go the code tries to get the version of kubernetes. 
Import: 
```
import (
	....
	"k8s.io/kubernetes/pkg/version"
)
```
Access: 
```
	// KubeVerison is the Kubernetes version
	KubeVersion *version.Info

```
However, the current version of the referenced package does not have anything with a KubeVersion object. See https://github.com/kubernetes/kubernetes/tree/master/pkg/version

Also see https://github.com/kubernetes/kubernetes/commit/52f683157601bc27e95b86ce2e68fd71a3592ffd#diff-bcee38a2cd2e5f1990f046729f3833d8

For me just uncommenting line 31 was enough, but it prop needs to be fixed in a better way.

EDIT: I just saw that you are using glide to fix the version while in my project I was just using the latest repo version, so I guess it didn't affect you. Can you generally recommend glide?
If this issue is known before migration to the next version, please close or delete it.

**Comment by technosophos** [comment]
Doing `make bootstrap` should fix that for you.

I recommend using Glide. But I'm highly biased: I also wrote Glide.

**Comment by iamzhout** [comment]
@alban23 `KubeVersion *version.Info` is [golang struct](https://golang.org/pkg/go/doc/#Example) means the `KubeVersion` is the struct member name, while `*version.Info` is for member type, so you should not lookup KubeVersion inside kubernetes code which will have no result.

**Comment by alban23** [comment]
I see. Thanks for feedback. I shall then close the issue.
