### ISSUE TITLE
Getting ImagePullBackOff status from tiller install after helm init

### ISSUE THREAD

**Issue by mcameron** [kubernetes/helm#1893]
Might be a dupe of: https://github.com/kubernetes/helm/issues/355

**Comment by mcameron** [comment]
Or: https://github.com/kubernetes/helm/issues/623.  

I'm on v2.1.3.

**Comment by bacongobbler** [comment]
Can you please provide logs as well as a more thorough explanation on what's going on? There's not a whole lot of information to go on here.

**Comment by bzub** [comment]
I see this also.

When I do a kubectl describe on the tiller pod I see:
```
Error syncing pod, skipping: failed to "StartContainer" for "tiller" with ErrImagePull: "image pull failed for gcr.io/kubernetes-helm/tiller:v2.1.3, this may be because there are no credentials on this request.  details: (Error response from daemon: {\"message\":\"target is unknown\"})"
Back-off pulling image "gcr.io/kubernetes-helm/tiller:v2.1.3"
```

Also tried this:
```
$ docker pull gcr.io/kubernetes-helm/tiller:v2.1.3
Error response from daemon: target is unknown
```

The issues @mcameron cited show similar issues where the tag/image was mistakenly set to private.

**Comment by bzub** [comment]
Oh, looks like a change in Docker is the culprit.  v1.13.1 fixes it.

This issue is probably a dupe of #1824 which is closed so it's not easily identified by new users.

**Comment by technosophos** [comment]
I'm closing this in light of the last comment. Please re-open if this continues to occur.

**Comment by mozzymoz** [comment]
I'm sorry I don't understand, why is the image not repushed, since not docker is the problem but the imag mime type?
