### ISSUE TITLE
Quick start guide references functionality in future release

### ISSUE THREAD

**Issue by ttrahan** [kubernetes/helm#1895]
The instructions in the [Quick Start guide](https://github.com/kubernetes/helm/blob/master/docs/quickstart.md#initialize-helm-and-install-tiller) provide a tip to use the `helm init --upgrade` command to automatically upgrade Tiller on the server. This flag is not available in Helm CLI yet (v2.1.3 is latest available) and appears to be slated for v2.4 per https://github.com/kubernetes/helm/issues/1782

**Comment by technosophos** [comment]
This feature is now released in 2.2.0. We need to figure out a better solution to documentation.
