### ISSUE TITLE
Locking Chart Repository Design

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#1896]
I'm opening this issue to test my sanity regarding chart repo hosting. I understand that a chart repo is a web server that serves `GET /index.yml`. `index.yml` is the complete list of all charts and their appropriate metadata and download location. The documented approach to publishing a chart is to download the complete `index.yml`, merge in additional packages, and push back to the server. `helm` can handle merges but not pushing back to the server. I understand this is a simple approach that works in simple use cases.

Here is my use case. We want to ship our applications as helm charts. Here is our (proposed process):

1. Make a PR to git repo containing the helm chart (say `foo`) code
2. CI runs on the PR
    - Push a helm chart to our repo server tagged with the feature branch. Example: `foo-VERSION.$BRANCH-$BUILD_NUMBER.`.
4. Team deploys the `foo-VERSION.$BRANCH-$BUILD_NUMBER` chart for verification
5. The PR (mentioned in step 1) receives a new commit to change the chart version.
6. Tests run again on PR 
    - producing a new `foo-VERSION.$BRANCH-$BUILD_NUMBER` chart and publishing that
7. The PR is merged to master.
8. CI runs on master
    - A new `foo-VERSION` chart is published to the repo
10. Team deploys `foo-VERSION` to the production environment

The simple model for repo hosting is problematic for us because there may be multiple CI runs happening at once. The publisher's responsibility to merge the index is the root cause. One workaround is put a sort of "concurrent limit" on the CI system to only run one build at once for a particular project. This ensures there is only one process merging the index at one point in time. This creates a new issue. Any publish action outside the CI system _may_ overwrite existing charts.

Moving the merge responsibility to the repo server is a better solution. Helm uses a simple web server model that I can leverage for this solution. My solution is allow any actor to publish single charts and have the server handle the `index.yml`. Here's a proposed workflow:

1. Do an HTTP `PUT /charts/:id-:version` with the data required to create an entry in `index.yml`. These data blobs can be stored anywhere (like a DB or a directory)
2. The client joins all persisted charts when `GET /index.yml` is requested.

This server is straight forward to implement. I'm surprised that something like this is needed so I need to question my assumptions about the repo server and how it's intended to work with helm. Here are my questions:

1. Does this make sense?
2. Why is the publisher required to merge with the existing index before publishing?
3. Is there a wider story for repo servers I'm unaware of?

Thanks :)

**Comment by tazjin** [comment]
I guess the issue here is logic-less reposervers, i.e. people who just push their repo into a GCS or S3 bucket. There wouldn't really be anything that can run the required index generation code.

**Comment by ahawkins** [comment]
> I guess the issue here is logic-less reposervers, i.e. people who just push their repo into a GCS or S3 bucket. There wouldn't really be anything that can run the required index generation code.

Correct, but then only a single user can push at a time.

**Comment by technosophos** [comment]
Our intention regarding repositories is that Helm itself would place only minimal requirements on a repository, and then provide a bare-bones implementation for developers to use. We figured that at some point we or others would build better tools outside of Helm. Notably, we figured we (or others) would build a custom repository server that would support a full lifecycle workflow (Push/Pull, for example).

I love the idea of a server-side tool that accepted charts via PUT or something, and dynamically (and safely) managed the `index.yaml` file. I think that is a MUCH better design compared to managing the index on the client.

**Comment by ahawkins** [comment]
> Notably, we figured we (or others) would build a custom repository server that would support a full lifecycle workflow (Push/Pull, for example).

This is why I opened the issue. I want to understand more of the future trajectory to see if it's worth taking on this work.

> I love the idea of a server-side tool that accepted charts via PUT or something, and dynamically (and safely) managed the index.yaml file. I think that is a MUCH better design compared to managing the index on the client.

I think we'll put something together for this then. We need this for our process. We're happy to contribute it as a separate open source project (Given are skill set is not with go).

**Comment by technosophos** [comment]
That would be fantastic! Please let us know if there's anything we can do to help, and if at some point you want to demo your work, we'd love to see it at the dev standup, and probably SIG-Apps

**Comment by ahawkins** [comment]
> That would be fantastic! Please let us know if there's anything we can do to help, and if at some point you want to demo your work, we'd love to see it at the dev standup, and probably SIG-Apps

Roger that command. I'll get the code written and you help me navigate the kubernetes ecosystem/community :bow:

**Comment by technosophos** [comment]
I'm marking this as "support" since we currently don't have a category for this type of issue.

**Comment by alonl** [comment]
@technosophos any progress so far? I'll be happy to assist. I was about doing the same thing...

**Comment by ant31** [comment]
@alonl have you took a look at the app-registry and the helm plugin ? 
Seems to solve that issue and users are using it mainly for CI/CD as described, 
```
helm registry push quay.io/ant31/my-chart 
 -> chart 1.0.1 pushed
helm registry install quay.io/ant31/my-chart@1.0.1
```

https://github.com/app-registry/appr-helm-plugin

**Comment by jdolitsky** [comment]
@ahawkins @alonl ChartMuseum provides an alternative approach to this problem, similar to the solution @technosophos described above. It does not offer some of the nice features of app-registry (channels etc.), but it works natively with the Helm CLI
https://github.com/chartmuseum/chartmuseum

**Comment by spesnova** [comment]
@jdolitsky Hi! I saw ChartMuseum yesterday and it's awesome. It looks ChartMuseum doesn't have AuthN yet. Do you have a plan to implement AuthN to it? or Is there way to enable auth for ChartMuseum now?

**Comment by jdolitsky** [comment]
@spesnova thanks! Currently no built-in authentication/authorization. Please file an issue on the repo describing your needs. One option (for now) is to put ChartMuseum behind something like Nginx that will handle this piece for you

**Comment by spesnova** [comment]
@jdolitsky 

> Please file an issue on the repo describing your needs. One option (for now) is to put ChartMuseum behind something like Nginx that will handle this piece for you

I see, thanks!

**Comment by jdolitsky** [comment]
@spesnova just following up, ChartMuseum now has support for both basic auth and TLS

**Comment by spesnova** [comment]
@jdolitsky Thank you for telling me about!

**Comment by ausov** [comment]
For large repositories, would it be easier to split repository into repo per chart (subfolders similar to maven repo)? This can practically prevent collisions since CI/CD pipelines for the same chart are usually sequential.

**Comment by ausov** [comment]
Isn't it an already implemented mechanism in Helm that would utilize ETag or Last-Modified headers for conditional HTTP PUT request? Then it would be sufficient to reload updated index and retry PUT if remote version changed. Why is additional locking needed then?

**Comment by ausov** [comment]
Just wanted to share our solution for Google Could Storage using object version and conditional PUT:

```sh
current_index=$(gsutil ls -a gs://${HELM_REPO_BUCKET}/index.yaml 2>/dev/null || true)
if [ -z "$current_index" ]; then
	echo "Creating new repository"
	helm repo index --url ${HELM_REPO_URL} ${HELM_REPO_DIR}
	gsutil -m cp ${HELM_REPO_DIR}/index.yaml gs://${HELM_REPO_BUCKET}/index.yaml
else
	current_index_version="${current_index##*#}"
	echo "Updating repository index version $current_index_version"
	gsutil cp $current_index ${HELM_REPO_DIR}/
	helm repo index --url ${HELM_REPO_URL} --merge ${HELM_REPO_DIR}/index.yaml ${HELM_REPO_DIR}
	gsutil -m -h x-goog-if-generation-match:$current_index_version cp ${HELM_REPO_DIR}/index.yaml gs://${HELM_REPO_BUCKET}/index.yaml
fi
gsutil -m rsync -x "index\.yaml$" ${HELM_REPO_DIR}/ gs://${HELM_REPO_BUCKET}/
```

**Comment by bacongobbler** [comment]
Given the workaround @ausov mentions for `helm repo index` and with [chartmuseum](http://github.com/kubernetes-helm/chartmuseum)'s introduction as an incubator project for Helm (along with other implementations like app registry), should we consider this ticket as resolved?
