### ISSUE TITLE
Proposal: move downloader and resolver package to /pkg

### ISSUE THREAD

**Issue by libesz** [kubernetes/helm#1898]
I am planning to create an alternative tiller client, which is not CLI based, but for example has REST/JSON NBI for further integration with e.g. a web front-end, which is not capable to handle gRPC directly. The client would have limited capabilities comparing to helm, like install/upgrade/fallback. As chart fetching and dependency resolution is on the client side (from tiller's perspective) I would like to reuse these as well, to stay fully compatible. Maybe there are other parts which might needed, but so far I found these.
Now these components are under the /cmd/helm directory, which is not supposed to be reused as the stuff under /pkg, according to the developer guide.
Is there a specific reason why these are not shared libraries? Could they be?

**Comment by technosophos** [comment]
The only requirement I'd place on this is that nothing in `pkg` should assume that `os.Stdout` is the correct destination to write something to. I think there are some places in those packages that may still do `fmt.Print...`.

Otherwise, I'm in favor of moving anything re-usable into `pkg`.

**Comment by libesz** [comment]
Thanks!
I did not find any direct os.Stdout or fmt.Print* usage. The majority returns the say in the form of errors. The rest (like [warnings](https://github.com/kubernetes/helm/blob/master/cmd/helm/downloader/chart_downloader.go#L108)) is printed to the Out io.Writer field of the package's main data struct, so that it is configurable.
