### ISSUE TITLE
client should support schemas for imported templates

### ISSUE THREAD

**Issue by bmelville** [kubernetes/helm#19]
GCP DM has the gcloud CLI which will, for an imported template, also look for and import its schema file and recursively pull in all imports defined within. e.g.,

imports: [foo.py]

may end up passing foo.py, foo.py.schema, and foo-helper.py to the API.

The DM client should also support this.

**Comment by jackgr** [comment]
Is this a client issue or a type resolver issue on the server side?

**Comment by bmelville** [comment]
This is already supported in the type resolver, we just need to make the type resolver available in the client for locally imported templates as well as URLs.
