### ISSUE TITLE
(feat/cmd/helm): Add support for longer table column wides using `-o wide`

### ISSUE THREAD

**Issue by lachie83** [kubernetes/helm#1915]
See #1914 

Example

Without `-o wide` - Table colum wide ~30
```
helm history jaunty-llama
REVISION	UPDATED                 	STATUS  	CHART                         
1       	Fri Feb  3 15:58:10 2017	DEPLOYED	alpine-1.0.847.192312075-16...
```
With `-o wide` - Table colum wide ~60
```
./helm history jaunty-llama
REVISION	UPDATED                 	STATUS  	CHART                              	DESCRIPTION
1       	Fri Feb  3 15:58:10 2017	DEPLOYED	alpine-1.0.847.192312075-165164_365	
```

**Comment by lachie83** [comment]
This appears to differ from kubectl behavior (`-o wide` in kubectl doesn’t change the column width
it adds more columns and prints them if they are returned) https://github.com/kubernetes/kubernetes/blob/d6f7ae2ffbdc1d5cd89181666e62cf0208830f85/pkg/kubectl/resource_printer.go#L511-L512

**Comment by bnookala** [comment]
👋  Hello! I thought to try and attempt this, since it seemed fairly simple. I got as far as doing an `ack` to see how things were currently implemented and found this:

```$ ack 'MaxColWidth'
cmd/helm/dependency.go
234:	table.MaxColWidth = 80

cmd/helm/history.go
96:	tbl.MaxColWidth = 60

cmd/helm/list.go
204:	table.MaxColWidth = 60

cmd/helm/search.go
126:	table.MaxColWidth = 50

cmd/helm/status.go
122:	tbl.MaxColWidth = 50
```
Seems like there's a few different `MaxColWidth` settings, and all appear to be beyond 30. For this ticket to be marked as closed, should this be standardized back to 60? Just wondering how to start and proceed here… :)

**Comment by made2591** [comment]
@bnookala I think that uitable.MaxColWidth property of github.com/gosuri/uitable instances should setup only once a single point (or for each specific scenario but in a single place)...

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/helm/pull/2950 introduces the --format flag to `helm list`, so it should be relatively simple issue to pick up if anyone wants to give this a shot!

**Comment by fgimenez** [comment]
I'd like to give it a try, hopefully will have a PR ready soon :)

**Comment by fgimenez** [comment]
Looks like this is already implemented in #2836 is that correct?

**Comment by mikeln** [comment]
Would really be helpful also on the output of "helm search <repo>"  when you are looking for versions of a chart in a chart repo.  The version is too short in some cases.   Similar type of thing.

**Comment by bacongobbler** [comment]
@mikeln I opened #3947 to track that feature. Feel like taking a crack at it?

**Comment by mikeln** [comment]
we'll have someone get to this
