### ISSUE TITLE
Question: recursive dependencies

### ISSUE THREAD

**Issue by fiunchinho** [kubernetes/helm#1919]
If the ChartA has a requirements.yaml file saying that it depends on ChartB, and ChartB has a requirements.yaml file saying that it depends on ChartC, should I get ChartC when installing ChartA? When testing this locally, I get ChartB but I don't get ChartC. The charts folder inside ChartA contains a ChartB gzip file.

**Comment by technosophos** [comment]
`helm dep up` is not recursive. This is mainly because the design of the package format requires that a packaged chart contains all of its dependencies, and `helm dep` was intended to be used for fetching packaged charts.

**Comment by fiunchinho** [comment]
Thank you for your reply! You mean it's like that by design, and it's not expected to work otherwise? Wouldn't be better to fetch dependencies when packaging the chart so when another chart downloads it, it gets the chart and its dependencies?

**Comment by bacongobbler** [comment]
Intentional by design. It is expected that a chart contains all of its dependencies as @technosophos mentioned.

**Comment by fiunchinho** [comment]
We could keep that design decision but change how `helm package` works. If `helm package` runs `helm dp up` before packaging, when the chart is made, the gzip package will contain the dependencies. That way, when installing the package, I'd get the dependencies too. Right?

**Comment by bacongobbler** [comment]
> Wouldn't be better to fetch dependencies when packaging the chart so when another chart downloads it, it gets the chart and its dependencies?

requirements.yaml allows fuzzy semver strings (e.g. `v0.1.x`), so if that were to be supported then subsequent calls to `helm package` could end up with differing results. It would also cause chart repositories to balloon like crazy when uploading charts (having to save the same chart for every chart that depends on it, rather than just referencing it in a requirements.yaml).
