### ISSUE TITLE
add `--cleanup` flag to `helm test` cmd

### ISSUE THREAD

**Issue by vdice** [kubernetes/helm#1920]
As an option to automatically clean up test pods after test suite completion.  See https://github.com/kubernetes/helm/pull/1777#discussion_r99491030

(Requires https://github.com/kubernetes/helm/pull/1777)

**Comment by foxish** [comment]
+1 but aside from this, it seems like we should also have a new test run clobber the old completed pod perhaps?
For example, the below result was unexpected:

```
~/g/s/k/helm (master=) ./bin/helm test quieting-coral
RUNNING: quieting-coral-service-test
ERROR: pods "quieting-coral-service-test" already exists
```

Or maybe we should have the test pods use some auto-generated name suffix? Thoughts?

**Comment by vdice** [comment]
@foxish the current plan/implementation in the linked PR (https://github.com/kubernetes/helm/pull/1935) is to enable this functionality explicitly from the user via a flag, e.g. `helm test --cleanup <release>`.  If it's decided we'd rather have cleanup be the default, it should be a simple change.

As for naming test pods with, say, a random suffix, I believe we've decided to leave that up to the test template author.  For example, something like this should work:
```
...
metadata:
  name: "{{.Release.Name}}-service-test-{{randAlphaNum 6}}"
...
```
