### ISSUE TITLE
'helm delete' and PVCs

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#1933]
So, I created a pvc of my own, as I can't use the dynamic provisioner for a particular use case.

I then enabled the pvc setting on stable/grafana and launched it:
helm install stable/grafana --name grafana --values grafana-values.yaml
Error: release grafana failed: persistentvolumeclaims "grafana-grafana" already exists

helm delete --purge  grafana then ends up deleting the pvc, even though the pvc isn't owned by the release. I think this is unexpected behavior?

**Comment by kfox1111** [comment]
So, actually repeating the procedure, the error is printed and the release enters "failed" state, but the server came up and bound to the existing pvc anyway. So, not sure if it is really a bug that "Error" really should be "Warning" and status really should be DEPLOYED, or if it should not be trying to delete the pvc on delete.

**Comment by technosophos** [comment]
During a `delete` helm operation, Tiller will send the same batch of manifests created with `install` or `upgrade` to Kubernetes API. In this case, the labels for the PVC in the chart must have matched the labels on the existing PVC.

Can you by any chance send us the labels for those two so that we can reverse engineer this a bit?

**Comment by kfox1111** [comment]
I created:
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

the chart tried:
https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/pvc.yaml

There was no lablels on the pvc I created.

Even if they did match perfectly, the user might have done that to try and get it to load and this case still would have been hit.

**Comment by technosophos** [comment]
So did the full name match `grafana-grafana`? I'm wondering if the actual delete logic in k8s just deletes based on name, not name + labels.

**Comment by kfox1111** [comment]
Yeah. the full name matched. The labels didn't so I think your right.

**Comment by technosophos** [comment]
Updated title to make it more evident what the problem is

**Comment by technosophos** [comment]
I think that what we need to decide for this is whether we are going to override Kubernetes' own deletion logic, perhaps by explicitly using label selectors.

**Comment by kfox1111** [comment]
The inconsistency to me, was helm didn't create the object, errored but continued though reported failed state, and then deleted it on removal.

I think it would be much more consistent if it did any of:
1. errored on creation. entered failed state. didn't delete the pv on deletion of the failed release.
2. warned on creation but continued. state=ok, delete doesn't delete the pv because it didn't actually create it.
3. warned on creation but continued. state=ok, helm delete, deletes the pv because it was attached successfully to something...

Though 3 still feels a little weird.

**Comment by bacongobbler** [comment]
I'm concerned that fixing this in the ways @kfox1111 proposes may introduce a breaking change. Users may have been documenting and working around this issue in production. If we introduce 1) or 2), the installation behaviour will differ from what's in master with no workaround.

Would it be possible to hide this behind a feature flag? It's not clear to me what's the right path forward for this ticket.

**Comment by kfox1111** [comment]
Or a feature flag that you can set if you want the older behavior, and a note in the changelog describing the flag for those that care?

The new behavior is about failing safe, so it should be more safe making it a new default then leaving it alone I think?

**Comment by bacongobbler** [comment]
> Or a feature flag that you can set if you want the older behavior, and a note in the changelog describing the flag for those that care?

We cannot introduce breaking changes to users unless it's for a **very** good reason (case in point: compliance issues with facebook's Go libraries introduced in Helm 2.5). We can set up a deprecation notice to eventually bring this in, but I wouldn't go full steam ahead with breaking existing users' workflows, even if it's the "right" way to fix the problem.
