### ISSUE TITLE
RFC: Helm Webinar Outline

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#1946]
This issue is an RFC on my outline for a helm webinar I'm doing. You can find more details on my [blog](http://blog.slashdeploy.com/2017/02/11/real-world-kubernetes-webinar-series/). I'd like some feedback on my outline and to make sure the maintainers (@technosophos, @adamreese, @michelleN ) have input into how their project is marketed and things they think prospective users should know/understand.

Webinar Date: First Week of March

## Abstract

_helm_ is a package manager for Kubernetes. You should use helm to deploy and upgrade Kubernetes applications. It's great for application engineers, devops teams, and operations engineers.

## Outline

* Introducing `helm`
    - What is helm; charts and the official charts repos
    - Use cases; deploying applications
*  Charts
   - How charts work
   - Releases
   - Configuring charts with values
   - The official charts repo
   - Chart repo hosting
* Demos
   - Install a chart
   - Install the same chart as multiple releases
   - Upgrade a chart

I submit this outline to you to be transparent with you, and with an open heart and mind. Thank you for all you hard work on such an important project. I hope my webinar can introduce `helm` to more people and help them in your work. Thank you lovely kops maintainers ❤️

**Comment by technosophos** [comment]
Depending on whether you're targeting chart _developers_ or just chart _users_, you might want to add a segment on the template language.

Ideas for other things you might consider covering (depending on your audience):

- Helm deployment lifecycle (install, get, status, upgrade, history, rollback, delete)
- Hooks
- The brand new `helm test` stuff
- Helm starter packs (`helm create --starter`)
- Creating Helm plugins

Overall, this is looking really cool. Please let us know how it goes.

**Comment by ahawkins** [comment]
@technosophos I think it will be a little of both. I may do `helm create` to create a simple chart the install it on a cluster. The goal is to educate people on how they can use helm to deploy _their_ applications and everyone else's. I didn't know about `helm test`. I need to look into the change log!

**Comment by technosophos** [comment]
I am going to mark this as closed now.
