### ISSUE TITLE
Proposal: add a templates function to provide a short and unique ID

### ISSUE THREAD

**Issue by kdada** [kubernetes/helm#1949]
Sometimes, we create a chart which has some dependencies. If some subcharts have same name, it will fail when we install the chart. Because we usually use the template as k8s resource name:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
```
If we have an unique ID, we can use `{{ .Release.Name }}-{{ .Chart.Name }}-ID` as  the name of k8s resource. It ensures that all resource won't conflict. 

In sprig, I find some related functions:
```
randAlphaNum: Generate a random alpha-numeric string
randAlpha: Generate a random alphabetic string
randAscii: Generate a random ASCII string, including symbols
randNumeric: Generate a random numeric string
uuidv4: Generate a UUID v4 string
```

But these functions can't provide a short ID and guarantee unique absolutely.

**Comment by technosophos** [comment]
Somewhat related to #1961 (subchart naming) and #1186 (built-in naming function)

`uuidv4` is very, very, very likely to generate a universally unique ID. So if that is all you need, you might consider just using that. As Wikipedia notes:

> for there to be a one in a billion chance of duplication, 103 trillion version 4 UUIDs must be generated.

https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by kdada** [comment]
Thanks for your reply. I'm clear that the uuid can generate unique ID ( 36 charactors ). But the ID is too long to used in resource name which is limited with 63 charactors.
I think my demand is like #1961 . Need a short unique ID for every chart. It seems that the work is going on.

**Comment by technosophos** [comment]
Oh! Okay. That makes sense. Mind if I link this to #1961, and then close this one out as a duplicate?

**Comment by kdada** [comment]
@technosophos 

ok
