### ISSUE TITLE
Proposal: Add release validation

### ISSUE THREAD

**Issue by thomastaylor312** [kubernetes/helm#1952]
This is an offshoot of the work started in #1163. 

With the testing framework recently added, there is now a way to test whether a chart is working once it is deployed. However, for future evolution, there may be a need for two types of "tests"

**Tests**
These would test things that a specific user might not care about, but are important to make sure the Chart will work in every way it is intended too. So if I have a nginx server that I want to work with 10 different configurations, I would want to deploy the Chart 10 times and validate it is working each time before cleaning up the deployed chart. This would specifically be for Chart developers and not for all users. This functionality would be under `helm test` when implemented.

**Validation**
These would take care of making sure things are up and running as currently implemented with `helm test`. Instead of a separate command, this would be more along the lines of a flag called `--validate` on an `upgrade`, `rollback`, or `install`. If I request validation and it fails, I would want the release to be marked as failed. This validation logic would also be used with `helm test` to validate that all configurations of the chart work as intended

**Comment by thomastaylor312** [comment]
@michelleN Your feedback, when you have some time, would be very useful here

**Comment by technosophos** [comment]
I'm changing the title from "deployment" to "release" so people don't think this is about Deployment objects.

**Comment by thomastaylor312** [comment]
Good point @technosophos

**Comment by jschrantz** [comment]
Is the expectation that helm test would be getting a major overhaul/scope change or is @thomastaylor312's use case of "I would want to deploy the Chart 10 times and validate it is working each time before cleaning up the deployed chart" not a valid representation of what helm test would be used for?

My understanding is that helm test is working at the release level, essentially doing a validation of a single release to whatever detail you'd like. I suppose --validate could be used to call a subset of the release test's checks, but without a major change both test and test --validate would be operating at the scope of a single release.

If there isn't a plan to change the scope of helm test then you'll still need an actual test suite for the chart. Something that would deploy the chart n times with different parameters, update the deployments, roll them back, delete them, etc.

On my team, we're planning on using an external test suite for the chart operations with helm test to validate that the individual operations were successful. If there is a plan to change the scope of helm test to handle the test suite runner natively it would be useful to integrate with that. If that's the plan, I'd recommend going with a different command for the chart level tests (assuming you don't want to break backwards compatibility of test). You currently have create, lint, package, etc as chart operations and install, upgrade, rollback, delete, etc as release operations. Having a test command that deals with either depending on the flag would be a bit confusing IMO.

**Comment by thomastaylor312** [comment]
@jschrantz This is something that isn't yet handled by `helm test`, but we haven't had too many discussions about this recently. @michelleN do you have any current plans for `helm test` (relating to this proposal or otherwise)?

**Comment by michelleN** [comment]
@thomastaylor312 I don't have any current plans for `helm test`. Originally, I thought we would do this version as an MVP and do a major overhaul. There have been a few feature requests here and there but I don't have the bandwidth to work on those or a major overhaul at the moment. 
I'd be interested in having a discussion at SIG Apps about `helm test` to see if we want to do a proposal for a major design change. Maybe this is something we could also discuss at Helm Summit if there is still interest?

**Comment by thomastaylor312** [comment]
@michelleN Helm Summit sounds like a good venue for a discussion on this
