### ISSUE TITLE
Adding `--force` to `helm upgrade`

### ISSUE THREAD

**Issue by peay** [kubernetes/helm#1958]
`helm upgrade` seems to use `patch`. For some use cases, applying patches can fail (e.g., for services, because `clusterIp` is immutable).  Maybe there's a better solution, but at the moment I have to delete and re-install the full release.

`kubectl apply` has a `--force` option which allows to give up on trying to patch if it fails, destroy and re-create the resource. This would be great if `helm upgrade` could have a flag like this too. 

This may also require a `--grace-period` parameter as in `kubectl apply`. Seems like https://github.com/kubernetes/helm/blob/master/pkg/kube/client.go#L244 could be modified to do a bit more like https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go#L594. I am not sure if multiple retries like in apply are necessary. Maybe trying once would be enough.

**Comment by peay** [comment]
I am considering contributing a PR if we can agree on a design for this.

**Comment by sstarcher** [comment]
Support for this would improve the UX around chart development.  Currently if I don't want to `helm delete` the install I have no way to update the chart unless I change the Chart.yaml version number every-time.  This feature would also allow people to change the chart in-place if the only change was a values.yaml change via `--set`

**Comment by thomastaylor312** [comment]
I am all for this feature as well. It is definitely useful for chart developers and CI/CD, and has some applications in production as well (like when you need to force an update of a stateful set)

**Comment by thomastaylor312** [comment]
@peay Are you still interested in making a PR for this? I think it would be helpful to see the idea implemented and then work through any changes we need to make

**Comment by peay** [comment]
Yes, I'll send a PR, I'll ping you there.
