### ISSUE TITLE
Running tiller in namespace other than kube-system

### ISSUE THREAD

**Issue by naphthalene** [kubernetes/helm#1959]
The kubernetes cluster we are using has special authorization built in that restricts access to the kubernetes API to another namespace. I was able to manually deploy tiller by generating a manifest and changing the namespace, but now when I run helm commands it says it cannot find tiller. Is there a way to configure the namespace when doing helm init?

**Comment by technosophos** [comment]
In Helm 2.2.0, see the `--tiller-namespace` flag and `$TILLER_NAMESPACE` environment variable.

**Comment by naphthalene** [comment]
:100: thanks!
