### ISSUE TITLE
helm version should have a shorter timeout

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#1972]
If you try and run `helm version` with no available server it can take almost 30 seconds for the command to return. It seems like it would be a better user experience if the timeout was something much shorter like 5 seconds.

**Comment by jchauncey** [comment]
```
╰─○time ./helm version
Client: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}
Error: cannot connect to Tiller
./helm version  0.07s user 0.02s system 0% cpu 30.073 total
```

**Comment by theishshah** [comment]
would like to help out on this, any tips on where to get started/
