### ISSUE TITLE
helm test returns an exit code of non-zero when there's no tests in the release to run.

### ISSUE THREAD

**Issue by AmandaCameron** [kubernetes/helm#1973]
This seems counter-intuitive for a CI standpoint, as it means that any charts that are tested which don't have any tests will instantly fail the build. While it oculd be argued this is desirable, I'd prefer at least a flag of some kind to indicate that this is not, for instance, if there's no way to test that a deployment succeeded, it'd be nice to have CI still be possible.

**Comment by michelleN** [comment]
@AmandaCameron Great point. Do you think that `helm test` should just exit cleanly if no tests were defined with a message indicating that instead?

**Comment by AmandaCameron** [comment]
Yes that would be acceptable, or at least a well-defined (different) exit code that a CI system could be poked into ignoring if wanted.
