### ISSUE TITLE
Pass Array values through --set

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/helm#1987]
Please add the ability to pass Array values through `--set`.

For example, the stable/aws-cluster-autoscaler Chart must receive the following:

```
autoscalingGroups:
  - name: my-asg-name
    maxSize: 50
    minSize: 2
```

If this is already possible, please do tell.. And update the docs to show how.

**Comment by technosophos** [comment]
Array values can be specified using curly braces: `--set foo={a,b,c}`. This will translate to the YAML:

```yaml
foo:
  - a
  - b
  - c
```

Maps have to be passed like this: `something.key=value,something.key2=value2`, which will translate to the YAML:

```
something:
  key: value
  key2: value2
```

The full documentation for `--set` is buried in this document: https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set

**Comment by pluttrell** [comment]
@technosophos Many thanks for responding.

After reading the referenced doc, I still don't see how to reference the following via `--set`:

```
autoscalingGroups:
  - name: my-asg-name
    maxSize: 50
    minSize: 2
```

Is  there a way to do this?

**Comment by technosophos** [comment]
I believe that the most straightforward way to do that would be to alter the structure of values.yaml into something like this:

```
autoscalingGroups:
  "my-asg-name":
    maxSize: 50
    minSize: 2
  "my-other-asg":
    maxSize: 50
    minSize: 2
```

That strategy will simply make it easier to reference them from `--set`, while also being pretty easy to work with in templates.

As you probably noticed from the documentation, there is no way in the current `--set` syntax to access an array value by index. So working with arrays is sort of a pain.

**Comment by JeanMertz** [comment]
> So working with arrays is sort of a pain.

I'm looking for ways to set an array using `set`, but it's unclear to me what the above statement means? _Is_ it possible to set an array with `set`, or isn't it? If it's _sort of a pain_, then I don't mind, but I'd like to find out how to do it.

I know I can convert the array to a map, but that's not really what I'm looking for, as the user experience (for an internal company-wide chart) degrades to work around a technical issue.

I'm not saying this _should_ be possible, but if it's not, we should probably mention this clearly in the documentation. (and if it already is, then I'm sorry, I must have missed it)

**Comment by bacongobbler** [comment]
[From the documentation](https://github.com/kubernetes/helm/blob/7cbed3f77bd771dfb46c63733c497e8c05225422/docs/using_helm.md):

> Lists can be expressed by enclosing values in { and }. For example, --set name={a, b, c} translates to:

```
name:
  - a
  - b
  - c
```

**Comment by cabrinoob** [comment]
@pluttrell : Maybe 

--set autoscalingGroups[0].name=my-asg-name --set autoscalingGroups[0].maxSize=50 --set autoscalingGroups[0].minSize=2

**Comment by yanhongwang** [comment]
Hello all,

Do you know how about this structure of Kubernetes kind '**affinity**'.

###################################################
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - mongodb-replicaset
      topologyKey: kubernetes.io/hostname
##################################################

Should I write in 
--set=affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector.matchExpressions.key=app,\
affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector.matchExpressions.operator=In,\
affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector.matchExpressions.values=mongodb-replicaset,\
affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution.topologyKey=kubernetes.io/hostname

Or some other correct syntax?
Thanks very much.

Hong

**Comment by cabrinoob** [comment]
I think that when you have to apply complexe modifications like these, you'd bettre have to put them in a file intead of using --set.

**Comment by yanhongwang** [comment]
Hello @cabrinoob 

Thanks for your recommendation.

That's true that I used --values=values.yaml to adapt appropriated value.
So there is no syntax to express **affinity** syntax by --set, right?

Thanks very much.

Hong

**Comment by cabrinoob** [comment]
You do not have to have the same structure in your `values.yaml` file than in your `deployment.yaml` resource.

You can have a relatively "flat" structure in values.yaml that makes usage of `--set` more simple.

**Comment by yanhongwang** [comment]
Hello @cabrinoob 

Thanks for your comments.

But, I saw the most of charts application in https://github.com/kubernetes/charts/tree/master/stable

For example:
#############################################
values.yaml
affinity: {}

deployment.yaml
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
############################################

Is that mean that **deployment file** needed to be **patched** when desired?
Thanks.

BR
Hong

**Comment by cabrinoob** [comment]
Yes, that means the whole bloc named "affinity" will be taken like this
(toYaml / indent 8) and injected in the deployment.yaml.

But, I think that if the affinity bloc is "complex" you'd better have to
override it through a file instead of using --set because in that case
--set parameter can be very tricky.

Le 27 juin 2018 13:59, "Hong" <notifications@github.com> a écrit :

Hello @cabrinoob <https://github.com/cabrinoob>

Thanks for your comments.

But, I saw the most of charts application in
https://github.com/kubernetes/charts/tree/master/stable

For example:
#############################################
values.yaml
affinity: {}

deployment.yaml
{{- with .Values.affinity }}
affinity:
{{ toYaml . | indent 8 }}
{{- end }}
############################################

Is that mean that *deployment file* needed to be *patched* when desired?
Thanks.

BR

Hong

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/helm/issues/1987#issuecomment-400646663>,
or mute
the thread

**Comment by intellix** [comment]
Been gruelling over this all morning after trying to use the gcloud proxy: https://github.com/helm/charts/tree/master/stable/gcloud-sqlproxy

The first example that it gives is: `[{instance: instance, project: project, region: region, port: 5432}]` which is basically JSON. After lots of failed attempts and eventually figuring I need to escape the commas, I found that it's actually not the correct syntax after stumbling upon this issue.

They do this by hardcoding a single instance like so:
```
--set cloudsql.instances[0].instance=INSTANCE \
--set cloudsql.instances[0].project=PROJECT \
--set cloudsql.instances[0].region=REGION \
--set cloudsql.instances[0].port=5432
```

I'm coming from Gitlab where you have a `.gitlab-ci.yml` containing a large `helm upgrade` command with lots of `--set` coming from environment variables. I was hoping to provide the whole instance array there but it looks like I'll have to hardcode it to a single instance using 4x ENV vars. Now I'm wondering why gcloud-proxy even bothered to make it an array cause it's impossible to provide dynamically

**Comment by jugatsu** [comment]
If someone googles how to pass `imagePullSecrets` via `--set` flag, here is the command:

For example, helm template with `imagePullSecrets` like this one:

```yaml
spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
```

command:
```bash
--set 'imagePullSecrets[0].name=regcred'
```

**Comment by pkaramol** [comment]
According to this suggestion, I should be able to run the following:

```
helm upgrade --force --tls --install --set master.installPlugins={'kubernetes:1.21.2', 'workflow-job:2.36'} --set master.tag=lts --set agent.tag=3.27-1 -f /org_files/tmp/kerkyra-jenkins/jenkins-values.yaml --namespace jenkins jenkins-kerkyra stable/jenkins
```

However this fails:

> Error: This command needs 2 arguments: release name, chart path

Any suggestions?

**Comment by HartS** [comment]
@pkaramol I hop eyou already figured this out, but since the `master.installPlugin` value you're passing isn't quoted, it treats your argument to `--set` as `master.installPlugins={kubernetes:1.21.2,` , and then attempts to parse `workflow-job:2.36'}` as your next argument. You need to remove the space between list items as that space would be treated literally if the curly braces were properly quoted, but if you remove the space and are using a shell which would attempt to expand `{1,2,3}` (such as bash), you will also need to quote the outside of the curly braces (which also means you want to remove the single quotes from your array element values, unless the values should be strings which include literal quotes)

**Comment by davidwindell** [comment]
@intellix re Gitlab, I also stumbled across the need to pass an arbitrary number of environment variables to our helm chart whilst using set. I ended up with this hacky CSV to array solution but I'd be interested if you or anyone else had a better suggestion:

`--set app.extraEnv="ENVVAR1=foo\,ENVVAR2=bar\,ENVVAR3=bat"`

```yaml
env:
{{- range (split "," .Values.app.extraEnv) }}
  - name: {{ (split "=" .)._0 }}
    value: {{ (split "=" .)._1 | quote }}
{{- end }}
```

**Comment by willzhang** [comment]
## 变量

values.yaml示例

```
master:
    initContainerEnv:
      - name: http_proxy
        value: "http://192.168.64.1:3128"
```

变量配置方式

```
helm install jenkins-blueocean \
  --set master.initContainerEnv[0].name="JENKINS_UC" \
  --set master.initContainerEnv[0].value="https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json/" \
  --set master.initContainerEnv[1].name="JENKINS_UC_DOWNLOAD" \
  --set master.initContainerEnv[1].value="https://mirrors.tuna.tsinghua.edu.cn/jenkins/" \
  stable/jenkins
```

**Comment by gargabhay1999** [comment]
> values.yaml示例
> 
> ```
> master:
>     initContainerEnv:
>       - name: http_proxy
>         value: "http://192.168.64.1:3128"
> ```
> 
> 变量配置方式
> 
> ```
> helm install jenkins-blueocean \
>   --set master.initContainerEnv[0].name="JENKINS_UC" \
>   --set master.initContainerEnv[0].value="https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json/" \
>   --set master.initContainerEnv[1].name="JENKINS_UC_DOWNLOAD" \
>   --set master.initContainerEnv[1].value="https://mirrors.tuna.tsinghua.edu.cn/jenkins/" \
>   stable/jenkins
> ```

Thanks @willzhang . Your solution made by day <3

**Comment by hari4147** [comment]
set using an array list destroy the values yaml structure
1. I have powershell script to set a collection of values to a single key in values.yaml
![image](https://user-images.githubusercontent.com/37335234/186882578-5430f649-12f2-4ebf-89b1-781bb1ae585f.png)

But when I execute the The script result like this.
![image](https://user-images.githubusercontent.com/37335234/186883013-394aa88b-45ca-400c-a73b-bb241e8308bc.png)
Actually I want the values like this, But i got this structure only use the set flag like this **helm upgrade testing testconfig --set "KeyvautCollection={may0,may1}"**
![image](https://user-images.githubusercontent.com/37335234/186883468-362c4884-3ea8-483b-aeca-84197799ef19.png)
 **I want to pass a dynamic array along with --set flag**

**Comment by madrisan** [comment]
@hari4147 stackoverflow.com is a way better site for this type of questions.

**Comment by hari4147** [comment]
sorry for the inconvenience.

**Comment by nyurik** [comment]
In case when a value could be either a single string, or multiple strings, using `toStrings` in a template makes it much easier to override.  In the following setup, it is possible to use `--set foo.mylist=bar` to override `a,b,c` list with a single value `bar`, while still treating it as a list.

### `values.yaml`

```yaml
foo:
  mylist: ["a", "b", "c"]
```

### `templates/foo.yaml`

```helm
{{- range $val := .Values.foo.mylist | toStrings }}
  {{- $val }}
{{- end }}
```
