### ISSUE TITLE
Install/upgrade a chart with SemVer including metadata `0.1.0-beta.1+metadata'

### ISSUE THREAD

**Issue by terlar** [kubernetes/helm#2001]
It seems this version is not compatible with the regex specified for labels that gets applied based on the version. So I get a bunch of:

```
is invalid: [metadata.labels: Invalid value: "chart-0.1.0-beta.1+metadata": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345')
```

The only workaround I have been able to do so far is by omitting the metadata. It is clearly due to the `+` not being allowed inside the regex validating labels. So either the labels applied would need to omit the `+` or include it in the regex, not sure what the limitations are there.

**Comment by technosophos** [comment]
The root of this is that Kubernetes disallows `+` in a label value. One option is to do something like this in your template: `{{ .Chart.Version | replace "+" "_" }}`.

**Comment by ahawkins** [comment]
@technosophos you can close this issue.  2e0f949d4 fixes the issue. Our template was generated before this commit.

**Comment by technosophos** [comment]
Cool. Thanks.
