### ISSUE TITLE
`helm install --wait` Error transport is closing

### ISSUE THREAD

**Issue by naphthalene** [kubernetes/helm#2003]
Hello,

I've created a helm chart that contains a post-install hook. In the event the hook fails, the helm install command times out and errors out with the following error:

```
E0221 14:35:37.318948    8601 portforward.go:175] lost connection to pod
Error: transport is closing
```

I suspect this happens because if the job/hook fails, it spins up a new pod to retry the job, killing the old one.

I am running helm v2.2.0. Please let me know if more details are needed.

**Comment by technosophos** [comment]
Yeah, that is probably a timeout (assuming Tiller didn't crash). You can use the `--timeout` flag to give it more time if you think the main issue is time-related. You can also use `kubectl` to (a) tail the Tiller log, or (b) check on the actual resource you are trying to deploy.

**Comment by naphthalene** [comment]
I think you're right, its not really a helm issue. Thanks for the tips. (Tiller definitely doesn't crash).

As a followup though, once the release times out, I have an issue where I can't reuse the name of the release or delete it:

```
$ helm install ./restapp --wait -n restapp-hooks
Error: a release named "restapp-hooks" already exists
$ helm delete restapp-hooks
Error: the release named "restapp-hooks" is already deleted
```

**Comment by technosophos** [comment]
Do `helm delete --force ...`

**Comment by kotamahesh** [comment]
what is the solution or conclusion?
