### ISSUE TITLE
--wait does not work as expected with helm version 2.2.0 install/upgrade/rollback

### ISSUE THREAD

**Issue by payal-hshah** [kubernetes/helm#2006]
It is expected for `helm install/upgrade/rollback` to wait before coming back  to make sure all the pods are up and running for a given release.. But, seems like it does not wait and comes back right away .. Logging an issue after conversation with @technosophos

**Comment by thomastaylor312** [comment]
I am going to take a look at this. @payal-hshah was this with every chart you installed or was it only with a specific one?

**Comment by thomastaylor312** [comment]
And just to be thorough, are you running tiller at version 2.2.0? And what version of kubernetes are you using?

**Comment by payal-hshah** [comment]
@thomastaylor312 I have tried it with one chart as of now and also I have tried running both `helm install` and `helm upgrade` .. Seeing the same behavior .. Also, my tiller is upgraded to use `v2.2.0`

`helm version
Client: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}`

Note: I have 5 containers running inside the pod

Let me know if you need more detail..

**Comment by thomastaylor312** [comment]
Looks like this is related to when we added support for TPRs in Helm. We build every `resource.Info` type as Unstructured, which breaks type casting used in the `--wait` flag and with `--recreate-pods`. /cc @adamreese

**Comment by technosophos** [comment]
On the community meeting today, it was requested that I drop this on the 2.2.1 release.

**Comment by skevy** [comment]
This issue seems to still be happening on 2.2.1.

```bash
❯ helm version
Client: &version.Version{SemVer:"v2.2.1", GitCommit:"db531fd75fb2a1fb0841a98d9e55c58c21f70f4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.1", GitCommit:"db531fd75fb2a1fb0841a98d9e55c58c21f70f4c", GitTreeState:"clean"}
```

When I run `helm upgrade`, it exits immediately with output saying "Available" == 0.

```bash
❯ helm upgrade docs-staging [path to chart] --install -f [my values.yml] --namespace [my namespace] --wait --timeout 600
....
==> extensions/v1beta1/Deployment
NAME          DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
docs-staging  1        1        1           0          3s
....
```

Any ideas? Am I doing something wrong?

**Comment by thomastaylor312** [comment]
@skevy I have been using it multiple times now without a problem, so I am not quite sure what is happening. Your pods all have readiness probes, correct?

**Comment by lightsaway** [comment]
It seems that issue is back again with:
```
Client: &version.Version{SemVer:"v2.3.0", GitCommit:"2342275b61e0539d259590975cfb78f23afcc1e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.3.0", GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:"clean"}
```

**Comment by thomastaylor312** [comment]
@lightsaway Just checking, the pods have a readiness probe, right?

**Comment by lightsaway** [comment]
yep, readyness is there
