### ISSUE TITLE
can't delete the release name from the kubernetes

### ISSUE THREAD

**Issue by sunnybi** [kubernetes/helm#2014]
After I use helm install a ETCD cluster, I want to delete it and reuse the same name to install again, but failed. It complains the release name already exits. But if I delete the release name, it complains the release name is already deleted. Below is my procedure.

1) I create a ETCD cluster using helm chart.

[root@foss-ssc-8 subi]# helm install ./etcdcluster.v0 --name etcd-cluster
NAME:   etcd-cluster
LAST DEPLOYED: Thu Feb 23 17:54:40 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> extensions/v1beta1/Deployment
NAME               DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
etcd-cluster-oam1  1        1        1           0          0s
etcd-cluster-oam2  1        1        1           0          0s
etcd-cluster-oam3  1        1        1           0          0s

2) I delete it, but there is no feedback if it success or failure. Actually, all ETCD pod are deleted when I use kubectl get pods command to check.

[root@foss-ssc-8 subi]# helm delete etcd-cluster
[root@foss-ssc-8 subi]# ls

3)I recreate the ETCD cluster using the same release name, it complains the release name already exists

[root@foss-ssc-8 subi]# helm install ./etcdcluster.v0 --name etcd-cluster
Error: a release named "etcd-cluster" already exists
[root@foss-ssc-8 subi]# helm

4) I delete the release name again because it complains the name exists in step 3

[root@foss-ssc-8 subi]# helm delete etcd-cluster
Error: the release named "etcd-cluster" is already deleted
[root@foss-ssc-8 subi]# helm install ./etcdcluster.v0 --name etcd-cluster
Error: a release named "etcd-cluster" already exists

**Comment by Ladicle** [comment]
I think that ConfigMap is left.
Please check with `kubectl get cm -n kube-system|grep etcd`.

ConfigMap of the release will remain so that the history can be referenced.
You need the `--purge` option If you want to delete it completely.

**Comment by technosophos** [comment]
You can also use the `helm install --replace` flag after a regular `helm delete`. That will have the effect of appending the new release versions to the existing history for that version.

**Comment by sunnybi** [comment]
Thank you @Ladicle and @technosophos. It works now after I use --purge option.

**Comment by technosophos** [comment]
Okay. I'm going to close this for now. Feel free to re-open if you find another issue.

**Comment by devipriyap** [comment]
hi

I am trying to install nginx-ingress but getting this following error
Error: uninstall: Release not loaded: ingress: release: not found

**Comment by marckhouzam** [comment]
@devipriyap  could you open a new issue for this and provide more details about the problem you face? Helm version, commands you ran, etc. Thanks!

**Comment by devipriyap** [comment]
How to configure multiple nginx ingress controllers in a single eks cluster?
