### ISSUE TITLE
helm dep up pull

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#2019]
'helm dep up' does an automatic 'helm update'. This is desirable in the general case, but if you are building a large number of packages, doing dep up for each package cause the repo's to be refreshed over and over greatly slowing down the process. There needs to be a flag that disables the repo refresh, or a way to only do it if the cache is older then some amount of time.

**Comment by technosophos** [comment]
How about if we do a `helm dep up --skip-refresh` option?

**Comment by kfox1111** [comment]
perfect. :)
