### ISSUE TITLE
local path repo verbose

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#2020]
The new local path code is working well, but it prints out a lot of lines like:
Archiving xxx from repo file://../../microservice/xxx
and
Repository from local path: file://../../microservice/xxx

This information is nice but not needed most of the time and sometimes obscures more important info. Can we hide them under the --debug flag?

**Comment by technosophos** [comment]
Would that be pretty easy to do @qwangrepos ?

**Comment by qwangrepos** [comment]
@technosophos I just checked the dependency commands and the debug flag is not currently implemented in the command structure. It is okay to modify the structure for "--debug"?
