### ISSUE TITLE
Helm Installs of Spinnaker Periodically Fail with PersistentVolumeClaim Issues

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/helm#2026]
I'm attempting to install Spinnaker via Helm and they fail a high percentage of the time with the following issues:

Minio Deployment:
```
[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "sullen-seahorse-minio", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "sullen-seahorse-minio", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "sullen-seahorse-minio", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "sullen-seahorse-minio", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "sullen-seahorse-minio", which is unexpected.]
```

Redis Deployment:
```
pod (sullen-seahorse-redis-1955876852-4xn7z) failed to fit in any node fit failure summary on nodes : NoVolumeZoneConflict (4), PodToleratesNodeTaints (3)
```

When this happens they never appear to recover, so I delete the release with Helm if it shows up, or delete all resources manually if it does not. 

Sometimes trying it again will just work.

**Comment by technosophos** [comment]
This error is bubbling up from Kubernetes' PVC system. @lachie83 do you have any experience on these errors? I don't know what they mean.

**Comment by lachie83** [comment]
By default the minio chart uses persistence which needs to backed by a PV that matches the requirements or use a dynamic provisioner. Have you manually created a PV or are you expecting to use the dynamic provisioner? @pluttrell

**Comment by pluttrell** [comment]
I wasn't sure what to expect. Early on in my attempts to deploy this chart I created a bunch of PVs manually evenly spread across the AZs but then noticed they weren't being used. Instead of smaller ones were getting auto created and used. I was unable to find clear Kubernetes documentation on what to expect, nor why the PVs I created weren't being used...but since it appears to auto create them, I've since stopped manually creating them.

**Comment by pluttrell** [comment]
When I try the Spinnaker chart, I get various errors such as the two described in this original issue.

The `NoVolumeZoneConflict` errors, such as the one example above for Redis pod, I believe can be traced back to the PVs being created in one AZ and the scheduler attempting to attach it to an EC2 instance in a different AZ, which isn't allowed. On this deep dive, it feels like something core is wrong with Kubernetes, perhaps in the schedule for this to ever happen. Since I've built my k8s cluster using Kops, I was pointed to a manual workaround that has worked thus far. It's documented in this [kops issue](https://github.com/kubernetes/kops/issues/1998).

With regards to the more generic error in the Minio deployment, I wonder if AWS is taking longer than some timeout to bind the PV and thus fulfill the PVC...though I have no idea where such a timeout might be. Further adding to the inconsistency of these issues is that sometimes I'll see failures like this one that will go away after some time..in the many minutes timeframe. Other times I'll wait hours and it'll still be listed as failed before I delete the chart if helm lets me, or all of the artifacts manually.

**Comment by technosophos** [comment]
This looks like it might be a Kubernetes Chart repo issue... should we move this issue to that queue?

**Comment by pluttrell** [comment]
Works for me.

**Comment by psyhomb** [comment]
Anything new on this?

**Comment by bacongobbler** [comment]
closing. Tickets related to the spinnaker chart should be followed up at https://github.com/kubernetes/charts.
