### ISSUE TITLE
Error: file "helm install stable/nginx-ingress" not found (and mysql doesn't work either)

### ISSUE THREAD

**Issue by colemickens** [kubernetes/helm#2030]
So, I'm following the Quick Start Guide: https://github.com/kubernetes/helm

Neither `stable/nginx-ingress` nor `stable/mysql` work.

```shell
$ helm repo update

Hang tight while we grab the latest from your chart repositories...
...Skip local chart repositoryh...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "deis" chart repository
Update Complete. ⎈ Happy Helming!⎈

# ignoring that the output looks bad... there's at least one newline missing...

$ helm install stable/nginx-ingress
Error: file "stable/nginx-ingress" not found

$ helm install stable/mysql
Error: release muddled-aardvark failed: Deployment.extensions "muddled-aardvark-mysql" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
```

Version info:

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}
```

**Comment by colemickens** [comment]
Hm, looks like deleting `~/.helm` and starting over helped. (And removed the `deis` source , which is fine and makes sense)..

Closing for now, I guess y'all know if it's expected that users would need to take this remediation action.

**Comment by bacongobbler** [comment]
~~can you check `helm search` and confirm if there's a stable/mysql package?~~

Yep, that'd do the trick. :)

**Comment by ritazh** [comment]
Getting the same error. 

> And removed the deis source

@colemickens what specific things did you have to remove

**Comment by johnlabarge** [comment]
I have the same error.

**Comment by bacongobbler** [comment]
can you all try upgrading to v2.2.3 and see if that fixes things? Someone else on slack had a similar issue that went away with v2.2.3.

**Comment by johnlabarge** [comment]
That worked.

**Comment by bacongobbler** [comment]
@ritazh in case you still need help, @colemickens used `rm -rf ~/.helm && helm init --client-only` to remove the `deis` repository. Alternatively you can also use `helm repo rm deis`.

**Comment by ReSearchITEng** [comment]
I have just tried with v2.3.1, and there are still issues.
after install (first helm init), the index was only 82k
-rw-r--r--. 1 root root 82145 Jan 20 18:14 stable-index.yaml
after `rm -rf ~/.helm && helm init --client-only`,  it was fixed, and became much bigger: ~250k.
probably `helm repo update` would have done the same.
Note: I don't have any deis repo.

**Comment by adamtwiss** [comment]
I had this issue after installing (2.4.1 on MacOS) and it was because HELM_HOME wasn't set.
After doing: 
```
export HELM_HOME=$HOME/.helm
```
It worked fine.

**Comment by dshamanthreddy** [comment]
I still have same issue, plz help @bacongobbler 
<img width="716" alt="screen shot 2018-03-28 at 11 27 21 pm" src="https://user-images.githubusercontent.com/18470551/38068534-b5049956-32df-11e8-90cc-5ed89094552b.png">

**Comment by jorgemorando** [comment]
Having the same issue, none of the above solutions proposed worked, any ideas anyone?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
can you two determine if you can connect to the kubernetes API through

```
kubectl -n kube-system port-forward <my-tiller-pod> 44134:44134
```

and in another terminal:

```
HELM_HOST=:44134 helm install stable/mysql
```

?

**Comment by bighnaraj** [comment]
Still shows error:
Fetched stable/mysql to mysql-0.6.0.tgz
Error: release dapper-flee failed: error validating "": error validating data: found invalid field initContainers for v1.PodSpec

**Comment by bacongobbler** [comment]
@bighnaraj you might be using an older version of kubernetes that doesn't support init containers.

**Comment by unfor19** [comment]
On Ubuntu 19.10, I removed the cache:
`rm -r ~/snap/code/common/.cache/helm`
Then followed the instructions: https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/
