### ISSUE TITLE
Helm lint Does Not Support Same Arguments as Install/Upgrade

### ISSUE THREAD

**Issue by mikeln** [kubernetes/helm#2036]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): lint, --set, --namespace, --value

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Helm version** (use helm version): 
Client: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.0", GitCommit:"fc315ab59850ddd1b9b4959c89ef008fef5cdf89", GitTreeState:"clean"}

**Description**:
`helm lint` should support the same set of (applicable) arguments as `helm install` and `helm upgrade`.   

`helm lint` does not support the following arguments:
- `--namespace`
- `--set`
- `--values`

However `helm lint` does support `--tiller-namespace` now (thank you!), but this argument should be the same name, i.e. `--namespace`.

**Reasons**:
`helm lint` is useful in chart development, and also in CI pipelines.  However, it is very desirable to run the `helm lint` validation with the exact same parameters as `helm install/upgrade` will be run on a system.  

There are circumstances where a default `values.yaml` file may not be complete by design.   Where it is better to require the define values on the command line via `--set`.   (I will not provide some of the cases here, as it may sidetrack the spirit of this issue).

Also, it is generally better to run the new chart automated integration/testing with the same arguments as are used in the actual install/upgrade.   This guarantees that a single version of a Chart is all that is needed, vs a different default `values.yaml` setup specifically for `helm lint`.

**Comment by technosophos** [comment]
This makes sense to me. it would definitely make lint a better tool for finding problems introduced by parameters even when the base chart seems to work fine. It would also make it easier to do better testing of various combinations for parameters.

**Comment by migmartri** [comment]
This seems a great addition to the linter.

@technosophos, to your question. Either @prydonius or I will work on this issue next week.

**Comment by xmik** [comment]
@technosophos I think you wanted to close #2035 instead of this one :)

**Comment by mikeln** [comment]
Yes, this one is still open.  You should have closed #2035 as stated in the above comment.

**Comment by bbeaudreault** [comment]
Hey guys, curious if there is any update here. We have the usecase the OP describes, where the lint fails on our chart which has required fields which must be set on the command line. This makes lint unfortunately useless for us.

I see there was some initial interest in fixing this short term, but it seems to have fallen by the wayside.

**Comment by vglafirov** [comment]
This is huge gap in our CI/CD pipeline, please prioritise it.

**Comment by rbuck** [comment]
Ditto here too, this gap makes the tool pretty much useless for us.

**Comment by sudermanjr** [comment]
+1 for this feature.  Would be very helpful for CI/CD pipelines

**Comment by shanecorcoran** [comment]
+1 For this

**Comment by bacongobbler** [comment]
@jmastr I noticed you have a fork of helm with some commits that add --namespace, --set and --values to `helm lint`. Is this in a workable state to be PR'd upstream or do we have permission to use your code?

**Comment by jmastr** [comment]
@bacongobbler The PR is here: #2972

**Comment by bacongobbler** [comment]
Ooh thanks! I forgot about that PR; I'm just triaging issues at the moment but I'll be happy to take a look at it in a second.

**Comment by jmastr** [comment]
@bacongobbler np, #2495 might be a duplicate.

**Comment by bacongobbler** [comment]
thanks for pointing that out! :)

**Comment by Stelminator** [comment]
+1 looking forward to this for our CI/CD.

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/helm/pull/2972 was merged, therefore this is now available in the canary builds. Thanks @jmastr for the PR!
