### ISSUE TITLE
helm --wait option crash tiller server when deploying same chart.

### ISSUE THREAD

**Issue by gerardo8a** [kubernetes/helm#2043]
After upgrading helm/tiller to latest version 2.2.1 , tiller started to crash whenever an existing deployment with the same chart gets deployed using the --wait option.

$ helm version
Client: &version.Version{SemVer:"v2.2.1", GitCommit:"db531fd75fb2a1fb0841a98d9e55c58c21f70f4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.1", GitCommit:"db531fd75fb2a1fb0841a98d9e55c58c21f70f4c", GitTreeState:"clean"}

Steps to reproduce:

1) create a new chart and deploy  (this works)
helm install -n my-test nginx-my-0.1.1.tgz --wait --debug --timeout 60

2) upgrade / rollback same version
helm upgrade my-test nginx-my-0.1.1.tgz --wait --debug --timeout 30
output:
Created tunnel using local port: '65109'
SERVER: "localhost:65109"
Error: UPGRADE FAILED: transport is closing

### container crashed
$ helm version
Client: &version.Version{SemVer:"v2.2.1", GitCommit:"db531fd75fb2a1fb0841a98d9e55c58c21f70f4c", GitTreeState:"clean"}
Error: cannot connect to Tiller

After that the pod just crashed and it recovers, or some times I had to kill the pod manually to get it back.

Do you think this is something that will be fix soon, or how long it will take to get the fix out there, I would like to have an estimate to relay in this new option. 
Thank you!

-------------
Tiller pod logs:

2017/02/28 21:34:48 storage.go:133: Getting release history for 'my-test'
2017/02/28 21:34:48 release_server.go:533: rolling back my-test (current: v2, target: v1)
2017/02/28 21:34:48 storage.go:37: Getting release "my-test" (v1) from storage
2017/02/28 21:34:48 release_server.go:913: Executing pre-rollback hooks for my-test
2017/02/28 21:34:48 release_server.go:940: Hooks complete for pre-rollback my-test
2017/02/28 21:34:48 client.go:393: Looks like there are no changes for nginx-my-deployment
2017/02/28 21:34:48 client.go:560: beginning wait for resources with timeout of 5m0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54b973]

goroutine 105 [running]:
panic(0x156c840, 0xc42000a040)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/kube.(*Client).waitForResources.func1(0x14ce080, 0xc4207e4c60, 0xc420a5d5a7)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/kube/client.go:588 +0xe63
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait.WaitFor(0xc420a2eee0, 0xc42091bb00, 0xc42006db00, 0x15daa00, 0xc420a2eee0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:271 +0x70
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait.pollInternal(0xc420a2eee0, 0xc42091bb00, 0xc420a2eee0, 0xc42091bb00)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:187 +0x41
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait.Poll(0x77359400, 0x45d964b800, 0xc42091bb00, 0x0, 0x1)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:183 +0x4d
k8s.io/helm/pkg/kube.(*Client).waitForResources(0xc420435660, 0x45d964b800, 0xc4209ab408, 0x1, 0x1, 0x1, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/kube/client.go:633 +0x167
k8s.io/helm/pkg/kube.(*Client).Update(0xc420435660, 0xc4203703e0, 0x1a, 0x1fd6d40, 0xc420245030, 0x1fd6d40, 0xc4202450a0, 0xc420176000, 0x12c, 0x1, ...)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/kube/client.go:267 +0x4cb
k8s.io/helm/pkg/tiller.(*ReleaseServer).performKubeUpdate(0xc4202e6020, 0xc420244bd0, 0xc420244fc0, 0x0, 0x12c, 0x1, 0xc4203703e0, 0x1a)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:510 +0x22a
k8s.io/helm/pkg/tiller.(*ReleaseServer).performRollback(0xc4202e6020, 0xc420244bd0, 0xc420244fc0, 0xc42012e5a0, 0x0, 0x0, 0x6)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:480 +0x181
k8s.io/helm/pkg/tiller.(*ReleaseServer).RollbackRelease(0xc4202e6020, 0x7fa9960e7ce8, 0xc42012e540, 0xc42012e5a0, 0x1ff0740, 0x18, 0x18)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:451 +0x7d
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_RollbackRelease_Handler.func1(0x7fa9960e7ce8, 0xc42012e540, 0x15b09a0, 0xc42012e5a0, 0xc420266340, 0xc42043e400, 0xc420335a90, 0x4110f8)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:900 +0xa2
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x7fa9960e7ce8, 0xc42012e540, 0x15b09a0, 0xc42012e5a0, 0xc4202e7420, 0xc4202e7440, 0x15, 0xc420583b38, 0x0, 0xc420583b28)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/server.go:53 +0x18c
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_RollbackRelease_Handler(0x16c8d20, 0xc4202e6020, 0x7fa9960e7ce8, 0xc42012e540, 0xc420529770, 0x17e0a98, 0x0, 0x0, 0x2, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:902 +0x166
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420266300, 0x1ff0740, 0xc42037c120, 0xc4203f03c0, 0xc4203ae450, 0x2037650, 0xc42012e4e0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:638 +0xc14
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420266300, 0x1ff0740, 0xc42037c120, 0xc4203f03c0, 0xc42012e4e0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:796 +0x6b0
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42043e300, 0xc420266300, 0x1ff0740, 0xc42037c120, 0xc4203f03c0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:449 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:450 +0xa3

**Comment by thomastaylor312** [comment]
I duplicated this and am taking a look

**Comment by dsteffy-yahoo** [comment]
Hi!  Thanks for looking into this @thomastaylor312.  Really appreciate it.  Do you know when 2.2.2 is scheduled to go out?

**Comment by thomastaylor312** [comment]
We may cut a release because of this bug, but the PR is open to fix it

**Comment by thomastaylor312** [comment]
Also huge thanks to @gerardo8a for bringing this up!

**Comment by chancez** [comment]
I think I'm hitting this in 2.3.1 still. I cannot test w/ 2.4.x because I'm still running issues with `--wait` https://github.com/kubernetes/helm/issues/2426#issuecomment-302481887.

Here's my log output, and the resulting panic:
```
2017/05/18 18:19:06 storage.go:133: Getting release history for 'commerce-staging-deploy'
2017/05/18 18:19:06 hooks.go:87: info: manifest "soy-deploy/charts/nginx-ingress/templates/controller-daemonset.yaml" is empty. Skipping.
2017/05/18 18:19:06 hooks.go:87: info: manifest "soy-deploy/charts/nginx-ingress/templates/controller-metrics-service.yaml" is empty. Skipping.
2017/05/18 18:19:06 hooks.go:87: info: manifest "soy-deploy/charts/nginx-ingress/templates/tcp-configmap.yaml" is empty. Skipping.
2017/05/18 18:19:06 hooks.go:87: info: manifest "soy-deploy/charts/nginx-ingress/templates/controller-stats-service.yaml" is empty. Skipping.
2017/05/18 18:19:06 hooks.go:87: info: manifest "soy-deploy/charts/nginx-ingress/templates/udp-configmap.yaml" is empty. Skipping.
2017/05/18 18:19:08 release_server.go:936: Executing pre-upgrade hooks for commerce-staging-deploy
2017/05/18 18:19:08 release_server.go:965: Hooks complete for pre-upgrade commerce-staging-deploy
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Secret "soy-hookhandler-secrets"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Secret "soy-server-secrets"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Secret "soy-worker-secrets"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Secret "tectonic-com-deploy-dockercfg"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Secret "creme-license-key-secrets"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Secret "soy-license-key-secrets"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Secret "dex-secrets"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Secret "creme-secrets"
2017/05/18 18:19:11 client.go:398: generating strategic merge patch for *runtime.Unstructured
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for ConfigMap "commerce-staging-deploy-nginx-ingress-controller"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for ConfigMap "dex-config"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for ConfigMap "soy-server-config"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for ConfigMap "creme-config"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for ConfigMap "commerce-staging-deploy-nginx-redirect-domain-config"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for ConfigMap "soy-hookhandler-config"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Service "commerce-staging-deploy-nginx-ingress-default-backend"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Service "soy-hookhandler"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Service "creme"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Service "dex-overlord"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Service "commerce-staging-deploy-nginx-redirect-domain"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Service "commerce-staging-deploy-nginx-ingress-controller"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Service "soy-server"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Service "dex-worker"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Deployment "commerce-staging-deploy-creme"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Deployment "commerce-staging-deploy-soy-server"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Deployment "commerce-staging-deploy-nginx-redirect-domain"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Deployment "commerce-staging-deploy-nginx-ingress-default-backend"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Deployment "commerce-staging-deploy-dex-overlord"
2017/05/18 18:19:11 client.go:398: generating strategic merge patch for *runtime.Unstructured
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Deployment "commerce-staging-deploy-soy-hookhandler"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Deployment "commerce-staging-deploy-dex-worker"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Deployment "commerce-staging-deploy-nginx-ingress-controller"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Ingress "commerce-staging-deploy-nginx-redirect-domain-config"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Ingress "dex-worker"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Ingress "hookhandler"
2017/05/18 18:19:11 client.go:410: Looks like there are no changes for Ingress "creme"
2017/05/18 18:19:11 client.go:592: beginning wait for resources with timeout of 5m0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2d8 pc=0x582480]

goroutine 359 [running]:
panic(0x1582f00, 0xc42000a030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/kube.deploymentsReady(0xc4220da200, 0x9, 0x10, 0x1ffaf01)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/kube/client.go:563 +0xa0
k8s.io/helm/pkg/kube.(*Client).waitForResources.func1(0x14e3da0, 0xc42356bb00, 0xc4215835a7)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/kube/client.go:678 +0x1f04
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait.WaitFor(0xc4237151c0, 0xc420b0f920, 0xc420135aa0, 0x15f1940, 0xc4237151c0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:271 +0x70
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait.pollInternal(0xc4237151c0, 0xc420b0f920, 0xc4237151c0, 0xc420b0f920)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:187 +0x41
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait.Poll(0x77359400, 0x45d964b800, 0xc420b0f920, 0x0, 0x1)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:183 +0x4d
k8s.io/helm/pkg/kube.(*Client).waitForResources(0xc4204a6200, 0x45d964b800, 0xc421733600, 0x24, 0x40, 0x40, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/kube/client.go:679 +0x167
k8s.io/helm/pkg/kube.(*Client).Update(0xc4204a6200, 0xc420c66b30, 0x10, 0x1ff6d40, 0xc4203c1180, 0x1ff6d40, 0xc4203c11f0, 0xc423d26e00, 0x12c, 0x1, ...)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/kube/client.go:284 +0x4cb
k8s.io/helm/pkg/tiller.(*ReleaseServer).performKubeUpdate(0xc4203569c0, 0xc420a9e850, 0xc420418e00, 0x0, 0x12c, 0x1, 0xc420c66b30, 0x10)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:533 +0x22a
k8s.io/helm/pkg/tiller.(*ReleaseServer).performUpdate(0xc4203569c0, 0xc420a9e850, 0xc420418e00, 0xc421e36000, 0x0, 0x0, 0x6)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:322 +0x19b
k8s.io/helm/pkg/tiller.(*ReleaseServer).UpdateRelease(0xc4203569c0, 0x7fab002b2bf0, 0xc421472db0, 0xc421e36000, 0x2010860, 0x18, 0x18)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:292 +0x7d
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler.func1(0x7fab002b2bf0, 0xc421472db0, 0x15fb040, 0xc421e36000, 0xc42019d840, 0xc4233b3420, 0xc423665a80, 0x411d48)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:831 +0xa2
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x7fab002b2bf0, 0xc421472db0, 0x15fb040, 0xc421e36000, 0xc420c45ba0, 0xc420c45c20, 0x24359, 0xc420471b38, 0x0, 0xc420471b28)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/server.go:58 +0x18c
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler(0x16e0640, 0xc4203569c0, 0x7fab002b2bf0, 0xc421472db0, 0xc4221ca5f0, 0x17f96d0, 0x0, 0x0, 0x2020202020202020, 0x6547707474682020)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:833 +0x166
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42019d800, 0x2010860, 0xc421474090, 0xc423202f00, 0xc420369350, 0x2057770, 0xc421472d80, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:638 +0xc14
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42019d800, 0x2010860, 0xc421474090, 0xc423202f00, 0xc421472d80)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:796 +0x6b0
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4233b3080, 0xc42019d800, 0x2010860, 0xc421474090, 0xc423202f00)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:449 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:450 +0xa3
```

Note, that this is only panicing in a particular release, my other releases with the same chart are upgrading fine.
