### ISSUE TITLE
Create helm client container

### ISSUE THREAD

**Issue by mattymo** [kubernetes/helm#2049]
Many other popular kubernetes apps distribute not only a binary, but a lightweight container with their client tools. Can you either include helm client in the tiller container or create a separate helm container based on Alpine Linux?

I'm creating this issue as a possible solution to the CoreOS dilemma where you need to obtain a statically compiled socat in order to deploy Helm. The shortcut solution seems to me that it's simpler if you can just distribute a container with all required binaries, such as socat.

**Comment by bacongobbler** [comment]
See #1929

**Comment by thomastaylor312** [comment]
This issue has been inactive for 30 days and has another open issue. Closing.
