### ISSUE TITLE
helm dep list report missing for subcharts downloaded with version matching

### ISSUE THREAD

**Issue by qwangrepos** [kubernetes/helm#2056]
If a subchart's version is defined implicitly, `helm dep list` would still report missing after a subchart is downloaded via `helm dep update` or `helm dep build`. This is because `helm dep list` does not consider implicit version when checking existence of a subchart.

Implicit version is like: 0.5.x, >=0.5.0, etc. 

A fix to this could be loading version information from requirements.lock instead of requirements.yaml.

**Comment by technosophos** [comment]
That's a good idea. There _might_ be an edge case where the requirements.lock does not exist, but it would be easy enough to just generate that lock file on-the-fly.

**Comment by qwangrepos** [comment]
On a second thought, generating the lock file on-the-fly could also have inconsistent version information when the repo has been updated recently - a new version comes out while the existing subchart in the charts folder still has an old one.
Maybe just using version matching is the most intuitive way to solve it.
