### ISSUE TITLE
Add "exec" functionality

### ISSUE THREAD

**Issue by InAnimaTe** [kubernetes/helm#2057]
Earlier, I wrote a [function](https://gist.github.com/InAnimaTe/fb2dd61d73d1d113208ac64032324841) to aid  me in entering containers across namespaces and within pods. When testing etc.. it gets tiring typing out full kc commands, especially when you have things partitioned off into multiple namespaces.

Then, I miraculously thought it would be a fantastic idea if I could do this at the helm level i.e. `helm exec flying-molasses /bin/bash`. Obviously, there's some assumptions made here as a chart can contain many different deployed objects so there could be many many containers. 

Either way, I think this could be cool feature.

**Comment by technosophos** [comment]
I think there were some plans to implement this feature as a plugin. The big unknown was how we figure out which container to attach to. If anyone has guidance on that...

**Comment by thomastaylor312** [comment]
@technosophos Is this still a possibility for a feature or should we go ahead and close this?

**Comment by bacongobbler** [comment]
We should go ahead and close this. Tools like [draft](https://github.com/Azure/draft) should be able to solve the use case, but I don't think this is something we're going to implement in helm. If anyone knows of a helm plugin that does this, please let us know!
