### ISSUE TITLE
Error: could not find a ready tiller pod

### ISSUE THREAD

**Issue by vielmetti** [kubernetes/helm#2064]
I'm bringing up Kubernetes on my Mac under minikube and xhyve, with the eye towards using Kubernetic to manage the whole thing. I installed helm from homebrew as `brew install kubernetes-helm`.

When I do pretty much any Helm command, I get this error message:

```
$ helm status
Error: could not find a ready tiller pod
```

which seems pretty fundamental of a problem. I am not sure how to proceed from here, suggestions for debugging or component installation welcomed. However the upgrade seems to work:

```
$ helm init --upgrade
$HELM_HOME has been configured at /Users/emv/.helm.

Tiller (the helm server side component) has been upgraded to the current version.
Happy Helming!
```

**Comment by bacongobbler** [comment]
if you run `kubectl -n kube-system get po`, do you see a tiller-deploy pod available there?

**Comment by vielmetti** [comment]
I see two pods in mid-deploy:

```
Edwards-MacBook-Air:~ emv$ kubectl -n kube-system get po
NAME                             READY     STATUS              RESTARTS   AGE
kube-addon-manager-minikube      0/1       ContainerCreating   0          46m
tiller-deploy-2654728925-j2zvk   0/1       ContainerCreating   0          28m
```

Searching through kubectl logs I see this error:

```
E0303 22:15:59.462029    2423 docker_manager.go:2114] Failed to create pod infra container: ErrImagePull; Skipping pod "kube-addon-manager-minikube_kube-system(46ae05e07c52d84167b077b142aa4a39)": image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 173.194.66.82:443: i/o timeout)
```

which suggests that I missed something fundamental in setup....

**Comment by vielmetti** [comment]
I did two things, and now it's working.

`minikube addons enable registry-creds` seemed to address the problem of "no credentials on this request".

I also waited a long time, and it came up. I can't be certain that the registry-creds addon was the fix, but now it's working:

```
$ kubectl -n kube-system get po
NAME                             READY     STATUS    RESTARTS   AGE
kube-addon-manager-minikube      1/1       Running   0          1h
kube-dns-v20-ir9j5               3/3       Running   0          51m
kubernetes-dashboard-gxj81       1/1       Running   0          51m
tiller-deploy-2654728925-j2zvk   1/1       Running   0          1h
```

Thanks @bacongobbler for the debug help, I'll close this out.

**Comment by peterzandbergen** [comment]
@vielmetti I would like to know what command you used to find the mentioned log file entry. Cheers

**Comment by peterzandbergen** [comment]
Sounds familiar. Happens to me all the time. Thanks for replying.

**Comment by nottinhill** [comment]
In my case Tiller was stuck booting. So I waited 10 minutes and then it worked. Would it be safe to delete the Tiller Pod if necessary? Or isnt there a ReplicaSet running?

**Comment by CharlieKuharski** [comment]
@vielmetti 
Thanks!  - I can confirm "minikube addons enable registry-creds" was the fix for my tiller pod not starting.

**Comment by vineethvijay** [comment]
None was working for my case(there wasn't the pod scheduling). 
This worked:

I ran tiller locally,
```
$ <bin>/tiller
[main] 2018/12/19 11:10:41 Starting Tiller v2.12.0 (tls=false)
[main] 2018/12/19 11:10:41 GRPC listening on :44134
[main] 2018/12/19 11:10:41 Probes listening on :44135
[main] 2018/12/19 11:10:41 Storage driver is ConfigMap
[main] 2018/12/19 11:10:41 Max history per release is 0
...
...

$ export HELM_HOST=localhost:44134
$ helm version # Should connect to localhost.

```

**Comment by sdejan12cc** [comment]
Funny, for me worked when I did
`minikube addons disable registry-creds`
and then
`minikube addons enable registry-creds`

**Comment by ravibhattinkw** [comment]
I have the same problem
[a-iamdevuser ~]$ kubectl -n kube-system get pod
NAME                             READY     STATUS    RESTARTS   AGE
coredns-7d77776957-6s7h2         0/1       Pending   0          6h
coredns-7d77776957-hcwf6         0/1       Pending   0          6h
tiller-deploy-5c5455c544-6gczg   0/1       Pending   0          2h
[a-iamdevuser@ ~]$ kubectl logs tiller-deploy-5c5455c544-6gczg
Error from server (NotFound): pods "tiller-deploy-5c5455c544-6gczg" not found
[a-iamdevuser@ ~]$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Error: could not find a ready tiller pod

**Comment by loganxavier** [comment]
Having the same error on a fresh machine, opened a question about [here](https://serverfault.com/questions/958912/helm-under-microk8s-giving-error-could-not-find-a-ready-tiller-pod).

**Comment by DNXie** [comment]
@charlenezheng I was trying your solution and ran into this error:

`Error from server (BadRequest): container "tiller" in pod "tiller-deploy-c48485567-9tlpw" is waiting to start: trying and failing to pull image`

**Comment by ebrucucen** [comment]
For me, my installation was missing tiller service account. On istio installation folder, running this solved my issue.
```
kubectl apply -f install/kubernetes/helm/helm-service-account.yaml   
helm init --service-account tiller
```

**Comment by stevegore** [comment]
If anyone else arrives at this point because you're scripting up a `helm install` followed by a `helm upgrade --install`, the good news is you can now use the `wait` command to wait for the pod to be ready before you do the upgrade. In the below I'm using labels to select the right pod:

```bash
kubectl -n kube-system wait --for=condition=Ready pod -l name=tiller --timeout=300s
```

**Comment by source-ram** [comment]
allow master to run pods:
kubectl taint nodes --all node-role.kubernetes.io/master-

**Comment by micseydel** [comment]
Nothing in this thread helped me with the issue, although restarting Docker fixed it.

**Comment by BiteFoo** [comment]
> allow master to run pods:
> kubectl taint nodes --all node-role.kubernetes.io/master-

thanks,it works for me.
