### ISSUE TITLE
Issue warning if unknown dependencies present in `/charts` directory

### ISSUE THREAD

**Issue by jrnt30** [kubernetes/helm#2066]
Thanks for all the work on the project, it's really quite enjoyable to use!  It would be useful to get a warning when doing a `helm install` of a chart, if there are charts in the `/charts` folder that are not actually mapped to the `requirements.yaml`.   As it stands now, if you you remove a dependency from `requirements.yaml` it is still present (and installed) when you run it next. 

In my situation, I had been attempting to test two things simultaneously, the `file://` based processing of local charts in conjunction with the `condition` option.  

My issue was that: 
* Defined the dependency in the `requirements.yaml` of the Parent project
* Did **not** use the name that was declared in the other chart.
* Helm installed the dep locally with the "real" name of the package 
* The `condition` for the requirement was not respected as the installed package name had been change to the "real" name 

```
### parent/requirements.yaml

dependencies:
- name: local-dep
  repository: "file://../dep"
  condition: local.enabled
  version: 0.1.0
```

```.
├── dep/
│   ├── Chart.yaml
│   ├── charts/
│   ├── templates/
│   │   ├── NOTES.txt
│   │   ├── _helpers.tpl
│   │   ├── deployment.yaml
│   │   └── service.yaml
│   └── values.yaml
└── parent/
    ├── Chart.yaml
    ├── charts/
    │   └── dep-0.1.0.tgz
    ├── requirements.lock
    ├── requirements.yaml
    └── values.yaml
```

Super simple example [deptest.zip](https://github.com/kubernetes/helm/files/818410/deptest.zip)

**Comment by technosophos** [comment]
This was done intentionally.

Here's why we did it: It is completely valid for you to create a subchart in your `charts/` directory that is not managed as an external requirement. Only external requirements are managed by `requirements.yaml`.

At some point in the future, we may no longer have the `repository` field be mandatory in `requirements.yaml`, in which case we might be able to do basically what you are suggesting. So I'm adding this to the backlog of work to do.

**Comment by jrnt30** [comment]
Thanks for the feedback, that makes a lot of sense.

**Comment by bacongobbler** [comment]
Is this something we want to discuss for Helm 3 or should we consider this something as "working as intended"? I'm not too familiar with this side of the codebase, so I'll defer to someone else to make the call.

**Comment by jrnt30** [comment]
I think this should be closed, having gotten to know the project better I see value in the inherit dependencies present in the `/charts`.
