### ISSUE TITLE
feature: Limit number of historical releases Helm tracks

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#2081]
Per @majewsky in #1829:

>The rationale is the same as with the revisionHistoryLimit on a Kubernetes Deployment object. We deploy a quite large chart (https://github.com/sapcc/openstack-helm), and once a few hundred releases had accumulated in our staging env, many Helm operations (and many kubectl operations, even) got really sluggish because the few hundred configmaps occupy an impressive amount of space in the etcd. I don't have the exact numbers, but I have been told that our k8s's etcd's disk footprint had grown to 3-4 GB (with 8 GB being the limit at which etcd would start to break down), and we had a lot of failed raft proposals, leader elections and general sluggishness going on in the etcd cluster because of that. Now that garbage collection is in place, we're back down to 500 MB and everything is running smoothly again.
>
> The ideal solution, in fact, would be if Helm releases had a revisionHistoryLimit like Kubernetes deployments do, so we can do away with our custom garbage collector. But that would be a separate issue.

This would be relatively straightforward to implement in the storage layer, but we need to figure out what the right way is to set this. Is it a global setting, or a per-release setting (or a hybrid)?

**Comment by jbehling** [comment]
+1 on this, we update a helm release as part of a CI deploy, when it gets into the thousands of release it starts to hurt performance

**Comment by bacongobbler** [comment]
This has been fixed in helm 2.7 as part of #2636.
