### ISSUE TITLE
Add semver comparison functions to templates

### ISSUE THREAD

**Issue by chancez** [kubernetes/helm#2087]
The use case is that sometime apps will make breaking changes, and this would allow templates to add conditional based on the application version. While this adds significant complexity to the chart/template, I think it's important to have the option. A user may want to update their chart, but not necessarily update the application version and this would allow a chart author to enable this.

This an example of what I see this being used for:
https://github.com/kubernetes/charts/pull/770#issuecomment-285234715

**Comment by technosophos** [comment]
I think I may implement this in Sprig, which is about to have a substantial release anyway.

**Comment by egeland** [comment]
Probably just need the `-1, 0, 1` comparisons between versions?
Something like `semVerCompare VER_A VER_B` returning:
* `-1` if A < B
* `0` if A == B
* `1` if A > B
?

https://github.com/blang/semver looks like a comprehensive semver library to use.

**Comment by chancez** [comment]
I'm guessing the helm team may want to use https://github.com/Masterminds/semver since many of the helm people worked on that library.

**Comment by egeland** [comment]
Can't see that being a problem, given the same comparison exists in that library, too: https://github.com/Masterminds/semver/blob/master/version.go#L259-L292
:grin:
