### ISSUE TITLE
Release test was timeout but exit code return 0

### ISSUE THREAD

**Issue by Ladicle** [kubernetes/helm#2089]
I think that exit code had better return not 0 when timeout occurs.

```
(%-U-)< helm test hogehoge-release --timeout 10
RUNNING: hogehoge-release
UNKNOWN: hogehoge-release: timed out waiting for the condition

(%-U-)< echo $?
0
```

**Comment by technosophos** [comment]
See also #2166 

We now have several related issues with `helm test` not returning the expected error code when tests fail. Can we get a read on how hard this will be to fix?

**Comment by michelleN** [comment]
Hey @Ladicle - good point. I'm looking into this now. Thanks!
