### ISSUE TITLE
PROPOSAL: Sharing/Adding starter charts

### ISSUE THREAD

**Issue by thenamly** [kubernetes/helm#2091]
This will improve way of sharing/adding starter packs clearly.

# Usage
This command will create a new chart from the CHART, starter chart given. 

```
helm create [-f,--from CHART] NAME
```

CHART can be chart reference, path to packaged or unpackaged chart, absolute URL. This have the same meaning and behaviour as `CHART` in `helm install` command. 

# How it works?
* It fetch/copy the `CHART` to the `$HELM_HOME/starters`. 
* Then overwrite name(=NAME) and version(=0.1.0) in the `Chart.yaml` when creating new chart of the user as it is on [here](https://github.com/kubernetes/helm/blob/5517d00a48a8e9ebe68a19dfe260396d45fb0771/cmd/helm/create.go#L101)

# Use cases

## Starter charts for projects
Other projects/companies can have their own public/private starter packs on their repo or as a shared folder to get project members start implementing new charts that is compatible with the project because they may have different conventions, rules, integrations that they use themselves on their charts. 

## Community driven starter charts
Also if we will have `kubernetes/charts/starters`, chart maintainers can suggest improvements or add new useful starter packs as they are getting more experienced of developing charts.

We should be more strict about following best practices guide when we accept PRs to starters there because we should only add starter packs if it is useful to new comers and maintainers.

## Default chart
If we will have our default chart on `kubernetes/charts/starters/default` and
if `helm create mychart` actually uses that as a default starter chart without giving option as `--from=starters/default`

Then we can move default chart to `kubernetes/charts/starters/default` instead of embedding it to the [code](https://github.com/kubernetes/helm/blob/6aa63d671c5deb99810c338d0a44cca21a581131/pkg/chartutil/create.go#L143)

This will make it easy to improve default starter chart with evolving best practices and helm itself for us (collabrators, official chart maintainers and community).

# QA

## I understand why we overwrite Chart.name, but why we overwrite Chart.version?
Starter chart can get updates and get version bump with time. It should be behave like exactly the same as just another chart in the repo by having consistent SemVer versioning. 

However, when a new chart created from starter chart, it should have `0.1.0` as initial version. So we just overwrite when generating new chart from it. 

## What about `--starter, -p` options?
Actually we can add the feature to this options. 

However, we also need to check `$HELM_HOME/starters` when we are checking `CHART` as we do in `install`. This will complicate the code. It is better to leave `--starter, -p` as it is until 3.x for backward compabability. Also, maybe we can use `$HELM_HOME/starters` after we exhaust every possibility of `CHART`.

# Volunteering for a PR
I can start implementing this on a PR as soon as I get feedback from maintainers here, I believe it can be on 2.3 (or upcoming-minor/backlog-minor as #2069) as it is small addition.

# Thanks everyone for helm, the great tool for kubernetes community

**Comment by technosophos** [comment]
I love this idea. Manually creating new starters is sort of a pain. This would make it much better.

I'm marking you as working on it. I'll drop this in the 2.4-triage queue, and if you feel like you can get it done in the 2.3.0 milestone, I'll bump it in there.

**Comment by thomastaylor312** [comment]
@thenamli Are you going to work on a PR for this? If not, I am going to unassign it and label it as help wanted so people can take this

**Comment by ipedrazas** [comment]
I was going to suggest to create a `helm add secret CHART` to generate a `secret.yaml` in the templates folder, but this sounds like a better idea :)

**Comment by prydonius** [comment]
@ipedrazas I think that would be pretty useful too as your working on a chart.

**Comment by ipedrazas** [comment]
I did start implementing the `helm add` command:

https://github.com/ipedrazas/helm/tree/add-resources/

I’ve added a functionality that allows me to do the following:
`helm create my-chart` <-- nothing new here
`helm add secret my-chart` <-- it creates a `secret.yaml` in the `templates` dir of `my-chart` 

I started this after chatting with @lachie83 during the KubeCon...

**Comment by sslavic** [comment]
I don't understand current limitation of `helm create -p`, what value it adds to limit/require that charts can be created only from charts which are themselves stored in "starters" directory. Does it make sense to allow creating a new chart from just about any existing chart, on local filesystem or remote repo (just like install)?
