### ISSUE TITLE
Add `helm repo show [NAME]` command

### ISSUE THREAD

**Issue by kragniz** [kubernetes/helm#2098]
If your repo urls are long, `helm repo list` truncates them. For example, something like:

```
$ helm repo list
NAME     	URL                                               
stable   	http://storage.googleapis.com/kubernetes-charts
incubator	https://kubernetes-charts-incubator.storage.goo...
```

It would be nice to have either a --verbose flag to `helm repo list`, or `helm repo show [NAME]` to show the full url.

**Comment by adamreese** [comment]
Looks like we can remove the max column width.
