### ISSUE TITLE
Unable to use condition in `requirements.yaml`

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/helm#2111]
While trying to enabled and disable a chart via `requirements.yaml`, I am unable to successfully disable a chart based on a known `false` boolean value.

##### Download a chart with nested dependencies 

```bash
$ wget https://charts.deis.com/workflow/workflow-v2.12.0.tgz
$ tar -xzf workflow-v2.12.0.tgz
$ cd workflow
```

##### Add `router.enabled` bool to parent `values.yaml`

```yaml
..snip
184 router:
 +     enabled: false
185    dhparam: ""
..snip
```

##### Add `condition: router.enabled` to `requirements.yaml`

```yaml
..snip
47  - name: router                                                                                                                                                                      
48    version: "v2.11.0"                                                                                                                                                                
49    repository: https://charts.deis.com/router                                                                                                                                        
 +    condition: router.enabled
..snip
```

##### Remove `requirements.lock`

```bash
$ rm -f requirements.lock
```

##### Install the chart

```bash
$  helm install . --namespace deis
```

##### Check if the router subchart was deployed

```bash
$ kubectl get po -n deis | grep -i router
deis-router-2126433040-fmx2g             1/1       Running             0          29s
```

### Notes

 - Replicated behavior **with** and **without** `requirements.lock`
 - Replicated behavior by explicitly setting the flag ` helm install . --namespace deis --set router.enabled=false`

##### Documentation:

This is the part where I am getting confused, and really hope I am just doing something incorrectly

> Condition - The condition field holds one or more YAML paths (delimited by commas). If this path exists in the top parent's values and resolves to a boolean value, the chart will be enabled or disabled based on that boolean value. 

[Original documentation](https://github.com/kubernetes/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml)

##### Helm version

```bash
$ helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
You're using an older version of Helm. Upgrade to v2.2.0+ which is when condition support was added.

For reference I was able to get it all working with v2.2.2:

```
$ cd /tmp/ghost
$ helm fetch stable/ghost --untar
$ vim ghost/requirements.yaml # enter a condition field of mariadb.enabled for the mariadb dependency
$ helm install ./ghost --name ghost1 --set mariadb.enabled=true
$ helm install ./ghost --name ghost2 --set mariadb.enabled=false
$ kubectl get deploy
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
ghost1-mariadb   1         1         1            0           4s
```

**Comment by kris-nova** [comment]
Thanks @bacongobbler
