### ISSUE TITLE
Allow unnamed repositories

### ISSUE THREAD

**Issue by kragniz** [kubernetes/helm#2113]
When doing operations such as `helm fetch` and `install`, it would be useful if helm allowed to specify a repo URL instead of a locally configured repo name.

Something similar to

    helm fetch https://charts.foo.com fancy-package

which would install the default version of `fancy-package` from charts.foo.com.

Doing this makes it easier to use from scripts, since you don't need the extra step of naming and configuring a repo locally.

**Comment by kragniz** [comment]
Could also reuse the docker-style naming

    helm fetch charts.foo.com/fancy-package

**Comment by thomastaylor312** [comment]
I think this could be a very useful feature for CI/CD stuff and may even be a good starter feature for a new contributor. I know you'd have to change things in a few places, but the logic wouldn't be hard. Should we label this as a starter?

**Comment by kragniz** [comment]
Some decision about how the command line arguments should look should take place before labelling as a starter issue.

**Comment by kragniz** [comment]
FWIW, I think the best way to handle this is to add a `--repo` option to install and fetch.

    helm fetch --repo=https://charts.foo.com fancy-package

**Comment by technosophos** [comment]
I agree. That would allow the most flexibility both now and in the future.

**Comment by technosophos** [comment]
Assigned to @sushilkm . For some reason, the gh box won't let me assign it the normal way.

**Comment by thomastaylor312** [comment]
Closed in #2300
