### ISSUE TITLE
Feature request: `helm init --wait`

### ISSUE THREAD

**Issue by c-knowles** [kubernetes/helm#2114]
It's now possible in 2.2.x to use the `--wait` flag to [wait for deploys](https://github.com/kubernetes/helm/issues/1805) to be ready which is a great addition especially for various CI/CD scenarios.

How feasible would it be to add the same to `helm init` with reference specifically to Tiller and it being ready to serve? Same premise as waiting for Charts to be ready but with Tiller itself to be installed/upgraded.

**Comment by technosophos** [comment]
Seems like a good idea to me.

**Comment by foxish** [comment]
+1. This will likely help us with writing e2e tests and automation as well.

**Comment by pminkov** [comment]
+1. In the meantime, here's a workaround:

```bash
$ helm init; kubectl rollout status -w deployment/tiller-deploy --namespace=kube-system; 
$HELM_HOME has been configured at /home/petko/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
Waiting for rollout to finish: 0 of 1 updated replicas are available...
deployment "tiller-deploy" successfully rolled out
```

**Comment by at1012** [comment]
@technosophos I would like to work on this.
