### ISSUE TITLE
Add --destination flag to helm package

### ISSUE THREAD

**Issue by kragniz** [kubernetes/helm#2117]
`helm fetch` has the `--destination` `-d` flag to save chart archives to a particular directory, which is pretty useful. It would be nice if `helm package` had something similar.

**Comment by technosophos** [comment]
I'm totally cool with that.

**Comment by vbmade2000** [comment]
@kragniz Can we close this ?

**Comment by bacongobbler** [comment]
Once #2153 is merged, yes.

**Comment by kragniz** [comment]
Why would we want to close?

**Comment by vbmade2000** [comment]
@kragniz Ah I didn't see that it is yet to be merged.
@bacongobbler Yes.
