### ISSUE TITLE
Allow updating chart dependencies when packaging a chart

### ISSUE THREAD

**Issue by seh** [kubernetes/helm#2128]
At present when one runs _helm package_ against a chart with entries in its _requirements.yaml_ file but an empty _charts_ directory (or even one partially populated), Helm fails with the following complaint:
> Warning: <chart name> is in requirements.yaml but not in the charts/ directory!

It would be helpful to be able to tell Helm to acquire any missing dependencies before packaging, since packaging can't proceed without doing so anyway. Per [discussion in the "helm" Slack channel](https://kubernetes.slack.com/archives/helm/p1489686911637282), consider adding a flag to the _helm package_ command that would first run the equivalent behavior of _helm dependency update_.

Such eager updating can't be the new default behavior without surprising long-time users who are already used to the manual dependency updating requirement.

**Comment by technosophos** [comment]
The discussion in the slack channel basically suggested that we provide a `helm package -u` flag that would cause `helm dep up` to be run prior to the packaging logic.
