### ISSUE TITLE
Error: grpc: received message length xxx exceeding the max size 10485760

### ISSUE THREAD

**Issue by pierreozoux** [kubernetes/helm#2129]
(I run helm v2.2.2)

I'm developing a new chart, and when I try to debug, I get the following error:

```
helm install --dry-run --debug --namespace jitsi --name jitsi  ./jitsi-meet
Created tunnel using local port: '44735'
SERVER: "localhost:44735"
CHART PATH: /home/pierre/f/pierreozoux/charts/stable/jitsi-meet
Error: grpc: received message length 337346954 exceeding the max size 10485760
```

I guess it is because the message output is too big.
There are just 12 yaml files and 245 lines in total.

Just using `dry-run` flag is doing the same, and trying to install for real, is also the same.

On the server, not much help neither.
```
Starting Tiller v2.2.2
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
2017/03/16 18:34:08 storage.go:94: Listing all releases with filter
2017/03/16 18:40:01 storage.go:94: Listing all releases with filter
2017/03/16 18:41:04 storage.go:94: Listing all releases with filter
```

I'll split it in various charts and try again.

**Comment by technosophos** [comment]
Typically, you have to be loading quite a bit of data to hit the maximum size. Are some other files sneaking in there? You can use a `.helmignore` file to prevent things like `.git` or other directories from being sent to Tiller.

**Comment by pierreozoux** [comment]
Indeed! I searched in this repo, but didn't find anything about this error.

But thanks a lot, I solved my issue with `.helmignore`.
