### ISSUE TITLE
PROPOSAL: Hierarchical dir values load as -d option

### ISSUE THREAD

**Issue by szibis** [kubernetes/helm#2134]
**Description:**

Thinking about -d option to helm install/upgrade which will load values from top directory recursively to the last sub-directory and each sub-directory will overwrite/merge values if exist on this level.

All charts values will be used as default values if not set from -d just like now with -f option.

With this, we can build external values structure to be applied to helm in runtime and can be simply managed from the versioned git repository.

In current implementation we can only apply multiple -f options and last will overwrite/merge previous. This is good but hard to maintain. 

**Example:**
```
vars/values.yaml
vars/us-east-1/values.yaml
vars/us-east-1/sandbox/values.yaml
vars/us-east-1/sandbox/my-app/values.yml
```
It will get globals/values from first depth0 values, then from us-east-1, next from sandbox in us-east-1 and last from app in sandbox on us-east-1 region.

We can also load multiple value files from directory.
```
vars/values.yaml
vars/us-east-1/values.yaml
vars/us-east-1/sandbox/values.yaml
vars/us-east-1/sandbox/my-app/values.yml
vars/us-east-1/sandbox/my-app/secrets.yml
vars/us-east-1/sandbox/my-app/ingress.yml
```

**Comment by seh** [comment]
Together with #2133, this would allow more specific "environments" or "flavors" deeper in the hierarchy to compose new values by interpolating values supplied higher up in the hierarchy. That is, file _vars/us-east-1/values.yaml_ could define a variable, say, "regional-app" as `${app}-${region}`, where `app` comes from file _vars/values.yaml_.

**Comment by technosophos** [comment]
I'm not opposed to this, since many UNIX tools support something like it. It might be easily done with a plugin.

When it comes to having multiple files in a directory, is the precedence is determined by alphabetical / lexicographical ordering?

I would point out that the Tiller-side would not be able to track the origin file for any given parameter in this case (which is already the case with `--set` and `-f` now). So supporting this may make debugging more difficult.

**Comment by seh** [comment]
Thinking about this more, it's an alternate but more confined take on template inclusion. [The example above](https://github.com/kubernetes/helm/issues/2134#issue-214983327) could be thought of alternately as follows:
- File _vars/us-east-1/sandbox/my-app/values.yml_ includes file _vars/us-east-1/sandbox/values.yaml at its start.
- File _vars/us-east-1/sandbox/my-app/values.yml_ also includes file _vars/us-east-1/values.yaml_ at its start.
- File _vars/us-east-1/values.yaml_ includes file _vars/values.yaml_ at its start.

There are two templates (_vars/us-east-1/sandbox/values.yaml_ and _vars/us-east-1/sandbox/my-app/values.yml_) that happen to include the same subgraph. The directory tree on disk is just a convenient way to express that inclusion graph by "physical arrangement."

**Comment by seh** [comment]
> Never publish anything right before bed — Me

Shortly after posting [my preceding idea](https://github.com/kubernetes/helm/issues/2134#issuecomment-287507761), it occurred to me that that idea could be backwards.

In my current project, where I face variation in deployment environments, I have a skeleton of a template at the top level that needs a few details from the target environment. For example, I define a _Deployment_ that knows that it intends to use a Docker image with a given name and a default tag, but it falls to the environment to define the Docker registry address (which, sadly, for now varies by environment), and maybe override the default image tag.

In that arrangement, using the file names from the original example, file _vars/values.yaml_ would be the skeleton that first wants to include the overriding values from from files _vars/us-east-1/values.yaml_, which includes _vars/us-east-1/sandbox/values.yaml_, which in turn includes _vars/us-east-1/sandbox/my-app/values.yml_. Each file is using details supplied by those it included to interpolate its placeholders, with the more general files picking up details from the more specific files.

Of the two interpretations I've described here, I think the latter one (in this message) would suit my needs better. I'm curious to hear from @szibis whether either of my interpretations match his intent.

**Comment by szibis** [comment]
Ok, maybe I explain more about this proposal.

From 3 years we are using our custom group_vars plugin in Ansible. This plugin gave us the ability to manage multiple Clusters, Env's, Region's, Projects with just one simple command, by managing only 4 values from extra_vars in ansible in a command line.

We just build dir structure and on each level, we can add values file and/or security file. 

Let's say we have project "Zeus" and this project need to be located in two regions us-east-1 and eu-west-1. We need two environments in these regions like production and sandbox. As the last level, we need to run particular app cluster code name "Kronos".
It use role app to deploy app-kronos (role=app, cluster_name=kronos)
```
ansible-playbook playbook.yml -e "hostgroup=app-kronos env=sandbox region=us-east-1 project=zeus"
```
Now directory structure for values and secrets. Plugin will map region,env,project,app on each defined level:
```
# load global values - always load
group_vars/vars.yaml
# per defined project global vars
group_vars/zeus/vars.yml
# load vars per defined region from extra_vars (-e)
group_vars/zeus/us-east-1/vars.yaml
group_vars/zeus/eu-west-1/vars.yaml
# load vars per defined env in particual defined region from extra_vars (-e) 
group_vars/zeus/us-east-1/sandbox/vars.yaml
group_vars/zeus/us-east-1/production/vars.yaml
group_vars/zeus/eu-west-1/sandbox/vars.yaml
group_vars/zeus/eu-west-1/production/vars.yaml
# load vars per defined project,region,env,app from extra_vars (-e)
group_vars/zeus/us-east-1/sandbox/app-kronos/vars.yaml
group_vars/zeus/us-east-1/sandbox/app-kronos/security.yaml
group_vars/zeus/us-east-1/production/app-hera/vars.yaml
group_vars/zeus/us-east-1/production/app-hera/security.yaml
group_vars/zeus/eu-west-1/sandbox/app-athena/vars.yaml
group_vars/zeus/eu-west-1/sandbox/app-athena/security.yaml
group_vars/zeus/eu-west-1/production/app-poseidon/vars.yaml
group_vars/zeus/eu-west-1/production/app-poseidon/security.yaml
```
Running ansible command above it will load files from global to cluster depth - merging/replacing yaml structures.
```
group_vars/vars.yaml
group_vars/zeus/vars.yaml
group_vars/zeus/us-east-1/vars.yaml
group_vars/zeus/us-east-1/sandbox/vars.yaml
group_vars/zeus/us-east-1/sandbox/app-kronos/vars.yaml
group_vars/zeus/us-east-1/sandbox/app-kronos/security.yaml
```

Now how this can be used in Helm. I think we need the ability to manage the scope of loaded values through maybe --set (region, env, project, app) - maybe namespace should be involved but can be managed separately. 
I think this should be possible through external plugins in helm client and tiller to build a custom solution and some default values load model integrated inside helm itself.
Maybe values files should have comments with well defined metadata to instruct tiller in debug mode which value file contain what values and to expose them in diff output.

This feature is for me a key to efficiently use CI/CD with Helm as the backend for app deployments. 

What is very nice is that we can integrate Helm with https://github.com/kubernetes-incubator/kargo
to build cluster, test it and then deploy all helm charts we need. 
Ansible could look at values from the helm and template them before deploy or just use helm module to manage using --set parameters to helm from inside kargo cluster build playbook.

Waiting for some feedback and I think this should be generic and extensible by plugins at every level to build custom solutions.
