### ISSUE TITLE
Proposal: Add a weight system to hooks

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#2136]
## Scenario
I have two `pre-upgrade` hooks that I need to fire in a very particular order. As it is currently implemented the ordering is not guaranteed and my upgrade procedure may not complete. 

## Proposal
* Add a weight to all hooks (supplied as an integer). 
* Tiller will pre-sort all hooks by weight in `ascending` order
* Execute all hooks with the same weight simultaneously 

This will allow users to supply their weights as a variable in the `values.yaml` file which can be overridden if a conflict arises. This also satisfies the need of allowing a specific execution order of hooks for complicated installation/upgrade processes.

**Comment by jchauncey** [comment]
So I have an implementation of this done. 

* Sorts hooks by weight and if there are any ties it will use the Name (hook.Name)
* Does not execute hooks simultaneously (Im going to look into this but doesnt seem to be important)
* Adds a new annotation `helm.sh/hookWeight`

**Comment by cheyang** [comment]
> I have two `pre-upgrade` hooks that I need to fire in a very particular order. As it is currently implemented the ordering is not guaranteed and my upgrade procedure may not complete.

I'd like to ask how to determine `the previous hook` is completed, then start the second hook. If the previous hook is a pod, does the complete mean the pod is ready or just is loaded into kubernetes(maybe in pending).
