### ISSUE TITLE
ProcessRequirementsEnabled doesn't inherit tags/conditions from the parent chart

### ISSUE THREAD

**Issue by altroy75** [kubernetes/helm#2139]
It looks like every recursive call to ProcessRequirementsEnabled (pkg/chartutil/requirements.go) on a subchart ignores tags/conditions defined in the parent chart

the way to reproduce this problem: 

1.  parent-chart 
  - `tags.standalone = false`
  - `requirements.dependencies: kafka`
  2.  charts/subchartA
    -  `requirements.dependencies: kafka (tags: standalone)`
  3.  charts/subchartB
    - `requirements.dependencies: kafka (tags: standalone)`

In this scenario all 3 kafka dependencies remain enabled. The required result, which is only kafka dependency of the parent chart is enabled, is achieved only when using --set tags.standalone=false explicitly in the command line.

**Comment by technosophos** [comment]
@jascott1 Want to take a look at this? Or clarify the functionality?

**Comment by jascott1** [comment]
@altroy75 i will check this out and get back asap.

**Comment by jascott1** [comment]
@altroy75 You don't have a tag for your top level Kafka dep listed in your example. Is that the case?

**Comment by altroy75** [comment]
Correct. the top level kafka dep is the one that should remain. 
Basically the purpose of this is the following:  subchartA and subchartB are standalone charts, each with its own kafka dependency. tThose charts can be deployed and tested independently from the parent-chart. But when they are aggregated into the product chart (parent-chart), then only one kafka broker should be deployed, the one that comes from the product level chart.

**Comment by jascott1** [comment]
Sorry for the delay but I am looking into this now.

**Comment by jascott1** [comment]
I have confirmed that is a bug with the values processing and have created a fix. 

@technosophos @thomastaylor312 Can we mark this issue as a bug so I can reference it in PR?
