### ISSUE TITLE
Need to lock releases during 'helm upgrade'

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#2146]
In Slack, @chancez asked a few questions that got me looking at the code. It appears that it may be possible to run two `helm upgrade` commands at very nearly the same time, and get a result that contains interleaved results.

One thing we can do to minimize this risk is modify `performUpdate` to lock a release (by name) when it starts the update, and unlock it when it completes. While we cannot ensure that that will fix all ordering issues (since really it's Kubernetes that is responsible for that), we can ensure that the manifests for a particular release are sent together in groups.

The same locks should be respected in `rollback` and `delete`.

**Comment by nebril** [comment]
I would like to give it a go
