### ISSUE TITLE
SemVer is not quite compatible with SemVer2

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#216]
Can we replace the SemVer library here with one of the standard ones?
https://github.com/kubernetes/deployment-manager/blob/master/registry/semver.go

The one present here only handles a subset of SemVer versions. We typically use https://github.com/Masterminds/semver

**Comment by goltermann** [comment]
FWIW, Kubernetes uses blang/semver.

https://github.com/kubernetes/kubernetes/blob/796cc556636879d323418ea1dffce52ec04603b8/pkg/version/semver.go#L23

**Comment by mattfarina** [comment]
The implementation of SemVer currently in deployment-manager doesn't match the spec. See http://semver.org.

**Comment by technosophos** [comment]
Looking at Blang, it does not have the right comparators for us. It seems to be missing major version (^) and minor version (~) comparisons.

**Comment by technosophos** [comment]
Investigating this issue, I found more problems.

It looks like the usage of SemVer inside of DM assumes that it can collapse v2.0.0 down to v2, which is the opposite way that the other SemVer spec seems to work. I surveyed a number of other libraries in a few different languages, and they all expand `v2` to `v2.0.0`. However, we can't simply implement this because it appears that the semver number is correlated to GitHub tags in existing DM repositories, which may not be actual semantic versions. Probably, if we switch over to `semver`, we can use `semver.Version.Original()` to handle that case.

The SemVer package also does not handle pre-release and build metadata, both of which are used frequently and are part of the spec (and also in GitHub tags). It's not clear how we'd do this, since the non-standard rendering of 2.0.0 to 2 makes it unclear to me whether the right representation of 2.0.0-alpha.1+1234 is 2-alpha.1+1234 or 2.0.0-alpha.1+1234.

**Comment by mattfarina** [comment]
@technosophos The [SemVer spec](http://semver.org) notes that it needs to be in the form `2.0.0-alpha.1+1234`. `2-alpha.1+1234` is _NOT_ SemVer. So, it's either SemVer and needs to be fixed to work in the form `2.0.0-alpha.1+1234` or it's not SemVer and a description of the format should be documented.
