### ISSUE TITLE
Feature: Tiller api should be namespaced

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/helm#2168]
In Tiller 2.x, all Tiller apis are not namespaced, eg, `GetReleaseStatusRequest`, `GetReleaseStatusResponse`, `UpdateReleaseRequest`. I think releases should be namespaced meaning:

 - A single release can only mutate objects in its namespace.
- Release versions will only consider prior releases in the same namespace.

Some of the benefits of this approach I can think of are:
- Support multi-tenant model where different teams "own" different Kubernetes namespace.
- It will also allow a Tiller level auhorization check against TPR for a namespace.

Thanks.

**Comment by technosophos** [comment]
This has been discussed at length elsewhere. Tiller is not designed to restrict operations to a namespace, and in the future we want to allow multi-namespaced charts. TPRs, RBACS, and other objects are not namespaced at all, yet Tiller releases need to model them. A release is a global entity, at the same nomenclature level as RBACS, namespaces, and TPR definitions. It will continue to be this way at least until Helm 3, and probably onward from there.

That said, restricting Tiller operations to a namespace can be done using RBAC rules, provided you have an identity to assert against an RBAC.

See #2060

**Comment by chancez** [comment]
@technosophos RBAC is both namespaced, and global, so overall I think tiller should probably do something similar.

I don't think most people need multi-namespace releases, and if they do, then that should be it's own kind of release, separate from normal releases. Perhaps you have "ClusterRelease" and "Release" types, similar to RBAC.
