### ISSUE TITLE
PROPOSAL: Propagate values.yaml inside pod's containers as environment variables

### ISSUE THREAD

**Issue by lightsaway** [kubernetes/helm#2170]
Proposal:
It would be great if values.yaml are propagated inside containers as environmental variables

Example:
values.yaml
```
some:
  value: foo
other:
  value: bar
```

When doing helm install  and printenv in container variables will be propagated to smth like this:
```
some.value="foo"
other.value="bar"
```

**This will be a lot of easier since application configuration can be changed from env vars. and can be controlled without templating, but with just _values.yaml_ or _--set_ command**

**Comment by bacongobbler** [comment]
One way we got around this was to template out a specific value:

```
        env:
          {{ range $key, $value := .Values.env }}
         - name: {{ $key }}
           value: {{ $value | quote }}
         {{ end }}
```

Then inside values.yaml:

```
env:
  NAME: "jenny"
  WHO_CAN_I_TURN_TO: "867-5309"
```

This way you can still do `helm install --set env.NAME=foo mychart` while not introducing new features into the codebase.

**Comment by lightsaway** [comment]
What if i have 10 containers in my pod, that means that this template i need to put 10x times which is kinda workaround but i can't see reason why not to put it in core functionality.  Kubernetes/docker does Env propagation to containers. I think this is pretty good feature to have, without having templating workaraounds.
