### ISSUE TITLE
Update grpc-go to 1.2.1

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/helm#2172]
I believe, to read validated client certificate info on the grpc server side, we need [grpc-go 1.2.0](https://github.com/grpc/grpc-go/releases). Relevant links:

- https://github.com/grpc/grpc-go/pull/956
- https://github.com/grpc/grpc-go/issues/111#issuecomment-275820771

**Comment by TamalSaha** [comment]
Since I filed this bug, grpc-go 1.2.1 is released with concurrency bug fix. @adamreese / @technosophos, do you guys mind applying this fix, now that kube dependency is upgraded to 1.6. If you can just do among yourselves, that will be great instead of me trying to send a pr and trying to keep up with the rebase race.

This will unblock the auth changes. Thank you.

**Comment by technosophos** [comment]
I am testing the latest gRPC Go package. I'll open a PR if it succeeds.

**Comment by TamalSaha** [comment]
Please take a look https://github.com/grpc/grpc-go/issues/1148, too.
