### ISSUE TITLE
Make 2.2.4 release?

### ISSUE THREAD

**Issue by anubhavmishra** [kubernetes/helm#2175]
@technosophos's helm-template still uses 2.2.0 (https://github.com/technosophos/helm-template/blob/master/glide.yaml#L5) so we can't use functions that are recently added. For example: `toJson` etc.

**Comment by bacongobbler** [comment]
patch releases should never include new functionality. The v2.3.0 release [will be released on April 4th](https://github.com/kubernetes/helm/milestone/30). :)

**Comment by bacongobbler** [comment]
If you feel like trying out new functionality, feel free to try out the canary releases!

64 bit releases can be found here:

darwin: https://kubernetes-helm.storage.googleapis.com/helm-canary-darwin-amd64.tar.gz
linux: https://kubernetes-helm.storage.googleapis.com/helm-canary-darwin-amd64.tar.gz
windows: https://kubernetes-helm.storage.googleapis.com/helm-canary-darwin-amd64.tar.gz

**Comment by anubhavmishra** [comment]
@bacongobbler thanks! Will use canary releases for now :)
