### ISSUE TITLE
Proposal: Support HTTP json api for Tiller

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/helm#2176]
We would like call Tiller api from via AJAX. We would like to see a HTTP Json version of Tiller api. https://github.com/grpc-ecosystem/grpc-gateway is a great way to auto generate http json api for grpc services.

**Comment by fiunchinho** [comment]
I see that the status is closed. Was this implemented somehow?

**Comment by tamalsaha** [comment]
@fiunchinho , I have implemented this https://github.com/appscode/wheel as a separate standalone project.
