### ISSUE TITLE
Tests not run if not existed while installing a Chart

### ISSUE THREAD

**Issue by xmik** [kubernetes/helm#2180]
I am surprised with one particular behavior and am asking if it is intentional.

My Chart does not use any dependencies. When I run `helm test` and there is a test:
   * that existed while running `helm upgrade --install`, that test will be run
   * that **did not exist** while running `helm upgrade --install`, that test will **not** be run

I expected `helm test` to run all the tests locally declared (all the files with `"helm.sh/hook"` annotation), not only the ones which existed while running `helm upgrade --install`.

I understand that current behavior may be well-grounded, it just seems counterintuitive to me and thus, I wanted to check that.

**Comment by thomastaylor312** [comment]
@xmik You are correct that the behavior is per install or upgrade. The reason being is that you want the tests to be run for that specific revision of the release and if you run them out of band (e.g. from your local dev environment), they are not actually part of the release revision you are testing. Does that make any more sense?

**Comment by xmik** [comment]
Yes, it makes sense. Additionally, I see that this way we can run tests without the need for a chart source code. But I wonder: when is this useful? I think potential use cases are:
  * to invoke tests regularly (and automatically) and treat their result as a health check (it is easier to do without the need for a chart source code)
  * to check once and manually that the deployed release revision works (it is easier to do without the need for a chart source code)
  * just to ensure the tests are part of the release revision we are testing (a safety measure)

Actually I think you only intended the last use case (a safety measure). Do I understand this correctly?

**Comment by thomastaylor312** [comment]
@xmik I believe those use cases you are describing are part of adding validation to an install/upgrade. I have an [open issue](https://github.com/kubernetes/helm/issues/1952) tracking that idea

**Comment by xmik** [comment]
Ok, thanks for the answers and the link. I will close this issue, because @thomastaylor312 you have answered my questions.
