### ISSUE TITLE
Output from "helm init --dry-run --debug" can't be fed back into "kubectl create -f"

### ISSUE THREAD

**Issue by seh** [kubernetes/helm#2181]
One can run the command _helm init --dry-run --debug_ to print YAML-format manifests for Tiller's _Deployment_, _Service_, and, optionally, its companion _Secret_. The idea is to capture these manifests, possibly edit them (such a streaming them through _sed_), and feed them back into the _kubectl create -f_ command. The current output from _helm init_ has two problems:
1. The manifests are separated by a blank line rather than a [YAML starting document boundary marker](http://yaml.org/spec/current.html#document%20boundary%20marker/).  
    _kubectl create_ winds up only creating the _last_ manifest in the stream.
1. The _Service_ spec contains the YAML mapping key "ExternalName," rather than "externalName" (with the leading 'e' in lowercase).  
  _kubectl create_ rejects that key with the following message:
> error: error validating "STDIN": error validating data: found invalid field ExternalName for v1.ServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false

We could add the document boundary markers [in `(*initCmd).Run`](https://github.com/kubernetes/helm/blob/master/cmd/helm/init.go#L152-L169). As for why we're winding up with the capitalized YAML key "ExternalName," I don't see that field mentioned where [we create the `api.Service`](https://github.com/kubernetes/helm/blob/d7cb50bf91eb3973c4331769510691156885f4ff/cmd/helm/installer/install.go#L208-L229) or anywhere else in the Helm project, so perhaps this is a bug in the upstream Kubernetes YAML marshaling configuration.

I first brought these problems up for discussion [in the "helm" channel of the "Kubernetes" Slack team](https://kubernetes.slack.com/archives/C0NH30761/p1490373040542748).

**Comment by thomastaylor312** [comment]
I wonder if it would be useful to make a `helm export` command that would just print out the manifests.

**Comment by seh** [comment]
That would be helpful, too, @thomastaylor312, so long as we can get the output to pass through _kubectl create -f_. The _sed_ script I had to write to get this to work is a cross between gross and embarrassing.

**Comment by seh** [comment]
Here's another issue related to that "ServiceName" key: kelseyhightower/compose2kube#41.

**Comment by seh** [comment]
By the way, here's my current workaround for this issue. Look away now if you must.
```shell
# Work around Helm issue 2181.
# (https://github.com/kubernetes/helm/issues/2181)
#
# We could include the following sed command as well, but it
# mistakenly indicates the beginning of another YAML document at the
# end of the stream. AWK handles this problem much more easily.
#
#   s/^\s*$/---/
helm init --dry-run --debug \
     --tiller-namespace "${target_namespace}" \
     --tiller-image "${tiller_image}" \
    | sed -E -e "
        s/^([ \t]*serviceAccountName:[ \t]*\")(\"[ \t]*)$/\1${service_account}\2/
        s/^([ \t]*)E(xternalName:)/\1e\2/" \
    | awk 'BEGIN { RS = "" ; FS = "\n" } { print "---"; print $0; print "..." }' \
    | kubectl --namespace="${target_namespace}" apply -f -
```

**Comment by seh** [comment]
Note that #2210 would at least eliminate the need for the _awk_ command [above](https://github.com/kubernetes/helm/issues/2181#issuecomment-289793296).

I am also considering the idea of adding a flag to _helm init_ to specify the service account in which Tiller should run, though that then makes one wonder whether Helm should take responsibility for _creating_ that service account, which will then lack any privileges without appropriate RBAC bindings.

**Comment by seh** [comment]
[Pertinent advice from the "sig-api-machinery" Slack channel](https://kubernetes.slack.com/archives/C0EG7JC6T/p1490988488243810): We suffer this "ExternalName" field problem in our _Service_ manifests because we're using the _internal_ Kubernetes types, when we should instead be using the _external_ types.

**Comment by thomastaylor312** [comment]
@seh With regards to your last comment, that sounds like something that we should at least discuss for 2.4

**Comment by seh** [comment]
Up until I had to take off for the day, I started porting Helm over to use _kubernetes/client-go_ and _kubernetes/apimachinery_. They are simple changes—mostly just import paths—that require a lot of tracking things down, asking, "Where did this symbol wind up in the new world?" I'll continue this effort on Monday.

Has anyone debated this migration before and decided against it? If so, I'll consider halting, but if not, I'll see it through.

**Comment by thomastaylor312** [comment]
@seh I actually think there is an open issue for it. I would continue with it and then come to the public dev meeting on Thursday so we can discuss it with the whole team

**Comment by shamil** [comment]
I think this plugin can help: https://github.com/technosophos/helm-template/

**Comment by technosophos** [comment]
At some point in the past, the `helm init` command switched from using a YAML file to using a declared object. An unintended consequence was that the output of `helm init --debug` was no longer readable by `kubectl`. I'm all for fixing that. My original intent with the `--debug` flag was that it would produce YAML that kubectl could load.

**Comment by seh** [comment]
Yes, I've been working on the port for a couple of days now. There are a few stumbling blocks (see kubernetes/client-go#170), but I have Helm mostly using _client-go_ now.

**Comment by seh** [comment]
See #2248 for a complete port to using _kubernetes/client-go_, which would fix the "ExternalName" capitalization problem.

**Comment by seh** [comment]
With #2248 merged, that covers [the second complaint concerning the "ExternalName" key](https://github.com/kubernetes/helm/issues/2181#issue-216856284). I look forward to the next release that will include this change.
