### ISSUE TITLE
PROPOSAL: Add template helper for configmap hashsum generation

### ISSUE THREAD

**Issue by Lookyan** [kubernetes/helm#2182]
Hi,
for now we need to use dirty hack with kubernetes deployment, which generates special annotation for automatic redeploy in case configmap file changes:

_include.tpl
```
{{- define "template" -}}
{{- $template := index . 0 -}}
{{- $context := index . 1 -}}
{{- $v := $context.Template.Name | split "/" -}}
{{- $last := sub (len $v) 1 | printf "_%d" | index $v -}}
{{- $wtf := printf "%s%s" ($context.Template.Name | trimSuffix $last) $template -}}
{{ include $wtf $context }}
{{- end -}}
```

deployment.yaml
```
...
annotations:
        checksum/config: {{ tuple "configmap.yaml" . | include "template" | sha256sum }}
...
```

I think we should add such functionality to helm.

**Comment by Lookyan** [comment]
Another good approach is to fix this hack - https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

Unfortunately `$.Template.BasePath` doesn't work properly.

**Comment by chancez** [comment]
@Lookyan I think `$.Template.BasePath` hasn't made it into a release yet, if thats what you mean by it not working properly. Or are you running a custom build based on master and it's not working for you?

**Comment by technosophos** [comment]
Is BasePath still broken?

**Comment by Lookyan** [comment]
Now it works properly. Thank you!
