### ISSUE TITLE
PROPOSAL: Faster chart development with a "develop" mode for dependencies

### ISSUE THREAD

**Issue by dabdine-r7** [kubernetes/helm#2183]
Currently, when writing a chart that has a dependency on other charts which are also being developed concurrently, you're required to run `helm dep up` each time you modify the dependency on the parent chart. This re-packages the dependency as a `tgz` so that helm can properly deal with it when you attempt to `helm install --dry-run --debug`, etc. I propose helm introduce a `--develop` option similar to python's [setup.py develop](http://setuptools.readthedocs.io/en/latest/setuptools.html#develop-deploy-the-project-source-in-development-mode), which uses a symlink for local, dependent charts.

As a more explicit example, let's say you have a chart named `application`. You realize `application` could be split into another base chart so you can specialize the application based on values. So, a majority of this functionality goes into a base `dependency` chart, while a small specialization remains in the `application` chart. While going through this development cycle, you commonly run `helm dep up` to repackage the `dependency` chart into the `charts/` directory of `application`. You also run into errors and scratch your head during late nights trying to figure out why your chart doesn't work after making a modification to your in-development dependencies, only to realize you didn't run `helm dep up` to consume the most recent `dependency` changes :)

Modifying the example above for this proposal, a developer in that situation would only run `helm dep up --develop` once. Helm would traverse a symlink in the carts/ directory pointing to the location of the dependent chart. The "caveat" is that this can only work for local dependencies (no remote repositories).

**Comment by technosophos** [comment]
I believe this could be done as a fairly simple plugin. The plugin would only have to read the requirements.yaml and create the relevant symlinks. This would be especially easy for `file:///` references.

**Comment by bacongobbler** [comment]
I think this has been resolved with feature flags like [helm install --dep-up](https://github.com/kubernetes/helm/pull/2880) and with tools that use Helm like [draft](https://github.com/Azure/draft), so we can consider this one closed. Please re-open if these don't solve your use case though. Thanks! :)
