### ISSUE TITLE
Issues using helm with a Rancher Kubernetes Stack cluster

### ISSUE THREAD

**Issue by fabriziotorelli-wipro** [kubernetes/helm#2185]
I was trying to connect to the Rancher Kubernets cluster via kubectl, in order to run some PODs creations via helm, and reuse some codes ...

helm ls
Error: client version is incompatible

kubectl --namespace=kube-system get pods | grep tiller
tiller-deploy-3991468440-fvx63          1/1       Running   0          9d

Any Idea?

helm version
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}

Here my kube config (Directly from Rancher Console):
kubectl config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://rancher-server-master.riglet:8080/r/projects/1a29/kubernetes
  name: Kubernetes1
contexts:
- context:
    cluster: Kubernetes1
    user: Kubernetes1
  name: Kubernetes1
current-context: Kubernetes1
kind: Config
preferences: {}
users:
- name: Kubernetes1
  user:
    username: 379...........2BE0BC
    password: kqK1W....................i5Xee

**Comment by bacongobbler** [comment]
As the error suggests, your helm client and tiller versions differ. Follow the docs to upgrade your tiller instance to v2.2.3 and you're all set.

**Comment by fabriziotorelli-wipro** [comment]
helm init --upgrade
$HELM_HOME has been configured at /Users/hellgate75/.helm.

Tiller (the helm server side component) has been upgraded to the current version.
Happy Helming!

helm ls
Error: client version is incompatible

**Comment by thomastaylor312** [comment]
@fabriziotorelli-wipro Is the `tiller-deploy` pod showing the correct tiller image version?

**Comment by technosophos** [comment]
Any update on this one?

**Comment by bacongobbler** [comment]
closing as inactive.
