### ISSUE TITLE
lint needs -f / --values

### ISSUE THREAD

**Issue by devth** [kubernetes/helm#2197]
*Not sure if this has been discussed; I didn't see it while searching through the issues.*

`helm lint` needs to accept an `-f / --values` option if we want it to lint under the same context that a corresponding `helm upgrade` / `helm install` will run.

Otherwise lint will give errors like this when upgrade/install commands are relying on (potentially many) custom values files:

```
[ERROR] templates/: render error in "vault/templates/statefulset.yaml": template: vault/templates/statefulset.yaml:8:21: executing "vault/templates/statefulset.yaml" at <.Values.vault.replic...>: can't evaluate field replicas in type interface {}
```

Also needs `--set` for the same reason.

**Comment by thomastaylor312** [comment]
Hi @devth, you are absolutely right! There is [another issue](https://github.com/kubernetes/helm/issues/2036) for this (you had to know what to look for, so no worries 😃 ) so I am going to close this. Thanks for filing this and reminding me we need to discuss it again!
