### ISSUE TITLE
helm completion fails in zsh

### ISSUE THREAD

**Issue by naveensrinivasan** [kubernetes/helm#2201]
The helm completions fail in zsh `source <(helm completion)`

It specifically fails on 
``` bash
if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_helm helm
else
    complete -o default -o nospace -F __start_helm helm
fi```

**Comment by thomastaylor312** [comment]
I was able to reproduce this bug as well

**Comment by thomastaylor312** [comment]
This is not technically a bug with Helm itself, but rather [with Cobra](https://github.com/spf13/cobra/issues/107). In that issue they mention a workaround that `kubectl` uses to fix this [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/completion.go). 

@technosophos do we want to keep this open to try and implement this fix ourselves or just wait for Cobra to fix it?

**Comment by technosophos** [comment]
Given that the Cobra bug has been open for two years, maybe we should fix it here. :-|

**Comment by SlickNik** [comment]
@technosophos, @thomastaylor312 -- Gonna take a look at a fix for this. Thanks!
