### ISSUE TITLE
Proposal: Workflow / Deployment Orchestration

### ISSUE THREAD

**Issue by wstrange** [kubernetes/helm#2207]
This is a big of vague RFE (apologies), but it would be awesome if helm provided the capability to orchestrate more complex deployments. For example, to be able to express the following:

Install chart A. When Chart A's pods become ready, install Charts B and C. When Chart C pods become ready, remove chart A.  If the deployment fails after 30 minutes, run Chart D.

Scripting the above workflow today is not trivial - in part because you have to tie together the helm release with the Kubernetes artifacts that are created.  Helm provides limited deployment information, and does not output in a tool friendly format (https://github.com/kubernetes/helm/issues/1534 is tracking that issue ). 

The way I do this today is by using labels, and searching for artifacts using those. This works - but it could be easier.  A workflow manager in helm should in theory understand what it has deployed and could make further deployment decisions based on that.

**Comment by technosophos** [comment]
There has been significant work on adding pluggable backends for this. There are two in-progress PRs about "Rudder" that address this very issue. But it's a big and complex problem... so we're moving a little slowly.

**Comment by bacongobbler** [comment]
Closing as this looks like something solved through alternative tooling like [brigade](http://brigade.sh/) or with a DIY "rudder" implementation, which #2079 has since been merged into helm.
