### ISSUE TITLE
Make an error instead of a warning when a chart `is in requirements.yaml but not in the charts/ directory!`

### ISSUE THREAD

**Issue by pierreozoux** [kubernetes/helm#2209]
I'm developing the `rocket.chat` chart.
So, in the mean time, I'm installing/upgrading it with the relative path.
This morning, I wanted to update the docker image to latest.

I got a little warning:
```
Warning: mongodb is in requirements.yaml but not in the charts/ directory!
```

As usually, I safely ignored the warning. What a mistake this time!
If you know `helm` better than I do, you already know what happened, it deleted my mongodb... with the attached volume... then I had to restore a snapshot, but still lost some data on the way.

I was really surprised that a warning had such an unattended effect.

I'd like to warn other people, and maybe propose to print an error and exit in such a scenario. I don't see any reason why somebody would want to deploy something without the dependencies. Or even worst, remove the dependency and its data during an upgrade.

**Comment by technosophos** [comment]
Marked this as a starter. I think it's safe to do this one.
