### ISSUE TITLE
How define global/local value in one chart ?

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/helm#2211]
How define global/local value in one chat ? I notice there is global/local value for [Subcharts and Global Values](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#subcharts-and-global-values)
but don't find how to do this in one chat, thanks

**Comment by mdshuai** [comment]
What I want is like below:
```
1. values.yaml
global
  registry: quay.io/myregistry
  tag: latest
image1:
  registry: ${ global.registry }
  tag: latest
image2:
  registry: ${ global.registry }
  tag: latest

2. In one templates file, I have two container and use image1.registry 
and image2.registry for each container.

3. When I only set global.registry=xxxx in 'helm install --set' comamnd, 
all containers will use the global value xxxx;

4. If I set both global.registry and image1.registry=xxxxx, 
then container1 will use image1.registry xxxxx and ignore the global.registry
container2 still use the global.registry
```

**Comment by thomastaylor312** [comment]
@mdshuai I would recommend using multiple values files (`-f`). It will merge the files together to get the final result you want.

**Comment by bacongobbler** [comment]
closing as resolved/inactive, but please re-open if the answer provided by @thomastaylor312 does not work for you. Thanks!
