### ISSUE TITLE
helm init could have a --wait option

### ISSUE THREAD

**Issue by naveensrinivasan** [kubernetes/helm#2213]
We are trying to use helm for bringing up our entire cluster. The first command we run is `helm init` and the rest are `helm install`. The issue we are having is that we don't have a way to know when helm has finished with its initialization. At present we are having a `sleep 20` as a hack.

The `helm install` has a `--wait` option for the blocking the requests. It would be a nice feature to have a one where the `helm init --wait` also has a wait option.

**Comment by cu12** [comment]
We use something like this for the same:

```
until [ $(kubectl get pods -n kube-system -l app=helm,name=tiller -o jsonpath="{.items[0].status.containerStatuses[0].ready}") = "true" ]; do
  sleep 2
done
```

**Comment by xmik** [comment]
Same issue as #2114

**Comment by naveensrinivasan** [comment]
Closing it because of duplication.
