### ISSUE TITLE
Helpers defined in one subchart interferes with helpers defined in another subchart

### ISSUE THREAD

**Issue by dagvl** [kubernetes/helm#2216]
Version info:
```
helm version
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T19:15:41Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

If you have two subcharts, `a` and `b`, and they both define the same template in _helpers.tpl, only one of the two will "win" and be valid for both subcharts. User expectation would be for subcharts to be independent so you can combine any two subcharts without first looking into their helpers and evalulate them for compatibility.

E.g. given the following char structure:
subtest
subtest/charts/a
subtest/charts/b

With the following helper files:
```
cat ./charts/a/templates/_helpers.tpl
{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "server.fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "a-%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}%
```

and
```
cat ./charts/b/templates/_helpers.tpl
{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "server.fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "b-%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
``` 
(Note the different prefix in the server.fullname template)

and one pod in each subchart using this for naming like so:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "server.fullname" . }}
```

one would expect two Deployments, one prefixed with `a-` and one prefixed with `b-`. The result however is that both of them are prefixed with the same (either a or b), and it differs from runs to runs. This might make e.g. upgrades fail.

E.g.:
```
helm install -n t1 --namespace dagvl . --debug
LAST DEPLOYED: Mon Apr  3 18:02:45 2017
NAMESPACE: dagvl
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME        CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
t1-b        100.66.123.213  <none>       80/TCP   2s
t1-subtest  100.70.195.252  <none>       80/TCP   2s
t1-a        100.67.59.216   <none>       80/TCP   2s

==> extensions/v1beta1/Deployment
NAME        DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
t1-subtest  1        1        1           0          2s
b-t1-a      1        1        1           0          2s
b-t1-b      1        1        1           0          2s
```
```
helm install -n t2 --namespace dagvl . --debug
LAST DEPLOYED: Mon Apr  3 18:02:56 2017
NAMESPACE: dagvl
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME        CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
t2-a        100.67.97.241   <none>       80/TCP   1s
t2-b        100.68.37.85    <none>       80/TCP   1s
t2-subtest  100.71.130.125  <none>       80/TCP   1s

==> extensions/v1beta1/Deployment
NAME        DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
t2-subtest  1        1        1           0          1s
b-t2-b      1        1        1           0          1s
b-t2-a      1        1        1           0          1s
```
```
helm install -n t3 --namespace dagvl . --debug
LAST DEPLOYED: Mon Apr  3 18:03:05 2017
NAMESPACE: dagvl
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME        CLUSTER-IP     EXTERNAL-IP  PORT(S)  AGE
t3-subtest  100.65.230.35  <none>       80/TCP   1s
t3-a        100.67.9.171   <none>       80/TCP   1s
t3-b        100.67.149.70  <none>       80/TCP   1s

==> extensions/v1beta1/Deployment
NAME        DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
t3-subtest  1        1        1           0          1s
a-t3-a      1        1        1           0          1s
a-t3-b      1        1        1           0          1s
```

I've attached a tar.gz with the full chart and subchart for reproducing this. [subtest.tar.gz](https://github.com/kubernetes/helm/files/891849/subtest.tar.gz)

The real-life issue that triggered this is that both the stable/grafana and stable/prometheus charts user a template named server.fullname that are incompatible, causing issues like this for us.

**Comment by seh** [comment]
Note that [the documentation](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/named_templates.md#declaring-and-using-templates-with-define-and-template) does cover this problem:
> There is one _really important_ detail to keep in mind when naming templates: *template names are global*. If you declare two templates with the same name, whichever one is loaded last will be the one used. Because templates in subcharts are compiled together with top-level templates, you should be careful to name your templates with chart-specific names.

Unfortunately, you can't control the names of the templates defined in charts upon which your charts depend. Naming my templates with a qualifying prefix violates the DRY principle, because I wind up sprinkling the chart name (on which I'll vacillate many times, and would prefer to state in only one place) all over the place. Still, I went back through and did it, liking neither the process nor the result.

**Comment by Janpot** [comment]
Yep, just running into this when trying to install the Chart with following `requirements.yml`:

```
dependencies:
- name: grafana
  version: "0.2.1"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: prometheus
  version: "2.0.3"
  repository: https://kubernetes-charts.storage.googleapis.com/
```

So now two public subcharts can mess with each other's configuration? I don't want to be rude but I'd call this a less than ideal solution.

Is there any technical reason why these helpers have to be global?

**Comment by seh** [comment]
@technosophos wrote that part of the documentation in d5346b1be968f91be897d98cb6cd8d084441c20f. Perhaps he can explain the constraints that led to the current design.

**Comment by technosophos** [comment]
This is an artifact of the Go template language. In the language, anything defined in a `define` is placed into the global namespace.

We consider this to be a good thing, because it makes it possible to share helpers across multiple templates (which is the basis for things like the experimental [common-chart](https://github.com/technosophos/common-chart) project). FWIW, I'd hardly consider giving things distinctive names to be a violation of [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself). In fact, giving distinctive names is part of the definition of DRY. This is the attribute of templates that allows us to repeatedly use the same template instead of duplicating the same functionality multiple times or places.

If there are still public charts with names like `fullname` and `name`, we need to file bug reports. Those should have been fixed long ago.

**Comment by Janpot** [comment]
Both helpers are called `server.fullname`. They still clash.

https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/_helpers.tpl#L22
https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/_helpers.tpl#L49

It would be better to isolate these helpers within a chart and find a better mechanism for sharing them across charts.

**Comment by seh** [comment]
When [I wrote about violating DRY above](https://github.com/kubernetes/helm/issues/2216#issuecomment-291852677), I meant that I think of the chart name like a package name: something that we'd prefer to state just once, and have it qualify and maybe even isolate all the definitions that fall within its scope.

At present, we repeat the "package name" in at least three ways:
- The directory name containing the chart's files
- The "name" field in the chart's _Chart.yaml_ file
- Each template name defined within the chart's _templates_ directory

**Comment by technosophos** [comment]
@Janpot Please file an issue in the Kubernetes charts repo. Those functions should have been named `grafana.server.fullname` and `prometheus.server.fullname` (respectively).

**Comment by Janpot** [comment]
@technosophos What if a minor version change of a subchart introduces a helper that clashes with any other helper in my chart or subcharts? Suddenly my release breaks. It's hard to debug because there's not even a warning that helpers are clashing. What if different organisations use different ways of naming their helpers?

**Comment by olvesh** [comment]
I think this issue propagates because the `helm create <chartname>` generates the `_helpers.tpl` the way this thread says is wrong:
```
 > helm create testname; cat testname/templates/_helpers.tpl 
Creating testname
{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

**Comment by bviolier** [comment]
Also got something related to this.

I have my own chart, in that chart, I have Memcached & Percona as a dependency.
The fullname in my chart is bigger than 24 characters.

But, 1 out of the 3 or 4 times that I deploy, my fullname is suddenly just 24 chars, which completely breaks the deploy and also creates completely new services with just the 24 chars name.

After research, and finding this issue, I saw that Memcached has the old limit of 24 configured in [_helpers.tpl](https://github.com/kubernetes/charts/blob/master/stable/memcached/templates/_helpers.tpl).

Upon reading this issue, I can imagine that the idea is that helpers are global. But, I cannot imagine that it is the idea that everytime you upgrade, it is a bingo upon which _helpers.tpl wins. Is this also a known issue?

I will make an issue for the Memcached _helpers.tpl update, but this problem can arise also in other dependencies, and also inter-dependency if two of them use "fullname".

**Comment by bacongobbler** [comment]
closing, please file bugs in kubernetes/charts as recommended by @technosophos in https://github.com/kubernetes/helm/issues/2216#issuecomment-294037962.

related follow-up for anyone interested: https://github.com/kubernetes/helm/issues/3081
