### ISSUE TITLE
map parsing ignores quotes

### ISSUE THREAD

**Issue by jangrewe** [kubernetes/helm#2218]
When i tried to install traefik with helm 2.2.3 and provided a quoted and comma-separated value for the service.annotations key, it seemed to ignore the quotes and assume that the second value is a new key:

```
helm install --name traefik --namespace kube-system stable/traefik --set dashboard.enabled=true,dashboard.domain=traefik.k8s.example.com,service.labels.dns=route53,service.annotations.domainName="traefik.k8s.example.com,api.k8s.example.com"
Error: failed parsing --set data: key "api" has no value
```

**Comment by thomastaylor312** [comment]
It looks like you are missing a second quote in there if I am reading it right.

**Comment by jangrewe** [comment]
@thomastaylor312 Sorry, that was a typo from editing the actually used hostnames. I've updated the original comment.

**Comment by thomastaylor312** [comment]
Yeah, it looks like it may be trying to still split on the comma. I'll tag this as a bug and work on duplicating it myself.

**Comment by technosophos** [comment]
Escape the `,`. This is documented here: https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#customizing-the-chart-before-installing

**Comment by bacongobbler** [comment]
closing as resolved/inactive. Please re-open if this does not work for you. Thanks!
