### ISSUE TITLE
Subchart files.glob override

### ISSUE THREAD

**Issue by s4mur4i** [kubernetes/helm#2221]
Hello,

I am researching a solution to solve a subchart issue.
We have a parent and subchart with following topology
mychart:
 - custom-grafana-dashboard
 - charts
    - subchart
       - grafana-dashboard
       - templates

In subchart/templates we have configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{.Chart.Name}}"
    chartversion: "{{.Chart.Version}}"
    component: "grafana"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-dashboards
  namespace: {{ .Values.namespace }}
data:
  prometheus-datasource.json: |
    {
      "access": "proxy",
      "basicAuth": false,
      "name": "prometheus",
      "type": "prometheus",
      "url": "http://prometheus-{{ .Release.Name }}.{{ .Release.Namespace }}:80"
    }
{{block "dashboards" . }}
{{ (.Files.Glob "grafana-dashboard/*").AsConfig | indent 2 }}
{{ end }}
```
As tested so far this works.
According to "Sharing templates and Subcharts" documentation I should be able to override this with an entry to mychart/template/_helpers.tpl:
```
{{- define "dashboards" -}}
{{ (.Files.Glob "custom-grafana-dashboard/*").AsConfig | indent 2 }}
{{- end -}}
```
But it doesnt work.
In some cases it gives:
```
Error: UPGRADE FAILED: YAML parse error on uprometheus/charts/uprometheus-operator/templates/grafana-dashboard.yaml: error converting YAML to JSON: yaml: line 21: could not find expected ':'
```
I have found an issue for this, but ..
If I run the helm upgrade command 3 times usually 2 times it will succeed, but once it will fail with the error.. which puzzles me

Is it possible to override subcharts files.glob this way?
If not is there any other supported, or hacky way?
The goal would be to overwrite the configmap from parent directory. I have the feeling that defining it in values file might work, but when we have 20 dashboards, the values file would be unreadable.

Thank you

**Comment by thomastaylor312** [comment]
@s4mur4i I am not sure if I completely follow with the examples you gave. Are you looking to include multiple dashboard definitions with a template?

**Comment by s4mur4i** [comment]
@thomastaylor312 
No. The goal would be that the parent chart overrides subchart grafana configmap.
I will try to explain it better.
You have the above configmap in a chart. All it does that it takes all files in grafana-dashboard and adds them to the configmap. this is the base ofa  deployment.

Then we create a parentchart and have the grafana as dependency, but we would like to modify the dashboards. we would like to not use the default ones, but rather have different kinds. We do not want to change the grafan subchart, but override the location from where subchart should take it's dashboards from, in this case the parent chart/custom-grafana-dashboard.

So the outcome should be that the helm install will create a configmap from subchart, but use files from parent custom-grafana-dashboard, instead of the default one defined in the subchart (grafana-dashboard).

**Comment by technosophos** [comment]
That particular error is almost always an issue with indentation. It looks to me like the success or failure of either of the imports you do above will be impacted by the indentation of those files.

I strongly advise people _not_ to us Go template `block` directives. Blocks have particularly hard to debug side effects because of the way template namespacing works. Blocks were developed to solve a very particular use case, and our setup does not match that use case.

**Comment by s4mur4i** [comment]
Thanks, on a side note, what would be the recommended practice to override a .Files.Glob import in subchart? 
Or different practice should be used for this use case?

Thanks

**Comment by technosophos** [comment]
For what you're doing, the most common method seems to be to change the literal glob path to a variable: `.Files.Glob .Values.globals.dashboards` and then set those. To hoist a value from the child chart to the parent chart, you can do this: https://github.com/kubernetes/helm/blob/master/docs/charts.md#importing-child-values-via-requirementsyaml

**Comment by jascott1** [comment]
Sorry but I incorrectly referenced this issue in a PR that has nothing to do with it. The PR commit message has been amended.

**Comment by dgsardina** [comment]
Is there any solution for exactly this requirement?
