### ISSUE TITLE
tiller net=host

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#2222]
I'd like to use helm to deploy sdn plugins such as canal, calico or weave. This would allow much more easily configured sdn's due to helms templating engine. To do so, requires tiller to be running before the sdn.

Due to the way helm contacts tiller via proxy without using a svc, This seems to work by simply by launching tiller's pod with net=host.

Can support for that be added as a command line flag to helm init?

**Comment by technosophos** [comment]
That seems like an option we should be able to add easily.

**Comment by jascott1** [comment]
@kfox1111 bin is here if you want to test.
https://raw.githubusercontent.com/jascott1/bins/master/helm/nethost/_dist/linux-amd64/helm

**Comment by kfox1111** [comment]
This works good. Thank you. :)

**Comment by jascott1** [comment]
@technosophos afaik if we want this in, we just need to decide on final flag name and description.
It is currently:
```
--host-net                 install tiller with net=host
```

**Comment by kfox1111** [comment]
I have a slight preference to --net-host instead of --host-net, as its closer to whats in docker. but doesn't matter too much.

One question would be when this would merge. If its going in to 2.3.1, I think its probably fine as is.

If its going to wait for 2.4.0, then maybe we should ask the question, should it be defaulted on, and can be turned off rather then off and defaulted on? --net-sdn or something.

Switching the default would be simpler for those wanting to deploy sdn and other low level things out of the box and I think should still work for everyone still.

**Comment by rothgar** [comment]
I believe this would also get around the problem of not having socat on nodes running kubelet. Maybe I'm wrong but I can test in my cluster.

**Comment by jascott1** [comment]
@kfox1111 i agree --net-host is better. I got it backwards myself telling someone so i think --net-host is more intuitive.

**Comment by kfox1111** [comment]
@jascott1 a couple of other issues found while testing this:

could the following toleration be added: 
node-role.kubernetes.io/master=:NoSchedule

and, some way to add nodeSelector's so tiller can be targeted to specific hosts rather then floating around the cluster. helm init -n key=value? Its kind of unrelated to this PR, but touches the same code.

**Comment by jascott1** [comment]
@kfox1111 So we want a switch to add that toleration or just use the key/value pattern like you suggested for nodeSelectors?

**Comment by kfox1111** [comment]
or I guess it could be a switch. --tolerations key=value. a little harder to use, but very generic.

**Comment by jascott1** [comment]
We should probably go for --tolerations and --node-selectors

**Comment by kfox1111** [comment]
Sounds good to me. :)

**Comment by jascott1** [comment]
@technosophos Sounds good?
