### ISSUE TITLE
helm error: Unable to create listener: Error listen tcp6 

### ISSUE THREAD

**Issue by yvespp** [kubernetes/helm#2223]
On every helm remote command I'm getting the following error:
```
helm version
E0406 17:26:06.983609   29625 portforward.go:209] Unable to create listener: Error listen tcp6 [::1]:30143: socket: address family not supported by protocol
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
```

Despite the error it seams that all commands are working fine though.
Helm is running on RHEL 7.2.

**Comment by technosophos** [comment]
If `HELM_HOST` is set to `localhost` instead of `127.0.0.1`, this can happen on systems that try IPv6 connections to localhost first.

**Comment by yvespp** [comment]
I don’t have HELM_HOST set, I guess it is set to localhost automatically?
Maybe this error could be suppressed as everything works fine?

**Comment by yvespp** [comment]
The error is logged here: https://github.com/kubernetes/kubernetes/blob/47908629a36430e154681b2af73fa91190e0f08d/staging/src/k8s.io/client-go/tools/portforward/portforward.go#L212

I'll try to change it.

**Comment by technosophos** [comment]
If I had to guess, I'd guess that this is the line that is causing that problem: https://github.com/kubernetes/helm/blob/master/cmd/helm/helm.go#L192

**Comment by technosophos** [comment]
If you export your HELM_HOST=127.0.0.1, does it work?

**Comment by yvespp** [comment]
Tiller is unreachable if I set HELM_HOST:
```
$ export HELM_HOST=127.0.0.1
$ helm version
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
Error: cannot connect to Tiller
```
As far as I understand it, Helm doesn't use the tunnel if HELM_HOST is set and the error doesn't show up.

I think the only way to fix this is to change the logging here (remove the runtime.HandleError): https://github.com/kubernetes/kubernetes/blob/47908629a36430e154681b2af73fa91190e0f08d/staging/src/k8s.io/client-go/tools/portforward/portforward.go#L212

IMHO that line is unnecessary as the error gets returned to the calling function and gets logged there. I'll try to submit a pull request to to kubernetes to remove this.

**Comment by yvespp** [comment]
This error shows up if ipv6 is disabled, on Linux: `sysctl net.ipv6.conf.all.disable_ipv6=1`

**Comment by kaskavalci** [comment]
Thanks @yvespp. For those who is looking for a solution:

```
sysctl net.ipv6.conf.all.disable_ipv6=0
```

**Comment by erikbsap** [comment]
I actually checked that in the source code. Helm calls an underlying library to first call ipv6 and then ipv4 if it fails. But because it just reraises any error it encounters instead of filtering what is reasonable, the error is listed. It is actually not an error but expected behavior. In most other languages that would be considered a bug.
