### ISSUE TITLE
stable/mysql chart not found 

### ISSUE THREAD

**Issue by sauryadas** [kubernetes/helm#2230]
![image](https://cloud.githubusercontent.com/assets/15387759/24781219/b9671f24-1af2-11e7-8f0d-39f3b6714aaa.png)

**Comment by thomastaylor312** [comment]
Have you tried running `helm repo update`?

**Comment by sauryadas** [comment]
for some reason it wasnt working after a repo update .. i did it again and its working.. thanks... is there a way to prompt users that charts might be out of date and need to be updated?
