### ISSUE TITLE
helm didn't work with k8s 1.6?

### ISSUE THREAD

**Issue by buddy-yao** [kubernetes/helm#2232]
kubernetes version: 1.6.0
kubectl version: 1.6.1
helm version: 2.3.0
```
$> helm ls
Error: the server does not allow access to the requested resource (get configmaps)
```

**Comment by thomastaylor312** [comment]
@buddy-yao This is a current issue with the new RBAC features and how they interact with Helm. I would recommend jumping on the slack channel and asking some of the people there for their workarounds. Also, we are working on full 1.6 support with the 2.4 release, which should be a much shorter development cycle than normal. You can track progress [here](https://github.com/kubernetes/helm/milestone/34)

**Comment by buddy-yao** [comment]
@thomastaylor312 Thanks!

**Comment by ianwalter** [comment]
@buddy-yao Find anything on this? Having the same problem. Thanks.
