### ISSUE TITLE
Docs: Warnings about hook ordering

### ISSUE THREAD

**Issue by eduardobaitello** [kubernetes/helm#2234]
In the [Hooks Section](https://github.com/kubernetes/helm/blob/v2.3.0/docs/charts_hooks.md) there is some warnings "that there are no ordering guarantees about hooks".
Helm v2.3.0 now supports "Hook Weights", which is already covered in the same docs section.

The warnings should be removed or hook execution ordering is not totally guaranteed?

**Comment by technosophos** [comment]
You are correct -- the documentation needs to be updated now that the hook weight system is there.
