### ISSUE TITLE
Helm init without internet connectivity.

### ISSUE THREAD

**Issue by libesz** [kubernetes/helm#2235]
### Use case:
Delivering helm into such environments where stable chart repo is not needed and (BTW) there is no internet connectivity (even no public DNS server is reachable) at all.
### Problem:
Currently helm init is failing in such isolated environments because it can not fetch the stable repo's index.yaml.
```
# helm init -c
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/repository/repositories.yaml
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on xx.xx.xx.xx:53: server misbehaving
```
### Workaround:
Creating an empty ```/root/.helm/repository/repositories.yaml``` file and the other relevant directories prior ```helm init -c``` solves the problem, because in this case helm does not want to reach out to the stable chart repo.
### Solution:
It would be nice to have some command line parameter or other option control to avoid this runtime internet dependency.

If the use case found to be meaningful, please advice on the desired parameter/method to control this and we will implement it.

**Comment by technosophos** [comment]
In Helm 2.3.0: `helm init -c --skip-refresh`

**Comment by libesz** [comment]
Indeed. We tried to figure it out with the 2.2.0 helm CLI, without master/2.3.0 code inspection.
Thanks for the quick response!

**Comment by purnendu15** [comment]
> helm init -c --skip-refresh

Thank you.
