### ISSUE TITLE
helm client behind http proxy issue

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes/helm#2246]
tiller/helm: 2.1.3
Kubernetes: 1.5.4

1. Disable http proxy and run "kubectl version" and "helm list" from **outside of cluster**, everything works fine.
2. Enable http proxy and run "kubectl version", it works fine.
3. Enable http proxy and run "helm list", error:
```
$helm list
Error: forwarding ports: error upgrading connection: error sending request: Post https://rancher.demo.com/r/projects/1a7/kubernetes/api/v1/namespaces/kube-system/pods/tiller-deploy-1323696517-81jm7/portforward: http: server gave HTTP response to HTTPS client
```
I'm using Rancher for K8S, but I don't know it's a rancher issue or helm issue, please help, thanks.

**Comment by thomastaylor312** [comment]
@hiscal2015 Have you tried asking this question in the Helm slack channel? People there are pretty responsive and you might be more likely to get an answer there

**Comment by technosophos** [comment]
Helm needs to be able to send HTTP/2 (gRPC) data across a forwarded port. If `kubectl port-forward` works, so should Helm. But a straight HTTP/1 proxy generally will not.
