### ISSUE TITLE
When the latest gcloud and kubectl, helm cluster authorization sporadically fails

### ISSUE THREAD

**Issue by natetarrh** [kubernetes/helm#2249]
With the [Google Cloud SDK 150.0.0 release](https://cloud.google.com/sdk/docs/release-notes), `kubectl` is configured to use the credentials of the active gcloud account instead of application default credentials. Under the hood, every `kubectl` command generates a short-lived access token.

As a result, when a `kubectl` command hasn't been run for some time, and a helm command is run, the helm command fails with e.g.

    Error: Get https://<REDACTED>/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: error executing access token command "/google-cloud-sdk/bin/gcloud ": exit status 2

This can be resolved by running a `kubectl` command to generate a short-lived access token, and then running the desired helm command.

Helm should generate a short-lived auth token on its own.

Looks like #2237 is a potential duplicate.

**Comment by kuroneko25** [comment]
This may be useful https://github.com/kubernetes/kubernetes/issues/30617 as a reference

**Comment by thomastaylor312** [comment]
Thanks for the link @kuroneko25, there are some possible good workarounds there.

I am going to tag this as a bug for now.

**Comment by hvalle** [comment]
Try any of the following commands, they worked for me:

`gcloud config set container/use_application_default_credentials true`
`export CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true`

You can read on the 150.0.0 [release notes](https://cloud.google.com/sdk/docs/release-notes) for more info.

Hope it helps :)

**Comment by devops1337** [comment]
Previous instructions didn't work for me

**Comment by bacongobbler** [comment]
can anyone bump this thread and let us know if this is still relevant for k8s 1.8/helm 2.7? I haven't seen any activity on this issue since April and Google Cloud SDK's now at 177.0.0.

**Comment by bacongobbler** [comment]
closed as resolved in https://github.com/kubernetes/helm/issues/2277.

**Comment by Davidrjx** [comment]
#2277 seems not works as it can not extend expire validly
