### ISSUE TITLE
helm 2.3.0 Error: grpc: received message length 11972000 exceeding the max size 10485760

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/helm#2261]
Once switched to helm 2.3.0 we started hitting an issue with one of gate jobs which deploy a very large chart. It was working ok with version 2.2.3 though.
It seems 2.3.0 has added some additional info which trigger crossing this limit.

**Comment by sbezverk** [comment]
Change here fixed the issue. Should do PR for this change?

pkg/tiller/server.go

var maxMsgSize = 1024 * 1024 * 20

**Comment by technosophos** [comment]
Closed by #2262

**Comment by sauliuspr** [comment]
Check if you Chart directory does not contain unnecessary large files.
