### ISSUE TITLE
Helm upgrade --wait breaks on 2.3.0 

### ISSUE THREAD

**Issue by mitchhh22** [kubernetes/helm#2263]
I upgraded my helm client and tiller on my local vagrant cluster (1.5.4) and I noticed the --wait flag no longer waits for the deployment to become ready.

After downgrading back to 2.2.3 it waits as expected.

**Comment by technosophos** [comment]
Is this specifically with `Deployment` objects, or with other types as well?

Between 2.2 and 2.3 we introduced this change: https://github.com/kubernetes/helm/pull/2143 I wonder if there is an edge case we missed there. /cc @thomastaylor312

**Comment by technosophos** [comment]
Oh, @thomastaylor312 just pointed me to the documentation (https://github.com/kubernetes/helm/blob/7cbed3f77bd771dfb46c63733c497e8c05225422/docs/using_helm.md#helpful-options-for-installupgraderollback) and suggested that maybe `maxUnavailable` is not set in the Deployment.

**Comment by thomastaylor312** [comment]
@mitchhh22: ☝️ Yep, this is quite possible. Let us know if that is the cause. If it isn't, we can circle back and relabel this

**Comment by mitchhh22** [comment]
@technosophos @thomastaylor312  You are correct, my deployments weren't setting maxUnavailable. As soon as I added that to one less than my replicas it worked as expected with v2.3.1

Thank you!
