### ISSUE TITLE
Helm upgrade should not install pre-release version by default

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/helm#2270]
If semver is followed and a user uses pre-released versions they can be installed over the stable version.

If a user has the following versions and 0.0.5 is currently installed.  A helm upgrade will install `0.1.1-alpha` when I believe most users would prefer `0.1.0` to be installed.  Possibly an additional flag to allow pre-released charts to be an upgrade path.

* 0.1.1-alpha
* 0.1.0
* 0.0.5

**Comment by technosophos** [comment]
I agree that we should (by default) favor stable charts.

Just so I'm clear -- this is when you're doing something like `helm install stable/foo`, right?

**Comment by sstarcher** [comment]
I'm working with private charts.  So in my case `helm install repo/foo` and foo can have tons of versions including versions that were built from pull/merge requests.  Those pull/merge request features will have a VERSION-something and preferably would not be installed/upgraded to unless specifically requested.

**Comment by technosophos** [comment]
Okay. I can't decide whether this is a feature request or a bug.

**Comment by chrislovecnm** [comment]
May we please list this as a bug :)
