### ISSUE TITLE
Provide "latest" url for easy upgrades and installation

### ISSUE THREAD

**Issue by rothgar** [kubernetes/helm#2274]
It would be nice if helm has a $latest url that I could curl to give me whatever the latest stable release is.

minikube and kubectl have this and getting it for helm would be great.

It would also be nice (though not a requirement) if the release had non-tar'd versions of the binaries.

currently the release download is at
https://storage.googleapis.com/kubernetes-helm/helm-v2.3.1-linux-amd64.tar.gz

I would suggest something like
https://storage.googleapis.com/kubernetes-helm/latest/helm-linux-amd64

There may be users who'd also want a beta/alpha release which could be provided similarly.

**Comment by technosophos** [comment]
Added to #1968 for the build system overhaul.
