### ISSUE TITLE
helm test exit codes

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/helm#2275]
On a `helm test` with tests that already exists it outputs ERROR, but the return code is a 0 when a user would expect non-zero.

```
~/.go/src/k8s.io/helm (master) helm test test
RUNNING: test
ERROR: pods "test" already exists

~/.go/src/k8s.io/helm (master) echo $?
0
```

On a `helm test --timeout` when the timeout triggers the response code is a 0 when a user would expect a non-zero.

```
~/.go/src/k8s.io/helm (master) helm test test --timeout=1
RUNNING: test
UNKNOWN: test: timed out waiting for the condition

~/.go/src/k8s.io/helm (master) echo $?
0
```

**Comment by xmik** [comment]
same issues:
  * helm test exit status #2166
  * timeout #2089
