### ISSUE TITLE
helm dependency list hangs if run on large directory

### ISSUE THREAD

**Issue by sushilkm** [kubernetes/helm#2276]
This is what I found, `helm dependency list` if ran without arguments sees current directory as a chart, now the issue is if one runs this command in a big directory by mistake, it gets stuck trying to scan everything under the directory to come up with the message 
```Error: chart metadata (Chart.yaml) missing```

**Comment by technosophos** [comment]
It might be possible to do a quick `os.Stat` on `Chart.yaml` before loading the chart.

This is a fairly easy change to make to `cmd/helm/dependency.go` in the `func (l *dependencyListCmd) run() error` function.
