### ISSUE TITLE
Error on helm init: error executing access token command "/google/google-cloud-sdk/bin/gcloud ": exit status 2

### ISSUE THREAD

**Issue by gorozcoh** [kubernetes/helm#2277]
Hi, helm init fails with error:

`Error: error installing: Post https://104.197.49.162/apis/extensions/v1beta1/namespaces/kube-system/deployments: error executing access token command "/google/google-cloud-sdk/bin/gcloud ": exit status 2`

Patform: Google Cloud Platform, Cluster version is 1.6.0, Environment is Google Cloud Shell, Helm version is 2.3.1.
After manual tiller installation helm version shows: Error: cannot connect to Tiller.
kubectl version shows:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
Thanks in advance

Gus

**Comment by technosophos** [comment]
Is this a duplicated of #2249?

It seems that GKE recently switched to expiring tokens. See that issue for details.

**Comment by jackzampolin** [comment]
This is preventing me from upgrading to the bugfix release. I'm unable to connect to tiller.

**Comment by jackzampolin** [comment]
This is preventing me from upgrading to the bugfix release. I'm unable to connect to tiller.

**Comment by VarunDT** [comment]
I have the same issue..

**Comment by bacongobbler** [comment]
did you both try the instructions in https://github.com/kubernetes/helm/issues/2249#issuecomment-294793552 like @technosophos pointed out, or is there something else going on?

**Comment by jackzampolin** [comment]
@bacongobbler I've tried both of those. Haven't really had the time to dig and and get any debugging tho...

**Comment by Draiken** [comment]
I believe you need to run `gcloud container clusters get-credentials <cluster_name>` again after setting the env variable or setting.

**Comment by jackzampolin** [comment]
@Draiken 🙈 Oh wow. Thank you for that. Figured I had tried doing that already. Works for me now! 🙊

**Comment by devops1337** [comment]
@Draiken's instructions worked, but in my case I had to exit `kubectl proxy` first before it worked.

**Comment by kolpav** [comment]
@Draiken 
It doesn't work for me even on new cluster and new Cloud shell.
```bash
$ terraform apply
$ gcloud config set compute/zone <zone> && gcloud container clusters get-credentials <project_name>
$ curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
$ chmod 700 get_helm.sh
$ ./get_helm.sh
gcloud container clusters get-credentials <project_name>
$ helm init
Error: error installing: Post https://<ip>/apis/extensions/v1beta1/namespaces/kube-system/deployments: error executing access token command "/google/google-cloud-sdk/bin/gcloud ": exit status 2
$ sudo helm init
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:8080: getsockopt: connection refused
```
Can somebody test it on a new cluster please?

**Comment by bacongobbler** [comment]
closing as resolved.

**Comment by Davidrjx** [comment]
@Draiken env or setup you referred to resembles the following screenshot, doesn't it?
![image](https://user-images.githubusercontent.com/4284791/58227552-e80b5c80-7d5d-11e9-8212-ac744fc5f2b5.png)
