### ISSUE TITLE
When we checkout the branch to "85c41ef11ab34b266cf31096826057040a1576b8" (message: * ref(*): kubernetes v1.6  Rebase on kubernetes v1.6) ,is build failed

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/helm#2281]
When we checkout the branch to "85c41ef11ab34b266cf31096826057040a1576b8" (message: * ref(*): kubernetes v1.6  Rebase on kubernetes v1.6) ,is build failed

the follow is the error:
warning: GOPATH set to GOROOT (/data/go/) has no effect
../../pkg/kube/wait.go:31:2: cannot find package "k8s.io/kubernetes/pkg/client/clientset_generated/clientset" in any of:
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (vendor tree)
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (from $GOROOT)
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (from $GOPATH)
../../pkg/kube/wait.go:32:2: cannot find package "k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1" in any of:
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1 (vendor tree)
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1 (from $GOROOT)
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1 (from $GOPATH)
../../pkg/kube/wait.go:33:2: cannot find package "k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1" in any of:
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1 (vendor tree)
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1 (from $GOROOT)
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1 (from $GOPATH)
../../pkg/kube/client.go:51:2: cannot find package "k8s.io/kubernetes/pkg/printers" in any of:
	/data/go/src/vendor/k8s.io/kubernetes/pkg/printers (vendor tree)
	/data/go/src/vendor/k8s.io/kubernetes/pkg/printers
	/data/go/src/k8s.io/kubernetes/pkg/printers (from $GOROOT)
	/data/go/src/k8s.io/kubernetes/pkg/printers (from $GOPATH)

How can solve the problem? when we checkout the kubernetes to the newest, the error is also.

**Comment by technosophos** [comment]
Run `make bootstrap` again.

**Comment by yan234280533** [comment]
Many thank and sorry to trouble you again.

I have do make bootstrap build  cmd in helm directory, but when I build again ,is error again

../../pkg/kube/wait.go:31:2: cannot find package "k8s.io/kubernetes/pkg/client/clientset_generated/clientset" in any of:
	/data/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (vendor tree)
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset
	/data/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (from $GOROOT)
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (from $GOPATH)
../../pkg/kube/wait.go:32:2: cannot find package "k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1" in any of:
	/data/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1 (vendor tree)
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1
	/data/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1 (from $GOROOT)
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1 (from $GOPATH)
../../pkg/kube/wait.go:33:2: cannot find package "k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1" in any of:
	/data/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1 (vendor tree)
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1
	/data/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1
	/data/go/src/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1 (from $GOROOT)
	/data/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/extensions/v1beta1 (from $GOPATH)
../../pkg/kube/client.go:51:2: cannot find package "k8s.io/kubernetes/pkg/printers" in any of:
	/data/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/printers (vendor tree)
	/data/go/src/vendor/k8s.io/kubernetes/pkg/printers
	/data/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/printers
	/data/go/src/vendor/k8s.io/kubernetes/pkg/printers
	/data/go/src/k8s.io/kubernetes/pkg/printers (from $GOROOT)
	/data/go/src/k8s.io/kubernetes/pkg/printers (from $GOPATH)

**Comment by yan234280533** [comment]
It is may glide log: 

(As the x project is not available now , I download it using github from  https://github.com/golang url)

[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally cloud.google.com/go 3b1ae45394a234c385be014e9a488f2bb6eef821!
[INFO]	--> Found desired version locally github.com/aokoli/goutils 9c37978a95bd5c709a15883b6242714ea6709e64!
[INFO]	--> Found desired version locally github.com/asaskevich/govalidator 7664702784775e51966f0885f5cd27435916517b!
[INFO]	--> Found desired version locally github.com/Azure/go-ansiterm 70b2c90b260171e829f1ebd7c17f600c11858dbe!
[INFO]	--> Found desired version locally github.com/chai2010/gettext-go c6fed771bfd517099caf0f7a961671fa8ed08723!
[INFO]	--> Found desired version locally github.com/coreos/go-oidc be73733bb8cc830d0205609b95d125215f8e9c70!
[INFO]	--> Found desired version locally github.com/coreos/pkg fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8!
[INFO]	--> Found desired version locally github.com/cpuguy83/go-md2man a65d4d2de4d5f7c74868dfa9b202a3c8be315aaa!
[INFO]	--> Found desired version locally github.com/davecgh/go-spew 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d!
[INFO]	--> Found desired version locally github.com/dgrijalva/jwt-go 01aeca54ebda6e0fbfafd0a524d234159c05ec20!
[INFO]	--> Found desired version locally github.com/docker/distribution cd27f179f2c10c5d300e6d09025b538c475b0d51!
[INFO]	--> Found desired version locally github.com/docker/docker b9f10c951893f9a00865890a5232e85d770c1087!
[INFO]	--> Found desired version locally github.com/docker/engine-api dea108d3aa0c67d7162a3fd8aa65f38a430019fd!
[INFO]	--> Found desired version locally github.com/docker/go-connections f549a9393d05688dff0992ef3efd8bbe6c628aeb!
[INFO]	--> Found desired version locally github.com/docker/go-units e30f1e79f3cd72542f2026ceec18d3bd67ab859c!
[INFO]	--> Found desired version locally github.com/docker/spdystream 449fdfce4d962303d702fec724ef0ad181c92528!
[INFO]	--> Found desired version locally github.com/emicklei/go-restful 09691a3b6378b740595c1002f40c34dd5f218a22!
[INFO]	--> Found desired version locally github.com/evanphx/json-patch ba18e35c5c1b36ef6334cad706eb681153d2d379!
[INFO]	--> Found desired version locally github.com/exponent-io/jsonpath d6023ce2651d8eafb5c75bb0c7167536102ec9f5!
[INFO]	--> Found desired version locally github.com/facebookgo/symwalk 42004b9f322246749dd73ad71008b1f3160c0052!
[INFO]	--> Found desired version locally github.com/ghodss/yaml 73d445a93680fa1a78ae23a5839bad48f32ba1ee!
[INFO]	--> Found desired version locally github.com/go-openapi/jsonpointer 46af16f9f7b149af66e5d1bd010e3574dc06de98!
[INFO]	--> Found desired version locally github.com/go-openapi/jsonreference 13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272!
[INFO]	--> Found desired version locally github.com/go-openapi/spec 6aced65f8501fe1217321abf0749d354824ba2ff!
[INFO]	--> Found desired version locally github.com/go-openapi/swag 1d0bd113de87027671077d3c71eb3ac5d7dbba72!
[INFO]	--> Found desired version locally github.com/gobwas/glob bea32b9cd2d6f55753d94a28e959b13f0244797a!
[INFO]	--> Found desired version locally github.com/gogo/protobuf e18d7aa8f8c624c915db340349aad4c49b10d173!
[INFO]	--> Found desired version locally github.com/golang/glog 44145f04b68cf362d9c4df2182967c2275eaefed!
[INFO]	--> Found desired version locally github.com/golang/groupcache 02826c3e79038b59d737d3b1c0a1d937f71a4433!
[INFO]	--> Found desired version locally github.com/golang/protobuf df1d3ca07d2d07bba352d5b73c4313b4e2a6203e!
[INFO]	--> Found desired version locally github.com/google/gofuzz 44d81051d367757e1c7c6a5a86423ece9afcf63c!
[INFO]	--> Found desired version locally github.com/gosuri/uitable 36ee7e946282a3fb1cfecd476ddc9b35d8847e42!
[INFO]	--> Found desired version locally github.com/howeyc/gopass 3ca23474a7c7203e0a0a070fd33508f6efdb9b3d!
[INFO]	--> Found desired version locally github.com/imdario/mergo 6633656539c1639d9d78127b7d47c622b5d7b6dc!
[INFO]	--> Found desired version locally github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75!
[INFO]	--> Found desired version locally github.com/jonboulle/clockwork 72f9bd7c4e0c2a40055ab3d0f09654f730cce982!
[INFO]	--> Found desired version locally github.com/juju/ratelimit 77ed1c8a01217656d2080ad51981f6e99adaa177!
[INFO]	--> Found desired version locally github.com/mailru/easyjson d5b7844b561a7bc640052f1b935f7b800330d7e0!
[INFO]	--> Found desired version locally github.com/Masterminds/semver 3f0ab6d4ab4bed1c61caf056b63a6e62190c7801!
[INFO]	--> Found desired version locally github.com/Masterminds/sprig 23597e5f6ad0e4d590e71314bfd0251a4a3cf849!
[INFO]	--> Found desired version locally github.com/Masterminds/vcs 795e20f901c3d561de52811fb3488a2cb2c8588b!
[INFO]	--> Found desired version locally github.com/mattn/go-runewidth d6bea18f789704b5f83375793155289da36a3c7f!
[INFO]	--> Found desired version locally github.com/mitchellh/go-wordwrap ad45545899c7b13c020ea92b2072220eefad42b8!
[INFO]	--> Found desired version locally github.com/naoina/go-stringutil 6b638e95a32d0c1131db0e7fe83775cbea4a0d0b!
[INFO]	--> Found desired version locally github.com/naoina/toml 751171607256bb66e64c9f0220c00662420c38e9!
[INFO]	--> Found desired version locally github.com/pborman/uuid ca53cad383cad2479bbba7f7a1a05797ec1386e4!
[INFO]	--> Found desired version locally github.com/PuerkitoBio/purell 8a290539e2e8629dbc4e6bad948158f790ec31f4!
[INFO]	--> Found desired version locally github.com/PuerkitoBio/urlesc 5bd2802263f21d8788851d5305584c82a5c75d7e!
[INFO]	--> Found desired version locally github.com/russross/blackfriday 300106c228d52c8941d4b3de6054a6062a86dda3!
[INFO]	--> Found desired version locally github.com/satori/go.uuid 879c5887cd475cd7864858769793b2ceb0d44feb!
[INFO]	--> Found desired version locally github.com/shurcooL/sanitized_anchor_name 10ef21a441db47d8b13ebcc5fd2310f636973c77!
[INFO]	--> Found desired version locally github.com/Sirupsen/logrus 51fe59aca108dc5680109e7b2051cbdcfa5a253c!
[INFO]	--> Found desired version locally github.com/spf13/cobra f62e98d28ab7ad31d707ba837a966378465c7b57!
[INFO]	--> Found desired version locally github.com/spf13/pflag 9ff6c6923cfffbcd502984b8e0c80539a94968b7!
[INFO]	--> Found desired version locally github.com/technosophos/moniker 9f956786b91d9786ca11aa5be6104542fa911546!
[INFO]	--> Found desired version locally github.com/ugorji/go ded73eae5db7e7a0ef6f55aace87a2873c5d2b74!
[INFO]	--> Found desired version locally google.golang.org/appengine 4f7eeb5305a4ba1966344836ba4af9996b7b4e05!
[INFO]	--> Found desired version locally google.golang.org/grpc b7f1379d3cbbbeb2ca3405852012e237aa05459e!
[INFO]	--> Found desired version locally gopkg.in/inf.v0 3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4!
[INFO]	--> Found desired version locally gopkg.in/yaml.v2 a83829b6f1293c91addabc89d0571c246397bbf4!
[INFO]	--> Found desired version locally k8s.io/apimachinery 20e10d54608f05c3059443a6c0afb9979641e88d!
[INFO]	--> Found desired version locally k8s.io/apiserver dcf548fbe26dacc3a78d18e1135adf17006552e9!
[INFO]	--> Found desired version locally k8s.io/client-go dabf37f5df16a224729883d9f616ce4a2c282e95!
[INFO]	--> Found desired version locally k8s.io/kubernetes b0b7a323cc5a4a2019b2e9520c21c7830b7f708e!
[INFO]	--> Found desired version locally vbom.ml/util db5cfe13f5cc80a4990d98e2e1b0707a4d1a5394!
[INFO]	--> Fetching golang.org/x/net
[INFO]	--> Fetching golang.org/x/oauth2
[INFO]	--> Fetching golang.org/x/crypto
[INFO]	--> Fetching golang.org/x/sys
[INFO]	--> Fetching golang.org/x/text
[WARN]	Unable to checkout golang.org/x/oauth2
[ERROR]	Update failed for golang.org/x/oauth2: Unable to get repository
[WARN]	Unable to checkout golang.org/x/text
[ERROR]	Update failed for golang.org/x/text: Unable to get repository
[WARN]	Unable to checkout golang.org/x/sys
[ERROR]	Update failed for golang.org/x/sys: Unable to get repository
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Unable to get repository
[WARN]	Unable to checkout golang.org/x/crypto
[ERROR]	Update failed for golang.org/x/crypto: Unable to get repository
[ERROR]	Failed to install: Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repositor

**Comment by yan234280533** [comment]
I try again:  

checkout  apimachinery to  : commit 72e51762028fdf72f1a20e59bedceece02a425c6
checkout  kubernetes to : commit b0b7a323cc5a4a2019b2e9520c21c7830b7f708e
checkout client-go to : commit  dabf37f5df16a224729883d9f616ce4a2c282e95
checkout apiserver to : commit  dcf548fbe26dacc3a78d18e1135adf17006552e9

**but is failed again!!!!**

the error log is :
k8s.io/kubernetes/pkg/client/unversioned/remotecommand
# k8s.io/helm/pkg/storage/driver
../../pkg/storage/driver/cfgmaps.go:71: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions) as type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions in argument to cfgmaps.impl.Get
../../pkg/storage/driver/cfgmaps.go:97: cannot use opts (type "k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions in argument to cfgmaps.impl.List
../../pkg/storage/driver/cfgmaps.go:133: cannot use opts (type "k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions in argument to cfgmaps.impl.List
../../pkg/storage/driver/cfgmaps.go:218: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions literal (type *"k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions) as type *"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions in argument to cfgmaps.impl.Delete
../../pkg/storage/driver/cfgmaps.go:261: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
k8s.io/helm/pkg/proto/hapi/services

**Comment by technosophos** [comment]
At the end of the `make bootstrap` there is a copy command that moves around those libraries. You might need to run that command. /cc @adamreese

**Comment by technosophos** [comment]
Oops... it's now in `scripts/setyupApiMachinery.sh`

**Comment by yan234280533** [comment]
I  mkdir the an directory /vendor/k8s.io and run the scripts/setupApiMachinery.sh command.

But when I build again . it  error again. can you help me , I am so sorry to trouble you.

@technosophos   @adamreese 

# k8s.io/helm/pkg/storage/driver
../../pkg/storage/driver/cfgmaps.go:71: cannot use "k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions literal (type "k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions) as type "k8s.io/helm/vendor/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions in argument to cfgmaps.impl.Get
../../pkg/storage/driver/cfgmaps.go:97: cannot use opts (type "k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as type "k8s.io/helm/vendor/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions in argument to cfgmaps.impl.List
../../pkg/storage/driver/cfgmaps.go:133: cannot use opts (type "k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as type "k8s.io/helm/vendor/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions in argument to cfgmaps.impl.List
../../pkg/storage/driver/cfgmaps.go:218: cannot use "k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions literal (type *"k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions) as type *"k8s.io/helm/vendor/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".DeleteOptions in argument to cfgmaps.impl.Delete
../../pkg/storage/driver/cfgmaps.go:261: cannot use "k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "k8s.io/helm/vendor/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value

root@VM-132-244-ubuntu:/data/go/src/k8s.io/helm/vendor/k8s.io# ls 
apimachinery  apiserver  client-go  kube-aggregator  kubernetes

**Comment by adamreese** [comment]
looks like it is still trying to access a nested vendor.  `k8s.io/helm/VENDOR/k8s.io/kubernetes/VENDOR/k8s.io/apimachinery/pkg/apis/meta/v1`

try running `rm -rf ./vendor/k8s.io && make bootstrap`

**Comment by yan234280533** [comment]
@adamreese  I  hava try to do it.  Why it the error coming , is so  strangely, so  strangely

**Comment by yan234280533** [comment]
When i run make bootsrap : 
it show the k8s library 's commit is :+1:  **Is it the right commit to build the new helm?**

[INFO]	--> Found desired version locally k8s.io/apimachinery 20e10d54608f05c3059443a6c0afb9979641e88d!
[INFO]	--> Found desired version locally k8s.io/apiserver dcf548fbe26dacc3a78d18e1135adf17006552e9!
[INFO]	--> Found desired version locally k8s.io/client-go dabf37f5df16a224729883d9f616ce4a2c282e95!
[INFO]	--> Found desired version locally k8s.io/kubernetes b0b7a323cc5a4a2019b2e9520c21c7830b7f708e!


@adamreese  **Can you give some information of the k8s's library commit you use, I checkout my 

 k8s's library  commit the same as you, to hava try again .  It's so sorry to trouble you, so many thanks.**

**Comment by adamreese** [comment]
it is because the git repo at k8s.io/apimachinery is incompatible with v1.6.  Also k8s.io/kubernetes checks in there vendor directory which causes all kinds of weird issues with import paths. `make bootstrap` cleans up the vendor directory leaving compatible apis.

**Comment by yan234280533** [comment]
@adamreese  what the commit id of kubernetes you checkout  ? I checkout the same commitId of  kubernetes  as you and have a try.

**Comment by yan234280533** [comment]
my env :  make bootstrap  have some cann't download the code ,it will hang in  "Fecture golang.org/x/sys"

so I must download some library  manual.

**Comment by yan234280533** [comment]
I do the following experiment: 

step1: I delete all k8s libraries in my vm. 

step2: I git clone helm, and checkout it to '0ab38a998c097a9227dc7ff022732a78c9ada922' (Merge pull request #2248 from adamreese/ref/kube-v1.6)

step 3: I  mkdir vendor, and mkdir k8s.io in vendor, then I git clone kubernetes  , and checkout to  b0b7a323cc5a4a2019b2e9520c21c7830b7f708e

step4:  I run the cmd : ./scripts/setup-apimachinery.sh , it copy  apimachinery library from kubernetes 

step5: I build helm, but it failed the same, the error log is the same as before.

so I think , I used the wrong commitid  kubernetes  library,  what the commit id of kubernetes you checkout ? I checkout the same commitId of kubernetes as you and have a try.  @adamreese 

So sorry to trouble you and thank you many and many.

**Comment by technosophos** [comment]
This is not likely to work:

> step 3: I mkdir vendor, and mkdir k8s.io in vendor, then I git clone kubernetes , and checkout to b0b7a323cc5a4a2019b2e9520c21c7830b7f708e

You need to use Glide to do that. (You may have to run `glide up` twice)

If you do not use Glide, you'll have to do all of the dependency management on your own. We cannot help with that.

**Comment by yan234280533** [comment]
@technosophos  many thanks, many thanks.

I slove the problem, by rm -rf the vendor directory in  kubernetes. I think is a problem of "go build".

the  experiment setup is:

I do the following experiment:

step1: I delete all k8s libraries in my vm.

step2: I git clone helm, and checkout it to '0ab38a998c097a9227dc7ff022732a78c9ada922' (Merge pull request #2248 from adamreese/ref/kube-v1.6)

step 3: I mkdir vendor, and mkdir k8s.io in vendor, then I git clone kubernetes , and checkout to b0b7a323cc5a4a2019b2e9520c21c7830b7f708e

step4: I run the cmd : ./scripts/setup-apimachinery.sh , it copy apimachinery library from kubernetes

step5：then I rm the helm/vendor/k8s.io/kubernetes /vendor 

Then build the helm is ok.

**Comment by technosophos** [comment]
Closing this since @yan234280533 has figured out a fix.
