### ISSUE TITLE
Helm Plugin Discovery

### ISSUE THREAD

**Issue by spiddy** [kubernetes/helm#2284]
On #1977 the helm plugin management was addressed, but currently there is no way to discover existing helm plugins.

An easy fix for the moment would be to add a wiki page that gathers existing plugins.

This will help to boost visibility of existing plugins and avoid replicated work.

I got here while trying to find if there exist a `helm s3` plugin for auth yet or not (which afaik it doesn't)

**Comment by spiddy** [comment]
helm s3 referenced [here](https://github.com/kubernetes/helm/issues/1038#issuecomment-268068410)

**Comment by technosophos** [comment]
There is a list in docs/related.md. But that list is probably incomplete right now.

**Comment by spiddy** [comment]
That's exactly what I was looking for. Not sure why I missed that section. Maybe I was expecting it do be in docs/plugins.md section.

**Comment by spiddy** [comment]
Maybe adding a reference to this at the end of plugins section will help redirect there.
