### ISSUE TITLE
Rollback ignores `--recreate-pods`

### ISSUE THREAD

**Issue by peay** [kubernetes/helm#2285]
I believe there is some wiring missing. Fixed in PR for #1958, but filing for reference. cc @thomastaylor312, let me know if you prefer a separate PR for this one line change.

From https://github.com/kubernetes/helm/blob/master/pkg/helm/client.go -- rollback does not set the `Recreate` field of the request:

```.go
// RollbackRelease rolls back a release to the previous version
func (h *Client) RollbackRelease(rlsName string, opts ...RollbackOption) (*rls.RollbackReleaseResponse, error) {
...
	req := &h.opts.rollbackReq
	req.DisableHooks = h.opts.disableHooks
	req.DryRun = h.opts.dryRun
	req.Name = rlsName
	ctx := NewContext()
...
}
```

This seems done correctly for update:

```.go
// UpdateReleaseFromChart updates a release to a new/different chart
func (h *Client) UpdateReleaseFromChart(rlsName string, chart *chart.Chart, opts ...UpdateOption) (*rls.UpdateReleaseResponse, error) {
...
	req.Recreate = h.opts.recreate //<-- OK
....
}
```

**Comment by thomastaylor312** [comment]
Thanks for finding this @peay. If I think it needs to be split out when I review your PR, I'll let you know. For now, let's just leave it in.

**Comment by peay** [comment]
@thomastaylor312 fix for this is still included in #2280, so merging that PR would close this issue as well.

**Comment by thomastaylor312** [comment]
I'll make sure to close this as well. Thank you for bringing it back up

**Comment by peay** [comment]
@thomastaylor312 I believe this can be closed now

**Comment by thomastaylor312** [comment]
@peay Thank you for pinging me on this. I'll close it
