### ISSUE TITLE
Helm into a Container?

### ISSUE THREAD

**Issue by adawolfs** [kubernetes/helm#2292]
Hello, I'm trying to provide a full containerized environment with kubernetes, helm and a REST service to deploy my apps and I want to know if there is a helm api to do it or an already created docker image with an integration of helm and kubernetes

Regards

**Comment by bacongobbler** [comment]
There's `kubectl exec` which will allow one to exec into a container. Is that what you're looking for?

**Comment by wstrange** [comment]
You can add the helm and kubectl binaries to a docker container, and run helm commands from within the cluster (I have tried this and it works)

**Comment by adawolfs** [comment]
Thanks @wstrange I've created my implementation taking as base the image "google/cloud-sdk", I'll post my Dockerfile for future references

`FROM google/cloud-sdk

ENV VERSION v2.1.3
ENV FILENAME helm-${VERSION}-linux-amd64.tar.gz

WORKDIR /

ADD http://storage.googleapis.com/kubernetes-helm/${FILENAME} /tmp

RUN tar -zxvf /tmp/${FILENAME} -C /tmp \
  && mv /tmp/linux-amd64/helm /bin/helm \
  && rm -rf /tmp

ADD gcloud /.config/gcloud
CMD ["/bin/bash"]`
