### ISSUE TITLE
While installing charts, error 'function toYaml not defined' and 'function trimSuffix not defined' 

### ISSUE THREAD

**Issue by wavermartijn** [kubernetes/helm#2293]
I've installed the helm-v2.2.1-linux-arm on my raspberry pi cluster and installation seems to work well. However, when trying to install stable charts like stable/mongodb, stable/joomla, stable/postgresql error messages pop up like:

For mongodb:
Error: parse error in "mongodb/templates/_helpers.tpl": template: mongodb/templates/_helpers.tpl:6: function "trimSuffix" not defined

for joomla:
Error: parse error in "joomla/charts/mariadb/templates/deployment.yaml": template: joomla/charts/mariadb/templates/deployment.yaml:73: function "toYaml" not defined

seems like some libraries are missing somewhere.

**Comment by technosophos** [comment]
Can you upgrade to Helm 2.3.0?

I believe those two functions were added later than 2.2.1.

**Comment by wavermartijn** [comment]
I just upgraded to 2.3.1. But for some reason messages are still appearing. 
helm version returns:
$ helm version
Client: &version.Version{SemVer:"v2.3.1", GitCommit:"32562a3040bb5ca690339b9840b6f60f8ce25da4", GitTreeState:"clean"}
Error: server is too old to know its version

Kubernetes logs show this as last message:
Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.3.1"

**Comment by bacongobbler** [comment]
closing this as inactive. Please re-open this issue if you're still seeing this. Thanks!
