### ISSUE TITLE
Error: could not find a ready tiller pod

### ISSUE THREAD

**Issue by lixiaobing1** [kubernetes/helm#2295]
when using helm to deploy k8s: https://docs.openstack.org/developer/kolla-kubernetes/deployment-guide.html, execute "helm install --debug kolla-kubernetes/helm/service/mariadb --namespace kolla --name mariadb --values ./cloud.yaml", an error: Error: could not find a ready tiller pod, so when is this tiller pod created?

**Comment by lixiaobing1** [comment]
why tiller has been installed but can't be found?

helm init
$HELM_HOME has been configured at /root/.helm.
Warning: Tiller is already installed in the cluster.

khelm install --debug kolla-kubernetes/helm/service/mariadb --namespce kolla --name mariadb --values ./cloud.yaml
Error: could not find a ready tiller pod

**Comment by technosophos** [comment]
Can you run:

```
$ kubectl get pods --namespace kube-system
```

Look for a pod named `tiller-deployment-XXXXX`

Run:

```
$ kubectl logs --namespace kube-system tiller-deployment-XXXX
```

**Comment by lixiaobing1** [comment]
kubectl logs --namespace kube-system tiller-deploy-1332173772-fgl21
Error from server (BadRequest): container "tiller" in pod "tiller-deploy-1332173772-fgl21" is waiting to start: ContainerCreating

**Comment by bacongobbler** [comment]
Can you run

```
kubectl --namespace kube-system describe tiller-deploy-1332173772-fgl21
```

to fetch more information?

**Comment by lixiaobing1** [comment]
root@ubuntu:/home/zte/share# kubectl get pods --namespace kube-system
NAME                             READY     STATUS              RESTARTS   AGE
tiller-deploy-1332173772-fgl21   0/1       ContainerCreating   0          17h
root@ubuntu:/home/zte/share# kubectl --namespace kube-system describe tiller-deploy-1332173772-fgl21
the server doesn't have a resource type "tiller-deploy-1332173772-fgl21"

**Comment by bacongobbler** [comment]
sorry, forgot a `pod` in there. The full command would be `kubectl --namespace kube-system describe pod tiller-deploy-1332173772-fgl21`.

**Comment by lixiaobing1** [comment]
kubectl --namespace kube-system describe pod tiller-deploy-1332173772-fgl21
Name:		tiller-deploy-1332173772-fgl21
Namespace:	kube-system
Node:		10.20.8.12/10.20.8.12
Start Time:	Wed, 19 Apr 2017 04:38:20 -0400
Labels:		app=helm
		name=tiller
		pod-template-hash=1332173772
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-1332173772","uid":"8afa9b7f-24db-11e7-b1ed-4c0...
Status:		Pending
IP:		
Controllers:	ReplicaSet/tiller-deploy-1332173772
Containers:
  tiller:
    Container ID:	
    Image:		gcr.io/kubernetes-helm/tiller:v2.3.1
    Image ID:		
    Port:		44134/TCP
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Liveness:		http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:	kube-system
    Mounts:		<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:	<none>
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type	Reason		Message
  ---------	--------	-----	----			-------------	--------------		-------
  19h		6h		31	kubelet, 10.20.8.12			Warning	FailedSync	(events with common reason combined)
  5h		5h		1	kubelet, 10.20.8.12			Warning	FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "tiller-deploy-1332173772-fgl21_kube-system(8afe01f0-24db-11e7-b1ed-4c09b4b0c553)" with CreatePodSandboxError: "CreatePodSandbox for pod \"tiller-deploy-1332173772-fgl21_kube-system(8afe01f0-24db-11e7-b1ed-4c09b4b0c553)\" failed: rpc error: code = 4 desc = context deadline exceeded"

  23h	5h	348	kubelet, 10.20.8.12		Warning	FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "tiller-deploy-1332173772-fgl21_kube-system(8afe01f0-24db-11e7-b1ed-4c09b4b0c553)" with CreatePodSandboxError: "CreatePodSandbox for pod \"tiller-deploy-1332173772-fgl21_kube-system(8afe01f0-24db-11e7-b1ed-4c09b4b0c553)\" failed: rpc error: code = 2 desc = unable to pull sandbox image \"gcr.io/google_containers/pause\": Error response from daemon: {\"message\":\"Get https://gcr.io/v1/_ping: dial tcp: i/o timeout\"}"

  23h	5h	389	kubelet, 10.20.8.12		Warning	MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  1h	1h	2	kubelet, 10.20.8.12		Warning	FailedSync		Error syncing pod, skipping: failed to "CreatePodSandbox" for "tiller-deploy-1332173772-fgl21_kube-system(8afe01f0-24db-11e7-b1ed-4c09b4b0c553)" with CreatePodSandboxError: "CreatePodSandbox for pod \"tiller-deploy-1332173772-fgl21_kube-system(8afe01f0-24db-11e7-b1ed-4c09b4b0c553)\" failed: rpc error: code = 2 desc = unable to pull sandbox image \"gcr.io/google_containers/pause\": Error response from daemon: {\"message\":\"Get https://gcr.io/v1/_ping: dial tcp: i/o timeout\"}"

  1h	1h	3	kubelet, 10.20.8.12		Warning	MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  1m	1m	1	kubelet, 10.20.8.12		Warning	MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.

**Comment by yan234280533** [comment]
I come across the same error, when I run the following tiller container, it run crashed.
gcr.io/kubernetes-helm/tiller          v2.3.1              38527daf791d        6 days ago          56MB
gcr.io/kubernetes-helm/tiller          v2.3.0              24d2d8f25332        13 days ago         56MB

Finalling, I was copy a tiller binary from the  tiller container, and start it from the vm, it run ok. But the problem i not find the solution

**Comment by lixiaobing1** [comment]
now the question is:
unable to pull sandbox image "gcr.io/google_containers/pause": Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp: i/o timeout"}"
so, how can i modify helm to get pause image from local docker respo?

**Comment by lixiaobing1** [comment]
ok, the question about the title has disappeared, close it ,thx.

**Comment by rushins** [comment]
i had the same probelm ...what is the solution now.

**Comment by bacongobbler** [comment]
@rushins can you show the output of the commands shown in https://github.com/kubernetes/helm/issues/2295#issuecomment-295475911 and https://github.com/kubernetes/helm/issues/2295#issuecomment-295542997? Those would be how to determine if the tiller pod is running or not.

**Comment by kazazuz** [comment]
burner@kube:~$ kubectl --namespace kube-system describe pod tiller-deploy-5b9d65c7f-qncnh
Name:           tiller-deploy-5b9d65c7f-qncnh
Namespace:      kube-system
Node:           <none>
Labels:         app=helm
                name=tiller
                pod-template-hash=165821739
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-5b9d65c7f","uid":"47627b2c-d128-11e7-9a56-0251...
Status:         Pending
IP:
Created By:     ReplicaSet/tiller-deploy-5b9d65c7f
Controlled By:  ReplicaSet/tiller-deploy-5b9d65c7f
Containers:
  tiller:
    Image:      gcr.io/kubernetes-helm/tiller:v2.7.2
    Port:       44134/TCP
    Liveness:   http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2rqcg (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  default-token-2rqcg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2rqcg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  2m (x57 over 17m)  default-scheduler  No nodes are available that match all of the predicates: NodeUnschedulable (1), PodToleratesNodeTaints (1).

**Comment by bacongobbler** [comment]
@kazazuz here's the important error message:

> Warning FailedScheduling 2m (x57 over 17m) default-scheduler No nodes are available that match all of the predicates: NodeUnschedulable (1), PodToleratesNodeTaints (1).

This is Kubernetes flipping belly over. Check and see if your nodes are in a healthy state with `kubectl describe nodes`.

**Comment by recolic** [comment]
I have a similar problem. Here's a screenshot
![screenshot](https://recolic.net/tmp/snap-0209-190757.png)

**Comment by BravoMao** [comment]
i figure this out with a `helm init` to install Tiller into k8s cluster

**Comment by macknight** [comment]
what you've done with more detail? @yan234280533  @lixiaobing1 , I am using ubuntu in virutial box and is installing helm.

**Comment by macknight** [comment]
I am having the same problem showing failed scheduling cause tiller always pending. @bacongobbler

**Comment by sminodonte** [comment]
same problem, tiller is always pending

**Comment by bacongobbler** [comment]
Check `kubectl -n kube-system describe pod <tiller pod name>`?

**Comment by ezspamat** [comment]
I'm having the same. I have set up a two node cluster on aws and have used wave net CNI. When I try to install helm, I notice that tiller pod is stuck in "creatingcontainer"  status. 
```
ubuntu@ip-172-31-38-189:/$ sudo helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: could not find a ready tiller pod
```

```
```
ubuntu@ip-172-31-38-189:/$ kubectl get nodes
NAME               STATUS   ROLES    AGE   VERSION
ip-172-31-38-189   Ready    master   17m   v1.12.2
ip-172-31-44-24    Ready    <none>   14m   v1.12.2
```

ubuntu@ip-172-31-38-189:/$ kubectl get pods -n kube-system
NAME                                       READY   STATUS              RESTARTS   AGE
coredns-576cbf47c7-7pfcz                   1/1     Running             0          18m
coredns-576cbf47c7-ghvrq                   1/1     Running             0          18m
etcd-ip-172-31-38-189                      1/1     Running             0          17m
kube-apiserver-ip-172-31-38-189            1/1     Running             0          17m
kube-controller-manager-ip-172-31-38-189   1/1     Running             0          17m
kube-proxy-vrhsn                           1/1     Running             0          18m
kube-proxy-wkfxm                           1/1     Running             0          15m
kube-scheduler-ip-172-31-38-189            1/1     Running             0          17m
tiller-deploy-6f6fd74b68-9npkw             0/1     ContainerCreating   0          14m
weave-net-9cztw                            2/2     Running             0          15m
weave-net-rnh2h                            2/2     Running             0          16m
```
```
ubuntu@ip-172-31-38-189:/$ kubectl describe pod tiller-deploy-6f6fd74b68-9npkw -n kube-system
Name:               tiller-deploy-6f6fd74b68-9npkw
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               ip-172-31-44-24/172.31.44.24
Start Time:         Wed, 14 Nov 2018 20:40:16 +0000
Labels:             app=helm
                    name=tiller
                    pod-template-hash=6f6fd74b68
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      ReplicaSet/tiller-deploy-6f6fd74b68
Containers:
  tiller:
    Container ID:
    Image:          gcr.io/kubernetes-helm/tiller:v2.11.0
    Image ID:
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-52wq2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tiller-token-52wq2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-52wq2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                 From                      Message
  ----     ------                  ----                ----                      -------
  Normal   Scheduled               15m                 default-scheduler         Successfully assigned kube-system/tiller-deploy-6f6fd74b68-9npkw to ip-172-31-44-24
  Warning  FailedCreatePodSandBox  3m7s (x3 over 11m)  kubelet, ip-172-31-44-24  Failed create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   SandboxChanged          3m7s (x3 over 11m)  kubelet, ip-172-31-44-24  Pod sandbox changed, it will be killed and re-created.
```
```
ubuntu@ip-172-31-38-189:/$ kubectl logs -n kube-system tiller-deploy-6f6fd74b68-9npkw
Error from server (BadRequest): container "tiller" in pod "tiller-deploy-6f6fd74b68-9npkw" is waiting to start: ContainerCreating
```

**Comment by NitinRanjan** [comment]
I am also getting the same error

`kubectl describe pod tiller-deploy-6f8d4f6c9c-cbp8s --namespace=kube-system
Name:               tiller-deploy-6f8d4f6c9c-cbp8s
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               k8s-worker1/xxx.xxx.xxx.xxx
Start Time:         Wed, 26 Dec 2018 16:50:55 +0530
Labels:             app=helm
                    name=tiller
                    pod-template-hash=6f8d4f6c9c
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      ReplicaSet/tiller-deploy-6f8d4f6c9c
Containers:
  tiller:
    Container ID:
    Image:          gcr.io/kubernetes-helm/tiller:v2.12.1
    Image ID:
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fgvtf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-fgvtf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fgvtf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                    From                  Message
  ----     ------                  ----                   ----                  -------
  Normal   Scheduled               6m29s                  default-scheduler     Successfully assigned kube-system/tiller-deploy-6f8d4f6c9c-cbp8s to k8s-worker1
  Warning  FailedCreatePodSandBox  6m28s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b032e4748702be6e5d0feb58fee4d49cb4efe7e3472fba8223881b63eaf24cfd" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m27s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3faf59400eab7b17bb17351f12821739dc039da188f44753723cfa351dd52ead" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m26s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "8b59515335ffad6bf8e79f2134bfe4f8fb164b2865887168b1fb7c753a5afcff" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m26s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ddebeb3c9f930c2c4ac7ed3b5553fcf710951fe5e241ced5238a19358d102877" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m25s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "981f5fd1db99b42ae7d434a2b11a0d7eeb4cb18d4b5127bf0cd9c4264228d5c4" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m24s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "11806a93283a02193c0e479e723e69f558b43009e4c9e0af7d504eccba570bdc" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m23s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "789f19685701ae83905707ae15e9fcedac3360a12be96b39a4d99dedd2583b07" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m22s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "0b6532eec9825695a979a9d7b566611d92ed4a35e90ea4e3df03c7af6927c60b" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m20s                  kubelet, k8s-worker1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "22cf5fe83d6f9bd992c2d550db896bdf55470142d0243e58fcfd23bb466c67f4" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Warning  FailedCreatePodSandBox  6m16s (x4 over 6m19s)  kubelet, k8s-worker1  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "60bb27be46cf438b522de29bed81d4840a4a90629c0cc85d7036c8ea63171d3d" network for pod "tiller-deploy-6f8d4f6c9c-cbp8s": NetworkPlugin cni failed to set up pod "tiller-deploy-6f8d4f6c9c-cbp8s_kube-system" network: no podCidr for node k8s-worker1
  Normal   SandboxChanged          88s (x287 over 6m28s)  kubelet, k8s-worker1  Pod sandbox changed, it will be killed and re-created.
`

**Comment by Warchant** [comment]
Check this stackoverflow answer: https://stackoverflow.com/a/49764370/1953079

**Comment by loganxavier** [comment]
Having the same error on a fresh machine, opened a question about [here](https://serverfault.com/questions/958912/helm-under-microk8s-giving-error-could-not-find-a-ready-tiller-pod).

**Comment by DNXie** [comment]
@bacongobbler  I have the same problem:

After running `kubectl --namespace kube-system describe pod tiller-deploy-c48485567-9tlpw`


Besides the message other people said, mine also says the following information: 

`sc = failed to resolve image "gcr.io/kubernetes-helm/tiller:v2.13.1": no available registry endpoint: failed to do request: Head https://gcr.io/v2/kubernetes-helm/tiller/manifests/v2.13.1: dial tcp 74.125.203.82:443: i/o timeout`

And after that I tried `kubectl get po -n kube-system` and the pod is still not ready.


Full information:

~~~
Name:               tiller-deploy-c48485567-9tlpw
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               jwang-ubuntu/10.5.11.140
Start Time:         Mon, 08 Apr 2019 17:09:59 +0800
Labels:             app=helm
                    name=tiller
                    pod-template-hash=c48485567
Annotations:        <none>
Status:             Pending
IP:                 10.1.1.18
Controlled By:      ReplicaSet/tiller-deploy-c48485567
Containers:
  tiller:
    Container ID:
    Image:          gcr.io/kubernetes-helm/tiller:v2.13.1
    Image ID:
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xftfv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-xftfv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xftfv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                   Message
  ----     ------     ----                   ----                   -------
  Normal   Scheduled  8m26s                  default-scheduler      Successfully assigned kube-system/tiller-deploy-c48485567-9tlpw to jwang-ubuntu
  Normal   Pulling    5m28s (x4 over 8m24s)  kubelet, jwang-ubuntu  Pulling image "gcr.io/kubernetes-helm/tiller:v2.13.1"
  Warning  Failed     4m58s (x4 over 7m54s)  kubelet, jwang-ubuntu  Error: ErrImagePull
  Warning  Failed     4m44s (x6 over 7m54s)  kubelet, jwang-ubuntu  Error: ImagePullBackOff
  Normal   BackOff    4m32s (x7 over 7m54s)  kubelet, jwang-ubuntu  Back-off pulling image "gcr.io/kubernetes-helm/tiller:v2.13.1"
  Warning  Failed     3m6s (x5 over 7m54s)   kubelet, jwang-ubuntu  Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.13.1": rpc error: code = Unknown desc = failed to resolve image "gcr.io/kubernetes-helm/tiller:v2.13.1": no available registry endpoint: failed to do request: Head https://gcr.io/v2/kubernetes-helm/tiller/manifests/v2.13.1: dial tcp 74.125.203.82:443: i/o timeout
~~~
