### ISSUE TITLE
helm takes keystrokes out of order

### ISSUE THREAD

**Issue by dwang20151005** [kubernetes/helm#2297]
If I do

    (let ((prompt "prompt")
          (candidates (loop for i from 0 to 500000 collecting (format "foo bar baz %S" i)))
          (require-match nil))
      (completing-read "prompt" candidates require-match))

and type `jjjjjk<RET>` quickly, I would expect it to return what I typed but
instead it returns "foo bar baz 0".

It's as if helm does the RET before it's understood the keystrokes before that.

The way this appears in practice is, when I do a completing read on a smaller
(4700) collection of longer candidates (which I can't send to you), and I type
input that does not match any of the candidates, sometimes what helm returns is
a truncated version of what I typed.

This is a problem for me because I love helm and I use it everywhere, and so some of the things I completing-read are inputs to production systems.

**Comment by bacongobbler** [comment]
I'm a bit out of the loop here, but what are you using to interface with Helm/tiller? The language posted in the block quotes is not one I'm familiar with... Helm/Tiller is written in Go and communicates via GRPC.

**Comment by bacongobbler** [comment]
Perhaps you meant to file an issue at https://github.com/emacs-helm/helm?

**Comment by dwang20151005** [comment]
Ha!  I am so sorry.  Thank you.
