### ISSUE TITLE
StatefulSet's for 1.6 will be broken until we have a release that vendors against K8s 1.6

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/helm#2306]
As an example, if you attempt to delete a StatefulSet with a `.Spec.Template` that uses `affinity` it will break when the Reaper attempts to scale the StatefulSet down prior to deleting the API object. This is because the Pod fields will stripped during the update and that represents an invalid mutation to the StatefulSet.

-  This can be mitigated by not using those fields, but the alpha annotations will not work on a 1.6 cluster.

**Comment by bacongobbler** [comment]
1.6 support was merged in #2248 and I know v2.4.0 is slated for [May 1st](https://github.com/kubernetes/helm/milestone/34), so that's when 1.6 support will drop in an official release.

**Comment by technosophos** [comment]
Marking this as fixed since the 1.6 library was merged into Helm 2.4.
