### ISSUE TITLE
can helm get pause from local?

### ISSUE THREAD

**Issue by lixiaobing1** [kubernetes/helm#2309]
when helm init:
unable to pull sandbox image "gcr.io/google_containers/pause": Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp: i/o timeout"}"
so, how can i modify helm to get pause image from local docker respo?

**Comment by bacongobbler** [comment]
The pause container is something kubernetes fetches to reserve the network namespace for the pod. This can be configurable from the kubelet via the `--pod_infra_container_image` flag, so you will need to change your kubelet's boot flags to fetch a local docker image instead. This isn't something that can be changed within helm as this is handled by the kubelet.

**Comment by bacongobbler** [comment]
further context: https://github.com/kubernetes/kubernetes/issues/4896#issuecomment-77917065

**Comment by lixiaobing1** [comment]
thx first, another, can u tell me where is the kubelet configuration?

**Comment by bacongobbler** [comment]
It's dependent on how your cluster was set up. I can't give you a definitive answer as it is cloud provider specific or specific to the instructions you followed to install kubernetes onto your cluster. I would follow up with your cloud provider's documentation.
