### ISSUE TITLE
Bug (tiller): Tiller docker image does not include ca-certificates

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/helm#2311]
When trusted certs are used, it is customary to not provide the cacert. GO will use the cacerts provided by OS. Currently [Tiller Dockerfile](https://github.com/kubernetes/helm/blob/master/rootfs/Dockerfile#L15) does not install `ca-certificates` package. This should be added in Tiller Dockerfile

## Fix:
http://stackoverflow.com/a/33353762/244009

cc: @fibonacci1729

**Comment by technosophos** [comment]
This should be very easy to fix in the Dockerfile. We might be too late for 2.4, so I added to 2.5. But if we can, let's bump this up.

**Comment by technosophos** [comment]
I'm gonna grab this one, since it's a quick fix.
