### ISSUE TITLE
helm install --wait does not save release when it fails

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#2312]
I'm running:

```
helm install --wait --timeout 1200 \
        --kube-context np.k8s.saltside.io \
        --namespace development \
        -f secrets.yaml \
        --name test-efritin \
        tmp/charts/sandbox/kviberg-efritin
E0421 05:13:20.886361    8137 portforward.go:175] lost connection to pod
Error: transport is closing
```

This fails for some reason for some reason (unknown to me; also this is a separate issue #2288). At this point some things have been created in the cluster, but they're unknown to tiller. The release `test-efritin` is not present in `helm ls`. It seems that if `helm install` fails to complete then the release is not saved in tiller.

```
$ helm version --client
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
```

EDIT: I think this may be an async issue. Tiller is still waiting for things to happen _before_ creating the release state. The release did appear after a few minutes.

**Comment by thomastaylor312** [comment]
@ahawkins You are correct, Tiller is waiting for a response from the running release. This is something I would like to improve in the future so that tiller knows to stop and mark as failed if the connection that started it is closed

**Comment by ahawkins** [comment]
> that tiller knows to stop and mark as failed if the connection that started it is closed

@thomastaylor312 Would that make sense though? In this case everything is still running on the tiller side. Could it be reliably cancelled while in-flight? Also what happens to resources created?

**Comment by thomastaylor312** [comment]
@ahawkins Was trying to avoid opening that can of worms 😃 . That is exactly why I haven't done it yet. There are a lot of considerations

**Comment by ahawkins** [comment]
@thomastaylor312 should we close this issue then?

**Comment by thomastaylor312** [comment]
Yeah, I'll close it for now.
