### ISSUE TITLE
Helm can't found charts in own repo

### ISSUE THREAD

**Issue by adawolfs** [kubernetes/helm#2315]
Hello

I've created my own repo into a google cloud bucket and added it to my helm, but when I try to install it I get the following error

Error: file "Repo/ChartName" not found

But if I make a search it is displayed into the coincidences

Please help

```
helm version       
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}

```

**Comment by bacongobbler** [comment]
Can you show `helm search repo/chartname`? Wonder if CamelCasing the repo/chart name has anything to do with it.

**Comment by adawolfs** [comment]
````
helm search liferay      
NAME        	VERSION	DESCRIPTION  
repo/liferay	0.1.0  	Liferay Chart

helm install repo/liferay
Error: file "repo/liferay" not found
````

**Comment by technosophos** [comment]
In your `index.yaml` file in the `repo/liferay` repository, are the URLs to the packages correct? Usually, the above indicates that `helm repo index` was called without `--url`, and the URL that Helm automatically built can't find any release.

Probably, the easiest fix is to run `helm repo index --url $YOU_BASE_URL`.

**Comment by adawolfs** [comment]
Thanks @technosophos $YOU_BASE_UR should to be my repo url?

**Comment by adawolfs** [comment]
Yeap, It's working now thank you for your help!

**Comment by bacongobbler** [comment]
I think this ticket can be closed now.
