### ISSUE TITLE
Release names should be unique across namespaces

### ISSUE THREAD

**Issue by sysradium** [kubernetes/helm#2317]
Personally I found it surprising that even there is a `--namespace` argument helm forces you to give unique names to your releases across the cluster.

I expected that it would be possible to create the release with the same name in different namespaces:

```
helm install --namespace=foo pubsub pubsub
helm install --namespace=bar pubsub pubsub
```

However this fails on the second try because `pubsub` already exists. K8S allows you to have identical resource names for the ones in different namespaces.

**Comment by bacongobbler** [comment]
related comment: https://github.com/kubernetes/helm/issues/2060#issuecomment-287164881

**Comment by sysradium** [comment]
@bacongobbler thanks a lot, basically the answer is "go to hell with the namespaces" :)
