### ISSUE TITLE
Can command "helm status" add the status of pod ? 

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/helm#2318]
In the lastest version of helm:
when show the status of a release, it  show service, deployment status, but not show the pod status:

RESOURCES:
==> v1/Secret
NAME                     TYPE    DATA  AGE
wonderful-goat-dokuwiki  Opaque  1     8d

==> v1/PersistentVolumeClaim
NAME                              STATUS   VOLUME  CAPACITY  ACCESSMODES  AGE
wonderful-goat-dokuwiki-dokuwiki  Pending  8d

==> v1/Service
NAME                     CLUSTER-IP     EXTERNAL-IP  PORT(S)                     AGE
wonderful-goat-dokuwiki  192.168.3.251  <pending>    80:31284/TCP,443:32581/TCP  8d

==> extensions/v1beta1/Deployment
NAME                     DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
wonderful-goat-dokuwiki  1        1        1           1          8d

can it add the status like:

NAME                                       READY     STATUS    RESTARTS   AGE
wonderful-goat-dokuwiki-2123172038-n7hmv   1/1       Running   0          8d

As the pod is the very important object in kuberbertes, so i think is necessary to add the pod's status.

I am happy to complete, so many thanks.

**Comment by DoctorZK** [comment]
In my opinion, the status in Helm is status describing the install/uninstall action, while the status of pods is more like the status descring the running status of resource objects, which is out of the scope of an install management service.

**Comment by yan234280533** [comment]
In kubenertes, service, deployment ,pod, configmap and so on , all of those are resource objects.
From the user, If a unsuccessful install/uninstall action happened, he wanted most is to know all of  resource objects under this release. Not to find some information using helm command  and then copy this information to use kubectl to find the other information.
I think is much more convenient for users.

**Comment by technosophos** [comment]
The information that Helm displays is passed from Kubernetes. So the additional information _can_ be added, but it will take some work.

**Comment by yan234280533** [comment]
I am happy to do this work. It my pleasured to make helm software better.

**Comment by thomastaylor312** [comment]
Closed in #2849
