### ISSUE TITLE
How about to " Helm describe" , using to show the detail information of the release ( like the "kubectl describe")

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/helm#2319]
How about to " Helm describe" , using to show the detail information of the release
 ( like the "kubectl describe")

If one find the relase he deployment has some error , he can use "Helm describe"  command  to show the 

detail  information of his  deployment .

the commad  include:
    
      Helm describe release-name               
      //show all of kinds resource  's details of the release , and the other information of this release

      Helm describe release-name  kind        
     //show one kind of resource( such as deployment) 's details of the release

      Helm describe  release-name  kind  instance-name  
      //show one resource instance's details of the release

**Comment by technosophos** [comment]
I believe that `helm status` does at least some of this now. We could probably extend it to take an optional kind. But really at that point it seems like we'd just be cloning existing `kubectl` behavior, right?

**Comment by yan234280533** [comment]
Many thanks for you technosophos.

I  understand you mean is that, By add an option of "helm status"  it  can be used :  
helm  status release-name kind 
helm  status release-name kind  instance-name
I think is an good idea,  I  agree with that. 

Can the "helm status" add to display the status of the pod resource, after  all  the pod resource 
is an important resource in kubernertes. 

I am very happy to do that work.

many thanks  technosophos.

**Comment by technosophos** [comment]
Yes, that sounds good.

**Comment by yan234280533** [comment]
Thanks a billion, many many thanks. 

I will  complete it as soon as possible.

**Comment by bacongobbler** [comment]
closed via https://github.com/kubernetes/helm/pull/2849.
