### ISSUE TITLE
install local/* not found, while search shows it exists

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/helm#2320]
```
$ helm search web
NAME                	VERSION	DESCRIPTION                                       
local/web           	0.1.0  	Run your application or service on Kubernetes, ...
stable/chronograf   	0.2.0  	Open-source web application written in Go and R...
...
```

```
$ helm install local/web --dry-run
Error: file "local/web" not found
```

According to `helm install --help` this should work, but it doesn't.

**Comment by bacongobbler** [comment]
Looks very familiar to https://github.com/kubernetes/helm/issues/2315.

**Comment by technosophos** [comment]
Are you running `helm serve`? If not, it can't find a server on localhost.

**Comment by Winterflower** [comment]
thank you @technosophos - was having the same issue and running helm serve solved it

**Comment by bacongobbler** [comment]
closing as solved/inactive. Sounds like no local server was running, but the cached index files were still present in ~/.helm/repository/local/index.yaml. If you removed that file, I bet you it would not show up in `helm search` any more.

**Comment by JeanMertz** [comment]
Thanks @bacongobbler. I can't remember I ever ran `helm serve` before, but I guess I must have 👍

**Comment by pbc** [comment]
For those who stumbled onto a similar issue but in a different context, you will also get the same error if you specify incorrect version using the "--version" option.
