### ISSUE TITLE
literal double-curly in template?

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/helm#2321]
I'm trying to get this to work:

```yaml
{{- range .Values.envs }}
{{ . }}: \{\{ {{ . }} \}\}
{{- end }}
```

Which should end up like this:

```yaml
HELLO_UNIVERSE: {{ HELLO_UNIVERSE }}
```

But when using install with `--debug`, I get:

```yaml
HELLO_UNIVERSE: \{\{ HELLO_UNIVERSE \}\}
```

I tried different styles, but I can't get the expected output.

**Comment by bacongobbler** [comment]
Use `{{ "{{" }}`.

**Comment by JeanMertz** [comment]
I tried that, but I get:

```yaml
{{- range .Values.envs }}
{{ . }}: {{ "{{" }}{{ . }}{{ "}}" }}
{{- end }}
```

> Error: yaml: invalid map key: map[interface {}]interface {}{"HELLO_UNIVERSE":interface {}(nil)}

**Comment by bacongobbler** [comment]
If you're trying to iterate through keys to dump as envvars in a manifest, try this:

```
{{ $key, $value := range .Values.envs }}
{{ $key }}: {{ $value | quote }}
{{ end }}
```

**Comment by bacongobbler** [comment]
Either way (using the `quote` function or encasing the double curly braces in a string) will allow you to render double curly brackets in your template. The rest is up to you :)

**Comment by JeanMertz** [comment]
No, I was explicitly trying to get the output I specified in the original post, so not using a map, but an array.

You say "either way using double curly braces in a string will allow you to render double curly brackets in your template", but isn't that what I demonstrated above, which doesn't work?

Here are some other things that don't work:

```
{{- range .Values.envs }}
{{ . }}: {{ "{{ " | quote }} {{ . }} {{ " }}" | quote }}
{{- end }}

Error: yaml: line 5: did not find expected key
```

```
{{- range .Values.envs }}
{{ . }}: {{ {{ | quote }} {{ . }} {{ }} | quote }}
{{- end }}

Error: parse error in "web/templates/resources.yaml": template: web/templates/resources.yaml:93: unexpected "{" in command
```

```
{{- range .Values.envs }}
{{ . }}: \{\{ {{ . }} \}\}
{{- end }}

works, but results in:

HELLO_UNIVERSE: \{\{ HELLO_UNIVERSE \}\}
```

```
{{- range .Values.envs }}
{{ . }}: {{ "{{" }} {{ . }} {{ "}}" }}
{{- end }}

Error: yaml: invalid map key: map[interface {}]interface {}{"HELLO_UNIVERSE":interface {}(nil)}

**Comment by bacongobbler** [comment]
In all of those cases, you are assigning the dot variable to a `map[interface {}] interface {}`. In other words, `range .Values.envs` is not an array but a yaml key/value pair, so from my perspective it didn't look like an array.

Can you post a clearer example of what your values.yaml looks like? That way we can figure out how you're trying to template it out.

**Comment by technosophos** [comment]
Try `{{ range $key, $value := .Values.envs }}`.

**Comment by technosophos** [comment]
It's been a few months, so I am closing this. Feel free to re-open if necessary.

**Comment by JeanMertz** [comment]
Sorry for not responding Matt. I went a different route, and must have missed your comment 👍

**Comment by DanGolding** [comment]
Try

```
{{- range .Values.envs }}
{{ . }}: `{{` {{ . }} `}}`
{{- end }}
```

**Comment by pjamenaja** [comment]
I added my solution in this comment here, I think that might be useful. https://github.com/helm/helm/issues/2798#issuecomment-890478869
