### ISSUE TITLE
helm install does not save a release under failure conditions

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#2329]
## What Happened

```
helm install
```

Failed because of the transport closed issue. The various resources (`Pods`, `Deployments`) etc had created, but `helm ls` does not show the release name. I'm guessing this because the release is only saved in tiller _after_ everything completed successfully. The unexpected transport closing breaks that process.

## Versions

```
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
```

**Comment by technosophos** [comment]
Did you try `helm ls --all`? The release record is written before the resources are created. But `helm ls` by default only shows releases that are in a success state.

**Comment by ahawkins** [comment]
I did not try with `--all`. However that makes sense given the option flags.
