### ISSUE TITLE
helm test fails with "transport closed" error

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#2330]
## What Happened

`helm test` failed with `error: transport closing`. Our test hook uses a `Pod` to run a smoke test against the release.

```
RUNNING: test-bikroy-kviberg-bikr-smoke-test
E0426 06:50:43.323874   11810 portforward.go:175] lost connection to pod
Error: transport is closing
test-bikroy test failed! Capturing logs and cleaning up
test-bikroy-kviberg-bikr-smoke-test Logs:

Error from server (BadRequest): the server rejected our request for an unknown reason (get pods test-bikroy-kviberg-bikr-smoke-test)
```

Tiller logs:

```
2017/04/26 06:49:43 storage.go:133: Getting release history for 'test-bikroy'
2017/04/26 06:49:43 client.go:708: Watching pod test-bikroy-kviberg-bikr-smoke-test for completion with timeout of 5m0s
```

## Versions

```
$ helm version
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
```

**Comment by michelleN** [comment]
@ahawkins = did you get that error after 5 minute timeout or immediately?

**Comment by michelleN** [comment]
@ahawkins Could you verify this is still an issue for you?
I also saw in #2340 that you were scripting some stuff around `helm test`. Could you verify that this is still an issue and give me the output by isolating just the `helm test` command's output?

Thank you.

**Comment by ahawkins** [comment]
I think it's safe enough to close this issue. I've run hundreds of
helm test commands at this point and not encountered the same failure.
I'll chock this one up to a transient error in tiller/kube-
proxy/Kubernetes itself.

On Sun, May 7, 2017, at 09:19 AM, Michelle Noorali wrote:
> @ahawkins[1] Could you verify this is still an issue for you?
>  I also saw in #2340[2] that you were scripting some stuff around helm
>  test. Could you verify that this is still an issue and give me the
>  output by isolating just the helm test command's output?> Thank you.


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].> 


Links:

  1. https://github.com/ahawkins
  2. https://github.com/kubernetes/helm/issues/2340
  3. https://github.com/kubernetes/helm/issues/2330#issuecomment-299680604

**Comment by michelleN** [comment]
Alrighty sounds good. Feel free to open another if you see something again.
