### ISSUE TITLE
Tiller does not clean up old config maps

### ISSUE THREAD

**Issue by bcorijn** [kubernetes/helm#2332]
Hi,

I almost never check the kube-system namespace, but when doing yesterday I noticed Tiller keeps a lot of old state / history around in config maps in its namespace, and never does any cleanup as far as I can see?
This seems like problems waiting to happen as these will just keep growing, and I don't see any Helm commands to do a purge. 
Is there a way we can limit this? (similar to Deployments RevisionHistoryLimit?)

**Comment by michelleN** [comment]
hey @bcorijn -- Tiller keeps release history around in case you want to rollback to a particular version. You can remove the configmap for a release when you do `helm delete` it by adding the `--purge` flag.

Does that help?

**Comment by SharpEdgeMarshall** [comment]
Yes, but without a limit the ConfigMaps keep growing.

**Comment by bcorijn** [comment]
@michelleN: I understand they are used to rollback to a particular release and they can be removed by adding a `--purge` flag during delete. However this does nothing to stop the fact that in a busy cluster sooner or later there will be a huge number of old, useless resources, something Kubernetes often does not deal very well with in my experience. 
In Kubernetes core the amount of old resources left behind by a deployment or cron job are limited, a concept I had assumed Helm followed as well. I don't think there is a need to be able to rollback 30 versions ago?

**Comment by sjthespian** [comment]
We are running into this issue frequently. I support an application that is building and deploying using a CI model that frequently releases several versions of the application a day. We have now run into an issue multiple times where the configmap has grown so large that helm times out trying to retrieve it. We end up manually trimming the releases, but that assumes that we can retrieve the configmap in the first place (i.e. when this happens even kubectl times out trying to retrieve the configmap).

We are probably going to have to build a step into our CI system that retrieves the releases and trims them, but having a flag in helm that does this automatically would save us quite a bit of work.

**Comment by technosophos** [comment]
I am just about done with a fix for this.

**Comment by bcorijn** [comment]
@technosophos Nice! Could you explain what you mean exactly with `To enable this feature, use helm init --history-max NNN. Note that because of the restrictions on Deployment objects, you will have to re-install Tiller to add a limit.` Will that init automatically re-deploy Tiller in my cluster or will I have to take any manual precautions? What will happen with releases that already have more history than the limit you set?

**Comment by bacongobbler** [comment]
@bcorijn if you have an existing tiller instance in your cluster, you'll also need to supply the `--upgrade` flag. Either that or `helm reset && helm init --history-max NNN` if `--upgrade` doesn't work.

**Comment by bacongobbler** [comment]
This of course will not work until Helm 2.7 is released (or you're using the canary deploys.

**Comment by bacongobbler** [comment]
> What will happen with releases that already have more history than the limit you set?

You can expect them to be removed the next time you call `helm upgrade`, as far as I understand the code.

**Comment by bcorijn** [comment]
@bacongobbler Perfect, thanks! Will check it out once 2.7 drops.

**Comment by punitag** [comment]
This is great. We have this issue because we are using tiller in a resource-limited namespace where we are allowed to create only 10 configmaps and we frequently hit this limit.

**Comment by ultimateboy** [comment]
I couldn't wait until 2.7 landed - my tiller was crashing with OOM because of way too many configmaps. I wrote this script to clean up old releases. Use with caution, but it unblocked me until 2.7 lands.

```bash
#!/usr/bin/env bash

TARGET_NUM_REVISIONS=10
TARGET_NUM_REVISIONS=$(($TARGET_NUM_REVISIONS+0))

RELEASES=$(kubectl --namespace=kube-system get cm -l OWNER=TILLER -o go-template --template='{{range .items}}{{ .metadata.labels.NAME }}{{"\n"}}{{ end }}' | sort -u)

# create the directory to store backups
mkdir configmaps

for RELEASE in $RELEASES
do
  # get the revisions of this release
  REVISIONS=$(kubectl --namespace=kube-system get cm -l OWNER=TILLER -l NAME=$RELEASE | awk '{if(NR>1)print $1}' | sed 's/.*\.v//' | sort -n)
  NUM_REVISIONS=$(echo $REVISIONS | tr " " "\n" | wc -l)
  NUM_REVISIONS=$(($NUM_REVISIONS+0))

  echo "Release $RELEASE has $NUM_REVISIONS revisions. Target is $TARGET_NUM_REVISIONS."
  if [[ $NUM_REVISIONS -gt $TARGET_NUM_REVISIONS ]]; then
    NUM_TO_DELETE=$(($NUM_REVISIONS-$TARGET_NUM_REVISIONS))
    echo "Will delete $NUM_TO_DELETE revisions"

    TO_DELETE=$(echo $REVISIONS | tr " " "\n" | head -n $NUM_TO_DELETE)

    for DELETE_REVISION in $TO_DELETE
    do
      CMNAME=$RELEASE.v$DELETE_REVISION
      echo "Deleting $CMNAME"
      # Take a backup
      kubectl --namespace=kube-system get cm $CMNAME -o yaml > configmaps/$CMNAME.yaml
      # Do the delete
      kubectl --namespace=kube-system delete cm $CMNAME
    done
  fi
done
```

**Comment by richstokes** [comment]
Not sure if helpful to anyone, but I made a small script that will clean up all DELETED helm deployment config maps. Essentially just runs through them all and purges. Was helpful to me as I had lots of short-lived deployments during testing which only had 1 or 2 revisions.

```
#!/usr/bin/env bash
RELEASES=$(kubectl --namespace=kube-system get cm -l OWNER=TILLER -l STATUS=DELETED -o go-template --template='{{range .items}}{{ .metadata.labels.NAME }}{{"\n"}}{{ end }}' | sort -u)

for RELEASE in $RELEASES
do
  helm delete $RELEASE --purge
done
```

**Comment by chestack** [comment]
Run into the same issue, It caused that kube-apiserver use too much memory up to the limits. kube-apiserver was OOM killed. Following is kube-apiserver.log:

```
I1018 02:27:10.465142       1 trace.go:76] Trace[967179655]: "List /api/v1/namespaces/kube-system/configmaps" (started: 2018-10-18 02:27:07.589957638 +0000 UTC m=+50270.823456577) (total time: 2.875147723s):
Trace[967179655]: [1.308105695s] [1.30803837s] Listing from storage done
Trace[967179655]: [2.87514482s] [1.566432149s] Writing http response done (702 items)
I1018 02:29:08.443211       1 trace.go:76] Trace[1423692943]: "List /api/v1/namespaces/kube-system/configmaps" (started: 2018-10-18 02:29:07.346663261 +0000 UTC m=+50390.580162229) (total time: 1.096515156s):
Trace[1423692943]: [1.079106655s] [1.079002293s] Listing from storage done
E1018 02:29:20.446953       1 writers.go:149] apiserver was unable to write a JSON response: client disconnected
E1018 02:29:20.446978       1 status.go:64] apiserver received an error that is not an metav1.Status: client disconnected
I1018 02:29:20.448104       1 trace.go:76] Trace[1455099037]: "List /api/v1/configmaps" (started: 2018-10-18 02:29:08.626741462 +0000 UTC m=+50391.860240414) (total time: 11.821327899s):
Trace[1455099037]: [11.821325849s] [11.819570395s] Writing http response done (783 items)
```

https://github.com/helm/helm/pull/2636 could fix it.

**Comment by davidxjohnson** [comment]
> We have now run into an issue multiple times where the configmap has grown so large that helm times out trying to retrieve it. 

If the configmap size for a release is too large to retrieve, it may that the `tgz` package is being included in the configmap. If you do not add `*.tgz` in the `.helmignore` file of the chart directory, the configmap will grow in size along with the tgz file. 

In other words, each `package` command will include the previous package file (if present) if you do not add `*.tgz` to `.getignore`. The size of the package file will grow exponentially if it's not excluded.

**Comment by sjthespian** [comment]
Unfortunately that wasn't the case, we made sure the packages were included long ago. This is just an application (that isn't our problem anymore, btw :) ) that released many times every day and created huge configmaps in the kube-system namespace for storing the helm release information.
