### ISSUE TITLE
HA Tiller Story

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#2334]
_I'm not sure exactly where to put this so feel free to close this if an issue is not right forum._

I'm opening this issue to discuss HA tiller. I've encountered a many bugs (which seems to be Tiller specific). These bugs end up crashing Tiller for one reason or the other. This got me thinking: What is the story for HA tiller? `helm init` creates a `Deployment` with one replica. I'm not sure if this is by design or just a missing feature for `--replicas` on helm init. Is the correct answer to this story to just run more replicas and forget about it _or_ is there more to the internal tiller server process to make it more resilient against certain failure modes?

EDIT: Related background context: https://medium.com/saltside-engineering/our-first-kubernetes-outage-c6b9249cfd3a

**Comment by technosophos** [comment]
@adamreese will the Helm client correctly handle this? I mean, there is a possible race condition if two Tillers modify the same release at the same time... but will the Helm client even balance between two tillers?

**Comment by bacongobbler** [comment]
It fetches [the first available pod](https://github.com/kubernetes/helm/blob/d1b1161f7778e60c4a5b43e4ac3a4ac8fdc7060f/pkg/helm/portforwarder/portforwarder.go#L62-L66) when HELM_HOST is not set, so it should be fine to run two at once. The race condition on CRUD operations is a valid concern too though.

**Comment by egeland** [comment]
I just read [your story](https://medium.com/saltside-engineering/our-first-kubernetes-outage-c6b9249cfd3a) @ahawkins - which led me to investigate HA for tiller, which led me to this issue..

We definitely need Tiller to be HA by default.

**Comment by ahawkins** [comment]
> It fetches the first available pod when HELM_HOST is not set, so it should be fine to run two at once. The race condition on CRUD operations is a valid concern too though.

How is "available" determined? If there were 2 replicas, would the code select the first pod returned from get pods API call? I wasn't aware of `HELM_HOST`. I think it may make sense to expose tiller with ` LoadBalancer` service and set that. Then in theory the number of replicas wouldn't matter.

**Comment by Miyurz** [comment]
I agree that tiller should be HA by default with one tiller on every master.Since tillers store the config data in etcd, the tiller acting on a release could lock it up so that the next one doesn't write to the same ?

**Comment by Miyurz** [comment]
@technosophos Has any work begun for this feature ?

**Comment by bacongobbler** [comment]
Closing this discussion as inactive and "too big to close" since there's nothing actionable described in this issue (and yes, release locking was implemented in recent releases of Helm).

If there are additional points where tiller's HA story is lacking, Please feel free to write up design documents and/or PRs to fix any issues you see. Thanks!

**Comment by egeland** [comment]
Seems like a counter-productive thing to do, closing this issue when there's still no HA for tiller...?

Or did I miss something (that might do well to be mentioned here)?

**Comment by bacongobbler** [comment]
Yes, in hindsight this was closed this a little too soon, but I did have my reasons for closing it :)

The problem with opening a generic issue like "make tiller HA ready" is that it does not provide any feedback to the community or to the maintainers on *what* needs to be done to make tiller HA ready. In my mind it's the same as opening a ticket stating that [mongodb is web scale](https://www.youtube.com/watch?v=b2F-DItXtZs) and tiller is not. Great, now what do we do to make it web scale?

I'm re-opening this ticket, but I would like the see the there to be some action items so we can track efforts to make tiller highly available.

**Comment by coderanger** [comment]
If mutex-ing on release changes is in place, it sounds like the next step would be to put in an option to `helm init` to generate the deployment with more than one replica, maybe with some anti-affinity settings if we're feeling super fancy?

**Comment by coderanger** [comment]
It's also worth noting that while the deployment has only a single replica, if Tiller (or the node it is one) fails, it should get restarted automatically so we should probably establish what kind of failure models this is for. I wouldn't normally consider Tiller being down for a few seconds to be something worthy of notice.

**Comment by egeland** [comment]
That's long enough to break CI/CD deployments, if you do a lot of them
(which we do).

**Comment by coderanger** [comment]
Possibly a premature closing again, though we're getting closer!

**Comment by bacongobbler** [comment]
GitHub auto closed this ticket. Not intentional :)

**Comment by onorua** [comment]
Hm, looks like mutexing is in place, @bacongobbler what's left here then?

**Comment by coderanger** [comment]
@onorua in-process mutexing has been in place for a while, the issue is now that if running multiple replicas and trying to do concurrent operations on a single release, you could get some nasty race conditions, so we need some kind of (hopefully simple) distributed locking.

**Comment by coderanger** [comment]
Given that Helm 3 is planning to get rid of Tiller (I think?), this does seem less and less likely to be addressed every day :)

**Comment by bacongobbler** [comment]
Yes, the current dev branch removed tiller

**Comment by coderanger** [comment]
We should probably close this out then, unless someone is going to put a lot of resources into Helm 2, this will likely not happen?

**Comment by itaimalek** [comment]
@bacongobbler , I think @ahawkins made a great solution offer .
if Helm client would be allow to communicate with tiller on a chosen ip, and tiller exposed via LB service, this would be ideal.

**Comment by coderanger** [comment]
@itaimalek Tiller is no longer used by Helm and a major structural reworking of Helm 2 seems unlikely and not worth the effort in light of that.
