### ISSUE TITLE
Proposal: Make value override work with yaml anchor/reference

### ISSUE THREAD

**Issue by caseeker** [kubernetes/helm#2336]
With Yaml anchor following can be done in values.yaml

```
imageTag: $imageTag "latest"
containers:
  nginx:
    image: "nginx"
    imageTag: *imageTag
```

However currently when the top level `imageTag` key is override in command line by --set, the values referring to the anchor will still show the value in the values.yaml file.

So with the above example, if I do `helm install --set imageTag=1.0.0"` the `.Values.containers.nginx.imageTag` will still be the latest while `.Values.imageTag` will be 1.0.0

If the Chart starts to contain lots of containers where certain values might get overriden together while still allowing each value to be overriden separately, having this feature will be very helpful.

**Comment by technosophos** [comment]
This is a feature of the YAML parser (https://github.com/go-yaml/yaml/). And as far as I can tell, the parser is correct in discarding the alias (see section 3.2.2.2 of the YAML spec).

The parsed representation of the data that we get from the YAML parser gives us no access to the original alias (we can't even tell, for example, when an alias was used). So there's now way for us to later substitute a different value into a previously dereferenced alias. Again, this seems to be the intention of the YAML spec.

If you can get the YAML parser maintainers to change the behavior, we might be able to support the requested feature.

**Comment by sgandon** [comment]
I there any news on this issue please ?
Cause basically if this is not possible, I guess that would be worth some more clear notes in the documentation here: https://github.com/helm/helm/blob/master/docs/chart_template_guide/yaml_techniques.md#yaml-anchors
Like explicitly stating that anchor usage is not recommended cause set the value with --set on the command line will fail and values files overriding will also fail.

**Comment by halradaideh** [comment]
is this issue gonna be fixed or implemented ?

**Comment by bacongobbler** [comment]
See https://github.com/helm/helm/issues/2336#issuecomment-297839969

**Comment by sgandon** [comment]
In fact since then the yaml parser has gone up to version 3 and now offers way more information on the parsing like in fact the anchor.
see https://godoc.org/gopkg.in/yaml.v3#Node

**Comment by technosophos** [comment]
It is not clear what you are suggesting @sgandon

**Comment by sgandon** [comment]
@technosophos , in a previous comment you said

> This is a feature of the YAML parser (https://github.com/go-yaml/yaml/). And as far as I can tell, the parser is correct in discarding the alias (see section 3.2.2.2 of the YAML spec).
> 
> The parsed representation of the data that we get from the YAML parser gives us no access to the original alias (we can't even tell, for example, when an alias was used). So there's now way for us to later substitute a different value into a previously dereferenced alias. Again, this seems to be the intention of the YAML spec.
> 
> If you can get the YAML parser maintainers to change the behavior, we might be able to support the requested feature.

I am suggesting that if you use the yaml parser V3 you will have access to the anchor metadata and can act upon those, that you could not do with the v2 as you mentionned rightfully.

**Comment by technosophos** [comment]
Oh. Yeah, if someone wants to write a custom YAML traversal to do that, I think we'd accept it as a PR! It is likely to break APIs to the extent that it would have to be a Helm 4 feature. But if there's a way to do it without breaking APIs, it would be a neat feature.

The right first step would be to open an issue marked "Proposal" that would explain how this feature would work and would be implemented.

**Comment by sgandon** [comment]
I fact I just realized that if you want to reuse values in the values file you can also leverage the `tpl` function.
So for the initial example you can do that
```
imageTag: "latest"
containers:
  nginx:
    image: "nginx"
    imageTag: "{{ .Values.imageTag }}"
```
and when you want the value of the containers.nginx.imageTag you can just do
`{{ tpl .Values.containers.nginx.imageTag . }}`
I think this is an acceptable workaround. what do you think @sunghospark ?

**Comment by wiruzman** [comment]
@sgandon How would you override templates you use as dependencies? It works well with your own template with `tpl`, but for dependencies it could be very nice to use anchors.

**Comment by pkrishnath** [comment]
@sgandon we wont be able to override "{{ .Values.imageTag }}" from parent chart right ?

**Comment by sgandon** [comment]
@pkrishnath 
Yes you would, this is just a string value so you can override it like any other values. You can override
`containers.nginx.imageTag` or you can override `imageTag`
@wiruzman indeed with charts you don't own you can't do much.

**Comment by miraculixx** [comment]
I have found a workaround to this problem using a little Python helper program. YMMV

https://gist.github.com/miraculixx/bbba80793895f081204a05fbd5573eda
