### ISSUE TITLE
helm package: exitcode=0 after error

### ISSUE THREAD

**Issue by ddska** [kubernetes/helm#2337]
When there is no `HELM_HOME` defined, and `~/.helm/repository/local` directory does not exists, when I execute `helm package` command, I get error

    Error: stat /home/user/.helm/repository/local: no such file or directory

which is fine.

What is not fine is that OS exit code is 0, so I can not recognize in script if the command was successful or not.

I believe the `helm package` is not the only command with this behavior. 

Helm v2.3.0, linux 64 bit.

**Comment by technosophos** [comment]
Did the package generate successfully? Copying to the local repo is not considered a fatal error for `helm package` unless the package itself also failed to generate.

**Comment by ddska** [comment]
Issue was caused by local environment, could be closed.
The actual exit code is 1.
