### ISSUE TITLE
[wip] failed upgrade is no upgredable without rollback

### ISSUE THREAD

**Issue by redbaron** [kubernetes/helm#2341]
I'll add more details later once I verify, but it looks like if release has resources A and B and upgrade failed due to problem in A, then one upgrades release with changes made to A and B, then B isn't actually updated in a cluster, probably because Helm thinks that there is nothing  to change.

Does Tiller run `kubectl apply`-like action on all resources on every release?

**Comment by technosophos** [comment]
We'll need more information. It all depends on what state your resources got into. You can definitely get into a situation where you must rollback in order to upgrade.

**Comment by redbaron** [comment]
Apply does 3-way merge between state of the resource, latest recorded apply and new desired state. It looks like apply logic in Helm is just a diff between latest state in the resource *in helm history* (even if it was failing) and a desired state in new release, am I right? If thats the case, it explains why https://github.com/kubernetes/helm/issues/2346 is happening

**Comment by bcorijn** [comment]
@technosophos is there any plans to support a three-way merge like apply? I am in another situation where helm is saying there's no changes to my service and doesn't do any deploy, while the manifest and the actual situation are different.
The only solution here is to figure out when it happened (I don't recall any failed deploys), roll-back (and thus possibly also roll-back my deployment& pods to an old version that could brake things) and re-apply the changes. Feels like a very non-ideal solution...

**Comment by redbaron** [comment]
@bcorijn I am working on a patch which somewhat fixes problem by using latest successful deploy as a base for a patch, rather than latest deploy like it is doing now. I'll post it here as a PR for a feedback

**Comment by svanellewee** [comment]
@redbaron I'm interested in this issue. Any luck with your PR?

**Comment by redbaron** [comment]
@svanellewee , whole storage model is based around massive manifest rendered as string rather than rich types per resource. Concepts are modeled in such a way that adding per-resource tracking felt like a ground up rewrite of tiller backend. In other words I gave up :)

**Comment by bacongobbler** [comment]
fixed via #3097
