### ISSUE TITLE
Client: Add `repository` commands

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#235]
We need to add the following three command to the new client:

- `helm repo list`: List all of the repos that the in-cluster DM knows about
- `helm repo add BASE_URL`: Add a new repo to DM
- `helm repo remove BASE_URL`: Remove the named repository from DM's list

The options for the Add command must:
- Connect to a Google Cloud Storage endpoint
- Make it possible to set credentials for connecting to GCS

**Comment by jackgr** [comment]
@technosophos can this issue be closed now?
