### ISSUE TITLE
(tiller): Use grpc-go 1.3.0

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/helm#2355]
https://github.com/grpc/grpc-go/releases/tag/v1.3.0 released with "separate incoming and outgoing metadata in context" (https://github.com/grpc/grpc-go/pull/1157)

IMO, grpc-go should be updated to 1.3.0 in which ever release Rudder changes are merged to ensure only necessary metadata is forwarded from Tiller backend to Rudder grpc service via context.

cc: @technosophos @nebril

**Comment by TamalSaha** [comment]
https://github.com/grpc/grpc-go/issues/1178 explains the api changes in grpc-go package.

**Comment by thomastaylor312** [comment]
This has been bumped several times, so I am bumping to Upcoming - Minor. @adamreese would like your opinion on if this is a breaking change or something we can pull into a minor version. I think this should be just fine to pull in, but wanted to be sure

**Comment by thomastaylor312** [comment]
We upgraded the Go gRPC in #3101. Closing
