### ISSUE TITLE
helm init failed on windows (space in gcloud path)

### ISSUE THREAD

**Issue by maksimru** [kubernetes/helm#2362]
Helm: helm-v2.3.1-windows-amd64

C:\WINDOWS\system32>C:\Helm.exe init

$HELM_HOME has been configured at .helm.
Error: error installing: Post https://XX.XX.XX.XX/apis/extensions/v1beta1/namespaces/kube-system/deployments: error executing access token command "C:\\Users\\MainUser\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin\\gcloud.cmd": exec: "C:\\Users\\MainUser\\AppData\\Local\\Google\\Cloud": file does not exist

Kubectl active context:
...
cmd-path: C:\Users\MainUser\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd
....

**Comment by michelleN** [comment]
hey @maksimru what version of gcloud are you using?

This might be related to #2249

**Comment by maksimru** [comment]
C:\WINDOWS\system32>gcloud -v
Google Cloud SDK 153.0.0
beta 2017.03.24
bq 2.0.24
core 2017.04.24
gcloud
gsutil 4.25
kubectl

C:\WINDOWS\system32>kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}


I don't have any problems with kubectl and gcloud. I think problem happens because cmd-path is not encoded with quotes in helm during auth

**Comment by seanknox** [comment]
This should be fixed via https://github.com/kubernetes/helm/pull/2544

**Comment by bacongobbler** [comment]
Yep. This works on Windows 10 with Helm v2.6.1.
