### ISSUE TITLE
helm api broken for kubernetes version > 1.6

### ISSUE THREAD

**Issue by rachlenko** [kubernetes/helm#2363]
after upgrade to kubernetes 1.6 helm stop working.

I didn't find here workaround.  
could you explain how to fix that? 

https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions
Kubernetes
Using RBAC Authorization
Production-Grade Container Orchestration

https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions

**Comment by michelleN** [comment]
Hey @rachlenko 
You might want to take a look at #2224 to see if you're in the same boat. For those that have RBAC enabled by default, we are adding a flag to enable passing a service account to the tiller configuration. That PR is in review: #2365

**Comment by willise** [comment]
Hi, I have installed helm recently and also encountered a problem as #1821. 
I want to know if k8s's version is incompatible with helm or something else. Thanks.@michelleN.

**Comment by technosophos** [comment]
@willise 2.4.1 is compatible with Kubernetes 1.6 and previous. We have no reason to believe that it will be incompatible with 1.7.

**Comment by rachlenko** [comment]
Ok. Thanks.

**Comment by thomastaylor312** [comment]
Has this issue been solved with #2365?

**Comment by bacongobbler** [comment]
yes.
