### ISSUE TITLE
Setting values file while installing chart from repo

### ISSUE THREAD

**Issue by apanousis** [kubernetes/helm#2368]
I am wondering if _-f_ value supports files bundled within a tgz file. So am I capable to install a chart from my local repo `helm install local/test -f values-local.yaml` since values-local.yaml is part of test-1.0-SNAPSHOT.tgz file?

**Comment by michelleN** [comment]
You'd have `helm fetch --untar` the chart before passing the file in on the command line

**Comment by apanousis** [comment]
That would work! Thanks.
