### ISSUE TITLE
Client: Deploy command

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#237]
The `helm deploy` command should have the following features:

`helm deploy ./local/path` should bundle up a local directory and send it to DM for deployment.

`helm deploy ./local/chart.tgz` should send the named tar file to be deployed.

Options:
- `-name=NAME` should allow setting the name of the deployment.
- `-properties` sets properties.

**Comment by technosophos** [comment]
A version of this that pushes chart tgz files and directories is in progress in the helm dm repo.

**Comment by jackgr** [comment]
@technosophos can this issue be closed now?
