### ISSUE TITLE
Error updating pod specs with initContainers

### ISSUE THREAD

**Issue by hexedpackets** [kubernetes/helm#2373]
Helm version: v2.3.1
Kubernetes version: v1.6.1

I have a deployment which consists of one container and one two init containers. Originally I had the init containers as a `pod.beta.kubernetes.io/init-containers` annotation. After upgrading kubernetes to 1.6, I switched the chart to use `spec.initContainers` instead. Helm can create this fine, but attempting an upgrade that changes the init container fails with the following error: 

`Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct PodSpec for the json field "initContainers"`

Doing a dry-run succeeds. I can also pull down the rendered deployment with `helm get` and update it directly with `kubectl apply` without any errors.

**Comment by michelleN** [comment]
@hexedpackets helm 2.4.0+ supports kubernetes 1.6.0+
We'll be release 2.4.1 today. Would you mind trying with that version to see if you still have the issue?

cc/ @adamreese - keep me honest please

**Comment by hexedpackets** [comment]
Just tried with 2.4.1 and it validated successfully, thanks!
