### ISSUE TITLE
Set GKE token expiry

### ISSUE THREAD

**Issue by adawolfs** [kubernetes/helm#2374]
Hello
I'm creating an automated helm deploy service for GKE but I have issues with the access token because it expires every 30 minutes how can I set a larger expire time for it?

at this moment I'm running an kubectl cluster-info before run my helm commands to refresh the token, but this is an ugly way... 

Regards

**Comment by michelleN** [comment]
This is probably related to #2249

**Comment by technosophos** [comment]
Closing this as a duplicate in favor of #2249.
