### ISSUE TITLE
V2.4.0 Not using k8s config

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes/helm#2376]
Ran `./helm init`
```
➜  out git:(helm) ✗ kubectl get nodes
NAME        STATUS                     AGE       VERSION
master001   Ready,SchedulingDisabled   17m       v1.6.2
worker001   Ready                      17m       v1.6.2
worker002   Ready                      17m       v1.6.2
➜  out git:(helm) ✗ export KUBECONFIG=~/.kube/config
➜  out git:(helm) ✗ stat ~/.kube/config
16777220 22173086 -rw-r--r-- 1 dkoshkin (1535981906 0 6228 "May  2 20:42:16 2017" "May  2 20:36:45 2017" "May  2 20:36:45 2017" "May  2 16:12:41 2017" 4096 16 0 /Users/dkoshkin/.kube/config
➜  out git:(helm) ✗ ./helm version
Client: &version.Version{SemVer:"v2.4.0", GitCommit:"1ec2c04be8d4d69c15b85df97394bfa2f5919f03", GitTreeState:"clean"}
^C
➜  out git:(helm) ✗ ./helm init
$HELM_HOME has been configured at /Users/dkoshkin/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:8080: getsockopt: connection refused
➜  out git:(helm) ✗
```

Expected to run successfully, the cluster is not running locally but looks like Helm is not picking up the kube config file. The same cluster setup works fine with `v2.3.1`

**Comment by rodcloutier** [comment]
After a git bisect the following commit https://github.com/kubernetes/helm/commit/4d8f23e0c63aada4d7c57a25b4b384734bc3c930 introduced the break

**Comment by yuvipanda** [comment]
A strace tells me it does open and read $HOME/.kube/config, but still tries to hit localhost.

**Comment by yuvipanda** [comment]
This isn't just `helm init` - all helm commands fail with similar reason (even when there's a tiller running already)

**Comment by rodcloutier** [comment]
Changing the github.com/imdario/mergo dependency to the previous version fixes the problem.

https://github.com/imdario/mergo/commit/6633656539c1639d9d78127b7d47c622b5d7b6dc is fine
https://github.com/imdario/mergo/commit/3e95a51e0639b4cf372f2ccf74c86749d747fbdc is breaks

**Comment by rodcloutier** [comment]
Kubernetes is also using mergo Maybe a clash in versions?

**Comment by rodcloutier** [comment]
I suggest to pin the version of mergo to a known working version. I could have a PR quickly but regenerating the glide.lock also brings the latest version of Kubernetes. Would this be fine?
