### ISSUE TITLE
Helm 2.4.0 seems to ignore my kubeconfig

### ISSUE THREAD

**Issue by colemickens** [kubernetes/helm#2379]
Despite `kubectl` working, `helm` seems to not be actually using the kubeconfig file. Every command results in, roughly:
```
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

I can even see with strace that it opens and reads the `kubeconfig` and then connects to localhost:8080.

When I downgraded to 2.3.1 this went away.

**Comment by colachg** [comment]
I meet this problem too.

**Comment by aga20** [comment]
Same problem here :/

**Comment by thomasmodeneis** [comment]
same here.

**Comment by discostur** [comment]
same problem for me

**Comment by dmelina** [comment]
same problem

**Comment by bacongobbler** [comment]
Dupe of #2376?

**Comment by dmelina** [comment]
yes duplicate

**Comment by colemickens** [comment]
Closing since dupe of #2376.

**Comment by colemickens** [comment]
On second thought, given the number of thumbs up, maybe we should leave this open until 2.4.1 is available.

**Comment by adamreese** [comment]
2.4.1 is released

**Comment by kinderyj** [comment]
same problem, and please never say "Dupe' , because my version is the latest: 2.8.2.

**Comment by bacongobbler** [comment]
@kinderyj could you please open a new ticket? If you're seeing this on v2.8.2 then it's something we should tackle separately. Thanks!
