### ISSUE TITLE
Allow to change reference name of dependency image

### ISSUE THREAD

**Issue by markpundsack** [kubernetes/helm#2383]
When including images via `requirements.yaml`, it's sometimes useful to be able to specify another name as an alias for the dependent chart. 

For example, for installing a complete GitLab bundle, we need two postgres databases. We currently can't do that within a single chart, because I can only refer to a single requirement of the same name. To work around it, I'd have to artificially create another chart, with it's own dependency on postgres, and then include that into the main chart.

Another use-case is simply being able to name a generic chart with something more specific. So rather than just referring to `postgres`, you can refer to `mattermost-db`.

**Comment by thomastaylor312** [comment]
This would be a very helpful feature. Thank you for submitting the request!

**Comment by technosophos** [comment]
If the chart exposes the image as a value then you can supply the image from your higher-level configs.

So if the chart has:

```
image: {{ default "postgres:latest" .Values.image }}
```

Then from the higher level chart you can set it in values:

```
postgres:
  image: "somethingelse:1.9.5"
```

**Comment by technosophos** [comment]
Oh... when you say "name for the image", you mean a name for the _chart_? Like an alias? That would be a nice feature.

**Comment by sushilkm** [comment]
Please assign this one to me, I would like to work on this one 👍

**Comment by markpundsack** [comment]
@technosophos yes, that's exactly it. I updated my original comment a bit to hopefully clarify.

**Comment by jascott1** [comment]
If I understand correctly, there are 2 things here. 

1. in first use case we are not talking about aliases in typical sense. We are talking about multiple instantiations of same chart (same as copying the chart and renaming). OP wants to get two DB charts with one requirement line. Assuming we don't copy the chart on disk (OP could just do that) then we are making in-memory copy that has to be preserved through helm's flow. I suspect any feature that introspects the chart tree would have to be altered to "see" these clones.

2. being able to refer to a single chart by another name, this is aliasing and might help admins id the instance of the chart easier. Many things are keyed on chart name though so I think the scope of this alias would need to be thought out.

I think there is potentially a ton of work in #1 but #2 seems doable. At the same time, I feel we are getting into some heavy convenience here but I may not be fully groking the use cases.

**Comment by technosophos** [comment]
I think the idea was to do (1): give a chart a different name so that in my values.yaml file I can do:

```
postgres1:
  image: foo
postgres2:
  image: bar
```

And it may be true that to accomplish 1 would require enough coding overrides that a better way may just be to `perl -pi -e` the chart. ;-)

**Comment by thomastaylor312** [comment]
@sushilkm Are you working on this? I was going to remove the help wanted label if you are

**Comment by sushilkm** [comment]
Yup @oftaylor i started to work on this, you can remove help label

**Comment by thomastaylor312** [comment]
Assigned to me so no one else takes it
