### ISSUE TITLE
helm plugin install silently updates the plugin, if it pre-existed

### ISSUE THREAD

**Issue by sushilkm** [kubernetes/helm#2385]
if we run `helm plugin install` for the plugin which was already installed it gives an error for the symlink creation, but then there is a side effect that it updates the installed plugin code

I think there should be a separate option to `helm plugin update` plugin and `install` should not do anything except for erroring out in case a plugin already

**Comment by thomastaylor312** [comment]
I am going to tag this as a bug so it matches with the other things that are all being fixed in #2400

**Comment by thomastaylor312** [comment]
Closed in #2400
