### ISSUE TITLE
Add CHART_NAME and CHART_VERSION labels to release storage

### ISSUE THREAD

**Issue by spiddy** [kubernetes/helm#2391]
Currently in the release storage the following labels are added:

```
    CREATED_AT: "1487519101"
    NAME: womping-kangaroo
    OWNER: TILLER
    STATUS: DEPLOYED
    VERSION: "1"
```

It would be useful to get the information of the chart used in labels and it's version. I know this information is inside the `data.release` string but adding the info on labels can add the possibility to use them for filtering.

This comes as a need from Kubernetic since it uses the ConfigMaps for retrieving information about the releases, instead of going through the helm CLI (This is done in order to get watchability of the releases to get real-time updates)

The wanted outcome is to get a link between charts -> releases as seen below:

![screen shot 2017-05-04 at 12 26 29](https://cloud.githubusercontent.com/assets/367397/25702739/ad8d6834-30d2-11e7-8c98-81cffa955c97.png)

In order to get that, we'll need the following labels on the ConfigMaps:

```
    CHART_NAME: pod-hello-world
    CHART_VERSION: 0.1.0
```

I have a PR ready if it is accepted as proposal.

**Comment by thomastaylor312** [comment]
@spiddy Feel free to open the PR if you already have one! It'll make the discussion easier. So are you saying the only thing that would be added is the chart version? I know the chart name is already in the release labels as you showed.

**Comment by technosophos** [comment]
I think release name is in the labels. We'd have to add chart name and version.
