### ISSUE TITLE
helm lint error around `.Capabilities.KubeVersion`

### ISSUE THREAD

**Issue by vdice** [kubernetes/helm#2393]
### Issue

`helm lint` gives the following error on a seemingly appropriate use of checking `.Capabilities.KubeVersion.Minor`:

```
 $ helm lint stable/spotify-docker-gc/
==> Linting stable/spotify-docker-gc/
...
[ERROR] templates/: render error in "spotify-docker-gc/templates/daemonset.yaml": template: spotify-docker-gc/templates/daemonset.yaml:6:25: executing "spotify-docker-gc/templates/daemonset.yaml" at <.Capabilities.KubeVe...>: can't evaluate field Minor in type *version.Info
```

### Details

The [chart](https://github.com/kubernetes/charts/pull/982) installs successfully and the template logic is evaluated as expected: yaml is not added if `KubeVersion.Minor` is less than 6, yaml is added if greater than or equal to 6.

The relevant template section looks like:
```
  {{- if ge .Capabilities.KubeVersion.Minor "6" }}
  updateStrategy:
    type: RollingUpdate
  {{- end }}
```

### Helm version
```
 $ helm version
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

**Comment by technosophos** [comment]
I suspect that Lint does not have an appropriately faked Kubernetes version field.

**Comment by abhijaypatne** [comment]
For those who are wondering about this issue, this has been fixed in `helm3.x`
