### ISSUE TITLE
Failed to install vendor dependencies on Windows

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#2396]
I'm unable to setup a windows environment to develop and build helm. When `glide install --strip-vendor` (which is in the ci.sh script for mac/nix based systems) doesn't run on Windows.

The error is:
```
[ERROR] Failed to set version on github.com/docker/distribution to cd27f179f2c10c5d300e6d09025b538c475b0d51: Unable to update checked out version
```

Docker distribution has a closed issue for this problem at https://github.com/docker/distribution/issues/1690. The commit that's locked is prior to the fix going in to Docker distribution.

**Comment by mattfarina** [comment]
This errant revision, `cd27f179f2c10c5d300e6d09025b538c475b0d51`, is what Kubernetes (tip of master right now) references. That's how it ends up in the lock file.

**Comment by thomastaylor312** [comment]
Thanks for catching this @mattfarina and reporting it upstream. I am going to keep this open so we can track. Can you update this issue if the k8s issue gets resolved?
