### ISSUE TITLE
Upgrade fails with "already exists"

### ISSUE THREAD

**Issue by atombender** [kubernetes/helm#2397]
This happens occasionally:

```
$ helm upgrade [...] picaxe-staging
Error: UPGRADE FAILED: release: already exists
```

Log:

```
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:15 storage.go:94: Listing all releases with filter
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:19 storage.go:133: Getting release history for 'picaxe-staging'
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:19 release_server.go:936: Executing pre-upgrade hooks for picaxe-staging
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:19 release_server.go:965: Hooks complete for pre-upgrade picaxe-staging
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:19 client.go:398: generating strategic merge patch for *runtime.Unstructured
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:19 client.go:398: generating strategic merge patch for *runtime.Unstructured
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:19 client.go:592: beginning wait for resources with timeout of 5m0s
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 release_server.go:936: Executing post-upgrade hooks for picaxe-staging
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 release_server.go:965: Hooks complete for post-upgrade picaxe-staging
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 storage.go:53: Updating "picaxe-staging" (v51) in storage
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 storage.go:45: Create release "picaxe-staging" (v52) in storage
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 release_server.go:936: Executing post-upgrade hooks for picaxe-staging
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 release_server.go:965: Hooks complete for post-upgrade picaxe-staging
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 storage.go:53: Updating "picaxe-staging" (v51) in storage
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 storage.go:45: Create release "picaxe-staging" (v52) in storage
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 release_server.go:936: Executing post-upgrade hooks for picaxe-staging
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 release_server.go:965: Hooks complete for post-upgrade picaxe-staging
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 storage.go:53: Updating "picaxe-staging" (v51) in storage
[tiller-deploy-3161650477-5jj7b] 2017/05/04 20:07:31 storage.go:45: Create release "picaxe-staging" (v52) in storage
```

We don't use any hooks.

Helm 2.3.0, Kubernetes 1.5.6.

**Comment by thomastaylor312** [comment]
Thank you for providing the logs on this. A few questions. How "occasionally" does this occur? Have you tried with helm 2.3.1 or 2.4.1 to see if it solves the problem?

**Comment by atombender** [comment]
It's only happened 2 times out of about 51 times so far, and it's not consistently reproducible, although I could of course write a stress-test script.

Only tried 2.3.0. Just installed 2.4.1, will let you know if it happens again.

**Comment by technosophos** [comment]
That typically happens if the release name is already present and being used. Do you have the `--install` flag set? Does the error only happen after an upgrade fails (or when the last upgrade is still in progres)?

**Comment by atombender** [comment]
Yes, we started using `helm upgrade --install`. And the release already exists when this happens.

**Comment by thomastaylor312** [comment]
@atombender Our friendly neighborhood bot reminded us that there hasn't been any activity. Are you still having this issue?

**Comment by HamzaK8s** [comment]
@thomastaylor312  @technosophos  I'm facing the same issue here, I can't do an upgrade over an existing resource, even thought I used hooks.

For instance, I already installed a release named myproject that had a secret
```
kind: Secret
metadata:
  name: secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    app: {{ .Values.global.environment.app }}
    environment: {{ $env }}
type: Opaque
{{- end }}

```

when I do  ```  helm upgrade --install --force project --tiller-namespace dev dev/ ``` I got this as result 

``` Error: UPGRADE FAILED: secrets "secret" already exists ```

Logs of Tiller:
```
[tiller] 2019/03/20 10:51:39 creating updated release for project
[storage] 2019/03/20 10:51:39 creating release "project.v2"
[tiller] 2019/03/20 10:51:39 performing update for project
[tiller] 2019/03/20 10:51:39 executing 2 pre-upgrade hooks for project
[kube] 2019/03/20 10:51:39 building resources from manifest
[kube] 2019/03/20 10:51:40 creating 1 resource(s)
[tiller] 2019/03/20 10:51:40 warning: Release project pre-upgrade project/templates/secret.yaml failed: secrets "secret" already exists
[storage] 2019/03/20 10:58:34 listing all releases with filter
```
Any help for this issue ?

Thank you

**Comment by tomislater** [comment]
I have encountered the same issue in Helm 3:

```
client.go:87: [debug] creating 377 resource(s)
Error: secrets "helm3-test-rabbitmq" already exists
helm.go:76: [debug] secrets "helm3-test-rabbitmq" already exists
```

I have run `helm upgrade --install`, so the namespace is nearly empty...

**Comment by technosophos** [comment]
@tomislater We need a little more information to debug that. Is the secret managed as a hook, or as a regular resource? If you can give us content of the secret's `metadata`, that might be helpful in figuring out why it is not upgrading. But if it is a hook, its behavior is subject to all the caveats described in the manual. Attempting to install over an existing secret that was created by a hook will still not work.

Again, though, I'm guessing about what your chart is trying to do... we really need more info to be able to provide any meaningful feedback. I would recommend opening a new issue with complete details, because I do not think it is the same issue as the one marked `Closed` here.

**Comment by tomislater** [comment]
@technosophos You are right, my issue is connected to https://github.com/helm/helm/issues/7093

Sorry for interruption!
