### ISSUE TITLE
helm plugin remove does not works as expected

### ISSUE THREAD

**Issue by sushilkm** [kubernetes/helm#2398]
Found that helm plugin remove has been coded to remove multiple plugins and the help also says so, but when executed with multiple arguments, it errors out saying that only one argument is supported.

```
$ helm plugin remove --help
remove one or more Helm plugins

Usage:
  helm plugin remove <plugin>... [flags]
....
....
$ helm plugin remove abc def ghi
Error: This command needs 1 argument: plugin
```

Also if remove is executed with a non-existent plugin it does not fails.
```
$ helm plugin list
NAME  	VERSION	DESCRIPTION
github	0.1.0  	This plugin provides GitHub services to Helm.
$ helm plugin remove abc
$ echo $?
0
```

**Comment by thomastaylor312** [comment]
Closed in #2400
