### ISSUE TITLE
Tiller tries to access API through TLS even if not configured

### ISSUE THREAD

**Issue by tiukhtinvladimir** [kubernetes/helm#2403]
Hello!

I am observing: "Cannot initialize Kubernetes connection: Get https://172.16.21.1:8080/api: http: server gave HTTP response to HTTPS client"

My env:
KUBERNETES_PORT=tcp://172.16.21.1:8080
KUBERNETES_SERVICE_PORT=8080
KUBERNETES_DASHBOARD_PORT=tcp://172.19.16.87:80
KUBERNETES_DASHBOARD_SERVICE_PORT=80
TILLER_DEPLOY_SERVICE_HOST=172.23.28.188
HOSTNAME=tiller-deploy-2264201710-9xgdw
SHLVL=1
HOME=/tmp
KUBERNETES_PORT_8080_TCP=tcp://172.16.21.1:8080
KUBERNETES_DASHBOARD_PORT_80_TCP_ADDR=172.19.16.87
TILLER_DEPLOY_PORT=tcp://172.23.28.188:44134
TILLER_DEPLOY_SERVICE_PORT=44134
KUBERNETES_DASHBOARD_PORT_80_TCP_PORT=80
TILLER_DEPLOY_PORT_44134_TCP_ADDR=172.23.28.188
KUBERNETES_DASHBOARD_PORT_80_TCP_PROTO=tcp
TILLER_DEPLOY_PORT_44134_TCP_PORT=44134
TILLER_DEPLOY_PORT_44134_TCP_PROTO=tcp
TERM=xterm
TILLER_DEPLOY_SERVICE_PORT_TILLER=44134
KUBERNETES_DASHBOARD_PORT_80_TCP=tcp://172.19.16.87:80
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TILLER_DEPLOY_PORT_44134_TCP=tcp://172.23.28.188:44134
KUBERNETES_SERVICE_PORT_HTTP=8080
PWD=/
KUBERNETES_SERVICE_HOST=172.16.21.1
KUBERNETES_PORT_8080_TCP_ADDR=172.16.21.1
KUBERNETES_DASHBOARD_SERVICE_HOST=172.19.16.87
KUBERNETES_PORT_8080_TCP_PORT=8080
KUBERNETES_PORT_8080_TCP_PROTO=tcp

Alto I noticed, that file /tmp/.kube/config ignored by tiller complitely.

**Comment by thomastaylor312** [comment]
This looks like there might be a problem even talking to Kubernetes. Do you have the tiller logs for when this happened?

**Comment by tiukhtinvladimir** [comment]
@thomastaylor312 thank you for your response. How to get logs? There is no --debug flag and

"Cannot initialize Kubernetes connection: Get https://172.16.21.1:8080/api: http: server gave HTTP response to HTTPS client"

is all what I get. But, at the same time I tried do 'strace /tiller' and saw, that it is reading /tmp/.kube/config file, but for some reason doesn't take configuration from it and use environment variables provided by kubernetes. Here is my /tmp/.kube/config:

/ # cat /tmp/.kube/config 
apiVersion: v1
clusters:
- cluster:
    server: 192.168.8.2:8080
  name: test
contexts:
- context:
    cluster: test
    user: ""
  name: test
current-context: test
kind: Config
preferences: {}
users: []

And my kubernetes service

root@k-master01:~# kubectl get svc kubernetes --namespace kube-system -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-05-05T10:01:52Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: kube-system
  resourceVersion: "3163650"
  selfLink: /api/v1/namespaces/kube-system/services/kubernetes
  uid: dcdd3e3a-3179-11e7-bcc9-5254008f1a20
spec:
  clusterIP: 172.16.21.1
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: ClientIP
  type: ClusterIP
status:
  loadBalancer: {}

**Comment by thomastaylor312** [comment]
What command are you running when you get this?

As for getting logs, you can them by finding the tiller pod with `kubectl get pods --namespace kube-system` and then use `kubectl logs --namespace kube-system <tiller-pod-name>` to get the logs

**Comment by tiukhtinvladimir** [comment]
@thomastaylor312 I am running ```helm init``` and  then, yes, I do ```kubectl logs deployment/tiller-deploy --namespace kube-system``` and getting this message. I then went further and implement SSL on a kubernetes API side and predictebly it started work. The question now is why tiller use https by default instead of pure http? Next question is why it ignores /tmp/.kube/config and use environmet variables instead?

**Comment by thomastaylor312** [comment]
@tiukhtinvladimir So by default Kubernetes uses https. The proxy is from a kubernetes library function that should honor all variables. As for why it is ignoring your config file, it looks like you haven't specified a `KUBECONFIG` environment variable. By default, it looks for the config at `~/.kube/config`. Try setting that env variable and give it a try

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
