### ISSUE TITLE
upgrade --install fails if release is not found

### ISSUE THREAD

**Issue by berndtj** [kubernetes/helm#2417]
As I understand upgrade should create the release if the --install flag is present and the release is not found.  Instead I get:

```
[django-ex (master)]$ helm upgrade berndtj/django-ex/master2 django-ex-0.1.0-build.001.tgz --install --reset-values --set image.repository=367199020685.dkr.ecr.us-west-2.amazonaws.com/photon/django-ex --set image.tag=21
Error: UPGRADE FAILED: Unable to lock release berndtj/django-ex/master2: release not found
```

**Comment by thomastaylor312** [comment]
@berndtj You are missing a positional argument here. You need to do `helm upgrade <chart_name> <chart_directory> <other_flags>`. Let me know if that works.

**Comment by berndtj** [comment]
It looks correct to me (though my example isn't good as the chart name is actually invalid).

```helm upgrade berndtj/django-ex/master2 django-ex-0.1.0-build.001.tgz --install --reset-values --set image.repository=367199020685.dkr.ecr.us-west-2.amazonaws.com/photon/django-ex --set image.tag=21```

chart name -> berndtj/django-ex/master2
chart directory -> django-ex-0.1.0-build.001.tgz
flags -> --install --reset-values --set image.repository=367199020685.dkr.ecr.us-west-2.amazonaws.com/photon/django-ex --set image.tag=21

Am I missing something?

The command works fine when the chart does exist.

**Comment by thomastaylor312** [comment]
@berndtj Actually I just had this happen to me...trying to figure out what caused it

**Comment by thomastaylor312** [comment]
And now I can't seem to duplicate it. What version of helm are you using @berndtj?

**Comment by berndtj** [comment]
```
[charts (master)]$ helm version
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

**Comment by bviolier** [comment]
We have run into the same issue. It used to work like this, but now it started giving an error. Not sure when it started doing this though.
```
$ helm version
Client: &version.Version{SemVer:"v2.3.1", GitCommit:"32562a3040bb5ca690339b9840b6f60f8ce25da4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

Syntax we use (and which used to work):
```
helm upgrade --install app-name helmet/app
```

It indeed still works perfectly when an install is already in place. 

I'm now gonna try installing the new client also, and seeing what happens then.

**Comment by bviolier** [comment]
Ok, for me this problem is fixed with the helm client upgrade.

**Comment by thomastaylor312** [comment]
@berndtj Can you confirm that this is fixed like @bviolier said?

**Comment by berndtj** [comment]
I was unable to reproduce the issue.  I'm fine with closing it for now.

**Comment by thomastaylor312** [comment]
Thank you! Let us know if you see any more problems

**Comment by ipedrazas** [comment]
I've verified it. If you do `helm upgrade --install` with helm `2.3.1` in the client and helm `2.4.2` on the server, you get this error. 

Once your client and server are in the same version everything works as expected
