### ISSUE TITLE
helm cannot connect to tiller  Error: forwarding ports:

### ISSUE THREAD

**Issue by Cryptophobia** [kubernetes/helm#2419]
Experiencing the following error when we try any helm command ` Error: forwarding ports: error upgrading connection: Upgrade request required`

When running the following command, get the following output:
```
$ helm version
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Error: cannot connect to Tiller
```

The kubernetes version and kubectl clients are:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.3", GitCommit:"ee39d359dd0896c4c0eccf23f033f158ad3d3bd7", GitTreeState:"clean", BuildDate:"2017-05-05T16:33:32Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
```

It seems from every issue that can be followed is that the tiller service is not forwarded properly behind the aws loadbalancer or that tiller is not exposing correctly.

Any help would be greatly appreciated.

**Comment by bacongobbler** [comment]
related issue: https://github.com/kubernetes/helm/issues/1505

**Comment by Cryptophobia** [comment]
@bacongobbler : Just tried `v2.0.0-beta.2` same issue is persisting.

**Comment by bacongobbler** [comment]
on v2.4.1, can you please post the output of `kubectl -n kube-system get pods`? I wonder if it's because Helm is incompatible with v1.7.0-alpha.3 considering that there have been API incompatibility issues before. v2.4.1 should work just fine on kubernetes v1.6, so I'd try that as well.

**Comment by Cryptophobia** [comment]
@bacongobbler , earlier we tried the combination of the latest helm v2.4.1 with kubernetes v1.6 and it did not work. Same errors messages. That's why we upgraded to v1.7.0-alpha.3 so that maybe we will take advantage of a new feature added to kubernetes - http2 enabled nginx config because it looked like the helm client was forcing http2 instead of http request to the tiller service...

**Comment by Cryptophobia** [comment]
@bacongobbler , we really think this is a loadbalancer issue and kubernetes and tiller-deploy cannot port forward behind the AWS loadbalancer.

**Comment by Cryptophobia** [comment]
The PR in kubernetes witht he http2 enabled nginx config is this one: https://github.com/kubernetes/kubernetes/pull/43625

**Comment by shnassar** [comment]
@Cryptophobia been playing around with this and found you are indeed correct. I have an AWS LB in front of my apiserver and noticed when I fixed the certs there (since kops doesn't install any) helm stopped working.

Just found I could fix this by changing the LB's listener protocol from HTTPS to SSL. With that saved (took couple takes damn AWS) helm was happy again and stopped throwing those errors.

Hope this helps!!

**Comment by Cryptophobia** [comment]
@shnassar, this is great to know! Such a simple fix. We will try it out and get back to this thread. Thanks for putting your fix here.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
