### ISSUE TITLE
Support Tiller installs in clusters with Windows nodes

### ISSUE THREAD

**Issue by seanknox** [kubernetes/helm#2420]
Now that nodes can run Windows or Linux, we can no longer assume Tiller will be scheduled to a Linux node. 

On such clusters, `helm init` often fails when the Tiller pod is scheduled to a Windows node. Perhaps we could hardcode a node selector with `beta.kubernetes.io/os=linux` as an easy workaround?

**Comment by thomastaylor312** [comment]
Good catch @seanknox. I'll label this as a bug and see if we can get in a temporary fix and figure out a longer term one as well.

**Comment by pedershk** [comment]
Following this as I've attempted and failed to install Tiller on a mixed-node cluster. Can provide logs etc. if you need it.

**Comment by technosophos** [comment]
@seanknox Is that label the right one for node selection?

**Comment by seanknox** [comment]
I *think* so. Will doublecheck.

**Comment by seanknox** [comment]
@technosophos yep, `beta.kubernetes.io/os=linux` appears to be the label to use.

https://kubernetes.io/docs/reference/labels-annotations-taints/#betakubernetesioos

**Comment by kfox1111** [comment]
if --node-selectors was available, that could be used too. you would label your nodes that helm could land on, or use an existing label for controller nodes. That would pin them away from windows computes.

**Comment by thomastaylor312** [comment]
So do we want to wait for `--node-selectors` to be implemented or do we still want a quick fix with a hard-coded annotation?

**Comment by seanknox** [comment]
What's the timeline for node selectors? If it's > 1 month I'd advocate for taking on a teeny bit of tech debt with hard coding now with for the benefit of bringing a slew of very hungry Helm users in the short term.

**Comment by thomastaylor312** [comment]
I am waiting to hear back on #2299, if it doesn't look like it will land in 2.5, I will implement this fix

**Comment by tesharp** [comment]
Was just trying a mixed cluster aswell, and ran into this. Would be nice with a quick fix

**Comment by bacongobbler** [comment]
When I'm at my desktop tomorrow, I'll give you a set of manifests which you can use to install v2.4.2 on a mixed node cluster via kubectl. `helm init` is more or less just a call to `kubectl create` plus some client-side bootstrapping.

**Comment by technosophos** [comment]
@thomastaylor312 I think we should do a quick fix for this in 2.4.3 or 2.4.4. It should just be a matter of adding the right line in the `cmd/helm/installer` setup for that Deployment.

**Comment by thomastaylor312** [comment]
I can do that tonight @technosophos

**Comment by rong0312** [comment]
Is this issue still no fixed?
I am facing this issue with the image 

gcr.io/kubernetes-helm/tiller:v2.14.3

**Comment by bacongobbler** [comment]
This was implemented over 2 years ago in #2544. Can you share more information in a new ticket please?

Also note that since tiller has been removed in Helm 3, this is no longer an issue in the next major release.
