### ISSUE TITLE
kubernetes helm start failed

### ISSUE THREAD

**Issue by sky-big** [kubernetes/helm#2422]
Hi,

I am trying on Ubuntu16.04 Kubernetes cluster install helm,but falied. Cluster started on two VM Ubuntu16.04.

kubernetes version:
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

helm version:
Client: &version.Version{SemVer:"v2.3.0", GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:"clean"}
Error: cannot connect to Tiller

Kubernetes cluster current pod:
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE       IP           NODE
default       busybox                                 1/1       Running   3          3h        10.1.46.3    192.168.152.134
kube-system   heapster-632696550-5tx12                1/1       Running   0          58m       10.1.46.7    192.168.152.134
kube-system   kube-dns-2852338463-c1mln               3/3       Running   0          58m       10.1.46.6    192.168.152.134
kube-system   kubernetes-dashboard-2852712022-5tk2k   1/1       Running   0          58m       10.1.46.10   192.168.152.134
kube-system   monitoring-grafana-3975459543-j1mhv     1/1       Running   0          58m       10.1.46.8    192.168.152.134
kube-system   monitoring-influxdb-3480804314-gg7pp    1/1       Running   0          58m       10.1.46.9    192.168.152.134
kube-system   tiller-deploy-1172528075-j2kxf          0/1       Running   16         33m       10.1.61.2    192.168.152.132

helm tiller logs:

Name:		tiller-deploy-1172528075-j2kxf
Namespace:	kube-system
Node:		192.168.152.132/192.168.152.132
Start Time:	Wed, 10 May 2017 14:48:58 +0800
Labels:		app=helm
		name=tiller
		pod-template-hash=1172528075
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-1172528075","uid":"be5c1c18-354c-11e7-b9f2-000...
Status:		Running
IP:		10.1.61.2
Controllers:	ReplicaSet/tiller-deploy-1172528075
Containers:
  tiller:
    Container ID:	docker://ac577cf9009f1722b4e2c231157b994e907ee66a3edebe6db38cbfe13f29816c
    Image:		gcr.io/kubernetes-helm/tiller:v2.3.0
    Image ID:		docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:fc5bef1464e78abe683c3e9e5e52dcb89111ab129049f8b3819eb157716fe4f7
    Port:		44134/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	2
      Started:		Mon, 01 Jan 0001 00:00:00 +0000
      Finished:		Wed, 10 May 2017 15:22:28 +0800
    Ready:		False
    Restart Count:	16
    Liveness:		http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:	kube-system
    Mounts:		<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:	<none>
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----				-------------		--------	------		-------
  34m		34m		1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal		Pulling		pulling image "gcr.io/kubernetes-helm/tiller:v2.3.0"
  34m		34m		1	default-scheduler					Normal		Scheduled	Successfully assigned tiller-deploy-1172528075-j2kxf to 192.168.152.132
  33m		33m		1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal		Pulled		Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.3.0"
  33m		33m		1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal		Created		Created container with id 1fe8236f1d196a6ce50c5b671544e940612de25120c3732763733b384dfafb73
  33m		33m		1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal		Started		Started container with id 1fe8236f1d196a6ce50c5b671544e940612de25120c3732763733b384dfafb73
  33m		33m		1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal		Created		Created container with id d0e810b6bc59ce7eba018c3e08ec515372b6e0dbe0bf820ec52b37dee8acac1c
  33m		33m		1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal		Started		Started container with id d0e810b6bc59ce7eba018c3e08ec515372b6e0dbe0bf820ec52b37dee8acac1c
  33m		33m		1	kubelet, 192.168.152.132				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 10s restarting failed container=tiller pod=tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)"

  33m	33m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Created		Created container with id 1facd6660d1f3511017b43756c90e266af22fa2e596c8246099a8768c62db339
  33m	33m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Started		Started container with id 1facd6660d1f3511017b43756c90e266af22fa2e596c8246099a8768c62db339
  33m	33m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Started		Started container with id 5be6c4b863516d248d4df3e73709a665b609cade6d82bc4324d9b644521c4846
  33m	33m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Created		Created container with id 5be6c4b863516d248d4df3e73709a665b609cade6d82bc4324d9b644521c4846
  33m	33m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://1facd6660d1f3511017b43756c90e266af22fa2e596c8246099a8768c62db339:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  32m	32m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://5be6c4b863516d248d4df3e73709a665b609cade6d82bc4324d9b644521c4846:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  32m	32m	5	kubelet, 192.168.152.132				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 40s restarting failed container=tiller pod=tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)"

  32m	32m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Started		Started container with id eb508f304999692f07ad6d6557ce2e4c044b8c1a8e4ff64517f0a247e164b206
  32m	32m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Created		Created container with id eb508f304999692f07ad6d6557ce2e4c044b8c1a8e4ff64517f0a247e164b206
  31m	31m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://eb508f304999692f07ad6d6557ce2e4c044b8c1a8e4ff64517f0a247e164b206:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  31m	30m	8	kubelet, 192.168.152.132				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=tiller pod=tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)"

  30m	30m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Created		Created container with id e0e314dce369e133ada927934cfc6a1191544fcfee5d1a27ee90e0283ffcef11
  30m	30m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Started		Started container with id e0e314dce369e133ada927934cfc6a1191544fcfee5d1a27ee90e0283ffcef11
  30m	30m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://e0e314dce369e133ada927934cfc6a1191544fcfee5d1a27ee90e0283ffcef11:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  30m	27m	14	kubelet, 192.168.152.132				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=tiller pod=tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)"

  27m	27m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Created		Created container with id 07cd165c285fea6b65c038e05e87af034f30d94d36a6875767483c0188caee1b
  27m	27m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Started		Started container with id 07cd165c285fea6b65c038e05e87af034f30d94d36a6875767483c0188caee1b
  27m	27m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://07cd165c285fea6b65c038e05e87af034f30d94d36a6875767483c0188caee1b:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  22m	22m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Started		Started container with id b173b41ccc90062c126f058934050d2416a56e0547df363e6b3e2812eec6c076
  22m	22m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Created		Created container with id b173b41ccc90062c126f058934050d2416a56e0547df363e6b3e2812eec6c076
  22m	22m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Started		Started container with id 249be2bdb471030e4d157a2699134f1b2a699c8b08d93257edc0a5703e6fd21b
  22m	22m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://b173b41ccc90062c126f058934050d2416a56e0547df363e6b3e2812eec6c076:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  22m	22m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Created		Created container with id 249be2bdb471030e4d157a2699134f1b2a699c8b08d93257edc0a5703e6fd21b
  22m	22m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://249be2bdb471030e4d157a2699134f1b2a699c8b08d93257edc0a5703e6fd21b:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  16m	16m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://4e4c5ece2388651129b6a8d661d4d54e649a886be4a0f9245f5bf51c6992f95f:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  16m	16m	1	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		Killing container with id docker://599c22c2e39fb736ee7f579d43fe9f3dfd4965ef07cf15533bf3da14ec5e5828:pod "tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)" container "tiller" is unhealthy, it will be killed and re-created.
  33m	48s	16	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Pulled		Container image "gcr.io/kubernetes-helm/tiller:v2.3.0" already present on machine
  16m	48s	8	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Created		(events with common reason combined)
  16m	48s	8	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Started		(events with common reason combined)
  11m	38s	6	kubelet, 192.168.152.132	spec.containers{tiller}	Normal	Killing		(events with common reason combined)
  27m	10s	126	kubelet, 192.168.152.132				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=tiller pod=tiller-deploy-1172528075-j2kxf_kube-system(be5e55de-354c-11e7-b9f2-000c29722a26)"

  33m	10s	154	kubelet, 192.168.152.132	spec.containers{tiller}	Warning	BackOff	Back-off restarting failed container

Kubernetes Cluster used flanned network plugin

/coreos.com/network/subnets/10.1.46.0-24
/coreos.com/network/subnets/10.1.61.0-24

How can i success work?

**Comment by technosophos** [comment]
Kubernetes is misconfigured. Please read through the install.md and install_faq.md documents. I think you might find the answer in there.

**Comment by gayanjay** [comment]
@sky-big, Did you find a way to make this work? Do you have this issue yet?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
