### ISSUE TITLE
Helm upgrade with --wait is waiting even when all resources are ready

### ISSUE THREAD

**Issue by eduardobaitello** [kubernetes/helm#2426]
I just installed a new release, then I upgraded the `image` tag for one of my Deployments inside a chart.
After that, I executed a `helm upgrade mychart myrelease --wait --timeout 9999`. Tiller logs only detected changes in the above described Deployment, creating a new pod and ReplicaSet with the new image. Then, the upgrade process get stuck in "waiting for resources", even when all my pods are ready and running:

```
[user@hostname ~]$ kubectl get po -n mynamespace
NAME                                         READY     STATUS    RESTARTS   AGE
XXXXX-2061248956-1k0xc                       1/1       Running   0          14m
XXXXXXXX-3687332959-bjb5b                    1/1       Running   0          14m
new-created-pod-2470432599-38k9j             1/1       Running   0          1m
XXXXXX-1811469710-3pm6k                      1/1       Running   0          14m
XXX-2438109-qv4m1                            1/1       Running   0          14m
```
```2017/05/10 18:24:01 wait.go:47: beginning wait for resources with timeout of 2h46m39s```

So I figured out that the problem is that a new ReplicaSet was created, but helm seems like also waiting  for the old one to get all resources ready.
I manually deleted the `old-replica-set-320589364`, and the upgrade was completed.
```
[user@hostname ~]$ kubectl get rs -n mynamespace
NAME                                   DESIRED   CURRENT   READY     AGE
XXXXX-2061248956                       1         1         1         21m
XXXXXXXX-3687332959                    1         1         1         21m
new-created-replica-set-2470432599     1         1         1         7m
old-replica-set-320589364              0         0         0         21m
XXXXXX-1811469710                      1         1         1         21m
XXX-2438109                            1         1         1         21m
```
I'm using Kubernetes `v1.6.0` with Helm `v2.4.1`

**Comment by blakebarnett** [comment]
Seeing this also, k8s 1.6.2, helm 2.4.1

**Comment by thomastaylor312** [comment]
@eduardobaitello Thank you for all of the details. I'll look to see what is happening

**Comment by thomastaylor312** [comment]
@eduardobaitello Can you give #2430 a try if you have some time and see if it solves the issue for you?

**Comment by eduardobaitello** [comment]
@thomastaylor312, thanks for the quick help!
I don't have expertise in Go lang, so a I need to wait a patch release with the fix :(
Thanks again!

**Comment by chancez** [comment]
I'm still having problems in 2.4.2 with this. Even if I've changed nothing in my release, tiller ends up waiting the full timeout, and no pods are unready, nothing even changed, so everything is already ready, but the wait seems to not detect this.

**Comment by eduardobaitello** [comment]
@chancez check the `maxUnavailable` value of your Deployments. The `--wait` flag now uses this value for check the "resources ready" condition (Take a look at [Notes](https://github.com/kubernetes/helm/blob/v2.4.2/docs/using_helm.md#helpful-options-for-installupgraderollback)).

**Comment by donaldguy** [comment]
can confirm that after upgrading to 2.4.2 I am also having a similar problem (but on a Deployment with `strategy: {   type: Recreate } ` )

**Comment by donaldguy** [comment]
In my case downgrading to 2.4.1 fixes my issue, so #2430  is directly implicated

**Comment by donaldguy** [comment]
admittedly my issue may be want of kubernetes/kubernetes#41740 (obviously I unlike the other in this thread am not on 1.6 yet)

**Comment by chancez** [comment]
I only tried 2.3.2 (works) and 2.4.2 (doesn't work), so I'll also give 2.4.1 a shot to see if I can help ensure it's just something in 2.4.2 (rather than the must larger 2.3.2 -> 2.4.2 set of change).

**Comment by thomastaylor312** [comment]
I am going to reopen this one due to the multiple people having issues. If you have a chart that you can share (or one of the main stable charts) when this issues happens, please let me know because I tried several charts and had issues duplicating this

**Comment by tyrannasaurusbanks** [comment]
FWIW, I thought I'd hit this bug but upon inspection it was because I was using an external service - proposed a fix for external services here: https://github.com/kubernetes/helm/pull/2497

Thought I'd mention in case anyone viewing this is using external services too.

**Comment by chancez** [comment]
I tested with 2.4.1, it has the same issue as 2.4.2, so it's definitely something about 2.4.x, but not sure where.

**Comment by chancez** [comment]
I'd also like to note I'm not using externalServices, my deployments are all at their desired replica count, no pods are unready, etc.

**Comment by chancez** [comment]
Tiller logs are this, https://gist.github.com/chancez/2d632496799632298efa0ccf9fa70f9d but I don't have the output of the resources at the time. I can assure you that they're in an unchanged state since I'm testing the helm upgrade without having made any changes, as the logs indicate. I'll try to get another helm run with 2.4.2 as well as the kubectl output.

**Comment by jagregory** [comment]
FWIW, I'm seeing this with `helm install --wait` too. v2.4.2

**Comment by prat0318** [comment]
I am also facing the issue with v2.4.2 even if no dead replica set is present in the list.

And `v2.4.1` doesn't do a proper `wait` and returns back success even in between of deployment roll happening in progress.

**Comment by cbelsole** [comment]
This is happening for me in the case of a deployment where I have `replicaCount: 1` and no deploy strategy. It seems like the default `maxUnavailable` is:

> Deployment can ensure that only a certain number of Pods may be down while they are being updated. By default, it ensures that at least 1 less than the desired number of Pods are up (1 max unavailable).

> `.spec.strategy.rollingUpdate.maxUnavailable` is an optional field that specifies the maximum number of Pods that can be unavailable during the update process. The value can be an absolute number (e.g. 5) or a percentage of desired Pods (e.g. 10%). The absolute number is calculated from percentage by rounding down. This can not be 0 if .spec.strategy.rollingUpdate.maxSurge is 0. By default, a value of 25% is used.

So since the default for `maxUnavailable` is `> 1` the deployment is allowed to go since this is the metric we are using to decide the threshold. https://github.com/kubernetes/helm/blob/master/pkg/kube/wait.go#L168

I confirmed this by setting `maxUnavailable` to `0`. This caused the `--wait` to act as normal.

**Comment by thomastaylor312** [comment]
@cbelsole That is expected behavior for `--wait` in this case. We do have it documented in Helm's documentation.

**Comment by whereisaaron** [comment]
After upgrading from 2.3 to 2.4.2 all my deployments starting failing on the `--wait` stage. Even through the deployment completes successfully in k8s, everything is Ready and running, helm just sits there waiting for some unspecified condition.

```
2017/06/12 18:07:16 wait.go:47: beginning wait for resources with timeout of 10m0s
2017/06/12 18:17:16 release_server.go:329: warning: Upgrade "my-test" failed: timed out waiting for the condition
```

```
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
```

**Comment by whereisaaron** [comment]
I saw @eduardobaitello's note about `maxUnavailable` but I am using the default values, so if anything `--wait` should not wait at all, since there is always >= 1-1=0 replicas available (desired replicas - maxUnavailable). Instead, since upgrading to 2.4.2 it waits forever.

```
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```

Looking at the code it appears to be waiting for the number of Ready replicas to be >= maxUnavailable, rather than waiting for (Ready replicas >= (Desired replicas-maxUnavailable)) as the documentation says it should. Am I reading that correctly?

That confuses me as to the changed behaviour in 2.4.2. Unless this code is looking at the old ReplicaSet rather than the new one? Then it would never succeed unless you set maxUnavailable to zero as @cbelsole reported. OK, I'm just plain confused :-)

https://github.com/kubernetes/helm/blob/master/pkg/kube/wait.go#L168
```
func deploymentsReady(deployments []deployment) bool {
	for _, v := range deployments {
		if !(v.replicaSets.Status.ReadyReplicas >= *v.deployment.Spec.Replicas-deploymentutil.MaxUnavailable(*v.deployment)) {
			return false
		}
	}
	return true
}
```

**Comment by thomastaylor312** [comment]
@whereisaaron So it is waiting for (Ready replicas >= (Desired replicas-maxUnavailable)) in the code you posted. The desired replicas - maxUnavailable is `*v.deployment.Spec.Replicas-deploymentutil.MaxUnavailable(*v.deployment)`. And it [should be looking at the new replica set](https://github.com/kubernetes/helm/blob/master/pkg/kube/wait.go#L82).

Do you have the chart available for me to test with? The problem I am having is that I haven't been able to duplicate this with the charts I have tried, so anything that would help me duplicate would be appreciated.

**Comment by baracoder** [comment]
We have the same problem with kubernetes 1.6.4 and tested helm 2.4.1 2.4.2 and 2.5.0 2.3.x does not wait for deployments to get ready

**Comment by thomastaylor312** [comment]
@baracoder Did you test with an internal chart or with one you can share? I'd love to get my hands on one that isn't working so I can figure this out

**Comment by baracoder** [comment]
@thomastaylor312 I created a sample to reproduce it. 

Funny enough I deployed it on GKE by accident and it worked like expected, but it fails in our local CoreOS cluster, both having kubernetes 1.6.4 and helm/tiller 2.5.0

Here the sample I used. The resulting logs are in the readme https://github.com/baracoder/helm-wait-sample

**Comment by baracoder** [comment]
I can also reproduce with the same sample and  minikube version: v0.17.1

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by thomastaylor312** [comment]
Thank you so much @baracoder! I'll take a look at that

**Comment by thomastaylor312** [comment]
Ok, I narrowed down where this is happening. I could not duplicate this on 1.6.4 (on Minikube), but I could duplicate the issue with 1.5.3 (on Minikube). The problem is that the new replica set is returning `nil` due to the fact that [this line](https://github.com/kubernetes/kubernetes/blob/ee4f635d6160ce973d8fd3db11564c6999de349a/pkg/controller/deployment/util/deployment_util.go#L567) doesn't return a controller for the deployment. 

@adamreese I went as far down the stack as I understand, do you have any idea what could be causing this?

**Comment by whereisaaron** [comment]
Thanks @thomastaylor312! Hopefully you're on the trail. Did that code differ between helm 2.3.x and 2.4.x? As we didn't see this issue with 2.3.x with everything else being identical.

In case it is relevant I am also using coreos clusters (kube-aws) like @baracoder. And the cluster it failed in was k8s 1.5.x.

**Comment by thomastaylor312** [comment]
@whereisaaron We made a change to be smarter with `--wait` and `Deployment` objects between 2.3 to 2.4. We found one bug that we had to patch with a similar issue. So we'll be working to figure this out

**Comment by seh** [comment]
If the _ReplicaSet_ either lacks an owner reference or has it set improperly, here's a place to look for telltale signs of failure: [`(*DeploymentController).getReplicaSetsForDeployment`](https://sourcegraph.com/github.com/kubernetes/kubernetes@ee4f635d6160ce973d8fd3db11564c6999de349a/-/blob/pkg/controller/deployment/deployment_controller.go#L494-522).

**Comment by thomastaylor312** [comment]
Is there something with how that is working in k8s 1.5?

**Comment by seh** [comment]
According to the VCS, that area of the code has [seen some action](https://github.com/kubernetes/kubernetes/blame/ee4f635d6160ce973d8fd3db11564c6999de349a/pkg/controller/deployment/deployment_controller.go#L494-L522) over the last eight months. Issue kubernetes/kubernetes#33845 and PR kubernetes/kubernetes#35676 sound relevant, and the latter looks like it didn't make it in until version 1.6.

**Comment by whereisaaron** [comment]
Hi @thomastaylor312 just upgraded to helm 2.5.1 for a k8s 1.5 cluster and can confirm this problem still exists. A `helm upgrade --install` will wait long after all the resources are ready and until the timeout is reached, then report the deployment as failed, even though the deployment was successful.

```
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```

helm 2.3 was the last version of `helm` where `--wait` worked for k8s 1.5 clusters. I test after each helm upgrade and `--wait` has never worked again.

```
+ helm upgrade --install --wait --timeout 600 ...
Error: UPGRADE FAILED: timed out waiting for the condition
```

**Comment by erichaase** [comment]
Upgrading to a 1.7 k8s cluster resolved this issue for me!

**Comment by boosh** [comment]
I'm seeing this with helm 2.7.2 on k8s 1.8.3-gke.0.

In my dev env with `replicas: 1` it works fine. In staging with `replicas: 2` helm hangs for the full duration of the timeout, yet all pods are running. The pod uses the following deployment strategy:

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

The only other thing to note is this chart runs a batch job as a post-install task. Even when that job finishes, helm still hangs though.

**Comment by thomastaylor312** [comment]
@boosh Do both of your pods show up as ready while it is hanging?

**Comment by boosh** [comment]
@thomastaylor312 Yes

**Comment by alexppg** [comment]
Hi, is there a solution to this in a 1.5.* cluster?

**Comment by whereisaaron** [comment]
@alexppg no, and even on the latest version I find it problematic/unreliable. I just don't use the `--wait` option any more. Better to deploy and then script your own wait-for-ready step.

**Comment by alexppg** [comment]
Shouldn't then be an opened issue about it?  This or any other one. 

PD: thanks, I'll do that. @whereisaaron

**Comment by MalhotraVijay** [comment]
We are also getting this issue with the helm version v2.10.0 version on Kubernetes version v1.8.2

> Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

We have an internal chart, which we intend to upgrade via the CI/CD pipeline using the following command and the upgrade process keeps on waiting. 

> helm upgrade <chart_release> <chart> --debug --wait 

We then have to kill the process and the chart release history show 'PENDING_UPGRADE' for  some unknown amount of time before either it says DEPLOYED during some builds or Upgrade "<chart_release>" failed: timed out waiting for the condition

Is this solved or are we missing something ?

**Comment by Brightside56** [comment]
I have same issue with install/update with --wait

**Comment by KIVagant** [comment]
Same here.
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

```
# helm upgrade ... --wait 900 ... shows:
Error: UPGRADE FAILED: timed out waiting for the condition

...
# helm status shows
LAST DEPLOYED: Fri Oct  5 14:04:23 2018
NAMESPACE: default
STATUS: FAILED```

But all resources were created.

**Comment by KIVagant** [comment]
Looks like this workaround suggested by @tcolgate is also working for this issue. I just fixed FAILED release using `helm rollback myproject 16` where 16 was "FAILED" release.

https://github.com/helm/helm/issues/3208#issuecomment-427451507

**Comment by KIVagant** [comment]
Looks like in my case there was a real problem. One of the pods stuck in `Pending` state with the error: `0/6 nodes are available: 2 node(s) had taints that the pod didn't tolerate, 4 Insufficient cpu.`

I added one more node and now it works!

**Comment by smileusd** [comment]
daemonset have the same problem

**Comment by lm-xingxing** [comment]
use --debug only(no --wait), to see which resource is pending, maybe it different from chart defined ,that cause pending

**Comment by Emixam23-FCMS** [comment]
Hey guys, still having the issue, any idea? Currently using helm image 3.2.0

**Comment by piratf** [comment]
Same issue. All pods are running, but helm upgrade still waiting.

version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

**Comment by zhilyaev** [comment]
The same problem
