### ISSUE TITLE
Question : customize upgrade/rollback strategy on k8s possible ?

### ISSUE THREAD

**Issue by chrisLeeTW** [kubernetes/helm#2435]
currently it will cause disconnect when helm do upgrade / rollback.

We need a really non-stop deployment strategy.

So could we accomplish that, maybe via plugins ?

BR

Chris

**Comment by technosophos** [comment]
You can integrate a custom Rudder (Tiller plugin) to do that once 2.5.0 is released.

/cc @nebril

**Comment by chrisLeeTW** [comment]
@technosophos thanks for the quick response.

It's really a great news. I'm really looking forward.

Cheers

Chris

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity since helm 2.5 was released several months ago, but please re-open if this still needs to be addressed. Thanks!
