### ISSUE TITLE
Helm doesn't delete removed requirement

### ISSUE THREAD

**Issue by olalonde** [kubernetes/helm#2439]
I deleted a requirement from my `./helm/infra/requirements.yaml`, did `helm dependency update ./helm/infra`, followed by `helm upgrade -i infra ./helm/infra`. I noticed that helm didn't delete the pods related to that requirement. Is this expected behavior? How should I otherwise delete that requirement's resources?

```
$ helm version
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

**Comment by technosophos** [comment]
This is expected behavior.

- It is legal to have a subchart that is not in requirements.yaml
- IIRC, a `helm delete` would have removed the old resources.

**Comment by olalonde** [comment]
Ok, thanks.
