### ISSUE TITLE
Fail to build Tiller locally from source

### ISSUE THREAD

**Issue by willise** [kubernetes/helm#2445]
I followed the instructions shown below to install tiller locally.
https://github.com/kubernetes/helm/blob/master/docs/install.md#from-source-linux-macos

During cmd `make bootstrap build`  execution, an error was raised.
`[INFO]  --> Fetching github.com/docker/docker.`
`[INFO]  --> Fetching k8s.io/kubernetes.`
`[WARN]  Unable to checkout bitbucket.org/ww/goautoneg`
`[ERROR] Update failed for bitbucket.org/ww/goautoneg: Unable to get repository`

Maybe some pre-checks can be used to validate the repos referred.

**Comment by bacongobbler** [comment]
I was not able to reproduce this. Fetching goautoneg works for me locally, so perhaps you may be having connectivity issues or bitbucket was temporarily down?

Here's my build, running from a container to demonstrate that I'm building from a clean working directory:

```
><> docker run -itw /go/src/k8s.io golang bash
root@db11976957c1:/go/src/k8s.io# git clone https://github.com/kubernetes/helm
Cloning into 'helm'...
remote: Counting objects: 19228, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 19228 (delta 3), reused 0 (delta 0), pack-reused 19215
Receiving objects: 100% (19228/19228), 4.88 MiB | 0 bytes/s, done.
Resolving deltas: 100% (11941/11941), done.
Checking connectivity... done.
root@db11976957c1:/go/src/k8s.io# cd helm/
root@db11976957c1:/go/src/k8s.io/helm# make bootstrap build
make: glide: Command not found
go get -u github.com/Masterminds/glide
go get -u github.com/mitchellh/gox
glide install --strip-vendor
[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching bitbucket.org/ww/goautoneg
[INFO]	--> Fetching cloud.google.com/go
...
go build -o bin/protoc-gen-go ./vendor/github.com/golang/protobuf/protoc-gen-go
scripts/setup-apimachinery.sh
GOBIN=/go/src/k8s.io/helm/bin go install  -tags '' -ldflags ' -X k8s.io/helm/pkg/version.GitCommit=35aabdb61a18cf57e6a814d7336097492e9ffac1 -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
root@db11976957c1:/go/src/k8s.io/helm# ls bin/
helm  protoc-gen-go  rudder  tiller
root@db11976957c1:/go/src/k8s.io/helm# ./bin/helm version --client     
Client: &version.Version{SemVer:"v2.4+unreleased", GitCommit:"35aabdb61a18cf57e6a814d7336097492e9ffac1", GitTreeState:"clean"}
```

The error `Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'` definitely looks actionable, however.

**Comment by willise** [comment]
I can download other repos except `goautoneg`. Maybe the firewall screwed up the connectivity.
Thanks.
