### ISSUE TITLE
Client: DM commands

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#245]
The `helm dm...` commands are:

- `helm dm install`: Install DM on a cluster
- `helm dm uninstall`: Uninstall DM on a cluster
- `helm dm status`: Show status of a DM cluster (healthz?)
- `helm dm target`: Show the connection details of the DM cluster we're currently pointing to

The `helm dm install` command is used when `helm init` has already been run once, but we are pointing to another cluster and want to install there.

**Comment by michelleN** [comment]
Update on this issue:
`helm dm install` and `helm dm uninstall` currently work as intended, although I'm having a hard time pulling the image.
`helm dm target` is a wrapper around `kubectl cluster-info` and works as intended. 
The only command not implemented here is `helm dm status` so I broke it out into it's own issue (see #301) for more discussion/isolation.

**Comment by technosophos** [comment]
Based on conversations in Slack, we're going to `s/dm/server/` on this one.

**Comment by michelleN** [comment]
:+1:
