### ISSUE TITLE
Proposal: Add a field named `Options` to chart metadata

### ISSUE THREAD

**Issue by kdada** [kubernetes/helm#2450]
I can find some infomation from `Chart.yaml` .  When I create a chart, I want add some other filed like `create time` because of my product. but I need save it in db and search it from db now.

If metadata have a field like:
```yaml
options:
  key: value
```

Then I can place some useful info in it.

**Comment by technosophos** [comment]
How would this differ from just putting this information inside of your chart's `values.yaml`?

**Comment by kdada** [comment]
`value.yaml` is used for generating kubernetes resource files. It's a runtime data for release. But `Chart.yaml` is static and sometimes constant. We always stores metadata in it. So I think `Chart.yaml` can be more flexible by adding some universal fields.
