### ISSUE TITLE
Sharing Templates with Subcharts is inconsistent in which template is used

### ISSUE THREAD

**Issue by twk3** [kubernetes/helm#2452]
Sharing Template With subcharts, a feature documented in the [chart template guide](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#sharing-templates-with-subcharts), appears to be inconsistent on which template will be used.

**Problem:**

If you have the same named template in both a parent and sub chart, it is random which template will be used.

**Why:**

Templates are being iterated and parsed in random order, (how golang's map/range works) here: https://github.com/kubernetes/helm/blob/master/pkg/engine/engine.go#L185

And it doesn't appear there is anything in place that is meant to ensure the parent templates override the subcharts.

**Comment by twk3** [comment]
This appears to me, to  also be related to the problems encountered in this issue: https://github.com/kubernetes/helm/issues/2221

**Comment by technosophos** [comment]
This is a known issue. We're trying to devise a workaround that would allow the creation of "library charts", which would be stored once per chart, even if subcharts used them. If you have any ideas about how that might look for the template developer, let us know.

**Comment by technosophos** [comment]
I think we'd also welcome a PR that sorts the templates inside of that function (e.g. does not change the function signature, but gives predictable ordering). An reverse alphabetical sort would have the nice side effect of making the shorter paths (umbrella charts) take precedence over the nested charts.
