### ISSUE TITLE
Proposal: Interactive acceptance of license(s)

### ISSUE THREAD

**Issue by krancour** [kubernetes/helm#2468]
Separate from a chart's own license, the software installed _by_ a chart might have its own license (which, for the sake of discussion, might not even be open source) and which may require explicit acceptance by the end user.

I want to propose a feature whereby `chart.yaml` could include text and/or links to 0..n software licenses that must be displayed to then explicitly and interactively accepted by the operator performing the installation. Ideally, this acceptance would be repeated on upgrade as well, since it's possible that terms change from one iteration of a chart to the next.

I hypothesize that providing this feature may pave the way for the construction and release of Helm charts that package commercial / proprietary / non-OSS software. (Note that if for any reason kubernetes/charts doesn't wish to host such charts, there's certainly no need. Alternative repos might spring up containing charts for non-OSS software.)

To account for users who script Helm CLI commands into their own workflows, it would be a good idea to also provide an optional CLI flag that preempts the interactive acceptance process.

I also want to justify why this is not a breaking change to Helm. Were this feature implemented, on day 0, even with no existing script utilizing an optional CLI flag to preempt interactive license acceptance, no installation or upgrade of any existing chart would fail (because none utilize the feature). If any existing chart should choose to adopt this feature going forward, that is a breaking change _to the chart_ (not to Helm) and individual charts can mitigate that by respecting semver and adopting this feature only in conjunction with a major release.

**Comment by ankushchadha** [comment]
Chart license is a bit deceiving. There should be a field such as an 'AppLicense' (similar to chart version vs app version). Note that a chart -
1. Can deploy multiple containerized microservices (there are multiple docker images)
2. A chart can further point to a sub-chart. Maybe there is a need to aggregate all the app licenses.
