### ISSUE TITLE
[Proposal] Add --silent flag

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/helm#2478]
Sometimes I would like helm to not print out the updated resources to the command line (particularly the service definitions since this can contain external-ip addresses). So I would like the ability to pass a silent flag in and only get if the upgrade/install succeeded/failed.

**Comment by jascott1** [comment]
How about `-q|--quiet` instead of `--silent`? 
Also which commands would need this functionality?
By "and only get if the upgrade/install succeeded/failed" do you mean return 0 to stdout for success and return 1 to stderr?

**Comment by jchauncey** [comment]
@jascott1 yeah a 0/1 exit could would work.

**Comment by tot-ra** [comment]
also interested in silencing feature.. right now resorting to just `> /dev/null` to get only errors

**Comment by hickeyma** [comment]
@tot-ra What version of Helm are you using?

**Comment by tot-ra** [comment]
v3.3.4

**Comment by danielsiwiec** [comment]
I don't believe this was ever implemented. Neither `--silent` nor `--quiet` are present. Helm v3.14.4

**Comment by imnasnainaec** [comment]
I'd like to use a `--quiet` option with the `helm repo [command]` commands.
