### ISSUE TITLE
helm install --wait doesn't work for Deployment pods

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/helm#2483]
> helm version 
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}

I used the following command:

```helm install stable/etcd-operator --name etcd-operator --wait --timeout 300```

I thought that helm will wait for all deployment pods to be ready, unfortunately it returns almost immediately and pod is in `pending` state.

I tested it with kubernetes versions 1.5, 1.6 and master branch

**Comment by nebril** [comment]
At first glance it seems like `podsReady` function is checking only pod status, not its phase (which is where `pending` lives)? Is it expected behaviour? @thomastaylor312

**Comment by adamreese** [comment]
In scenario where Deployment has replicas set to 1 and maxUnavailable is not set to 0 as part of rolling update strategy, --wait will return as ready as it has satisfied the minimum Pod in ready condition.

https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#helpful-options-for-installupgraderollback

**Comment by lukaszo** [comment]
Oh, I see. Is there a way to set maxUnavailable to 0 when running `helm install`?

**Comment by chancez** [comment]
@lukaszo there's `.Release.IsInstall` and `.Release.IsUpgrade`  you can use in your templates.

**Comment by lukaszo** [comment]
Ok, I understand how it works. Thank you for your help.
