### ISSUE TITLE
plugins dir is not created automatically

### ISSUE THREAD

**Issue by sgoings** [kubernetes/helm#2488]
I recently installed helm 2.4.2 and right away tried to install a plugin:

```
$ helm plugin list
NAME	VERSION	DESCRIPTION

$ helm plugin install https://github.com/technosophos/helm-github
Error: symlink /Users/sgoings/.helm/cache/plugins/https-github.com-technosophos-helm-github /Users/sgoings/.helm/plugins/helm-github: no such file or directory

$ mkdir -p ~/.helm/plugins

$ helm plugin install https://github.com/technosophos/helm-github
Installed plugin: github

$ helm plugin list
NAME  	VERSION	DESCRIPTION
github	0.1.0  	This plugin provides GitHub services to Helm.
```

Could the error message on missing directory be changed to something like:

"Ensure you run `helm init [--client-only]` before you attempt to install plugins."

or even better: just create this directory automatically?

**Comment by bacongobbler** [comment]
@elwaxoro you can also run `helm init --client-only` to create the plugin directories. :)

**Comment by blop** [comment]
issue still exists with v2.16.1 on macos 🤔
