### ISSUE TITLE
output lists/tables as json/yaml/etc

### ISSUE THREAD

**Issue by helgi** [kubernetes/helm#2504]
Would be good to have the ability to output tables (helm ls, dep, release and others) as `json`, potentially `yaml` and other formats. This would greatly simplify automations (especially with `jq`).

**Comment by h0tbird** [comment]
Also with `helm get values`. Super useful for me too!

**Comment by philipbjorge** [comment]
This would also be very useful to me -- I can write automation in any language I like, rather than go.
I think yaml would be the best format since it's consistent with the kubernetes/helm community at large.

**Comment by bacongobbler** [comment]
closing as a duplicate of https://github.com/kubernetes/helm/issues/1534
