### ISSUE TITLE
Docker Hub image for kubernetes/helm

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#2507]
It would be nice to have an image for kubernetes/helm on docker hub. Something to use in CI systems like [Drone](https://drone.io) or ConcourseCI. Maybe even a drone plugin. Does something exist? If not, any thoughts on where it should go?

**Comment by bacongobbler** [comment]
`gcr.io/kubernetes-helm/tiller` is the official image, though no helm client exists in that image. See https://github.com/kubernetes/helm/pull/1929

**Comment by technosophos** [comment]
There are at least a few community maintained ones. I don't know how far along they are. We'll probably add one once we have a build system that is not constantly on the edge of timing out.

**Comment by sheerun** [comment]
could you add helm client to official image?

**Comment by mattfarina** [comment]
1. Why is the image on gcr.io rather than hub.docker.com? Curious on what's driving it to be there.
2. Should the binary be in the tiller binary or separate? Given the purposes are different I'd want a separate image.
3. Is the only blocker the CI timeout?

**Comment by binoculars** [comment]
We've been using https://hub.docker.com/r/lachlanevenson/k8s-helm/ by @lachie83 but would appreciate an official image either on docker hub or k8s.gcr.io (or both).

**Comment by bacongobbler** [comment]
Closed via #1929; the canary images should now have helm inside the image, ready for use. You'll have to override the entrypoint using the --entrypoint flag, but it's there. :)

**Comment by gianrubio** [comment]
@bacongobbler the issue was related to push the image to docker hub so it's shouldn't be closed

**Comment by arbourd** [comment]
No logical reason. Just very lazy. 😂

**Comment by przemolb** [comment]
I have tried to use `gcr.io/kubernetes-helm/tiller:canary` to build our helm package within docker container but have write permission problems:
```
Error: Failed to save: open /data/BuildAgent/work/d8f8e12ff166691c/helm/charts/package-0.11.tgz: permission denied
```
When I `ls -al` inside the docker I can see:
```
[Step 1/1] total 0
[Step 1/1] drwxr-xr-x    3 1000     1000            24 Jan  5 08:39 .
[Step 1/1] drwxr-xr-x    3 1000     1000            20 Jan  5 08:39 ..
[Step 1/1] drwxr-xr-x    5 1000     1000           123 Jan  5 09:09 package
```
Any hint how to overcome it ?

**Comment by bacongobbler** [comment]
You could try writing to somewhere that has global read/write access like /tmp.

**Comment by przemolb** [comment]
I have used `-d /tmp --debug` and got the following:
```
[Step 1/1] [debug] Setting version to 0.16
[Step 1/1] [debug] Setting appVersion to 3.x/4.x
[Step 1/1] Error: stat /tmp/.helm/repository/local: no such file or directory
[Step 1/1] Successfully packaged chart and saved it to: /tmp/package-0.16.tgz
```
The error `/tmp/.helm/repository/local: no such file or directory` happened with previous example as well. So I still have an error ...

**Comment by przemolb** [comment]
I have just found solution: `helm init --client-only`.

**Comment by ahmadalli** [comment]
now that helm 3 doesn't have tiller, is there any alternative image for helm client?
