### ISSUE TITLE
Alias should replace chart name, not add a new one

### ISSUE THREAD

**Issue by markpundsack** [kubernetes/helm#2508]
From https://github.com/kubernetes/helm/pull/2486#pullrequestreview-40538968:

It's slightly confusing to have the first alias make a copy, rather than just alias (or rename) the first copy. e.g. if you're using alias to pretty up access, but still only need a single instance of the chart, there's no way to do that. So `alias` is acting more like `additional` or some other semantics.

I don't want to block the change as it solves the primary use case of the [original issue](https://github.com/kubernetes/helm/issues/2383), but it doesn't quite solve the secondary one.

> Another use-case is simply being able to name a generic chart with something more specific. So rather than just referring to `postgres`, you can refer to `mattermost-db`.

I propose that using `alias` should remove the unaltered chart from dependencies.

/cc @thomastaylor312

**Comment by wstrange** [comment]
Ran into this tonight.  Possible behavior  I would want?
alias:
- first-instance-name-replaces-chart-name
- a-second-instance-of-chart
- a-third-instance

**Comment by markpundsack** [comment]
As a side benefit, being able to alias chart names helps when charts have hyphens in their names since referring to variables in the chart with a hyphen is a pain. In that case, I'd like to alias the chart name to something with camelCase. But of course if aliasing creates a duplicate chart, I can't do that.

**Comment by thomastaylor312** [comment]
Thanks for opening this @markpundsack! I will try to get around to this, but am labeling as help wanted for now in case there are any takers. Also, cc-ing @sushilkm so he can follow along and help review any code because he wrote it 🙂

**Comment by sushilkm** [comment]
If noone is working on this, i can update the feature code, feel free to assign this to me

**Comment by thomastaylor312** [comment]
@sushilkm I haven't started it yet, so you can take it. I'll assign to me (because you didn't open it and I can't assign it) so no one else takes it

**Comment by groundnuty** [comment]
I can concur that this is also an alias behaviour that seemed natural for me what I developed charts that needed multiple copies of the dependencies. FYI I even wrote a plugin that does that, while waiting for helm 2.5.0. https://github.com/groundnuty/requirement-alias

**Comment by wstrange** [comment]
Thinking about this a bit more:

The current approach of specifying a list of aliases: `[ db1, db2, ... ] ` does not let you apply tags or conditions selectively to those aliases. i.e. a conditional expressions apply to *all* aliases -  but I might not want that behavior. I might want to conditionally override only db2 , for example.

Perhaps a better syntax is that there can be only a single alias for a chart, and that alias serves to rename the chart.  If you want to install many copies of the same chart, then you repeat the dependency, each time with a unique alias.  Then things like conditional expressions make more sense. 
So like this:
dependencies:
- name: database
  version: 0.1.0
  repository: https://foo/
  alias:  productdb
  tags: product-db
- name: database
  version: 0.1.0
  repository: https://foo/
  alias:  db2
  tags: backend-db

```

**Comment by groundnuty** [comment]
@wstrange that's exactly the approach I took when implementing an alias plugin. To illustrate with an [example](https://github.com/groundnuty/requirement-alias/blob/example/requirement-alias-example/requirements.yaml)
~~~
dependencies:
  # No alias, dependency processed normally
- name: redis
  version: 0.4.6
  repository: https://kubernetes-charts.storage.googleapis.com

  # Dependency will be renamed to match the alias
- name: redis
  alias: redis-1
  version: 0.4.6
  repository: https://kubernetes-charts.storage.googleapis.com

  # Different aliases can have different versions
- name: redis
  alias: redis-2
  version: 0.4.5
  repository: https://kubernetes-charts.storage.googleapis.com
~~~

This approach allows using all the power of dependencies applied to individual alias.

**Comment by markpundsack** [comment]
Thanks @wstrange, that's exactly how envisioned it, but didn't want to get greedy when someone else volunteered time to solve my problem. :)

**Comment by thomastaylor312** [comment]
I actually really like how that looks. @sushilkm How big of a pain would that be to switch around?

**Comment by thomastaylor312** [comment]
@sushilkm If the change mentioned above would be possible, we can open another issue to track it

**Comment by sushilkm** [comment]
Thanks for the suggestion @wstrange, yeah it looks we both had different ideas when thinking about the feature.

@thomastaylor312 I can update that
