### ISSUE TITLE
a release named  already exists when i install release  

### ISSUE THREAD

**Issue by wuzhihui1123** [kubernetes/helm#2515]
I has delete a release and  I still can't install ,  See below:

![image](https://cloud.githubusercontent.com/assets/4246626/26518878/97c88486-42eb-11e7-9aee-e89caf4c4c10.png)

**Comment by rimusz** [comment]
you need to use flag --forse when you delete

**Comment by wuzhihui1123** [comment]
@rimusz 
thanks ,  but no the flag
![image](https://cloud.githubusercontent.com/assets/4246626/26518965/15f9f230-42ed-11e7-83dd-aed171091789.png)

**Comment by wuzhihui1123** [comment]
oh, I know , if reuse the release , must use flag --purge when delete
![image](https://cloud.githubusercontent.com/assets/4246626/26519017/b32ab3d2-42ed-11e7-9c79-5d938a4a2a9d.png)

**Comment by emirhosseini** [comment]
> you need to use flag --forse when you delete

--purge not --force
