### ISSUE TITLE
helm get manifest only seems to work with DEPLOYED release

### ISSUE THREAD

**Issue by kiich** [kubernetes/helm#2525]
Using master.

When helm install/upgrade fails and release is marked as FAILED, doing
`helm get manifest <release_name>`

returns me:
```
[storage] 2017/05/31 16:28:14 Getting deployed release from "<release_name>" history
Error: release: "<release_name>" not found
```

I had hoped it will store failed manifests as well but doesn't seem like it.

**Comment by technosophos** [comment]
I'm looking into this. As a workaround, you can use `helm get manifest --revision $REVISION_ID $RELEASE_NAME`, where $REVISION_ID is the revision from `helm history $RELEASE_NAME`
