### ISSUE TITLE
Tiller-based orchestration

### ISSUE THREAD

**Issue by inc0** [kubernetes/helm#2526]
# Issue description

In kolla-kubernetes, notorious limit-pusher, we ran into issues of orchestration and pretty bad race conditions. We are using old code that resolves dependencies and wait for container startup only after all the dependencies are resolved, but I think that kind of logic could make good addition to Tiller.

# Proposed change

We would introduce "readiness" concept for whole chart - chart is ready when all of it's resoruces are ready.
Tiller would wait with creating new chart until all of it dependencies are ready.

# Issues to handle with this approach

Definition of "ready" would vary per resource and needs to be flexible to handle all the strange situations that can happen. For example one pod out of 3 is down in replicaset, so technically we can run next step as other 2 are working, but replicaset is still non-ready. I think these edge cases would need to be developed in time and/or able to be overridden from default naive scenario (we wait till all 3 are up) by users. Plugabbility could handle that to some extend (much like custom readiness probes).

**Comment by wstrange** [comment]
Another related use case that we have is conditional deployment of a dependency. For example, deploy this database sub-chart, but only if it has not already been deployed (perhaps as part of another chart).

The current mechanism only supports a static condition to determine whether or not to deploy a dependency. 

If Helm supported a pluggable probe, you could presumably support this kind of conditional deployment, as well as the use case described above (i.e. don't start the main chart until the sub chart reports ready).

The devil is in the details. This is probably non trivial to develop.

**Comment by thomastaylor312** [comment]
I am all for this. It will definitely require a refactor of the wait code to be a bit more robust and modular.

**Comment by bacongobbler** [comment]
Would this be something which `helm test` should be able to handle? pinging @michelleN

**Comment by technosophos** [comment]
There is a PR open that introduces "hook stages", which might be a solution to this issue. See #2440.

Also, with 2.5, it will be possible to plugin an an alternate orchestrator (as a Rudder). That might be a good way to test out some alternatives for this kind of workflow. /cc @nebril

**Comment by inc0** [comment]
I disagree that stages will allow to do it. Key here is requirements.yml, which would determine external charts that needs to be ready before chart can proceed. Unless I miss the hooks idea completely, hooks will be related to internals of chart not external charts, which makes these proposals orthogonal.

As for external orchiestrators yes, that would be solution, but having too many of these will in fact cause a lot of chaos for users. Let's discuss this more please, what are issues you see for implementing it in tiller besides scope of change?

**Comment by michelleN** [comment]
`helm test` can help assure that a release is working as expected but it would have to be run after `helm install` completes successfully. cc/ @bacongobbler 
I would agree that this seems like a good use case for the alternate orchestrator that the AppController folks are integrating using Rudder like @technosophos mentioned though. They already have the dependencies and parent/child hierarchies all figured out in their implementation. It seems like we would be duplicating a lot of what they've already built.

**Comment by nebril** [comment]
@inc0 please take a look at AppController Rudder: https://github.com/helm/rudder-appcontroller

It currently works exactly as you want it to work - charts are not being created until all their "parents" are ready, you define your own readiness probes in every pod template.

If you have any issues with deploying it, please let me know, it's still rough around the edges for users.

Additional resources:
Lightning talk: https://www.youtube.com/watch?v=7TjsBBnvHMM&t=11s
AppController repo: https://www.youtube.com/watch?v=7TjsBBnvHMM&t=11s

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
