### ISSUE TITLE
Incorrect order for parameter check in uninstall release, Can we adjust it?

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/helm#2529]
I read the code of uninstall release to study the code of this process.

Find that in UninstallRelease function, do these three steps:

1、 get release locker of release name 

2、  check  whether the release name  is ValidName.MatchString

3、 check  whether len(req.Name)  is long than releaseNameMaxLen

But if the   len(req.Name) is long than releaseNameMaxLen, the req.Name is illegal. Surely the get relese locker is failed, as it certainty can't find an release which name is req.Name. 

So can adjust the parameter check order ? To check  whether  the req.Name  is  illegal first , and then to get release locker.

**Comment by thomastaylor312** [comment]
This is a valid point, we probably should be checking the release name before trying to lock it

**Comment by technosophos** [comment]
Closed by #2540 

Thank you @yan234280533 !
