### ISSUE TITLE
helm 2.4.1 ignores --home option

### ISSUE THREAD

**Issue by abinet** [kubernetes/helm#2531]
on ubuntu 16.04

`helm home --home somedir`
still returns default user home directory

`HELM_HOME=somedir helm home `
works fine

**Comment by fibonacci1729** [comment]
@adamreese

**Comment by technosophos** [comment]
#2476 resolves this. We should probably put that into 2.4.3 and release it this week.

**Comment by technosophos** [comment]
Closed by #2476
