### ISSUE TITLE
Can it have necessary to give an Uniform Check for release name ? 

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/helm#2538]
I read the code of the release  processings, I find that in the processings such as Update, getstatus, gethistory and so on. Most of  those  processings no check the release name.

Can we have an Uniform Check for the release name ?  If the release name is illegal, processing exit and return the error message "The release name is illegal, release ""^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$"" and short than 53 chars.

The check is 

if !ValidName.MatchString(req.Name) {
		s.Log("uninstall: Release not found: %s", req.Name)
		return nil, errMissingRelease
	}

if len(req.Name) > releaseNameMaxLen {
		return nil, fmt.Errorf("release name %q exceeds max length of %d", req.Name, releaseNameMaxLen)
	}

**Comment by jascott1** [comment]
@yan234280533 We might get away just checking on write operations.

**Comment by technosophos** [comment]
Yes, we could add this check to any release operation (status, get,...) to catch errors early. I'll mark this as a feature. Do you want to do this @yan234280533 ?

**Comment by yan234280533** [comment]
@technosophos  I am very happy to do this, it my pleasure.
