### ISSUE TITLE
Proposal: Federation support

### ISSUE THREAD

**Issue by nebril** [kubernetes/helm#2539]
There is a need for proper federation support within Helm community, as this issue shows: https://github.com/kubernetes/helm/issues/1998

This document is intended to show the possible way of implementing support for federation in Helm.

K8s federation as it stands now, has the concept of a `host cluster`, in which the federation API server lives, which communicates with cluster API endpoints.

Federation API aims to be compatible with Kubernetes API. This fact can be used to leverage implementation of federation support - make Tiller talk to Federation API instead of regular k8s API, to create all release k8s objects in a federated cluster.

So far it seems that there is no need to actually run Tiller in a federated deployment to support federation.

Tiller talking to Federation API can be done in two ways:

 - If federation API is completely compatible, changing kubectl context to federation API while running Helm seems to be enough (although needs to be tested). Status would probably need to be altered to check federated resources. The changes could be done as an alternative federation-specific ReleaseModule object.
 - Implementing a federation-rudder backend, which would house all necessary alterations from regular API calls (if any) and status. Example rudder lives in Helm repository, another one is being implemented here: https://github.com/helm/rudder-appcontroller

**Comment by technosophos** [comment]
I like this idea. I had been considering trying something in the opposite direction (running a special tiller in federation plane), but this seems more sensible.

**Comment by bacongobbler** [comment]
should we close this ticket and point users to try out https://github.com/kubernetes-helm/rudder-federation if they want to try federated support for Helm?
