### ISSUE TITLE
`--set` and maps

### ISSUE THREAD

**Issue by vromero** [kubernetes/helm#2547]
I have a configuration in values.yaml as follows:

```
someone:
  - name : "mister"
    surname : "pompapdur"
```
To try to override I tried the following:

`helm install my-chart --set "someone={{name=john, surname=doe}}"`

But I get:

`Error: failed parsing --set data: key "}" has no value`

Is there a way to pass a map from the command line?

**Comment by technosophos** [comment]
It's not the map that is difficult to deal with, it's the list. Until recently, there was no way to access items in a list from `--set`. But we are about to merge a fix for this into Helm 2.5

In Helm 2.5, you will do it like this:

```
helm --set someone[0].name=mister,someone[0].surname=pompadur
```

**Comment by technosophos** [comment]
See #2545

**Comment by technosophos** [comment]
Closed by #2545

**Comment by 4c74356b41** [comment]
i like how the person doesnt answer the original question but talks about passing lists through command line. entertaining.

**Comment by bacongobbler** [comment]
The original question asked about an array of maps, so the answer provided did indeed answer the original question. The title was just worded incorrectly.

Is there something you're trying to figure out?

**Comment by 4c74356b41** [comment]
yeah, was, but completely unrelated to this question (randomly got here).

**Comment by gm42** [comment]
I think an example on how to set a map via `--set` would be nice to have, couldn't find anything here: https://helm.sh/docs/chart_best_practices/values/

**Comment by igoratencompass** [comment]
In my experience in case the var is a bit more complex like: 
```
someone:
  - name : ""
    surname : ""
    middlename: ""
    somelist: []
```
setting only the first two as per the example:
```
helm --set someone[0].name=mister,someone[0].surname=pompadur
```
wipes out the rest of the parameters as if they never existed converting the `someone` var into:
```
someone:
  - name : "mister"
    surname : "pompadur"
```
