### ISSUE TITLE
"fatal error: concurrent map writes" in Tiller when running several create-test-delete cycles concurrently

### ISSUE THREAD

**Issue by YorikSar** [kubernetes/helm#2552]
We've ran into this issue: when we started doing parallel testing in our CI, we quickly ran into the issue with Tiller panicking after some time.

We've been running 6 jobs in our CI that create, test and delete releases of our charts and after some time Tiller panicked and got restarted. Here are what seem to be relevant part of traceback that we got: https://gist.github.com/YorikSar/2576b061b4d01d006e7623aa5cd17689

From the looks of it, [here](https://github.com/kubernetes/helm/blob/v2.3.1/pkg/kube/client.go#L122) tiller calls Validator method that later goes down to [ClientCache.ClientConfigForVersion](https://github.com/kubernetes/kubernetes/blob/v1.5.6/pkg/kubectl/cmd/util/clientcache.go#L122). So if same ClientCache is used in several threads, there's a possibility of those map assignments happening in parallel and runtime will panic.

PS: We're running helm v2.3.1 on both client and server sides.

**Comment by technosophos** [comment]
This was fixed in Helm 2.4 (actually, in Kubernetes 1.6).

**Comment by YorikSar** [comment]
Ok, we'll have to investigate if we're ready to switch to 2.4 then. Thanks.
