### ISSUE TITLE
Helm applied applied only 'half' a spec without errors

### ISSUE THREAD

**Issue by TimJones** [kubernetes/helm#2562]
Running Helm v2.4.2 with a K8S 1.6.2 cliuster in AWS.

We have a `Deployment` that has an `initContainers` in the spec, and noticed yesterday that while the spec was being upgraded, the `initContainers` part was skipped/ignored due to a typo (comma in an `.env.name`) but no error during the upgrade.

Getting the deployment with `helm get` and applying the YAML manaully with `kubectl apply -f ...` did produce an error.

    The Deployment "test-err" is invalid: spec.template.spec.initContainers[0].env[0].name: Invalid value: "NAME,": a valid C identifier must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName', regex used for validation is '[A-Za-z_][A-Za-z0-9_]*')

I would expect helm to return this error when performing the upgrade rather than just not updating that part of the spec.

**Comment by technosophos** [comment]
I am curious whether this is specific to deployments, or whether replica sets have this issue too.

**Comment by seh** [comment]
@TimJones, had you modified the _Deployment_ in situ since Helm had installed the previous version? I wonder if the patch submitted during upgrade omitted the "initContainers" portion if it didn't appear to have changed since the last version.

**Comment by TimJones** [comment]
@seh Quite probably, I'll check with my colleagues.
Does Helm only check with what it applied (i.e. making a diff with it's stored configmap) against the new release? Never goes back to the Kubernetes API to confirm what it thinks should be there?

**Comment by seh** [comment]
I asked about this behavior in the "helm-dev" channel of the "Kubernetes" Slack team [on 28 April 2017](https://kubernetes.slack.com/archives/C51E88VDG/p1493387271859968). In short, Helm looks at the last manifests it applied when considering applying a new set, and uses the differences between them to submit patches. Helm does not take the current state of the Kubernetes objects into account.

This surprised me. As @technosophos [said in that discussion](https://kubernetes.slack.com/archives/C51E88VDG/p1493388866573733),
> It was one of our early "simplifying assumptions" that at some point we probably ought to revisit

though to do so would potentially change Helm into an "enforcer," where you could tell it to ensure that the current cluster state matches the intended state for an already-installed chart. Doing so requires ignoring parts of many of the objects (e.g. the status of a _ResourceQuota_).

**Comment by TimJones** [comment]
I would expect Helm to be an enforcer at the point of running the `install` or `upgrade` command. If I set a tag in a values file I expect it to be applied to the running deployment regardless of the deployment being modified since the previous `install` or `upgrade`.
