### ISSUE TITLE
Specifying appVersion with "helm package"

### ISSUE THREAD

**Issue by Bert-R** [kubernetes/helm#2566]
As I'd like to generate a helm package at build time, I would like to specify the ``appVersion`` as a command line parameter of the ``helm package`` command, just like you can do with the chart version.

Or is there an alternative way to do that? (I'm totally new to helm)

**Comment by seh** [comment]
I thought I've seen a proposal for making the _Chart.yaml_ file subject to some template expansion/interpolation, but I can't find any such issue today.

**Comment by technosophos** [comment]
Chart.yaml cannot be templated because it must be immutable from `helm package` time onward. But I think that adding a flag to set it at package time would be fine.

**Comment by Bert-R** [comment]
Indeed, that would match well with the ``--version`` flag. In addition, ``helm package`` does not have the ``--set`` option, which would be required when applying expansion/interpolation to ``Chart.yaml``.

**Comment by adshmh** [comment]
@bacongobbler I'd like to give this a try, as no one seems to be working on it.

**Comment by bacongobbler** [comment]
@adshmh feel free to give this a shot! Nobody has begun work on this. :)

**Comment by sslavic** [comment]
Requested in https://github.com/kubernetes/helm/issues/3141 support for `--values` but supporting `--set` for `helm package` would be even more useful.

**Comment by adshmh** [comment]
Just submitted a PR for app-version. Will work on --set next.

**Comment by Bert-R** [comment]
Thanks a lot Arash for working on this!
