### ISSUE TITLE
Manager REST API needs improvement

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#257]
Currently, the REST API offered by manager requires the client to know the registry for a type name. The client must know the registry in order to download the type URLs via GetDownloadURLs (/registries/{registry}/types/{type}) or to download the type definition or schema via GetFile (/registries/{registry}/download). However, the mapping from a type name to a registry should be the server's responsibility, not the client's.

Furthermore, clients currently have to fetch download URLs for files in registries in order to access the files. However, in general, clients don't have permission to actually download from those URLs. We offer GetFile (/registries/{registry}/download), which takes a download URL as an argument, as a workaround. Unfortunately, there are now two round trips involved:
* Client fetches download URLs.
* Client asks server to retrieve the file at a given URL.

In addition, the client expects multiple URLs to be returned as a slice, yet always choses the first element in the slice and discards, apparently assuming that:
* The first URL in the slice is the file they want.
* The rest of the URLs, if there were any, don't matter.

Apparently, however, there is nothing in the code, either client side or server side, which guarantees that these assumptions will always be valid.

We can and should clean up these APIs, so that clients are no longer required to map type names to registry names, or to fetch download URLs for files they can't actually download. Instead, we should provide APIs to do the type name to registry name mapping on the server, and to retrieve the definition of a chart, given its type name. As a convenience, we can also provide an API to retrieve the metadata for a type to support `helm info` or `dm describe`.

Here are the recommended changes:
* Do the type name to registry name mapping on the server by providing an API named GetTypeRegistry (/types/{type}/registry) that returns the registry name for a given type name. The registry name can then be used in calls to /registries/{registry}, et. al.
* Deprecate GetDownloadURLs and replace it with GetTypeDefinition (/types/{type}/definition), which returns the Chart for a type and GetTypeMetadata (/types/{type}/metadata), which returns the contents of the Chart.yaml file.

**Comment by jackgr** [comment]
Note that all of the uses of GetDownloadURLs currently found in dm can be removed with these changes. Creating a template from a type and listing the deployed instances of a type currently call it, but there's no need for either of them to call it, since the type name is mapped correctly on the server side.

**Comment by technosophos** [comment]
I'm okay with the proposed changes.

In many REST APIs, there's a root version path (`/v1/foo`). Perhaps versioning that way would be a way of adding new endpoints or significantly modifying the contract of existing endpoints?

**Comment by jackgr** [comment]
Great suggestion, @technosophos. Let's consider it a requirement to add an API version prefix.
