### ISSUE TITLE
chart rename

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#2571]
As we take some of the monolithic charts in kubernetes/charts and make them more modular, we're running into an issue with convention and naming. In the existing chart, the subchart like templates may reference a part of values like:
fooBar:
  ...

If I want to take those and put them in a subchart, by convention it should be called:
foo-bar

but then the values subsection would be called foo-bar which wouldn't match up with the values convention, nor the existing users values.yaml's.

I tried looking at the requirements, alias: ['fooBar'] method. But the documentation makes it seem like it clones another instance of foo-bar so that there are 2 where I only can have one. So, I need something like a rename. Maybe if rename is specified, and alias is there, the rename only happens to the instance not listed in the alias?

**Comment by jascott1** [comment]
@sushilkm i asked @kfox1111 to open this issue because he needs alias feature to give another name to single chart without instancing a duplicate of the chart. I remember it was discussed but were you planning on implementing this?

**Comment by sushilkm** [comment]
There were couple of fixes made, imho, an alias should be rename, also we updated the `alias` to be a single value instead of an array.

Can you check by building master branch if it helps you, if it does not we can work on thw fix :)

**Comment by jascott1** [comment]
Thanks @sushilkm. 
@kfox1111 it seems like it should work for your simple alias case. Can you confirm or post the specific issue?

**Comment by kfox1111** [comment]
@sushilkm alias is in the current stable release isn't it? Or maybe just the documentation was updated?

**Comment by sushilkm** [comment]
@kfox1111 if you are building yourself from master branch then you would get the latest, but imho latest released helm is 2.4.2 and this feature is not yet there

**Comment by kfox1111** [comment]
ah, ok. Was worried we were talking about breaking released api. I'll see what I can do to get a trunk build/test it. Thanks. :)

**Comment by jascott1** [comment]
@kfox1111 Did this work out?

**Comment by kfox1111** [comment]
Yes. I was able to alias it to the camel cased name and get it to work. Thanks. :)
