### ISSUE TITLE
[Question] Possible to use templates in Files.AsConfig?

### ISSUE THREAD

**Issue by jiahaog** [kubernetes/helm#2573]
Hi! Just a quick question, is it possible to use templates in `Files.AsConfig`?

I have a configuration for a application as a yaml file, which depends on the release name to communicate to some other service:

`configs/something.yaml`
```yaml
other_service_endpoint: {{ .Release.Name }}-service
```

And the template to create the configmap:
`templates/config.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
# ...
data:
{{ (.Files.Glob "configs/*").AsConfig | indent 2 }}
```

When I run `helm install`, the template in `other_service_endpoint` is not rendered, and it stays as the string `{{ .Release.Name }}-service`. 

Is the some way to trigger the rendering of this nested template? Something like `{{ (.Files.Glob "configs/*").AsConfig | some_function_to_rerender | indent 2 }}` in `templates/config.yaml`?

**Comment by eicnix** [comment]
This is currently not possible but will be added next Monday in the 2.5.0 release as a experimental feature by adding the `tpl` function. 

`{{ (tpl (.Files.Glob "configs/*").AsConfig . ) | indent 2 }}`

**Comment by jiahaog** [comment]
Good stuff, thanks a lot!

**Comment by tutaidalal** [comment]
Can I refer a varible instead of hardcoded config ?
Something like - 

> 
{{ (.Files.Glob {{ .Values.global.configPath}}"/*").AsConfig | indent 2 }}

{{ (.Files.Glob "configs/*").AsConfig | indent 2 }}

**Comment by tutaidalal** [comment]
Can I use some external file (outside of helm zip package) to include during helm install command ?

I have created a application using {{ (tpl (.Files.Glob "configs/*").AsConfig . ) | indent 2 }}. But end user dont want to unzip and use the helm. What is the procedure to include some external files for config mao

**Comment by coolduebtn** [comment]
> Can I refer a varible instead of hardcoded config ?
> Something like -
> 
> > 
> 
> {{ (.Files.Glob {{ .Values.global.configPath}}"/*").AsConfig | indent 2 }}
> 
> {{ (.Files.Glob "configs/*").AsConfig | indent 2 }}



> Can I refer a varible instead of hardcoded config ?
> Something like -
> 
> > 
> 
> {{ (.Files.Glob {{ .Values.global.configPath}}"/*").AsConfig | indent 2 }}
> 
> {{ (.Files.Glob "configs/*").AsConfig | indent 2 }}

Is it possible to do this ?
{{ (.Files.Glob {{ .Values.global.configPath}}"/*").AsConfig | indent 2 }}

**Comment by prasanthj** [comment]
@coolduebtn following worked for me
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-conf-{{ template "name" . }}
data:
{{ (tpl (.Files.Glob (printf "%s/*" .Values.configPath) ).AsConfig . ) | indent 2 }}
```

**Comment by abdennour** [comment]
or more elegant:

```yaml
kind: ConfigMap
#......
data:
{{- with .Files.Glob "configs/*" }}
{{ tpl .AsConfig $ | indent 2 }}
{{- end }}
```

**Comment by abdennour** [comment]
Or in one line ;) 

```yaml
#....
data:
  {{ (tpl (.Files.Glob "files/*.*").AsConfig .) | indent 2}}

```
Where `files/` is an example here and it must be a folder sibling of templates folder.

**Comment by akloss-terion** [comment]
I'm curious about closing this... you can symlink from `templates/` to elsewhere in the chart, so while a little awkward, it is pretty trivial to create a chart that refers to its own `templates/`.  This is appealing for name-managing sha of the templates into the resources the templates creates.  I have not tried it, but it seems like
```
diff --git a/pkg/chart/v2/loader/load.go b/pkg/chart/v2/loader/load.go
index d466e247c..b1702d296 100644
--- a/pkg/chart/v2/loader/load.go
+++ b/pkg/chart/v2/loader/load.go
@@ -146,6 +146,7 @@ func LoadFiles(files []*archive.BufferedFile) (*chart.Chart, error) {
 
 		case strings.HasPrefix(f.Name, "templates/"):
 			c.Templates = append(c.Templates, &common.File{Name: f.Name, ModTime: f.ModTime, Data: f.Data})
+			c.Files = append(c.Files, &common.File{Name: f.Name, ModTime: f.ModTime, Data: f.Data})
 		case strings.HasPrefix(f.Name, "charts/"):
 			if filepath.Ext(f.Name) == ".prov" {
 				c.Files = append(c.Files, &common.File{Name: f.Name, ModTime: f.ModTime, Data: f.Data})

```
would be sufficient to remove the need for the awkward symlink.  Thoughts?
