### ISSUE TITLE
Deployments with specified expiration/TTL

### ISSUE THREAD

**Issue by diclophis** [kubernetes/helm#2574]
Is there any existing support / planned support for creating deployments with a specified "time-to-live".

We are currently utilizing this project: https://github.com/mavenlink/karousel ... however our adoption of helm has introduced some amount of conflicts between to mechanisms for deploying and reaping pods.

Any advice / feedback would be appreciated.

**Comment by aguilarm** [comment]
Could you use [a job with activeDeadlineSeconds[(https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#job-termination-and-cleanup)?

**Comment by diclophis** [comment]
@aguilarm thanks for the quick reply... in our scenario the case is more like this:

1. A developer pushes a feature-branch to github
2. we use jenkins to fetch that pushed branch and build our app
3. we use helm to "deploy" that version of the app in a siloed "instastage (tm)" mode that allows it to live next to several hundred other instances of the same app
4. we use `karousel` to "reap" said deployment after a given TTL as to not let it "live forever"

... part of these deployments are cronjobs, and we were hoping that helm might have some features to facilitate this workflow.

**Comment by bacongobbler** [comment]
This is something out of scope for helm, but I know of other tooling where this would make sense, e.g. [brigade](http://brigade.sh/).

**Comment by rtpro** [comment]
This is implemented via a Helm plugin https://github.com/JovianX/helm-release-plugin#helm-release-ttl
