### ISSUE TITLE
support processing a single file

### ISSUE THREAD

**Issue by vinayagg** [kubernetes/helm#2587]
Other than charts, a project or organization has many other templating needs. E.g. we are trying to install monitoring solutions and needs templates for that. 

If helm allows a single file to be processed, it will become useful outside of charts and allow a single unified tool for all templating needs.

**Comment by michelleN** [comment]
hey @vinayagg - You can put your monitoring solution in a helm chart if you'd like. See this Prometheus chart as an example: https://github.com/kubernetes/charts/tree/master/stable/prometheus
If you're not looking to use helm charts, then you might want to look into Sprig. Sprig is a library of template functions for Go templating. That might be helpful if you need templating functionality but don't need or want to use the chart packaging format. 
Is that what you're looking for? If not, please help me understand a little better what you're asking. Thank you.

**Comment by vinayagg** [comment]
Hi @michelleN 
Let me try to explain. 

When we deploy a project using helm, we also need to setup monitoring external to kubernetes - e.g. uptime robot, new relic cloud, app dynamics cloud, netuitive cloud etc.
 
To do that automatically, we need to process a template but do not need to install it on k8s (we can use curl to invoke third party api.

Sure, I could put that in a helm chart but that feels like a bad practice.
I can use sprig as well, but it means, now I have to install/maintain sprig + go binary + go scripts to process templates. 

Overall, it is doable without helm, but it will mean more complexity and partial duplication of what helm already does. 

I see this functionality (or a variation of it) should hopefully need minimal changes to helm but it enables helm to be a much more general purpose tool that can do lot more than what it does today.
Hence my feature request.

**Comment by bacongobbler** [comment]
You might want to take a look into the [helm-template plugin](https://github.com/technosophos/helm-template) as that seems **very** to your use case. It runs a local chart through the template engine without actually installing it and displays the manifests on stdout.

**Comment by vinayagg** [comment]
even helm --debug --dry-run can do that, but that does not work.

It processes whole chart, so now each setting or monitor or anything needs
to be in its own chart instead of just a file. some non k8s stuff may need
its own directory structure but it wont work with this approach. As you can
see this gets messy very quickly.

**Comment by bacongobbler** [comment]
closing as out of scope for helm. A plugin or another project would be better suited for this sort of work.

**Comment by fzyzcjy** [comment]
Hi is there any updates after 3 years?
