### ISSUE TITLE
Alias in `requirements.yaml` not working

### ISSUE THREAD

**Issue by fuhbar** [kubernetes/helm#2588]
As the [docs](https://github.com/kubernetes/helm/blob/master/docs/charts.md#alias-field-in-requirementsyaml) stating it should be possible to deploy the very same dependency of a chart more than once. The alias mechanism - AFAIK - is the vehicle for achieving this. But it seems to be broken some how. 

```console
$ helm version
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}

$ helm create test
Creating test

$ cat -<<EOF >> test/requirements.yaml
dependencies:
  - name: redis
    version: 0.7.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    alias: redis-one
  - name: redis
    version: 0.7.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    alias: redis-two
EOF

$ helm dep update ./test
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com/
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com/

$ find test/charts
test/charts
test/charts/redis-0.7.0.tgz
```

I would have expected to see 2 charts as subcharts after dependency resolution. Do I have some misunderstanding here or this actually an issue?

**Comment by wstrange** [comment]
I think the docs are ahead of the release here.   I believe this is in 2.5, which should be out shortly.

You can try with the canary release - it works for me.

**Comment by dkellner** [comment]
I get exactly the same result as @fuhbar with the recently released 2.5.0, even the changelog mentioned the `alias`-feature being included (https://github.com/kubernetes/helm/releases).

```sh
$ helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

**Comment by rgauss** [comment]
+1

`requirements.lock` shows:

    - alias: ""

**Comment by rgauss** [comment]
Disregard my +1 (apologies, newb, was having a different problem).

While requirements.lock does show an empty alias string and there is only 1 copy of the chart present (which makes sense I think), things are working as expected in the deployment, including [override of subchart values](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#overriding-values-from-a-parent-chart) by alias.

**Comment by dkellner** [comment]
@rgauss That means you don't have any issues?

As far as I understood the [docs regarding alias fields](https://github.com/kubernetes/helm/blob/master/docs/charts.md#alias-field-in-requirementsyaml), there should be multiple copies in `charts/` after running `helm dep update`. If that's actually not true we should make that clear in the docs.

**Comment by rgauss** [comment]
> That means you don't have any issues?

Correct, no issues on the same v2.5.0.

> As far as I understood the docs regarding alias fields, there should be multiple copies in charts/ after running helm dep update.

I may have misinterpreted, but I didn't see where that was specifically indicated, just that you could have previously achieved a similar result by manually adding multiple copies.

> ... we will get 3 depenendencies in all for parentchart ...

not necessarily 3 duplicate items in `charts/`.

**Comment by argusua** [comment]
Works for me when I've added to values.yml 
````
redis-one:
    enabled: true

redis-two:
    enabled: true
````

**Comment by jeff-knurek** [comment]
This feature is not meeting the expectations set in the documentation.
The `alias` field seems to work and provide the needed functionality, but it doesn't download/install it with a different name in `charts/` (which is what I need at this time).

**Comment by bacongobbler** [comment]
@jeff-knurek can you point out where in the documentation this expectation is set? Perhaps there's some verbiage that needs fixing. As far as I understood this was never an expected use case. Perhaps you can also explain why you expect aliasing to work that way for your use case?

**Comment by jeff-knurek** [comment]
based on the original description/link of this issue

docs: https://github.com/kubernetes/helm/blob/master/docs/charts.md#alias-field-in-requirementsyaml

verbiage:
```
In the above example we will get 3 dependencies in all for parentchart

subchart
new-subchart-1
new-subchart-2

The manual way of achieving this is by copy/pasting the same chart in the charts/ directory multiple times with different names.
```

my use case: I think the root cause is a bug in the quay registry plugin (linked above), but because I can upload charts to the registry with a different name, when they get downloaded as dependencies, the requirements file doesn't match their downloaded name. And so I expected to workaround this bug by using an `alias` (as documented) to rename the dependency charts that get downloaded.

**Comment by jascott1** [comment]
@jeff-knurek Alias feature takes a given chart name and replicates it multiple times. I was against naming the feature `alias` because it leads to confusion since it isn't an alias (two names for the same thing) but is actually creating multiple instances of the chart. Can you think of anything we could add to the docs to be clearer on functionality?

**Comment by jeff-knurek** [comment]
I don't know, it's interesting because
> Alias feature takes a given chart name and replicates it multiple times

doesn't actually "replicate" it. If there's only one dependency chart and it uses `alias`, you still only have one subchart that gets installed. 

----
> The manual way of achieving this is by copy/pasting the same chart in the charts/ directory multiple times with different names.

That's not true either though, right? Because if you copy/paste a `.tgz` file with a different name, the chart itself is still the original name.

**Comment by jascott1** [comment]
@jeff-knurek I think "with different names" should read "with different directory names and chart names" but perhaps we could revise the whole thing with more detail.

**Comment by bacongobbler** [comment]
I'm going to go ahead and close this as the OP's problem has been resolved as noted by others chiming in here.
