### ISSUE TITLE
Private repo, can't update the index

### ISSUE THREAD

**Issue by Smana** [kubernetes/helm#2590]
Hi guys!

I'm trying to configure a private repository but i can't update the index following the guidelines.

The `index.yaml` is reachable with the following command : 
```
curl https://helmcharts.foo.bar/charts/index.yaml
```

The following command doesn't return any error
```
helm repo index mycharts --url https://helmcharts.foo.bar
```

But the index.yaml is not updated :/

Thanks for your help

**Comment by Smana** [comment]
I just tried with google storage and i'm facing the same issue...

**Comment by wstrange** [comment]
There is a --merge option to merge an existing index.yaml with the updated contents. 

Have a look at https://github.com/kubernetes/charts/blob/master/test/repo-sync.sh 
for an example

**Comment by michelleN** [comment]
@Smana does the `--merge` flag make a difference for you? Also, what about the index.yaml is not updated. Is it missing a new entry?

**Comment by michelleN** [comment]
@Smana I think your url you pass in needs to be `https://helmcharts.foo.bar/charts`.

**Comment by Smana** [comment]
Hi all !

Thank you for your answers @michelleN @wstrange 
`--merge` doesn't make any difference

Using the url `https://helmcharts.foo.bar/charts` doesn't work better and the command 
```
helm repo index charts --url https://helmcharts.foo.bar/charts 
```
doesn't return any output.

**Comment by Smana** [comment]
>  what about the index.yaml is not updated. Is it missing a new entry?
Yes even if i have a brand new index.yaml i'm expecting to overwrite the existing one. Is that the expected behavior ?

**Comment by Smana** [comment]
I'm still stucked with this issue, even on google cloud storage....
digging further, will try again

**Comment by bacongobbler** [comment]
@Smana were you able to resolve this issue?

**Comment by michelleN** [comment]
Hey @Smana 
In order to create an index file, you need to have a local directory that is a mirror of your chart repo. Do you have a local copy of your chart repo? You'll then get an updated index file locally which you can push up to your chart repo. I'm wondering if there is a mismatch in expectations for this command.

**Comment by Smana** [comment]
Hey @michelleN 

Actually i managed to create a private repository, i should have closed this issue earlier.
I'm using Nginx as the webserver along with network acls

**Comment by michelleN** [comment]
Awesome. thanks
