### ISSUE TITLE
Set a variable from the output of a command line

### ISSUE THREAD

**Issue by Smana** [kubernetes/helm#2591]
Hey,

I'm wondering if that'd be possible to set a variable from a command line ?
For instance i would like to use the short commit tag as the docker tag.
How would you do that please ?

Regards,

**Comment by Smana** [comment]
Another usage would be:
In an autoscaling environment, get the current number of replicas before to apply the new deployment.

**Comment by bacongobbler** [comment]
You can use `--set` to perform this action, depending if the chart has made the field template-able or not. There are several examples of this in the documentation.

**Comment by Smana** [comment]
nvm, i just figured it out
```
TAG=$(git rev-parse --short HEAD)
--set image="image:xxxxxx",
```
