### ISSUE TITLE
Bug: helm 2.4.2 'upgrade --install' sometimes fails with 'release not found' for non-existent release

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes/helm#2593]
Since upgrading to 2.4.2, using `upgrade --install` to create a new release no longer works.

In 2.3.x helm would detect the release did not exist and install a new release instead. Now with 2.4.2 it errors out with 'release not found' error. Expected helm 2.4.2 to create a new deployment like 2.3 did.

```
helm upgrade --install --namespace foo bar-release mychart-0.3.1.tgz -f base-values.yaml -f prod-values.yaml --set image.repository=blah.blah.amazonaws.com/foo/bar 
Error: UPGRADE FAILED: Unable to lock release bar-release: release not found
```

**Comment by whereisaaron** [comment]
Ok, that's strange. I just ran the same command again to debug this, and this time is behaved as expected.

```
Release "bar-release" does not exist. Installing it now.
```

**Comment by chancez** [comment]
@whereisaaron Are you running Kubernetes with multiple API servers? If so, it might be related.

**Comment by whereisaaron** [comment]
Hi @chancez no just one API server. Happened to me a few times now, the pattern appears to be that after a 'delete --purge' a subsequent `update --install` will fail. After a few attempts or maybe a period of time, it will succeed. Maybe a lock is not being released (immediately)?

**Comment by bacongobbler** [comment]
I think this was fixed in later releases of helm, but please re-open if this was not. Thanks!

**Comment by iensu** [comment]
This still seems to happen on Helm 2.11.0. I can't get helm upgrade --install to work if the release does not already exist
