### ISSUE TITLE
Helm 2.5.0 release cannot be downloaded

### ISSUE THREAD

**Issue by ljnelson** [kubernetes/helm#2595]
As of 7:38 PM PDT on Monday, June 19, 2017, the release links reachable from https://github.com/kubernetes/helm/releases/tag/v2.5.0 result in `NoSuchKey` errors.

For example, as of this writing attempting to download https://storage.googleapis.com/kubernetes-helm/helm-v2.5.0-darwin-amd64.tar.gz results in:

    <Error>
      <Code>NoSuchKey</Code>
      <Message>The specified key does not exist.</Message>
    </Error>

**Comment by gpremsankar** [comment]
The issue exists for other Linux versions - https://kubernetes-helm.storage.googleapis.com/helm-v2.5.0-linux-amd64.tar.gz.sha256 and this returns the same error.  The SHA256 file does not have an entry for v2.50 yet.

**Comment by bacongobbler** [comment]
https://kubernetes.slack.com/archives/C51E88VDG/p1497907103200487

**Comment by theckman** [comment]
For those who aren't in the Slack group, here is the content of the message that @bacongobbler linked to:

```
technosophos
[06:18] 
Okay, so I’m back from vacation, and we’re trying to cut Helm 2.5.0, but our Google Cloud Storage bucket is blocking uploads. Looks like the Helm project’s bucket might have gotten disabled. We’re looking into it now.

[06:18] 
This is why coming back from a vacation is a bad idea. :wink:
```
As someone on my way back from vacation, I couldn't agree more. 😂

**Comment by erikschlegel** [comment]
Same here. Receive a `SHA sum of /tmp/helm does not match. Aborting.` due to the `NoSuchKey` when trying to install helm.

**Comment by ReSearchITEng** [comment]
That's why we have have option to set version desired :)
so just add this when trying to install:
``` --version v2.4.2 ```

**Comment by adamreese** [comment]
Binaries are now in the bucket!

**Comment by svelleweetakealot** [comment]
having some trouble here again. seems adding this in minkube to the docker deamon helps:

Add this to 
```
dockerd --disable-legacy-registry 
```
Am I the only one who's seeing this again?

**Comment by jeremyjjbrown** [comment]
I'm having problems pulling it as well with helm Client: &version.Version{SemVer:"v2.5+unreleased", GitCommit:"3cf8f2c8b3aaa7e1cd9a4a8fc389bd416b4965a5", GitTreeState:"clean"}

**Comment by bacongobbler** [comment]
Pulling the helm v2.5.0 client from Google Cloud Storage works fine for me.

@jeremyjjbrown can you open a new issue and describe in more detail what exactly is the issue you're having?

**Comment by bacongobbler** [comment]
@svelleweetakealot I'm confused by your question. Can you elaborate more on what the issue you're seeing, possibly by opening a separate ticket as well? I'm going to need more than "I'm having some trouble" to assist. :)
