### ISSUE TITLE
Post-processing manifests (Istio sidecar injection)

### ISSUE THREAD

**Issue by charith-qubit** [kubernetes/helm#2596]
Apologies if this question has been asked before -- Google did not yield anything helpful.

Is there a way to perform post-processing on the generated manifests before they are installed on the server? My specific use case at the moment is to inject the Envoy sidecar through the `istioctl kube-inject ...` command (https://istio.io/docs/tasks/integrating-services-into-istio.html#injecting-envoy-sidecar-into-a-deployment).

**Comment by michelleN** [comment]
@charith-qubit Have you seen the istio chart? https://github.com/kubernetes/charts/tree/6b02b2f873111737e0813b8825c6651def5e2ece/incubator/istio
It looks like they're running the `istioctl kube-inject` command after doing a `helm install`. See the NOTES.txt template in that chart as an example https://github.com/kubernetes/charts/blob/6b02b2f873111737e0813b8825c6651def5e2ece/incubator/istio/templates/NOTES.txt
Would that work for your use case as well?

To answer your question, no there is not a native way to perform post-processing on generated manifests before they are installed in your cluster. There is however a helm plugin that will do client-side generation of your manifests called helm-template: https://github.com/technosophos/helm-template. You might be able to use that functionality as a building block for what you're trying to do.

Let me know if that helps or if you still have questions.

cc/ @technosophos in case you have anything to add here.

**Comment by charith-qubit** [comment]
@michelleN I don't think the Istio chart itself requires injection. It can be installed with a simple `helm install` -- which I have done already. When you want to use Istio with your own app, their suggested approach is to run `kubectl create -f <(istioctl kube-inject -f <your-app-spec>.yaml)`, which modifies the manifests to add the sidecar. This effectively precludes me from using Helm to deploy and manage my app because the post-processing bit (`istioctl kube-inject ...`) cannot be integrated into the Helm workflow. 

I can of course do something like `helm install --dry-run --debug` or use the helm-template plugin to generate the manifests and then manually run them through `istioctl` and `kubectl`, but then I will only be using Helm as a template processor and will not be able to use if for upgrades and releases as I normally would.

**Comment by bxav** [comment]
@charith-qubit Did you find a solution for your issue? I have the same problem, and I don't really want to use helm only as a template processor. 

On the istio roadmap for 0.2 they have the:
> Fully-automated injection of Envoy proxies into Kubernetes pods.

If I understand well we should be able to use istio and helm transparently.

**Comment by charith-qubit** [comment]
@bxav No, I don't have a workable solution yet.

I read something about Istio considering the use of Kubernetes admission controllers to inject the sidecar. AFAIK, admission controllers in their current state can't modify the manifests. Maybe they have a PR in the works to add that functionality(?). That would be a nice solution to this problem.

**Comment by kuroneko25** [comment]
Same use case here. Is it not possible to pass a helm template to `istioctl kube-inject`?

**Comment by thehufbro** [comment]
So, this is a bit hacky, and it wont work for all cases since there are some errors when trying to modify the stateful sets (Mostly with modifying the pod disruption). But you can play with it and see what you come up with. 

Deploy your chart with helm, then use helm to get the chart info, which includes that chart manifest. 
You can use sed to grab the lines after MANIFEST, and use istio to inject its sidecar. Then apply the config using kubectl as a patch.  

If you come up with something that works better, please let me know. 

``helm get <release-name> | sed -e '1,/MANIFEST:/d' | istioctl kube-inject -f - | kubectl apply -f -``

**Comment by jipperinbham** [comment]
came across https://twitter.com/kelseyhightower/status/887322667837255680 today which looks to be a possible way forward and I _think_ would address this issue

**Comment by charlesverdad** [comment]
Unfortunately, k8s initializers are still in alpha and won't run in GKE for more than 30 days :( https://cloud.google.com/container-engine/docs/alpha-clusters

**Comment by bacongobbler** [comment]
related issue which I just closed as out of scope for helm (read: other things like k8s initializers are better suited for this task): https://github.com/kubernetes/helm/issues/2554

Alternatively, one can take the output of `helm template` to perform post-processing before installing the manifests. Hope this helps!
