### ISSUE TITLE
Proposal: Access environment template values from ConfigMaps

### ISSUE THREAD

**Issue by TD-4242** [kubernetes/helm#2597]
The current solution for environmental configuration is to have a separate yaml file and then deploy with 

`helm install --namespace qa application -f qa.yaml` 
or 
`helm install --namespace prod database -f prod.yaml` 

These often have different ingress points or replication requirements among other items.

I recommend having the ability to store this data in a ConfigMap of the installation namespace for the deployment.  Then have template access to these values, perhaps in a `{{ .ConfigMap.name.key }}` format.

**Comment by michelleN** [comment]
@TD-4242 how would someone override the environment data in the ConfigMap?

**Comment by TD-4242** [comment]
That does open up some questions I hadn't thought deeply about, my first thought was just update the ConfigMap, but of course you may need two things deployed in the same namespace that has a different setting.  When I imaged this it would be for holding fairly specific environmental things such as ingress/tls domain names and maybe replica counts, but it shouldn't be limited to this.  These would be meant to be environmental dependent and to deploy something with different ConfigMap values would be to deploy to another namespace where a different ConfigMap had been loaded.  such as deployments to minikube/dev/qa/prod as well as special branch deployments and test environments all in their own namespaces.

These are some possible options:
* A special `configmap` key inside values similar to `global`?
* A ConfigMap equivelent of `-f` and `--set`
