### ISSUE TITLE
Alias is added to requirements.lock after upgrading to helm 2.5.0 from 2.4.x and running helm dep

### ISSUE THREAD

**Issue by chancez** [kubernetes/helm#2598]
`alias: ""` is added to `requirements.lock` after running `helm dep build/update` but if it's not specified in `requirements.yaml` it should be omitted in `requirements.lock`

CC @sushilkm

**Comment by michelleN** [comment]
@chancez are you seeing that it is causing issues?

**Comment by chancez** [comment]
@michelleN It results in helm complaining my requirements files are out of sync, and it's a backwards incompatible change since it's updating the lockfile despite nothing changing IMO.

**Comment by sushilkm** [comment]
@michelleN I can have a look on this
@chancez thanks for finding this
