### ISSUE TITLE
Client: Repo Commands

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#260]
add, list, remove chart repositories

**Comment by michelleN** [comment]
This includes client side work as well as some server side refactoring. 
1. client side: add `helm repo add`, `helm repo list`, `helm repo rm` commands
2. server side: Chart repositories are referred to as registries in the DM world as of now which is confusing, so I'll change the registry references to chart repositories along with this work.

**Comment by jackgr** [comment]
@michelleN there are several types of registry in DM, not just object storage. Changing them all would probably touch quite a few files.

Another thing to consider is that repository in DM refers to object storage for deployment metadata. We have both transient (in memory) and persistent (mongodb) repositories.

**Comment by michelleN** [comment]
Yes @jackgr. Good points. I've seen and assessed the possible conflicts you mentioned and am working to make sure my changes cause no issues but also maintain a clear understanding and isolation of chart repositories.

**Comment by jackgr** [comment]
SGTM

**Comment by jackgr** [comment]
@michelleN can this issue be closed now?

**Comment by michelleN** [comment]
yes.
