### ISSUE TITLE
helm cannot download index from a url with params in it.

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/helm#2609]
We cannot download index.yaml from url such as https://{some url}/index.yaml?token={some_token}

Maybe we should parse the url string to the URL object, and then download..

**Comment by thomastaylor312** [comment]
@qiujian16 Can you post the output from the error when you try to use a URL with params?

**Comment by qiujian16** [comment]
helm repo add test https://raw.github.ibm.com/IBMPrivateCloud/charts/stable/repo/stable/index.yaml?token=AAAMT610ReP-GOlOvY-n0HWRh45O7WYzks5ZVBoawA%3D%3D
Error: Looks like "https://raw.github.ibm.com/IBMPrivateCloud/charts/stable/repo/stable/index.yaml?token=AAAMT610ReP-GOlOvY-n0HWRh45O7WYzks5ZVBoawA%3D%3D" is not a valid chart repository or cannot be reached: Failed to fetch https://raw.github.ibm.com/IBMPrivateCloud/charts/stable/repo/stable/index.yaml?token=AAAMT610ReP-GOlOvY-n0HWRh45O7WYzks5ZVBoawA%3D%3D/index.yaml : 404 Not Found

From code, I see that we add "index.yaml" at the tail of the url, I think we may have more validation on the repo url?

**Comment by bacongobbler** [comment]
https://raw.github.ibm.com/IBMPrivateCloud/charts/stable/repo/stable/index.yaml 404s for me, so it's probably a bad URL. I'd chat with IBM specifically about this.

**Comment by thomastaylor312** [comment]
@qiujian16 We are going to close this for now because it looks like it isn't an issue with Helm. If you check with IBM and it looks like it may be a bug in helm, feel free to ping us on this issue again
