### ISSUE TITLE
[Question] How to mount .p12 certificate file with helm?

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes/helm#2618]
Hi, all

Seems .p12 certificate file is different with pem format certificate, we can't open it with text editor and paste the content as helm values, is there a best way to mount .p12 certificates? Thanks.

**Comment by technosophos** [comment]
You'd have to convert it with the `openssl` tool before sending it to Helm.

**Comment by hiscal2015** [comment]
Thanks.
