### ISSUE TITLE
KUBECONFIG

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#2619]
in 2.3.0, the KUBECONFIG env variable can be used along with a passed in config file to configure tiller when it runs without a service token.

in 2.4+, this no longer works.

**Comment by thomastaylor312** [comment]
@kfox1111 I have been using `KUBECONFIG` without issue in 2.4 for a while. Is there a specific setup that may be causing this?

**Comment by kfox1111** [comment]
I did the following in a static pod, then updated the image from 2.3 to 2.4. 2.4 complains about not being able to contact localhost like it does when it doesn't see a KUBECONFIG.

{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
    "creationTimestamp": null,
    "labels": {
      "app": "helm",
      "name": "tiller"
    },
    "name": "tiller-deploy",
    "namespace": "kube-system"
  },
  "spec": {
    "containers": [
      {
        "env": [
          {
            "name": "TILLER_NAMESPACE",
            "value": "kube-system"
          }
        ],
        "image": "gcr.io/kubernetes-helm/tiller:v2.3.0",
        "imagePullPolicy": "IfNotPresent",
        "livenessProbe": {
          "httpGet": {
            "path": "/liveness",
            "port": 44135
          },
          "initialDelaySeconds": 1,
          "timeoutSeconds": 1
        },
        "name": "tiller",
        "ports": [
          {
            "containerPort": 44134,
            "name": "tiller"
          }
        ],
        "readinessProbe": {
          "httpGet": {
            "path": "/readiness",
            "port": 44135
          },
          "initialDelaySeconds": 1,
          "timeoutSeconds": 1
        },
        "resources": {},
        "volumeMounts": [
          {
            "name": "kubeconf",
            "mountPath": "/etc/kubernetes/admin.conf"
          }
        ],
        "command": [
          "/bin/sh",
          "-c",
          "KUBECONFIG=/etc/kubernetes/admin.conf /tiller"
        ]
      }
    ],
    "hostNetwork": true,
    "nodeSelector": {},
    "volumes": [
      {
        "name": "kubeconf",
        "hostPath": {
          "path": "/etc/kubernetes/admin.conf"
        }
      }
    ]
  },
  "status": {}
}

**Comment by bacongobbler** [comment]
KUEBCONFIG on v2.3.0/v2.4.0 works for me.

```
$ docker run gcr.io/kubernetes-helm/tiller:v2.3.0 /tiller
Unable to find image 'gcr.io/kubernetes-helm/tiller:v2.3.0' locally
v2.3.0: Pulling from kubernetes-helm/tiller
53ebc9bfbcc0: Pull complete 
702126defe4b: Pull complete 
Digest: sha256:fc5bef1464e78abe683c3e9e5e52dcb89111ab129049f8b3819eb157716fe4f7
Status: Downloaded newer image for gcr.io/kubernetes-helm/tiller:v2.3.0
Cannot initialize Kubernetes connection: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refused

$ docker run -v ~/.kube/config:/tmp/kubeconfig -e KUBECONFIG=/tmp/kubeconfig gcr.io/kubernetes-helm/tiller:v2.3.0 /tiller
Cannot initialize Kubernetes connection: invalid configuration: [unable to read client-cert /Users/bacongobbler/.minikube/apiserver.crt for minikube due to open /Users/bacongobbler/.minikube/apiserver.crt: no such file or directory, unable to read client-key /Users/bacongobbler/.minikube/apiserver.key for minikube due to open /Users/bacongobbler/.minikube/apiserver.key: no such file or directory, unable to read certificate-authority /Users/bacongobbler/.minikube/ca.crt for minikube due to open /Users/bacongobbler/.minikube/ca.crt: no such file or directory]

$ docker run -v ~/.kube/config:/tmp/kubeconfig -e KUBECONFIG=/tmp/kubeconfig gcr.io/kubernetes-helm/tiller:v2.4.0 /tiller
Cannot initialize Kubernetes connection: invalid configuration: [unable to read client-cert /Users/bacongobbler/.minikube/apiserver.crt for minikube due to open /Users/bacongobbler/.minikube/apiserver.crt: no such file or directory, unable to read client-key /Users/bacongobbler/.minikube/apiserver.key for minikube due to open /Users/bacongobbler/.minikube/apiserver.key: no such file or directory, unable to read certificate-authority /Users/bacongobbler/.minikube/ca.crt for minikube due to open /Users/bacongobbler/.minikube/ca.crt: no such file or directory]
```

**Comment by kfox1111** [comment]
I tried 2.5.0 and it is working. might have just been 2.4.0 and no others. I"m closing this.
