### ISSUE TITLE
make tests fail intermittently on master

### ISSUE THREAD

**Issue by sushilkm** [kubernetes/helm#2623]
I have not witnessed this a number of times, so filing this issue, have seen `TestSortManifests` fail a number of times without any changes on master branch or some change which should not effect this test, and this happens intermittently.

only finding for now is the test log:
```
=== RUN   TestHookSorter
--- PASS: TestHookSorter (0.00s)
=== RUN   TestSortManifests
2017/06/23 15:53:38 info: skipping unknown hook: "no-such-hook"
2017/06/23 15:53:38 info: manifest "seven" is empty. Skipping.
--- FAIL: TestSortManifests (0.01s)
	hooks_test.go:208: error unmarshaling JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
	hooks_test.go:228: Expected "kind: ConfigMap\napiVersion: v1\nmetadata:\n  name: eighth\ndata:\n  name: value", got "kind: Pod\napiVersion: v1\nmetadata:\n  name: fourth\n  annotations:\n    nothing: here"
	hooks_test.go:228: Expected "kind: Pod\napiVersion: v1\nmetadata:\n  name: fourth\n  annotations:\n    nothing: here", got "apiVersion: v1\nkind: Pod\nmetadata:\n  name: example-test\n  annotations:\n    \"helm.sh/hook\": test-success"
=== RUN   TestVersionSet
--- PASS: TestVersionSet (0.00s)
```

I would post more as I find anything new.
If someone is already aware about anything which makes it fail or would have it fix, let me know, until then I am investigating.

**Comment by gardlt** [comment]
i just ran into this issue. it seems to fail only in the circleci. when i run unit-test locally it passes.

**Comment by sushilkm** [comment]
I have seen it failing multiple times on my computer

**Comment by thomastaylor312** [comment]
@sushilkm I have run into this flake before too and I am not quite sure what is causing it. I am going to label this as a bug.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity as this hasn't popped up in several months, but please re-open if this still needs to be addressed. Thanks!
