### ISSUE TITLE
installation script: openssl sha -sha256 does not work with OpenSSL 1.1.0f  25 May 2017

### ISSUE THREAD

**Issue by dhensen** [kubernetes/helm#2624]
When using the [installation script](https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get): `openssl sha -sha256` does not work with OpenSSL 1.1.0f  25 May 2017 (which is currently latest)

I have to instead use:
```
openssl sha256 path
```
What version of openssl are you guys expecting/using?

(I'm running Arch Linux btw)

**Comment by thomastaylor312** [comment]
@dhensen I just duplicated this on debian as well. I know that locally on my Mac it is 0.9, but I don't think we ever specified a version. 

@technosophos How do we want to handle this? I can't seem to find a command with openssl that works across versions.

**Comment by technosophos** [comment]
Fall back to `shasum` when available?

**Comment by thomastaylor312** [comment]
@technosophos Good point. Let's do that as the fix for it

**Comment by technosophos** [comment]
Bumping to 2.6, since it won't actually impact a patch release.

**Comment by ineffyble** [comment]
See https://github.com/Lyndir/MasterPassword/pull/149 for context.

If `openssl sha` fails, `openssl sha256` should work. According to this PR, LetsEncrypt check OpenSSL version to determine the suitable command. This might be preferable to `shasum`.

**Comment by thomastaylor312** [comment]
Thanks @ineffyble! Good pointer on that. I'll probably implement it the way you suggested.

**Comment by thomastaylor312** [comment]
This was fixed with #2860
