### ISSUE TITLE
HELM_HOME is not used for plugin commands

### ISSUE THREAD

**Issue by joejulian** [kubernetes/helm#2630]
I created a path in a docker image in which to install the apps registry plugin, `/etc/helm/plugins/appr` with HELM_HOME set to /etc/helm in my Dockerfile, `env HELM_HOME=/etc/helm`. 

I install the plugin into that directory and can show that the plugin is installed.
```
# helm plugin list
NAME    	VERSION	DESCRIPTION                              
registry	0.5.0  	This plugin provides APPR client to Helm.
```

But if I try to use that plugin, it errors:
```
# helm registry list quay.io
Error: unknown command "registry" for "helm"
Run 'helm --help' for usage.
```

If I symlink /etc/helm to ~/.helm, it works.

Please allow HELM_HOME to specify the home everywhere unless overridden by --home. The precedence I would expect to always work is:
1. Unconfigured: use default (`$HOME/.helm`)
2. HELM_HOME is set and no command line switch given: Use the setting in HELM_HOME.
3. The command line switch --home is used, it should override HELM_HOME if it exists and should always be used.

---
```
# helm version -c    
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
I was also able to reproduce this. However, I was able to work around this via

```
$ HELM_PLUGIN=/tmp/helm/plugins helm template --help
locally render templates (helm-template 2.4.1+2)

Usage:
  template [flags] CHART

Flags:
  -x, --execute stringArray   only execute the given templates.
  -n, --namespace string      namespace (default "NAMESPACE")
      --notes                 show the computed NOTES.txt file as well.
  -r, --release string        release name (default "RELEASE-NAME")
      --set stringArray       set values on the command line. See 'helm install -h'
  -f, --values valueFiles     specify one or more YAML files of values (default [])
  -v, --verbose               show the computed YAML values as well.
```

**Comment by ketzacoatl** [comment]
I ran into this with `helm search`:

Search fails:
```
$ helm search prometheus
Error: open /home/user/.helm/repository/repositories.yaml: no such file or directory
```

Home is not the default, but exists:
```
$ helm home
/home/user/.helm_prod/
$ echo $HELM_HOME
/home/user/.helm_prod/
```

Some commands work fine:
```
$ helm repo list
NAME    URL                                             
stable  https://kubernetes-charts.storage.googleapis.com
local   http://127.0.0.1:8879/charts
```
