### ISSUE TITLE
Docs: easy way to permalink sections

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#2633]
It would be great to be able to easily permalink a section in https://docs.helm.sh, something similar to the icon that shows up when hovering over a heading when viewing a markdown doc on GitHub.

**Comment by flynnduism** [comment]
Yep, easy win. I'll implement this asap

**Comment by flynnduism** [comment]
Permalinks are now available for titles and subtitles in the docs. This can be closed.

![permalinks](https://user-images.githubusercontent.com/686194/28796765-a5b417aa-75f3-11e7-9268-81e8d969af71.gif)

**Comment by prydonius** [comment]
@flynnduism sweet, thanks a lot!!
