### ISSUE TITLE
Ability to run helm with ipv6 disabled

### ISSUE THREAD

**Issue by SEJeff** [kubernetes/helm#2634]
Looking through #1410, #2223, #2482, the solution to this error is to enable ipv6:

```
E0629 13:56:41.645289   65789 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:44687: socket: address family not supported by protocol
```

At my company, we disable ipv6 explicitly via the Linux kernel boot option `ipv6.disable=1` entirely for on-premise servers, which includes all of our kubelets and Linux desktops. We would like a way to not require ipv6 to use helm. It seems you can mitigate it via setting `HELM_HOST` to `127.0.0.1`, or something else, but I'm not sure that is the correct fix.

Ideally, there would be a flag to only enable ipv4 or ipv6 much like there is in ping or other unix tools.

**Comment by seh** [comment]
Are you saying that when you run Helm on a machine with IPv6 disabled, Helm doesn't work, and you want it to tolerate the lack of IPv6, perhaps instructing it via command-line flag which protocol versions to use?

**Comment by SEJeff** [comment]
@seh yessir, that is what I would like if at all feasible. Both our clients or servers have IPv6 disabled by a design that is entirely out of my control. Our entire k8s footprint is on premise as well, so no cloud bits to worry about.

**Comment by SEJeff** [comment]
Another option is to simply fallback when ipv6 is disable either via no ipv6 interface up and/or the ipv6 sysctl being set to 0. Seems like a much better user experience ie: works out of the box.

**Comment by technosophos** [comment]
I believe that configuring /etc/hosts to point to the ipv4 address for localhost is probably all that needs to happen. (you might need to remove `::1 localhost` too)

**Comment by SEJeff** [comment]
@technosophos this is definitely an improvement, thanks.

The error still exists however:

```
$ helm list
E0629 15:20:56.429852  118376 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:45318: socket: address family not supported by protocol
NAME         	REVISION	UPDATED                 	STATUS  	CHART        	NAMESPACE
zeroed-jackal	1       	Thu Jun 29 14:36:33 2017	DEPLOYED	jenkins-0.7.4	default  
```

**Comment by leonlibraries** [comment]
@technosophos If I disabled IPv6 , this situation still confuses me too.

 Is there a way to fix it without enable IPv6 support? THX...

**Comment by osterman** [comment]
I'm running `alpine:3.6.2` under `docker` (for Mac) and cannot get any of the prescribed fixes to squelch the annoying (but benign) error message.

What I've tried:
1. `docker run --sysctl net.ipv6.conf.all.disable_ipv6=1 .......` (via: https://stackoverflow.com/questions/30750271/disable-ip-v6-in-docker-container)
2. removed `::1` mapping for `localhost` in `/etc/hosts`
3. added `net.ipv6.conf.all.disable_ipv6=1` to `/etc/sysctl.d/00-disable-ipv6.conf`

And as a variation of the above, I've tried replacing `all` with `lo` (for local loopback), but also to no avail.

I always get....
```
E0809 04:18:53.872766      20 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:39451: bind: cannot assign requested address
```
And then falls back to `ipv4` and works like a charm.

**Comment by Smana** [comment]
I faced the same issue there and we use the workaround by setting localhost to the ipv4 loopback.
However that'd be preferable to disable ipv6 from helm.

**Comment by ReSearchITEng** [comment]
Still here in helm 3.0.3 with k8s 1.17.2

**Comment by slavitch** [comment]
Reopen this please.

**Comment by hickeyma** [comment]
@slavitch What version of Helm are you using?
