### ISSUE TITLE
Automatically Roll Deployments When ConfigMaps change

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/helm#2639]
I dont really get how to use this feature from docs:
https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

```
checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
```

What is `/secret.yaml` ?

How does this feature essentially works? How does it know the changes in configs-map/secrets?

It would be nice if tiler could watch config-maps changes in cluster somehow  (or probably configs maps deployed using heml) and roll dependant deployments if values they depend on changed, I believe it is not possible now?

**Comment by seh** [comment]
At present, Tiller does not watch the Kubernetes objects it creates.

The suggested technique above is a way to force Tiller to change a _Deployment_ object when some other pertinent file changes, such as the hypothetical _secret.yaml_ file above that would define a _Secret_ object that the _Deployment_'s pods use.

Normally, even if you changed the _secret.yaml_ file and updated the chart that contains it, asking Tiller to upgrade to the new chart version would cause Tiller to update the _Secret_, but not the _Deployment_, because nothing in the existing _Deployment_ object differs from the object that the rendered chart requests. Tying the definition of the _Deployment_ object to the content of the _secret.yaml_ file forces Tiller to update the former object when the latter changes in the installed chart.

**Comment by whitecolor** [comment]
Ah ok, so this annotation is just a trigger to change, and can be named anything not only `checksum/config`?

**Comment by seh** [comment]
Yes, the name is immaterial. I take it as just a suggestion, so that its meaning would be clear, though note that there is a convention of choosing something that looks like a domain name for the annotation prefix—even though annotations keys are not subject to the same [syntactic restrictions as label keys](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set).

**Comment by bgrant0607** [comment]
See also:
https://github.com/kubernetes/kubernetes/issues/22368
https://github.com/kubernetes/kubernetes/pull/31701#issuecomment-252110430

**Comment by jstrachan** [comment]
FWIW until kubernetes itself has some kind of capability in that area we created a little microservice to watch ConfigMaps and do rolling upgrades on Deployments when they change via annotations:
https://github.com/fabric8io/configmapcontroller/

**Comment by midihenry** [comment]
If the `secret.yaml` template reads values from the `values.yaml` file, the checksum won't change even if those values change since the checksum if for the template and not the rendered result.
I tried this with configmaps, is there a way to use the checksum of the rendered template file  instead of the template in helm? That would be really great

**Comment by bacongobbler** [comment]
If you pipe the output of `tpl` into `sha256sum`, that should render a particular template with its values.

```
checksum: {{ tpl (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```

More info here: https://docs.helm.sh/developing_charts/#using-the-tpl-function

**Comment by midihenry** [comment]
thanks @bacongobbler, but that didn't work for me.
Tried it, but got this error:
```
Error: UPGRADE FAILED: parse error in "/templates/deployment.yaml": template: /templates/deployment.yaml:5: unexpected <.> in operand
```
for this line:
```
checksum/config: {{ tpl (print $.Template.BasePath "/configmap.yaml") $. | sha256sum  }}
```

**Comment by bacongobbler** [comment]
Sorry, I must've messed up the syntax. This is all from memory :)

Try replacing the `$.` with `$` so it looks like this:

```
checksum: {{ tpl (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
```

**Comment by midihenry** [comment]
Tried it, unfortunately it is still returning the same checksum even after updating the `values.yaml` file 😞
```
$ kubectl describe deployment seed-service | grep checksum
Annotations:            checksum/config=a22a0640026634ea56e0cca8879ac16ec202e8767321056063892c246b200fcb

$ helm template . -x templates/deployment.yaml | grep checksum
checksum/config: a22a0640026634ea56e0cca8879ac16ec202e8767321056063892c246b200fcb
```
Tried running a helm upgrade just in case, also the deployment was not updated.

**Comment by midihenry** [comment]
Looks like the tpl function is only returning the file path here:
```
{{ tpl (print $.Template.BasePath "/configmap.yaml") $ }}

$ helm template . -x templates/deployment.yaml  | grep checksum
    checksum/config: seed-service/templates/configmap.yaml
```
Isn't it supposed to return the contents of the file?

**Comment by alexpirine** [comment]
@midihenry it's not working for the base use case where the configmap.yaml file is overrided by values from a parent chart, so I wouldn't say you can just close the issue…

**Comment by Dmitry1987** [comment]
It didn't worked for some reason on a daemon set, on one of our legacy clusters on 1.8 :(  the configmap was updated and the daemon set pods are not rolling to re-read it.

**Comment by alexpirine** [comment]
@k8s-ci-robot /reopen

**Comment by komal-SkyNET** [comment]
@midihenry @Dmitry1987 True, doesn't work on deamonsets. Just verified.

**Comment by ltagliamonte-dd** [comment]
I'm using terraform and passing all the values of `values.yaml` dynamically via terraform helm provider.
In this way the checksum of the file doesn't change, even if the confimap gets successful updated with the new values the pods in my deployment don't get bounced.

**Comment by adityagu0910** [comment]
I am trying the same with statefulset and it is not working. All the time I am getting same checksum value. Seems sha256sum is getting calculated on the file itself and not its content 
I tried with below two commands as $.Template.BasePath is not working for my helm deployment 

`checksum/config: {{ include (print $root.Template.BasePath "/configmap.yaml") $root | sha256sum }}` 

`checksum/config: {{ include (print $root.Template.BasePath "/configmap.yaml") . | sha256sum }}`

**Comment by adityagu0910** [comment]
Also i want to monitor the changes in multiple properties file in multiple directories. Is there a way to do this ?
 below  works fine for one file only.
`checksum/config1: {{ $root.Files.Get "configmaps/abc.properties" | sha256sum }}`

I am creating my config map using below which list all the properties file in one config map that i can mount in my liberty server and access these properties files.
`  {{ range $path, $bytes := $root.Files.Glob "configmaps/**" }}
  {{ base $path }}: |-
{{ $root.Files.Get $path | indent 4 }}
  {{ end }}`

**Comment by adityagu0910** [comment]
seems this one is working. the only thing is that i will have multiple checksum for all files in one field.

`        checksum/config1: {{ range $path, $bytes := $root.Files.Glob "configmaps/**" }} {{ $root.Files.Get $path | sha256sum }} {{ end }}`

**Comment by himmakam** [comment]
Hi, can someone help me with this. I have a config-map with below  where it calls the loadconfigfiles helper function. And I do get values from external file globalvalues.yaml which I would be passing at the time of helm deployment. Can I know how to update the pod with new configmap when any value is changed in globalvalues.yaml file. 

The command used to deploy app is - helm install app app --values=globalvalues.yaml

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.appname }}-configmap
data:
  {{template "loadConfigFiles" $}}

**Comment by amolsh** [comment]
> I am trying the same with statefulset and it is not working. All the time I am getting same checksum value. Seems sha256sum is getting calculated on the file itself and not its content
> I tried with below two commands as $.Template.BasePath is not working for my helm deployment
> 
> `checksum/config: {{ include (print $root.Template.BasePath "/configmap.yaml") $root | sha256sum }}`
> 
> `checksum/config: {{ include (print $root.Template.BasePath "/configmap.yaml") . | sha256sum }}`

@adityagu0910 were you able to make it work with statefulset. I am seeing the same behavior with statefulset, everytime i get same checksome even after configmap is updated. I am using the following syntax `checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}`

**Comment by salamovz** [comment]
> seems this one is working. the only thing is that i will have multiple checksum for all files in one field.
> 
> ` checksum/config1: {{ range $path, $bytes := $root.Files.Glob "configmaps/**" }} {{ $root.Files.Get $path | sha256sum }} {{ end }}`

Thanks for this. Based on it I created one with short output:
`kind: ConfigMap
metadata:
  annotations:
    checksum/config1: {{- range $path, $bytes := .Files.Glob "files/**" -}} {{- $sha := $.Files.Get $path | sha256sum -}} {{- $shasha := printf "%s%s" $.Values.cmsha $sha -}}{{- $_ := set $.Values "cmsha" $shasha -}} {{- end -}}{{- .Values.cmsha | sha256sum  | indent 2 }}`

**Comment by mshivanna** [comment]
`        checksum/create_databases_config: {{ $.Files.Get "files/create_databases.sql.tpl"| sha256sum }}
        checksum/install_plugins_config: {{ $.Files.Get "files/install_plugins.sql.tpl"| sha256sum }}
        checksum/ota_cnf_config: {{ $.Files.Get "files/ota.cnf"| sha256sum }}`
