### ISSUE TITLE
Allow remote values.yaml with -f

### ISSUE THREAD

**Issue by mcasimir** [kubernetes/helm#2642]
It would be great to be able to use `-f` option with remote files, same as `kubectl apply -f` works.  

``` sh
helm install my-repo/my-service-template
  -f https://config-repo.example.com/my-namespace/my-service-config.yml
```

**Comment by seh** [comment]
I didn't realize that _kubectl_ accepted such URLs, but [indeed it does](https://github.com/kubernetes/kubernetes/blob/bce32b66cd7e2276169602928384fae31301b687/pkg/kubectl/resource/builder.go#L135-L141). [The URL retrieval implementation](https://github.com/kubernetes/kubernetes/blob/bce32b66cd7e2276169602928384fae31301b687/pkg/kubectl/resource/visitor.go#L228-L294) is 66 lines, including comments.

At present, [_helm install_ uses `io.ReadFile`](https://github.com/kubernetes/helm/blob/master/cmd/helm/install.go#L313) to interpret the flag value as a file path. We'd have to generalize that interpretation.

**Comment by technosophos** [comment]
It'd actually have to go through the protocol handler library, too.
