### ISSUE TITLE
'tips and tricks' link in docs.helm.sh not working

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/helm#2645]
The specialized function link here:
<img width="1034" alt="screen shot 2017-07-05 at 11 52 28 am" src="https://user-images.githubusercontent.com/13337345/27880049-7b2f3ce2-6178-11e7-9c40-12d1c3b1ed37.png">

links to `https://docs.helm.sh/developing_charts/#charts_tips_and_tricks` which does not resolve.

If I C-f search for 'tips and tricks' I find the right section. 

<img width="969" alt="screen shot 2017-07-05 at 11 52 17 am" src="https://user-images.githubusercontent.com/13337345/27880052-7dc2d13a-6178-11e7-9ff5-4e340a9ca0f7.png">

I'm not sure how to contribute to these docs as they appear to be assembled somehow. I'd run through the document on how to build and test the docs if someone can link me to it.

**Comment by seh** [comment]
@flynnduism, I can't assign an issue to you, but I hope you can help here.

**Comment by bacongobbler** [comment]
docs link: https://github.com/helm/helm-www

**Comment by flynnduism** [comment]
@seh thanks, I'll sort this out

**Comment by bacongobbler** [comment]
https://github.com/helm/helm-www/pull/50

**Comment by flynnduism** [comment]
Fixed and deployed. Thanks @seh!

**Comment by technosophos** [comment]
Marking this fixed, per last comment.
