### ISSUE TITLE
Docs: Change example chart away from mysql

### ISSUE THREAD

**Issue by johnharris85** [kubernetes/helm#2646]
As mysql depends on a PV being available on the cluster, this doesn't seem a great 'first example' for people potentially playing with helm for the first time. Maybe something that doesn't have a PV dependency that people can get up and running a little easier?

Maybe the kube-dashboard?

**Comment by seh** [comment]
As of Kubernetes version 1.6, running the Dashboard requires granting it the "cluster-admin" _ClusterRole_, which helps by showing how RBAC might be involved in a chart, but some would-be Helm users won't have sufficient privileges to bind that role themselves.

What about a stateless Web application using _nginx_?

**Comment by johnharris85** [comment]
Ye nginx was my first thought, although the one in stable is an ingress example and relies on LB / bunch of other stuff etc... All of them seem to depend on volumes or some non-default RBAC setup.
