### ISSUE TITLE
helm upgrade does not change resource value 

### ISSUE THREAD

**Issue by SiriusRed** [kubernetes/helm#2647]
Hi,
thx for flexible tools

I have a question about resource updating mechanism.

PROBLEM: 
When I want update a some deployment - `helm upgrade my-release .` some values don't change

Steps
1) I Installed chart with helm (deployment and service) `helm upgrade my-release . --install`.
 Part of deployment-template:

> ....
>         env:
>           {{- range .Values.container.env }}
>             - name: {{ .name }}
>               value: "{{ .value }}"
>           {{- end }}
> ....

which generate the manifest, with part like 

> ....
>         env:
>             - name: TEST_VAR
>               value: SomeValue
> ....

2) then, I made some changes  in another deployments.yaml (which the same with template result of chart deployment) and run `kubectl replace deploy -f deployment.yaml`
Part of deployment.yml which is not a template:
> ...
>           env:
>             - name: TEST_VAR
>                valueFrom:
>                 configMapKeyRef:
>                   name: someValueKeyFromConfigMap
>                   key: someValueFromConfigMap
> ...
Env vars were not changed

3) But, when I run `helm upgrade my-release .` again, the var doesn't change and stay `valueFrom` instead of `value`, like in my template 

And, when I made changes in value.yml - I received a message:
`spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when \`value\` is not empty`

So, which command of helm have the same mechanism like a `kubectl replace`.  

`Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}`

`Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}`

**Comment by technosophos** [comment]
What does `helm get RELEASE_NAME` show you? Do you see the changes there?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
