### ISSUE TITLE
Write a design document for dependencies

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#265]
Currently, helm and dm have different dependency mechanisms, and dm actually resolves dependencies, either by deploying nested charts, or by pulling values from deployed resources through references.

We need to resolve these mechanisms, and preferably end up with a single solution. A design document should be written to capture the solution we decide on.

**Comment by sparkprime** [comment]
There are several cases:
1) Dependency on service defined elsewhere in the same chart
2) Self hosting: Dependency on service defined in a chart that is referenced from this one (nested charts)
3) Hosted service: Dependency on service defined in a chart that is not part of this unit of deployment (could be managed by another team for example)
4) Dependency on a service that is managed by another team and we don't have access to the chart, in fact it may be some legacy service on IAAS or bare metal.

3 & 4 are probably really the same, or at least both solvable with an explicit host / port or service name.

Ideally, these should be interchangeable without major changes to the chart.  I.e. it should be possible to take a chart where all components are within that chart (or nested charts) and instead point them to the live prod infrastructure.  This is quite common if you want to e.g. develop the web front end of some service against live data.

I had examples of all of these working in micromanage on IAAS using a range of techniques from embedding ips directly in config / hosts files to split horizon and full blown DNS.  However I think in k8s the environment variables simplify things drastically and it should not need a complex solution to meet all these requirements.

I'm looking forward to seeing this design doc :)

**Comment by jackgr** [comment]
Thanks for the comments, @sparkprime. Cases 3 & 4 should probably be handled using some kind of service broker that would let DM find and provision access to the dependency on behalf the depending chart.

Would you be interested in taking a first cut at the document?

**Comment by sparkprime** [comment]
Sorry I never responded!  Yes I would be interested, but before putting pen to paper I'd have to establish what consensus already exists about requirements, as well as making sure I fully understand the prior art in Helm, DM, and Kubernetes.  So I can certainly go away and do the latter, and then perhaps chair a meeting to discuss the former.  What's the timeline on this?

**Comment by jackgr** [comment]
Probably quite important, since it affects the way we handle chart
references in DM templates, among other things. In fact, we have yet to
fully integrate charts and templates in the code, and there's a fair amount
of risk in this area until we do, so the sooner the better to answer this
question.

Jack Greenfield | Google
