### ISSUE TITLE
Clean way to check if a release exists

### ISSUE THREAD

**Issue by rcorre** [kubernetes/helm#2655]
The cmd code for helm's `upgrade -i` contains this [rather ugly solution](https://github.com/kubernetes/helm/blob/master/cmd/helm/upgrade.go#L151) to check if a release exists.

I'm using `helm.Interface` in a go project and want to use `upgrade -i`. Unfortunately, this means repeating that same messy check in my code. Is there a way to make it cleaner?

A few ideas:

- an `UpdateOrInstall` option I can pass to `UpdateRelease`
- a `ReleaseExists` function in `helm.Interface`
- Tiller itself implements `upgrade -i`, so the client code doesn't have to scan error strings

**Comment by technosophos** [comment]
The preferred way of finding if a release exists is to do what we do in Helm upgrade: check whether there is any history for a release with the given name.

The interface is frozen until Helm 3, and we are trying to freeze the gRPC API for the rest of the Helm 2.x lifecycle too. So it's unlikely that we'll add this in the near future. But I'm marking this for discussion in the Helm 3 planning cycle.

**Comment by rcorre** [comment]
> The preferred way of finding if a release exists is to do what we do in Helm upgrade: check whether there is any history for a release with the given name

If there isn't history, you get an error and have to scrape the error string to determine whether there actually isn't a release or whether some other error occurred. The 'preferred' approach feels hacky to me.

Thanks for considering it for helm 3 though. Even if the hackiness needs to stay, it would be nice to at least wrap it in an `Exists` method so users don't have to copy-paste it to their code.

**Comment by rcorre** [comment]
> The preferred way of finding if a release exists is to do what we do in Helm upgrade: check whether there is any history for a release with the given name.

It just occurred to me ... would the following be a cleaner way that doesn't involve error string scraping? Or is there some limitation I'm not seeing?

	releases, err := svc.helm.ListReleases(
		helm.ReleaseListFilter(name),
		helm.ReleaseListLimit(1),
		helm.ReleaseListNamespace(namespace),
		helm.ReleaseListStatuses([]release.Status_Code{
			release.Status_UNKNOWN,
			release.Status_DEPLOYED,
			release.Status_DELETED,
			release.Status_DELETING,
			release.Status_FAILED,
		}),
	)
	return releases.Count > 0, err

**Comment by rcorre** [comment]
I just discovered the hard way that `helm.ReleaseListFilter(name)` matches any part of the name, so my suggestion above doesn't work. Back to scraping strings ...

**Comment by thomastvedt** [comment]
Just as a reference to the future me:
`helm upgrade --install`

This will install or upgrade...
https://helm.sh/docs/helm/helm_upgrade/

 -i, --install                      if a release by this name doesn't already exist, run an install

**Comment by louis-cuny** [comment]
It seems you can use `helm status RELEASE-NAME` in an if condition

**Comment by ccmcbeck** [comment]
`status=$(helm status RELEASE_NAME  2>&1) && [[ "$status" != "Error: release: not found" ]]` is still the best way to go.  You should also trap for a non-zero exit code in case the helm command fails
