### ISSUE TITLE
How I can disable specific command from helm auto completion?

### ISSUE THREAD

**Issue by ryukinix** [kubernetes/helm#2659]
At example I have the `command` `gdb` disabled with `(put 'gdb 'disabled t)` for personal reasons. However the command still appears on autocomplete and annoys me. This is possible?

**Comment by technosophos** [comment]
I think you have this project confused with https://github.com/emacs-helm/helm

**Comment by ryukinix** [comment]
Wow!!! My bad! You are completely right! Sorry for this! 😆
