### ISSUE TITLE
`helm dependency build` should not change 'requirements.lock'

### ISSUE THREAD

**Issue by Mario54** [kubernetes/helm#2661]
When reading `helm dependency update --help`, I'm under the impression that the `requirements.lock` will not be changed:

> Build is used to reconstruct a chart's dependencies to the state specified in
the lock file. This will not re-negotiate dependencies, as 'helm dependency update'
does.

However, when running `helm dependency build` it changes the `generated` timestamp inside `requirements.lock`. This is confusing because it shows up when a developer executes `git status` even though the only change is the new `generated` timestamp.

Is this intended? If it is, is there a way to build charts from `requirements.lock` without updating the file?

**Comment by technosophos** [comment]
That is not the intended behavior. You are correct. A `helm dependency build` should not modify the lock file if the lock file is present. That includes the timestamp.

**Comment by zjj2wry** [comment]
what the issue status? i can not reappear

**Comment by Mario54** [comment]
Hmm you're right, I tried creating a simple chart and can't seem to reproduce.

I'll investigate as to why this was happening on my other chart.

**Comment by Mario54** [comment]
I read the code for `helm dependency update` and the only way I'm thinking this is happening is that somehow Helm cannot find the `requirements.lock`, so it creates a new one. It's clear from the code that if a `requirements.lock` is found, `helm dependency update` never updates any file.

However, I can't confirm that this is the case because even if I add `--debug` the command doesn't log this information 😞

**Comment by Mario54** [comment]
I built Helm and added a log and confirmed my theory.

It was indeed a problem in my setup. The file was getting cleaned by a bad Makefile target. My bad.

So there's no issue with Helm 😄 Sorry for wasting your time!
