### ISSUE TITLE
Several map lookups in chart value coalescing procedure can be eliminated

### ISSUE THREAD

**Issue by seh** [kubernetes/helm#2663]
In #2648, @scottrigby augmented the chart value coalescing procedure to treat null values specially, indicating that the given mapping should be removed. Those changes revealed [a few opportunities for removing map lookup expressions](https://github.com/kubernetes/helm/pull/2648#discussion_r126238947) in the [`chartutil.coalesceValues`](https://github.com/scottrigby/helm/blob/8be9bb51de31b551ab4178d6e43616fbbbca9850/pkg/chartutil/values.go#L263-L304) function—assuming that the Go compiler won't eliminate them already via CSE.

While we're there, consider [moving part of a comment referring to the YAML specification](https://github.com/kubernetes/helm/pull/2648#discussion_r126239691) to the unit test that makes use of the referenced definitions.

**Comment by thomastaylor312** [comment]
I was looking at this and realized it really is a great starter issue for someone who wants to get into helm. I am going to leave it open for a while and see if anyone would like to take it. If no one takes it, I'll fix this.
