### ISSUE TITLE
adding requirements.yaml file removes manual dependencies from install

### ISSUE THREAD

**Issue by jeff-knurek** [kubernetes/helm#2684]
The documentation [[1](https://docs.helm.sh/developing_charts/#charts)] describes two ways to add subcharts (via requirements.yaml or manually adding to `charts/`)

If you create subcharts to the `charts/` directory of the parent (in this case `simple`)
```
dep-test/
├── Chart.yaml
├── charts
│   └── simple
│       ├── Chart.yaml
│       ├── charts
│       ├── templates
│       │   ├── NOTES.txt
│       │   ├── _helpers.tpl
│       │   └── deployment.yaml
│       └── values.yaml
├── templates
│   ├── NOTES.txt
│   ├── _helpers.tpl
│   └── service.yaml
└── values.yaml
```
and package the chart (or `helm install --dry-run --debug dep-test`) you'll get the subchart's deployment included. 

### BUG:
The moment you add a `requirements.yaml` file (even if it's an empty file), the `simple` subchart is ignored.

### Workaround:
Use the `requirements.yaml` file to install external dependencies with `helm dependency update dep-test`, then delete the `requirements.yaml` (and `.lock`) file. 

1. https://docs.helm.sh/developing_charts/#charts

**Comment by roybotnik** [comment]
It seems that dependencies don't install at all if you have a requirements.yaml and requirements.lock. My requirements.yaml contains deis workflow, and after running helm dependency update and installing a new release, the deis workflow chart did not install. Deleting requirements.yaml and requirements.lock fixed it...

**Comment by prat0318** [comment]
I am also facing the same issue as ^. Is deleting the requirements* file the only option here?

**Comment by bacongobbler** [comment]
Is this relevant on Helm 2.7? I'm pretty sure this might've been related to the bug introduced in helm 2.6 which was fixed in 2.6.1.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by pesimon** [comment]
I could re-produce this behaviour with Helm 2.7.2 and 2.8.0 

@bacongobbler whats needed to re-open this?

**Comment by d-baranowski** [comment]
We're seeing a similar issue.

Steps: 
1. Delete the lock file
2. helm dep update
3. helm upgrade --install
4. Delete the chart from the charts directory
5. helm update --install again

Expected behaviour:
Deployment fails due to missing dependency

Actual behaviour:
Deployment happens and uses old dependency from historic deployment that was not present in the charts directory. 

What is the logic in helm for dependency resolution?
