### ISSUE TITLE
Users should know when the client is failing, wether or not it's tiller is online and ready.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/helm#2689]
Looks like at least some kubernetes deployments don't allow things running in kube-system to use the service accounts to do list operations.  

Reasons why using the kube-system default for helm's home should lead to a warning.
- If kube-system is secured in any ways, its more likely tiller will be happier in its own namespace.
- Even if kube-system is *not* secured, tiller will still be happy.
- I believe kube-system itself should be reserved by default by kube processes anyways.

Note that not all clusters secure kube-system:  I'm checking wether this is the case on minikube as well .

**Comment by bacongobbler** [comment]
We've been deploying to kube-system since v2.0 and we can't break backwards compatibility so it'll have to retain that behaviour for now. If you want to deploy tiller in a different namespace, there's always the `--tiller-namespace` flag on `helm init`.

**Comment by jayunit100** [comment]
This works ok for me on minikube, which is good news.  

I guess what we *should* do, then, is not have tiller infinitely retry, and let if fail, so that its obvious that its down, rather then have it zombie around permissions failure forever.

```
➜  ~ kubectl logs tiller-deploy-3703072393-vd7pt --namespace=kube-system
[main] 2017/07/14 17:40:59 Starting Tiller v2.5.0 (tls=false)
[main] 2017/07/14 17:40:59 GRPC listening on :44134
[main] 2017/07/14 17:40:59 Probes listening on :44135
[main] 2017/07/14 17:40:59 Storage driver is ConfigMap
```
