### ISSUE TITLE
Add a basic search widget to doc site

### ISSUE THREAD

**Issue by gtaylor** [kubernetes/helm#2698]
It would be really great to have a basic search widget somewhere in the nav or header for the doc site. It is true that I can go to my search engine of choice and manually form a search query only covering the doc site. However, that's more context switching on top of whatever I'm trying to look up while using helm.

I'll hold on making implementation suggestions, since that's probably not valuable at this point. There are tons of options that are good enough for basic site search.

Really loving the new doc site! Thanks to everyone who contributed.

**Comment by flynnduism** [comment]
Good idea @gtaylor, an embedded search would be helpful. I've done this in the past, there's a few different ways to do [client-side searching](https://halfelf.org/2017/hugos-lunr-search/) in a Hugo static site. 

Happy to tackle this when I have some cycles.

**Comment by bacongobbler** [comment]
I'm going to close this so we can continue tracking effort at helm/helm-www#56. Thanks!
