### ISSUE TITLE
feat: install Helm client identical to Tiller version

### ISSUE THREAD

**Issue by jcantosz** [kubernetes/helm#2699]
I have tiller installed in a cluster and I would like to get the version of tiller, before I install the helm CLI

I can install the helm CLI, see that I have a version mismatch with tiller, and downgrade the cli to match that of tiller's but I would like to be able to find the tiller version and install the correct helm version without going through this process. 

Current process requires a number of commands before I know i have the wrong version of the cli
```
ubuntu@jesse-master:~$ curl -o helm.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-v2.5.0-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.3M  100 14.3M    0     0  1280k      0  0:00:11  0:00:11 --:--:-- 3059k
ubuntu@jesse-master:~$ tar -xvzf helm.tar.gz 
linux-amd64/
linux-amd64/helm
linux-amd64/LICENSE
linux-amd64/README.md
ubuntu@jesse-master:~$ ./linux-amd64/helm init --client-only
$HELM_HOME has been configured at /home/ubuntu/.helm.
Not installing tiller due to 'client-only' flag having been set
Happy Helming!
ubuntu@jesse-master:~$ ./linux-amd64/helm list
Error: incompatible versions client[v2.5.0] server[v2.4.1]
```

Alternatively I am able to get this information by looking at the logs of the tiller pod:
```
ubuntu@jesse-master:~$ kubectl logs tiller-4045722333-8lfxq  --namespace=kube-system
Starting Tiller v2.4.1 (tls=false)
GRPC listening on :44134
```
My preference is to automate this process , and I would like to avoid parsing logs if possible. A REST endpoint would be ideal.

I found this PR, but it does not look like it was merged: https://github.com/kubernetes/helm/pull/2177

**Comment by bacongobbler** [comment]
Tiller communicates via gRPC so there is an endpoint, but it can't be consumed by common tools like `curl`. An easier way would be to just check the deployment object directly and inspect the image tag. That will give you the version of tiller running in your cluster, assuming it's an official helm release.

**Comment by jcantosz** [comment]
Thanks for the info @bacongobbler 

Using the method you described I am able to get the image tag via:
```bash
ubuntu@jesse-master:~$ kubectl get  deploy tiller  --namespace=kube-system -o='jsonpath={.spec.template.spec.containers[0].image}' | sed 's/.*v\([0-9\.]*\)/\1/g'
2.4.1
```

With the log method I can get the version via:
```bash
kubectl logs -l name=tiller  --namespace=kube-system  | grep "Starting Tiller" | sed 's/.*v\([0-9\.]*\).*/\1/g'
2.4.1
```

I would prefer not to depend on either of these items being present. For now I will test using the suggested solution

**Comment by bacongobbler** [comment]
I noticed no mention of `helm version` in your comment, which will display the client and server version available through the CLI, though that means grabbing the CLI in the first place which I assume is the issue you're trying to solve.

Honestly I don't have any idea how you'd like this to be solved. In any case, if you feel like running raw GRPC you're going to need to communicate with the API, which means talking GRPC or by inspecting the running image through kubectl.

Could you please explain how you'd like this issue to be solved?

**Comment by jcantosz** [comment]
If there were a helm init option like `--update-client` which would match the client version with the existing tiller version that would be helpful. 
`helm init --client-only --update-client`

### Background
I see that there is an `--upgrade` command in the init for if tiller is already present, and this would presumably solve the version mismatch, however I would like to preserve the tiller version. Essentially I want to run automated tests against our cloud platform using some of the helm charts we have, to validate that new releases continue to work well. The platform is stood up by another process, and tiller is already on the cluster. Since we will ship/support this version of helm/tiller, I don't want to upgrade the tiller component. Having an officially supported way up/downgrading the client would also mean that if something changes (output format changes, releases published elsewhere, tiller image name changes) the automation will still work

**Comment by bacongobbler** [comment]
So to solve that issue, there are certain cloud providers like Azure Container Services which are proposing convenience functions like `az acs kubernetes install-helm` via https://github.com/Azure/azure-cli/pull/4113. That way you can get a version of helm that matches your tiller instance running on their infrastructure.

So far we have guaranteed that the version of tiller will match the client version you're running via `helm init --update`, though the reverse isn't true. That would require a few technical design decisions like:

 - we need to bundle the helm binary for every supported release in the tiller image
 - the command running from tiller would need to be cross-compatible across Windows/MacOS/Linux
 - we need a way to run this command from tiller without actually requiring the helm client for the first time.

How do you propose we solve these problems?

**Comment by bacongobbler** [comment]
I've updated the title to reflect the new proposal.
