### ISSUE TITLE
Question on sharing charts 

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [kubernetes/helm#2705]
I am trying to introduce Helm in our Kubernetes infrastructure: we have several application which all share the same basic structure. They are composed by:
- a `configmap`
- a `deployment` file
- a `service`
- an `ingress`

The `configmap` is a bit tricky to share, but the other files really differ only in the actual values, the structure is the same (in 95% of the application). As a lazy developer, I would like to have a generic chart define the general structure and then having the actual application just depending on this chart and setting the right values. This is pretty easily achieved with a `requirements.yaml` file.

Now, on top of that I would like to have an environment chart, which would depend on the single applications and would set environment-specific values. This is again can be done with `requirements.yaml`; the (weird) thing is that to override values in the application, the environment chart has to set something like `application.application.key: value`.

To clarify the structure and the situation I come up so far, I have created a repository mimicking my current solution: https://github.com/ThanksForAllTheFish/helm-sample

The question is: am I having the right approach and I just have to deal with the `application.application` thing? Or, am I completely off and the what I am trying to achieve is doable in a more straightforward way?

**Comment by thomastaylor312** [comment]
@ThanksForAllTheFish So there is a common chart out there that uses a templates that you can just drop in. Check it out [here](https://github.com/technosophos/common-chart)

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
