### ISSUE TITLE
expose kubernetes version

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#2706]
There have been a lot of times now that we've had to use different versions of yaml for different k8s versions. for example, init-containers. I've also seen some templates flat out not work with older k8s versions.

I'd like to see two features added to helm.

1. a minimum k8s version field in Charts. This will give the user warning/block the deployment of a chart that is known to be too new for a particular version of k8s.

2. expose to the gotl templates, the major, minor, micro version of k8s. Templates can then use this information to render the right object if it wants to support optional features or multiple versions of k8s.

**Comment by bacongobbler** [comment]
Just noting that `.Capabilities.KubeVersion` [exposes Kubernetes version info](https://github.com/kubernetes/apimachinery/blob/master/pkg/version/types.go#L19-L32) to templates, so point 2 has already been solved.

example: https://github.com/kubernetes/helm/blob/f9c9e9d6cb7f16d6708992af00891c43bc42856c/pkg/lint/rules/testdata/albatross/templates/svc.yaml#L11-L12

**Comment by jascott1** [comment]
It seems if the KubeVersion is already available to Helm then it would be a simple check to handle number 1 on the client.

**Comment by kfox1111** [comment]
@bacongobbler oh, cool. didn't know about that one. Thanks. :)

**Comment by jascott1** [comment]
So a field in chart.yaml that takes a semver compatible value?

**Comment by kfox1111** [comment]
yeah. and bails if k8s is older then it.

**Comment by jascott1** [comment]
Also we can go full on semver range so chart can be deprecated and still work for older clusters and safely refuse to work for newer clusters if they are known to be incompatible.

**Comment by kfox1111** [comment]
even better. :)

**Comment by bacongobbler** [comment]
we should close this in favour of #2708 as that better describes the proposal in this ticket. Thanks @jascott1 for summarizing!

**Comment by bacongobbler** [comment]
closing in favour of #2708.

**Comment by jglick** [comment]
> we should close this in favour of #2708 as that better describes the proposal in this ticket

No, #2708 only covers the first item, not



> 2\. expose to the gotl templates, the major, minor, micro version of k8s. Templates can then use this information to render the right object if it wants to support optional features or multiple versions of k8s.
