### ISSUE TITLE
proposal: Allow charts to specify k8s compatibility in semver field

### ISSUE THREAD

**Issue by jascott1** [kubernetes/helm#2708]
## Problem

Charts do not currently specify which versions of Kubernetes they are compatible with. Providing this mechanism could save time otherwise spent in troubleshooting incompatibilities.  

## Solution

Add an optional field `k8sVersion` to `Chart.yaml` that allows the chart developer to specify a semver compliant version. Check the chart's semver value against the k8s version at install and upgrade time and exit with an error when incompatibilities are detected. The value could be any valid semver version format including a range of versions.

```
apiVersion: v1
description: foo Helm chart for Kubernetes
name: foo
version: 0.4.2
k8sVersion: >=1.7.1  # example 
```
An error should be returned when attempting to install a chart that is incompatible with the k8s version.

## Opens

Will version checking handle enough cases or will some full on individual k8s api checking be required?

**Comment by mattfarina** [comment]
Note, this would be really useful at part of the `index.yaml` file got an appVersion. Then, we could craft something where helm could look at the version of k8s to deploy to and the available compatible release to install.
