### ISSUE TITLE
Helm should support reading the values file from STDIN

### ISSUE THREAD

**Issue by luxas** [kubernetes/helm#2709]
I'd very much like to do
```
sed "s|foo|bar|g" values-template.yaml | helm install -f - stable/foo
```

I guess that would be pretty straightforward to implement
Just like `kubectl apply -f`

Now, with v2.5, I got:
```
Error: open -: no such file or directory
```
when running such a command

**Comment by thomastaylor312** [comment]
I can see how this could be very helpful, especially in scripting.
