### ISSUE TITLE
RemoteReleaseModule panics

### ISSUE THREAD

**Issue by nebril** [kubernetes/helm#2713]
When run in experimental mode, tiller panics when the connection cannot be established to rudder grpc endpoint.

There is a problem with handling nils returned from "k8s.io/helm/pkg/rudder" in place of Response object pointer. These errors result in dereferencing nil pointer and panic.

Example culprit is here: https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_modules.go#L135

Nil handling in response objects needs to be added there.

**Comment by nebril** [comment]
Please asign this issue to me, I will provide a fix as this is blocking my other work.

**Comment by thomastaylor312** [comment]
Ok, will do. Thank you for finding this @nebril

**Comment by thomastaylor312** [comment]
Also, I'll add this into 2.6 for now. If you think it will need to be pushed out, please let me know
