### ISSUE TITLE
helm dependencies update --verify should fail when verification fails.

### ISSUE THREAD

**Issue by aknrdureegaesr** [kubernetes/helm#2717]
## Szenario:

* My Helm chart `highlevel` is using another Helm chart  `lowlevel-x.y.z` as a dependency.
* I'm under attack by a man in the middle. That person intends and is somehow able to insert a manipulated version of `lowlevel-x.y.z`.
* I'm prudently using `--verify`.
* For the purpose of this ticket, let's assume the man in the middle does not own a GPG key that I trust.

So this issue is about the behaviour of

```
helm dependencies update --verify highlevel
```

## Expected outcome:

The man in the middle is not able to convince this command to succeed and dump the manipulated chart on me, not by just manipulating the network traffic caused by my `helm` command.

## Actual outcome:

If the man in the middle succeeds in producing a `404 not found` HTTP error when `helm` asks for `lowlevel-x.y.z.tgz.prov`, then, surprisingly,  the `helm` command will succeed (with exit value 0).

So, in essence, it is possible for a man in the middle to remotely switch off `--verify`.

**Comment by technosophos** [comment]
I agree -- the expected outcome is that helm should fail with a verification error, not ignore the failed verification.
