### ISSUE TITLE
Is a version of the kubernetes a dependency?

### ISSUE THREAD

**Issue by djkutiger** [kubernetes/helm#2728]
Does Helm check for the kubernetes's version and/or set of features different versions of the kubernetes provide?

**Comment by thomastaylor312** [comment]
I think you might be looking for the `Capabilities` object that is exposed by default. Can you take a look at the [docs](https://docs.helm.sh/chart_template_guide/#built-in-objects) and see if that gets you what you are looking for?

**Comment by djkutiger** [comment]
I missed that. Exactly what I need. Thank you.
