### ISSUE TITLE
Intelligently resolve dependencies

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#273]
A question was brought up in #250 about intelligent dependency resolution.
For example, if a chart for a todolist app also requires a redis chart for the backend, then upon resolving dependencies, will we look for an existing redis resource to connect to? 
This issue is to keep track of the discussion of this question.

* Another thing note here is how to deal with shared resources. For example, are we going to allow the redis service my todolist app uses to be used by another app/chart?

**Comment by jackgr** [comment]
Extends #265.
