### ISSUE TITLE
Possible to set values from requirements.yaml to dependencies?

### ISSUE THREAD

**Issue by Disturbing** [kubernetes/helm#2741]
I'm wondering if I can set the configuration values via pointing to file or --set functionality in the requirements .yaml.

I could not find any documentation for it.

**Comment by jascott1** [comment]
@Disturbing You would probably need to have a values.yaml in the subchart and then override those values as necessary using `--set`

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
