### ISSUE TITLE
Fetch values.yaml

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#2744]
Values.yaml provides a good mechanism for users to customize the release. Unfortunately,
unless the user is git cloning the chart repo and digging out the values, or crawling for it online,there is no easy way to get to it. Once fetched, you also must comment all the values if you want to continue to use the defaults in the chart and get updated values when the chart is updated.

There should be a way to fetch a reference values.yaml to use along with your chart in a commented way. We need a cli command like:
helm reference values <chart name>

It should have a behavior such as:
1. If there is a reference-values.yaml file in the chart, it should return it verbatim.
2. If no reference-values.yaml, it should return the values.yaml file with every line commented out that isn't already commented. This allows the defaults in values.yaml inside the chart to not get overridden by the user explicitly until desired.

An example workflow is as follows (I do something like this but curling values.yaml out of github currently):
1. user makes a directory to store values for running releases named
~/helm/<namespace>
2. for each release of a chart, the user downloads the values for the release named after the release name:
helm reference values stable/prometheus > ~/helm/default/prometheus-values.yaml
3. user edits the values, updating a few values.
4. user launches the chart
helm install stable/prometheus --name prometheus --values ~/helm/default/prometheus-values.yaml

**Comment by kfox1111** [comment]
@jascott1 Wish list item.

**Comment by bonhamjp** [comment]
I can give this a shot, if nobody minds

**Comment by bacongobbler** [comment]
I think a more clear and concise document on the design choices/rational would be helpful before going ahead. It’d also be good to rally some feedback from the community as a first step to see if this is useful, or what other common idioms others are doing to work around this. I wouldn’t want you to spend time working on a feature only to be shot down because there are existing (or possibly better) ways to solve this problem.

**Comment by kfox1111** [comment]
@bacongobbler do you have anyone in mind to ask?

I requested the feature, as I've seen this specific use case several times at my site. So, thats at least one community member. :)

**Comment by kfox1111** [comment]
btw, anyone who wants to experience the issue should try the following workflow:

helm search <something>

pick a something.

try to figure out what configuration options are needed for the release:
helm install stable/<something>

**Comment by bacongobbler** [comment]
It's a rough idea at this point, but bear with me here...

I've noticed that we have introduced a LOT of (great) features to Helm recently. While I love the amount of work that's being put into the project and the current velocity, we don't have very coherent documentation for a lot of these new features, and that has led to a large influx of basic questions about new features that are missing significant documentation on the feature, the motivation behind it, possible conflicts with other features in Helm, etc. Occasionally these features are implemented then the author falls off the face of the internet. This has caused a few of us (meaning me) a lot of "actually I don't know what this feature does" answers to other community members, either in Slack, at conferences, etc.

Moving forward, I would like to see us improve upon writing better documentation when introducing new features to Helm. I'd like to propose that the contributor will need to write out a design document, gather feedback from the community on that document (e.g. #helm-users on slack, the weekly dev meetings, mailing list etc.) then go ahead and implement the feature once design has been fleshed out.

In my mind, the design document should contain (note: a lot of the verbiage here is shared with Python's [PEP 1](https://www.python.org/dev/peps/pep-0001/)):

1. Abstract: a short (~200 word) description of the technical issue being addressed.
1. Specification: The technical specification should describe the syntax and semantics of the feature. The specification should be detailed enough to give users (and maintainers) a reference to the full understanding of the feature.
1. Motivation: Clearly explains why the existing workflow is inadequate to address the problem that the proposal solves.
1. Rationale: The rationale fleshes out the specification by describing what motivated the design and why particular design decisions were made. It should describe alternate designs that were considered and related work, e.g. how the feature is supported in other tools related to Helm.
1. Backwards Compatibility -- If this feature introduces backwards incompatibilities, it must include a section describing these incompatibilities and their severity. The proposal must explain how the author proposes to deal with these incompatibilities.

I'm going to propose this tomorrow at the Helm dev meeting and probably give a talk on it at the Helm dev summit in January, but in general it makes sense to just start writing proposals or design documents when writing new features, anyways.

Does that make sense?

**Comment by kfox1111** [comment]
It does. and would come in handy to have those documents around for when a helm v3 gets implemented, so you don't drop important features by mistake.

**Comment by ablekh** [comment]
Unless I'm totally missing something, it seems that this functionality can be achieved (assuming that a user doesn't mind a preliminary Helm chart install step -- the intent is to install a chart anyway, just with custom values) simply by using standard command `helm get`:

```
Usage:
  helm get [flags] RELEASE_NAME
  helm get [command]

Available Commands:
  hooks       download all hooks for a named release
  manifest    download the manifest for a named release
  values      download the values file for a named release
```

**Comment by yanivpaz1973** [comment]
> Unless I'm totally missing something, it seems that this functionality can be achieved (assuming that a user doesn't mind a preliminary Helm chart install step -- the intent is to install a chart anyway, just with custom values) simply by using standard command `helm get`, more specifically: `helm get <release-name> values`.
> 
> ```
> Usage:
>   helm get [flags] RELEASE_NAME
>   helm get [command]
> 
> Available Commands:
>   hooks       download all hooks for a named release
>   manifest    download the manifest for a named release
>   values      download the values file for a named release
> ```

It will give only user provided values , not all the current values that used during the deployment

**Comment by kfox1111** [comment]
That is what your missing. Needing to install the chart first. Some charts don't go in smoothly if they are not configured. Knowing what to configure is not always easy in these cases. Getting the reference config, where all chart defined values comments are in tact is useful. Finding it currently is hard for users.

**Comment by bekriebel** [comment]
I'm not sure when this was introduced, but you can use `helm show values <chart-name>` to get the values of the chart in with helm v3.0.3.

**Comment by kfox1111** [comment]
helm show values <chart-name> seems to be about 95% of what I was looking for. Thanks!
