### ISSUE TITLE
When deleting, helm can say non-existent resources are kept

### ISSUE THREAD

**Issue by fetmar** [kubernetes/helm#2745]
```
These resources were kept due to the resource policy:
[Secret] my-secret-user
```

If an installation were aborted, or a problem occurred and my-secret-user was not actually created, this warning would be inaccurate.

**Comment by bacongobbler** [comment]
labelling this as a starter bug. This should be relatively simple to fix.

**Comment by fgimenez** [comment]
Dibs, i'd like to work on this one if anyone else is already with it
