### ISSUE TITLE
Importing an "external" container in a deployment

### ISSUE THREAD

**Issue by odino** [kubernetes/helm#2748]
Aloha there!

Say that I have a container re-used across multiple deployments, is there any way to package it as a chart dependency? As far as I know I will only be able to package k8s "resources" (eg. pod, ingress, configmap, etc), not a "random" container. The way I see it is that I should copy the container definition on all my charts, right? 

Think of an auth layer that runs on top of the pod's "actual" container

**Comment by kfox1111** [comment]
your not talking about the image itself, but the parameters/auth used for that container? repo info, image location, image name, etc?

**Comment by odino** [comment]
Yeah, think of an element in the list of containers inside a deployment. When I say auth I mean imagine you have an auth proxy that you run in front of your applications -- we run an auth layer in basically every deployment, and would like to be able to import that rather than duplicate in every helm chart.

**Comment by bacongobbler** [comment]
Yes, this is possible through [chart dependencies](https://docs.helm.sh/chart_template_guide/#subcharts-and-global-values). You can define a chart to be as simple as you like. An auth proxy would typically be fronting the application, which means that there's typically a service and a deployment involved at the very least. That would be a chart, which can then be a subchart for your other charts.

I'm going to close this as answered, but please re-open if this does not answer your question. Thanks!

**Comment by kfox1111** [comment]
@bacongobbler I think this does raise an interesting point. Several times I've fronted containers with sidecar proxies. like oauth2_proxy for auth, or haproxy for ssl termination or connection tracking...

So far, I've had to tweak the chart of everything I've needed to do this on.

It would be good if there was a generic mechanism in helm charts to allow end users to slide in with some kind of generic fronting mechanism in a sidecar they want. that way charts are decoupled a bit from the specifics of deployment.

**Comment by odino** [comment]
@bacongobbler actually the auth service runs as a container in every pod that's reachable via HTTP, so it doesn't have its own service etc. It's a container we run in each and every deployment (thus it doesnt have a chart on its own).

**Comment by kfox1111** [comment]
I'm more and more thinking it would be good to have a common library where stuff like this could land?

Maybe have a macro for a http frontend sidecar, and leave it blank by default. allowing the end user to override its contents with their chosen container/options?

**Comment by bacongobbler** [comment]
That type of chart exists in the chart incubator as https://github.com/kubernetes/charts/tree/master/incubator/common.
