### ISSUE TITLE
fail to start tiller container

### ISSUE THREAD

**Issue by rocky-nupt** [kubernetes/helm#2752]
When I install helm, the tiller container fails to start. The container's log is as follows:

`[root@master ~]# docker logs 7a53d79af78a
[main] 2017/08/02 09:21:51 Cannot initialize Kubernetes connection: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: getsockopt: connection refused`

Description of tiller pod:
`Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  2h		49s		32	kubelet, 127.0.0.1				Warning		MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  2h		49s		30	kubelet, 127.0.0.1	spec.containers{tiller}	Normal		Pulled		Container image "gcr.io/kubernetes-helm/tiller:v2.5.0" already present on machine
  1h		49s		22	kubelet, 127.0.0.1	spec.containers{tiller}	Normal		Created		(events with common reason combined)
  1h		48s		22	kubelet, 127.0.0.1	spec.containers{tiller}	Normal		Started		(events with common reason combined)
  2h		3s		610	kubelet, 127.0.0.1	spec.containers{tiller}	Warning		BackOff		Back-off restarting failed docker container
  2h		3s		579	kubelet, 127.0.0.1				Warning		FailedSyncError syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=tiller pod=tiller-deploy-542252878-8973b_kube-system(96f6a96c-7749-11e7-ab93-52540048dc63)"
`

However, in fact,  http://localhost:8080/api is reachable. Is localhost here not the host node ip because I have install flannel in my cluster?

**Comment by zjj2wry** [comment]
Concepts
Overview
What is Kubernetes?
Kubernetes Components
Working with Kubernetes Objects
Understanding Kubernetes Objects
Names
Namespaces
Labels and Selectors
Annotations
The Kubernetes API
Kubernetes Architecture
Nodes
Master-Node communication
Extending the Kubernetes API
Custom Resources
Extending the Kubernetes API with the aggregation layer
Containers
Images
Container Environment Variables
Container Lifecycle Hooks
Workloads
Pods
Pod Overview
Pods
Pod Lifecycle
Init Containers
Disruptions
Controllers
Replica Sets
Replication Controller
Deployments
StatefulSets
PetSets
Daemon Sets
Garbage Collection
Jobs - Run to Completion
Cron Jobs
Configuration
Configuration Best Practices
Managing Compute Resources for Containers
Assigning Pods to Nodes
Secrets
Services, Load Balancing, and Networking
Services
DNS Pods and Services
Connecting Applications with Services
Ingress Resources
Network Policies
Adding entries to Pod /etc/hosts with HostAliases
Storage
Volumes
Persistent Volumes
Dynamic Provisioning
Cluster Administration
Cluster Administration Overview
Managing Resources
Cluster Networking
Network Plugins
Logging Architecture
Configuring kubelet Garbage Collection
Federation
Using Sysctls in a Kubernetes Cluster
Proxies in Kubernetes
Controller manager metrics
Policies
Resource Quotas
Pod Security Policies
Edit This Page
DNS Pods and Services

Introduction

As of Kubernetes 1.3, DNS is a built-in service launched automatically using the addon manager cluster add-on.
Kubernetes DNS schedules a DNS Pod and Service on the cluster, and configures the kubelets to tell individual containers to use the DNS Service’s IP to resolve DNS names.
What things get DNS names?

Every Service defined in the cluster (including the DNS server itself) is assigned a DNS name. By default, a client Pod’s DNS search list will include the Pod’s own namespace and the cluster’s default domain. This is best illustrated by example:
Assume a Service named foo in the Kubernetes namespace bar. A Pod running in namespace bar can look up this service by simply doing a DNS query for foo. A Pod running in namespace quux can look up this service by doing a DNS query for foo.bar.
Supported DNS schema

The following sections detail the supported record types and layout that is supported. Any other layout or names or queries that happen to work are considered implementation details and are subject to change without warning.
Services
A records
“Normal” (not headless) Services are assigned a DNS A record for a name of the form my-svc.my-namespace.svc.cluster.local. This resolves to the cluster IP of the Service.
“Headless” (without a cluster IP) Services are also assigned a DNS A record for a name of the form my-svc.my-namespace.svc.cluster.local. Unlike normal Services, this resolves to the set of IPs of the pods selected by the Service. Clients are expected to consume the set or else use standard round-robin selection from the set.
SRV records
SRV Records are created for named ports that are part of normal or Headless Services. For each named port, the SRV record would have the form _my-port-name._my-port-protocol.my-svc.my-namespace.svc.cluster.local. For a regular service, this resolves to the port number and the CNAME: my-svc.my-namespace.svc.cluster.local. For a headless service, this resolves to multiple answers, one for each pod that is backing the service, and contains the port number and a CNAME of the pod of the form auto-generated-name.my-svc.my-namespace.svc.cluster.local.
Backwards compatibility
Previous versions of kube-dns made names of the form my-svc.my-namespace.cluster.local (the ‘svc’ level was added later). This is no longer supported.
Pods
A Records
When enabled, pods are assigned a DNS A record in the form of pod-ip-address.my-namespace.pod.cluster.local.
For example, a pod with IP 1.2.3.4 in the namespace default with a DNS name of cluster.local would have an entry: 1-2-3-4.default.pod.cluster.local.
A Records and hostname based on Pod’s hostname and subdomain fields
Currently when a pod is created, its hostname is the Pod’s metadata.name value.
With v1.2, users can specify a Pod annotation, pod.beta.kubernetes.io/hostname, to specify what the Pod’s hostname should be. The Pod annotation, if specified, takes precedence over the Pod’s name, to be the hostname of the pod. For example, given a Pod with annotation pod.beta.kubernetes.io/hostname: my-pod-name, the Pod will have its hostname set to “my-pod-name”.
With v1.3, the PodSpec has a hostname field, which can be used to specify the Pod’s hostname. This field value takes precedence over the pod.beta.kubernetes.io/hostname annotation value.
v1.2 introduces a beta feature where the user can specify a Pod annotation, pod.beta.kubernetes.io/subdomain, to specify the Pod’s subdomain. The final domain will be “ ...svc.". For example, a Pod with the hostname annotation set to "foo", and the subdomain annotation set to "bar", in namespace "my-namespace", will have the FQDN "foo.bar.my-namespace.svc.cluster.local"
With v1.3, the PodSpec has a subdomain field, which can be used to specify the Pod’s subdomain. This field value takes precedence over the pod.beta.kubernetes.io/subdomain annotation value.
Example:
apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: busybox
  clusterIP: None
  ports:
    - name: foo # Actually, no port is needed.
      port: 1234
      targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    name: busybox
spec:
  hostname: busybox-1
  subdomain: default-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    name: busybox
spec:
  hostname: busybox-2
  subdomain: default-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
If there exists a headless service in the same namespace as the pod and with the same name as the subdomain, the cluster’s KubeDNS Server also returns an A record for the Pod’s fully qualified hostname. Given a Pod with the hostname set to “busybox-1” and the subdomain set to “default-subdomain”, and a headless Service named “default-subdomain” in the same namespace, the pod will see it’s own FQDN as “busybox-1.default-subdomain.my-namespace.svc.cluster.local”. DNS serves an A record at that name, pointing to the Pod’s IP. Both pods “busybox1” and “busybox2” can have their distinct A records.
As of Kubernetes v1.2, the Endpoints object also has the annotation endpoints.beta.kubernetes.io/hostnames-map. Its value is the json representation of map[string(IP)][endpoints.HostRecord], for example: ‘{“10.245.1.6”:{HostName: “my-webserver”}}’. If the Endpoints are for a headless service, an A record is created with the format ...svc. For the example json, if endpoints are for a headless service named "bar", and one of the endpoints has IP "10.245.1.6", an A record is created with the name "my-webserver.bar.my-namespace.svc.cluster.local" and the A record lookup would return "10.245.1.6". This endpoints annotation generally does not need to be specified by end-users, but can used by the internal service controller to deliver the aforementioned feature.
With v1.3, The Endpoints object can specify the hostname for any endpoint, along with its IP. The hostname field takes precedence over the hostname value that might have been specified via the endpoints.beta.kubernetes.io/hostnames-map annotation.
With v1.3, the following annotations are deprecated: pod.beta.kubernetes.io/hostname, pod.beta.kubernetes.io/subdomain, endpoints.beta.kubernetes.io/hostnames-map
How do I test if it is working?

Create a simple Pod to use as a test environment
Create a file named busybox.yaml with the following contents:
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
Then create a pod using this file:
kubectl create -f busybox.yaml
Wait for this pod to go into the running state
You can get its status with: kubectl get pods busybox
You should see:
NAME      READY     STATUS    RESTARTS   AGE
busybox   1/1       Running   0          <some-time>
Validate that DNS is working
Once that pod is running, you can exec nslookup in that environment:
kubectl exec -ti busybox -- nslookup kubernetes.default
You should see something like:
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes.default
Address 1: 10.0.0.1
If you see that, DNS is working correctly.
Troubleshooting Tips
If the nslookup command fails, check the following:
Check the local DNS configuration first
Take a look inside the resolv.conf file. (See “Inheriting DNS from the node” and “Known issues” below for more information)
kubectl exec busybox cat /etc/resolv.conf
Verify that the search path and name server are set up like the following (note that search path may vary for different cloud providers):
search default.svc.cluster.local svc.cluster.local cluster.local google.internal c.gce_project_id.internal
nameserver 10.0.0.10
options ndots:5
DNS Policy
By default, DNS policy for a pod is ‘ClusterFirst’. So pods running with hostNetwork cannot resolve DNS names. To have DNS options set along with hostNetwork, you should specify DNS policy explicitly to ‘ClusterFirstWithHostNet’. Update the busybox.yaml as following:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
```

**Comment by rocky-nupt** [comment]
Yeh, thank you for your remind.
