### ISSUE TITLE
Question: I cannot depend on a chart which a dependency also depends on

### ISSUE THREAD

**Issue by djhaskin987** [kubernetes/helm#2762]
I cannot depend on a chart safely which itself is a dependency of another chart that I depend on.

Steps to reproduce are encapsulated in the following bash script:

```
mkdir experiment
cd experiment
helm create a
helm create b
helm create c
mv c c-0.2.0
cat > c-0.2.0/Chart.yaml << CHART
apiVersion: v1
description: A Helm chart for Kubernetes
name: c
version: 0.2.0
CHART
helm create c
mv c c-0.1.0
cd b
cp -af ../c-0.1.0 charts
cd ../a
cp -af ../b charts
cp -af ../c-0.2.0 charts
helm install --debug .
```

This script yields the following result:

```
Error: release prodding-gecko failed: services "prodding-gecko-c" already exists
```

The above script illustrates the problem. Chart "C" comes in two versions: 0.1.0 and 0.2.0 . Chart "B" relies on chart "C" at version 0.1.0. Char "A" relies on chart "B" and also relies on chart "C" at version 0.2.0 .
When I try to install chart "A", it tries to install chart "C" twice, and the second installation fails, thus failing the deploy.

I understand that this problem can be gotten around by changing the "C" chart so that the version of the chart is also used in the k8s service name, but this requires potentially changing an upstream dependency. Further, this behavior is not the default, since `helm create` by default just uses the name of the chart to create the service name within the deployment.

This is the classic [broken diamond dependency problem](https://research.swtch.com/version-sat).

Understanding that this problem may not be solvable for helm, do you have any recommendations for how to deal with this?

**Comment by bacongobbler** [comment]
If chart B relies on chart C, and chart A relies on chart B and C, then why not let chart A rely on chart B? Is there a technical limitation to why chart B must use v0.1.0 and chart A must use v0.2.0?

**Comment by djhaskin987** [comment]
This simple example illustrates a problem with deeper dependencies. This same problem can happen when the dependency graph gets deeper and larger. Example: A depends on B, which depends on C, which depends on D; and A also depends on E, which has listed C as a dependency on a different version than what B listed. This occurred because E and B were created by two entirely different development teams which have no contact with each other. This happens all the time in the open source world, for example. 

So, If it's possible for me to change E (often it's not), I *could* change E and B to both rely on the same version of C, but that wouldn't change the fact that helm would try to install the service for C twice, as part of the same deploy, and break. But in all likelihood, I will not be able to change E or B; those are upstream dependencies created by a different developer team or even company in the open source world.

It's entirely conceivable to assume that two services (Say E and B) rely on the same service (say C) to be present, but only one such service needs to be present. So, both E and B must list C as a dependency, in case they are deployed by themselves (e.g. `helm install E`). They probably also each pass C different values overrides in their values.yaml file. In short, both E and B in this example each assume that there is a service built from the C chart set up for their sole consumption.

It may be that the solution is just to make sure that two C services can be spun up when `helm install` is called; one for B and one for E. I don't know how to do that, but if some change can be made in helm to allow this, I'd be most grateful.

**Comment by djhaskin987** [comment]
Re-opening, I didn't mean to close :(

**Comment by djhaskin987** [comment]
Perhaps this can be accomplished by  changing `{{template "fullname" }}` -- by adding the name of any parent charts to it. Thus, for a release called `prodding-gecko`, `{{template "fullname"}} would yield `"prodding-gecko-a-b-c"` inside the A -> B -> C chart, and would yield `"prodding-gecko-a-c"` inside the A -> C chart.

To improve the solution's backwards compatibility, we might just create a *new* template function called something like `{{template "chartqualifier" }}` and make this the default instead of `{{template "fullname" }}` when `helm create` is called. 

Thoughts?

**Comment by djhaskin987** [comment]
Or so:
```
{{ $chartqualifier :=  printf "%v-%v" .Release.Name (.Template.BasePath | replace "/templates" "" | replace "/charts/" "-" | replace "/" "-" )}}
```
That would yield something like this:
```
wooly-mastiff-b-c
```
For the C chart.

**Comment by jamorales-bsft** [comment]
I have a similar issue. A, B are standalone services with share a dependency. For me A relies on B and C and B relies on C. If I make it so C is installed by only A and remove the C dependency from B it resolves the issue. But then if I want to install B by itself without A it will not work. How can I get around this and be able to install both B with C only and A with B and C If I want?

**Comment by djhaskin987** [comment]
Here's how we got around it at my work:

1. We use [degasolv](degasolv.readthedocs.io) to do the dependency resolution instead of helm itself.
1. When we package charts, we don't put the required charts under the charts/ directory before we package it. Charts are packaged as *.tgz files *without* their dependencies inside the tarball.
1. We earmark special charts, called *atlases*, which **are** packaged with their dependencies. These special charts are then deployed.

It's like java's maven. When jar files are not used for deployment, they just package up only the code in the given library. When the jar file represents a microservice, however, it is packaged as an *uberjar*, which includes the code and all its dependencies.

I applied the same principle. Mostly, the charts we build don't have their dependencies put into them. However, when I am ready to make a deploy, I make an uberchart, or an *atlas*. Degasolv resolves all of the atlas's requirements recursively, putting them flatly in the atlas's "charts/" directory.

For example, if chart A requires chart B and C, and chart B requires chart C, I package all of them without their dependencies. Each chart has a degasolv.edn file describing their dependencies. For example, B's config file might look like this:

```
{
 :id "B"
 :version "0.1.0"
 :requirements ["C>=1.0"]
 :location "http://example.com/repo/b-0.1.0.tgz"
}
``

So that degasolv can track the dependencies between the charts.

Now say I want to deploy "A". I create an atlas (collection of charts) out of it by using `degasolv resolve-locations` to get the list of requirements, then I download them and put them in the charts/ directory of "A" myself. I package A with its dependencies, and it's dependencies' dependencies, etc.

The final layout of the chart "A" looks like this:

"A/charts/B"
"A/charts/C"
"A/templates/"

That is, A's dependencies and B's dependencies are installed into the charts/ directory flat. C is not installed relative to B.

This fixes *everything*.

When the C chart is applied, any services it contains are likely named "<release>-c", and it serves both A and B.

Probably not very clear, but we solved it where I'm at. I'm on the kubernetes slack under "djhaskin987" if you want to chat about it later @jamorales-bsft .

**Comment by jamorales-bsft** [comment]
@djhaskin987 Thanks for the explanation. A few questions. I get how the final structure fixes everything, basically instead of A installing C and then B trying to install a second version of C, which is what breaks everything, only one version of C is installed in the final "atlas". I have a few questions on how you get there though that are not 100% clear from your explanation.

1. You package A,B, and C charts with empty chart/ folders. Do you also omit the `requirements.yaml` file and basically replace it with the `degasolv.edn` file?

2. Now assuming the `degasolv.edn` is a direct replacement for the `requirements.yaml` file that means A chart's `degasolv.edn` would contain B/C package references and B chart's `degasolv.edn` would contain C package reference? 

Basically `degasolv resolve-locations` has the ability to realize that A/B share a same reference and it's output will only list it once for download.  Since for me B can be installed standalone I want it to be able to install C as its own dependency.

3. Assuming everything I said is correct then does that mean this only works for charts I make/control? For instance say C was a third-party chart that had x number of additional requirements.yaml dependencies. Since `degasolv resolve-locations` does not understand requirements.yaml it would not manage those and any conflicts amongst them would not be solved? Would I have to make some script to unpackage each .tgz convert it's `requirements.yaml` to a `degasolv.edn` then run `degasolv resolve-locations`?

Hopefully I am on the right track and this make sense.

**Comment by djhaskin987** [comment]
You're on the right track.

1. Yes, I replaced requirements.yaml with degasolv.edn in my implementation.

2. Yes, B's degasolv.edn has a reference to C and A's degasolv.edn has a reference to B and C. 

3. Currently, yes, it would only work for your company. However there may be something I can do to help you here.


I am the maintainer of the degasolv project. I could have "taught" degasolv to read requirements.yaml for projects but opted not to because it violates the semantics if that file. Maybe people write requirements.yaml files *expecting* for there to be two C packages installed. 


Instead, I could start a degasolv repository on bintray with third party dependencies pre loaded for the atlas model. If you are interested in this you should email me at the [degasolv-users Google group](https://groups.google.com/forum/m/?source=mog&gl=us#!forum/degasolv-users).

1. Yes, I replaced requirements.yaml with degasolv.edn in my implementation.

2. Yes, B's degasolv.edn has a reference to C and A's degasolv.edn has a reference to B and C. 

3. Currently, yes, it would only work for your company. However there may be something I can do to help you here.


I am the maintainer of the degasolv project. I could have "taught" degasolv to read requirements.yaml for projects but opted not to because it violates the semantics if that file. Maybe people write requirements.yaml files *expecting* for there to be two C packages installed. 


Instead, I could start a degasolv repository on bintray with third party dependencies pre loaded for the atlas model. If you are interested in this you should email me at the [degasolv-users Google group](https://groups.google.com/forum/m/?source=mog&gl=us#!forum/degasolv-users).

**Comment by jamorales-bsft** [comment]
@djhaskin987 I posted in the group. Was thinking to possibly make this a plugin. But I think I get how your solution works and it would definately solve my problem, bummer this is not native way helm handle dependencies though. Might be worth it to make a plugin

**Comment by djhaskin987** [comment]
This does show that flat dependency management is very compelling, @bacongobbler . Is there any way we can build a plugin into helm so that we don't have to work around it using some other tool?

**Comment by djhaskin987** [comment]
I also think one way we might solve this is alter helm so that it simply uses the first "C" that it sees. This is how maven works, and it works pretty well. That way there would only be one "C" deployed.

**Comment by karthik-ir** [comment]
I too have almost similar requirement 
I have 4 charts A,B,C,D
C Depends on A,B
D depends on A,B

Now if i run `helm upgrade --install {{NAME}} ./C` it works I get ABC working 
now the same when I run a next jenkins job for D I’ll be running the same command `helm upgrade --install {{NAME}} ./D` but then this removes C and has ABD installed. 

I want all of these under a single name, Because A and B have services and C/D will talk to then using {Release-name}-A/B .

I am also looking for a solution where a subchart can be updated individually without affecting the other deployment pieces.

**Comment by iamrandys** [comment]
👍 

It looks like I too will have to start using degasolv.  I have charts that all depend on some of the same charts and I only need the dependency to be included once.  Tags and conditions for requirements.yaml files really don't solve this.

**Comment by benkeil** [comment]
I have the same problem and described it a little bit better in [#3163](https://github.com/kubernetes/helm/issues/3163). We don't want to use a further tool...
