### ISSUE TITLE
Namespace discrepancy between `helm install` and `helm upgrade --install`

### ISSUE THREAD

**Issue by RemingtonReackhof** [kubernetes/helm#2764]
@tdickman and I  experiencing unexpected behavior when running `helm install` versus `helm upgrade --install`. 
If I run these while in my `rreackhof` namespace, these are the results:
```console
$ helm install stable/mysql
$ helm ls
NAME                                    REVISION        UPDATED                         STATUS          CHART           NAMESPACE
turbulent-koala                         1               Fri Aug  4 15:22:55 2017        DEPLOYED        mysql-0.2.6     rreackhof
```
```console
$ helm upgrade release-name --install stable/mysql
$ helm ls 
NAME                                    REVISION        UPDATED                         STATUS          CHART           NAMESPACE
release-name                            1               Fri Aug  4 15:26:18 2017        DEPLOYED        mysql-0.2.6     default
```
Passing `--kube-context` also does not change the results. I believe that `install` and `upgrade --install` should behave the same way.

**Comment by eric4545** [comment]
Hi, i found  upgradeCmd default namespace is `default`, which cause call installCmd will not getting Namespace from KubeContext.
https://github.com/kubernetes/helm/blob/master/cmd/helm/upgrade.go#L124

**Comment by maheshmahadevan** [comment]
+1 . facing same issue as mentioned in 2814

**Comment by hmagph** [comment]
Facing this too.

**Comment by bacongobbler** [comment]
2.6.1 is already released. https://github.com/kubernetes/helm/releases/tag/v2.6.1
