### ISSUE TITLE
helm init --upgrade will downgrade

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/helm#2774]
It seems that `helm init --upgrade` shouldn't downgrade a tiller version unless there's a `--force` option or `--downgrade` is specified.

**Comment by nebril** [comment]
@blakebarnett thanks for the issue, can you specify what went wrong?

If I understand you correctly, you had a helm version older than tiller version and `--upgrade` rolled tiller back to old version?

**Comment by bacongobbler** [comment]
If this is the case, it might be cool to do a version check between helm and tiller. If a tiller pod exists and the helm version is <= tiller's version, we could either exit non-zero with an informative error message unless `--force` is supplied.

**Comment by blakebarnett** [comment]
@nebril correct

@bacongobbler yeah seems reasonable
