### ISSUE TITLE
Helm fail with "template not defined" error with files from Bitbucket

### ISSUE THREAD

**Issue by danallraj** [kubernetes/helm#2775]
Hi, 

I am executing a git clone command to download the charts files from bitbucket repository unto an ec2 instance. When I run the helm lint command, i get the following error:

==> Linting .
[ERROR] templates/: render error in "vindicia-listener-dev/templates/deployment.yaml": template: vindicia-listener-dev/templates/deployment.yaml:4:20: executing "vindicia-listener-dev/templates/deployment.yaml" at <{{template "fullname...>: template "fullname" not defined

Error: 1 chart(s) linted, 1 chart(s) failed

I am not sure what could be causing this. If I create a new helm template e.g. 'helm create foo' and copy all the yaml files across from the local repository file to the new 'foo' directory, helm lint and install dry-run is successful. 

I've made sure permissions are the same, did a diff on the files but still not working. Appreciate any help on this. Thanks in advance.

**Comment by danallraj** [comment]
okay, so finally got a working helm lint. 

the original yaml files were created by using copy and paste text into bitbucket rather than commit and push. 

I have since modified the file on my local machine and then pushed to bitbucket. The git clone down to the helm client was successful and so was the helm lint command. 

i am not able to test with helm install due to authentication issues

Error: the server has asked for the client to provide credentials (get pods)

so will report back with the how i go with the helm install once the auth issue is resolved.

**Comment by bacongobbler** [comment]
ping @danallraj, were you able to get this working?

**Comment by danallraj** [comment]
Yes, it was my bad in the end... I deleted the NOTES and helper files which the yaml file was referring to. It worked when I copied to a new template directory because those two files were I  there.
