### ISSUE TITLE
Allow multiple yaml files to be included in a single values.yaml

### ISSUE THREAD

**Issue by a1dutch** [kubernetes/helm#2776]
We have quite a big values.yaml file that brings up an entire environment it would be nice if you could include other files into a single values.yaml file.  

e.g.
*#* values.yaml
-include: system.yaml
-include: othersystem.yaml

*#* system.yaml
....

*#* othersystem.yaml
....

This is the same way as Ansible allows files to be imported.

**Comment by nebril** [comment]
@a1dutch afaik you can already specify multiple `-f` options while installing a chart.

Or do you want for `value.yaml` file to be able to import other yaml files? This may be somewhat problematic as yaml format doesn't specify a way to import other files. It is implementable, but are you sure that current composable command or a script combining your yamls before installing wouldn't be a better way to handle that?

**Comment by a1dutch** [comment]
just the value.yaml file to be able to import other yaml files.  i don't want to have to have to add multiple `-f` files.

My current usage is: `helm update --install environments/dev`, i have a single yaml file with all my config, just need a way to split the file up.

**Comment by bacongobbler** [comment]
One way this could be solved is through a helm plugin that would merge multiple values.yaml files into one for submission to `helm install`. For example:

```
$ helm install -f "$(helm merge-templates environments/dev/*.yaml)"
```

Where `helm merge-templates` would generate a file in /tmp and print the filename to stdout.

**Comment by a1dutch** [comment]
I may try to have a go at a plugin when i get some free time, would it be possible to support the `-include: file.yaml` syntax in a plugin?

For the time being i managed to get it working with `helm install $(for x in environments/dev/values/*.yaml; do echo -n " -f $x"; done;)`

**Comment by jascott1** [comment]
@a1dutch Plugins will not allow you to augment an existing command like `helm install --mything`

**Comment by francescobianco** [comment]
I suggest you @a1dutch @nebril @bacongobbler to use a command-line parse to build a compose YAML file using a specific '$include' tag, consider to have your values.yml generated from values.template.yml using thi tool https://github.com/javanile/yamlinc

**Comment by balboah** [comment]
I'm also leaning towards having some additional merge values functionality built into Helm. Currently thinking about how to structure different releases (k8s clusters) on different cloud providers where the different providers have common defaults. I could do `helm -f cloudA.yaml -f clusterspecific.yaml -f otheroverrides.yaml` but maybe it would be convenient to have `helm -f clusterspecific.yaml` and be able to set something like the suggested `- includes: foo` or `- extends: cloudA.yaml`.

Another possibly convenient feature is to support passing a directory or glob to the `-f` option

**Comment by gopinatht** [comment]
I too would like to see this feature implemented. Because our helm charts are large, we tend to manage variability in a single location, typically the values file. This tends to make the values.yaml file very large and unwieldy. If we could split the files into multiple parts that would make it more manageable. 

I like the idea of the values directory proposed by @balboah and extend that to propose a "default" values directory similar to the default values file. 

The ultimate goal is to be able to organize the values into multiple files while still being able to do a simple `helm install my-chart` and not have to mess around with a variable list of `-f` parameters.

**Comment by jstrachan** [comment]
I just submitted an issue for supporting a directory on `--values` https://github.com/kubernetes/helm/issues/3786 which is something `kubectl` did too; it started taking yaml files but then allowed directories of yaml files. Maybe that would help fix this issue too.

For the multiple clouds use case you could specify multiple `--values` arguments for different directories or yaml files?

**Comment by schollii** [comment]
> I may try to have a go at a plugin when i get some free time, would it be possible to support the `-include: file.yaml` syntax in a plugin?
> 
> For the time being i managed to get it working with
> 
> ```
> helm install $(for x in environments/dev/values/*.yaml; do echo -n " -f $x"; done;)
> ```

I believe this will only work if there is no overlap between the root elements of the various yaml files. Using -f list of files does not have this limitation.
