### ISSUE TITLE
Documentation for "include" is misleading

### ISSUE THREAD

**Issue by atombender** [kubernetes/helm#2779]
The documentation [here](https://docs.helm.sh/developing_charts/) heavily implies that `include` takes a _file name_. It has two examples using a file name:

```
value: {{include "mytpl.tpl" . | lower | quote}}
```

and

```
checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
```

(This last example is nonsensical, since it demonstrates the reading of a file. It should be using `.Files.Get`, presumably.)

However, `include` takes the _name_ of a template that has been made with `define`.

This problem is exacerbated by the fact that there's no function reference anywhere. I had to go look in the [code](https://github.com/kubernetes/helm/blob/dece57e0baa94abdba22c0e3ced0b6ea64a83afd/pkg/engine/engine.go#L139) to find it.

**Comment by thomastaylor312** [comment]
Closed in #3076
