### ISSUE TITLE
Environment variables interpreted as true and false

### ISSUE THREAD

**Issue by ismail261** [kubernetes/helm#2782]
Hello,

I would like to know what all values are being interpreted as boolean when passing them in environment variables? 
When i pass yes/no that is true/false
When i pass on/off that is true/false (can anyone confirm that behaviour?)

What are the other such values?
Is there a way to use them as original values?

Thanks,
Ismail

**Comment by bacongobbler** [comment]
I've found that with environment variables, it's best to ensure that they're piped to `quote`. That way they will not be converted to boolean values. This is a Kubernetes Thing ™️.

More info is in the best practices guide: https://docs.helm.sh/chart_best_practices/#make-types-clear

**Comment by ismail261** [comment]
I am using values.yaml to replace the values in deployment.yaml.

values.yaml has a property

debugMessages: yes

And deployment.yaml has

env:
          - name: debugMessage
            value: "{{ .Values.e1.deploy.startup.debugMessage }}"

Is this not counted as values piped to quote? 
Should it be vice versa? Like Values.yaml has "yes" and deployment.yaml has value: {{ .Values.e1.deploy.startup.debugMessage }}

**Comment by bacongobbler** [comment]
This does not count as a value piped to `quote`. In your deployment.yaml, change it to the following:

```
env:
- name: debugMessage
value: "{{ .Values.e1.deploy.startup.debugMessage | quote }}"
```

It's better to encase the string to ensure the YAML parser interprets the value as a string rather than a boolean, which is what the link I pointed out is attempting to describe.

**Comment by ismail261** [comment]
I wanted to use property true directly in values. But it is not getting set.
When i set my values as debugMessage: true
and env variables as 
env:
- name: debugMessage
  value: {{ quote .Values.e1.deploy.startup.debugMessage }}
it just took the previous chart values which was being used. 
If i change it to some other random values then it is able to understand that change and update it.

**Comment by ismail261** [comment]
@bacongobbler Thank you that worked :)

But i am kind of confused here. 
1) Without quotes why yes/no and on/off values get converts to boolean?
2) Are there any such other values which gets interpreted as boolean? If yes then is there any documentation for that?

**Comment by bacongobbler** [comment]
> Without quotes why yes/no and on/off values get converts to boolean?

Because the YAML parser parses unquoted yes/no and on/off as booleans. Same as true/false.

> Are there any such other values which gets interpreted as boolean? If yes then is there any documentation for that?

You'll have to read the Kubernetes documentation, specifically the [resource reference for a Deployment](https://kubernetes.io/docs/resources-reference/v1.5/#deployment-v1beta1) to get a better idea on the manifest specification.

I'm going to close this issue as resolved, but please feel free to re-open. Thanks!

**Comment by rost5000** [comment]
> 
> 
> > Without quotes why yes/no and on/off values get converts to boolean?
> 
> Because the YAML parser parses unquoted yes/no and on/off as booleans. Same as true/false.
> 
> > Are there any such other values which gets interpreted as boolean? If yes then is there any documentation for that?
> 
> You'll have to read the Kubernetes documentation, specifically the [resource reference for a Deployment](https://kubernetes.io/docs/resources-reference/v1.5/#deployment-v1beta1) to get a better idea on the manifest specification.
> 
> I'm going to close this issue as resolved, but please feel free to re-open. Thanks!

@bacongobbler , could you refresh the referral link?
