### ISSUE TITLE
Tiller deployment with deterministic pod name

### ISSUE THREAD

**Issue by cehoffman** [kubernetes/helm#2783]
Since the user using helm needs the privilege to port-forward with the tiller pod in the kube-system namespace, it would be nice from an RBAC specification to only allow a user that privilege on the tiller pod and no other in the kube-system namespace.

Because tiller is deployed using a deployment, the name is not deterministic and so I can not write a RoleBinding for the namespace which restricts the pods/portforward resource create verb. If tiller was deployed using a statefulset, this limitation would go away. For reference my typical deployment flow uses a namespace per service and the helm deploy user has full access to that namespace using the built in admin ClusterRole. This lets me set quotas on the namespace that the helm user can not modify. However I have to give the helm user fully portfoward creation ability in the kube-system namespace in addition to pod listing capabilities. With the statefulset, pod listing permission would not be needed either.

**Comment by nebril** [comment]
As far as I understand, `helm init` is just a quick start command, that lets you hack away. You can easily change tiller deployment to suit your needs manually (even changing to StatefulSet), or if you want to consistently create tiller as StatefulSet - it may be a job for helm plugin, which would init tiller as StatefulSet.

**Comment by cehoffman** [comment]
Offering this as perhaps a good default as well. Since this doesn't change how the normal workflow from the CLI works and offers better RBAC restrictions on the tiller pod, it seems an improvement on install.

It was also pointed out to me that I could install tiller in a specific namespace which help get around giving a user extra permissions outside of their namespace and offer a workaround for user permission delegation to tiller until #1918 comes through.

**Comment by nebril** [comment]
Yes, you can install tiller in your namespace by using `helm init --tiller-namespace nsname`.

@adamreese what do you think about changing default tiller deployment to StatefulSet?

**Comment by seh** [comment]
Right now, Tiller winds up with a generated pod name because _helm init_ creates a _Deployment_. In my environment, we want neither the _Service_, nor the _Deployment_, nor the _ReplicaSet_; we just want the pod, and the pod having a stable name would indeed make it possible to write a more narrow RBAC _Role_ for the "pods/portforward" resource's name.

I suppose that having a _Deployment_ makes upgrading Tiller easier, but the extra objects make it harder to lock down the permissions. Our primary concern is ensuring that only a small set of people can find or get _helm_ (or any other gRPC client) to talk to Tiller.

**Comment by bacongobbler** [comment]
this sounds more like a doc request, which should be closed out with #2962. Am I correct with that assumption?

I don't think we're going to change `helm init` from deploying anything other than a deployment and a service any time soon... Unless the infrastructure significantly changes in helm 3.

**Comment by seh** [comment]
For now, my Helm chart that installs Tiller honors an option to elide the _Deployment_ and just deploy a pod directly with a predictable name. As I said, it trades reliability for security. Should the node hosting Tiller's pod fail, there's no supervising object to schedule a replacement elsewhere.
