### ISSUE TITLE
User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system"

### ISSUE THREAD

**Issue by rcorre** [kubernetes/helm#2787]
When invoking 

	releases, err := svc.getClient().ListReleases(
		k8shelm.ReleaseListLimit(req.PageSize),
		k8shelm.ReleaseListOffset(req.Offset),
		k8shelm.ReleaseListNamespace(req.Namespace),
	)

We see errors from tiller like the following about 50% of the time:

```
storage] 2017/08/09 17:33:05 listing all releases with filter
[storage/driver] 2017/08/09 17:33:05 list: failed to list: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system". (get configmaps)
```

These also occur with `Install` and `Upgrade`. We just upgraded our cluster to 1.7 and didn't notice this in 1.6.

We are on 7cf31e8d9a026287041bae077b09165be247ae66 (`v2.5.1`) of the helm client and server server.

**Comment by bacongobbler** [comment]
does tiller have access to read configmaps in kube-system?

**Comment by rcorre** [comment]
You know what, we realized that we accidentally had two tiller deployments and I forgot to check if deleting the rogue instance fixed this. I'll check back in on Monday.
- Ryan

On August 11, 2017 5:51:26 PM EDT, Matthew Fisher <notifications@github.com> wrote:
Does tiller have access to read configmaps in kube-system?

**Comment by rcorre** [comment]
Turns out this was due to our messed-up configuration. Sorry about that!
