### ISSUE TITLE
support GCP signed URL

### ISSUE THREAD

**Issue by rimusz** [kubernetes/helm#2789]
https://cloud.google.com/storage/docs/access-control/create-signed-urls-gsutil
providing generated signer URL gives the error:
`is not a valid chart repository or cannot be reached: error unmarshaling JSON: json: cannot unmarshal string into Go value of type repo.IndexFile` 
as it looks like does not like special characters in the URL. 
I was working on private helm repo access plugin for GCS/S3 got struck by this error.

**Comment by technosophos** [comment]
Can you generate a demo URL that I can test?

**Comment by rimusz** [comment]
sure, dropped it you privately to slack
