### ISSUE TITLE
cannot connect to tiller in minikube local

### ISSUE THREAD

**Issue by harshil562** [kubernetes/helm#2795]
I installed helm in my local system. There was a minikube cluster running in my local with kubectl pointing to it. After running helm init, it is installed properly and I can see the helm pod and a service created. The pod logs are as follows - 
`
2017-08-11T11:46:28.812993896Z [main] 2017/08/11 11:46:28 Starting Tiller v2.5.1 (tls=false)
2017-08-11T11:46:28.813095316Z [main] 2017/08/11 11:46:28 GRPC listening on :44134
2017-08-11T11:46:28.813102347Z [main] 2017/08/11 11:46:28 Probes listening on :44135
2017-08-11T11:46:28.813104894Z [main] 2017/08/11 11:46:28 Storage driver is ConfigMap
`

helm version command fails to run and running `helm version --debug` gives me -

> [debug] Created tunnel using local port: '46572'
>
>[debug] SERVER: "localhost:46572"
>
>Client: &version.Version{SemVer:"v2.5.1", >GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
>[debug] context deadline exceeded
>Error: cannot connect to Tiller

**Comment by bacongobbler** [comment]
What version of minikube are you running, and how was the cluster set up? I am unable to reproduce this locally on v2.5.1.

```
><> minikube version
minikube version: v0.20.0
><> minikube ip
192.168.99.100
><> helm version --debug
[debug] Created tunnel using local port: '63527'

[debug] SERVER: "localhost:63527"

Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```

**Comment by harshil562** [comment]
minikube version: v0.20.0

kubectl version :
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"dirty", BuildDate:"2017-06-22T04:31:09Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by ChristianWeyer** [comment]
I am having the exact same problem.
Is there already any solution?

Thanks!

**Comment by bacongobbler** [comment]
Hi @ChristianWeyer. Can you please explain your issue in more detail?

- How did you install minikube?
- What option flags were sent with `minikube start`?
- What version of minikube/helm?
- What is the output of `cat ~/.minikube/config/config.json`?

**Comment by bacongobbler** [comment]
You can also try to run the following to help diagnose the issue:

```
><> kubectl -n kube-system get pods
NAME                             READY     STATUS    RESTARTS   AGE
default-http-backend-9hd1v       1/1       Running   4          4d
draftd-821994266-2n273           2/2       Running   2          19h
kube-addon-manager-minikube      1/1       Running   4          4d
kube-dns-910330662-bm86z         3/3       Running   12         4d
kubernetes-dashboard-95vsz       1/1       Running   4          4d
nginx-ingress-controller-n8x1l   1/1       Running   4          4d
registry-cw2n7                   1/1       Running   4          4d
tiller-deploy-1651615695-kwk2n   1/1       Running   3          3d
><> kubectl -n kube-system port-forward tiller-deploy-1651615695-kwk2n :44134
Forwarding from 127.0.0.1:52671 -> 44134
Forwarding from [::1]:52671 -> 44134
```

And in another terminal:

```
><> HELM_HOST=127.0.0.1:52671 helm list
```

**Comment by ChristianWeyer** [comment]
Seems like I had one or more outdated components - most likely Helm.
Thanks for your help! It now works :-)

**Comment by pranayhasan** [comment]
`helm init --upgrade` show resolve this.

**Comment by grebois** [comment]
@pranayhasan @bacongobbler this is still not working;

```
$ helm init --upgrade
$HELM_HOME has been configured at /Users/mgreboi/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!

$ helm ls
Error: context deadline exceeded
```

**Comment by grebois** [comment]
@bacongobbler could you please re-open this issue:

```
$ helm version --debug
[debug] Created tunnel using local port: '55762'

[debug] SERVER: "localhost:55762"

Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
```

**Comment by grebois** [comment]
@bacongobbler could you re-open this, its not yet working with the latest version;
```
$ helm version --debug
[debug] Created tunnel using local port: '55762'

[debug] SERVER: "localhost:55762"

Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller
```

and there are many related reports of this issue:

https://github.com/kubernetes/helm/issues/2921
https://github.com/kubernetes/helm/issues/2827
https://github.com/kubernetes/helm/issues/2409

**Comment by bacongobbler** [comment]
Can you please provide more information about your deployment? I can’t determine if this is the right ticket to track your issue.

**Comment by grebois** [comment]
```
$ minikube version
minikube version: v0.22.3

$ helm version --debug
[debug] Created tunnel using local port: '57315'

[debug] SERVER: "localhost:57315"

Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
[debug] context deadline exceeded
Error: cannot connect to Tiller

$ helm ls
Error: context deadline exceeded
```

**Comment by bacongobbler** [comment]
What’s the output of `kubectl -n kube-system get po`

**Comment by grebois** [comment]
```
$ kubectl -n kube-system get po
NAME                             READY     STATUS    RESTARTS   AGE
default-http-backend-pp9tf       1/1       Running   0          1m
heapster-1rq6t                   1/1       Running   0          1m
influxdb-grafana-s79g0           2/2       Running   0          1m
kube-addon-manager-minikube      1/1       Running   0          1m
kube-dns-1326421443-63rfm        2/3       Running   0          1m
kubernetes-dashboard-kp7gs       1/1       Running   0          1m
nginx-ingress-controller-dl902   1/1       Running   0          1m
tiller-deploy-1114875906-mxkfl   1/1       Running   0          1m
```
