### ISSUE TITLE
pod of  tiller  automatically quit

### ISSUE THREAD

**Issue by post707** [kubernetes/helm#2801]
[root@k8smaster ~]# helm list --all
NAME                    REVISION        UPDATED                         STATUS          CHART           NAMESPACE
my-spark-chart          1               Sun Aug 13 05:39:23 2017        DELETING        spark-0.2.2.0   default 

When I manually delete my-spark chart, perform the delete operation

[root@k8smaster ~]# helm del --purge my-spark-chart
Error: transport is closing

Tiller quit automatically

**Comment by MattFriedman** [comment]
We see "transport is closing" frequently. 

Would love to get some hints as to why this can happen, and how we might troubleshoot. 

Thanks.

```
helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-23T16:14:43Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5+coreos.0", GitCommit:"e2cd7718ba844e874a68aa13f8f5bb0728b415bb", GitTreeState:"clean", BuildDate:"2017-03-22T01:59:35Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bacongobbler** [comment]
@MattFriedman ca you try upgrading helm and tiller to v2.5.1 and see if that fixes things? There was a deadlock in 2.5.0 when calling `helm delete` occasionally.

**Comment by MattFriedman** [comment]
@bacongobbler 
I tried doing `helm init --upgrade` but nothing changed, so is there a specific way I should upgrade in order to get 2.5.1? Thank you.

**Comment by bacongobbler** [comment]
Did you have the v2.5.1 client installed when you ran `helm init --upgrade`?

**Comment by post707** [comment]
@bacongobbler  
Thank you.
