### ISSUE TITLE
helm should ignore not yaml files in charts directory (whitelist)

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/helm#2807]
I've got a couple different editors which leave either previous versions around or autosave versions in the directory of the file being edited. It is irritating to have to go delete those, as they often result in a second object getting created that conflicts and prevents the `helm install` from succeeding.

I'm not sure if only yaml is what should be parsed, I've also seen some tpl's. It'd be great to have it ignore everything else but those. Not sure if there is anything else.

**Comment by bacongobbler** [comment]
Have you looked into the .helmignore file? Would that work for you or is it missing something?

**Comment by jascott1** [comment]
@MHBauer I agree that you should checkout Helm ignore but please be aware that by design Helm sends almost everything in the chart dir to be gzip'd and base64 encoded into a Release configMap.

**Comment by MHBauer** [comment]
never heard of helmignore. Having trouble finding the documentation, do you have a pointer?

**Comment by bacongobbler** [comment]
.helmignore works similar to .gitignore's syntax, however it prevents those files from being parsed when loading a chart via `helm install` (or any other command for that matter).

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
