### ISSUE TITLE
Package Image in the helm package

### ISSUE THREAD

**Issue by jungopro** [kubernetes/helm#2812]
Hello

Hope I'm posting this in the right place, I'm a github newbie :-)
I was wondering if there's a way (and if not, offer an idea) to package the container image together with the chart in the helm package command.

Ideally, if developed, it can be great that once the chart is deployed, it will create a temp registry, upload the container images from the package (.tgz file) to that registry and then instruct kubernetes to deploy from there.

I see a few benefits to this approach:

- Helm charts can be deployed without any dependencies - internet, latency, repo availability, etc.
- Charts with big container images will be deployed much faster
- Security - you can be sure that the image that you tested is the one you deployed and no changes were made from the minute you packaged the chart

Thanks
Omer

**Comment by rimusz** [comment]
hey there, Helm charts are made to pack your kubernetes manifest to one package and you reference in your .e.g. Deployment which docker image to use. Helm charts aren't meant to pack container images, this is docker registries are for.

**Comment by jungopro** [comment]
Hello

Thanks for your answer. I do understand the basic intention and usage of each (Helm & Docker). 
However, don't you think it will be nice if helm package will also download and package the specific docker image and keep all the dependencies together?
I understand it's not implemented today, but (in my humble opinion), I feel it may be a path worth approaching
How can I raise awareness to this as a "feature" rather than an "issue"? Is there a different place to post such suggestion?

Thank you
Omer

**Comment by rimusz** [comment]
when you install Helm chart it exactly does - downloads and packages the specific docker image and keeps all the dependencies together which you specify in the chart.
I think it is a bit of scope for the Helm chart to have in the chart the docker image as well.

**Comment by bacongobbler** [comment]
You might want to look at tools like [Draft](https://github.com/Azure/draft) to achieve this effect which deploys both a docker image and the chart. It's early software but there are other tools which are working on this problem.

disclaimer: I work on both Helm and Draft.

That being said, I do agree with @rimusz that this feature is out of scope of helm's original design.

**Comment by foobarbecue** [comment]
Draft appears to be dead :-( . The don't have plans to make it work with helm 3. Any alternatives?

**Comment by lsoica** [comment]
> You might want to look at tools like [Draft](https://github.com/Azure/draft) to achieve this effect which deploys both a docker image and the chart. It's early software but there are other tools which are working on this problem.
> 
> disclaimer: I work on both Helm and Draft.
> 
> That being said, I do agree with @rimusz that this feature is out of scope of helm's original design. There are other tools working on this problem alongside Helm.

It's 2023 and I'm still looking for a solution to transport an application's helm chart and corresponding container images to a disconnected environment in one go; something like an application package. Are there any alternative tools (with adoption) that cover this use case?

**Comment by jacobcrawford** [comment]
We are currently looking for the same. We have found this project that comes close to the wanted functionality: https://github.com/bitnami-labs/charts-syncer#sync-all-helm-charts
