### ISSUE TITLE
helm upgrade --install does not respect --namespace flag

### ISSUE THREAD

**Issue by nambrot** [kubernetes/helm#2814]
I have a somewhat similar situation to https://github.com/kubernetes/helm/issues/2764 but basically I'm trying to install a chart via `helm upgrade --install` and do so in a specific namespace with the `--namespace namespace` flag, but it still only installs it into the `default` namespace.

I suppose even the linked PR won't fix my issue as I manually set the namespace of my kube context and it still installs it into `default`

**Comment by bacongobbler** [comment]
I believe the linked issue is the exact same problem as described here. Can you please post there instead so we can keep it all in one ticket? Thanks.

**Comment by nambrot** [comment]
Thank you for your response. I believe the linked issue talks about the behavior in absence of the `--namespace` flag. In my case, I'm explicitly specifying it?

**Comment by bacongobbler** [comment]
It's the same code path and would be solved in the same PR, I'd believe. In this specific case I think it's fine to keep it in the same ticket for tracking `helm upgrade --install` namespace issues.

**Comment by nambrot** [comment]
Got it!

**Comment by macropin** [comment]
I don't believe this was resolved with PR #2808 I'm having this exact issue with v2.6.1

eg `helm upgrade --install --namespace andrew -f foo.yaml andrew .` installs into the default namespace.

**Comment by bacongobbler** [comment]
@macropin I could not reproduce this issue.

```
$ helm version
Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
$ helm upgrade --install --namespace foo ingressctl stable/nginx-ingress
Release "ingressctl" does not exist. Installing it now.
NAME:   ingressctl
LAST DEPLOYED: Mon Oct 16 21:48:39 2017
NAMESPACE: foo
STATUS: DEPLOYED
```

**Comment by macropin** [comment]
@bacongobbler after further investigation it looks like my issue is actually #3037. Helm reuses the namespace from the first revision of the release. `helm delete <release>` does not remove this reference. `helm delete <release> --purge` must be used before releasing into a different namespace.

I'm not sure if this is further evidence of a bug, or my misunderstanding of how helm retains configuration data.

**Comment by bacongobbler** [comment]
This isn’t the first time I've heard about the confusing behaviour between `helm delete` with and without the `—purge` flag. It is working as intended, though “as intended” does not seem to match many user’s understanding.

You are absolutely right in that you were bitten by #3037. Let’s carry the conversation there. :)
