### ISSUE TITLE
(cmd/helm): No way of obtaining the chart version for a release when chart name + version > 60 chars

### ISSUE THREAD

**Issue by sbuliarca** [kubernetes/helm#2828]
This is somehow related to #1914 and #1915.

helm version: 2.6.0

The MaxColumn is set to 60 on `helm list` and `helm history`.

Example:
```
helm list
NAME                            	REVISION	UPDATED                 	STATUS  	CHART                                                       	NAMESPACE
methode-article-image-set-mapper	5       	Fri Aug 18 15:37:00 2017	DEPLOYED	methode-article-image-set-mapper-1.3.0-k28s-helm-integrat...	default
```

Currently there is no way to obtain the version of the chart used for the release.

**Proposed solutions**:
1. allow setting the column max length from the command line ``` helm list --max-col-length=6000```
2. introduce another flag to show full column values ``` helm list --full-output ```

**Comment by jascott1** [comment]
@sbuliarca Im not crazy about --max-col-length personally. It might be time to consider adding `--output` similar to Kubernetes to allow more output formatting options for all commands.

**Comment by sbuliarca** [comment]
@jascott1 Indeed this would be a very nice option that would be more familiar to kubectl. I guess it implies more work though.

**Comment by jascott1** [comment]
@sbuliarca We could just start with `--o wide` and expand the output options later.

**Comment by sbuliarca** [comment]
@jascott1 Indeed, this sounds good.

**Comment by sbuliarca** [comment]
@jascott1 Are there any plans to include this feature in the near future?

**Comment by sbuliarca** [comment]
Excellent, thank you. I'll give it a go.

**Comment by sbuliarca** [comment]
@bacongobbler I managed to test it, and it works as expected

**Comment by Sushama-pan** [comment]
My chart versions are like 3.0.0+build.123 , 3.0.0-alpha.123.
I am able to push chart but while pull how to specify chart version? I am trying to add regex in:
helm pull --version ${regexstr} 

Regex not working any idea?
