### ISSUE TITLE
Dependency update deletes subcharts

### ISSUE THREAD

**Issue by thomastaylor312** [kubernetes/helm#2830]
In Helm 2.6.0, the new delete feature that deletes old versions of charts is deleting subcharts that aren't in `requirements.yaml`. Output of what this looks like is below:

```shell
$ ls charts/subchart 
Chart.yaml  charts      templates   values.yaml
$ helm dep up
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading heapster from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
$ ls charts
heapster-0.1.0.tgz
```

**Comment by jascott1** [comment]
@thomastaylor312  Sorry I did test that PR but not that case. I definitely think we should add a test for this.

**Comment by thomastaylor312** [comment]
@jascott1 If you know how to fix this quickly, feel free to take it. Otherwise I'll try to fix it over the weekend

**Comment by rocky-nupt** [comment]
I find dependency update safe delete subcharts in chart.denpendency instead of them in requirements.yaml.

**Comment by thomastaylor312** [comment]
@rocky-nupt Sorry I missed this. Please feel free to take it. I didn't have time over the weekend to work on it.

**Comment by prat0318** [comment]
Is there a way to *not* delete charts not present in `requirements.yaml`. I have some manually defined sub-charts along with `requirements.yaml`. I want both of the sets to get deployed.

**Comment by rocky-nupt** [comment]
Yes, of course. Our target is just to delete subcharts in requirements.yaml. @prat0318

**Comment by FX-HAO** [comment]
@rocky-nupt So there is no way to delete charts present in `requirements.yaml` ?

**Comment by rocky-nupt** [comment]
yeah, you can delete them manually if you want to delete charts present in requirements.yaml. @FX-HAO

**Comment by FX-HAO** [comment]
Maybe we could provide a flag to delete them automatically? @rocky-nupt

**Comment by FX-HAO** [comment]
Alternatively we can add a flag indicates installing and upgrading the charts present in `requirements.yaml`.

**Comment by rocky-nupt** [comment]
Of course, you can open a new issue. Just do it! : ) @FX-HAO
