### ISSUE TITLE
Helm history shows SUPERSEDED status for both successful and failed installations

### ISSUE THREAD

**Issue by nebril** [kubernetes/helm#2832]
There is no easy way to distinguish failed and successful releases that got superseded. Should this information be retained somehow, or should we get rid of SUPERSEDED status?

**Comment by fiunchinho** [comment]
I think it's useful information that get lost, and we should keep it somehow. Maybe we could only mark as SUPERSEDED those installations that were successful.

**Comment by redbaron** [comment]
status SUPERSEDED  can be inferred from `release.version != maxReleseVersionInHistory` therefore it adds no value, but instead conceals useful historical status

**Comment by bacongobbler** [comment]
fixed via #3097
