### ISSUE TITLE
Rudder address is hardcoded

### ISSUE THREAD

**Issue by dshulyak** [kubernetes/helm#2833]
One side of this issue is that currently deploying rudder is not easy as it could be. And second one, perhaps not that common, i am not able to spawn both original rudder and proxy requests to that rudder in my application (see https://github.com/dshulyak/rudder-proxy for details).

I suggest to add options both to rudder and tiller that will allow to use non-default address for grpc server and client. And as a third step, add options to helm init that will allow to configure them.

changes in:
- [x] rudder https://github.com/kubernetes/helm/pull/2825
- [x] tiller https://github.com/kubernetes/helm/pull/2835
- [ ] helm init

**Comment by bacongobbler** [comment]
@dshulyak looks like items 1 and 2 have been completed. Are you looking into item 3 any time soon? :)

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
