### ISSUE TITLE
rename kubernetes/application-dm-templates to kubernetes/charts

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#284]

**Comment by vaikas-google** [comment]
@jackgr when do you want this to happen?

**Comment by jackgr** [comment]
As soon as the PR from @adamreese is merged.

On Monday, February 29, 2016, vaikas-google <notifications@github.com>
wrote:

> @jackgr <https://github.com/jackgr> when do you want this to happen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/deployment-manager/issues/284#issuecomment-190384480>
> .
>


-- 
Jack Greenfield | Google

**Comment by vaikas-google** [comment]
is this ready to be done?

**Comment by jackgr** [comment]
Not yet. We'll want to reach a point where the integration is stable before
we rename. Not there yet. Do you have a hard deadline of any kind that we
need to accommodate?

Jack Greenfield | Google

**Comment by jackgr** [comment]
I'm now a Kubernetes owner, as well, so either of us can do it. We just need everyone to coordinate, so that it's orderly.
