### ISSUE TITLE
Version command/flag for tiller binary

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/helm#2841]
Would it be possible to add a command / flag to tiller to retrieve the current version? (similar to the helm binary)

**Comment by bacongobbler** [comment]
I have been inspecting the tag of the docker image via `kubectl -n kube-system get deploy tiller-deploy -o yaml`. I don't see why not, but then again there are existing ways to check the tiller version running in your cluster (`helm version`, check tiller deployment image tag)

**Comment by jascott1** [comment]
This seems like a reasonable feature as a binary should be able to tell you what version it is.

**Comment by rocky-nupt** [comment]
There is several ways to check the tiller if tiller has been installed. However, it seems that we can't get its version before it is installed. I think it is indeed a meaningful feature.

**Comment by sbueringer** [comment]
We have to build our own Tiller Image in our environment and we just wanted a way to verify with some kind of smoke test that tiller is there and in the correct version. Therefore something like tiller version would be nice. Although it's not really that important it would be useful.
