### ISSUE TITLE
[chart_best_practices] suggest adding the usage of `namespace`

### ISSUE THREAD

**Issue by flyer103** [kubernetes/helm#2842]
In [chart_best_practices](https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices), there's no state which indicates whether or not the chart should manage the namespace that resources should reside in. From the usage of `helm`, which namespace is used by chart is decided by the argument of `helm install/upgrade`. And there's no state which  indicates which namespace `helm` will use to install a chart if the `--namespace` argument is empty.

So I suggest that adding the usage of `namespace` to [chart_best_practices](https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices) will be helpful to developers.

**Comment by DoctorZK** [comment]
I think the namespace you referred to is release namespace. The release namespace will be set as `default` if you do not give a value through `--namespace` flag, which have no connection with chart information. Therefore, I prefer a new doc for describing all the default value for Helm actions (install/upgrade/uninstall/rollback ,etc.) than adding this into existing files in chart_best_practices.

**Comment by flyer103** [comment]
If using `helm install` without `--namespace`, it will try to use the current context's namespace from `kubeconfig` and if the value is empty, then `default` namespace will be used.

**Comment by bacongobbler** [comment]
This was a very recent feature that hasn't landed in a release yet.

**Comment by bacongobbler** [comment]
My bad, this was actually implemented well before v2.0.0 in https://github.com/kubernetes/helm/pull/1400.

**Comment by flyer103** [comment]
Aha, I think you may want to refer to the the change for `helm upgrade --install` without `--namespace`: https://github.com/kubernetes/helm/pull/2808  :D

**Comment by bacongobbler** [comment]
thanks @flyer103. Yeah, this was merged in and should be available in v2.7.0. :)
