### ISSUE TITLE
how to void ::  helm escaping doesnt help ?

### ISSUE THREAD

**Issue by rajivmucheli** [kubernetes/helm#2844]
I have to helm the below 2 postgres queries:

SELECT floating_network_id, COUNT(floating_ip_address) AS FIP_Used FROM floatingips WHERE floating_ip_address LIKE '10%' GROUP BY floatingips.floating_network_id

SELECT ipallocations.network_id, SUM(ipallocationpools.last_ip::inet - ipallocationpools.first_ip::inet) as iprange_value  FROM ipallocationpools INNER JOIN ipallocations ON ipallocationpools.subnet_id=ipallocations.subnet_id WHERE ip_address LIKE '10%' GROUP BY ipallocations.network_id

Helm lint doesn't show any errors, yaml & go validators dont show any errors either. 

helm escaping works for ", but adding \ for :: doesnt help.

`helm version`
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}

**Comment by bacongobbler** [comment]
I'm completely lost here. How does helm and SQL statements relate to each other? Perhaps you're thinking of another project?

**Comment by rajivmucheli** [comment]
These queries are added in the values.yaml file to create metrics. May be
you could look at SAPCC org on openstack-helm for more details!

**Comment by bacongobbler** [comment]
What have you tried? Have you tried escaping the double colon using `\:\:` in your values?

**Comment by rajivmucheli** [comment]
Yes I tried this as well but had no luck!, I tried using " and ' but the
query doesn't work. inet function in the query plays a key role in the
metric execution and creation.
