### ISSUE TITLE
Deploy helm chart via REST

### ISSUE THREAD

**Issue by ajayapte** [kubernetes/helm#2847]
I don't see any swagger definition for tiller.  Did I miss it?  How do I deploy a chart via REST?  I see a few go classes that do it but I am not using go (just straight http/rest).  Is there a swagger or doc on how to?

**Comment by bacongobbler** [comment]
Tiller communicates using gRPC, not REST.

related request: https://github.com/kubernetes/helm/issues/2176

**Comment by DoctorZK** [comment]
Several people have tried to build an api-server by themselves to recieve REST requests and resend the REST requets to tiller through gRPC. In the api server, you can import the helm client as an embeded package. Perhaps you can try this way, if you really want to communication with Tiller through REST.

**Comment by ajayapte** [comment]
OK thanks.  That seems to be the path.
