### ISSUE TITLE
There's no way to set a value to literal string "true", "false" or number

### ISSUE THREAD

**Issue by calind** [kubernetes/helm#2848]
I need to set some annotations to literal string `true` rather than boolean of truth. Currently there is no way to do it since the value `true`, `false` and numbers get parsed into their typed values.

The issue can be reproduced for nginx-ingress chart for example:

```
helm install stable/nginx-ingress --set controller.podAnnotations.prometheus\\.io/scrape=true
```

**Comment by bacongobbler** [comment]
`helm install stable/nginx-ingress --set controller.podAnnotations.prometheus\\.io/scrape=\"true\"` worked for me.

**Comment by bacongobbler** [comment]
We should document this in https://docs.helm.sh/using_helm/#the-format-and-limitations-of-set.

**Comment by DoctorZK** [comment]
ESC must be added before your boolen value, since helm now recieves all values through command line  as []string{}.

**Comment by dcwangmit01** [comment]
FYI... I think the escape workaround only works depending on the application.  I've tried all permutations of escaping, including "!!str true", and it still doesn't work for nginx-ingress-controller.    It looks like I might have to fork the chart this point.

**Comment by dcwangmit01** [comment]
I'm curious if the fix for this issue:
  https://github.com/kubernetes/helm/issues/1449

Has created the bug in this thread.

**Comment by inkwelldocs** [comment]
@bacongobbler, your workaround doesn't work for me, the `prometheus.io/scrape` value in the resulting YAML ends up literally being the string `\"true\"`.

**Comment by jahewson** [comment]
@bacongobbler, your workaround doesn't work for me, the `prometheus.io/scrape` value in the resulting YAML ends up literally being the string `\"true\"`.

**Comment by jahewson** [comment]
@DoctorZK, what do you mean by "ESC must be added before your boolen value"?

**Comment by dvdmuckle** [comment]
This issue appears to still be present, currently running into the same thing as @jahewson, where `\"true\"` ends up as `"\"true\""` in the resulting YAML.

**Comment by bacongobbler** [comment]
`--set-string` was introduced into master and should be available in 1.9. Closing via #3599

**Comment by licarth** [comment]
> This issue appears to still be present, currently running into the same thing as @jahewson, where \"true\" ends up as "\"true\"" in the resulting YAML.

@dvdmuckle Me too. My workaround is to use `helm install -f values.yaml` with values being : 
```
controller:
    config:
        my-boolean-config-entry: "true"
```

I end up having proper `"true"` as expected in the resulting YAML.

**Comment by elritsch** [comment]
Hi @bacongobbler, according to your comment in https://github.com/kubernetes/helm/issues/4006#issuecomment-386161617, `--set-string` only affects long integers and is not supposed to have any effect on boolean types. This contradicts https://github.com/kubernetes/helm/issues/2848#issuecomment-376557547 just above, so, I think this issue was closed prematurely. Would you agree?

However, I've created a patch that makes the `--set-string` flag parse *all* values as strings and no longer interprets `true`, `false`, `null`: https://github.com/elritsch/helm/commit/272d9bc6efff112b578e48334054534290d3af95.

In my mind, the above patch would make the behaviour of `--set-string` more intuitive than the current behaviour. I'd be happy to make a pull-request if you like.

**Comment by bacongobbler** [comment]
yes, I think that patch is the right approach. If you could PR that it'd be much appreciated. Thanks!

**Comment by jeffery7** [comment]
I happened upon this problem today and solved it like this:
`some.test.attribute1:                    '"true"'
some.test.attribute2:                    '"false"'`

**Comment by sharkymcdongles** [comment]
I know this is old, but easiest way to solve this is printf e.g.

`{{ printf "%t" .Values.some.bool }}`

This will print true or false.
