### ISSUE TITLE
rename kubernetes/deployment-manager to kubernetes/helm

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#285]

**Comment by vaikas-google** [comment]
@jackgr when do you want this to happen?

**Comment by jackgr** [comment]
As soon as the PR from @adamreese is merged

On Monday, February 29, 2016, vaikas-google <notifications@github.com>
wrote:

> @jackgr <https://github.com/jackgr> when do you want this to happen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/deployment-manager/issues/285#issuecomment-190384327>
> .
>


-- 
Jack Greenfield | Google

**Comment by vaikas-google** [comment]
Ok, so is this ready to be done now?

**Comment by jackgr** [comment]
Not yet. We'll want to reach a point where the integration is stable before
we rename. Not there yet. Do you have a hard deadline of any kind that we
need to accommodate?

Jack Greenfield | Google

**Comment by vaikas-google** [comment]
No, just want to make sure I'm not blocking anything. So, I'll just wait...

**Comment by jackgr** [comment]
No worries. I'm now a Kubernetes owner, as well, so either of us can do it. We just need everyone to coordinate, so that it's orderly.
