### ISSUE TITLE
helm init thinks tiller is installed, but helm ls cant find tiller

### ISSUE THREAD

**Issue by mhristof** [kubernetes/helm#2851]
Versions:
```
helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T17:03:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Im initializing helm with

```
helm init --service-account tiller --kube-context k8s.example.org
```

and that reports back that everything is ok

```
? helm init --service-account tiller --kube-context k8s.example.org
 has been configured at /Users/user/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```

But if i try to check the pods that are available in all nodes, im not getting tiller anywhere

```
? kc get pods --all-namespaces                                             (k8s.example.org/kube-system)
NAMESPACE     NAME                                                               READY     STATUS    RESTARTS   AGE
kube-system   dns-controller-341853554-7bx8r                                     1/1       Running   0          1h
kube-system   etcd-server-events-host-WjaJrQts.reg-n5X70.compute.internal        1/1       Running   0          1h
kube-system   etcd-server-host-WjaJrQts.reg-n5X70.compute.internal               1/1       Running   0          1h
kube-system   kube-apiserver-host-WjaJrQts.reg-n5X70.compute.internal            1/1       Running   0          1h
kube-system   kube-controller-manager-host-WjaJrQts.reg-n5X70.compute.internal   1/1       Running   0          1h
kube-system   kube-dns-479524115-4s4v9                                           3/3       Running   0          1h
kube-system   kube-dns-479524115-zrlxq                                           3/3       Running   0          1h
kube-system   kube-dns-autoscaler-1818915203-89ltb                               1/1       Running   0          1h
kube-system   kube-proxy-host-WjaJrQts.reg-n5X70.compute.internal                1/1       Running   0          1h
kube-system   kube-proxy-host-zUKxnz73+.reg-n5X70.compute.internal               1/1       Running   0          1h
kube-system   kube-proxy-host-D7Gg8fk7l.reg-n5X70.compute.internal               1/1       Running   0          1h
kube-system   kube-proxy-host-FF6Bbj7.reg-n5X70.compute.internal                 1/1       Running   0          1h
kube-system   kube-scheduler-host-WjaJrQts.reg-n5X70.compute.internal            1/1       Running   0          1h
kube-system   weave-net-84bgr                                                    2/2       Running   0          1h
kube-system   weave-net-90m02                                                    2/2       Running   0          1h
kube-system   weave-net-g4fcs                                                    2/2       Running   0          1h
kube-system   weave-net-nntlj                                                    2/2       Running   0          1h
```

and when i try to check `ls`, im getting the tiller warning

```
? helm ls                                                                  (k8s.example.org/kube-system)
Error: could not find tiller
```

I dont believe there is a bug in helm as im currently trying RBAC stuff and i've probably not set something that is required for helm to work. But its misleading that the `init` tells me that tiller is already installed.

**Comment by bacongobbler** [comment]
Can you try v2.6.0 and confirm if that's working? Also I'd check `ks get deploy` and see if a `tiller-deploy` resource exists in that namespace. You can also check the namespace events and perhaps that'd show why pods are not being created.

**Comment by mhristof** [comment]
The deployment was there, but the pod was failing.

Does some rewording like this makes sense or should i close this ?

from

```
Warning: Tiller is already installed in the cluster.
```

to

```
Warning: Tiller deployment is already installed in the cluster.
```

**Comment by jascott1** [comment]
@mhristof Im not sure just adding the word `deployment` adds much clarity. Perhaps giving more detail in the docs about manually uninstalling Helm/Tiller would be more helpful. For instance, we currently mention [uninstalling by deleting the Tiller deployment](https://github.com/kubernetes/helm/blob/4204f69cd24c0dbe80c3045f89c6f315daa4055a/docs/install.md#installing-tiller-canary-builds) but there is also a service and configmaps to be removed.

**Comment by mhristof** [comment]
That might be valid @jascott1 but im not sure its related to this.
Im closing the issue as i dont think any action needs to be taken

**Comment by cforce** [comment]
I delete Tiller deployment manually from ns kube-system on docker for windows cluster. Then run again helm init and deployment appeared again. Butt still says can findt tiller?

PS C:\Users\user> kubectl get deployment/tiller-deploy  -o wide
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS   IMAGES                                  SELECTOR
tiller-deploy   1         0         0            0           36s       tiller       gcr.io/kubernetes-helm/tiller:v2.11.0   app=helm,name=tiller
PS C:\Users\user> helm status
Error: could not find tiller
PS C:\Users\fwallwit>

**Comment by bacongobbler** [comment]
doesn't look like there's a pod running on your cluster. Check and see why there's no pods running.

**Comment by cforce** [comment]
i found a leftover from istio, that want to be installed as sidecar on the tiller pod and fails. That is the issue. So no helm issue. sry, for innovience
