### ISSUE TITLE
failed to install when namespace exists

### ISSUE THREAD

**Issue by Anmorata** [kubernetes/helm#2853]
I'm having problem when installing helm chart. I created helm template with `helm create mychart` and added few my lines. added also namespace template.
when running helm install:
`Error: release funky-buffoon failed: namespaces "default" already exists
`
kubernetes is 1.6.6 verstion on azure cloud. tiller came with it I just updated to 2.6 version

version:
```
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

**Comment by jascott1** [comment]
Hi @Anmorata, can you also share the entire command you are running?

**Comment by Anmorata** [comment]
I tried `helm install ./chartName` and `helm install --replace ./chartName`

**Comment by seh** [comment]
To clarify, does your chart include a manifest for an object of kind _Namespace_?

**Comment by Anmorata** [comment]
yes, I have three manifests deployment,service and namespace. so that if namespace doesn't exists it'll create one

**Comment by seh** [comment]
Keep in mind that Helm will already create a nonexistent namespace for the release—assuming you mean the target namespace into which the chart is being installed. There are cases where a chart being installed into one namespace needs to create other namespaces as well. It's also possible that you want the target namespace to have, say, certain annotations on it, which I assumed was your motivation here.

**Comment by Anmorata** [comment]
the problem is that this namespace already exists, its not nonexistent. all manifests target one namespace.  I have two services that must go in one namespace. after creating first one, second helm chart is arguing because the namespace already exists.

**Comment by bacongobbler** [comment]
What @seh means is that you should not be including Namespace manifests in your chart. You should be using the --namespace flag. Helm charts at this time can only be installed in a single namespace.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
