### ISSUE TITLE
getting some information

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/helm#2855]
Hi,

I really love the basic idea of helm templating. So I decided to use it for a project. But some things are still really hard to get.

For instance, after you parse my templates, where do you put the parsed results? It's so important if you have a parser for anything that you can view the results to see what the parser did maybe different than one expected.

Where can I see what http requests helm is sending (url+body)? I'm not having a default kubernetes installation here and need to make sure that others can also reach the tiller service. Also maybe seeing some http responses may help debug things.

What is the difference between the argument `--namespace` and  the environment variable `$TILLER_NAMESPACE`? For some reason I can only use helm when I do the second version. And I had nothing tell me about the problem. It was dumb try and error. Would be really nice if there would be a smarter way to debug.

And why does a `helm delete --purge <name>` not remove everything? For instance in my environment there is always a serviceaccount that still exists after.

Thanks!

**Comment by jascott1** [comment]
@erikbgithub Thank you for using Helm. Hopefully we can get your issues taken care of. To see parsed results of templating you may add the `--debug` flag to see the final output. Also adding the `--dry-run` flag together with `--debug` will let you see the output without actually installing. 

Helm uses gRPC not REST so you will not be able to see requests to Tiller as you might be used to in conventional REST applications.

`--namespace` directs Helm to install your chart into the specified namespace.
TILLER_NAMESPACE refers to the namespace that the backend componnent Tiller is installed into ("kube-system" by default)

Hope that helps. Please let us know if you have any more questions.

**Comment by erikbgithub** [comment]
Hi jascott1, thanks for responding.

I'm not sure the namespace question is complete. Because I do both in a separate session after `helm init` already succeded another day.

Example. Let's assume you start the day with a new bash session in which no helm environment is set. Tiller is already deployed. Now you do just a `helm ls --namespace=foobar` and it fails. Now you set `export TILLER_NAMESPACE=foobar`  and now `helm ls` without a namespace flag succeeds. Would you agree that situation is not explained by your answer?

**Comment by bacongobbler** [comment]
nope, I can understand @jascott1's instructions quite clearly (but then again, I'm a helm dev).

- `helm list` with `--namespace` shows charts that were released in that namespace.

- `TILLER_NAMESPACE=foobar helm list` tells helm to communicate with the tiller instance installed in the `foobar` namespace to list *all* releases installed across all namespaces.

I can understand the confusion, though. TILLER_NAMESPACE is documented [here](https://docs.helm.sh/using_helm/#easy-in-cluster-installation):

> Helm will look for Tiller in the `kube-system` namespace unless `--tiller-namespace` or `$TILLER_NAMESPACE` is set.

Does that help clear things up? If not, I highly suggest taking a look through the [Using Helm](https://docs.helm.sh/using_helm) section of the docs to get a clearer picture.

**Comment by erikbgithub** [comment]
Ah now I understand. Thanks!
