### ISSUE TITLE
helm release deleted but k8s objects still there

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/helm#2858]
I created a deployment->replicaset->pod(1) installation via a helm chart. Then I tried to delete it again via `helm delete --purge <name>`. It reports a success.

But when I check k8s the objects are still there.

Trying to delete them manually via `kubectl delete` yields timeout errors. So I would suspect that the returncode on the underlying kubectl or api requests isn't really checked in the helm code and a success is reported incorrectly. Until I've resolved the timeout error I'm free to provide further information.

**Comment by jascott1** [comment]
Hi @erikbgithub 
Sorry for the unusual delete behavior but hopefully we can get it resolved. One thing you said that concerns me is 
>Trying to delete them manually via kubectl delete yields timeout errors

To me that suggests something is wrong with your k8s cluster since Helm creates resources that should always be deletable by `kubectl delete`.  Does `kubectl delete` work on other non-Helm created resources?

**Comment by erikbgithub** [comment]
Hi @jascott1 
Yeah, the problem that yielded that behavior was k8s related. I think even other helm charts may work. However, would you agree that if such a timeout happens, that helm should yield an error and leave the release entry in its own database? Let's focus on that point here. I have k8s people who can help with the second problem resolving the problem on that end.

**Comment by jascott1** [comment]
I agree that Helm should report any errors, timeouts or otherwise. It is possible k8s lied so its currently hard to say where the problem is. Have you figured out how to reproduce?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
