### ISSUE TITLE
Tiller keeps turning itself off?

### ISSUE THREAD

**Issue by MostAwesomeDude** [kubernetes/helm#2866]
Branching from #2640, I've got a problem where `tiller-deploy` keeps being disabled somehow. I have two clusters, and the offending cluster offers this description:

```
$ kubectl describe deploy tiller-deploy --namespace kube-system
Name:			tiller-deploy
Namespace:		kube-system
CreationTimestamp:	Wed, 23 Aug 2017 21:54:58 -0700
Labels:			app=helm
			name=tiller
Selector:		app=helm,name=tiller
Replicas:		0 updated | 0 total | 0 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	True	MinimumReplicasAvailable
OldReplicaSets:	<none>
NewReplicaSet:	tiller-deploy-3864487562 (0/0 replicas created)
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  2d		20s		2	{deployment-controller }			Normal		ScalingReplicaSetScaled up replica set tiller-deploy-3864487562 to 1
  2d		10s		2	{deployment-controller }			Normal		ScalingReplicaSetScaled down replica set tiller-deploy-3864487562 to 0
```

My Helm is Helm 2.5.1 from nixpkgs:

```
$ helm version
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```

The non-cooperative cluster is GKE with k8s 1.6.7:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6+114f891", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"not a git tree", BuildDate:"2017-08-18T01:05:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

And the working cluster is Bluemix with k8s 1.5.6:

```
$ kubectl version --context blanu-dal12
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6+114f891", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"not a git tree", BuildDate:"2017-08-18T01:05:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.6-4+abe34653415733", GitCommit:"abe346534157336e6bd5a70702756cff19d43a49", GitTreeState:"clean", BuildDate:"2017-05-18T16:52:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by seh** [comment]
Can you clarify what you mean by "being disabled?" Are you referring to the _Deployment_ being scaled down to zero replicas?

**Comment by MostAwesomeDude** [comment]
Yes. I am seeking the root cause of Helm being unable to contact Tiller. I figure that it is related to the fact that there are no `tiller-deploy` pods running.

**Comment by seh** [comment]
That is odd that the _Deployment_ was scaled without your intervention. Note the second event above shown in _kubectl describe deployment_, shortly after being scaled up to one:
> ScalingReplicaSetScaled down replica set tiller-deploy-3864487562 to 0

Do you have a _ResourceQuota_ governing the "kube-system" namespace? Normally such a quota wouldn't scale a _Deployment_, but I'm wondering whether GKE has something fancy here that's surprising us both.

**Comment by MostAwesomeDude** [comment]
Hi! Apologies for the lag. Your quick turnaround is appreciated.

I had to go learn some more about k8s. I think that there are no quotas set up:

```
$ kubectl get quota --all-namespaces
No resources found.
```

The automatic rescaling is just something that happens, yeah. I don't know enough about k8s to find out where that is coming from; I figured that Tiller might do it somehow, which I know is wrong, but I can't find anything else on the cluster that would do that.

...Well, actually, chaoskube used to be running on this cluster. I don't think it's the culprit because it was installed via Helm, and I removed all of the Helm-installed stuff, and I also read the chaoskube source and it only cancels Pods, so it can't do this.

**Comment by bacongobbler** [comment]
ping @MostAwesomeDude, were you able to resolve this issue eventually? This seems like an external actor is causing this behaviour from my perspective. I've never heard of a Deployment scaling up on its own unless there was some horizontal pod autoscaler enabled on your cluster.
