### ISSUE TITLE
Installation of app from custom remote repo is failing

### ISSUE THREAD

**Issue by krlng** [kubernetes/helm#2868]
I am hosting a custom helm-repo in a [gcloud bucket](https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md#google-cloud-storage). I can not install the app from there, since it gives me `http: no Host in request URL`. If I serve the same folder locally, I don't have any trouble to install the apps.

```
$ helm version
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}

$ helm repo list
NAME            URL
stable          https://kubernetes-charts.storage.googleapis.com
local           http://127.0.0.1:8879/charts
onlinerepo        https://helmrepo.storage.googleapis.com

$ helm install --debug onlinerepo/helm-logstash
[debug] Created tunnel using local port: '50494'

[debug] SERVER: "localhost:50494"

[debug] Original chart version: ""
Error: Get http:///helmrepo.storage.googleapis.com/helm-logstash-0.0.1.tgz: http: no Host in request URL

$ helm search logstash
NAME                    VERSION DESCRIPTION
onlinerepo/helm-logstash  0.0.1
local/helm-logstash     0.0.1
```

**Comment by jascott1** [comment]
Hi @krlng 
Sorry you are having trouble. First thing, any idea why there is an extra slash in the repo URL returned in the error?
```
Error: Get http:///helmrepo.storage.googleapis.com/helm-logstash-0.0.1.tgz: http: no Host in request URL
                  ^extra slash
```

**Comment by krlng** [comment]
Okay, Thank you jascott. I did not recognize the third slash. After finding this I checked my index.yaml more carefully and recognized, it had 3 slashes as well. Then I checked my bash history and found that I accidenatly built my repo with `helm repo index --url http:///helmrepo.storage.googleapis.com .` (3 Slashes in the url). The the problem was my error. Closing this.

**Comment by WesleyCharlesBlake** [comment]
one thing be sure to do is run `helm repo update` to refresh the repo of changes
