### ISSUE TITLE
PR helm/charts onto kubernetes/charts

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#287]
Depends on #284.

/cc @runseb

**Comment by runseb** [comment]
PR is in https://github.com/kubernetes/application-dm-templates/pull/9

But we need to figure out CLA issues. By bringing the history of helm/charts some authors may not have a CLA on file.

**Comment by jackgr** [comment]
Closing this issue, since we have the PR in kubernertes/charts to track it.
