### ISSUE TITLE
Helm should create `$HELM_HOME/plugins`

### ISSUE THREAD

**Issue by svend** [kubernetes/helm#2870]
Installing a plugin via `helm plugin install` fails if the plugins directory does not exist:

```
$ helm plugin install https://github.com/technosophos/helm-template
Error: plugin home "$HELM_HOME/plugins" does not exist
```

The directory needs to be manually created. It would be nice if helm automatically created this directory.

```
$ helm version
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
This directory is created when you run `helm init` or `helm init --client-only`. Does that work for you?

**Comment by svend** [comment]
That works. Thanks!
