### ISSUE TITLE
Releases link and Windows link not available in landing page.

### ISSUE THREAD

**Issue by jagraj** [kubernetes/helm#2875]
Hi,

We do not have download link for windows and there is no link to previous releases. The only way we can get to the previous releases is from Installation guide. Could you please add releases and windows link to landing page.?

Landing page : https://github.com/kubernetes/helm

Releases : https://github.com/kubernetes/helm/releases

**Comment by jascott1** [comment]
@jagraj Im sorry but I do not understand your problem. You can access all the Windows binaries from the `releases` page you linked so I don't understand your statement "We do not have download link for windows and there is no link to previous releases". Can you elaborate more on what you need?

**Comment by jascott1** [comment]
@jagraj 
Esteemed Helm ninja @bacongobbler took care of that Windows link on the home page. FYI previous releases are available under releases->tags. Thanks!
