### ISSUE TITLE
Configuration tag to prefer specific namespace?

### ISSUE THREAD

**Issue by mcandre** [kubernetes/helm#2883]
Could there be a helm metadata in Kubernetes resources, so that the resource deploys to the configured namespace by default, unless overridden with `--namespace`?

**Comment by bacongobbler** [comment]
You can point your kube config to a specific namespace. Helm will then install in that namespace by default. It's in master but hasn't made into a release yet.

https://github.com/kubernetes/helm/pull/2808

**Comment by bacongobbler** [comment]
this was merged in and is in helm 2.7.
