### ISSUE TITLE
Enhancement: Dependent charts

### ISSUE THREAD

**Issue by mcandre** [kubernetes/helm#2884]
Could Helm provide a mechanism for declaring links from one chart to another, so that for example `kafka` first deploys `zookeeper`? I mean, we could use make to establish these links, but that somehow feels wrong when working with clusters instead of files.

**Comment by bacongobbler** [comment]
Helm has a concept called "umbrella charts" that allow you to specify a set of charts all installable as a single chart. For example, Deis Workflow is a single umbrella chart that installs the controller, logger, router, builder, monitoring stack etc.

https://docs.helm.sh/developing_charts/#complex-charts-with-many-dependencies

Does that work for you?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
