### ISSUE TITLE
Helm reset won't work

### ISSUE THREAD

**Issue by dfang** [kubernetes/helm#2886]
helm reset and helm reset --force could not uninstall Tiller from my minikube cluster.

> minikube version
minikube version: v0.21.0

> helm reset
Error: could not find tiller

> helm reset --force
Error: error unstalling Tiller: timed out waiting for the condition

ref: https://github.com/kubernetes/kubernetes/issues/51764

**Comment by jascott1** [comment]
@dfang it appears helm cannot contact Tiller. Do other helm commands work? Does `kubectl` work from same terminal?

**Comment by dfang** [comment]
@jascott1 i upgraded kubectl, helm, minikube to the latest version, the bug is gone. close the issue.
