### ISSUE TITLE
Update docs to clarify best use of default command

### ISSUE THREAD

**Issue by scottrigby** [kubernetes/helm#2888]
The current docs for best use of default command recommends duplicating defaults both in `values.yaml` and in a `default` command inside the template. This is not DRY, and I don't think we should recommend that. However, there are use cases where `default` command is not redundant (for example, computed values which can't be declared in static `values.yaml`). I'll open a PR for this next.

**Comment by scottrigby** [comment]
Please add `docs` label

**Comment by scottrigby** [comment]
@technosophos I understand the docs are meant to start simple, and add more complexity as other concepts/functions are explained - which makes sense. But IMO this statement is misleading:
> It is considered good (almost mandatory) practice to set defaults with default for any object that originates from .Values.

I think that is actually false. If so, there would be no value in a `values.yaml` file at all (I know there are discussions elsewhere about updating how charts document these defaults, but as of Today I think we don't want to recommend people repeat a default both in `values.yaml` and using the `default` command inside templates, right?

**Comment by omkensey** [comment]
(Bringing over my comment from my chart PR, for the sake of this discussion)

Given that, is it still considered necessary or good practice to wrap calls to values nested beyond the first level, that have defaults in `values.yaml`, in `{{- if }}` blocks like so?

```
{{- if .Values.foo.service }}
    - name: {{ .Values.foo.service.name }}
      port: {{ .Values.foo.service.port }}
{{- else }}
    - name: "myservice"
      port: 80
{{- end }}
```
...or can the conditional guards be dropped entirely in that case and just say

```
    - name: {{ .Values.foo.service.name }}
      port: {{ .Values.foo.service.port }}
```

**Comment by scottrigby** [comment]
@omkensey Conditionals still make sense, if that part of the final k8s manifest is optional. This issue is only about clarifying the part of the helm docs that says it's:
> considered good (almost mandatory) practice to set defaults with `default` for any object that originates from `.Values`

The PR #2889 has a LGTM on it now, so looks like that part will be updated, while trying to preserve the original intent of this part of the docs.
