### ISSUE TITLE
Using a NFS server in a chart 

### ISSUE THREAD

**Issue by vincbe** [kubernetes/helm#2895]
I'm testing helm to package an application and I'm wondering if I'm missing something.
We decide to use NFS for our PV because we neewhen I d "ReadWriteMany" access mode.

As I was previously using a shell script to deploy the app, I was beginning by creating a NFS server service, getting its IP address (a cluster IP) that I finally substitute in my K8s descriptor to bind my PV on the IP (for the moment it using the IP seems to be only way to get a PV on a NFS. Local cluster DNS resolution doesn't work.. yet?)

I can't see dynamic way to get the this NFS server IP using an unique chart that could describe altogether the NFS server and the PV using it.
Is the only solution would be to have a distinct chart for my NFS server and another one for the app that will use the NFS so I can set the IP with a variable...
so I'll have to script the orchestration and helm won't help for this dependency? 

All hints are welcome ;)

**Comment by bacongobbler** [comment]
were you able to figure out a solution for this? :)

**Comment by vincbe** [comment]
I did separate the NFS service in a distinct chart that has to be installed (with its IP defined) before to install my app chart. This NFS IP is a variable required for my app chart.

**Comment by bacongobbler** [comment]
That's basically the same approach I'd suggest. Helm doesn't perform any explicit bindings between charts, nor do I think it should to separate concerns between a package manager and a orchestration platform.

[Kubernetes services](https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services) provide environment variables for every exposed port in its manifest to all pods in the same namespace, which is a common software pattern when writing apps for Kubernetes. You should be able to write out a service in your NFS chart that exposes the NFS pod's container port, then your application may use NFS_SERVICE_HOST:NFS_SERVICE_PORT to access the NFS daemon.

Does that help? :)
