### ISSUE TITLE
Unable to install chart - Error: open values.yml: no such file or directory

### ISSUE THREAD

**Issue by juliohm1978** [kubernetes/helm#2896]
On a fresh installation, I'm unable to install any new charts.

```
$ helm version
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

```
$ helm init
$HELM_HOME has been configured at /root/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```

```
root@infra00-lab:~/kube/nginx-ingress-controller# helm install --namespace frontend --name frontend stable/nginx-ingress -f values.yml
Error: open values.yml: no such file or directory
```

```
helm install --namespace monitoring --name prometheus -f helm-values.yaml stable/prometheus
Error: open helm-values.yaml: no such file or directory
```

I know it seems obvious, but both files `values.yml` and `helm-values.yaml` exist in the related directories where `helm install` is being issued.

```
root@infra00-lab:~/kube/prometheus# ls -l
total 56
-rw-r--r-- 1 root root   275 Aug  3 16:22 clusterrolebindings.yaml
-rw-r--r-- 1 root root 26277 Aug 25 13:20 helm-values.yaml
-rw-r--r-- 1 root root    92 Aug 21 17:18 install.sh
-rw-r--r-- 1 root root    59 Aug  3 16:19 namespaces.yaml
-rw-r--r-- 1 root root   503 Aug  2 15:40 persistentvolumes.yaml
-rw-r--r-- 1 root root   130 Aug 24 12:42 quota.yaml
-rw-r--r-- 1 root root   366 Aug  3 16:19 roles.yaml
-rw-r--r-- 1 root root    62 Aug 21 17:17 upgrade.sh
```

```
root@infra00-lab:~/kube/nginx-ingress-controller# ls -l
total 24
-rw-r--r-- 1 root root   29 Aug 11 18:49 delete.sh
-rw-r--r-- 1 root root   85 Sep  5 13:32 install.sh
-rw-r--r-- 1 root root  937 Aug 11 17:34 permissions.yml
-rw-r--r-- 1 root root   57 Aug 11 17:43 upgrade.sh
-rw-r--r-- 1 root root 5288 Sep  5 13:29 values.yml
```

**Comment by bacongobbler** [comment]
Are you absolutely sure you're running `helm install` from the correct directory? I cannot reproduce this when running from a temporary directory in my local filesystem.

```
><> pwd
/tmp/test
><> ls -al
total 0
drwxr-xr-x  2 bacongobbler  wheel   68  5 Sep 10:01 .
drwxrwxrwt  8 root          wheel  272  5 Sep 09:59 ..
><> touch helm-values.yaml
><> helm install stable/nginx-ingress -f helm-values.yaml
NAME:   dealing-fish
LAST DEPLOYED: Tue Sep  5 10:02:05 2017
[...]
><> helm version
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

**Comment by juliohm1978** [comment]
Yes, I'm sure.

On further details, my Kubernetes installation was provisioned by Kubespray, which also installs helm if you wish for that.

As I found out later, Kubespray deployed Tiller with a `default` ServiceAccount, which would be useless. I was able to completely remove the helm installation made by Kubespray and manually install it again with the correct permissions.

The good news is, it's working now. But if this is related to permissions, the error message provided by helm might need some polishing.

Thanks for the help!

**Comment by guenhter** [comment]
**Kubespray-helm**
The reason why `helm` doesn't find any files provided with the `-f` option is because `helm` is installed as docker container run command by kubespray:

```
cat /usr/local/bin/helm

#!/bin/bash
/usr/bin/docker run --rm \
  --net=host \
  --name=helm \
  -v /etc/ssl:/etc/ssl:ro \
  -v /root/.helm:/root/.helm:rw \
  -v /usr/share/ca-certificates:/usr/share/ca-certificates:ro \
  lachlanevenson/k8s-helm:2.7.0 \
  "$@"
```

If you define a file with `-f`, the container doesn't find that file, unless you place it into a folder which is mounted (e.g. the `/root/.helm`)

**Comment by rahulroyal924** [comment]
Hi ,

I am trying this command to deploy the chart in spinanaker

"./helm install -n fd stable/spinnaker -f spinnaker-config.yaml --debug --timeout 600 --version 1.1.6 --wait"

But i am facing below error
"
[debug] Created tunnel using local port: '34897'

[debug] SERVER: "127.0.0.1:34897"

[debug] Original chart version: "1.1.6"
[debug] Fetched stable/spinnaker to /home/mabluh/.helm/cache/archive/spinnaker-1.1.6.tgz

[debug] CHART PATH: /home/mabluh/.helm/cache/archive/spinnaker-1.1.6.tgz

Error: Job failed: BackoffLimitExceeded"

Can anybody please help me to resolve this problem?

Thanks in advance
