### ISSUE TITLE
Update Sprig to support regex functions

### ISSUE THREAD

**Issue by philipbjorge** [kubernetes/helm#2902]
Sprig now supports regex replacements -- it would be great to get these functions into helm as they would simplify creating `DNS-1123` compliant labels among other things...

**Comment by jascott1** [comment]
@philipbjorge Sprig version in Helm is has been 2.12 for a few releases. Which functions are not available?

**Comment by philipbjorge** [comment]
I'm primarily interested in the regex functions:
https://github.com/Masterminds/sprig/commit/32180d9bfa4afdd61b10d062616774286a0fc6e2

But there have been other functions added as well:
https://github.com/Masterminds/sprig/commit/f6e5c4edb5bf19979ba526fbb83d33a09c3ce160
https://github.com/Masterminds/sprig/commit/e169b83f8f8caa2cb17347808bc179e464c536fe
https://github.com/Masterminds/sprig/commit/782a01164d2cba80d80ef202fc45616e6d0a333d

I believe they are all pending release. The regex functions though would help a lot in ensuring that values being passed to my charts are properly sanitized before giving to kubernetes.

@technosophos -- Do you know when we'll see another release of sprig?

**Comment by technosophos** [comment]
Yeah -- I am planning on doing a release of it next week in order to make the 2.7.0 release milestone.

**Comment by bacongobbler** [comment]
closed via #2930.
