### ISSUE TITLE
Tiller fails to delete stateful set with annotations:pod.beta.kubernetes.io/init-containers

### ISSUE THREAD

**Issue by abinet** [kubernetes/helm#2908]
I have helm chart which contains a statefull set with a init-containers annotation like:

```      
annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox:1.26.2",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
``` 

Such stateful set can not be deleted with `helm delete ..` 
In tiller logs one can observe following error:

`2017/09/08 07:42:24 release_server.go:1084: uninstall: Failed deletion of "es": Scaling the resource failed with: StatefulSet.apps "es-data-elasticsearch" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' are forbidden.; Current resource version 25617104`

But I'm able to delete stateful set with kubectl.

Helm versions `2.4.x-2.6.0` 
Kubernetes `v1.5.4-rancher1`

**Comment by jascott1** [comment]
@abinet Thanks for reporting this. I failed to reproduce this on helm 2.6.1 and K8s 1.7.5. 
I created a foo chart, changed the Deployment to a StatefulSet, modified the apiVersion to `apps/v1beta1`, added your annotation. It installs and deletes without problem. 
I can tell the error you posted is from an earlier version of Helm since that file no longer has a line 1080. Can you post the output with Helm 2.6.1?

**Comment by abinet** [comment]
Tried with Helm 2.6.1 - same error:

```2017-09-12T10:26:32.537165903Z [tiller] 2017/09/12 10:26:32 error: Scaling the resource failed with: StatefulSet.apps "es-data-elasticsearch" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' are forbidden.; Current resource version 26535124```

Maybe it is an issue only for earlier K8s versions (I'm using 1.5.4-rancher1)

**Comment by jascott1** [comment]
@abinet Yes it seems so. Are you able to try with a more recent k8s?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
