### ISSUE TITLE
`helm upgrade --install` should also show invalid YAML on error

### ISSUE THREAD

**Issue by georgecrawford** [kubernetes/helm#2909]
`helm install --dry-run --debug` nicely dumps the templated YAML when there's a parse error (see https://github.com/kubernetes/helm/pull/1546). However, `helm upgrade --install --dry-run --debug` does not do this, so I just see this fairly useless error:

```
Error: UPGRADE FAILED: YAML parse error on api/templates/deployment.yaml: error converting YAML to JSON: yaml: line 73: did not find expected key
```
I can't see the YAML, so I have no idea what's on line 73.

Thanks for a great project!

**Comment by technosophos** [comment]
Yeah, we need to handle this case better. Upgrade's output has been a source of contention (should it show a diff or the full YAML?). But regardless of which way we go, we need to do _something_ to improve the output.

**Comment by naphthalene** [comment]
Please include the full YAML. Its impossible to debug parse errors.

Sometimes there's no line number included either, making it even harder:

```
Error: UPGRADE FAILED: error converting YAML to JSON: json: unsupported value: +Inf
```

**Comment by bacongobbler** [comment]
There is a new feature being rolled out in the 2.7 release called `helm template` which should assist in debugging these issues. You can try out one of the canary releases if you feel like giving it a shot!

**Comment by bacongobbler** [comment]
Given that `helm template` was rolled into core in #1887 I think we can call this issue closed.

For anyone using older clients, you can use the `helm template` plugin via `helm plugin install https://technosophos/helm-template`.

**Comment by naphthalene** [comment]
Thank you @bacongobbler !
