### ISSUE TITLE
Question: helm install use existing k8 running containers, configmaps, services.. etc

### ISSUE THREAD

**Issue by jamorales-bsft** [kubernetes/helm#2910]
The question is if doing a helm install for the first time can existing k8 components be brought into the new helm release and managed by helm as if helm had installed the components? 

The reason being my company already has a production environment setup and it would nice if OPs could using existing services for instance with the same IP instead of having to do helm install to make a new helm release and then tear down the existing setup and change IPs

**Comment by bacongobbler** [comment]
There is a proposal for a command to bring in existing resources via #2730. You might want to add your thoughts to that discussion.

**Comment by bacongobbler** [comment]
cc'ing @thomastaylor312

**Comment by jamorales-bsft** [comment]
will do thanks
