### ISSUE TITLE
default with null global in values.yaml gives error

### ISSUE THREAD

**Issue by jamorales-bsft** [kubernetes/helm#2913]
Running this line in my deployment yaml give me the error below

Error: render error .... can't evaluate field nodepool in type interface {}

Bad:

`nodeSelector:
            cloud.google.com/gke-nodepool: {{ default .Values.nodepool .Values.global.nodepool }}`

I tracked it down to the fact that I have no .Values.global.nodepool is not defined. However I should not have to define it. If I use a non global value that is not defined it works normally just leaving it blank

Good:

`nodeSelector:
            cloud.google.com/gke-nodepool: {{ default .Values.nodepool .Values.nodepool }}`

values.yaml - for both examples

`nodepool: `

**Comment by bacongobbler** [comment]
`default` works by setting a "default" value if the first string is an empty string. You probably want to use `default .Values.nodepool "some-node-selector"` so that "some-node-selector" is used if .Values.nodepool is not set.

Can you explain more clearly on what you want to do with this section of code? Perhaps using a conditional field like `{{- if .Values.nodepool }}nodeSelector: cloud.google.com/gke-nodepool: {{ .Values.nodepool }}{{- end }}` would be a better use here.

**Comment by jamorales-bsft** [comment]
nodeSelector: cloud.google.com/gke-nodepool: {{ default .Values.nodepool .Values.global.nodepool }}

so again with the piece of code it is not setting a default value. It is giving an error if the global is not defined. If .Values.nodepool is defined but .Values.global.nodepool is not I get the error I posted. According to what you posted default should use the first string of .Values.nodepool since it exists. Instead it is doing some kind of precheck to see if .Values.global.nodepool first even exists regardless of what is in the first string.

**Comment by jamorales-bsft** [comment]
Your solution will not work because I want to make the global value the default and the non global the first string. It seems like you are saying I have to hardcode the default value. This is incorrect in the `helm create` helper.tpl file there existing this command.

`{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}` You can see default being used here with 2 template variables. The issue is simply default fails when either of its values are global and that global is empty.

**Comment by bacongobbler** [comment]
That would be because `.Chart.Name` is automatically provided through `helm install` even if `--name` is present, whereas `nodepool` is not.

**Comment by jamorales-bsft** [comment]
ok your workaround will work as it protects against an undefined global variable. 

But default will still work if 2 template variable are used that are non global. This for instance works in all cases. Whether one or both of the variable are not defined.

`cloud.google.com/gke-nodepool: {{ default .Values.nodepool .Values.testValue }}`

using a global still causes default to operate differently. Unless this use case is the the bug and it should be causing an error.

**Comment by jamorales-bsft** [comment]
Actually after some more digging your work around is causing the same issue. The problem seems to be that `.Values.global.nodepool` is not defined at all if there is no `global: nodepool:` in the value.yaml unlike non global values which seem to default to undefined values but the key is defined. Both of our code does not work because if no `global: nodepool:` is defined then .Values.global.nodepool is undefined and that means `.Values.global.nodepool` is trying to reference an undefined key versus an undefined value. A simple `global:` only still causes the same error to get thrown. 

Both cases work if I add `global: nodepool:` to value.yaml even if it has no value.

**Comment by bacongobbler** [comment]
Are you looking for something like [`required`](https://docs.helm.sh/developing_charts/#know-your-template-functions)? You're not being very clear what is the problem you are attempting to solve.

`default` does not provide nor will it provide "protection" against undefined variables. As I've said several times, it is only useful when you want to provide a "sane default" value when a value is not present.

https://github.com/Masterminds/sprig/blob/master/docs/defaults.md#default


> Actually after some more digging your work around is causing the same issue.

Not for me. I ran `helm create` and made a few changes to test this. Here's what I did:

values.yaml:

```
$ cat tmpchart/values.yaml | head -n 1
global: {}
```

deployment.yaml (note the new annotation):

```
$ cat tmpchart/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if or .Values.nodepool .Values.global.nodepool }}nodeSelector: cloud.google.com/gke-nodepool: {{ default .Values.nodepool .Values.global.nodepool }}{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
```

And the end result:

```
$ helm template tmpchart/
---
# Source: tmpchart/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: RELEASE-NAME-tmpchart
  labels:
    app: tmpchart
    chart: tmpchart-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
  annotations:
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tmpchart
        release: RELEASE-NAME
    spec:
      containers:
        - name: tmpchart
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            null


---
# Source: tmpchart/templates/ingress.yaml

---
# Source: tmpchart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-tmpchart
  labels:
    app: tmpchart
    chart: tmpchart-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: tmpchart
    release: RELEASE-NAME
```

No rendering errors, and the nodepool value is unset. Now, if I set .Values.global.nodepool:

```
><> helm template --set global.nodepool=foo tmpchart/
---
# Source: tmpchart/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: RELEASE-NAME-tmpchart
  labels:
    app: tmpchart
    chart: tmpchart-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
  annotations:nodeSelector: cloud.google.com/gke-nodepool: foo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tmpchart
        release: RELEASE-NAME
    spec:
      containers:
        - name: tmpchart
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            null


---
# Source: tmpchart/templates/ingress.yaml

---
# Source: tmpchart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-tmpchart
  labels:
    app: tmpchart
    chart: tmpchart-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: tmpchart
    release: RELEASE-NAME
```

And the same result happens for `--set nodepool=bar`.

```
><> helm template --set nodepool=bar tmpchart/
---
# Source: tmpchart/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: RELEASE-NAME-tmpchart
  labels:
    app: tmpchart
    chart: tmpchart-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
  annotations:nodeSelector: cloud.google.com/gke-nodepool: bar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tmpchart
        release: RELEASE-NAME
    spec:
      containers:
        - name: tmpchart
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            null


---
# Source: tmpchart/templates/ingress.yaml

---
# Source: tmpchart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-tmpchart
  labels:
    app: tmpchart
    chart: tmpchart-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: tmpchart
    release: RELEASE-NAME
```

It's not clear to me what is the issue. Please explain your problem more clearly so I may be able to assist you. Thanks.

**Comment by jamorales-bsft** [comment]
If you change your example to use global: instead of global: {} in your values.yaml it will throw the error. I am reporting a bug/inconsistent behavior not actually looking for a solution. This would be easier if we could focus on what is causing the unexpected behavior and you guys can determine what you want to do with it if anything. 

default does not provide nor will it provide "protection" against empty/undefined variables.
- My point is sometime it does and that is confusing. 

Again this will work. Even if values.yaml is completely empty. In this case default is protecting again undefined variables as well as being forgiving if no variable is defined. 
`cloud.google.com/gke-nodepool: {{ default .Values.nodepool .Values.testValue }}`

However changing one of these to a global will break this if values.yaml is completely empty. So far that issue has not been addressed at all. If default should only work when there is a hardcoded default value then 
`cloud.google.com/gke-nodepool: {{ default .Values.nodepool .Values.testValue }}`

should not work and throw some kind of error.

**Comment by bacongobbler** [comment]
Hey, finally coming back to this issue after being on the road for a few weeks. Sorry about that!

I completely understand the frustration you're having with the error message. The problem is that YAML's spec is a very complex beast, so parser errors like this are very common and are not very intuitive to the user on how they should fix this. I actually ranted about this a little in https://github.com/Azure/draft/issues/326 and it's also an ongoing discussion in #2577.

Using `global:` as opposed to `global: {}` is poorly formed YAML and will fail the parser. It goes against [the YAML spec](http://yaml.org/spec/) to specify an undefined map in your YAML file. I'm not sure if there's anything we can do to "fix" this. Helm is doing the right thing here by reporting the parser error you described in the original error message, and this is the best we can do. `helm lint` should also report the same error.

For reference, I'm referring to this error.

> Error: render error .... can't evaluate field nodepool in type interface {}

Thank you very much for the bug report!
