### ISSUE TITLE
Ability for charts to have a slash ('/') in thieir name, to better namespace them.

### ISSUE THREAD

**Issue by AmandaCameron** [kubernetes/helm#2915]
I had originally thought that this was what #1401 was meant to include, but I now understand that I had just been reading what I wanted to read.

My PR #1997 happen to include that assumption as part of it, however it was stripped back to ease the burden of the case of there being issues with slashy-names.

I decided rather than try and re-do it all, I'd first check if this is of interest to anyone else. With some clever hacking of `cd` and such in my charts repo, we can probably proceed roughly with what we wanted using just #1401  and #1997, however it's not quite the solution we were originally hoping for.

The primary usecase I see for this is "namespacing" of charts, for example, if we were to have `foo-service` and `bar-service` both of which were SSP webapps backed by a second chart for serving an "API" the SSP used, I feel it'd be worth having a `foo-service/backend` be considered a seperate entity by helm than `bar-service/backend`, without the unnessary stutter that'd be required currently of `foo-service/foo-service-backend` in a charts repo.

**Comment by jascott1** [comment]
@AmandaCameron  Thanks for the idea. I sympathize with trying to better organize the charts but In my opinion this is not necessary and undesirable for these reasons:
* If foo-service-backend chart is specific to foo-service it should be named foo-service-backend. If its the same sub-chart for both, you might be able to use the `alias` feature in `requirements.yaml`
* This breaks the chart/directory naming convention (chart name matches directory name) so would be 3.x release 
* I suspect it would affect many subsystems and require refactoring where the ROI just isn't worth it

That being said, I'd like to help figure out a solution. Can you explain your take on the alias feature and if it works for what you are trying to accomplish?

**Comment by AmandaCameron** [comment]
It wasn't actually too hard to implement, I ended up fixing #1401 in my PR #1997 by implementing the ideas put forth in this proposal, having mis-understood #1401's purpose.

re: naming convention: I solved this originally by making it check not just the base directory name, but parent directories too. so it'd check `foo-service/backend` against the `.../foo-service/backend/` containing the Chart.yaml
