### ISSUE TITLE
Passing value to subcharts maintained by others?

### ISSUE THREAD

**Issue by martinbeck** [kubernetes/helm#2927]
How can I pass a non-global value to a subchart that is not maintained by myself? E.g., our parent chart is using postgresql chart as dependency, which provides a `postgresql.nodeSelector` value. However, we also have many other components depending on a single, 'global' `nodeSelectors.system` value in our own values.yaml. How can I pass the value specified for `nodeSelectors.system` to the postgresql subchart's `postgresql.nodeSelector`?

Even if I make a copy of the postgresql chart and modify it, I have to use `global.nodeSelectors.system` to be able to access the value from the parent. But from our users' perspective, it makes no sense to have `global` namespace in config options, they don't care that we're using other charts internally.

**Comment by technosophos** [comment]
Values can be passed "downstream" from an umbrella chart to subcharts just by specifying the path in the values file. (And the parent's value file can include these -- they don't have to be overriden by the user). So we tend to suggest overriding at the top level and passing the values downward (though sometimes that means duplicating the same value with two different names).

There are maybe a few tricks you could try based on the requirements file (https://docs.helm.sh/developing_charts/#chart-development-tips-and-tricks), but I'm not sure any of them will provide you a more straightforward solution.

**Comment by martinbeck** [comment]
So my parent chart's values.yml looks like this:
```
nodeSelectors:
  system: {}

postgresql:
  nodeSelector: {}
```
What I want is that if the user specifies `--set nodeSelectors.system=...` that this will automatically get passed downstream to postgresql.nodeSelector. I don't see, how this is currently possible. I tried to use `import-values` in requirements.yml, which kinda might do what I want, but as of now, it does only support dictionaries but not single values.

As the chart ecosystem grows, I would expect this use-case to happen more often: Renaming a config option of a subchart under a new name of the umbrella chart. Are there any plans to support something like this?

**Comment by wernight** [comment]
I'm wondering the same.

**Comment by jgoeres** [comment]
I consider this a valid requirement and have been wondering how to solve this without requiring my end  users to duplicate certain values that they special on the commandline/with a values file.
THe issue should be reopened.
