### ISSUE TITLE
Helm create say creating but doesnt create

### ISSUE THREAD

**Issue by rishiraaz** [kubernetes/helm#2935]
Helm was installed through kubespray playbook
[root@# helm create mojo
Creating mojo
[root]# ll
total 0
[root]#

helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}

If I create manually and then run helm install
it says , no Charts.yaml found.

**Comment by bacongobbler** [comment]
When you say

> If I create manually and then run helm install

How are you creating the chart manually, and are you supplying the directory name to `helm install`? Can you please provide steps on how you installed the Helm client? As far as I understand kubespray it only sets up tiller which is the server-side side of helm, which is not required for `helm create`.

For example, you should be able to do the following:

```
$ git clone https://github.com/kubernetes/charts
$ helm install charts/stable/mailhog
```

And it should install the mailhog chart on your cluster.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
