### ISSUE TITLE
Helm always appends /index.yaml at the end of the URL

### ISSUE THREAD

**Issue by mcwienczek** [kubernetes/helm#2937]
When adding a new repo helm always appends /index.yaml to the end of URL. This is undesired behaviour for some repositories that need additional query string parameters, such as Azure Blob Storage. Azure Blob Storage required appending special query string to HTTPS URL in order to get access to the file. Other sites might use similar mechanism or want to pass some parameters as query strings.

Example URL:

https://sometestblobstorage.blob.core.windows.net/?sv=2017-04-17&ss=1234&srt=asd&sp=12314&se=2019-10-15T19:49:26Z&st=2017-10-15T11:49:26Z&spr=https&sig=MKARQzLpTeSt7IRlgjpF9ke6p34UO0xhUGaMotWUrz1PpDFWw

Helm looks for index.yaml at:

https://sometestblobstorage.blob.core.windows.net/?sv=2017-04-17&ss=1234&srt=asd&sp=12314&se=2019-10-15T19:49:26Z&st=2017-10-15T11:49:26Z&spr=https&sig=MKARQzLpTeSt7IRlgjpF9ke6p34UO0xhUGaMotWUrz1PpDFWw/index.yaml

Expected behaviour:

inserting index.yaml inside url, right before query string.

https://sometestblobstorage.blob.core.windows.net/index.yaml?sv=2017-04-17&ss=1234&srt=asd&sp=12314&se=2019-10-15T19:49:26Z&st=2017-10-15T11:49:26Z&spr=https&sig=MKARQzLpTeSt7IRlgjpF9ke6p34UO0xhUGaMotWUrz1PpDFWw

I know that probably in the same way we would need to rewrite fetching packages. I am ready to create PR this week.

**Comment by mcwienczek** [comment]
I would like to start working on this. Any guidelines and help really appreciated.

**Comment by mattfarina** [comment]
@mcwienczek I would start in the repo package...

https://github.com/kubernetes/helm/blob/eea32faaadf8891f6882b00f0dfe828e5cbe8e0e/pkg/repo/chartrepo.go#L111-L115

Instead of trimming a suffix and just appending the index file name, you might update this to use the `url` package manipulate the url and generate a valid string.

**Comment by mcwienczek** [comment]
Thank you for the heads up @mattfarina. I have posted first draft of PR. Could you please review it for me? Thank you in advance for help. 

Unfortunately I have a feeling that URL string is overused in the repository. I decided, though, not to refactor half of the application just to use URL struct, as it might break some backward compatibility. Therefore I decided to go with bugfix for current version .This PR should not affect any other functionality as it only tries to fetch charts when not found at the original URL.

**Comment by mcwienczek** [comment]
UPDATE: I think I've been able to find the code that is responsible for that bug and fixed the issue at the root. I have also added one test. I hope that is enough to fix that bug.
