### ISSUE TITLE
update security email link

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes/helm#2939]
As far as I know, helm-security@deis.com still works as per [Reporting a Security Issue](https://github.com/kubernetes/helm/blob/master/CONTRIBUTING.md#reporting-a-security-issue), but we should probably update the mailing list now that Deis has been acquired by Microsoft.

**Comment by mattfarina** [comment]
Should this be a MS email address or something for the community?

**Comment by mattfarina** [comment]
@michelleN did you own the task to chase this one down? I think I remember that from a Helm meeting. If I'm wrong maybe you remember who had this.

**Comment by michelleN** [comment]
yeah I'm asking CNCf now.

**Comment by michelleN** [comment]
This should be a private mailing lists that anyone can email right?

**Comment by mattfarina** [comment]
@michelleN yeah.

Note, where we share this we should even go so far as to point people to pgp keys, for those that have them, if someone wants to use that.

**Comment by bacongobbler** [comment]
closed via #4124
