### ISSUE TITLE
Helm upgrade --install deletes daemonset and drops desired to zero

### ISSUE THREAD

**Issue by rustyShacklefurd** [kubernetes/helm#2958]
```
helm version
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```
Helm is run via `helmfile --kube-context prod --file helm/production.yaml sync`
[Helmfile Repo](https://github.com/roboll/helmfile}
```
Command helmfile runs with no changes to the chart or associated values:
helm upgrade --install kube2iam stable/kube2iam --version 0.5.1 --namespace kube-system --values values.yaml --kube-context prod
```
Expected Behavior
Since the kube2iam daemonset already exists and no values had changed, the expected behavior is for helm to see no changes and do nothing.

Experienced Behavior
Helm drops the number of desired pods to zero.  Tiller deletes the daemonset `kube2iam` daemonset and redeploys as `kube2iam-kube2iam`.
```
Release "kube2iam" has been upgraded. Happy Helming!
LAST DEPLOYED: Fri Sep 15 17:29:56 2017
NAMESPACE: kube-system
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/DaemonSet
NAME               DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE-SELECTOR  AGE
kube2iam-kube2iam  0        0        0      0           0          <none>         15s
```
Tiller logs pertaining to the event https://gist.github.com/rustyShacklefurd/96280924f52b59bb4c1087758b7e8193

The most problematic part of this is that it seems to happen sporadically about every 20 runs or so and only happens to daemonsets deployed by helm but never any other kubernetes pod deployment concepts.

**Comment by bacongobbler** [comment]
This looks like a chart upgrade issue rather than a Helm issue, per se. The behaviour on how the chart was named was changed in https://github.com/kubernetes/charts/commit/1b2ad923ae111bdff761d85c14da7f62a91cea6f#diff-df86d0f1c7721d7866b0319ac74efe55, so it looks like it's working as it was originally intended. I would open an issue at http://github.com/kubernetes/charts unless it's actually a core Helm issue. Thanks!
