### ISSUE TITLE
helm delete bug

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/helm#2959]
with helm 2.6.1, I'm seeing a strange issue on delete:
http://logs.openstack.org/26/449826/29/check/gate-kolla-kubernetes-deploy-ubuntu-binary-2-ceph-nv/8d2739b/console.html#_2017-09-21_16_55_48_292414

2.4.0 does not have the issue, nor does 2.5.1. I have not tested 2.6.0 yet. I'll put it in the queue.

**Comment by kfox1111** [comment]
2.6.0 has the issue too.

**Comment by bacongobbler** [comment]
can you try v2.7.0 and see if it's been fixed? The logs you posted are no longer available so I don't have an idea on what the original issue was. Sorry!

**Comment by bacongobbler** [comment]
closing as inactive.
