### ISSUE TITLE
Feature request: Tolerations and node affinity on tiller

### ISSUE THREAD

**Issue by egeland** [kubernetes/helm#2966]
It would be good if it was possible to supply tiller with a (for example)
`--toleration="key=value:taint"` to allow it to tolerate taints (so it can run on master nodes, for example) and `--node-affinity="key=value"`, so we can prefer to schedule tiller onto non-spot instances in AWS, for example.

I'm a Go novice, but I can try to implement, if someone more knowledgable  can assist, especially with writing the tests..?

**Comment by jascott1** [comment]
Hi @egeland 

We have some expanded init options coming in 2.7 including the ability to `--set` arbitrary keys and values in the Tiller deployment manifest. Hopefully this will address your needs but please let me know if there are any gaps.
https://github.com/kubernetes/helm/pull/2557

**Comment by egeland** [comment]
Sounds promising - I added a note requesting documentation examples, to the ticket you linked to 😀

**Comment by bacongobbler** [comment]
#2557 seems to solve this with --override and --node-selectors, so I'm closing this. Thanks!

**Comment by 34code** [comment]
Does --override only apply to tiller or to charts also?

**Comment by jascott1** [comment]
`--override` only applies to `helm init` and the Tiller deployment manifest.

**Comment by 34code** [comment]
@jascott1 thanks for the confirmation!
