### ISSUE TITLE
errors between tiller and helm when using ssl

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/helm#2967]
Hello,

I have tiller configured with ssl, but when I'm trying to install a chart, this is what the server is reponding to helm:

    2017/09/25 13:11:16 grpc: Server.Serve failed to complete security handshake from "127.0.0.1:51418": tls: first record does not look like a TLS handshake

Any ideas what I'm doing wrong?

Best regards,
Cristian

**Comment by bacongobbler** [comment]
Hey @cristifalcas, can you show the documentation and steps you followed on how you set up tiller with HTTPS? Also how are you connecting to tiller? Are you using HELM_HOST? WHat command are you running to get this error?

**Comment by cristi-** [comment]
Hi,

 We have the same issue when running **helm list** (helm install works fine).
 I'm not too familiar with Golang but it seems the difference is that the package for install uses the certificates while the list doesn't actually use them.

Install: https://github.com/kubernetes/helm/blob/8fc88ab62612f6ca81a3c1187f3a545da4ed6935/cmd/helm/install.go#L102-L125
List: https://github.com/kubernetes/helm/blob/8fc88ab62612f6ca81a3c1187f3a545da4ed6935/cmd/helm/list.go#L60-L77

Thanks!

**Comment by cristifalcas** [comment]
Installation:

    helm init --tiller-tls --tiller-tls-verify --tls-ca-cert /etc/kubernetes/pki/ca.crt --tiller-tls-cert /etc/kubernetes/pki/tiller.crt --tiller-tls-key /etc/kubernetes/pki/tiller-key.pem --tiller-image external/tiller:v2.6.2
    kubectl create serviceaccount --namespace kube-system tiller
    kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

Using:

    # helm install stable/memcached --namespace memcached-ns --tls --tls-ca-cert /etc/kubernetes/pki/ca.crt --tls-cert /etc/kubernetes/pki/client.crt --tls-key /etc/kubernetes/pki/client-key.pem
    NAME:   viable-wombat
    LAST DEPLOYED: Tue Oct 24 11:21:55 2017
    NAMESPACE: memcached-ns
    STATUS: DEPLOYED
    .....

List:

    # helm list --tls --tls-ca-cert /etc/kubernetes/pki/ca.crt --tls-cert /etc/kubernetes/pki/client.crt --tls-key       
    /etc/kubernetes/pki/client-key.pemError: transport is closing

**Comment by bacongobbler** [comment]
this might be related to #2791.

**Comment by bacongobbler** [comment]
this was fixed in v2.7.1.
