### ISSUE TITLE
Update Roadmap wiki

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#2968]
The roadmap wiki, linked in the README, is out of date. It should likely link to the milestones and explain them. It currently talks about features back in the 2.3.0 timeframe when a roadmap wiki page was required for incubation.

**Comment by bacongobbler** [comment]
This was noted in https://github.com/kubernetes/helm/issues/694#issuecomment-322363075 so we should definitely update the documentation to point at the github milestones at the very least.

**Comment by mattfarina** [comment]
@bacongobbler seems I have edit access to the wiki. Is there a review process to update it? I'm happy to do it.

**Comment by bacongobbler** [comment]
Oh hey, so do I! :)

No, I don't think there's a formalized review process to update the wiki. Since it's largely been eclipsed with https://docs.helm.sh I think we can change it at-will. I'll fire off a quick PR to update the README.
