### ISSUE TITLE
Cannot connect to Tiller - context deadline exceeded

### ISSUE THREAD

**Issue by gowthamsadasivam** [kubernetes/helm#2970]
I have a three (1 master + 2 minions) nodes Kubernetes cluster up and running on Cent OS 7.

**Kubernetes Version**: `v1.5.2`

**Kubernetes Config** :
> `# kubectl config view`
> apiVersion: v1
> clusters: []
> contexts: []
> current-context: ""
> kind: Config
> preferences: {}
> users: []

**Kubernetes Cluster Info** :
> `# kubectl cluster-info`
> Kubernetes master is running at http://localhost:8080
> KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
> kubernetes-dashboard is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

I've just followed the Helm installation steps from the documentation. After downloading the "helm" binary to the system path I did : `# helm init` 

> `Creating /root/.helm `
> `Creating /root/.helm/repository `
> `Creating /root/.helm/repository/cache `
> `Creating /root/.helm/repository/local `
> `Creating /root/.helm/plugins `
> `Creating /root/.helm/starters `
> `Creating /root/.helm/cache/archive `
> `Creating /root/.helm/repository/repositories.yaml `
> `$HELM_HOME has been configured at /root/.helm.`
> `Happy Helming!`

I can see `Tiller` pod is running : `# kubectl get pods -o wide --all-namespaces`

```
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
default       nginx-ingress-rc-s83kb                  1/1       Running   0          6d        172.30.71.3   minion03
kube-system   kube-dns-v20-z8lnd                      3/3       Running   0          21d       172.30.71.2   minion03
kube-system   kubernetes-dashboard-3543765157-tmmb8   1/1       Running   1          21d       172.30.89.2   minion02
kube-system   tiller-deploy-833363792-5v0gk           1/1       Running   0          10m       172.30.71.6   minion03
```

But, when I issue the version command : `helm version --debug`

> `Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}`
> `[debug] context deadline exceeded`
> `Error: cannot connect to Tiller`

^ Couldn't connect to `helm server` pod.

What am I doing wrong? How to fix this issue?

**Comment by bacongobbler** [comment]
looks like a duplicate of #2409. Can you please comment on that ticket? It doesn't seem like a cloud provider specific problem if it's happening on different deployments.

**Comment by gowthamsadasivam** [comment]
Hello @bacongobbler 

Thanks for the comment & suggestion. I'm running on bare-metal, not a cloud provider specific problem. I just commented this at #2409 thread and will follow up from there. Closing this issue now.
