### ISSUE TITLE
Golang requirement is actually >= 1.7, stated as 1.6 on Developer Guide

### ISSUE THREAD

**Issue by danielyinanc** [kubernetes/helm#2987]
Go 1.6.0 or later is claimed to be Prequisite, however 1.6 goLang build attempts result in this error:
vendor/k8s.io/client-go/rest/request.go:21:2: cannot find package "context" in any of:

context package is added as of 1.7, hence effective minimum version of GO required to build helm is actually 1.7 and above.

**Comment by bacongobbler** [comment]
A lot of the core maintainers just always use the latest version of Go. We should just document that you should be using the latest version of Go on HEAD because there are a few new features like type aliases and test helpers which we might be using soon, and those are both Go 1.9 features. https://github.com/kubernetes/helm/pull/2126#issuecomment-325397035

**Comment by danielyinanc** [comment]
@bacongobbler that is a good idea however there may be some package dependencies relying on earlier versions of Go in the future.

Also a small number of us (including myself) are actually building it to deploy via binaries to solve some infrastructure type of problem preventing 'helm init' to work correctly. These folks need some stable version of Go to build as they need  to support infrastructure deployments on enterprise side of things.  

Without binaries built for different nix platforms and no docker image on docker hub etc, becomes a problem for enterprise infra.

**Comment by bacongobbler** [comment]
> however there may be some package dependencies relying on earlier versions of Go in the future.

That hasn't ever been a problem (and if it is, we'd love to hear about it!). Go 1.x has always been backwards compatible with older releases, so compiling packages that "rely" on older versions of Go will still work the same on later releases. The only time this will break is when Go 2.0 comes out. 

Go follows semantic versioning very carefully and should be considered a gold standard when it comes to stability and backwards compatibility.

> These folks need some stable version of Go to build as they need to support infrastructure deployments on enterprise side of things.

That should not prevent development on HEAD from moving forward. Stability and "the bleeding edge that is HEAD" are two very different use cases... Unless you happen to be running HEAD in production, which I wouldn't recommend for obvious reasons.

As far as

> Without binaries built for different nix platforms and no docker image on docker hub etc, becomes a problem for enterprise infra.

We just recently replatformed our CI on top of CircleCI 2.0 as of #2838, so we should try and revisit #1929 and others.

**Comment by flyer103** [comment]
Maybe using `golang image` other than golang binary on every developers' environment could make building helm uniform. 
Example: https://github.com/thockin/go-build-template/blob/master/Makefile#L81

**Comment by danielyinanc** [comment]
That can help, due to docker DNS requirements, had to build it for ubuntu servers, a lot of enterprise folks will have similar issues... found some abandoned docker images to support projects.

Anything that can make the build process standardized and easier, can assist in adoption of Helm big time IMHO.

**Comment by bacongobbler** [comment]
Once https://github.com/kubernetes/helm/pull/1929 has been merged that workflow will become available. I would open a separate ticket as that discussion is separate from the OP.
