### ISSUE TITLE
Tiller does not correctly verify apiserver cert

### ISSUE THREAD

**Issue by khenidak** [kubernetes/helm#2989]
If Kubernetes default service ip (first ip of service cider) is not in the cert used by apiserver tiller will not complain, leaving tiller subject to man in the middle attacks.

**Comment by ysh7** [comment]
Yes doesn't verify tls by default, you need to configure tls while running [helm init](https://github.com/kubernetes/helm/blob/master/docs/helm/helm_init.md).

**Comment by bacongobbler** [comment]
@khenidak is there something actionable here that the flags provided in `helm init` doesn't provide already?

**Comment by khenidak** [comment]
I think - could be wrong? - helm init parameters refer to client auth certs, not tiller=>api-server

I believe that helm should be secure by default. as in validate the cert by default unless the user deliberately override the behavior.

@lachie83
