### ISSUE TITLE
Helm hooks not being processed in correct order

### ISSUE THREAD

**Issue by lachie83** [kubernetes/helm#2995]
I'm having issues ordering the creation of the following resource in this PR - https://github.com/kubernetes/charts/pull/2369.

I have a bunch of CRD pre-install resources with a weight of 1 and a bunch of custom resources with a hook weight of 2. I expect the resource with a weight of 1 to be installed first. Instead I see the behaviour works some of the time and other times results in 

```
$ helm install --name istio . --namespace istio-system
Error: apiVersion "config.istio.io/v1alpha2" in istio/templates/custom-resources.yaml is not available
```

This is helm 2.6.1 on k8s 1.7.5

**Comment by lachie83** [comment]
Seeing the following in tiller logs
```
[tiller] 2017/10/02 07:47:40 preparing install for istio
[storage] 2017/10/02 07:47:40 getting release history for "istio"
[tiller] 2017/10/02 07:47:40 rendering istio chart using values
[tiller] 2017/10/02 07:47:40 failed install prepare step: apiVersion "config.istio.io/v1alpha2" in istio/templates/custom-resources.yaml is not available
```

**Comment by bacongobbler** [comment]
The proper annotation is actually `helm.sh/hookWeight`, not `helm.sh/hook-weight`. Your hooks don't have a weight assigned to them :)

Perhaps this is something we should capture in `helm lint` as I've seen this occur more than once.

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/helm/commit/05d0fcb774d8134b49e60587f4dd7db98c8ef7b7

**Comment by lachie83** [comment]
Let's update the docs too -- https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md

**Comment by unguiculus** [comment]
`helm.sh/hook-weight` is correct. The mentioned commit above is the original one in the PR. It was changed by my review.

https://github.com/kubernetes/helm/pull/2157#issuecomment-290982046

https://github.com/kubernetes/helm/blob/master/pkg/hooks/hooks.go#L27

**Comment by bacongobbler** [comment]
Huh, so it did. My bad. https://github.com/kubernetes/helm/commit/b9ef8dbe563e6626c047d1cf91b1367ac7f087c2#diff-4ce0c4408808dad0b46844b92388f205
