### ISSUE TITLE
Support the use of vanilla kubernetes manifests to deploy.

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/helm#3]
I want to be able to deploy this like I do other systems in Kubernetes via declarative config in kubectl create (e.g., without requiring local daemons/binaries running in a specialized local environment).

**Comment by jackgr** [comment]
Great suggestion. Thanks, Chris.

**Comment by vaikas-google** [comment]
I think the new streamlined getting started process takes care of this? Chris can you take a look and then we can close if that's the case.

**Comment by technosophos** [comment]
This is now done.
