### ISSUE TITLE
Code consolidation opportunity in pkg/chartutils/requirements.go?

### ISSUE THREAD

**Issue by ljnelson** [kubernetes/helm#3004]
I think—I am not sure, and am no kind of Go expert, so feel free to close this issue if I am mistaken—that [this block in `coalesceValues`](https://github.com/kubernetes/helm/blob/v2.6.1/pkg/chartutil/values.go#L281-L303) can simply become a call to [`coalesceTables`](https://github.com/kubernetes/helm/blob/v2.6.1/pkg/chartutil/values.go#L310-L332), reducing duplication.

Filed per @jascott1's request.

**Comment by jascott1** [comment]
@ljnelson Thanks for pointing this out during your investigation of the code base. Im going to label as refactor so we can take a look and see if we can remove some code.
