### ISSUE TITLE
Unable to create symlinks

### ISSUE THREAD

**Issue by odino** [kubernetes/helm#3007]
Ahoi!

Since 2.6.2 we are unable to create symlinks in the charts anymore -- any idea?

If we add a symlink on the root of the chart (ie. `ln -s /tmp env`) and try to install the chart I'll get an error:

```
Error: error reading env: read /path/to/chart/env: is a directory
```

The same chart would work alright with 1.6.1.

PS. I have a test chart to reproduce the issue if you want to have a look, but you can literally just `ln -s` in an existing chart to reproduce.

EDIT: I assume we stopped supporting symlinks with [this](https://github.com/kubernetes/helm/pull/2938/files) :)

**Comment by redbaron** [comment]
Yes, going to be interesting how that feature can be reimplemented without looking "too similar" to the  implementation which facebook had.

**Comment by bacongobbler** [comment]
Yes, I mentioned the reasoning behind this in the v2.6.2 release notes. The previous ticket has been re-opened.

Let’s keep the discussion rolling along in #1639. Thanks!

**Comment by bacongobbler** [comment]
Release notes: https://github.com/kubernetes/helm/releases/tag/v2.6.2
