### ISSUE TITLE
Helm install with specific chart names not working as expected.

### ISSUE THREAD

**Issue by lachie83** [kubernetes/helm#3009]
k8s 1.7.6
helm 2.6.2

```
$ helm search istio -l
NAME           	VERSION     	DESCRIPTION
incubator/istio	0.2.7-chart2	Istio Helm chart for Kubernetes
incubator/istio	0.2.7-chart1	Istio Helm chart for Kubernetes
incubator/istio	0.2.6-chart1	Istio Helm chart for Kubernetes
incubator/istio	0.1.6-chart6	Istio Helm chart for Kubernetes
incubator/istio	0.1.6-chart5	Istio Helm chart for Kubernetes
incubator/istio	0.1.6-chart4	Istio Helm chart for Kubernetes
incubator/istio	0.1.6-chart3	Istio Helm chart for Kubernetes
incubator/istio	0.1.6-chart2	Istio Helm chart for Kubernetes
incubator/istio	0.1.6-chart1	Istio Helm chart for Kubernetes
```

```
$ helm install incubator/istio --dry-run --debug
[debug] Created tunnel using local port: '63563'

[debug] SERVER: "localhost:63563"

[debug] Original chart version: ""
Error: chart "istio" matching  not found in incubator index. (try 'helm repo update'). No chart version found for istio-
```

```
$ helm install incubator/istio --version 0.2.7-chart2 --dry-run --debug
[debug] Created tunnel using local port: '63625'

[debug] SERVER: "localhost:63625"

[debug] Original chart version: "0.2.7-chart2"
[debug] Fetched incubator/istio to /Users/laevenso/.helm/cache/archive/istio-0.2.7-chart2.tgz

[debug] CHART PATH: /Users/laevenso/.helm/cache/archive/istio-0.2.7-chart2.tgz
```

**Comment by lachie83** [comment]
Looks like there's an issue in determining the latest version. Using --devel works

```
helm install incubator/istio --devel --dry-run --debug
[debug] Created tunnel using local port: '64342'

[debug] SERVER: "localhost:64342"

[debug] Original chart version: ""
[debug] setting version to >0.0.0-a
[debug] Fetched incubator/istio to /Users/laevenso/.helm/cache/archive/istio-0.2.7-chart2.tgz

[debug] CHART PATH: /Users/laevenso/.helm/cache/archive/istio-0.2.7-chart2.tgz
```

**Comment by lachie83** [comment]
cc @viglesiasce

**Comment by lachie83** [comment]
I worked with @mattfarina on looking into this. The dash in the version denotes a pre-release and hence won't be captured by a default install. Using the --devel tag will install all pre-releases.  We need to go back to the drawing board on how we symver this chart.

**Comment by ldemailly** [comment]
thanks for looking into this, is there another character that is allowed and works differently ?
I suppose once the helm works well you can drop the -chartN and it becomes "final" for that istio release

there will be a 0.2.8 soon after 0.2.7 on istio side

or we drop the sync completely and use 1.0.N for helm ?

or maybe you can support 4 digits ? 0.2.7.1 0.2.7.2... ?

**Comment by lachie83** [comment]
Take a look at semver v2 spec. http://semver.org/ That's what helm implements for chart versioning

**Comment by ldemailly** [comment]
I need to write a v3 when I get around to it :-)

in the meantime let's do -pre1 -pre2 ... until the next version of istio is almost ready and we promote the last -preN chart to stable
(but then if it turns out to have even 1 small helm specific bug, we're toast...)

that or decouple the 2 but using a very different version range for helm than istio to try to avoid confusion (to be honest I don't like that option because I remember the users talking about having installed istio 0.3.0 when helm had that while it was istio 0.1.6...)

**Comment by unguiculus** [comment]
I would just decouple the two versions and use normal semantic versioning, but I guess my opinion is not very popular here. Maybe we need to better explain `appVersion` vs. `version`. I think Istio is the only chart that is doing this -chartN suffix thing. I've always found that weird.

**Comment by thomastaylor312** [comment]
So is there any outstanding fixes or feature adds here? Want to make sure this gets tagged appropriately 🙂

**Comment by lachie83** [comment]
Thanks Taylor. The referenced ticket is what needs to happen.

**Comment by thomastaylor312** [comment]
Ok, thanks for letting me know. Are people in this issue ok with closing this in favor of #3010 or would you like to me keep this open?

**Comment by lachie83** [comment]
This can be closed Thanks @thomastaylor312
