### ISSUE TITLE
helm init installs incompatible version of tiller 

### ISSUE THREAD

**Issue by matt-deboer** [kubernetes/helm#3012]
**Helm Client**: 2.6.2
**OS**: OSX 10.12.3

Running `helm init ...` results in tiller version `2.6.1` being installed, which is not entirely compatible with client `2.6.2`. 
(Helm install will fail for users without permissions to create/put in kube-system)

**Comment by bacongobbler** [comment]
Thanks @matt-deboer! I'll see if I can verify this and get back to you.

**Comment by bacongobbler** [comment]
Hmm, I was unable to reproduce this. I just booted a fresh minikube cluster and ran `helm init` with v2.6.2 and got a v2.6.2 tiller.

<img width="711" alt="helm-version" src="https://user-images.githubusercontent.com/1360539/31299688-86e96bbe-aaa4-11e7-9f0e-fdfa71cb0629.PNG">

Can you demonstrate your setup and/or try again? `helm reset && helm init` should do the trick.

**Comment by matt-deboer** [comment]
you're right; my mistake
