### ISSUE TITLE
Add patch field to .Capabilities.KubeVersion

### ISSUE THREAD

**Issue by prat0318** [kubernetes/helm#3013]
There is a use-case where cadvisor endpoint has changed between pre 1.7.2 and post 1.7.3. I want to put prometheus endpoints accordingly. We have `major` and `minor` fields, it will be useful to also get `patch` field.

**Comment by bacongobbler** [comment]
Hey! This is a great idea, but it would have to be contributed upstream as kubernetes's core libraries only provide [the major and minor](https://github.com/kubernetes/apimachinery/blob/3b05bbfa0a45413bfa184edbf9af617e277962fb/pkg/version/types.go#L22-L32) version in the API. Would you mind opening a ticket upstream first? Once that's been implemented, we can then take advantage of that new feature. :)

**Comment by prat0318** [comment]
I have cut an issue upstream #kubernetes/kubernetes/53582
