### ISSUE TITLE
Error: transport is closing

### ISSUE THREAD

**Issue by hobti01** [kubernetes/helm#3015]
I've seen a few issues with similar timeout situations, but no resolution.

I cannot reproduce this 100%, but it happens regularly on our CI system.  What additional data can I gather to isolate the cause of this issue?

I do not think this is a timeout issue, the error seems to happen right away.

```
helm version --short
Client: v2.6.2+gbe3ae4e
Server: v2.6.2+gbe3ae4e
E1006 20:27:30.237578     128 portforward.go:178] lost connection to pod
Error: transport is closing
```

```
helm upgrade --install ...
Release "my-release" does not exist. Installing it now.
E1007 13:54:06.914646     164 portforward.go:178] lost connection to pod
Error: transport is closing
```

```
helm upgrade --install ...
Release "my-release" does not exist. Installing it now.
E1006 23:50:34.576467     174 portforward.go:178] lost connection to pod
Error: transport is closing
```

**Comment by thomastaylor312** [comment]
@hobti01 Can you give me a few more details about what environment your cluster is running in? We had the same problem in CI and it turned out to be a problem with AWS ELB timeouts

**Comment by hobti01** [comment]
Our CI is GitLab.com.  Helm deployment is from the GitLab shared runners in Digital Ocean and our own dedicated runners within our Kubernetes cluster(s) in AWS.

After many trials with different timeout settings for helm and the ELB and more tiller log analysis...

- The job relies upon a ConfigMap that is created during the deployment, but the job is a `pre-install` job. This issue is already identified, and makes sense in hindsight. https://github.com/kubernetes/helm/issues/2622
- The race condition between helm and the ELB timeouts determines the error message to the client:
    - If helm times out first: `Error: timed out waiting for the condition`
    - If ELB times out first: `Error: transport is closing`

I'm not sure how this ever succeeded, but I will change the approach to not use a ConfigMap with a `pre-install` Job.

A suggestion would be to improve the error messages, but I'm happy to close this issue.

**Comment by thomastaylor312** [comment]
@hobti01 If you would like to see some better error messages, feel free to open a specific feature request for it and tag me in it (or ping on slack). I'll close this for now. Thank you for getting back to us!

**Comment by kostyrev** [comment]
@thomastaylor312 I don't get it. What ELB are you talking about?

**Comment by thomastaylor312** [comment]
@kostyrev I was asking if the cluster was running in AWS because we had seen issues with ELBs killing connections from your local Helm client to Tiller running in the cluster

**Comment by kostyrev** [comment]
yeah, thanks
After some browsing I've figured it out that you were talking about ELB in front of API server.  
And that's was the case for me. By default kops sets up 300 seconds. After increasing idle_timeout the problem was solved for me.
