### ISSUE TITLE
Invalid data type

### ISSUE THREAD

**Issue by Nin-0** [kubernetes/helm#3023]
If you run `helm upgrade --install ` and provide a different datatype for an existing value, helm breaks the deployment.

Example:

You have an existing deployment which is running. It contains  

values.yaml
```
image:
  repository: <my repository>
  tag: <my tag eg. v0.0.1>
```
which is refered in a deployment file:

deployment.yaml

```
image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

If values and deployment file are changed to:

values.yaml

```
image: <my repository>:<my tag eg. v0.0.1>
```
deployment.yaml

```
image: "{{ .Values.image }}"
```
Helm breaks the next deployment. In Kubernetes you can see

`map[repository:<repository> tag:<tag>]`

as value for image with

`kubectl get deployment <deployment> -o yaml`

kubernetes is not able to pull the image, now.

Error occurs with:

Client: v2.6.0
Server: v2.6.0

@jayme-github 
@wjkohnen

**Comment by bacongobbler** [comment]
What did you provide with `helm upgrade --install`? I think you have to discard the old values you provided and use `--set image=myrepo:tag` to fix this.

**Comment by Nin-0** [comment]
I didn't provide any values with `--set`, I only changed values in `values.yaml` and `deployment.yaml`.
