### ISSUE TITLE
helm lint fails on a chart with a 'fail' directive in a template

### ISSUE THREAD

**Issue by arschles** [kubernetes/helm#3026]
If you do the following:

1. run `helm create failchart`
2. Add the following label to the `templates/deployment.yaml` manifest:

```yaml
failure: {{ fail "this is a failure!" }}
```

3. run `helm lint failchart`

The `helm lint` command returns a failure that looks like:

```console
[ERROR] templates/: render error in "failchart/templates/deployment.yaml": template: failchart/templates/deployment.yaml:7:16: executing "failchart/templates/deployment.yaml" at <fail "this is a fail...>: error calling fail: this is a failure!
```

I believe that the linter shouldn't fail if there is a `fail` directive in the template, since it is still a valid template.

I've attached a `failchart.zip` that reproduces the failure. Simply unzip it and run `helm lint failchart`. (Github wouldn't let me attach a `.tgz` packaged chart to this issue 😦 )

[failchart.zip](https://github.com/kubernetes/helm/files/1377300/failchart.zip)

**Comment by bacongobbler** [comment]
This also occurs when `required` is in the chart too. #2347

**Comment by vDMG** [comment]
We have the exactly same issue. 
which is really anoying because we can't raise some errors and lint our helm charts
/reopen

**Comment by bridgetkromhout** [comment]
Hi, @vDMG - this is a very old issue. Can you please [open a new issue](https://github.com/helm/helm/issues/new) and give us the requested info? You can mention https://github.com/helm/helm/issues/3026 but please go into more detail about your environment, version, etc. Thanks.

**Comment by SekretOne** [comment]
@vDMG I imagine you're having an issue where you can't lint if your default values would result in a fail?

I found a solution to this problem by creating a separate values file that has a passing example and performing the lint while passing in the values of the valid result.

e.g.

```shell
helm lint failchart values=values.passing.yaml
```
