### ISSUE TITLE
[Question] Are there plans to release an SDK for creating custom clients for Tiller ?

### ISSUE THREAD

**Issue by migueleliasweb** [kubernetes/helm#3031]
Hi guys,

I recently came across Helm and immediately I found it awesome. Although it's awesomeness and the fact it comes with plugin support it would be good to have a way to create custom clients with an SDK instead of just running it through the CLI. Don't you guys agree ? Are there plans to release an SDK for Tiller ?

**Comment by nolith** [comment]
I was thinking the same, but given that `helm` interacts with `tiller` through gRPC, you should be able to build your own client using `_proto` folder.

The question is more about long/mid-term stability of the gRPC api.

**Comment by bacongobbler** [comment]
For people writing their apps in Go, `k8s.io/helm/pkg` has been very stable in terms of backwards compatibility. Multiple projects like [Draft](https://github.com/Azure/draft) and [chartmuseum](https://github.com/chartmuseum/chartmuseum) have been using Helm's packages with great success.

There have not been any other client libraries released in differing languages like Ruby, but @nolith is on the right track if all you want to do is to interface directly with Tiller.

disclaimer: I'm one of the core contributors to draft as well as a core maintainer to Helm, so my perspective on how easy it is to write an app against helm's packages may be slightly biased. :)

**Comment by bacongobbler** [comment]
Marking this as "help wanted" so it's clear to others that this should be a community effort. We don't pretend to know how to write good client libs for scala/rust for example. :)

**Comment by migueleliasweb** [comment]
Hey guys ! Thanks for the awesome feedback !

I started digging to the gRPC implementation is "fairly" easy to use. I think the case in here would be creating some documentation for creating custom clients using this approach. Do you guys want some help with that ? After uncovering all the secrets I could write a small  "first-steps" to create custom implementation for Tiller clients =]. What do you guys think ?

**Comment by nolith** [comment]
hi @migueleliasweb did you find a way to handle `kubectl port-forward` without using `kubernetes-client-go` or `kubectl` binary?

I did [this](https://gitlab.com/nolith/hapi-helm) in ruby but given the very tight schedule I have at the moment I decide to put it on hold and move my first iteration for `tiller` integration wrapping `helm` binary calls.

**Comment by migueleliasweb** [comment]
What's up @nolith ! I'm not that far with the implementations but I hope within a couple days I can wrap up what I have learned so far into some kind of step-by-step markdown and share with you guys !

**Comment by philipbjorge** [comment]
grpc is fairly easy to use.

For anyone looking to generate grpc for python:
```
git clone https://github.com/kubernetes/helm ./helm
pushd helm
git checkout tags/v${1}
popd

python -m grpc_tools.protoc -I helm/_proto --python_out=. --grpc_python_out=. helm/_proto/hapi/chart/*
python -m grpc_tools.protoc -I helm/_proto --python_out=. --grpc_python_out=. helm/_proto/hapi/services/*
python -m grpc_tools.protoc -I helm/_proto --python_out=. --grpc_python_out=. helm/_proto/hapi/release/*
python -m grpc_tools.protoc -I helm/_proto --python_out=. --grpc_python_out=. helm/_proto/hapi/version/*

```

The armada project is a really great example of building custom tooling around helm.
https://github.com/att-comdev/armada

**Comment by Nitrogenycs** [comment]
There is also https://github.com/appscode/swift which is a JSON/HTTP gateway to tiller. I use this for something like my own client.

**Comment by bacongobbler** [comment]
Closing question as answered :)

**Comment by robel-yemane** [comment]
> What's up @nolith ! I'm not that far with the implementations but I hope within a couple days I can wrap up what I have learned so far into some kind of step-by-step markdown and share with you guys !

Hey @migueleliasweb  any updates on this? I'm trying to write a Go App that interfaces with Helm/Tiller and programmatically get release details etc.., but stuck on working out the Helm API

**Comment by bacongobbler** [comment]
Does the example in https://github.com/helm/helm/issues/3663#issuecomment-372436053 help at all?

**Comment by robel-yemane** [comment]
Thanks @bacongobbler

**Comment by migueleliasweb** [comment]
@robel-yemane Sup, I'm not actively working on it anymore. Sry about that.

I gave a try with a Go implementation and got fairly far by importing a few modules from Helm itself instead of using the gRPC client directly. But in the end I ended up not using Tiller and just called helm to render the templates.
