### ISSUE TITLE
throw more specific invalid repo url error during helm dep up

### ISSUE THREAD

**Issue by magicalbanana** [kubernetes/helm#3032]
So I'm running this:

`helm dep up`

and it's returning an error:

`No requirements found in /Users/momo/src/github.com/momo/common-helm-charts/storage/postgresql-postgis/charts.`

Here's my chart:

```
total 24
drwxr-xr-x  6 momo  staff  204 Oct 12 19:32 .
drwxr-xr-x  6 momo  staff  204 Oct 12 19:32 ..
-rw-r--r--  1 momo  staff  412 Oct 12 19:32 Chart.yaml
drwxr-xr-x  2 momo  staff   68 Oct 12 14:05 charts
-rw-r--r--  1 momo  staff  117 Oct 12 19:20 requirements.yaml
-rw-r--r--  1 momo  staff   84 Oct 12 13:58 values.yaml
```

`charts/` is empty.

**Comment by michelleN** [comment]
@magicalbanana What version of helm are you running?

**Comment by magicalbanana** [comment]
I figured it out. The issue was that I wasn't using the right repository URL. I just wish it returned a meaningful error.

**Comment by michelleN** [comment]
@magicalbanana glad you figured it out. 
What would you wanted the error to say for you to debug faster?

**Comment by magicalbanana** [comment]
Invalid repository URL would be nice.

**Comment by michelleN** [comment]
Alrighty and what version of helm are you running?

**Comment by magicalbanana** [comment]
```
$ helm version
Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
```

**Comment by michelleN** [comment]
Alrighty. Thanks for submitting your issue. We can look into throwing a more specific error in this case as you suggested. I'll edit the name of this issue and label correctly. Thanks again.

**Comment by franzbeltran** [comment]
Hi @michelleN , I'm trying to replicate this issue and couldn't see the error. May I know the incorrect repository URL you've used?

**Comment by michelleN** [comment]
Hey @franzbeltran. I was not the one running into this issue. 

What error are you seeing?

**Comment by franzbeltran** [comment]
Oh sorry I didn't notice that @michelleN . Here's the error:
`Error: no repository definition...`

Tagging @magicalbanana , what's the incorrect repository URL that you used?

**Comment by michelleN** [comment]
@franzbeltran 
That error feels vague too and could be more specific. What repo url are you using?
