### ISSUE TITLE
Release goes to failed state but not rollback

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/helm#3038]
- Install a chart that specifies a NodePort. For my example, I used ibm-microservicebuilder-pipeline, but really this should be the same for any chart.
- Specify a NodePort that already exists (the default is 31000 in MSB and if you don't change it, the second deployment will have a conflict).
- Because the NodePort already exists, then `helm install` will be failed.
- But after changing the port, and re-install again, tiller report the release already exist.
- I had to update the name and create a second release; even though the original error message told me the deployment failed. 

Does tiller have some plan to rollback a failed deployment, so that my second install can still be succeed even with the same name as the first failed one?

**Comment by michelleN** [comment]
Hey @gyliu513 - thanks for submitting this issue.

There are two ways of handling this kind of situation. If you'd like to re-use that release name, you can:
1. Use the `--replace` flag when re-installing an initially failed chart. Your command would look like this: `helm install mychart --name <release-name> --replace`
From the helm install help test:
```
--replace   re-use the given name, even if that name is already used. This is unsafe in production
```

2.  You can upgrade a failed release to the correct version. This will also preserve history of your releases so you can see that the first one failed.
```console
$ helm upgrade [release-name] [path to updated chart]
```

Let me know if that helps or if you have any other questions.

**Comment by gyliu513** [comment]
Thanks @michelleN , it works!
