### ISSUE TITLE
support for .json files in templates and environments

### ISSUE THREAD

**Issue by robertlabrie** [kubernetes/helm#3044]
I'm probably opening an old can of worms here, but is there any possibility of treating `.json` files as first class citizens in helm? I prefer JSON over YML and while I can put valid JSON in `whatever.yaml` when I mentioned it one of my colleagues suggested that "anyone who does that should be taken out back and shot"

**Comment by bacongobbler** [comment]
related ticket with a larger amount of background context: https://github.com/kubernetes/helm/issues/2577

**Comment by bacongobbler** [comment]
closing as a dupe of #2577
