### ISSUE TITLE
.helmignore and .Files.Get

### ISSUE THREAD

**Issue by leo-baltus** [kubernetes/helm#3050]
We use `{{ .Files.Get "foo/bar" }}` to read information from files we use during install and upgrade we do not want to package these files however on `helm package` so we add them to `.helmignore` . It seems however that if `foo/` is in `.helmignore` it no longer is available for .Files.Get.

I can tell you it took me some time to figure this out. So I assume this is a bug not a feature?

In anyway it is not mentioned in the documentation I Read. What I did found is:
 
- [this](https://github.com/kubernetes/helm/blob/1fa853959ccbdb1c2834bd625f3655b2a9e7a4cb/docs/charts.md) says 'non-special files'
- [this](https://github.com/kubernetes/helm/blob/1aafaf84fb2dbed0a24e24e7b5a6a0f0a1454dc5/docs/chart_template_guide/accessing_files.md) says 'for security reasons'

Both seem rather vague and could use some elaboration. So is this also driven by `.helmignore`?

we are at v2.6.1

**Comment by mattfarina** [comment]
According to the docs:
> .helmignore   # Contains patterns to ignore when packaging Helm charts.

I wouldn't expect `.Files.Get` to impact files being listed there.

But, it appears that files in the `.helmignore` are filtered out. See the source of the [`chartutil.LoadDir` function](https://github.com/kubernetes/helm/blob/1aafaf84fb2dbed0a24e24e7b5a6a0f0a1454dc5/pkg/chartutil/load.go#L219). What's loaded here appears to be what [`.Files.Get`](https://github.com/kubernetes/helm/blob/1aafaf84fb2dbed0a24e24e7b5a6a0f0a1454dc5/pkg/chartutil/files.go#L65) contains.

An update to the docs would be useful.

In the interest of finding another way to solve this... Is there a reason you aren't passing this information as a configmap and then reading it that way? This may be a more k8s way of doing it, too.

**Comment by leo-baltus** [comment]
In fact I am populating secrets with it. Sorry for not being clear about that.

**Comment by mattfarina** [comment]
@leo-baltus To restate, you have files in the chart you don't want to be packaged but you want to read the contents of them into secrets. Is that right?

If that is the case, it might be worth adding a `read` function that uses something like [`ioutil.ReadFile`](https://golang.org/pkg/io/ioutil/#ReadFile) to [sprig](https://github.com/masterminds/sprig).

@technosophos any thoughts?

**Comment by eicnix** [comment]
@leo-baltus The templating process of helm is executed at the backend using Tiller. Therefore Tiller needs all files that should be loaded via `.Files.Get`. 
If you add a File to `.helmignore` it will neither be packaged nor send to Tiller for processing and can therefore not be loaded with `.Files.Get`. 

If you don't want to package this file you could pass the contents as a file as a value during the installation with `--set=secretfile=...`.

**Comment by leo-baltus** [comment]
@eicnix setting `--set=secretfile=...` would not eliminate the need to read the file at some point, since it won't be in tiller, it can't be read I suppose.

I saw that there was work done to support secrets in helm natively. A pointer to how to use this would be useful to me.

**Comment by bacongobbler** [comment]
The secret storage backend won't fix this since the process to install a chart is the same as it is with the default storage backend (configmap).

@mattfarina that's exactly how [`.Files.Get` works](https://github.com/kubernetes/helm/blob/d815310928b0ea77382e34b3b49a425adcea5f77/pkg/chartutil/files.go#L62-L70) :)

@eicnix's suggestion is the best way to approach this. How we used to pass in "secret" files that we didn't want to package in the public chart was through `--set`. For example, if I wanted to pass in the contents of a file, we would do:

```
$ helm install mychart --set secretconfig="$(base64 mysecretfile.cfg)"
```

Then on the other end we would base64 decode the value.

**Comment by Antiarchitect** [comment]
@bacongobbler Can this be reopened. I have a big project with files that need to be read by template functions to form Secrets and Configmaps but their paths can be dynamic and sophisticated and there are big extra files in those folders that just exceed the release size. Anyway, I do not want a directory content to be packed into release, but I want to form my Secrets and CM from those files.
