### ISSUE TITLE
Ruleset for helm lint

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#3051]
As a potential feature for `helm lint` in v3 is to move to a ruleset. Using a ruleset is common in linters to enable some amount of configuration to linting. For example, see the ESLint [config file](https://eslint.org/docs/user-guide/configuring#extending-configuration-files) and [rules](https://eslint.org/docs/rules/).

Note, this is a follow-up from the Helm meeting on Oct. 19, 2017.

cc: @michelleN

**Comment by bacongobbler** [comment]
It turns out that this request already existed in the form of #2694, so I'm going to close this in favour of the older ticket. We can track discussion over there moving forward :) Thanks for bringing this up @mattfarina!
