### ISSUE TITLE
Use of tpl function breaks .Template

### ISSUE THREAD

**Issue by mparry** [kubernetes/helm#3054]
The `tpl` function (added in #1978) seems to break `.Template`, leaving `BasePath` empty and `Name` set to 'aaa_template'.

[Here is a minimal chart](https://github.com/kubernetes/helm/files/1406896/tpl-bug.zip) that demonstrates the problem. Here's the output:

```
> helm --debug install --dry-run --set anything=1 tpl-bug

apiVersion: v1
kind: ConfigMap
data:
  triggerBug: 1
  basePath:
  name: aaa_template
```

If you remove L4 (ie. `triggerBug`) in configmap.yaml then you get more sensible output:

```
> helm --debug install --dry-run tpl-bug

apiVersion: v1
kind: ConfigMap
data:
  basePath: tpl-bug/templates
  name: tpl-bug/templates/configmap.yaml
```

Incidentally, `tpl` doesn't seem to be mentioned in the documentation anywhere at the moment.

**Comment by eicnix** [comment]
@mparry I wrote the `tpl` function and can take a look at it in the next days.

**Comment by thomastaylor312** [comment]
Looks like this is a bug based on the PR. Tagging as a bug and pulling into 2.7.1

**Comment by alexkreidler** [comment]
Any updates?
