### ISSUE TITLE
Proposal: Add url to chart maintainer details

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#3056]
There are times you want a URL to a package maintainer.

For example, in Monocular (as seen on Kubeapps.com) the name is taken and turned into a url to a location on GitHub (see [issue about it as a bug](kubernetes-helm/monocular/issues/382)). This doesn't work for a variety of reasons.

It would be nice to use a URL to a maintainers chosen location. This could even be used as an alternative to an email address for those who don't want to give it out. See the monocular issue for a couple example of hiding email addresses.

The proposal is to add a URL field alongside the email one...

https://github.com/kubernetes/helm/blob/3fc189d688fdfd4c0423fa6888a7762f8cde2381/_proto/hapi/chart/metadata.proto#L21-L28

**Comment by bacongobbler** [comment]
I could see the value in a URL field like "report-bugs-to". I've seen that format used in other places where the maintainers want to point users to file bug reports or further discussion over, such as a mailing list or a forum.

For example, [PEP 1](https://www.python.org/dev/peps/pep-0001/) describes the "Discussions-To" field in PEPs as

> PEP review and resolution may also occur on a list other than python-dev (for example, distutils-sig for packaging related PEPs that don't immediately affect the standard library). In this case, the "Discussions-To" heading in the PEP will identify the appropriate alternative list where discussion, review and pronouncement on the PEP will occur.

Would that help resolve the issue for monocular?

**Comment by bacongobbler** [comment]
Another valid use case:

We (as the former Deis team) set up an engineering@deis.com email address for users to file bug reports with the charts to satisfy this field. However, we would prefer to point users over to https://github.com/deis/workflow/issues instead.

Does that seem to satisfy the requirements? :)

**Comment by prydonius** [comment]
Just to add some context, the reason we point to a GitHub profile was to provide a better experience than a mailto link in the case of the stable/incubator repos. The Charts team decided on using GitHub IDs for maintainer names, but this is being implemented gradually and so we currently have some broken links.

I do feel that a URL field will be useful and agree with @bacongobbler's usecases. +1 for adding url as an optional field to the maintainer object.
