### ISSUE TITLE
relative URL in index.yaml

### ISSUE THREAD

**Issue by kraney** [kubernetes/helm#3057]
Index.yaml currently requires all of the source URLs to be full URLs. When sources are hosted locally on the same webserver, it should be possible to just specify a relative URL. For example
```
urls
- chart-0.0.0.tgz
```
would imply
```
urls
- http://repository/path/containing/index/chart-0.0.0.tgz
```

This would make much more sense than having a relative path cause helm to look under the local filesystem, as it does now.

**Comment by mattfarina** [comment]
@kraney A couple questions...

1. Since the index.yaml file is generated does it matter if it's relative or absolute? Or, do you have a different use case than using helm or something like chartmuseum to generate the index.yaml file?
2. Helm supports the package not being in the same location as the index. How would you propose differentiating between the two?

**Comment by kraney** [comment]
For my use case, it makes a difference. I have a build pipeline that will package the charts and create index.yaml. Later, this is deployed to an S3 bucket. I don't know the URL for the bucket at the time the index.yaml is generated. I only find out later.

Differentiating between a package in the same location as the index and being elsewhere is simple. If it's elsewhere, you need to use a full URL. If it's relative, it's implicitly in the same location as index.yaml. "Relative" should mean relative to the index.yaml, essentially. Whatever directory / URL it's in, package paths are relative to that. If the packages cannot be found relative to that, then don't use a relative path, use an absolute path. Right now, if you call helm repo index without specifying a URL, it generates relative paths, but what those relative paths mean is undefined. The resulting index.yaml doesn't work, and fails with unhelpful errors.
