### ISSUE TITLE
nicer UX when using`helm install` and missing `required` fields

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#3063]
It would be nice to provide a better UX if a user misses required values from a chart when trying to install it. e.g.

```$ helm install target/my-helm.tar.gz
Error: render error in "fabric8-jenkins-github/templates/keycloak-configmap.yaml": template: fabric8-jenkins-github/templates/keycloak-configmap.yaml:167:32: executing "fabric8-jenkins-github/templates/keycloak-configmap.yaml" at <required "A valid .V...>: error calling required: A valid .Values.github_oauth_client_secret entry required!
```

thats quite a verbose output that takes a user a while to parse. It might be better to have a more clear set of output to help users. e.g. something vaguely like:
```$ helm install target/my-helm.tar.gz
Error: missing required values:
  * github_oauth_client_id
  * github_oauth_client_secret

To specify the values try:
helm install -set github_oauth_client_id=value1,github_oauth_client_secret=value2 target/my-helm.tar.gz
```

We could even have an interactive mode that prompted the user to enter the missing values interactively. We'd just require some way to mark values as being required.

I wonder, to be able to specify required values and possibly even to add validation to the values; if we should consider allowing an optional JSON Schema document (or YAML Schema ;) to be included in a chart - or something along those lines so that the helm CLI can know what values are required and validate them a little more before they get applied?

**Comment by eicnix** [comment]
There is a proposal to add a JsonSchema to the values of a Chart: https://github.com/kubernetes/helm/issues/2431

Having a schema would make the validation of values before the rendering process possible.
