### ISSUE TITLE
Incomplete Changelog

### ISSUE THREAD

**Issue by philipbjorge** [kubernetes/helm#3066]
https://github.com/kubernetes/helm/pull/2636
I'm pretty sure this made the cut for 2.7.0 but is not listed in the changelog.

https://github.com/kubernetes/helm/commit/734b1245772ff4e8319e3648646e1c0f1d797d87
Hook delete policy also got missed.

These are some of the biggest features IMO.

**Comment by bacongobbler** [comment]
Indeed there were a lot of changes that were missed.

Full changelog is available here: https://github.com/kubernetes/helm/compare/v2.6.2...v2.7.0

I'm not on the machine that was used to generate the changelog but I'll post the command here tomorrow. We can then come up with a better git alias for future releases and document it via #3027.
