### ISSUE TITLE
Helm upgrade -i will "succeed" after failing on duplicate resource.

### ISSUE THREAD

**Issue by tcolgate** [kubernetes/helm#3068]
## What happens

create a service named myservice in a cluster.

create a chart that attempts to create/manage a service named myservice.

`helm upgrade -i ./chart mychart`

First run will fail. The release status will be "FAILED". No pods or other resources will be created.

Now run `helm upgrade -i ./chart mychart` again. The deploy now succeeds, but myservice is not updated and does not match the requested service in the release. release status is now DEPLOYED.

## What should happen.

The second upgrade -i should also fail. It should be clear to the user that the api objects are not being successfully managed.

**Comment by bacongobbler** [comment]
fixed via #3097
