### ISSUE TITLE
File not found when doing local install from folder

### ISSUE THREAD

**Issue by lastonoga** [kubernetes/helm#3080]
Hey there,

helm version
```
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

I cant do local install at all. From repos it works good.

For example i try to make that one
```
helm install --name prometheus-operator --set rbacEnable=true --namespace=monitoring helm/prometheus-operator
```

There is an error
```
Error: file "helm/prometheus-operator" not found
```

But `ls helm/prometheus-operator` shows 
```
Chart.yaml  README.md  templates  values.yaml
```

**Comment by bacongobbler** [comment]
Can you try `./helm/Prometheus-operator` instead? Helm recognizes `./` as a reference to a local file path. Let me know if that works.

**Comment by bacongobbler** [comment]
I also noticed that your client version is **very** out of date. Try updating that to v2.7.0 and try again.

**Comment by lastonoga** [comment]
@bacongobbler  I tried, no results. Well, i searched the whole universe and did not found how to update client (there is a part in documentation only about updating tiller)

**Comment by bacongobbler** [comment]
Just fetch one of the releases from https://github.com/kubernetes/helm/releases and put in in your path, Alternatively, if you're on macOS try `brew install kubernetes-helm`.

**Comment by lastonoga** [comment]
@bacongobbler Thanks, now everything is perfect!

**Comment by bacongobbler** [comment]
No problem :)
