### ISSUE TITLE
Question: should charts be mutable?

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#3084]
Repository `index.yaml` files contain a `digest` (hash) for a package. This works with provenance.

But, nothing stops an `index.yaml` file from updated to a new hash for a version and an updated package at the same version that matches. There's no checking or, and please correct me if I'm wrong, tracking of the hash for a version of a package.

I know systems like npm enforce immutable packages. For example, the npm documentation notes...

> Once a package is published with a given name and version, that specific name and version combination can never be used again

Debian has notes such as:

> It should be possible to reproduce, byte for byte, every build of every package in Debian.

and...

> Packages should build reproducibly, which for the purposes of this document [20] means that given
>
> * a version of a source package unpacked at a given path;
> ...

My consideration comes to security (you can check hashes/changes to hashes) and reproducibility (install the same chart in multiple environments... for testing, debugging, dev/test/prod workflows, etc).

Should charts be mutable or immutable?

cc: @kubernetes/charts-maintainers as you might be interested

**Comment by technosophos** [comment]
My view is that a chart+version _should_ be immutable, and any system that formalizes tracking of packages may comfortably proceed accordingly. (The provenance system was designed for this scenario and will NOT work in a mutable environment). More specifically, when `foo-1.2.3.tgz` is released, that version string is forever allocated to the snapshot of the contents of that file. If a package maintainer discovers that 1.2.3 has a fatal flaw, the solution is to release foo-1.2.4 (or 1.3.0, or whatever).

This is also why it is an operational error to modify the `values.yaml` file inside of a chart with specific configuration for your installation. You should supply an external `values.yaml` that overrides the in-chart version. The in-package values.yaml is the _default_ configuration, and modification of that constitutes a new version of the package.

Helm itself does not track state changes of helm index files and so on (neither, for that matter, do the apt-get, brew, npm, etc. toolchains). Enforcing immutability is an attribute of the chart release process for any given chart publisher.

Our view of this is not arbitrary. It's our best interpretation of the way other major packaging systems (such as Apt) work.

**Comment by ankushchadha** [comment]
Continuing the immutability topic -

Is it a good idea not to expose docker image tags as part of values.yaml? Exposing docker image tag as part of values.yaml means that a different version of a docker image can be deployed compared to what's specified as part of a chart. Traceability is lost and from a deployment perspective, it's not immutable.

It probably makes sense to specify docker image tags as part of values.yaml when the charts are being developed, but once the charts are final and published, then the flexibility of changing the docker image tag should be removed in favor of traceability.

**Comment by prydonius** [comment]
Interesting thoughts @ankushchadha, the main reason we decided to make image tags configurable is in cases where I want to point to a mirrored image in a private registry instead of the public one.

**Comment by unguiculus** [comment]
@ankushchadha I think we need to distinguish between immutability and configurability. The way you see it, no chart would be immutable because it can always be configured somehow. Even hard-coding the image tag may not help because tagged images can still be updated in the registry. I think immutability should just refer to taking a has from the chart.

**Comment by ankushchadha** [comment]
I agree, that we need to distinguish between immutability and configurability especially for released charts.

If a docker image changes, the app version changes. IMO, the app version should not be treated as a configuration. 

From traceability perspective, the image tag part of a chart should be set to a static tag instead of a dynamic tag. The other extreme is to use digest.

**Comment by mattfarina** [comment]
I think we're getting into the difference between a chart and a chart + passed in configuration. We want charts to be immutable. But, they are configurable. To make this more complicated let's look at an example. A value set on a release of a chart might be the number of replica sets. But, I might also want an outside tool to be able to alter that (e.g., kubectl). How does all of that work?

Since charts are configurable (which is useful) I think the part that's immutable is the chart package itself. Looking for mutated version can be used to check for security issues, etc.

**Comment by mattfarina** [comment]
To close this out...

As a general rule we're recommending immutable charts.
