### ISSUE TITLE
Dead link in side bar at https://docs.helm.sh

### ISSUE THREAD

**Issue by neil-ca-moore** [kubernetes/helm#3090]
If you visit https://docs.helm.sh and then click on "Helm Commands" followed by "Helm List" it doesn't work. The link is to https://docs.helm.sh/helm/#helm-rep-**listo** which doesn't exist.

I can't figure out how this is generated, not sure it is possible for me to fix it with a PR. I can't find any instance of the string "listo" anywhere

**Comment by bacongobbler** [comment]
https://github.com/helm/helm-www is the repository that generates the site, if you want to take a shot at fixing this bug.

**Comment by neil-ca-moore** [comment]
Thanks. See https://github.com/helm/helm-www/pull/62
