### ISSUE TITLE
[Question] Support for custom template functions in Helm?

### ISSUE THREAD

**Issue by craiganderson** [kubernetes/helm#3093]
If I have a need for custom template functions (beyond what's included in Go template language and the Sprig library), is modifying my Helm source code the only option? Or could such custom template functions be implemented in a Helm plugin or within a Helm chart?

Thanks.

**Comment by jascott1** [comment]
@craiganderson Other than creating additional helper templates, yes you are limited to the existing functions unless you hack in your own (not recommended).

**Comment by craiganderson** [comment]
Thanks, that answers my question.
