### ISSUE TITLE
Document RBAC conventions for charts

### ISSUE THREAD

**Issue by omkensey** [kubernetes/helm#3098]
With the move toward RBAC being on by default in more and more cluster installers, the convention seems to have appeared to control RBAC-related templates as follows:

```
rbac:
  create: [true|false]
  serviceAccountName: [string]
```

(see e.g. coreos/alb-ingress-controller#146)

This is not yet documented in Chart best practices, and it should be.  I'm happy to do the doc PR, but wanted to file an issue first to probe for consensus on whether the default value of `rbac.create` shoulfd be `true` or `false`.  Most charts using this convention seem to be defaulting to `false`, but my own opinion is that it should be `true`, based both on the direction Kubernetes installers are moving (kubeadm apparently turns on RBAC by default since 1.6, and others have done so since even earlier versions) and my own sense that the defaults should be secure unless there's a very good reason not to be.

**Comment by bacongobbler** [comment]
I just updated the title to reflect that this is for charts and not for tiller as seen in #3094.

**Comment by julianxhokaxhiu** [comment]
I agree on this. I am currently doing my first round on K8S 1.6 and I'm confused as well. I also think it should be `true` as using `kubeadm init` we get RBAC by default.

Isn't this the case? Please correct me if I am wrong.

**Comment by mgoodness** [comment]
Sound reasoning. Let's make `rbac.create=true` by default.

**Comment by mattfarina** [comment]
cc: @kubernetes/charts-maintainers

**Comment by omkensey** [comment]
Haven't seen anybody object to this so I'm thinking of writing it up later tonight.  Should it be its own section of the Best Practices guide, part of the Templates section, part of the Pods and Pod Specs section, or somewhere else entirely?

**Comment by prydonius** [comment]
@omkensey that would be great. I think this should probably be it's own section.
