### ISSUE TITLE
`helm create` conflicts with documentation on imagePullPolicy

### ISSUE THREAD

**Issue by omkensey** [kubernetes/helm#3099]
[Documentation about chart best practices](https://docs.helm.sh/chart_best_practices/#imagepullpolicy) says:

> The imagePullPolicy should default to an empty value, but allow users to override it:
> `imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}`

However, the example chart from `helm create` sets `image.pullPolicy` to IfNotPresent, which seems like a much more sensible default value.  Which is correct?  If the docs need updating I'm happy to submit that PR.

**Comment by jascott1** [comment]
@omkensey Good point. Its tricky since there is no one-size-fits-all. Rather then absolutely prescribe something we might explain more about the implications of setting a default and explain that `required` could be used.

**Comment by unguiculus** [comment]
Generally we discourage the use of the `default` function in favor of defaults in `values.yaml`. We should update the docs following example charts and what `helm create` does.
