### ISSUE TITLE
`helm init` creates bad Deployment image url - missing minor version `.0` - 2.7.0 release

### ISSUE THREAD

**Issue by dvdotsenko** [kubernetes/helm#3100]
As a result, Tiller pod fails to start:
`kube-system   po/tiller-deploy-756866f6f4-4rhz9          0/1       ImagePullBackOff   0          2h`

```
$ helm init -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "0"
        image: gcr.io/kubernetes-helm/tiller:v2.7  #<-----------------------------------
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        - containerPort: 44135
          name: http
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
status: {}
```

```
$ docker pull gcr.io/kubernetes-helm/tiller:v2.7
Error response from daemon: manifest for gcr.io/kubernetes-helm/tiller:v2.7 not found
```

```
$ docker pull gcr.io/kubernetes-helm/tiller:v2.7.0
v2.7.0: Pulling from kubernetes-helm/tiller
Digest: sha256:1becf867016f6e7652908518729e140845107c5344afc237718e3ed3b6ca63c7
Status: Image is up to date for gcr.io/kubernetes-helm/tiller:v2.7.0
```

**Comment by bacongobbler** [comment]
Hey, can you explain how you got the helm client? I can't reproduce.

```
><> helm init --dry-run --debug | grep gcr
        image: gcr.io/kubernetes-helm/tiller:v2.7.0
><> helm version -c
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

I've seen this happen when users run `go build` from source rather than `make build` which populates `helm version` metadata correctly.

**Comment by bacongobbler** [comment]
This seems to happen when a user builds from source. In those situations it's best to supply the tiller image you built with `helm init -i` or `helm init --canary-image`.

```
><> make build
GOBIN=/Users/bacongobbler/go/src/k8s.io/helm/bin go install  -tags '' -ldflags ' -X k8s.io/helm/pkg/version.GitCommit=0647cdf84c074a91957ce32d1b820459f8733fbe -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
><> ./bin/helm version -c
Client: &version.Version{SemVer:"v2.7+unreleased", GitCommit:"0647cdf84c074a91957ce32d1b820459f8733fbe", GitTreeState:"clean"}
><> ./bin/helm init --dry-run --debug | grep gcr
        image: gcr.io/kubernetes-helm/tiller:v2.7
```

**Comment by dvdotsenko** [comment]
> Hey, can you explain how you got the helm client? I can't reproduce

"Linux AMD64" link https://kubernetes-helm.storage.googleapis.com/helm-canary-linux-amd64.tar.gz
off https://docs.helm.sh/using_helm/#installing-helm

```
$ helm version
Client: &version.Version{SemVer:"v2.7+unreleased", GitCommit:"0647cdf84c074a91957ce32d1b820459f8733fbe", GitTreeState:"clean"}
```

**Comment by dvdotsenko** [comment]
A side note. While trying to work around that version thing by extracting yaml, editing it and applying it by hand, realized that  `helm init -o yaml` does not output `Service` yaml. 

There is also no `ServiceAccount` / `ClusterRoleBinding` or anything similar. Without `helm list` barks about lack of permissions to list. `ServiceAccount` must go into `Deployment`, so adding it manually after also requires redefining the `Deployment` - a little annoying.
 
Is it supposed to be like that or a separate ticket would be appropriate? I can probably provide some scraps.

**Comment by dvdotsenko** [comment]
Indeed a cannary-specific issue. After downloading a 2.7 release bin (Linux) from here https://github.com/kubernetes/helm/releases - `helm init -o yaml` has properly resolved image url : `image: gcr.io/kubernetes-helm/tiller:v2.7.0` 

I consider this issue addressed on my side - i should not be using cannary. 

Thank you.
