### ISSUE TITLE
Proposal: Handle private repos with Authorization tokens

### ISSUE THREAD

**Issue by burdiyan** [kubernetes/helm#3102]
Right now a user can specify TLS credentials when doing `helm repo add` by using `--ca-file`, `--cert-file` and `--key-file` flags.

It would be great if user could also specify an authorisation token, so that Helm would pass it in every request to the repo.

This may simplify a lot dealing with private repos. A repo can be plain GCS or S3 bucket (non-public), which accept Bearer authorization tokens of allowed IAM users. This also allows to have complex access control use-cases which are already covered by object store provider.

Required changes:

1. Add `--token` flag to `repo add` command. This would store the token in `repositories.yaml` file.
2. Update the code that interacts with the repo, to check if token is specified, and pass it as `Authorization: Bearer <token>` HTTP header for all requests to the repo.

As far as I'm concerned, this shouldn't bring any compatibility issues, but I would like to have a comment from maintainers about it.

**Comment by burdiyan** [comment]
I guess this can also help to solve this one: https://github.com/kubernetes/helm/issues/3092.

**Comment by almed4** [comment]
bump
