### ISSUE TITLE
Helm upgrade will succeed when the previous upgrade is in a failed state

### ISSUE THREAD

**Issue by mmerrill3** [kubernetes/helm#3105]
Helm upgrade will succeed when the previous upgrade is in a failed state

If a helm package is in a failed state, rerunning the upgrade will succeed.  This is because the check against the previous resource in the history will yield no difference, and changes are not applied.

The checker should check against the last known successful version of the helm chart.

**Comment by jascott1** [comment]
@mmerrill3 It appears this is fixed in https://github.com/kubernetes/helm/pull/3097
Please let me know if you have concerns otherwise I will close this. Thanks.

**Comment by mmerrill3** [comment]
This is easily simulated by changing a network policy in your helm chart.  kubernetes version 1.7.9 will not allow updates to network policies (fixed in version 1.7.10).  Upgrading will result in a failed upgrade.  If you run the the same command, it will succeed, which is bas since the failed resources in the previous run don't get applied.

**Comment by mmerrill3** [comment]
Thanks @jascott1 , that is our issue.  We'll install 2.7.1 for the fix when it is available.
