### ISSUE TITLE
How do you get the chart's repostory to use variables？

### ISSUE THREAD

**Issue by singhwx** [kubernetes/helm#3106]
I want to get the chart's repository in the template or chart's metadata.It's best to be in the chart's metadata.How to implement it,please?

**Comment by bacongobbler** [comment]
Hey! Would you mind if I ask what use case you are trying to solve with this? Is the repository URL necessary for displaying in the application, or is this for users of the chart to submit bugs/see the source code, as done in #3056?

**Comment by SchindlerWang** [comment]
I'm using HAPI, and I want to update the specified release, so I need to know which repo belongs to this release. I can't implement this now.
