### ISSUE TITLE
Documents correction

### ISSUE THREAD

**Issue by nohkwangsun** [kubernetes/helm#3107]
While I read documents of the Helm, I was confused at "https://docs.helm.sh/using_helm/#using-override"

The below example  is right? I think the "--set" needs to be changed with "--override".

`helm init --set metadata.annotations."deployment\.kubernetes\.io/revision"="1"`

**Comment by jascott1** [comment]
@nohkwangsun You are correct and the example should be using `--override`. I will submit a PR. Thanks for the catch!
