### ISSUE TITLE
Proposal: Make it easier to use tags for selecting charts to run

### ISSUE THREAD

**Issue by balboah** [kubernetes/helm#3108]
I'm using Helm mainly as a way to structure my own templates with values before hitting k8s, not to use shared charts from 3rd party repositories.
Having all my charts as sub-charts in one big umbrella chart works really well, until you want to select which of these charts to run in slightly different cluster environments.

I figured that tags and `file://` location for requirements is what I want. But this will still require me to specify versions in two places and run `helm dependency update` only to copy the files into a tar file on the same git repository.

My use case would be smoother if either:

### A)

You could have requirements link to `file://../charts/something` without having to match the version spec and without having to run `helm dependency update` between changes.

### B)

You could have tags or selectors for your sub-charts without having to first add requirements.

### C)

Being able to use symlinks in charts would avoid having any different functionality than already exists. Currently fails with `charts/foobar: is a directory`

**Comment by jascott1** [comment]
Hi @balboah,

Hopefully we can find a solution for your use case. Can you expand on "slightly different" in "slightly different cluster environments"?

**Comment by balboah** [comment]
Closing this issue as I've successfully solved it with option C
