### ISSUE TITLE
Helm is inconsistent about handling actual state of resources

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/helm#3118]
We see this quite often with people new to Helm who know how to use Kubernetes and kubectl.  

1. User deploys a helm chart
2. They make a tweak to the resources (like running `kubectl scale` or `kubectl annotate`)
3. Later try to upgrade the chart (which apparently succeeds)

In most cases it seems like the upgrade works fine.  In other cases changes or settings either get merged in, or dropped depending on what the state of the resource is within the release that tiller knows about.

AFAICT It would make sense if Helm made use of the same merging behavior in `kubectl patch` / `kubectl apply` to solve this problem, perhaps in 2 stages like:

1. patch release with new changes to the chart
2. patch actual resources with changes

I can see it being tricky to handle deletions for actual resources in this case, but it it would make sense to favor the contents of the chart in that case I suppose? 

At the very least, helm should refuse to upgrade a modified actual resource and tell the user why.

**Comment by blakebarnett** [comment]
I realized after thinking about this for a while that maybe what I'm actually asking for is a `--no-tiller` mode, that applies rendered resources directly to the k8s API.

I realize this is a big change and probably not viable for charts installed via repository, but if this and the proposed change to allow a selection of a different template engine other than go-template were available, suddenly I have no qualms about helm at all and could see us using it indefinitely.

**Comment by blakebarnett** [comment]
/remove-lifecycle stale

This seems to be relevant to the Helm 3 discussion but feel free to close it if it's being tracked elsewhere.

**Comment by bacongobbler** [comment]
I'll move this to the milestone for now and we'll triage when we get there :)

**Comment by bacongobbler** [comment]
closing as this is being tracked as part of the helm 3 proposals in https://github.com/kubernetes-helm/community/tree/master/helm-v3
