### ISSUE TITLE
Port forwarding error when using helm install

### ISSUE THREAD

**Issue by aneeta34** [kubernetes/helm#3132]
When I run helm install stable/kube-state-metrics or helm ls I get the following output : 
Error: forwarding ports: error upgrading connection: error sending request: Post https://xx.xxx.xx.xx:xxxx/api/v1/namespaces/kube-system/pods/tiller-deploy-2123856503-1j6zh/portforward: http: server gave HTTP response to HTTPS client

**Comment by jascott1** [comment]
@aneeta34 kubectl proxy is HTTP. It appears you are trying to use HTTPS over that connection. Is that the case?

**Comment by aneeta34** [comment]
If kubectl proxy is HTTP, then how do I connect to an https server?

**Comment by jascott1** [comment]
@aneeta34 Sorry for the delay. If you are using `kubectl proxy` then you would make your requests with http not https. You should not need to run that for Helm to access a remote cluster though. I just wanted to make sure kubectl wasn't involved so we could eliminate that for troubleshooting. It does sound like you have a mismatch between the protocols tho. Perhaps your `.kube/config` has https but your API server is running insecure (http)?
