### ISSUE TITLE
Helm on Windows: unknown flag: --kubeconfig

### ISSUE THREAD

**Issue by grrywlsn** [kubernetes/helm#3146]
I'm testing using Helm on Windows, and running in to an issue trying to pass it the Kubernetes configuration.  

The `--kubeconfig` option is being reported as an unknown flag. For reference, the config file is saved at the default location, C:\Users\my-user\ .kube\config, which is being picked up just fine by kubectl without having to set any flags.

From the docs, it looks like this flag should be a valid option. My version of Helm:

```Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}```

Should I be able to use this flag (and rely on it being there in future versions)?

**Comment by bacongobbler** [comment]
#2219 was merged in after v2.7.0 was released, so it'll make it into v2.8.0. Thanks!

**Comment by bacongobbler** [comment]
sorry, #2621. #2219 is the issue.

**Comment by grrywlsn** [comment]
Awesome, thanks @bacongobbler
