### ISSUE TITLE
docs(templates): PR #3076 should be reverted

### ISSUE THREAD

**Issue by unguiculus** [kubernetes/helm#3151]
I would like to see #3076 reverted because it is incorrect. The old example was correct. It is not possible to used `.Files.Get` to retrieve templates.

https://github.com/kubernetes/helm/pull/3076/files#diff-3afc5f8731b9da3a7be91779aec40fbaL147

See https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/accessing_files.md

Interestingly, though, Helm does not complain if `.Files.Get` is used with a template path. It just returns an empty string. So, this does generate a checksum: `checksum/config: {{ .Files.Get "templates/configmap.yaml" | sha256sum }}`, but not based on the file's contents. In fact, `checksum/config: {{ "" | sha256sum }}` yields the same checksum.

It can easily be tested with a `NOTES.txt` file:
* Adding `{{ .Files.Get "templates/configmap.yaml" }}` to a `NOTES.txt` silently prints nothing.
* Adding `{{ include (print .Template.BasePath "/configmap.yaml") . }}` to a `NOTES.txt` prints the contents of `configmap.yaml`.

**Comment by bacongobbler** [comment]
cc @joanrieu, perhaps he can pipe in a bit and elaborate on why the previous documentation did not work in his use case.

**Comment by usr42** [comment]
`.Files.Get` does not work for files in the templates folder:
https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/accessing_files.md

Maybe both use cases should be described in the documentation.
The `.Files.Get` approach for static ConfigMaps or Secrets outside of the templates folder and the `include` approach for variable ConfigMaps or Secrets utilizing templates.

See also my comment: https://github.com/kubernetes/helm/pull/3076#issuecomment-344633659

**Comment by bacongobbler** [comment]
fixed in #3142.
