### ISSUE TITLE
how to make daemonset upgrade sequentially 

### ISSUE THREAD

**Issue by rootfs** [kubernetes/helm#3153]
I have a ceph helm chart that has daemonsets in it. The daemonsets start up ceph osd. There could be multiple daemonsets, e.g. ceph-osd-dev-sdc, ceph-osd-dev-sdd, ceph-osd-dev-sde.

I want to upgrade these daemonsets sequentially during helm upgrade, i.e. daemonset ceph-osd-dev-sdd waits till ceph-osd-dev-sdc is complete before it can upgrade. 

Ideas and pointers are appreciated.

**Comment by rootfs** [comment]
@technosophos I saw your comments on some related issues.

**Comment by rjminsha** [comment]
Quick thoughts ... 
The daemonsets could share a local volume and set a state file in that volume.  The init script for the containers waits on that state to flip to <version>-ready before proceeding with the upgrade logic.  Readiness checks can then also return based on the same state. 

Alternatively could provide a prereq env to daemonsets, they check for the prereq and wait till it is up to speed.  This can also be used as a readiness check.
