### ISSUE TITLE
Unable to create roles and rolebindings as pre-install hooks

### ISSUE THREAD

**Issue by jberkenbilt** [kubernetes/helm#3165]
Problem: when creating a role or rolebinding in a pre-install hook, helm succeeds in creating the role or rolebinding, but the operation fails because of a failure running a get command. The cluster in which I reproduced this problem has helm 2.7.0 with RBAC enabled. tiller is in the kube-system namespace and has cluster-admin. The user running helm is also a cluster admin

The following typescript illustrates. Here's what's going on:

* Start with an empty namespace.
* Attempt to install a helm chart that does nothing but install a role and a rolebinding as pre-install hooks. The role has a lower weight so it will install first.
* Observe that there are initially no roles or rolebindings.
* Attempt to install the chart. Observe that the helm install reports a failure because of a permission on get but that the role was successfully created.
* Temporarily disable the role installation by renaming the file to start with `_`
* Install the chart again. The same error happens with rolebinding.
* Make a copy of the chart but change the role and rolebinding to be normal installations rather than hooks.
* Install the chart, and observe that the chart installs successfully.

I'm not sure whether this is a bug (it seems like one to me) or whether it's an error in my RBAC configuration. I'm not sure what permission should be required to do this get or what user is trying to do the get, but tiller is supposed to have cluster-admin in my setup.

Note: this is an initial test cluster. We are going to do a full security audit on it including figuring out exactly what permissions tiller etc. should have. I have set the broadest possible permissions here in an effort to rule out a configuration error as the source of this problem, but I am relatively new to kubernetes and RBAC and could be making a mistake.

The log below contains the contents of the two yaml files. _helpers.tpl is the one created by helm create.

```
% cat roles/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "roles.fullname" . }}-namespace-admin
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
% cat roles/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "roles.fullname" . }}-namespace-admin
  namespace: "{{.Release.Namespace}}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-8"
subjects:
- kind: ServiceAccount
  name: default
  namespace: "{{.Release.Namespace}}"
roleRef:
  kind: Role
  name: {{ template "roles.fullname" . }}-namespace-admin
  apiGroup: rbac.authorization.k8s.io
% ls roles
_helpers.tpl  rolebinding.yaml	role.yaml
% kubectl get roles
No resources found.
% kubectl get rolebindings
No resources found.
% helm install --name=q roles
Error: the server rejected our request for an unknown reason (get roles.rbac.authorization.k8s.io)
% kubectl get roles
NAME                      AGE
q-roles-namespace-admin   3s
% mv roles/templates/role.yaml roles/templates/_role.yaml
% helm install --name=q roles
Error: the server rejected our request for an unknown reason (get rolebindings.rbac.authorization.k8s.io)
% kubectl get rolebindings
NAME                      AGE
q-roles-namespace-admin   4s
% kubectl delete namespace q
namespace "q" deleted
% mv roles/templates/_role.yaml roles/templates/role.yaml
% cp -a roles roles1
% cd roles1/templates
% for i in r*.yaml; do sed -i -e s/helm.sh/xelm.sh/ $i; done
% cat role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "roles.fullname" . }}-namespace-admin
  annotations:
    "xelm.sh/hook": pre-install
    "xelm.sh/hook-weight": "-10"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
% cd ../..
% helm install --name=q roles1
NAME:   q
LAST DEPLOYED: Sat Nov 18 07:59:50 2017
NAMESPACE: q
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Role
NAME                     AGE
q-roles-namespace-admin  0s

==> v1beta1/RoleBinding
NAME                     AGE
q-roles-namespace-admin  0s
```

**Comment by bacongobbler** [comment]
You may want to take a look at how the stable charts do it at https://github.com/kubernetes/charts. There are probably a few common patterns used to install roles and rolebindings for certain charts.

**Comment by frankreno** [comment]
I have this same issue.  If I pre-create the RBAC configuration then install the chart (which has hooks that run with the previously created service account it works fine.  However, if I properly annotate the RBAC config with the weights to install them before the weight of the hook, i get the above error.

**Comment by mkjpryor-stfc** [comment]
I have the same issue.

**Comment by baldeynz** [comment]
I have the same issue

**Comment by clementnero** [comment]
I have the exact same issue.

**Comment by yuvipanda** [comment]
I had the same issue, it turns out it works on 1.8 clusters but not 1.7
