### ISSUE TITLE
$ does not refer to root scope in a nested template

### ISSUE THREAD

**Issue by mikn** [kubernetes/helm#3167]
Encountered that `$` does not refer to the root scope inside a template that has been given another scope.
Example:
```
{{- define "metadata" -}}
name: {{ template "test.fullname" $ }}
role: {{ .role }}
{{- end -}}
```
```
{{ include "metadata" .Values }}
```
Will result in this error:
`Error: render error in "test/templates/deployment.yaml": template: test/templates/deployment.yaml:3:3: executing "test/templates/deployment.yaml" at <include "metadata" ....>: error calling include: template: test/templates/_helpers.tpl:14:27: executing "test.fullname" at <.Chart.Name>: can't evaluate field Name in type interface {}`

Helm version:
```
helm version
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```
Having this supported could greatly simplify templating, especially in cases where you want to start several different types of services with the same pod definition. An example would be this scenario with elasticsearch: https://github.com/clockworksoul/helm-elasticsearch/tree/master/templates

**Comment by omkensey** [comment]
The .Chart set of attributes exists outside the .Values hierarchy so this looks like "behaving as designed" to me.  This is documented in https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/control_structures.md#modifying-scope-using-with -- the variable assignment workaround there might be useful to you (although you probably wouldn't be able to use it as-is).

**Comment by omkensey** [comment]
(deleted earlier comment)

I think maybe this is "working as designed".  When child chart templates are rendered, they render with a root scope that is defined for that chart, not inherited directly from the parent.  If the call to a named template is intended to mimic that behavior, then the root scope for that call to that named template would be whatever you pass to it explicitly with the `include` call.

**Comment by mikn** [comment]
I think the documentation would do well with some clarification regarding this issue. An alternative solution to the problem I'm trying to solve is template parameters, so that I can explicitly pass in variables rather than just a variable scope. I found this issue: https://github.com/kubernetes/helm/issues/1054 which does provide me with a passable workaround for now, but doing
```smarty
{{- $_ := set $ "vals" .Values.data }}
{{- include "metadata" . | indent 4 }}
```
Is a bit hacky, still. :)
