### ISSUE TITLE
deploy charts with the same name in different namespaces

### ISSUE THREAD

**Issue by prune998** [kubernetes/helm#3188]
Hi,
Here is the use-case I can't reproduce using Helm.
Let's say I want to deploy a database for the `dev` namespace, but I also need one for the `prod` namespace.  
I would deploy in dev : 
```helm install --name kafka --namespace dev kafka ```

Then my other services in dev can reach Kafka using the service `kafka-kafka`. This is pretty ugly, but well, I can do with it.

Then, when deploying to `PROD`, I want all my services to be able to reach Kafka with the same service name, so I don't have to template the service deployment.

The idea would be to be able to run : 
```helm install --name kafka --namespace prod kafka ```

Which should, in the end, from a K8s view, create a `kafka-kafka.dev` and a `kafka-kafka.prod service`

for the moment, Helm is using the `name` as the key, so you can't have 2 identical names, even in different namespaces.
Trying the deployment above leads to `Error: a release named kafka already exists.`

How to solve this situation ?

**Comment by benlangfeld** [comment]
If one were to run a Tiller instance in each namespace, scoped to that namespace, this would be achievable. This also avoids Helm being used to circumvent RBAC.

**Comment by prune998** [comment]
but this solution is a pain, and a twist of the regular Helm usage.

**Comment by irfn** [comment]
Is there no plan to fix this?
Namespaces are an elegant way to avoid too much configuration. services in each namespace can lookup other services without having to override config.

**Comment by irfn** [comment]
Is there no plan to fix this?
Namespaces are an elegant way to avoid too much configuration. services in each namespace can lookup other services without having to override config.

**Comment by bacongobbler** [comment]
closing in favour of https://github.com/kubernetes/helm/issues/2060 where there is further discussion on these points.
