### ISSUE TITLE
helm guestbook example

### ISSUE THREAD

**Issue by yahavb** [kubernetes/helm#3191]
I ported the kubernetes/examples/guestbook to helm. I validated it in GKE and plan to do so in AWS-based cluster. Do you guys want me to share it for the benefits of those who uses the kubernetes examples?

**Comment by benlangfeld** [comment]
If you've already written it, I see no reason not to share it. I don't think you need to ask for permission :)

**Comment by yahavb** [comment]
Thanks, I signed the contributor agreement. I created a local branch that includes my additions but when I execute `git push --set-upstream origin guestbook-helm-example` it fails due to permission issues.
```
remote: Permission to kubernetes/helm.git denied to yahavb.
fatal: unable to access 'https://github.com/kubernetes/helm.git/': The requested URL returned error: 403```

Anything else is needed for creating a PR.

**Comment by yahavb** [comment]
Pull request https://github.com/kubernetes/helm/pull/3201
