### ISSUE TITLE
helm install (of umbrella chart) hangs though release status is DEPLOYED

### ISSUE THREAD

**Issue by matth-boise** [kubernetes/helm#3216]
helm version 2.7.2 (client and tiller), kubectl version 1.7.10 (client and server)
 
**when running on an AWS EC2 (ubuntu 16.04)**
- helm ls works
- helm install different/smaller chart works
- helm install larger umbrella chart hangs
    `helm install --debug --timeout 1200 --namespace xxx umbrellachart # command does not return`
- helm ls shows release status is DEPLOYED (note: takes about 15 minutes)
- tiller log shows
    `[tiller] 2017/11/30 17:27:06 hooks complete for post-install happy-penguin`
    `[storage] 2017/11/30 17:27:06 updating release "happy-penguin.v1"`

**when running on local ubuntu machine (16.04)**
- everything above works using the same charts - nothing hangs

**more information**
- i have reproduced this several times
- one time, tiller showed the release failed (after about 8 minutes) but helm did not return and show the failure.  (it was hung)

i got golang stack trace of helm in this condition but... it's meaningless to me (and long).
lsof of helm shows:
```
$ lsof -p 14886
COMMAND   PID   USER   FD      TYPE  DEVICE SIZE/OFF    NODE NAME
helm    14886 ubuntu  cwd       DIR   202,1     4096 2594345 /home/ubuntu/workspace/kube/Promote/ncm-all@4/kube-tools
helm    14886 ubuntu  rtd       DIR   202,1     4096       2 /
helm    14886 ubuntu  txt       REG   202,1 48608135   50265 /usr/local/bin/helm
helm    14886 ubuntu    0u      CHR   136,0      0t0       3 /dev/pts/0
helm    14886 ubuntu    1u      CHR   136,0      0t0       3 /dev/pts/0
helm    14886 ubuntu    2u      CHR   136,0      0t0       3 /dev/pts/0
helm    14886 ubuntu    4u  a_inode    0,11        0    8112 [eventpoll]
helm    14886 ubuntu    5u     IPv4 2405399      0t0     TCP ip-xx-xx-xx-xx.us-west-2.compute.internal:52426->ec2-xx-xx-xx-xx.us-west-2.compute.amazonaws.com:https (ESTABLISHED)
helm    14886 ubuntu    6u     IPv4 2405400      0t0     TCP localhost:40613 (LISTEN)
helm    14886 ubuntu    8u     IPv4 2405046      0t0     TCP localhost:37256->localhost:40613 (ESTABLISHED)
helm    14886 ubuntu    9u     IPv4 2405402      0t0     TCP localhost:40613->localhost:37256 (ESTABLISHED)
```

**Comment by matth-boise** [comment]
ha!  i posted too early: does anyone have an idea how to triage this?  lsof shows:
```
$ lsof -p 14886
COMMAND   PID   USER   FD      TYPE  DEVICE SIZE/OFF    NODE NAME
helm    14886 ubuntu  cwd       DIR   202,1     4096 2594345 /home/ubuntu/workspace/kube/Promote/ncm-all@4/kube-tools
helm    14886 ubuntu  rtd       DIR   202,1     4096       2 /
helm    14886 ubuntu  txt       REG   202,1 48608135   50265 /usr/local/bin/helm
helm    14886 ubuntu    0u      CHR   136,0      0t0       3 /dev/pts/0
helm    14886 ubuntu    1u      CHR   136,0      0t0       3 /dev/pts/0
helm    14886 ubuntu    2u      CHR   136,0      0t0       3 /dev/pts/0
helm    14886 ubuntu    4u  a_inode    0,11        0    8112 [eventpoll]
helm    14886 ubuntu    5u     IPv4 2405399      0t0     TCP ip-xx-xx-xx-xx.us-west-2.compute.internal:52426->ec2-xx-xx-xx-xx.us-west-2.compute.amazonaws.com:https (ESTABLISHED)
helm    14886 ubuntu    6u     IPv4 2405400      0t0     TCP localhost:40613 (LISTEN)
helm    14886 ubuntu    8u     IPv4 2405046      0t0     TCP localhost:37256->localhost:40613 (ESTABLISHED)
helm    14886 ubuntu    9u     IPv4 2405402      0t0     TCP localhost:40613->localhost:37256 (ESTABLISHED)
```

**Comment by matth-boise** [comment]
more information:
- this umbrella chart takes about 15 minutes to install because it uses helm hook jobs to do ordered things like db migrations
- i have reproduced this several times
- one time, tiller showed the release failed (after about 8 minutes) but helm did not return and show the failure.  (it was hung)
- i got go stack trace of helm in this condition but... it's meaningless to me (and long)

**Comment by jascott1** [comment]
Hi @matth-boise 

Sorry you are having trouble. Would it be possible to post a chart that demonstrates the problem?

**Comment by matth-boise** [comment]
@jascott1 unfortunately this is an umbrella chart that includes private images, so you cannot repro.

i'm not sure my description was clear but this helm install "hang" only occurs when running on an AWS EC2.  even though the helm install command does not return, tiller reports the release as successfully deployed.  when running helm on a local machine helm does not hang - and chart installs successfully.  (chart also installs successfully on minikube.)  simpler charts install successfully on AWS EC2.

we are working around this by running helm install within timeout.

**Comment by jascott1** [comment]
@matth-boise I was curious about the size and complexity of the chart as those are very long install times. How long does it take for the local install?

**Comment by matth-boise** [comment]
if by "local install" you mean running helm install of this umbrella chart from a native machine, the time for the chart install to be successfully deployed on this aws cluster is the same.  the difference is, the helm install command returns successfully on native/local machine but the command "never" (we waited 24 hours) returns return to aws ec2.

the kubernetes work to create everything is, of course, very fast.  the reason our umbrella chart takes so long (13-15 min) is because we are using helm post-install hooks to run several db migrations.  post-install hook jobs must all complete (each within --timeout) for the install to be complete for helm to consider the release deployed.

i'm concerned that my environment has a configuration problem that causes the kubectl proxy to stop working between the api server nodes and this ec2.  i ran iptrace to watch tcp traffic between the client ec2 and the cluster api nodes - and every 30 seconds there was a { ec2-to-api-node, api-node-to-ec2 } duplet.  this 30 sec ping-pong continues even after tiller successfully installs the chart so i don't think there is fundamental network failure...

is there a way to increase debugging to help understand this?  on both the client (aws ec2 in this case) and on tiller pod??

**Comment by jascott1** [comment]
@matth-boise 

Sorry for the delay, I guess this fell off my radar after the holidays. Did you resolved this issue?

To increase Tiller's verbosity you can modify the Tiller deployment with `kubectl edit` and add this to the container
```
command:
- /tiller
- -v=99
```
Im not sure it will add anything relevant but you never know.
