### ISSUE TITLE
How to destroy Tiller from cluster

### ISSUE THREAD

**Issue by bq1756** [kubernetes/helm#3223]
I want to destroy the instance of **tiller** running in my cluster.  Really, I want to redeploy **tiller**.  However, **tiller** won't go away.  How can I remove **tiller**?

What I have tried so far......
Use kubectl commands:
  kubectl -n "kube-system" delete deployment tiller-deploy
  kubectl -n "kube-system" delete service tiller-deploy
  Results:  tiller pods recreates itself

Use helm commands:
  helm reset
  Results:  fails due to a cluster issue.  This is why I want to destroy tiller and start over.

**Comment by bacongobbler** [comment]
> Note: tiller is running as a daemon-set

How did this happen? :) `helm init` deploys tiller as a deployment, which deploys replica sets/pods.

`kubectl -n "kube-system" delete deployment tiller-deploy` should be the way to remove tiller from the cluster assuming it was deployed using `helm init`.

**Comment by bacongobbler** [comment]
Also, which cloud provider are you using? I know in certain instances (like on ACS) tiller is deployed through their addon manager, and this manifested in a bug. See https://github.com/Azure/ACS/issues/55 for more background on that one.

**Comment by bq1756** [comment]
I deployed on ACS via acs-engine.  https://github.com/Azure/ACS/issues/55 explains the issue.
