### ISSUE TITLE
Feature: Pass in user-agent for http calls

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#3231]
Some applications wrap helm and it can be useful to specify the user-agent when making HTTP calls. The specific use case here is for the charts CI. It will regularly make calls to the stable and incubator repos. To separate out the CI calls from other calls in the metrics it would be useful to specify the user agent string.

**Comment by mattfarina** [comment]
Note, I'm happy to write this.

**Comment by bacongobbler** [comment]
I’m all for this. Kubernetes just did this on their http liveness probes and I dearly wished I had that feature sooner to differentiate between incoming liveness probes and “real” requests.
