### ISSUE TITLE
Convert from Make to Mage for cross platform compat

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#3237]
Make is known for its use on POSIX systems. But, Helm is cross platform and that includes Windows. To handle that in other languages they use other tools. For example, in JavaScript folks use Grunt.

Should Helm consider switching to [Mage](https://github.com/magefile/mage) and Magefiles?

cc: @adamreese @technosophos

**Comment by bacongobbler** [comment]
After discussions among the other core maintainers we prefer to stick with make. Closing!
