### ISSUE TITLE
Cannot download Tiller image 2.6, but can download 2.6.2

### ISSUE THREAD

**Issue by kylos101** [kubernetes/helm#3244]
Hi,

First off, Helm is awesome, thank you so much for this!!! 

My Kubernetes is unable to download Tiller image v2.6 with the canary build of Helm for Windows (I just downloaded Helm, to verify I'm using the latest version).

For example, Docker cannot download the same image:
docker pull gcr.io/kubernetes-helm/tiller:v2.6

It yields this error:
Error response from daemon: manifest for gcr.io/kubernetes-helm/tiller:v2.6 not found

I changed the YAML in Kubernetes for my Replica Set and Deployment to this:
gcr.io/kubernetes-helm/tiller:v2.6.2

And then deleted my Tiller pod, it started up well, and I was able to use Helm to install charts again.

Let me know if anything else is needed, take care.

**Comment by bacongobbler** [comment]
hey @kylos101, can you explain why or how you're downloading the v2.6 tag? This tag does not exist as you'd expect; though there is a v2.6.0 release. Is that what you're looking for?

**Comment by kylos101** [comment]
Hi Matt, it wasn't intentional, it's what happened when I tried to
initialize helm with my minikube cluster.

As the fresh tiller pod came online, it was trying to pull that image.

I'm using minikube 0.24.1 on Windows 10, if that helps. Let me know if you
need more info and I'll see what I can do.

**Comment by bacongobbler** [comment]
Thanks. Can you post the output of `helm version` and how you got the binary so I can reproduce?

**Comment by kylos101** [comment]
Sure thing, here's the helm version output:
Client: &version.Version{SemVer:"v2.6+unreleased", GitCommit:"1ac5cd78debfa4a99d07f7b1a01c1ee46e2cfb56", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}

I got the binary from here:
https://kubernetes-helm.storage.googleapis.com/helm-canary-windows-amd64.zip

Extracted the EXE

And install it like this: "helm init --upgrade"

**Comment by bacongobbler** [comment]
Ah yes. If you’re using a canary release client, you also need to supply the —canary flag to `helm init`. Let me know if that works for you.

**Comment by kylos101** [comment]
Ah, that works much better! ;-) Thank you very much, @bacongobbler! 

Now my tiller image in my YAML references this: 
gcr.io/kubernetes-helm/tiller:canary

I must have missed [the releases here](https://github.com/kubernetes/helm/releases). I'll take a swing at using 2.7.2.

Thanks again!
