### ISSUE TITLE
Helm client doesn't support concurrency

### ISSUE THREAD

**Issue by nicolerenee** [kubernetes/helm#3253]
To interact with helm we are importing the `k8s.io/helm/pkg/helm` package. This allows us to build a client that can talk to the tiller and create/update/delete releases. This works great.

Recently we have been trying to speed up our interactions with the tiller so we added some concurrency on our side. It appears the client that comes as part of the k8s.io/helm/pkg/helm package does not support concurrency. Is this expected behavior?

I've built a basic example that shows this failing. The code for that is here: https://github.com/nicolerenee/helm-concurrency

**Comment by bacongobbler** [comment]
If there are certain areas of the client package that can't work in a thread-safe environment which we can fix, let's make that happen :) feel like taking a crack at a PR?

**Comment by bacongobbler** [comment]
labeling this as a feature because nobody (asides @nicolerenee) has used the helm client in a concurrent way before, so this would be introducing new functionality to pkg/helm.

**Comment by nicolerenee** [comment]
Sure. I'll get started working on a PR for this. Hopefully can get something together without having to change to much in how the client works.

**Comment by burdiyan** [comment]
OMG, we were having so many issues with that, and I just realized that this was the reason. Hope it will be released soon.
