### ISSUE TITLE
helm upgrade fails when updating the apiVersion of a resource that's not available anymore

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/helm#3256]
Helm version: 2.7.2
k8s version: 1.8.5

We're seeing this with 1.8 after `batch/v2alpha1` support is disabled no charts that referenced CronJob with that `apiVersion` can upgrade, we have to `delete --purge` the chart and re-install.  Trying to figure out a good solution for prod to avoid downtime.

Same issue as https://github.com/kubernetes/helm/issues/2885 but it seems the fix only works if both apiVersions are still valid?

**Comment by bacongobbler** [comment]
Yeah, this was a design decision made by the kubernetes devs that one cannot upgrade resources from one apiVersion to the next. We're also having the same concern with tiller in #3234 as well. There does not appear to be a migration patch forward for deprecated api versions, and I'm not sure there's a clean path forward for helm either. This is something we should discuss upstream.

**Comment by blakebarnett** [comment]
To avoid downtime for the rest of the resources in charts like this can we make it handle the upgrade by just deleting the v2alpha1 CronJob resource somehow? Surgically remove it from the release configmap or something?

**Comment by bacongobbler** [comment]
You could try editing the cronjob out of the latest release's configmap payload, though I'm not 100% sure what the outcome would be. My hunch is that the existing DaemonSet will be orphaned and the new CronJob will appear, so I'd make sure the old CronJob is removed from the cluster before applying an upgrade. You're welcome to give that a shot though and see what happens! :)

**Comment by blakebarnett** [comment]
I didn't dare for production, I just had everyone remove CronJob resources from their helm charts until after the upgrade. I imagine we'll hit this again someday with some other alpha resource so I'll try to validate a process for manually modifying the configmap on a test cluster.
