### ISSUE TITLE
[BUG] Tiller cause Worker outage when install big Chart. 

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/helm#3261]
Hi ! 

I found a bug on Helm v2.7.2 that 'cause multiple outage on our Kubernetes workers due of **huge Server Load increasing**. 

I wrote a Helm chart for deploy a specific App (Ubiquiti UNMS), here is my folder : 
```
unms/
  values.yaml
  Chart.yaml
  templates/
    services.yaml
     deploy-redis.yaml
     deploy-unms.yaml
     deploy-postgres.yaml
     ingress.yaml
     network-policies.yaml
```  
Before all, Helm work fine on my setup, I got like 15 charts deployed and upgraded every day. 

But this one, cause big problems : 

```
14:02:36 › helm install -n unms --namespace ubiquiti-unms . --debug                                                                                                                               

[debug] Created tunnel using local port: '52331'

[debug] SERVER: "127.0.0.1:52331"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/Valentin/UNMS/helm

(NOTHING after THAT)
```

Tiller logs : 
```
[tiller] 2017/12/15 03:02:56 preparing install for unms
[storage] 2017/12/15 03:02:56 getting release history for "unms"
[tiller] 2017/12/15 03:02:56 rendering unms chart using values

(NOTHING after THAT)
``` 

**Worker Load change from 0.8 before `helm install` to more than 60** (on 8vCPUs)  in few seconds and cause that The API-Server can talk to this node anymore until I kill the tiller process (or pod). 

Any idea what's going on' ?

**Comment by jascott1** [comment]
Hi @valentin2105 

Would it be possible to share the chart ?

**Comment by valentin2105** [comment]
Here is it  : https://github.com/valentin2105/unms-chart 

`helm install -n unms --namespace ubiquiti-unms unms-chart/ --debug`

**Comment by jascott1** [comment]
Really sorry you having this trouble. Does removing the Tiller pod and letting it re-spawn have any effect?

**Comment by valentin2105** [comment]
Deleting the pod stop the load increase, but if I don't kill the pod, the
worker crash totally (no ssh access) in 2 or 3 minutes.

**Comment by jascott1** [comment]
Hi @valentin2105 

You have some issues with your chart. After I fixed these I could install it normally.

`apiversion` should be `apiVersion`
https://github.com/valentin2105/unms-chart/blob/master/templates/deployment_unms.yaml#L1

Missing `apiVersion` for both PVCs
https://github.com/valentin2105/unms-chart/blob/master/templates/pvc.yaml#L1

Im not sure why you see the high resource load. Please let me know if this fixes the issue for you. Thanks!

**Comment by mfilotto** [comment]
Any update on this one ?

**Comment by valentin2105** [comment]
Thanks @jascott1 it's fixed, 
but doesn't explain the high load.
Otherwise, here the updated version : 
https://github.com/valentin2105/unms-chart
