### ISSUE TITLE
helm package is not idempotent when used for a N-dependencies umbrella chart

### ISSUE THREAD

**Issue by cridam** [kubernetes/helm#3264]
`helm package -u` for the same umbrella chart having more than 1 dependency is not idempotent, that it may generate a binary with a different signature ... (md5)  . Dependencies are unchanged.

Step to reproduce from any where.  

For instance using a umbrella chart of the internet (jaeger)
Notice the test fails also, without fetching on every round (instead just `rm -rf jaeger/charts jaeger/*tgz` )
 
helm version : **v2.7.2**
# test 
`helm repo add k8s https://kubernetes-charts-incubator.storage.googleapis.com/;>/tmp/md5;seq 30 | xargs -I S sh -c "echo -n \"round S = \";rm -rf jaeger;helm fetch k8s/jaeger --untar;cd jaeger;helm package -u . 1>/dev/null;cd ..;find jaeger/*tgz | xargs md5sum >> /tmp/md5;cat /tmp/md5 | sort | uniq | wc -l";cat /tmp/md5;`

# result
round 1 = 1
round 2 = 2
round 3 = 2
round 4 = 2
....

`cat /tmp/md5`
8509b8f7be7c278fea3b9565dbe92528  jaeger/jaeger-0.2.1.tgz
25326cce5e6d769f513743a80d92512a  jaeger/jaeger-0.2.1.tgz
8509b8f7be7c278fea3b9565dbe92528  jaeger/jaeger-0.2.1.tgz
0ab078de9d20889e6e2011688fabefdf  jaeger/jaeger-0.2.1.tgz
0ab078de9d20889e6e2011688fabefdf  jaeger/jaeger-0.2.1.tgz
8509b8f7be7c278fea3b9565dbe92528  jaeger/jaeger-0.2.1.tgz
8509b8f7be7c278fea3b9565dbe92528  jaeger/jaeger-0.2.1.tgz
8509b8f7be7c278fea3b9565dbe92528  jaeger/jaeger-0.2.1.tgz
8509b8f7be7c278fea3b9565dbe92528  jaeger/jaeger-0.2.1.tgz
25326cce5e6d769f513743a80d92512a  jaeger/jaeger-0.2.1.tgz
25326cce5e6d769f513743a80d92512a  jaeger/jaeger-0.2.1.tgz
163a618366e3c348c6d5a77b3d1a75ed  jaeger/jaeger-0.2.1.tgz
8509b8f7be7c278fea3b9565dbe92528  jaeger/jaeger-0.2.1.tgz
0ab078de9d20889e6e2011688fabefdf  jaeger/jaeger-0.2.1.tgz
163a618366e3c348c6d5a77b3d1a75ed  jaeger/jaeger-0.2.1.tgz
8509b8f7be7c278fea3b9565dbe92528  jaeger/jaeger-0.2.1.tgz

**Comment by cridam** [comment]
My 2p,
i m not familiar at all with golang) , but you might need to sort the dependencies before writing contents 

```
// sorting here ??
sort.Sort(ByName(c.Dependencies))
for _, dep := range c.Dependencies {
		if err := writeTarContents(out, dep, base+"/charts"); err != nil {
			return err
		}
	}
```

**Comment by jschaul** [comment]
/remove-lifecycle rotten
/reopen

This issue is still there and makes comparing chart releases for changes harder.

**Comment by jschaul** [comment]
I guess this is a duplicate of https://github.com/helm/helm/issues/3612.
