### ISSUE TITLE
SolrCloud Helm Chart

### ISSUE THREAD

**Issue by AceHack** [kubernetes/helm#3265]
Is there a plan to support SolrCloud with an official Helm Chart?

Know of any examples?

Thanks.

**Comment by jascott1** [comment]
Hi @AceHack 

Charts are independently submitted by contributors to the kubernetes/charts repo. You might ask in the Solr community about interest in an official Helm chart for that project. Alternatively if you want to tackle it yourself then Im sure the good folks in the `charts` and `helm` channels on Kubernetes slack will be happy to help!
