### ISSUE TITLE
Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.6": rpc error: code = Unknown desc = unauthorized: authentication required

### ISSUE THREAD

**Issue by AceHack** [kubernetes/helm#3270]
Error after helm init

This is in Azure aks right after setting up a brand new aks image

container "tiller" in pod "tiller-deploy-5b9675c8d-twl8w" is waiting to start: trying and failing to pull image

**Comment by AceHack** [comment]
Found the issue I think.

Docs point to old canary build on windows.
https://kubernetes-helm.storage.googleapis.com/helm-canary-windows-amd64.zip

Would be great if this actually pointed to a recent canary build since zip is a lot easier to deal with on windows in powershell than tar.gz (need external tools like 7zip)

After using recent build, things start working.  Any chance on having this url updated to latest canary builds in the future?

**Comment by AceHack** [comment]
yes but what I'm saying is the .zip canary is much older than the .tar.gz

https://docs.helm.sh/using_helm/#installing-helm

Please update https://kubernetes-helm.storage.googleapis.com/helm-canary-windows-amd64.zip
to be the same version as https://kubernetes-helm.storage.googleapis.com/helm-canary-windows-amd64.tar.gz

And keep them in sync

**Comment by bacongobbler** [comment]
this is a side-effect of CI not having `zip` installed. I filed #3274 to fix that.
