### ISSUE TITLE
get_helm.sh could not get helm on arm64

### ISSUE THREAD

**Issue by kevin-zhaoshuai** [kubernetes/helm#3271]
Since Helm has released available Helm packages on arm64, ref: https://storage.googleapis.com/kubernetes-helm/

It's better to add support for download arm64 helm binary with get_helm.sh.
Now run get_helm.sh will return:
linux@kolla-k8s-ut:~$ ./get_helm.sh 
No prebuild binary for linux-arm64.
To build from source, go to https://github.com/kubernetes/helm
Failed to install helm
	For support, go to https://github.com/kubernetes/helm.

**Comment by bacongobbler** [comment]
I'll tackle this. This should be a relatively quick fix!

**Comment by kevin-zhaoshuai** [comment]
@bacongobbler  Thanks a lot!
