### ISSUE TITLE
helm upgrade hungs with helm 2.7.1

### ISSUE THREAD

**Issue by msavlani** [kubernetes/helm#3273]
Hi,

we are using following -

**helm : v2.7.1**

Client: &version.Version{SemVer:"v2.7.1", GitCommit:"4aef7fddc8335e0b7b00d9168c04955d903fdbee", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.1", GitCommit:"4aef7fddc8335e0b7b00d9168c04955d903fdbee", GitTreeState:"clean"}

**Kubernetes -  1.6.7**

We have seen this multiple times now -
When we run helm upgrade command, it hungs indefinitely even after upgrade is successful in background.

Command used - helm upgrade ns1 helm/ns1-1.0.0-41.tgz --namespace ns1
And this command is stuck even though it updated pods in environment.
$ ps -ef|grep helm
ns1 24199 21361  0 18:14 ?        00:00:02 helm upgrade aio-stage1 helm/aio_stage1_cd-1.0.0-41.tgz --namespace staging1
ns2   59115 59114  0 18:00 ?        00:00:00 helm list --all

Noticed 2 things  -

**1 :** 
If you notice above i have another command "helm list --all" which is also stuck and it was ran before helm upgrade (4 minutes earlier) from another unix user.

I am not sure if "helm list --all" stuck is holding any resource which is required by helm upgrade.

**2 :**
Attaching tiller pod logs. 
If you see last line it throws error about : 
2017/12/19 00:25:46 transport: http2Server.HandleStreams failed to read frame: read tcp 172.40.205.244:44134->172.40.68.128:59796: read: connection reset by peer

When i check in my system i have IP 172.40.68.128 assigned to logstash pod running in ns3 namespace and has no relation to pods i am upgrading with above helm command.

[tiller.txt](https://github.com/kubernetes/helm/files/1569972/tiller.txt)

Let me know if you need more information.

**Comment by jascott1** [comment]
@msavlani Not exactly the same but might be related to issue with too many open sockets. Please take a look at https://github.com/kubernetes/helm/issues/3121
