### ISSUE TITLE
cronjob update: cronjob not found

### ISSUE THREAD

**Issue by yanns** [kubernetes/helm#3277]
When upgrading a cron-job, I have the following error:
```
Error: UPGRADE FAILED: no resource with the name "global-reindex-old-indices" found
```

But the cronjob exists:
```
kubectl get cronjobs
NAME                         SCHEDULE   SUSPEND   ACTIVE    LAST SCHEDULE   AGE
global-reindex-old-indices   @daily     False     1         Tue, 19 Dec 2017 01:00:00 +0100
```

Surprisingly, we deployed the same helm on 3 difference environments, but I only have this error on one of them.

**Comment by jascott1** [comment]
Hi @yanns 

Thanks for reporting the problem. Can you reliably reproduce it in that environment and can you think of any major differences between the environments?

**Comment by yanns** [comment]
I can reproduce it:
- reliably on that environment
- also with a new resource, like a `HorizontalPodAutoscaler`

I tried to check for differences between this environment and others, and could not find any.
I plan to completely destroy the release and re-install from scratch because it's blocking our continuous deployment, unless you have any idea.

**Comment by yanns** [comment]
We found out the the same last version is deployed 2 times on the environment that is failing.
(with `helm list --deployed`)

**Comment by yanns** [comment]
I purged the deployment and installed the helm char again.
Since then, this issue does not appear anymore.

**Comment by gaieges** [comment]
I see the same thing, consistently with the below version.  

Purging seems like a poor solution. While it works, this bug should remain open and be addressed in helm, vs expecting a manual purge to take place.

```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```

**Comment by hgajjar** [comment]
I'm facing this same issue too, is there a solution except deleting the deployment?

**Comment by hgajjar** [comment]
I'm able to fix this by purging the release and reinstalling it, also tested with an upgrade afterwards. Just an observation, this might have happened due to a manual change I did in one of the k8s resources after preview release.
