### ISSUE TITLE
helm-show-kill-ring disregards the selection

### ISSUE THREAD

**Issue by mgoldenbe** [kubernetes/helm#3278]
When I select entries (with `C-<SPACE>`) in `helm-show-kill-ring` and press either `Enter` or `F1`, it disregards the selection and yanks the entry currently under cursor. Why would this be the case and how can I cause it to yank all the selected entries?

Versions: Emacs 24.5.1 (minimal configuration), helm-20150626.731

**Comment by bacongobbler** [comment]
Wrong project. You’re looking for https://github.com/emacs-helm/helm :)

**Comment by mgoldenbe** [comment]
Oops. Thanks!
