### ISSUE TITLE
duplicate menu while pase php file wiile calling helm-semantic-or-imenu

### ISSUE THREAD

**Issue by chenpoyang** [kubernetes/helm#3284]
i have php file open, and use helm-semantic-or-imenu to lookup the function i define.
the menu is dumplicate like this:

<pre>
Pubilc Methods / index
Public Methods / db
Public Methods / hello
Public Methods / list
Public Methods / read
Public Methods / post
All Methods / index
All Methods / db
All Methods / hello
All Methods / list
All Methods / read
All Methods / post
</pre>
and no issue while open lisp file , C/C++ file etc. i don't know if it is a bug?

**Comment by bacongobbler** [comment]
Wrong project. You’re looking for https://github.com/emacs-helm/helm :)
