### ISSUE TITLE
When helm deletes something, maybe pass --include-initialized

### ISSUE THREAD

**Issue by ljnelson** [kubernetes/helm#3286]
Hard to summarize this one.

I happened to install a release into an environment with Istio's [automatic injection](https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection) in play.

My chart ideally would not be Istio-aware.

Anyway, something about Istio caused my installation to fail.  Specifically, a `Job` created as a Helm hook could not be created.  Helm dutifully failed the install.

I did `helm delete --purge my-release` to clean up.

I checked to see that this worked by running commands like `kubectl get -a jobs`, which reported no resources found.  So it looked like everything cleaned up.  But then on a whim I tried `kubectl get -a job name-of-helm-hook-job`, and that returned a status that showed my failed job.  So `helm delete --purge` did _not_ clean everything up.

Many, many, many discussions later, I found that to find this job I have to do `kubectl get --include-uninitialized -a jobs`.  Similarly, I would expect that whatever delete operation Helm performs under the covers should do the equivalent of, for example, `kubectl delete --include-uninitialized some-resource-name`.

I don't know how this all interacts with the fact that initializers are in alpha status but figured I'd file the issue here and let others smarter than I figure out the ramifications.  :-)

**Comment by bacongobbler** [comment]
Hmm, sounds a lot like https://github.com/kubernetes/helm/issues/3017. Essentially objects that are related to the installation to the chart but weren't directly tied to the release (in this case, a Job kicked off by a hook) aren't being cleaned up on `helm delete`.

Perhaps we can inject some labels into all objects "installed" by helm, which then we can just use those label selectors to perform an uninstall, falling back to the old behaviour if those labels are not found. A "mark and sweep", if you will.

How does that sound?
