### ISSUE TITLE
helm can't handle symlink dependencies

### ISSUE THREAD

**Issue by Stono** [kubernetes/helm#3298]
Hey, 
When I'm testing dependencies between things locally it'd be nice to be able to use symlinks:

- some-base-chart

- some-other-chart
  - charts/some-base-chart

- and-another-chart
  - charts/some-base-chart

However when using a symlink:
```
❯ ls -lah
total 8
drwxr-xr-x   4 karl.stoney  staff   136B 25 Dec 11:38 .
drwxr-xr-x  11 karl.stoney  staff   374B 25 Dec 11:35 ..
lrwxr-xr-x   1 karl.stoney  staff    30B 25 Dec 11:38 some-base-chart -> ../../some-base-chart
```
I get the following error:
```
Error: error reading charts/some-base-chart: read charts/some-base-chart: is a directory
```

Presumably as it's treating it like a file rather than following the link.

**Comment by bacongobbler** [comment]
This feature was added in #3113 but has not made it into a release yet. You can test this functionality out using [a canary build of Helm](https://docs.helm.sh/using_helm/#from-canary-builds).

Because this was already tracked at #1639 I'm going to go ahead and close this as a duplicate. Thanks!

**Comment by Stono** [comment]
Thank you @bacongobbler 
I also like Bacon
