### ISSUE TITLE
helm : helm list crashing with timeout

### ISSUE THREAD

**Issue by singhpr** [kubernetes/helm#3300]
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp [::1]:8080: i/o timeout

**Comment by bacongobbler** [comment]
Hi @singhpr. Could you please provide more information? Things like

- your kubernetes version
- how you deployed your cluster (GKE, Azure, home-grown solution?)
- your helm/tiller versions
- the output of `kubectl get pods --all-namespaces`
- also the output of `kubectl cluster-info`

Thanks!

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
