### ISSUE TITLE
Client timeout fails deployment even though all resources deploy successfully

### ISSUE THREAD

**Issue by TD-4242** [kubernetes/helm#3301]
We have an app with a fairly large container with a long startup time.  I can't get it to deploy fast enough to not hit a timeout.  All the resources still get installed in kubernetes but it always marks the helm deployment as FAILED with no way to fix it.

I would expect the client to upload the chart to tiller and tiller would still continue to insure the k8s resources were created and the deployment succeed even if the client lost connection.

**Comment by bacongobbler** [comment]
This is a good proposal for Helm 3 in the form of refactoring tiller into a CRD controller. See #3089 for more info.
