### ISSUE TITLE
Tiller need to retry when watching the job to be completed

### ISSUE THREAD

**Issue by raoy1990** [kubernetes/helm#3303]
Recently，I set a long job as hook, then install it. but I got an error _**watch closed before Until timeout**_ when tiller watching the job to be completed,then tiller stop the workflow. I checked the code and find that the tiller does not retry to watch the job when the connection is closed with unknown reason.

**Comment by technosophos** [comment]
This would be a good thing to add.

**Comment by scriptonist** [comment]
Will this be a good starting point for a beginner contributor to helm and also new to the k8s ecosystem ?
