### ISSUE TITLE
[proposal] refactor aliases for subcharts

### ISSUE THREAD

**Issue by balboah** [kubernetes/helm#3314]
#### Some background:
I'm having one umbrella chart to manage a "complete deployment". Where instead of a requirements file, I'm using symlinked subcharts (feature merged in https://github.com/kubernetes/helm/pull/3113). This lets me group all my different services into charts where everything is still hosted within the same repository without any external dependency management. Each subchart has its values populated by the umbrella values file, for example:
```yaml
serviceA:
  foo: bar
serviceB:
  bar: foo
```

#### Use case:  
Now I need to deploy one of the services multiple times with slightly different values. Since all my subcharts are already symlinks, I figured why not just create another symlink to the same chart but with a different name. This way I can create the different configurations without having to change the subchart itself.
Example:
```
ls -l charts/
groupA-kafka -> ../../charts/kafka
groupB-kafka -> ../../charts/kafka
```
```yaml
groupA-kafka:
  foo: bar
groupB-kafka:
  bar: foo
```

#### Problem:  
It seems that when trying to override the values from the umbrella chart, the key needs to match the .Chart.Name, not the path dirname. This makes it impossible to do it like this without first making a real copy and editing the Chart.yaml in each.

#### Proposal alternatives:  

1. Refactor requirements alias directive to be separate from requirements dependency loading [code](https://github.com/kubernetes/helm/blob/e3e1116eaa6c305be89a9fe476fcfbe2bb6788d2/pkg/chartutil/requirements.go#L240) (maybe a helmalias file?)

1. Base the values keys on path dirname instead of chart name.
  
 1. Implement https://github.com/kubernetes/helm/issues/3221 and use requirements for local charts dir, which would hopefully allow using alias without a fully fledged dependency work flow

**Comment by technosophos** [comment]
The workaround we've suggested before is to add one more subdirectory:

```
groupa/kafka -> kafka
groupb/kafka -> kafka
```

Then you can address them in the values file/set syntax as `groupa.kafka`...

For 1, I think a helmalias file would be fine if we couldn't solve via #3221.

For 2, I think that breaks backward compatibility.

For 3, my only reservation about #3221 (which has come up before) is that it might break backward compatibility. But as a solution, it seems adequate to solve this case. I should go comment on that issue, though. If we can solve it without breaking backward compatibility, I'd be :100: for this.

**Comment by balboah** [comment]
I'll close this in favor of #3221 and hope that it will solve this use case. Thanks for the work around suggestion!

**Comment by victornoel** [comment]
@technosophos do you mean using subdirectory in the charts directory?

I tried something like this:
```
├── blue-green
│   ├── charts
│   │   ├── blue
│   │   │   └── app -> ../../../app
│   │   ├── green
│   │   │   └── app -> ../../../app
│   │   └── commons -> ../../commons
│   ├── Chart.yaml
```

But helm tells me:
```
ERROR] templates/: error unpacking blue in blue-green: chart metadata (Chart.yaml) missing
```
