### ISSUE TITLE
Non processed values in docs

### ISSUE THREAD

**Issue by Carreau** [kubernetes/helm#3317]
Apologies if I haven't found a similar issue, but there are several place in the docs where unprocess values are visible.

For example https://docs.helm.sh/chart_template_guide/#built-in-objects have aliases defined just above:

```
+++ aliases = [ “builtin_objects.md”, “chart_template_guide/builtin_objects.md”, 
“using_helm/builtin_objects.md”, “developing_charts/builtin_objects.md” ] +++
```

<img width="821" alt="screen shot 2018-01-07 at 20 12 19" src="https://user-images.githubusercontent.com/335567/34653074-19e1833a-f3e7-11e7-8f35-34e62c75e1e4.png">

I'm going to assume this is not on purpose and have not been caught by CI. 

I'm pretty sure it is not relevant for the content to be understood but can be distracting. 
I grep-ed through the repo but was not able to find where this come from. 

Hopefully this is already fixed and simply not deployed. 

Thanks !

**Comment by flynnduism** [comment]
Yeah I'll sort this out - it's metadata from Hugo getting rendered as page content. Will ensure it gets cleaned up in the build process

**Comment by flynnduism** [comment]
The docs site has been updated, those metadata blobs are no longer being rendered:
[https://docs.helm.sh/chart_template_guide/#built-in-objects](https://docs.helm.sh/chart_template_guide/#built-in-objects)

**Comment by bacongobbler** [comment]
thanks @flynnduism! Closing this.
