### ISSUE TITLE
helm custom resource validation fail

### ISSUE THREAD

**Issue by luisyonaldo** [kubernetes/helm#3325]
According to helm docs, you can install a CRD as a pre-install hook, but in practice it still fails because validation step doesn't yet recognise the 3rd party api definition. Only way I have found is installing resources that depends on the CRD as post-install hook that creates a job that trigger a container that manually install the resources using `kubectl apply -f custome-resources-config.yaml ``so validation doesn't fail and order is right. Or do a 2 step install (`install` and then `upgrade`) which first install CRD and later CR (that depend on the previous CRD).

Any of the two solutions works but this seems more like a hack than a solution and also is not what the documentation says. Am I missing something?

```
helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
related: #2994

**Comment by luisyonaldo** [comment]
Would be good to be able to discuss about it and know about its progress or if it hasen't been taking into consideration yet

**Comment by technosophos** [comment]
The summary is that we need to figure out how to install CRDs before even validating the rest of the manifest. This is a substantial change to the flow of installation, but it can be done with enough work.

**Comment by luisyonaldo** [comment]
Thanks, I'll try to read the code and see if I can help.
