### ISSUE TITLE
crashLoopBackOff

### ISSUE THREAD

**Issue by hamzeh-kh** [kubernetes/helm#3326]
What happened here?

kube-dns, kubernetes, and Tiller are keep craching

NAME                                   READY     STATUS             RESTARTS   AGE
heapster-4285517626-glm7x              1/1       Running            5          6d
kube-dns-638003847-n0l3g               1/3       CrashLoopBackOff   164        6d
kubernetes-dashboard-716739405-xzkf6   0/1       CrashLoopBackOff   72         6d
monitoring-grafana-2360823841-72vd3    1/1       Running            4          6d
monitoring-influxdb-2323019309-lmb0m   1/1       Running            4          6d
tiller-deploy-737598192-qwsw8          0/1       CrashLoopBackOff   84         6d

**Comment by jascott1** [comment]
Hi @hamzeh-kh 

If kube-dns is crashing I would double check CNI driver (network). Maybe check syslog or journalctl?

**Comment by technosophos** [comment]
Also, can you tell us what versions of Kubernetes and Tiller you are using? `helm version` and `kubectl version` will show that.

**Comment by hamzeh-kh** [comment]
Hi @jascott1  Could you tell me how should i check that, because i am new on this.

Hi @technosophos 
here you are the data:
helm version
Client: &version.Version{SemVer:"v2.3.0", GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:"clean"}
Error: cannot connect to Tiller

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Error from server (InternalError): an error on the server ("Service unavailable") has prevented the request from succeeding

**Comment by jascott1** [comment]
@hamzeh-kh 

Your kube-dns problem points to a possible problem with your cluster configuration (not Helm related) so I would start with checking the system logs. On Ubuntu, syslog can typically be found in /var/log/syslog. On Centos and systems using systemd, you will need to use `journalctl` command to view system log.

Also your version of Helm "2.3.0" is about 8 months old where as your Kubernetes version is much newer. Please upgrade to Helm latest stable (2.7.2) to work with K8s 1.8.x.

Let us know what you find and we can continue to find a solution.

**Comment by hamzeh-kh** [comment]
@jascott1 
Ok, I am going to check the system log and update the helm version.
apart of this, yesterday i face a new issue, which i think you know about that. 
At the beginning i defined an environment in order to start working with rancher, kubernetes and ONAP. at that day i set up everything correctly and system work smoothly. but a day later when i tried to run my environment, it wasn't available in rancher!, so i decided to create new one with another name. in the second environment, i encountered the tiller and dns issue as mentioned above. Yesterday my first environment backed in the rancher and second one gone and everything worked perfectly again. but today the first environment gone and second one backed in rancher and i faced same problem again with some more issue. 
I would like to know what is the problem that i can not seen both environments at the same time.
what i have to do to ride of this issue. 
please let me know the solution

**Comment by jascott1** [comment]
@hamzeh-kh 

Im not experienced with Rancher so I am no help there. Perhaps someone else has a suggestion. The first step is to get a stable Kubernetes cluster running that you can reproduce reliably. If you are not tied to Rancher you might consider the kops or kube-spray projects for cluster installation.

**Comment by hamzeh-kh** [comment]
Thanks the problem is solved

**Comment by meghalidhoble** [comment]
hi @hamzeh-kh , 
I am also observing similar issue, can you point me to the solution which worked for you? 
Thanks,
Meghali
