### ISSUE TITLE
helm install the server was unable to return a response

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/helm#3328]
I want to install HD on kubernetes with self-made helm. Because install need too much time, so I config timeout much bigger than default. But soon helm return a error, so helm install failed. so why？

[root@master3 ~]# helm install insightHD-stable-3.6.tgz --name=stable --timeout=10000 --namespace=bigdata --debug --wait
[debug] Created tunnel using local port: '39034'

[debug] SERVER: "localhost:39034"

[debug] Original chart version: ""
[debug] CHART PATH: /root/insightHD-stable-3.6.tgz

Error: release stable failed: the server was unable to return a response in the time allotted, but may still be processing the request (get persistentvolumeclaims data1-stable-agent-2)

**Comment by like-inspur** [comment]
Next I found error like this:
Error: timed out waiting for the condition

**Comment by jascott1** [comment]
Hi @like-inspur 

Do you have working persistent volumes setup?  That part of the error ('get persistentvolumeclaims data1-stable-agent-2') suggests to check into that.
