### ISSUE TITLE
Setup merge automation for this repo

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/helm#3333]
I'd like to setup merge automation for this repo. This means:

Use an OWNERS file, /approve, /lgtm to allow people to merge PR's into this repo:
- Create/update an OWNERS_ALIAS file that names the existing teams that have write/admin access to the repo
- Create/update an OWNERS file with approvers based on the write/admin access teams
- Configure prow to turn on the "approval" plugin for this repo
- Configure prow/tide to include this repo in the tide query

/assign

**Comment by mattfarina** [comment]
I'll bring this up in the next helm meeting for discussion.

What is the benefit for the helm repo to start using this?

**Comment by spiffxp** [comment]
/close
Based on discussion in #3334 it sounds like helm maintainers aren't interested in this.  Please /reopen if I'm incorrect
