### ISSUE TITLE
How to change a value of an env variable exposed thru charts via helm in a running pod? 

### ISSUE THREAD

**Issue by Abhishek-Srivastava** [kubernetes/helm#3340]
I am trying out to change an env variable in the pod thru helm which is read by the go service running inside the pod.  I don't want to re-install the pod. Is there a way to  do it thru helm?

**Comment by bacongobbler** [comment]
You can modify the chart template to write out a new environment variable to the deployment then call `helm update` on the chart, but it cannot be done without deleting the pod. Is there a particular reason you do not want to re-install the pod? Perhaps a bit more information on the chart and how you installed the app may be more useful.

Might I also suggest taking a look at the [Developing Charts](https://docs.helm.sh/developing_charts/#charts) guide; it might provide the information you seek. :)
