### ISSUE TITLE
2.8.0-rc.1 isn't greater than 2.5.0 (incompatible semVer)

### ISSUE THREAD

**Issue by BarDweller** [kubernetes/helm#3341]
When testing with the new 2.8.0-rc.1 release, I've noticed that charts with 
tillerVersion: '>=2.5.0'  
(or similar equivalents) are rejected as being incompatible with the current version. 

Removing the tillerVersion: attrib from the chart.yaml allows the chart to install as expected, but this means I can't just helm install stuff, but have to helm fetch, then edit etc.. 

Feels like a bug in the semantic version handling.. or possibly with the rc version formatting?

**Comment by mattfarina** [comment]
This is because `2.8.0-rc.1` is a pre-release. [Per the semver spec](https://semver.org/#spec-item-9),

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

The current version handling filters out pre-releases by default. If you want to include pre-releases set:

```
tillerVersion: '>=2.5.0-0'
```

Putting a pre-release on the end engages pre-release checking

**Comment by BarDweller** [comment]
Ah.. thanks.. I did hunt around for info on how it might be handling the pre-release tag, but didn't find anything useful.
The annoying thing is that if I want to use that workaround, I still have to edit the yamls in question, is there a way to deploy 2.8.0-rc.1 so that it pretends to be 2.8.0 (for testing purposes), so I can then test & deploy existing charts without alteration?

**Comment by bacongobbler** [comment]
This might be a good question to ask the chart maintainers. We should figure out if stable charts should allow being installed by tiller release candidates. I think it makes sense, but I'm curious on if there are any opposing views.

cc @kubernetes/charts-maintainers

**Comment by mattfarina** [comment]
@kubernetes/charts-maintainers

**Comment by BarDweller** [comment]
My thinking is the purpose of a Release Candidate is to allow people to test stuff, so you gain a chance to catch any issues missed before you cut the real release. 

With the versioning as is today, it's pretty difficult to test any real live charts with the RC, because they have to be fetched, and individually edited to allow them to be installed, for me, that means I'll probably just wait for the real release to try out the charts I use, because it'll be a lot less hassle to try.

It would be really handy to have a command line flag for helm that could be used to have charts treated as if they accepted pre-releases, even if they don't state that. It might go a long way to making it easier for people to try the RC with existing charts, improving the feedback you might get for the Release.
