### ISSUE TITLE
Problem setting hostname using Helm 

### ISSUE THREAD

**Issue by keithjohnhowe** [kubernetes/helm#3342]
I am installing a Helm chart that uses fluent-bit and fluentd. I am running into problems as fluent-bit requires the hostname of fluentd. I have used a value.yaml file to set this, however when I install the helm chart it adds to the hostname and fuent-bit gives me an error. 
 [ warn] net_tcp_fd_connect: getaddrinfo(host='fluentd.default.cluster.local')
Is there a way of either using environment variables to refer to the fluentd pod, or stopping helm adding changing the hostname ?

**Comment by bacongobbler** [comment]
This is a good question to ask over in https://github.com/kubernetes/charts/issues as it's a chart usability issue rather than Helm itself. Would you mind following up over there?

Thanks!
