### ISSUE TITLE
helm-v2.8.0-rc.1-windows-amd64.zip download link broken

### ISSUE THREAD

**Issue by dkirrane** [kubernetes/helm#3344]
Link for Windows download is broken

https://storage.googleapis.com/kubernetes-helm/helm-v2.8.0-rc.1-windows-amd64.zip

**Comment by bacongobbler** [comment]
Proper link is https://storage.googleapis.com/kubernetes-helm/helm-v2.8.0-rc.1-windows-amd64.tar.gz (tarball as opposed to a zip). Would you mind letting us know where you found the link so we can update it?

**Comment by bacongobbler** [comment]
Ah nvm I noticed it was on the release page. I've updated the link now.

cc @adamreese

**Comment by bacongobbler** [comment]
Just an FYI this was fixed in master via #3274 so v2.8.0 windows builds will be available via zip again.
