### ISSUE TITLE
Helm delete with --purge takes awhile

### ISSUE THREAD

**Issue by jhaynie** [kubernetes/helm#3346]
I have a helm chart that had several dependencies (>5).

When I remove the charts using `helm delete --purge` it can take awhile (like ~2-3m) to delete them all.  I suppose this is because Helm is waiting for Kubernetes to validate that all the Objects are deleted and cleaned up. 

When I delete directly using `kubectl` command in Kubernetes it returns immediately. It appears that Kubernetes is doing the cleanup in the background.

However, if I delete through Kubernetes they still show up in Helm - presumably because Tiller still has them in its ConfigMap?  

Is there a way to make helm delete run async?  For development, I want a much faster iteration cycle and don't mind if helm takes 2-3m in the background to cleanup. I'd prefer my build pipeline to not have to wait 2-3m before proceeding.

Could we add a `--no-wait` or `--async` flag to help to do something like this where the default behavior would be as it exists today (synchronous)?

**Comment by bacongobbler** [comment]
I think a `--no-wait` flag for `helm delete` would be do-able. It looks like tiller will return a response that says that [the delete is "in progress"](https://github.com/kubernetes/helm/blob/077be881c4ccb0e89e33432a286f20f47b9af17f/pkg/tiller/release_uninstall.go#L64-L68) so we could just watch for that response from tiller and return when it's in pending/exited.

How does that sound? Do you feel like contributing that feature flag? :)

**Comment by jhaynie** [comment]
OK, that's what I was hoping. I can see if I can make a PR.
