### ISSUE TITLE
Ignore errors on helm install or delete

### ISSUE THREAD

**Issue by garymurtagh** [kubernetes/helm#3352]
I am deploying multiple releases into a Kubernetes cluster using helm via an automated pipeline.
In most cases I create a new release when the job runs through the pipeline.

However in some cases I need to redeploy with the same release name.
Is there any facility or flag in helm to ignore an error on install or delete?
Sometimes errors are acceptable/expected so I don't want my pipeline to crash or have to add a bunch of custom logic to circumvent the (expected) error.

A flag kin to what kubectl has would be ideal:
```
--ignore-not-found=true
```

**Comment by SlickNik** [comment]
Hi @garymurtagh. I'm not aware of a flag like `--ignore-not-found=true` for helm. However, the `helm install` command does support a `--replace` flag which re-uses the given release name, even if that name is already used (caveat: this is not safe in a production environment). 

Would using this flag suffice for your use case?

**Comment by ehvattum** [comment]
using `helm upgrade <release> <chart> --install` installs or upgrades the release.
