### ISSUE TITLE
Is there a way to output the ENTIRE Kubernetes configuration to be piped in via kubectl?

### ISSUE THREAD

**Issue by cdrage** [kubernetes/helm#3354]
This may be unorthodox (and excuse me if this has been already asked). But is there a way to utilize `helm install` and output all the contents to yaml files / STDOUT?

Ex:

`helm install foo/bar -o yaml | kubectl create -f -`

I know this is unorthodox.

**Comment by bacongobbler** [comment]
Yes, this is exactly what `helm template` was designed to do. :)

**Comment by cdrage** [comment]
@bacongobbler Thanks fellow Canadian :)

**Comment by bacongobbler** [comment]
🍁 🏒 :canada:
