### ISSUE TITLE
chaincode error

### ISSUE THREAD

**Issue by harinishree** [kubernetes/helm#3355]
while i am trying to run the chaincode i am getting this error pls anyone help me to how to resolve this error
2018-01-05 05:04:30.127 UTC [shim] userChaincodeStreamGetter -> ERRO 003 Error trying to connect to local peer: context deadline exceeded

**Comment by SlickNik** [comment]
Hi @harinishree -- I suspect that you may have opened this issue in the Helm project by mistake. Helm is a tool for managing Kubernetes charts, and isn't associated with chaincode. :)

Perhaps you meant to open this issue in the [hyperledger/fabric](https://github.com/hyperledger/fabric) project instead?

**Comment by SlickNik** [comment]
@harinishree Since the kubernetes/helm project isn't really associated with either chaincode or the hyperledger/fabric project in any way, I'm going to go ahead and close this issue. Please feel free to re-open with more info in case we can be of any additional help. :)

Thanks!
