### ISSUE TITLE
Golang 1.10

### ISSUE THREAD

**Issue by javefang** [kubernetes/helm#3356]
Hi,

Just wonder if there is any plan on using Go1.9 for Helm? Go since 1.9 includes an important fix which makes Go to read CA from System keychain as well on macOS. (previously it only reads the SystemRoot keychain). 

Relevant change is here
https://github.com/golang/go/commit/4dbcacda961abb0ca3490dc06923fa7ab344d702#diff-21a1b245266cb97c8bdf720e71593956

Thanks

Xinghong

**Comment by mattfarina** [comment]
1.10 is due by January 31, 2018 and Go supports N and N-1 versions. 1.8 will soon be an unsupported version.

@javefang did you want to submit a PR to do builds using 1.9? See the CircleCI config.

**Comment by javefang** [comment]
EDIT: Golang 1.10 is out, tested and it actually require Helm to be compiled with 1.10 to make Helm to read MacOS's system keychain correctly. I have a local build of helm here and will test it for a few more days.

**Comment by mattfarina** [comment]
@javefang Would you be up for PR to the build pipeline? See https://github.com/kubernetes/helm/blob/master/.circleci/config.yml#L7

**Comment by bacongobbler** [comment]
see #3626
