### ISSUE TITLE
helm upgrade to statefulset no response

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes/helm#3359]
Hi,

tiller and helm client version both are v2.6.0
Kubernetes version: 1.7.4

I have one chart include statefulset resource, and I can run helm upgrade with success, but statefulset pods will not be replaced with new version (even with --recreate-pods parameter), but if I delete these pods manually, k8s will auto re-create new pods with new version, please help, thanks a lot.

**Comment by hiscal2015** [comment]
Anyone can help? Thanks.

**Comment by unguiculus** [comment]
See #3372 and #3373.

**Comment by hiscal2015** [comment]
Changed updateStrategy from ondelete to RollingUpdate, works fine now.
