### ISSUE TITLE
Helm installation on OpenStack behind floating IP

### ISSUE THREAD

**Issue by maxkondr** [kubernetes/helm#3360]
Hi,

**Environment**:

Kubernetes version (use kubectl version): v1.8
Cloud provider or hardware configuration: OpenStack
OS (e.g. from /etc/os-release): "Container Linux by CoreOS 1576.4.0 (Ladybug)"
Kernel (e.g. uname -a): Linux master-1.novalocal 4.13.16-coreos-r2
Others: OpenStack floating IP for master node is 192.168.67.107
RBAC enabled.

I have installed helm using:
> $ kubectl create serviceaccount tiller --namespace kube-system
$ kubectl create rolebinding tiller-kube-system --role=admin --serviceaccount=kube-system:tiller --namespace=kube-system
$ helm init --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' --net-host --host=192.168.67.107 --tiller-tls --tiller-tls-cert=./CA/helm/helm.crt --tiller-tls-key=./CA/helm/helm.key --tiller-tls-verify --tls-ca-cert=./CA/cluster-ca.crt --service-account tiller --tiller-namespace kube-system

Now I see that tiller is up and running:

>  $ kubectl get pods -n kube-system
NAME                                         READY     STATUS    RESTARTS   AGE
kube-apiserver-master-1.novalocal            1/1       Running   0          17m
kube-controller-manager-master-1.novalocal   1/1       Running   0          16m
kube-proxy-master-1.novalocal                1/1       Running   0          16m
kube-scheduler-master-1.novalocal            1/1       Running   0          17m
tiller-deploy-69c957c7c7-b7jmq               1/1       Running   0          14m
weave-net-p7nfb                              2/2       Running   0          16m

> $ kubectl describe pod tiller-deploy-69c957c7c7-b7jmq -n kube-system
....
Status:         Running
IP:             10.16.50.3

The IP 10.16.50.3 is internal OpenStack ip and is mapped to 192.168.67.107 to be reached from outside.

Now I try to use helm:

> $ helm list --host=192.168.67.107 --tls --tls-ca-cert=./CA/cluster-ca.crt --tls-cert=./CA/helm/helm.crt --tls-key=./CA/helm/helm.key --tls-verify --debug  --tiller-namespace=kube-system
[debug] SERVER: "192.168.67.107"
[debug] Key="./CA/helm/helm.key", Cert="./CA/helm/helm.crt", CA="./CA/cluster-ca.crt"
Error: context deadline exceeded

Could you please help to find the root of the issue?

**Comment by jascott1** [comment]
Hi @maxkondr 

Sorry you have having trouble. Have you verified `helm list` works from the server itself?

**Comment by maxkondr** [comment]
I have tried it from the server - with no luck.
It tries to resolve internal name:
> Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp: lookup master-1.novalocal on 8.8.8.8:53: no such host

despite the fact that I hass `--host=<IP>` param to `helm init`. Is there any way to avoid host resolution and use IPs only ?

**Comment by maxkondr** [comment]
Is it possible to setup ingress resource somehow to overcome this situation ?

**Comment by jascott1** [comment]
@maxkondr `helm list` should work from the server so we should start there. Can you remove the helm deployment and re-install with `helm init` without the `--override` and without `--host`?

Also I would check:
Tiller logs - Get pod name with `kubectl get po -n kube-system` and then `kubectl logs <tiiler pod name>`
Kube-dns - Do you have a dns service running for the cluster?

**Comment by maxkondr** [comment]
finally I have overcame this issue adding `--kubelet-preferred-address-types=InternalIP` to the apiserver manifest.

Now tiller is reachable from the Internet using floating IP and I can list/install charts as usual.
Closing.

**Comment by SlickNik** [comment]
Thanks for confirming @maxkondr! :) 👍
