### ISSUE TITLE
Flag --recreate-pods broken

### ISSUE THREAD

**Issue by unguiculus** [kubernetes/helm#3372]
The flag `--recreate-pods` no longer works as expected. There are two problems:

- If there is no patch, recreation is not executed. But excactly when there is no patch the flag would be useful. When the feature was added, the function would not immediately return when there was no patch. The following commit seems to have changed this: https://github.com/kubernetes/helm/commit/0f461ba8b55cdfad6d10c8fa9caa658ecddefbd6#diff-a483d6c0863082c3df21f4aad513afe2R394. Was this change intentional?
- Only resources with specific API versions have been eligible for a restart since the check for a selector was introduced in #1956. I'm working on a fix for the first point. I managed to get recreation working for Deployments with APIVersion `extensions/v1beta1` only, not for `apps/v1beta1` onwards. This should not depend on specific APIVersions.

**Comment by unguiculus** [comment]
#3373 fixes the first part of the problem.

**Comment by unguiculus** [comment]
I pushed another commit to the PR that fixes the second part.

**Comment by josdotso** [comment]
@bacongobbler , @mattfarina , @unguiculus 

Is it possible that this patch is the reason my upgrade with recreate pods immediately terminates all pods in my StatefulSet?  I find the same result with updateStrategy OnDelete as with RollingUpdate.  

Ideally, recreate pods would do a rolling update where appropriate and block where OnDelete is used -- and I believe this was previously the case (as of tiller `v2.8.0`).  OnDelete required manual intervention even when supplying recreate pods on `v2.8.0`. Rolling update allowed the recreate pods flag to roll through pods.

On a cluster with tiller `v2.8.2` I lost zookeeper quorum in this way. 

Thoughts?

**Comment by timm088** [comment]
@josdotso , did you ever find further detail about this?
