### ISSUE TITLE
Conditions as booleans is too restrictive

### ISSUE THREAD

**Issue by withnale** [kubernetes/helm#3376]
I was surprised when looking through the code that the evaluation of conditionals in `requirements.yaml` explcitly checks whether the value is boolean.

In other areas of helm, most notably when writing helm templates, the go template idea of 'truthy' is used to  evaluate conditions. I would suggest the same should apply here. This would mean that I do not need to create an additional boolean value - I would typically hang the conditional on the presence of absence of a string or map value.

**Comment by SlickNik** [comment]
@withnale Thanks for reporting this! Since this would change existing behavior I'm going to tag it as a "feature" (even though it's fairly small).

Also, is this something that you're looking at pushing up a PR for? :)

**Comment by withnale** [comment]
I'm quite happy to write the implementation for this. However, I've already got three PRs open waiting for review/further discussion - I'd really like to get some more traction on them TBH before creating more PRs.

**Comment by bacongobbler** [comment]
FYI @withnale we have responded on all 3 PRs. We're just waiting on your response. :)

**Comment by withnale** [comment]
lol. my mistake. I was watching the issues not the PRs - I had assumed something in the issue would say 'yes - this change would make sense - now lets sort out the PR'

I'll get right on them.
