### ISSUE TITLE
Helm with multiple paths in KUBECONFIG broken in 2.8.0

### ISSUE THREAD

**Issue by qrevel** [kubernetes/helm#3378]
With 2.8.0 release, my helm cannot connect to my server anymore.
I have the following setup
```
echo $KUBECONFIG
/Very Long Path/Infrastructure/production/.kube_config:/Users/quentinrevel/.config/kube
```

I get the following error
```
Error: could not get Kubernetes config for context "": stat /Very Long Path/Infrastructure/production/.kube_config:/Users/quentinrevel/.config/kube: no such file or directory
```

Both files exist on my computer.
Kubectl is working.

Thanks

**Comment by bacongobbler** [comment]
Curious, but why is $KUBECONFIG set like that? Shouldn't it be just the absolute path to a single kube config file? I have not seen this before. :)

**Comment by bacongobbler** [comment]
If this worked on kube 1.8, it might be something broken upstream as we don't interact with $KUBECONFIG directly; [client-go does](https://github.com/kubernetes/client-go/blob/54b86aca521e22773da8c35133b8e8421596de2b/tools/clientcmd/loader.go#L44).

**Comment by thatsk** [comment]
you have to set that path kubeconfig in your present directory like.
~/.kube/config

config is file for accessing kubernetes cluster

**Comment by qrevel** [comment]
Same as @torosent, the main config is in `~/.config/kube` and a context is specified in `...production/.kube_config`

**Comment by bacongobbler** [comment]
I've opened up #3401 that should hopefully fix this problem, however I have not tested this myself. If one of you could please confirm, that would be very helpful. Thanks! :)

**Comment by DylanGraham** [comment]
LGTM

**Comment by pjanuario** [comment]
I also use multiple configs and have the same problem, I think it's a common practice when u connect to multiple clusters. Thanks for the fix.
