### ISSUE TITLE
helm init --wait gets a context deadline exceeded

### ISSUE THREAD

**Issue by helgi** [kubernetes/helm#3379]
```
Running helm init --wait --upgrade --service-account tiller
$HELM_HOME has been configured at /root/.helm.
Error: could not ping Tiller: context deadline exceeded
```
Could be related to using upgrade?

v2.8.0

**Comment by bacongobbler** [comment]
Hey @helgi! We're not entirely sure what causes this issue, but there is some debugging going on at https://github.com/kubernetes/helm/issues/2409 with a few proposed solutions. It appears to be something at the kubernetes API level.

**Comment by helgi** [comment]
@bacongobbler great thanks! Will pay attention there as well

**Comment by TheOriginalAlex** [comment]
@bacongobbler: Ping me if you think #3238 could be the root of this issue.

**Comment by Chili-Man** [comment]
I am running into this issue as well (same helm version too) when I try to initialize helm with the `--init` flag.  It seems to wait for about 5 seconds and then it displays that error. 

Maybe it has to do with the default connection timeout being set to 5 seconds here:
https://github.com/kubernetes/helm/blob/master/pkg/helm/client.go#L306

**Comment by helgi** [comment]
@TheOriginalAlex I don't think an increase to the timeout will fix it as that is the wait time for a new connection to be established (https://godoc.org/google.golang.org/grpc#WithTimeout - We should move to using the context better tbh).

My guess is that `helm init --upgrade` is the culprit and won't happen without `--upgrade`; Telling Tiller to upgrade you need to start the connection, then it goes down to upgrade itself and we lose the connection. The `--wait` seems to assume that connection is not going to go away on upgrade, which is why it no longer has an active context.

Just a guess tho but seems upgrade needs to be handled specifically.

**Comment by Chili-Man** [comment]
@helgi  I am actually seeing this behavior without the `--upgrade` option:

```shell
helm init --wait
Error: could not ping Tiller: context deadline exceeded
```
so I'm not too sure that the `--upgrade` option is the problem

**Comment by shaneog** [comment]
I'm also getting this when I run `helm init --wait`

**Comment by bacongobbler** [comment]
@TheOriginalAlex would you mind taking a look into this?

**Comment by TheOriginalAlex** [comment]
@bacongobbler: Will take a look this upcoming weekend!  :)

**Comment by alexey-igrychev** [comment]
Wait algorithm changed here, https://github.com/kubernetes/helm/pull/3506.

**Comment by JerryWang20** [comment]
i still get this error when i use helm v2.13.1? what's the solution for it?
