### ISSUE TITLE
Run local registry in CircleCI and test `make container`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#338]
After doing some local testing, it looks like we might be able to run a local Docker registry inside of CircleCI and then at least test that `make container` runs.

**Comment by technosophos** [comment]
Depends on #339.

**Comment by technosophos** [comment]
Related to #352.

**Comment by adamreese** [comment]
We could also separate the build/push steps and have `make container` only require a docker host.

**Comment by adamreese** [comment]
Related to #307
