### ISSUE TITLE
is it safe to have sensitive information on the `values.yaml` file?

### ISSUE THREAD

**Issue by stevenbarragan** [kubernetes/helm#3380]
I've seen some helm charts where I have to set sensitive information on the `values.yaml` file. Either by editing the file directly or using the `--set` param. But either way it ends up in the `tiller` right?

Is it safe? is it a good practice?

example: https://github.com/kubernetes/charts/tree/master/stable/datadog

```
helm install --name my-release \
    --set datadog.apiKey=SENSITIVE_DATA stable/datadog
```

I know it ends up creating a secret with it, which is fine, but, as far as I know, the `apiKey` ends up on `tiller` as well. Should we worry about this?

**Comment by mikejk8s** [comment]
I personally don't place any sensitive data in my values.yaml. I place references to already generated secrets that I deploy to the server outside of helm and are encrypted. In your case I would have a gpg'd secret for datadog that I deploy outside of Helm and I would replace the deployments env: datadog_apikey with a secretkeyref. 

Most charts are set up to get a user quickly to the goal of running $x application. You'll need to modify some of them quite a bit to get them to be production ready.

**Comment by helgi** [comment]
It is not safe, I would recommend helm-secrets (a plugin) or similar tools to inject them as late as possible in your deploy process
