### ISSUE TITLE
grpc.ErrorDesc is deprecated

### ISSUE THREAD

**Issue by PureWhiteWu** [kubernetes/helm#3381]
![image](https://user-images.githubusercontent.com/3314335/35317790-631c71c0-0113-11e8-8fdf-c385347f4f0a.png)

![image](https://user-images.githubusercontent.com/3314335/35317787-5da9d570-0113-11e8-9b89-133d800fda51.png)

**Comment by SlickNik** [comment]
@PureWhiteWu Thanks for reporting this! Is this something that you are working on a PR for? :)

**Comment by PureWhiteWu** [comment]
@SlickNik I had intended to, but was too busy today. If it's not urgent, I can send one maybe tomorrow.

**Comment by SlickNik** [comment]
@PureWhiteWu -- not urgent. Just wanted to ensure that someone else didn't start looking at it in the meanwhile. :)

Also, thanks for taking a look! Appreciate it.

**Comment by PureWhiteWu** [comment]
@SlickNik PR sent. #3383
