### ISSUE TITLE
Helm 2.8.0 with CRDs: unable to find api field in struct Unstructured for the json field "metadata"

### ISSUE THREAD

**Issue by Stono** [kubernetes/helm#3382]
Hi, 
We're seeing this a lot since updating to 2.8.0.  This only happens on subsequent upgrades to existing charts.

```
❯ helm upgrade --reset-values --debug --wait --install --namespace default --version 0.1.379 at-sauron-web-mobile . -f values.yaml -f dev.yaml
[debug] Created tunnel using local port: '56621'

[debug] SERVER: "127.0.0.1:56621"

Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct Unstructured for the json field "metadata"
```

This particular chart is upgrading the following components:
  - configmap
  - service
  - deployment 
  - ingress

If i take the `--dry-run` output and put it into a file and do `kubectl apply -f` myself, it works fine

**Comment by Stono** [comment]
Hi,
This is proving to be a huge problem for us, we've got 10 or so applications having intermittent failures.

All clients and server are 2.8.0

```
Fetching cluster endpoint and auth data.
kubeconfig entry generated for delivery-platform.
Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct Unstructured for the json field "metadata"
```

**Comment by thomastaylor312** [comment]
@Stono I'll ping some people on this

**Comment by Stono** [comment]
Cheers @thomastaylor312

**Comment by technosophos** [comment]
From Slack:

- Kube version is 1.8.6/GKE and Helm 2.7 was working fine
- I suspect Deployment may be the culprit, since that had notable changes between Kube 1.8 and Kube 1.9, and here we have a library incompatibility

Probably the best testing procedure would be to dump the generated chart, and then dump the actually installed resources and look for structural differences that might tip us off to some sort of transform that happened on a resource.

**Comment by Stono** [comment]
OK I think you might be right on the money.

  - Deployed: `extensions/v1beta1`
  - Helm Template: `apiVersion: apps/v1beta2`

my template is `apiVersion: apps/v1beta2`, so it looks like after the initial deployment, for whatever reason what is on the server is `v1beta1`

**Comment by munnerz** [comment]
@Stono the server will respond with a manifest in the version of whatever you ask it for, it isn't necessarily stored in this version in etcd.

You can ask for a specific version of a resource with something like:

`kubectl get deployments.v1beta2.apps -o yaml`

**Comment by mattfarina** [comment]
The setup, as I understand it, is in both circumstances helm/tiller is talking to k8s 1.8.6. Helm 2.7.2 is built to k8s 1.8 libs (e.g., apimachinery) while helm 2.8 is built to k8s 1.9 versions of the libs.

I think the error is being generated inside of [LookupPatchMetadataForStruct](https://github.com/kubernetes/kubernetes/blob/32913ab0cdc5c4dde50e50ecffa4c1e9c6d6a150/staging/src/k8s.io/apimachinery/third_party/forked/golang/json/fields.go#L68). This is notable because the error and function signature didn't exist until k8s 1.9. [Here's the PR that changed it to the current state](https://github.com/kubernetes/kubernetes/commit/f1ad84a2c3d4c6680091250967e96108cc9dd652#diff-6d77075bc1eb9e91f07508b3014a89b1).

Looking at the type as `Unstructured` which looks like the following the few places it shows up in code:

```go
type Unstructured struct {
	// Object is a JSON compatible map with string, float, int, bool, []interface{}, or
	// map[string]interface{}
	// children.
	Object map[string]interface{}
}
```

and that the field name is "metadata" may help us start to find the culprit.

**Comment by technosophos** [comment]
Might have to ask @adamreese for help on this one. This is his area of expertise.

**Comment by mattfarina** [comment]
@k8s-mirror-api-machinery-bugs any idea why we'd experience issues working with a k8s 1.8 cluster (client-go/api-machinery for k8s 1.9)?

**Comment by munnerz** [comment]
I've bumped our e2e tests for a couple of our projects to use Helm 2.8.0 and am experiencing a similar thing in Kubernetes 1.9 and 1.7. I'd imagine also 1.8, but our e2e tests look like they flaked on that run:

- https://prow.build-infra.jetstack.net/log?job=navigator-e2e-v1-9&id=148
- https://prow.build-infra.jetstack.net/log?job=navigator-e2e-v1-7&id=610
- https://prow.build-infra.jetstack.net/log?job=navigator-e2e-v1-8&id=627

Namely:

```Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct Unstructured for the json field "spec"```

so it appears the issue isn't constrained to just metadata, nor isolated to an API version 😄. My guess would be that the way unstructured fields are handled in the new machinery (client side) is different.

I am *also* seeing test failures on another project of ours, this time when deploying a particular chart for the first time. This happens consistently against k8s 1.7, 1.8 and 1.9. I'll need to do a bit more digging to get us some better logs out of this one, as it seems to be hitting the `--wait` timeout. For now I'd theorise that these failures are unrelated to this issue (although it does seem to be a 2.8.0 regression): https://storage.googleapis.com/jetstack-logs/pr-logs/pull/jetstack_cert-manager/276/cert-manager-e2e-v1-8/89/build-log.txt

/cc @sttts are you aware of any changes to Unstructured since release-1.8 that could cause this sort of thing?

**Comment by sttts** [comment]
Looks like something related to strategic merge patches as the error messages come from LookupPatchMetadataForStruct called from https://github.com/kubernetes/kubernetes/blob/f1ad84a2c3d4c6680091250967e96108cc9dd652/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go#L74.

**Comment by Stono** [comment]
Hey all, just wondering if you're managing to make any progress with this?

**Comment by thomastaylor312** [comment]
@Stono We just talked about this in the dev call. Pretty much all of the maintainers with free cycles will be trying to take a look at this today and tomorrow

**Comment by thomastaylor312** [comment]
@sttts Is there any chance you might have some time for debugging this with one of the maintainers today and tomorrow?

**Comment by jascott1** [comment]
I tried with a foo chart with Helm 2.8.0 and k8s 1.8.4 but could not reproduce. Changing cluster to 1.8.6 now but if anyone has a chart that demonstrates the problem please share.

**Comment by adamreese** [comment]
I think this unrelated to 1.9.  This test is with kubectl v1.8 on a v1.8 cluster.

Running `kubectl apply` on a `apps/v1beta2` deployment creates a `apps/v1beta1` but the version in `kubectl.kubernetes.io/last-applied-configuration` is `v1beta2`

```
$ cat <<EOF | kubectl apply -f -
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: apps-bug
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: apps-bug
        image: nginx
EOF

deployment "apps-bug" created

$ kubectl get deployment apps-bug -o jsonpath="{.apiVersion}"
extensions/v1beta1

$ kubectl apply view-last-applied deployment apps-bug
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations: {}
  name: apps-bug
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: apps-bug
```

**Comment by bacongobbler** [comment]
![wat](http://i0.kym-cdn.com/photos/images/facebook/000/173/575/25810.jpg)

**Comment by bacongobbler** [comment]
Yep. I can also confirm that I was able to produce the same output from the API with kubectl v1.8.0 and kubernetes v1.8.7. This is an upstream thing and is not in any way related to #3234, so I'm going to remove it from the 2.8.1 milestone as it's out of our control at this point.

**Comment by mattfarina** [comment]
@adamreese @bacongobbler I'm not sure I understand the link to the original error in the issue which read:

```
Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct Unstructured for the json field "metadata"
```

Also, when helm upgraded to client-go/apimachinery for k8s 1.8 we didn't have reported issues of this.

Can you fill me in on the link and how the "metadata" json error relates?

**Comment by bismarck** [comment]
We're seeing this issue when trying to update a CRD.  I wasn't sure if this was related to kubernetes/kubernetes#58017?

**Comment by mattfarina** [comment]
I've done a little more digging and discovered that...

https://github.com/kubernetes/helm/blob/1f87bf031ab12d6444067880ec07df4f3889d3a4/pkg/kube/client.go#L390-L417

The `versionedObject` on line 405 is returning a struct type of `Unstructured`. If you dig down into `strategicpatch.CreateTwoWayMergePatch` and functions it calls this is turned into a `schema` and `LookupPatchMetadataForStruct` is called for fields like `metadata` on it which don't exist.

Still investigating.

**Comment by technosophos** [comment]
Is everyone who has had this issue running on GKE? Can anyone reproduce on Minikube or any other distribution?

**Comment by mattfarina** [comment]
Folks, we're having a little trouble recreating the original problem in order to understand the root and test any fixes. If you are experiencing this problem could you please point us to a chart and setup we could use to recreate the problem. The more detail the better.

**Comment by Stono** [comment]
@mattfarina see slack (helm-dev)

**Comment by mattfarina** [comment]
Here's where my testing is at:

* I can't replicate a problem in 1.9.0 (via minikube)
* I can't replicate a problem in 1.8.7 in GKE
* I **can** produce other in **1.8.6** in GKE. These issues were related to communications with tiller.

I wonder if there's an issue with 1.8.6 or with the setup (is it a forked API server in gke?) in GKE. If anyone has more insight it would be appreciated.

**Comment by bacongobbler** [comment]
@mattfarina did you happen to test using @adamreese's steps in https://github.com/kubernetes/helm/issues/3382#issuecomment-362435708? I was able to reproduce the described behaviour across multiple cluster versions, including 1.9.0. We can 🍐 on that later today if you'd like to do a deep dive.

**Comment by mattfarina** [comment]
@bacongobbler That's comment details a different issue from the original at the top.

**Comment by Stono** [comment]
OK, further testing on my part has narrowed this down to a CustomResource called `RouteRule` in the `config.istio.io/v1alpha2` api, although I suspect the problem will be with all CRDs.

To replicate the problem I've managed to pull apart the bits of the chart that cause the issue:

**Create the CRD**

You'll need to do this before running the chart with a simple `kubectl apply -f`
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: helm-platform-istio
    chart: helm-platform-istio-0.1.0
    heritage: Tiller
    release: istio
  name: routerules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    listKind: RouteRuleList
    plural: routerules
    singular: routerule
  version: v1alpha2
```

Then, create a simple chart with a single template:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: some-service-policy
  labels:
    another: label
    app: at-consumer-platform
    chart: helm-at-consumer-platform-0.1.184
    heritage: Tiller
    release: at-consumer-platform
    version: "23"
spec:
  destination:
    name: some-service
  httpReqRetries:
    simpleRetry:
      attempts: 1
  httpReqTimeout:
    simpleTimeout:
      timeout: 1
```

Install it:
```
bash-4.2$ helm upgrade --reset-values --install --namespace default --version 0.1.183 at-consumer-platform .
Fetching cluster endpoint and auth data.
kubeconfig entry generated for delivery-platform.
Release "at-consumer-platform" does not exist. Installing it now.
NAME:   at-consumer-platform
LAST DEPLOYED: Mon Feb  5 17:07:39 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1alpha2/RouteRule
NAME                 AGE
some-service-policy  1s
```

Now, edit the file and change the `version` line to a different number than `23`:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: some-service-policy
  labels:
    another: label
    app: at-consumer-platform
    chart: helm-at-consumer-platform-0.1.184
    heritage: Tiller
    release: at-consumer-platform
    version: "24"
spec:
  destination:
    name: some-service
  httpReqRetries:
    simpleRetry:
      attempts: 1
  httpReqTimeout:
    simpleTimeout:
      timeout: 1
```

And then run your helm install again:
```
bash-4.2$ helm upgrade --reset-values --install --namespace default --version 0.1.183 at-consumer-platform .
Fetching cluster endpoint and auth data.
kubeconfig entry generated for delivery-platform.
Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct Unstructured for the json field "metadata"
```

**Comment by Stono** [comment]
Oh it looks like @bismarck confirms the CRD issue and looks like it is to do with https://github.com/kubernetes/kubernetes/issues/58017

**Comment by mattfarina** [comment]
@Stono Thanks for chasing this down and for finding the core issue (within api-machinery)

Using the example above I was able to reproduce the issue using minikube (1.9.0)

**Comment by mattfarina** [comment]
@sttts It appears this is a bug inside of api-machinery.

**Comment by bacongobbler** [comment]
Updated the title to reflect the bug. @adamreese the bug you found is probably unrelated but might also be good to track separately just so we have a pulse on that one as well. I'll see if someone's already submitted that issue upstream.

**Comment by bacongobbler** [comment]
filed https://github.com/kubernetes/kubernetes/issues/59362 to track the other issue

**Comment by mattfarina** [comment]
FYI, I created a repo with a test folks can run to reproduce. I've used this against minikube. https://github.com/mattfarina/bad-chart-2.8-1.9

**Comment by mattfarina** [comment]
To close the loop, I've also posted to the SIG API Machinery list at https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/Mv5ya3HcVE0. Their next meeting is on Feb 14th. I can't make it but if someone else wants to go and bring it up there (if we don't have direction already). You can find it on the calendar at https://kubernetes.io/community/

**Comment by mattfarina** [comment]
Adding this back to the 2.8.1 bugfix release. I think #3459 fixes it.

Thanks to @liggitt for the help.

**Comment by Stono** [comment]
Great work getting to the bottom of it and getting a fix into 2.8.1 :-)

**Comment by balboah** [comment]
yay, love when things are fixed a couple of days before experiencing the issue :)

**Comment by flah00** [comment]
Sorry to resurrect a zombie, but I just ran into this, using helm-2.8.2, tiller-2.8.2, kubectl client 1.9.2 and kubectl server 1.8.4+coreos.0.

**Comment by macropin** [comment]
We're seeing this as well with helm v2.8.2, tiller v2.8.2, kubectl v1.9.7, kubernetes v1.9.8.

**Comment by liggitt** [comment]
> We're seeing this as well with helm v2.8.2, tiller v2.8.2, kubectl v1.9.7, kubernetes v1.9.8.

On every patch request, or occasionally on contentious resources?

**Comment by macropin** [comment]
We're using helm to deploy a custom application. It appears to happen on every deployment.

**Comment by liggitt** [comment]
> We're using helm to deploy a custom application. It appears to happen on every deployment.

What are the custom resources involved? What component is submitting patches for those custom resources? Do you have details of the API requests (body, url, submitted content-type) that are returning this error?

**Comment by jimethn** [comment]
We're having this problem with normal Deployments, we don't have any CRDs. Helm 2.10.0 and Kubernetes 1.10.5.

**Comment by Stono** [comment]
@jimethn - I've seen this error manifest when you're using integer values where they should be strings, for example in your `env` settings for your deployment, do you have `value: 1`, instead of `value: "1"`

**Comment by jimethn** [comment]
@Stono thank you for the swift reply. I'm not seeing that anywhere with integers, although we do use unquoted strings all over the place. Might that be related? My apologies for posting in this closed thread. As we refine the issue further we may open a fresh ticket and refer to this one.

**Comment by Stono** [comment]
Ya another burn is using `true` instead of `"true"`.  I'm not saying this is your issue btw, you could have a genuine problem :d if it isn't this - i suggest a new issue where you paste your manifest.

**Comment by pkelleratwork** [comment]
I am experiencing this issue on 
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
helm chart uses
```
    annotations:
      checksum/config: {{ include (print $.Template.BasePath "/checksum-configmap.yaml") . | sha256sum }}
```

getting error 
```
Error: UPGRADE FAILED: failed to create patch: unable to find api field in struct PodTemplateSpec for the json field "annotations"
```

**Comment by cblecker** [comment]
@pkelleratwork You're putting the annotations at the wrong level. They need to be under metadata, not directly as part of the PodTemplateSpec
