### ISSUE TITLE
`helm init --wait` does not wait for tiller pod to be ready

### ISSUE THREAD

**Issue by kenden** [kubernetes/helm#3393]
# Description

`helm init --wait` does not wait for the tiller pod to be ready

# Repro steps
```sh
$ helm reset --force # delete tiller

# install tiller with --wait and try to use helm right after
$ helm init --wait && helm list
$HELM_HOME has been configured at /Users/redacted/.helm.
Error: could not ping Tiller: context deadline exceeded

$ kubectl get deployment tiller-deploy -w  # wait for tiller to become ready
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
tiller-deploy   1         1         1            1           1m

$ helm list  # showing helm works now tiller is ready
NAME                	REVISION	UPDATED                 	STATUS  	CHART                   	NAMESPACE
curator             	1       	Tue Jan 16 13:30:08 2018	DEPLOYED	curator-0.1.0           	crons
...
```

# Expected
`helm init --wait` should wait for the tiller pod to be ready

# Versions

```sh
$ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}

$ uname -a
Darwin apollo 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```

**Comment by TheOriginalAlex** [comment]
Looks like a dup of #3379.  Might have to increase the timeout from 5 seconds to something higher.

**Comment by helgi** [comment]
I believe this ticket can be closed now that #3379 is resolved

**Comment by bacongobbler** [comment]
thanks @helgi!

**Comment by Flowkap** [comment]
Is there already a release for it?

**Comment by bacongobbler** [comment]
Yes, 2.8.2

**Comment by yanhongwang** [comment]
Hi, @bacongobbler 

I use helm 2.8.2 version.
I also use 'helm init --wait'.
But, it happened erro message like below.

Error: tiller was not found. polling deadline exceeded
Error: could not find a ready tiller pod

Thanks.

Hong

**Comment by bacongobbler** [comment]
if the polling deadline exceeded then it failed waiting for tiller to come up. Can you please open a new issue for this case? Sounds like tiller failed to start. Thanks!

**Comment by yanhongwang** [comment]
@bacongobbler ,

Thanks for reply.

By the way, I ran again my automatic script, but it passed without error.
If that happen again, I will open a new issue for that.
Thanks again.

Hong
