### ISSUE TITLE
Can't render template with single curly braces and substitutions.

### ISSUE THREAD

**Issue by ketchoop** [kubernetes/helm#3412]
Hello. I've got a template with strings like this: `{ exometer_report_graphite, [hackney, "{{ .Values.BaseName }}", nb_requests], [value], 10000, true}`. When I try to render the template I get following error: *unclosed action*. When I delete this string the error disappears. How could I resolve this thing?

**Comment by bacongobbler** [comment]
Can you share your chart with us? The single curly brackets won't cause an issue. "unclosed action" normally shows up when a double curly bracket is unclosed in the template.

**Comment by ketchoop** [comment]
We've found a way to fix the problem. Just deleted spaces in substitutions. Thank you for reply! I'm going to close the issue
