### ISSUE TITLE
helm failing to connect for pretty much every command

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/helm#3416]
I've been trying to install spinnaker for a while and today I have started getting this all of a sudden:

```
$ helm ls
Error: Get https://100.64.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 100.64.0.1:443: i/o timeout
```

I can still `kubectl get pods` and stuff so the functionality of the cluster is still unaffected, but I can't reset, init or install anything

Versions info if needed (cluster on AWS). Note that helm was able to talk to the tiller pod to get the version number...

```
$ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by jascott1** [comment]
Hi @huang-jy 

Are you running Helm client on the server or local?

**Comment by huang-jy** [comment]
local.

The tiller pod is in a Kubernetes cluster in AWS.

For some reason I was getting that on both my personal and my corporate test k8s cluster, even after wiping ~/.helm

And now, for some weird reason, it's suddenly decided to work.... and I have just managed to install spinnaker.

Oh well, I'll close this issue -- can't replicate the issue problem now...

Sorry for wasting your time.
