### ISSUE TITLE
[Question] about checksum/config

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes/helm#3418]
Hi, 

How can I define multiple checksum/config?
like this:
```
  annotations:
      checksum/config: {{ include (print $.Template.BasePath "/configmap1.yaml") . | sha256sum }}
      checksum/config: {{ include (print $.Template.BasePath "/configmap2.yaml") . | sha256sum }}
```
What's the correct definition? One config one line? Thanks.

**Comment by unguiculus** [comment]
Just give the annotations different names. The name doesn't matter.

**Comment by hiscal2015** [comment]
@unguiculus Do you mean "checksum/config" is not a fixed name? I can define it like "checksum/nginxconfig" or something else?

**Comment by bacongobbler** [comment]
yes.

**Comment by hiscal2015** [comment]
Thanks both.

**Comment by nmrkic** [comment]
Yes, thanks guys :)
