### ISSUE TITLE
Portal and policy Pods

### ISSUE THREAD

**Issue by hamzeh-kh** [kubernetes/helm#3420]
Hi, 
Dose anyone know what the portal and policy are not shown in the namespaces!

I already run the portal , policy pods.

Also the ete.k8s.sh is not shown in the dockerdata-nfs!

NAMESPACE     NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                      AGE       SELECTOR
default       kubernetes                    ClusterIP   10.43.0.1       <none>        443/TCP                                                                      1d        <none>
demo-aai      aai-resources                 ClusterIP   None            <none>        8447/TCP,5005/TCP                                                            3h        app=aai-resources
demo-aai      aai-service                   NodePort    10.43.255.254   <none>        8443:30233/TCP,8080:30232/TCP                                                3h        app=aai-service
demo-aai      aai-traversal                 ClusterIP   None            <none>        8446/TCP,5005/TCP                                                            3h        app=aai-traversal
demo-aai      elasticsearch                 ClusterIP   None            <none>        9200/TCP                                                                     3h        app=elasticsearch
demo-aai      gremlin                       ClusterIP   None            <none>        8182/TCP                                                                     3h        app=gremlin
demo-aai      hbase                         ClusterIP   None            <none>        2181/TCP,8080/TCP,8085/TCP,9090/TCP,16000/TCP,16010/TCP,16201/TCP            3h        app=hbase
demo-aai      model-loader-service          NodePort    10.43.90.89     <none>        8443:30229/TCP,8080:30210/TCP                                                3h        app=model-loader-service
demo-aai      search-data-service           ClusterIP   None            <none>        9509/TCP                                                                     3h        app=search-data-service
demo-aai      sparky-be                     ClusterIP   None            <none>        9517/TCP                                                                     3h        app=sparky-be
demo-consul   consul-server                 NodePort    10.43.50.30     <none>        8500:30270/TCP,8301:30271/TCP                                                3h        app=consul-server
demo-dcae     dcae-collector-common-event   NodePort    10.43.237.57    <none>        8080:30236/TCP,8443:30237/TCP,9999:30238/TCP                                 3h        app=dcae-collector-common-event
demo-dcae     dcae-collector-dmaapbc        NodePort    10.43.1.27      <none>        8080:30239/TCP,8443:30240/TCP                                                3h        app=dcae-collector-dmaapbc
demo-dcae     dcae-controller               NodePort    10.43.13.244    <none>        8000:30234/TCP,9998:30235/TCP                                                3h        app=dcae-controller
demo-dcae     dmaap                         ClusterIP   None            <none>        3904/TCP,3905/TCP                                                            3h        app=dmaap
demo-dcae     kafka                         ClusterIP   None            <none>        9092/TCP                                                                     3h        app=kafka
demo-dcae     zldciad4vipstg00              NodePort    10.43.219.236   <none>        5432:30245/TCP                                                               3h        app=dcae-pgaas
demo-dcae     zookeeper                     ClusterIP   None            <none>        2181/TCP                                                                     3h        app=zookeeper
demo-msb      msb-consul                    NodePort    10.43.229.5     <none>        8500:30500/TCP                                                               3h        app=msb-consul
demo-msb      msb-discovery                 NodePort    10.43.17.21     <none>        10081:30081/TCP                                                              3h        app=msb-discovery
demo-msb      msb-eag                       NodePort    10.43.241.33    <none>        80:30082/TCP                                                                 3h        app=msb-eag
demo-msb      msb-iag                       NodePort    10.43.124.82    <none>        80:30080/TCP                                                                 3h        app=msb-iag
demo-mso      mariadb                       NodePort    10.43.204.189   <none>        3306:30252/TCP                                                               3h        app=mariadb
demo-mso      mso                           NodePort    10.43.219.6     <none>        8080:30223/TCP,3904:30225/TCP,3905:30224/TCP,9990:30222/TCP,8787:30250/TCP   3h        app=mso
demo-robot    robot                         NodePort    10.43.43.22     <none>        88:30209/TCP                                                                 3h        app=robot
demo-sdc      sdc-be                        NodePort    10.43.36.33     <none>        8443:30204/TCP,8080:30205/TCP                                                3h        app=sdc-be
demo-sdc      sdc-cs                        ClusterIP   None            <none>        9042/TCP,9160/TCP                                                            3h        app=sdc-cs
demo-sdc      sdc-es                        ClusterIP   None            <none>        9200/TCP,9300/TCP                                                            3h        app=sdc-es
demo-sdc      sdc-fe                        NodePort    10.43.3.194     <none>        9443:30207/TCP,8181:30206/TCP                                                3h        app=sdc-fe
demo-sdc      sdc-kb                        ClusterIP   None            <none>        5601/TCP                                                                     3h        app=sdc-kb
demo-sdnc     dbhost                        ClusterIP   None            <none>        3306/TCP                                                                     3h        app=sdnc-dbhost
demo-sdnc     dbhost-read                   ClusterIP   10.43.168.244   <none>        3306/TCP                                                                     3h        app=sdnc-dbhost
demo-sdnc     nfs-provisioner               ClusterIP   10.43.216.75    <none>        2049/TCP,20048/TCP,111/TCP,111/UDP                                           3h        app=nfs-provisioner
demo-sdnc     sdnc-dgbuilder                NodePort    10.43.49.112    <none>        3000:30203/TCP                                                               3h        app=sdnc-dgbuilder
demo-sdnc     sdnc-portal                   NodePort    10.43.30.83     <none>        8843:30201/TCP                                                               3h        app=sdnc-portal
demo-sdnc     sdnctldb01                    ClusterIP   None            <none>        3306/TCP                                                                     3h        app=sdnc-dbhost
demo-sdnc     sdnctldb02                    ClusterIP   None            <none>        3306/TCP                                                                     3h        app=sdnc-dbhost
demo-sdnc     sdnhost                       NodePort    10.43.82.51     <none>        8282:30202/TCP,8201:30208/TCP,8280:30246/TCP                                 3h        app=sdnc
demo-vid      vid-mariadb                   ClusterIP   None            <none>        3306/TCP                                                                     3h        app=vid-mariadb
demo-vid      vid-server                    NodePort    10.43.16.7      <none>        8080:30200/TCP                                                               3h        app=vid-server
kube-system   heapster                      ClusterIP   10.43.31.135    <none>        80/TCP                                                                       1d        k8s-app=heapster
kube-system   kube-dns                      ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP                                                                1d        k8s-app=kube-dns
kube-system   kubernetes-dashboard          ClusterIP   10.43.113.123   <none>        80/TCP                                                                       1d        k8s-app=kubernetes-dashboard
kube-system   monitoring-grafana            ClusterIP   10.43.21.118    <none>        80/TCP                                                                       1d        k8s-app=grafana
kube-system   monitoring-influxdb           ClusterIP   10.43.202.229   <none>        8086/TCP                                                                     1d        k8s-app=influxdb
kube-system   tiller-deploy                 ClusterIP   10.43.228.50    <none>        44134/TCP                                                                    1d        app=helm,name=tiller

In addition, i have checked the pods via the following command:
kubectl get pods --all-namespaces -a | grep 2/2
so i received this information, which the portal and policy are not there too.
 demo-aai      model-loader-service-5c9d84589b-6pz5q          2/2       Running            0          4h
demo-aai      search-data-service-6fc58fd7cc-qhzdc           2/2       Running            0          4h
demo-aai      sparky-be-684d6759bc-jl5wx                     2/2       Running            0          4h
demo-mso      mso-6c4dd64bf9-nhdjs                           2/2       Running            2          4h
demo-sdnc     sdnc-dbhost-0                                  2/2       Running            1          4h
demo-vid      vid-server-56d895b8c-2nctp                     2/2       Running            0          3h

**Comment by jascott1** [comment]
Hi @hamzeh-kh 

There is a lot of output here. Could you explain more about what charts you are trying to run and more detail about the statement `Also the ete.k8s.sh is not shown in the dockerdata-nfs!`

**Comment by hamzeh-kh** [comment]
Hi @jascott1 
let me explain in detail what i am doing:
I am implementing ONAP on kubernetes. For this, i using Rancher to to connect to the kubernetes cluster.
Here is the link of implementation: https://wiki.onap.org/display/DW/ONAP+on+Kubernetes
In this implementation, we can run 86 docker containers by installing Rancher, Kubernetes server and client, Docker and Helm. Once all requirements done then should create and configure the Pods. Next should run the ONAP with running pods ( few number of pods or all the pods).
for less RAM run enough pods : ./createAll.bash -n onap -a robot|appc|aai
for more RAM: ./createAll.bash -n onap
Once it done, the sdc, portal, aai, vid, mso, appc, sdnc and policy should be shown as follow.
root@kos1001:~/oom1004/oom/kubernetes/oneclick# kubectl get pods --all-namespaces -a | grep 2/2
onap-aai              aai-resources-338473047-8k6vr           2/2       Running     0          1h
onap-aai              aai-traversal-2033243133-6cr9v          2/2       Running     0          1h
onap-aai              model-loader-service-3356570452-25fjp   2/2       Running     0          1h
onap-aai              search-data-service-2366687049-jt0nb    2/2       Running     0          1h
onap-aai              sparky-be-3141964573-f2mhr              2/2       Running     0          1h
onap-appc             appc-1335254431-v1pcs                   2/2       Running     0          1h
onap-mso              mso-3911927766-bmww7                    2/2       Running     0          1h
onap-policy           drools-2302173499-t0zmt                 2/2       Running     0          1h
onap-policy           pap-1954142582-vsrld                    2/2       Running     0          1h
onap-policy           pdp-4137191120-qgqnj                    2/2       Running     0          1h
onap-portal           portalapps-4168271938-4kp32             2/2       Running     0          1h
onap-portal           portaldb-2821262885-0t32z               2/2       Running     0          1h
onap-sdc              sdc-be-2986438255-sdqj6                 2/2       Running     0          1h
onap-sdc              sdc-fe-1573125197-7j3gp                 2/2       Running     0          1h
onap-sdnc             sdnc-3858151307-w9h7j                   2/2       Running     0          1h
onap-vid              vid-server-1837290631-x4ttc             2/2       Running     0          1h

But in my implementation the portal and policy is not available!
even when i run the ONAP portal by using VNC-portal, i can not find the portal in the ONAP. 
In principle i tried to added the portal but a error is comes up that "the portal is already exist".

Regarding to ete.k8s.sh, you are right, the ete.k8s.sh is not in the dockerdata-nfs/demo/robot.

Please let me know what is your advise. actually i am new on the ONAP and selected oNAP on kubernetes in order to run on devices with low specification (less RAM and CPU).

**Comment by jascott1** [comment]
@hamzeh-kh 

Looking at one of the policy deployment files here
https://git.onap.org/oom/tree/kubernetes/policy/templates/dep-drools.yaml

There is an if condition that will make the policy deployment/pod not be installed:
`{{ if not .Values.disablePolicyDrools }}`

Please check the source values.yaml file (likely specified in one of those .sh files) for that property ("disablePolicyDrools", etc.) for each of the policies. It is likely that it is being disabled there. 

As for NFS, did you complete the NFS setup specified in the doc?
https://wiki.onap.org/pages/viewpage.action?pageId=16010229

**Comment by hamzeh-kh** [comment]
@jascott1 
Thanks for your kind help.
Should i change the disablePolicyDrools to enablePolicyDrools in the dep-drools.yaml file? i put .yaml file at the end of this conversation.
Regarding to .sh file, there is no any .sh files in the dockerdata-nfs. its completely empty.

Regarding to NFS, No i didnt complete that because it wasn't explained in the ONAP on Kubernetes. So i am going to complete the NFS setup and try ete.k8s.sh again.

#{{ if not .Values.disablePolicyDrools }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drools
  namespace: "{{ .Values.nsPrefix }}-policy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drools
  template:
    metadata:
      labels:
        app: drools
      name: drools
    spec:
      initContainers:
      - command:
        - /root/ready.py
        args:
        - --container-name
        - mariadb
        - --container-name
        - nexus
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: "{{ .Values.image.readiness }}:{{ .Values.image.readinessVersion }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: drools-readiness
      hostAliases:
      - ip: "{{ .Values.aaiServiceClusterIp }}"
        hostnames:
        - "aai.api.simpledemo.openecomp.org"
      containers:
      - command:
        - /bin/bash
        - -c
        - ./do-start.sh
        image: "{{ .Values.image.policyDrools }}:{{ .Values.image.policyDroolsVersion }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: drools
        ports:
        - containerPort: 6969
        readinessProbe:
          tcpSocket:
            port: 6969
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /tmp/policy-install/config
          name: drools
        - mountPath: /usr/share/maven/conf/settings.xml
          name: drools-settingsxml
          subPath: settings.xml
        - mountPath: /var/log/onap
          name: policy-logs
        - mountPath: /tmp/logback.xml
          name: policy-logback
          subPath: logback.xml
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "export LOG=wait_logback.log; touch $LOG; export SRC=/tmp/logback.xml; export DST=/opt/app/policy/config/; while [ ! -e $DST ]; do echo 'Waiting for $DST...' >> $LOG; sleep 5; done; sleep 2; /bin/cp -f $SRC $DST; echo 'Done' >> $LOG"]
      - image: {{ .Values.image.filebeat }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: filebeat-onap
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-conf
          subPath: filebeat.yml
        - mountPath: /var/log/onap
          name: policy-logs
        - mountPath: /usr/share/filebeat/data
          name: policy-data-filebeat
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: filebeat-conf
          configMap:
            name: policy-filebeat-configmap
        - name: policy-logs
          emptyDir: {}
        - name: policy-data-filebeat
          emptyDir: {}
        - name: policy-logback
          configMap:
            name: policy-drools-log-configmap
        - name: drools-settingsxml
          configMap:
            name: policy-dep-drools-settings-configmap
        - name: drools
          secret:
            secretName: policy-dep-drools-secret
            items:
            - key: policy-keystore
              path: policy-keystore
              mode: 0644
            - key: feature-healthcheck.conf
              path: feature-healthcheck.conf
              mode: 0644
            - key: base.conf
              path: base.conf
              mode: 0755
            - key: policy-management.conf
              path: policy-management.conf
              mode: 0755
            - key: drools-tweaks.sh
              path: drools-tweaks.sh
              mode: 0755
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}

**Comment by jascott1** [comment]
@hamzeh-kh There should be a yaml file being used for values somewhere that contains  the line`disablePolicyDrools: False`. You just need to change it and the others to `True`. You might try to grep for it or search the repo. Also if you are colocated then it sounds like you don't need NFS. I would solve the first problem and then move on to the missing .sh file problem.

**Comment by bacongobbler** [comment]
Hi! Is there anything else we need to follow up on this ticket or has the issue been resolved in the past week? :)
