### ISSUE TITLE
Error using global values

### ISSUE THREAD

**Issue by joe-boyce** [kubernetes/helm#3425]
Hi,

I followed the steps detailed in the docs here:

https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md

But getting the following error when using global values:

```Error: render error in "mysubchart/templates/configmap.yaml": template: mysubchart/templates/configmap.yaml:7:19: executing "mysubchart/templates/configmap.yaml" at <.Values.Global.salad>: can't evaluate field salad in type interface {}```

Helm & tiller versions as follows:

```Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}```
```Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}```

What is causing this?

Thanks,

Joe

**Comment by jascott1** [comment]
Hi @joe-boyce 

It could be a YAML error. Would you be able to post your values and configmap template?

**Comment by joe-boyce** [comment]
Sorry guys should have closed this, all good now user error, thanks for the quick response 👍

**Comment by ramalhais-sky** [comment]
It would be nice to know what you changed to fix it. There's nothing more annoying than finding a problem like yours and then not knowing how you fixed it.

**Comment by lukipro** [comment]
@ramalhais-sky, there is no fix required. It's just a matter of instructions misinterpretation.
If you run:
`helm install --dry-run --debug mychart`
you will see both ConfigMaps rendered (parent and child).
Otherwise, if you run:
`helm install --dry-run --debug mychart/charts/mysubchart`
you will see the error that brought you to this issue.
