### ISSUE TITLE
generating template and skipping deploying 

### ISSUE THREAD

**Issue by bilalyasar** [kubernetes/helm#3426]
i have a txt file as a template and i want to get some helm values inside that file.
so i have following variables in my file like: `{{.Values.foo}}`

when i put this file under `templates` directory then helm tries to deploy it and fails.
when i put underscore beginning of the filename then helm completely ignores file, it doesn't replace the variables.

is there any way that generating file from template and skipping deployment part?

**Comment by jascott1** [comment]
Hi @bilalyasar 

You might try the `helm template` command. It will do your templating and output to stdout so you can send it on to `kubectl` or file.

**Comment by bacongobbler** [comment]
closing the question as resolved, but please re-open if you have any more questions. Thanks!
