### ISSUE TITLE
K8s is moving away from using the term "master"

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#3435]
The parent issue is at kubernetes/website#6525 and it was discussed in both ContribX and SIG Architecture. The proposed direction, at the moment, is to use a more accurate name if one exists (e.g., api server) or use the term "control plane".

There may be places within helm, specifically the documentation, that need to be updated as well.

**Comment by bacongobbler** [comment]
I ran through via `git grep` and found a few places. See #3458. :)
