### ISSUE TITLE
Does Helm support istio kube-inject now?

### ISSUE THREAD

**Issue by kubebc** [kubernetes/helm#3436]
Hi, Team,
Does Helm support istio 0.4 kube-inject now? i.e.

MS="myServices"; kubectl apply -f <(istioctl kube-inject -f deploy/$MS.yaml --includeIPRanges=100.64.0.0/10);

Thanks!

**Comment by Stono** [comment]
@kubebc what do you mean by helm supporting kube inject?
I believe istios suggested way of hanging this is to use the auto initializers in 1.9.0+

**Comment by bacongobbler** [comment]
closing; see #2878.

**Comment by SaifRehman** [comment]
use auto initializer https://archive.istio.io/v0.3/docs/setup/kubernetes/sidecar-injection.html
