### ISSUE TITLE
'no route to host' in tiller pod when using helm install or reset

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/helm#3441]
When attempting to install (spinnaker in my case) into my test cluster, I get this in my console:

```$ helm install stable/spinnaker --name spinnaker --wait --timeout 3600 --debug -f myvalues.yaml 
[debug] Created tunnel using local port: '38423'

[debug] SERVER: "127.0.0.1:38423"

[debug] Original chart version: ""
[debug] Fetched stable/spinnaker to /home/user/.helm/cache/archive/spinnaker-0.3.12.tgz

[debug] CHART PATH: /home/user/.helm/cache/archive/spinnaker-0.3.12.tgz

Error: Get https://100.64.0.1:443/version: dial tcp 100.64.0.1:443: getsockopt: no route to host
```

In the tiller pod, I see this:

```
[main] 2018/02/02 08:02:09 Starting Tiller v2.8.0 (tls=false)
[main] 2018/02/02 08:02:09 GRPC listening on :44134
[main] 2018/02/02 08:02:09 Probes listening on :44135
[main] 2018/02/02 08:02:09 Storage driver is ConfigMap
[main] 2018/02/02 08:02:09 Max history per release is 0
[tiller] 2018/02/02 08:02:34 preparing install for spinnaker
[storage] 2018/02/02 08:02:34 getting release history for "spinnaker"
[storage/driver] 2018/02/02 08:02:37 query: failed to query with labels: Get https://100.64.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dspinnaker%2COWNER%3DTILLER: dial tcp 100.64.0.1:443: getsockopt: no route to host
[tiller] 2018/02/02 08:02:40 failed install prepare step: Get https://100.64.0.1:443/version: dial tcp 100.64.0.1:443: getsockopt: no route to host
```

When trying to reset helm and start again, I couldn't even remove helm using `helm reset` (I had to use `helm reset -f`

```
$ helm reset
Error: Get https://100.64.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 100.64.0.1:443: getsockopt: no route to host

$ helm reset -f
Tiller (the Helm server-side component) has been uninstalled from your Kubernetes Cluster.

```

Does anyone know what's happened here?

**Comment by bacongobbler** [comment]
I'd check your network internal to your kubernetes cluster. 99% of the time it's due to a flaky cluster network config.

**Comment by huang-jy** [comment]
This seemed to come and go so I suspect something within the cluster hadn't initialised properly. So I'll go ahead and close this for now.

**Comment by dszmaj** [comment]
Hey @huang-jy , have you solved this issue? It seems I have exactly the same one with error like:
`Error: UPGRADE FAILED: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)registry%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 10.43.0.1:443: connect: no route to host`

**Comment by huang-jy** [comment]
@dszmaj in my case, I had to add more nodes to my cluster to allow the load to be spread across the cluster.

**Comment by dszmaj** [comment]
thank you for insanely quick response

unfortunately this is not the case, I have 4 big empty workers waiting for load

thanks for your insight :)

**Comment by huang-jy** [comment]
Trying doing a 

`watch kubectl get pods --all-namespaces | grep -i tiller`

as you do your deploy and see if tiller dies out.

**Comment by dszmaj** [comment]
It turns out that it is a networking problem just as everyone was pointing it out in internet, canal for some reason is craching on 2 machines and tiller was deployed inside one of them thus making it unavailable for cross culster requests
