### ISSUE TITLE
cannot create roles in kubernetes in  helm even after tiller has clusteradmin role

### ISSUE THREAD

**Issue by anitakumar** [kubernetes/helm#3444]
is forbidden: attempt to grant extra privileges
i have a namespace test1

i configured tiller as follows

cat rbac-tiller-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller-sa
  namespace: test1

cat rbac-tiller-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-manager
  namespace: test1
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]

cat rbac-tiller-rb.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-rb
  namespace: test1
subjects:
  - kind: ServiceAccount
    name: tiller-sa
    namespace: test1
roleRef:
    kind: Role
    name: tiller-manager
    apiGroup: rbac.authorization.k8s.io

i ran the command 
helm init --service-account tiller-sa --tiller-namespace test1

if i tried to create a role in the namespace test1 using helm i get the error 
+ helm upgrade --install --wait -f helm/values.yaml users-nodejs_usr ./helm

Release "users-nodejs_usr" does not exist. Installing it now.

Error: release users-nodejs_usr failed: roles.rbac.authorization.k8s.io "developer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["service"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["service"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["service"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["deployment"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["deployment"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["deployment"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["replicasets"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["replicasets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["replicasets"], APIGroups:[""], Verbs:["list"]}] user=&{system:serviceaccount:kube-system:default bc2b1fa3-f56a-11e7-ada8-0a4a2e979d98 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]

script returned exit code 1

**Comment by bacongobbler** [comment]
Have you tried adding `rbac.authorization.k8s.io` to the `apiGroups` section in the `tiller-manager` role? By default the documentation describes the core, extension and workload APIs, but none of the non-core APIs such as RBAC.

**Comment by anitakumar** [comment]
i tried this 

ind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-manager
  namespace: test1
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
apiGroup: rbac.authorization.k8s.io

and i got the error as follows
rror: error validating "rbac-tiller-role.yaml": error validating data: ValidationError(Role): unknown field "apiGroup" in io.k8s.kubernetes.pkg.apis.rbac.v1beta1.Role; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by bacongobbler** [comment]
According to https://docs.helm.sh/using_helm/#role-based-access-control you don't need the `apiGroup` field in a Role object, hence why it's failing kubernetes' schema validation. :)

**Comment by bacongobbler** [comment]
The correct Role would be:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-manager
  namespace: test1
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
```

**Comment by anitakumar** [comment]
Thanks I ill have a go at this.
