### ISSUE TITLE
failed to list: dial tcp 172.28.0.1:443: i/o timeout

### ISSUE THREAD

**Issue by joshskains** [kubernetes/helm#3447]
I have tried everything, but I am getting:

helm install stable/nginx-ingress
Error: no available release name found

The tiller log shows:

[root@KUBE-MASTER1 .kube]# kubectl logs tiller-deploy-5774d4b8bd-jdv5z --namespace kube-system
[main] 2018/02/02 23:40:29 Starting Tiller v2.8.0 (tls=false)
[main] 2018/02/02 23:40:29 GRPC listening on :44134
[main] 2018/02/02 23:40:29 Probes listening on :44135
[main] 2018/02/02 23:40:29 Storage driver is ConfigMap
[main] 2018/02/02 23:40:29 Max history per release is 0
[storage] 2018/02/02 23:40:37 listing all releases with filter
[storage/driver] 2018/02/02 23:41:07 list: failed to list: Get https://172.28.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 172.28.0.1:443: i/o timeout

What concerns me is the i/o timeout and I can't seem to find anything that fixes this issue.

**Comment by joshskains** [comment]
The I/O timeout issue can not be replicated on the master:
[root@KUBE-MASTER1 .kube]# curl https://172.28.0.1:443 -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403

**Comment by bacongobbler** [comment]
perhaps https://github.com/kubernetes/helm/issues/3347 is relevant here.

**Comment by joshskains** [comment]
Sorry, was out of town. 

It's a basic cluster with dual masters behind an HAProxy LB.

jskains-mbp:.kube jskains$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY     STATUS    RESTARTS   AGE
kube-system   coredns-65dcdb4cf-l84j7                  1/1       Running   0          3d
kube-system   kube-apiserver-kube-master1              1/1       Running   0          3d
kube-system   kube-apiserver-kube-master1-2            1/1       Running   0          3d
kube-system   kube-controller-manager-kube-master1     1/1       Running   0          3d
kube-system   kube-controller-manager-kube-master1-2   1/1       Running   0          3d
kube-system   kube-flannel-ds-4kj24                    1/1       Running   0          3d
kube-system   kube-flannel-ds-kssbx                    1/1       Running   0          3d
kube-system   kube-flannel-ds-wdqtz                    1/1       Running   0          3d
kube-system   kube-flannel-ds-z86w7                    1/1       Running   0          3d
kube-system   kube-proxy-9rsd7                         1/1       Running   0          3d
kube-system   kube-proxy-lls2b                         1/1       Running   0          3d
kube-system   kube-proxy-qf8v6                         1/1       Running   0          3d
kube-system   kube-proxy-rjfgn                         1/1       Running   0          3d
kube-system   kube-scheduler-kube-master1              1/1       Running   0          3d
kube-system   kube-scheduler-kube-master1-2            1/1       Running   0          3d
kube-system   tiller-deploy-5774d4b8bd-jdv5z           1/1       Running   0          3d

**Comment by bacongobbler** [comment]
So from the error message, it looks like the helm client is able to establish a connection to tiller, but tiller is unable to establish a connection to the API server. I'd check your network config and confirm that your worker nodes are able to connect to the API server, as opposed to connecting from the master as demonstrated in your second comment.

Does that make sense?

**Comment by joshskains** [comment]
[root@KUBE-MINION1-2 ~]# curl https://172.28.0.1:443 -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}[root@KUBE-MINION1-2 ~]#

**Comment by zzsuneo** [comment]
i have the same  bug with u,if u have any ideas ,please tell me ,thanks

**Comment by joshskains** [comment]
I moved to Calico and it worked fine. It appears something is off with flannel and helm?

**Comment by bacongobbler** [comment]
yes, that appears to be a [common pattern](https://github.com/kubernetes/helm/search?q=flannel&type=Issues&utf8=%E2%9C%93). We're not exactly sure why flannel doesn't allow connections back from the data plane to the control plane.

I'm going to close this because the original issue has been solved, but please re-open if there's something we need to do on our end to get helm working properly with flannel. My guess is that there's some documentation on flannel's side we may need to look up, but for now calico is a good workaround.

**Comment by zwhitchcox** [comment]
How to fix this problem

Remove flannel,

installl calico with the following command:

```
kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/etcd.yaml
kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/rbac.yaml
kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/calico.yaml
```

**Comment by marcstreeter** [comment]
removing flannel is the hard part it seems.

**Comment by BedivereZero** [comment]
I also have this problem with calico

```shell
[root@node-181 ~]# helm --debug install stable/mariadb --name some-mariadb
[debug] Created tunnel using local port: '45825'

[debug] SERVER: "127.0.0.1:45825"

[debug] Original chart version: ""
[debug] Fetched stable/mariadb to /root/.helm/cache/archive/mariadb-5.4.0.tgz

[debug] CHART PATH: /root/.helm/cache/archive/mariadb-5.4.0.tgz

Error: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
```

**Comment by dustnic** [comment]
exactly same issue here!

**Comment by bacongobbler** [comment]
Seems like the exactly same diagnosis made earlier: https://github.com/helm/helm/issues/3447#issuecomment-363521370

I suggest checking your internal network policy to see if tiller can talk to the API server.

**Comment by darmenliu** [comment]
hi，same issue for me，also with calico.

**Comment by darmenliu** [comment]
[storage/driver] 2019/07/24 06:30:48 list: failed to list: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: i/o timeout
[storage] 2019/07/24 06:30:48 listing all releases with filter
[storage/driver] 2019/07/24 06:31:18 list: failed to list: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: i/o timeout

**Comment by github4es** [comment]
Post https://abc.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps: dial tcp IP:443: i/o timeout

  on modules eks_nodes.tf line 17, in resource "kubernetes_config_map" "aws_auth":
  17: resource "kubernetes_config_map" "aws_auth" 

has anybody experienced this?

**Comment by w180112** [comment]
same issue here, 
Is there anybody knows the solution?
I have 1 master and 2 worker kubernetes nodes and install both helm client/server at one of the workers
Every action needs connect to kubernetes api server will fail and shows dial tcp 10.96.0.1:443: i/o timeout.
I use calico CNI and all kubernetes nodes run in different KVM virtual machine, their IP subnet is 192.168.10.0/24.
I also have checked kubectl can connect kubernetes api server at the worker which helm installed

**Comment by github4es** [comment]
have you tried restarting the kubelet service on the nodes?

**Comment by w180112** [comment]
@github4es Yes, I have, but it is still not functional

**Comment by avarf** [comment]
I am managing two clusters, one k8s 1.16 and 1 master and 4 workers and the second one k8s 1.15 and 1 master and 2 workers and both are using Calico and I am facing this issue on the  k8s 1.15. Any solution?

**Comment by marcosx86** [comment]
> I also have this problem with calico
> 
> ```shell
> [root@node-181 ~]# helm --debug install stable/mariadb --name some-mariadb
> [debug] Created tunnel using local port: '45825'
> 
> [debug] SERVER: "127.0.0.1:45825"
> 
> [debug] Original chart version: ""
> [debug] Fetched stable/mariadb to /root/.helm/cache/archive/mariadb-5.4.0.tgz
> 
> [debug] CHART PATH: /root/.helm/cache/archive/mariadb-5.4.0.tgz
> 
> Error: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
> ```

also getting problem with basic calico setup...

marcos@k8s-master:~$ kubectl logs -n metallb-system controller-65895b47d4-mh5t7 -f

I0306 00:32:41.937393       1 trace.go:81] Trace[392828266]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-03-06 00:32:11.93672354 +0000 UTC m=+992.064722232) (total time: 30.000609214s):
Trace[392828266]: [30.000609214s] [30.000609214s] END
E0306 00:32:41.937412       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig&limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0306 00:32:41.939114       1 trace.go:81] Trace[919889828]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-03-06 00:32:11.938608048 +0000 UTC m=+992.066606741) (total time: 30.000471357s):
Trace[919889828]: [30.000471357s] [30.000471357s] END
E0306 00:32:41.939145       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout

looping forever
