### ISSUE TITLE
Helm crashing with no error output

### ISSUE THREAD

**Issue by jeffutter** [kubernetes/helm#3448]
I have a somewhat complex chat with ~5 subcharts. I've started having issues performing upgrades on the chart on helm 2.8 on kops on aws. Particularly when `diffing` the chart using helm-diff (which basically just does a dry run).

The output I get on the client side is:

```
2018/02/03 10:48:16 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
2018/02/03 10:48:16 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:55924: operation was canceled"; Reconnecting to {127.0.0.1:55924 <nil>}
2018/02/03 10:48:16 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
```

and the output from the tiller logs is simply 

```
[storage] 2018/02/03 16:47:50 getting last revision of "myapp-blue"
[storage] 2018/02/03 16:47:50 getting release history for "myapp-blue"
```

Those logs happen before it starts to crash.

The strange part is what happens next. Tiller crashes another 5-10 times with no logs. Even if I log `--previous` it is just blank.

Describing the deployment just shows the health checks timing out.

Any ideas how I can debug this further?

**Comment by bacongobbler** [comment]
I'd try the instructions available at https://github.com/kubernetes/helm/issues/3409#issuecomment-364455566 and see if that fixes things. :)

**Comment by jeffutter** [comment]
I think I eventually figured this out. There was a dns issue causing my kubernetes nodes to become unreachable. Everything seems fine now.

**Comment by vhosakot** [comment]
I saw the `Error: transport is closing` error too when I ran `helm install`, and after doing `rm -rf ~/.helm`, the error was not seen anymore. Guess deleting the helm cache (`rm -rf ~/.helm`) may resolve the error.
