### ISSUE TITLE
Cannot upgrade helm server version to 2.8.0 correctly

### ISSUE THREAD

**Issue by zhangtbj** [kubernetes/helm#3476]
Hi,

We are upgrading our both helm client and server version from 2.7.0 to 2.8.0

The client version can be upgraded correctly.

But when I tried to upgrade server version by using `helm init --upgrade`, I got an error:
```
root@4c7870cb3b80:/# helm init --upgrade
$HELM_HOME has been configured at /root/.helm.
Error: error when upgrading: current Tiller version is newer, use --force-upgrade to downgrade
```

But the version show:
```
root@4c7870cb3b80:/# helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

Then I have to uninstall helm tiller and re-install again:
```
root@4c7870cb3b80:/# helm reset --force --remove-helm-home
Deleting /root/.helm
Tiller (the Helm server-side component) has been uninstalled from your Kubernetes Cluster.
root@4c7870cb3b80:/# helm init
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Happy Helming!
root@4c7870cb3b80:/# helm list
Error: grpc: received message larger than max (8086655 vs. 4194304)
```

I still cannot use helm function because:
`Error: grpc: received message larger than max (8086655 vs. 4194304)`

Do you have any idea about it?

Thanks!

**Comment by zhangtbj** [comment]
Another action:
```
root@4c7870cb3b80:/# helm reset --debug
[debug] Created tunnel using local port: '33151'

[debug] SERVER: "127.0.0.1:33151"

Error: grpc: received message larger than max (7386357 vs. 4194304)
```

**Comment by bacongobbler** [comment]
This was fixed in v2.8.1. Can you try upgrading?

**Comment by bacongobbler** [comment]
Or rather, we patched some things that might’ve fixed this

**Comment by zhangtbj** [comment]
Hi @bacongobbler , I have upgarded to v2.8.1, the upgrade problem is solved.  Thanks a lot!

But `Error: grpc: received message larger than max (7386357 vs. 4194304)` is another problem, if there are lots of helm releases, `helm list` cannot show them all because stream limit? so cannot show all, I have to use --max to limit the count. 

Do you think it is a problem?

**Comment by bacongobbler** [comment]
Yes, though we can follow up with that issue in #3322. :)

I'm going to close this as the original issue (`helm init --upgrade`) has been resolved in v2.8.1 and the other issue that you two are describing should be tracked under #3322 just so that we're tracking the issue in a single ticket. Thanks!

**Comment by feluxe** [comment]
How can I upgrade Helm `2.8.0` if `helm init --upgrade` and `helm init --force-upgrade` don't work?

**Comment by bacongobbler** [comment]
@feluxe you can upgrade your client (Helm) to v2.8.2, then after that you can run `helm init --upgrade` and it should work again.

**Comment by feluxe** [comment]
In case anyone else runs into this: I tried the suggested command `helm init --upgrade --client-only` which didn't work. I had to reinstall the client via one of the suggested methods from the docs: [Installing Helm](https://docs.helm.sh/using_helm/#installing-helm) and then run `helm init --upgrade`.

@bacongobbler Works like a charm now! Thanks!

**Comment by bacongobbler** [comment]
Yeah it's a little ambiguous but helm init --upgrade doesn't actually upgrade your client =)

**Comment by ayeletmorris** [comment]
@bacongobbler 
So, what does upgrade the client? (except re-installing it)
somehow my server is in rc-2 and my client is in rc-1... the --force-upgrade in order to downgrade the tiller doesn't work...

**Comment by bacongobbler** [comment]
Your local friendly package manager! there are community-maintained packages available for [choco](https://chocolatey.org/packages/kubernetes-helm), [homebrew](https://formulae.brew.sh/formula/kubernetes-helm) and [Ubuntu's Snap](https://github.com/snapcrafters/helm).

**Comment by ayeletmorris** [comment]
@bacongobbler  snap installed an OLDER version: helm 2.9.1 from 'snapcrafters' installed
but it seems that the client is still in rc-1
is there a way to define the version installed for the client? (because rc-2 is not an official version...)

**Comment by bacongobbler** [comment]
Looks like they haven't bumped to 2.10 yet. I pushed a PR upstream to bump to 2.10.0: https://github.com/snapcrafters/helm/pull/21

We don't actually own these packages, so if you have questions/feedback/feature requests, I'd bring it up with the snap package maintainers directly. :)
