### ISSUE TITLE
helpers in sub-charts override each other

### ISSUE THREAD

**Issue by lenalebt** [kubernetes/helm#3484]
/kind bug report

I have a chart that uses two sub-charts. Both subcharts define `_helpers.tpl`. These two charts both have an implementation of `imagePullSecret` which are slightly different:

    {{- define "imagePullSecret" }}
    {{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageCredentials.registry (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
    {{- end }}

and

    {{- define "imagePullSecret" }}
    {{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}, \"bip\": \"172.30.200.0/16\"}" .Values.imageCredentials.registry (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
    {{- end }}

Note the "bip" part. The first definition is in the first (alphabetically sorted) chart.

When I use the `{{ template "imagePullSecret" }}` in the second chart, it uses the helpers from the first one (without the "bip" part). Workaround: renaming the second one.

My expectation is that the charts define their `_helpers.tpl` locally, but it seems that they get defined globally. This behaviour seems wrong to me.

**Comment by jascott1** [comment]
Hi @lenalebt 

Template helpers are global. It is documented [here](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/named_templates.md#declaring-and-using-templates-with-define-and-template):

> There is one really important detail to keep in mind when naming templates: template names are global. If you declare two templates with the same name, whichever one is loaded last will be the one used. Because templates in subcharts are compiled together with top-level templates, you should be careful to name your templates with chart-specific names.

I do apologize that the docs contain examples that are not following this practice. I opened https://github.com/kubernetes/helm/issues/3487 to update the docs to be more clear.

**Comment by lenalebt** [comment]
Hi @jascott1 
thanks for the clarification! I think that updated documentation improves the situation, but nevertheless this is a problem if you try to use charts that do not follow these practices. It could even introduce security problems if you do not completely proofread all of the charts sources you're using.

Attack would work as follows:

You create a chart that has 2 subcharts A and B. You do trust B (because it is from a part of your organization), and therefore you give it access to credentials (in your `values.yaml`).
Chart A is malicious. It defines an `imagePullSecret` template that not only adds a pull secret, but within the same YAML file a `busybox` pod that connects to a server, sending out these credentials (simple `wget`). Since B uses an `imagePullSecret`, its credentials will be sent to the server, too.

So, although you did not give any credentials to chart A, and although it may not have rights to read the pull secrets in production, it will be able to send that data somewhere. I think this is counter-intuitive and opens an attack vector that could be avoided by not making the helpers global.

**Comment by jascott1** [comment]
Thanks for the input. I agree there is a vector there but any untrusted image would be able to relay sensitive information (some worse than pull secrets) to a third party. If helpers were not global they would have to be redefined repeatedly for each subchart which becomes cumbersome. I think we would consider any remediation that still allows helpers to be re-used across multiple charts so please do share your ideas.
