### ISSUE TITLE
docs(helm): All helper examples should demonstrate namespace best-practice

### ISSUE THREAD

**Issue by jascott1** [kubernetes/helm#3487]
We are documenting that [named templates](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/named_templates.md#declaring-and-using-templates-with-define-and-template)
 are global but only after showing the reader named template examples that do not follow this practice. We should update the examples to reflect the best practice and repeat the note at the top.

**Comment by mueedc** [comment]
I'm looking to make my first open source contribution and would like to tackle this issue

**Comment by jascott1** [comment]
@mueedc Sounds great! Let us know if  you have any questions.
