### ISSUE TITLE
mongodb-replicaset fails when auth is enabled

### ISSUE THREAD

**Issue by rjain15** [kubernetes/helm#3517]
Error: render error in "mongodb-replicaset/templates/mongodb-keyfile-secret.yaml": template: mongodb-replicaset/templates/mongodb-keyfile-secret.yaml:13:33: executing "mongodb-replicaset/templates/mongodb-keyfile-secret.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0

auth:
  enabled: true
  # adminUser: admin
  # adminPassword: password
  # key: keycontent
  # existingKeySecret:
  # existingAdminSecret:

What are the values I have to provide to the adminUser, adminPassword, key, existingKeySecret.

I have tried to provide values and it still didn't work.

**Comment by bacongobbler** [comment]
hey @rjain15 can you post this at https://github.com/kubernetes/charts? Any chart-related support questions should go to the owners of those charts. Thanks!
