### ISSUE TITLE
end to end testing for helm

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#352]
I'm currently working on an issue that touches both server and client side code. Unit tests are not enough for these changes, so I've been thinking about how to test helm/dm end to end.

A full test suite would look like this:
1. Run local/units tests
2. Spin up or attach to Kubernetes cluster
3. Cut new images with the changes or latest code to use.
4. Replace image tags in pkg/dm/install's InstallYAML (or use template params to generate install yaml with new tags)
5. Run through helm scenarios using gingko as the test framework. (i.e. install dm, deploy a chart, check deployments, etc.)

We could run the end to end tests on every change to master automated by circleci.

Talked to @adamreese about this and he's got thoughts on this too.

... Feel free to discuss here.

**Comment by jackgr** [comment]
:+1: See [gingko](https://godoc.org/github.com/onsi/ginkgo).
