### ISSUE TITLE
Helm repo add and helm install with the URL doesn't work in Linux when executed via java program

### ISSUE THREAD

**Issue by kamesh2229** [kubernetes/helm#3522]
Hi,

I am facing the same issue when trying to do repo add for a specific service.

run command /home/kamesh/src/ap/helm_workspace/helm repo add cm https:// main
18-02-15 16:51:45.510 INFO execution result
Error: Looks like "https:///cd/test/app" is not a valid chart repository or cannot be reached: open .helm/repository/cache/.helm/repository/cache/app-index.yaml: no such file or directory

if you see the directory structure ./helm/repository/cache is returning twice.

I am using Helm client and triller version as 2.7.2

What i am doing is as below :

Created a Java program that first does helm init default is /home/kamesh/.helm
Doing repo add app
Then throwing this error.
From java a new shell is swapned for every instance and the command is executed using ShellCommand API.

Can you please let me know if any specific reason.

Thanks

**Comment by kamesh2229** [comment]
Hi,

Can somone please help me .. i am unable to find the root cause of the issue.
All other helm commands works fine with the script but only repo add and helm install directly getting from the remote repo is failing with the above error.

I see many such issues observed by others and any clue on how i can solve.

Thanks in advance.

**Comment by bacongobbler** [comment]
Can you post the output of `helm home` as well as the full output from `helm repo add`? It looks like a large amount of the logs were cut or edited, so it’s not providing any useful information to grok.

**Comment by bacongobbler** [comment]
Also try `helm init —client-only` first. Your home directory might not be initialized.

**Comment by kamesh2229** [comment]
I will provide the output by tomorrow..
I have initiated the helm init --client-only command and is successful...anyhow will give the exact output ..

**Comment by kamesh2229** [comment]
Hi,

Here are the complete details.

I am using a Java framework 

Test Step 1: Init helm - Duration: 00:00:00.169(h:m:s)
run command /home/eprkame/adp-gs-cm/src/cm/helm_workspace/2.7.2/helm init --client-only   
  18-02-20 17:39:23.881  INFO  execution result 
 $HELM_HOME has been configured at .helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!

18-02-20 17:39:24.203  INFO  Test Step 2: Add the test-app chart to the repository - Duration: 
  18-02-20 17:39:24.350  INFO  print the Uri <Location where the helm chart is stored>
   18-02-20 17:39:24.363  INFO  run command /home/eprkame/src/helm_workspace/2.7.2/helm repo add  test-app <URI location where chart is available>
   Error: Looks like "The URI provided above" is not a valid chart repository or cannot be reached: open .helm/repository/cache/.helm/repository/cache/test-app-index.yaml: no such file or directory

Below is the java code used to execute the helm commands in a shell.
where my env contains the kubeconfig and helm path variables.

I am able to execute other helm commands without any issues ,but repo add is failed with the error mentioned above.If we see the path .helm/repository/cache/ is valid but i guess this is repeated twice and which the path is not valid.Not sure if the java code is executed in 2 different shells for each command i,e for init client and helm repo add where the repo environment is different .(Not sure the reason so thinking different ways)

private String runCommand(CommandLine command, Map<String, String> env)
            throws ExecutionException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PumpStreamHandler streamHandler = new PumpStreamHandler(outputStream);
        ExecuteWatchdog watchdog = new ExecuteWatchdog(60000);
        ExecutionResultHandler resultHandler = new ExecutionResultHandler(
                watchdog);
        executor.setWatchdog(watchdog);
        executor.setStreamHandler(streamHandler);
        
        try {
            executor.execute(command, env);
         } catch (IOException ex) {
            throw new ExecutionException(ex.getMessage(),
                    outputStream.toString(), ex);
        } finally {
            Logger.info("execution result \n {}", outputStream.toString());
        }
        return (outputStream.toString());
    }

**Comment by bacongobbler** [comment]
I didn't see the repository URL in the command arguments... Just `helm repo add test-app`. Did you make sure to add one to the command?

I'd check and make sure $HELM_HOME is set properly as well. It appears that your environment may be duplicating that value. I'm able to run `helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/` just fine from my local machine.

**Comment by bacongobbler** [comment]
From your output, it looks like $HELM_HOME is set to `.helm`. Perhaps $HOME isn't set or something is messing with your home directory. I'd try explicitly settings $HELM_HOME.

**Comment by kamesh2229** [comment]
Ok actually it is set under /home/kamesh/.helm.

I guess for some reason it is omiting the/home/Kamesh. May be something is corrupted ... anyhow I will try explicitly setting the HELM home variable.. 

Thanks

**Comment by kamesh2229** [comment]
Just another thing is when I manually execute the command in the shell I don't have any issues and execute from the java code which will spawn a replica of the shell the issue is observed

**Comment by kamesh2229** [comment]
Thanks i solved the issue by defining the HELM_HOME variable which was not set properly when using the default value.

**Comment by rakelkar** [comment]
Looks like setting HELM_HOME as a relative path causes this issue. Setting to an absolute path resolves it...

Relative path gives me an error:
```
$ HELM_HOME=./helm helm repo add po https://rakelkar.github.io/prometheus-operator-helm/
Error: Looks like "https://rakelkar.github.io/prometheus-operator-helm/" is not a valid chart repository or cannot be reached: open helm/repository/cache/helm/repository/cache/po-index.yaml: no such file or directory
```
But absolute path works:
```
$ HELM_HOME=/home/rakelkar/try/terraform/aks3/helm helm repo add po https://rakelkar.github.io/prometheus-operator-helm/
"po" has been added to your repositories
```

**Comment by stan-sz** [comment]
Thanks @rakelkar and @bacongobbler. Indeed, when `$HOME` isn't set, `$HELM_HOME` becomes a relative path. The error message is misleading, though. Should helm warn on `$HOME` not set, given that it has downstream effects?
