### ISSUE TITLE
Tests under pkg/releasetesting leak output to stdout during build 

### ISSUE THREAD

**Issue by adshmh** [kubernetes/helm#3526]
While building helm, tests under pkg/releasetesting package leak output to the standard output, e.g.:

>=== RUN   TestNewTestSuite
>--- PASS: TestNewTestSuite (0.00s)
>=== RUN   TestRun
>apiVersion: v1
>kind: Pod
>metadata:
>  name: finding-nemo,
> annotations:
>"helm.sh/hook": test-success
>spec:
>containers:
>name: nemo-test
>image: fake-image
>cmd: fake-command
>apiVersion: v1
>kind: Pod
>metadata:
>  name: gold-rush,
>  annotations:
>    "helm.sh/hook": test-failure
>spec:
> containers:
>name: gold-finding-test
>   image: fake-gold-finding-image
>   cmd: fake-gold-finding-command
>--- PASS: TestRun (0.00s)
>=== RUN   TestRunEmptyTestSuite
>--- PASS: TestRunEmptyTestSuite (0.00s)

**Comment by jascott1** [comment]
Marking as a bug since the output seems useless and makes the tests "ugly".
