### ISSUE TITLE
Tests under pkg/tiller leak output during build

### ISSUE THREAD

**Issue by adshmh** [kubernetes/helm#3534]
Tests under pkg/tiller directory leak output to stdout during build, e.g.:

>=== RUN   TestUpdateRelease_ReuseValues
kind: ConfigMap
metadata:
  name: test-cm
  annotations:
    "helm.sh/hook": post-upgrade,pre-upgrade
data:
  name: valuekind: ConfigMap
metadata:
  name: test-cm
  annotations:
    "helm.sh/hook": post-upgrade,pre-upgrade
data:
  name: value
---\# Source: hello/templates/hello
hello: worldkind: ConfigMap
metadata:
  name: test-cm
  annotations:
    "helm.sh/hook": post-upgrade,pre-upgrade
data:
  name: valuekind: ConfigMap
metadata:
  name: test-cm
  annotations:
    "helm.sh/hook": post-upgrade,pre-upgrade
data:
  name: value--- PASS: TestUpdateRelease_ReuseValues (0.01s)
...

**Comment by adshmh** [comment]
Another example of output leaked to stdout by tests: 

TestUpdateReleaseNoChanges:
>\# Source: hello/templates/with-partials
>hello: Earth--- PASS: TestUpdateReleaseNoChanges (0.02s)
>PASS
>ok      k8s.io/helm/pkg/tiller  2.240s

**Comment by jascott1** [comment]
I labeled this a bug because Im not aware of any value gained by the current output during tests and it seems like it should be cleaned up.
