### ISSUE TITLE
Make Helm respect resource limits in the namespace it is deploying to

### ISSUE THREAD

**Issue by rendhalver** [kubernetes/helm#3538]
Helm currently doesn't check resource limits in the namespace it is deploying to.
This results in a silently failing deploy if the requested resources exceed the quotas set in the namespace.

I am aware the Helm also doesn't check whether a namespace exists before it deploys so that is a likely requirement before this can be implemented.

I am largely unaware of how to implement this but I am happy to learn.

**Comment by jascott1** [comment]
Hi @rendhalver 

Helm should return any errors that are possible to return and we should investigate that problem. It will not check resource limits but should return errors from Kubernetes. Would it be possible to share a chart that demonstrates the problem with silent errors to help us find and fix the bug?  Also can you please share the version of k8s and helm?

**Comment by kkehres** [comment]
We use openshift and helm 2.7.1 does return messages about hitting resource limits in the namespace.

**Comment by rendhalver** [comment]
Helm only seems to fail on things like number of deployments of number of pods but not on things set via resources.
As for versions I have these running.

```
$ helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sancyx** [comment]
@rendhalver I've run into the same issue. To me it seems this is not about helm but the way Kubernetes works. If you try to create a pod with kubectl you will get an error about running out of resource quotas. However if you create some deployment (which is probably most of the cases) you won't get any error, since the pod will be created async by some deployment controller. Once you update the quotas pod's are created. Since there's no error when you submit deployments I don't see how Helm would be able to handle this.

**Comment by rendhalver** [comment]
Thanks @sancyx that makes sense.
I guess I need to translate this into an issue in Kube then.

**Comment by bacongobbler** [comment]
I'll close this one out as something out of Helm's control/nothing actionable on our end. :)

**Comment by iangkent** [comment]
In our CI/CD pipelines we run helm install --dry-run and parse out container resource requests (spec.template.spec.containers.*.resources.requests) then use kubectl to obtain namespace resource quota and determine if enough resources are available to meet chart install requested resources. If there is not enough resources available we either fail build.
