### ISSUE TITLE
Helm substitutes variables values on upgrade with default values if they are not specified in CLI

### ISSUE THREAD

**Issue by tiukhtinvladimir** [kubernetes/helm#3550]
/bug

So, as in header helm substitutes variables values on upgrade with default values if they are not specified in CLI. Let's say we are doing
helm install with --set foo=bar,image.tag=dev
Then is you do
helm upgrade --set image.tag=prod variable "foo" will take its default value instead of "bar"

**Comment by jascott1** [comment]
Sorry for the frustration but it sounds like it is functioning as designed. You supplied two values with `--set` and later you attempted to upgrade using the original local chart values with only one set value. As you pointed out, `--reuse-values` will deploy with the final values in the previous release which contains both original`--set` values but with one overridden by your subsequent `--set`.

**Comment by bacongobbler** [comment]
clsoing as working as intended.
