### ISSUE TITLE
Invalid deployed release prevents upgrade

### ISSUE THREAD

**Issue by tcolgate** [kubernetes/helm#3552]
I have a successful DEPLOYED release which actually contains an error. The specific error is a DeploymentSpec without a selector field. Clearly at some point either the API or helm client, or something, allowed this in. The object in the api has a selector. I'm not sure if that was manually added.

The selector is present in kubectl get deployment thing, but not present in helm get manifest --revision N , where N is a deployed release.

I am now trying to upgrade the deployed release. 

Helm attempts to deserialise the last DEPLOYED release, the one with the error. This deserialisation fails. The new deploy cannot continue.

I have tried using --force but things still fail at reading the release.

I'm not quite sure what the correct behaviour should be here. I think I can get things working again by hacking the config maps, but this situation should probably be catered for

perhaps helm edit manifest?

**Comment by tcolgate** [comment]
editting labels on config map entries doesn't seem to change the status (shame). Instead I curiously managed to rollback to a failed redploy (one that had failed due to the deserialisation problem), that seemed to work.

**Comment by jascott1** [comment]
Hi @tcolgate 

Sorry you are having trouble. Would it be possible to share a chart that displays the problem? Also what version of helm and k8s are you working with?

**Comment by gianrubio** [comment]
@tcolgate maybe your issue is related to #1873

**Comment by tcolgate** [comment]
It might be worth just closing this, but just to try and clarify a little. The cause of this was very simple. The content of the configmap was not compatible with the currently running API (or atleast whatever tiller was built against), reading the configmap caused an error due to the missing selector. There should probably be a better way of fixing this but I did manage to resolve it by doing a "rollback" to the most recent deploy (which was actually in a failed state).
