### ISSUE TITLE
Improve "grpc: received message larger than max" error message

### ISSUE THREAD

**Issue by mausch** [kubernetes/helm#3563]
For most users this error message means very little, so it is not actionable. I just got this error and spent about an hour trying different things. Ultimately it was caused by an unwanted large file in my chart directory. 
Perhaps helm could catch this error and append something like "check the size of your chart" or something like that?

**Comment by SlickNik** [comment]
Thanks for the suggestion @mausch! I know there is currently at least one other grpc bug that is actively being worked on -- so this may be a good addition to that fix, if possible.

**Comment by helgi** [comment]
Looks like the client side of it got merged just recently #3514

**Comment by bacongobbler** [comment]
verified

**Comment by helgi** [comment]
@bacongobbler Since I don't have the power, probably close this as fixed in 2.8.2  or 2.8.1 (with the milestone set)?

**Comment by SlickNik** [comment]
Sure thing -- Thanks @helgi!

**Comment by SlickNik** [comment]
This is fixed in 2.8.2
