### ISSUE TITLE
Question: What happens when you upgrade multiple times

### ISSUE THREAD

**Issue by Disturbing** [kubernetes/helm#3565]
If multiple requests are attempting to upgrade a single, specific, service multiple times, what would happen?

Sorry if this is in the documentation somewhere, but I could not find it?

My use case:

I'd like to dodge and race conditions if someone asked to deploy something N number of times, that hopefully it would just override and restart the previous deployment.  If not, curious how to handle this?

**Comment by ostlerc** [comment]
From what I understand, a helm has state of the current install and is idempotent. So doing two upgrades of a single specific service most likely will do nothing the second time. This is assuming you are not using extra command line flags to the upgrade command.

**Comment by Disturbing** [comment]
Thanks!
