### ISSUE TITLE
helm upgrade fails if the --wait flag is specified

### ISSUE THREAD

**Issue by IdanAdar** [kubernetes/helm#3566]
Helm/Tiller version: 2.8.1
Command: 
```
helm upgrade myrelease config/helm --install --set "global.env=dev" --wait 10
```

With the `--wait` flag the command keeps failing with: 
```
Error: This command needs 2 arguments: release name, chart path
```

Remove `--wait` and you'll get:
```
Release "myrelease" does not exist. Installing it now.
```

**Comment by eicnix** [comment]
The `--wait` flag takes no parameter. If you want to overwrite the wait timeout use ` --wait --timeout 10`

**Comment by IdanAdar** [comment]
Right, got confused there. However, I'd say that the resulting error message seem incorrect for the scenario at hand...
