### ISSUE TITLE
Unable to start tiller-deploy pod in my minikube kubernets cluster

### ISSUE THREAD

**Issue by rrajadevops** [kubernetes/helm#3569]
Hi team,

I am running minikube on my widows machine and I am trying to configure helm in my system. But when I am trying to "helm init" i got the below response but my tiller-deploy pod is not running on my kubernets cluster. Please give some suggestion to fix this issue.

C:\Users\Raja>docker pull gcr.io/kubernetes-helm/tiller:v2.1.3

C:\Users\Raja>helm init
Creating C:\Users\Raja\.helm
Creating C:\Users\Raja\.helm\repository
Creating C:\Users\Raja\.helm\repository\cache
Creating C:\Users\Raja\.helm\repository\local
Creating C:\Users\Raja\.helm\plugins
Creating C:\Users\Raja\.helm\starters
Creating C:\Users\Raja\.helm\cache\archive
Creating C:\Users\Raja\.helm\repository\repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at C:\Users\Raja\.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!

C:\Users\Raja>kubectl -n kube-system get po
NAME                             READY     STATUS              RESTARTS   AGE
kube-addon-manager-minikube      1/1       Running             0          1h
kube-dns-86f6f55dd5-9crrc        3/3       Running             0          1h
kubernetes-dashboard-rx6br       1/1       Running             0          1h
registry-creds-pflc6             0/1       ContainerCreating   0          1h
storage-provisioner              1/1       Running             0          1h
tiller-deploy-7b964d79f6-c9v5g   0/1       ImagePullBackOff    0          13m

Regards,
Raja

**Comment by SlickNik** [comment]
Hi @rrajadevops -- Looks like you're unable to fetch the tiller image in your minikube environment. The output from running `kubectl -n kube-system describe pod tiller-deploy-7b964d79f6-c9v5g` might give you some more insight into why that's the case.

**Comment by rrajadevops** [comment]
@SlickNik  thanks for your response. I can see some error in my cmd, As I am new to helm i couldnt find what is means exactly. Can you please see the below error.

C:\Users\Raja>kubectl -n kube-system describe pod tiller-deploy-7b964d79f6-c9v5g
Name:           tiller-deploy-7b964d79f6-c9v5g
Namespace:      kube-system
Node:           minikube/192.168.99.100
Start Time:     Mon, 26 Feb 2018 13:56:35 +0530
Labels:         app=helm
                name=tiller
                pod-template-hash=3652083592
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-7b964d79f6","uid":"e558dc61-1ac7-11e8-af89-080...
Status:         Pending
IP:             172.17.0.5
Created By:     ReplicaSet/tiller-deploy-7b964d79f6
Controlled By:  ReplicaSet/tiller-deploy-7b964d79f6
Containers:
  tiller:
    Container ID:
    Image:          gcr.io/kubernetes-helm/tiller:v2.8
    Image ID:
    Ports:          44134/TCP, 44135/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-d9lcm (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-d9lcm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-d9lcm
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason      Age                 From               Message
  ----     ------      ----                ----               -------
  Normal   BackOff     50m (x424 over 2h)  kubelet, minikube  Back-off pulling image "gcr.io/kubernetes-helm/tiller:v2.8"
  Normal   Pulling     34m (x27 over 2h)   kubelet, minikube  pulling image "gcr.io/kubernetes-helm/tiller:v2.8"
  Warning  FailedSync  8s (x648 over 2h)   kubelet, minikube  Error syncing pod

Regards,
Raja

**Comment by jascott1** [comment]
Hi @rrajadevops 

`Reason: ImagePullBackOff` suggests that your server cannot access the internet. Perhaps you are behind a corporate proxy?

**Comment by bacongobbler** [comment]
I've seen this error occur with custom helm client builds. If you've built helm from source, you need to specify the tiller image release with one of the following flags:

1. `helm init --canary-image`
2. `helm init --tiller-image=gcr.io/kubernetes-helm/tiller:v2.8.2`

You can confirm if you've built Helm from source using `helm version -c`. You should see the SemVer field read something like `2.8+`.

**Comment by leandroBorgesFerreira** [comment]
I had the problem. Status: 
```
  Type     Reason                 Age   From               Message
  ----     ------                 ----  ----               -------
  Normal   Scheduled              46s   default-scheduler  Successfully assigned tiller-deploy-865dd6c794-spm4g to minikube
  Normal   SuccessfulMountVolume  46s   kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4qwhc"
  Normal   Pulling                46s   kubelet, minikube  pulling image "gcr.io/kubernetes-helm/tiller:v2.8.2"
  Warning  Failed                 11s   kubelet, minikube  Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.8.2": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: dial tcp [2800:3f0:4003:c00::52]:443: connect: network is unreachable
  Warning  Failed                 11s   kubelet, minikube  Error: ErrImagePull
  Normal   BackOff                10s   kubelet, minikube  Back-off pulling image "gcr.io/kubernetes-helm/tiller:v2.8.2"
  Warning  Failed                 10s   kubelet, minikube  Error: ImagePullBackOff
```  

But after sometime, the image was downloaded and the pod started running. Maybe there is some instability with image registry.

**Comment by chalvern** [comment]
I had the same error, which seems the host refused my request. I am wondering the gcr.io service may have stopped.

`
Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.8.2": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: dial tcp 108.177.125.82:443: getsockopt: connection refused
`

**Comment by monztors** [comment]
> I had same the problem. 
> Status:
> ```
> Type     Reason                 Age               From                         Message
>  ----     ------                 ----              ----                         -------
> Normal   Scheduled              6m                default-scheduler            Successfully assigned tiller-deploy-5fc6fbb69c-z6wc6 to docker-for-desktop
> Normal   SuccessfulMountVolume  6m                kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-8vmgd"
> Warning  Failed                 5m                kubelet, docker-for-desktop  Failed to pull image "gcr.io/kubernetes-helm/tiller:canary": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: TLS handshake timeout
> Warning  Failed                 4m (x2 over 6m)   kubelet, docker-for-desktop  Failed to pull image "gcr.io/kubernetes-helm/tiller:canary": rpc error: code = Unknown desc = error pulling image configuration: Get https://gcr.io/v2/kubernetes-helm/tiller/blobs/sha256:c0fb8f7c34ea5c02771098425c8abff1a837e02d9cb79607442dfedd8b593956: net/http: TLS handshake timeout
> Normal   Pulling                4m (x4 over 6m)   kubelet, docker-for-desktop  pulling image "gcr.io/kubernetes-helm/tiller:canary"
> Warning  Failed                 3m (x4 over 6m)   kubelet, docker-for-desktop  Error: ErrImagePull
> Warning  Failed                 3m                kubelet, docker-for-desktop  Failed to pull image "gcr.io/kubernetes-helm/tiller:canary": rpc error: code = Unknown desc = error pulling image configuration: Get https://storage.googleapis.com/artifacts.kubernetes-helm.appspot.com/containers/images/sha256:c0fb8f7c34ea5c02771098425c8abff1a837e02d9cb79607442dfedd8b593956: net/http: TLS handshake timeout
> Normal   BackOff                3m (x6 over 6m)   kubelet, docker-for-desktop  Back-off pulling image "gcr.io/kubernetes-helm/tiller:canary"
> Warning  Failed                 1m (x12 over 6m)  kubelet, docker-for-desktop  Error: ImagePullBackOff
> ```
> i've been try  
>```
> kubectl delete deployment tiller-deploy --namespace kube-system
> and
> helm init --canary-image
>```
> but still not solve the problem.

**Comment by bacongobbler** [comment]
@monztors here's the main error from that report:

> Error response from daemon: Get https://gcr.io/v2/: net/http: TLS handshake timeout

That error typically indicates a connection could not be established with gcr.io, which is the container registry hosting tiller's image. Are you in a region where gcr.io is blocked? For example we've heard reports from people in China that gcr.io is unavailable behind the firewall.

**Comment by monztors** [comment]
@bacongobbler 
>Thanks for fast respons. actually i'm from indonesia. 
> i also tried using antoher image (**ibmcom/tiller:v2.6.0**), and succeeded.
>```
> helm init -i ibmcom/tiller:v2.6.0
> Events:
> Type    Reason                 Age   From                         Message
>  ----    ------                 ----  ----                         -------
>  Normal  Scheduled              1m    default-scheduler            Successfully assigned tiller-deploy-6dbb577bcb-9ftsb to docker-for-desktop
>  Normal  SuccessfulMountVolume  1m    kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-8vmgd"
>  Normal  Pulled                 1m    kubelet, docker-for-desktop  Container image "ibmcom/tiller:v2.6.0" already present on machine
>  Normal  Created                1m    kubelet, docker-for-desktop  Created container
>  Normal  Started                1m    kubelet, docker-for-desktop  Started container
> ```
> but the helm client and server version incompatible
> ```
> helm list
> Error: incompatible versions client[v2.12.3] server[v2.6.0]
> ```
> however, when i try to upgade, the result is the same
>```
>Events:
> Type     Reason                 Age   From                         Message
>  ----     ------                 ----  ----                         -------
> Normal   Scheduled              35s   default-scheduler            Successfully assigned tiller-deploy-7995854f67-fqxsd to docker-for-desktop
> Normal   SuccessfulMountVolume  34s   kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-8vmgd"
> Normal   Pulling                34s   kubelet, docker-for-desktop  pulling image "gcr.io/kubernetes-helm/tiller:v2.12.3"
> Warning  Failed                 4s    kubelet, docker-for-desktop  Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.12.3": rpc error: code = Unknown desc = error pulling image configuration: Get https://storage.googleapis.com/artifacts.kubernetes-helm.appspot.com/containers/images/sha256:ecd91fcf9f6d6ad881a230d12daca5aa23b8e710e956ada9483625da37d825b2: net/http: TLS handshake timeout
> Warning  Failed                 4s    kubelet, docker-for-desktop  Error: ErrImagePull
> Normal   BackOff                3s    kubelet, docker-for-desktop  Back-off pulling image "gcr.io/kubernetes-helm/tiller:v2.12.3"
> Warning  Failed                 3s    kubelet, docker-for-desktop  Error: ImagePullBackOff
>```
>I think, I agree with you. There are two possibilities, my connection problem, or there is problem with image on gcr.io

**Comment by bacongobbler** [comment]
Works for me over here in North America, so there's no problem with the image itself. :)

```
><> helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Same with the canary image. I'd check your connection information and see if you can connect to gcr.io.

**Comment by monztors** [comment]
> Works for me over here in North America, so there's no problem with the image itself. :)
> 
> ```
> ><> helm version
> Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
> ```
> Same with the canary image. I'd check your connection and see if you can connect to gcr.io.

@bacongobbler 
Thanks for your help, after a few days of trying, suddenly now i can download the image using command **"helm init --canary-image"**
>```
> kubectl describe pods --namespace kube-system tiller-deploy-5fc6fbb69c-mjgjk
> Events:
> Type    Reason                 Age   From                         Message
>  ----    ------                 ----  ----                         -------
>  Normal  Scheduled              5m    default-scheduler            Successfully assigned tiller-deploy-5fc6fbb69c-mjgjk to docker-for-desktop
>  Normal  SuccessfulMountVolume  5m    kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-8vmgd"
>  Normal  Pulling                5m    kubelet, docker-for-desktop  pulling image "gcr.io/kubernetes-helm/tiller:canary"
>  Normal  Pulled                 5m    kubelet, docker-for-desktop  Successfully pulled image "gcr.io/kubernetes-helm/tiller:canary"
>  Normal  Created                5m    kubelet, docker-for-desktop  Created container
>  Normal  Started                5m    kubelet, docker-for-desktop  Started container
>```
