### ISSUE TITLE
Retrieve release history with namespace filter(Can't use same release name in different namespace)

### ISSUE THREAD

**Issue by Xuhao** [kubernetes/helm#3575]
I have a service with name same as release name (assume  `web-api`). I installed it in `staging` namespace, but when I install it in `production` later, I got the warning:

```
WARNING: Namespace doesn't match with previous. Release will be deployed to staging
```
 
I think it's effected by：https://github.com/kubernetes/helm/blob/18b709ef21ae44143ee685da7502417361c76af9/cmd/helm/upgrade.go#L154-L161

Helm retrieve release history without namespace filter.

my workaround is keep to use same service (for service discovery), but use namespace as suffix of release name.

**Comment by jascott1** [comment]
@Xuhao Sorry for the trouble but that is how it is currently designed. My guess is that it was implemented that way to avoid confusion arising from accidental duplication in different namespaces. Hopefully someone more familiar with the rationale can weigh in.

**Comment by Xuhao** [comment]
@jascott1 
For namespace,  I think release should have same behavior as service does, also when we run `helm install` we can pass `--namespace` to make sure install into correct namespace, and same as `helm upgrade` does,  helm operations in a namespace should not effect other namespace.

**Comment by vincentvanderweele** [comment]
Reading that code snippet, it looks like a typo to me. Nowhere do I see code that actually sets the namespace to the previous one.

Could it be that the release will actually be deployed to the new namespace and the warning is just supposed to warn about that? So [this line](https://github.com/kubernetes/helm/blob/18b709ef21ae44143ee685da7502417361c76af9/cmd/helm/upgrade.go#L159) should be:

```diff
- fmt.Fprintf(u.out, "WARNING: Namespace doesn't match with previous. Release will be deployed to %s\n", previousReleaseNamespace)
+ fmt.Fprintf(u.out, "WARNING: Namespace doesn't match with previous. Release will be deployed to %s\n", u.namespace)
```

**Comment by bacongobbler** [comment]
Nope! That's the intention. Once a chart has been installed into the cluster, it cannot be switched over into another namespace without deleting the existing resources and re-installing it, so we are reporting that the upgrade will occur in the previous namespace.

Also see my comment in #3657

**Comment by bacongobbler** [comment]
closing as answered
