### ISSUE TITLE
helm history errors when number of revisions is high

### ISSUE THREAD

**Issue by codesuki** [kubernetes/helm#3577]
```
helm list
NAME               	REVISION
gateway            	492 
```
results in
```
helm history gateway
Error: grpc: received message larger than max (4209459 vs. 4194304)
```

**Comment by bacongobbler** [comment]
related: #3322

**Comment by bacongobbler** [comment]
also see #3514

**Comment by codesuki** [comment]
Thanks, sorry my bad, I didn't check if a related issue exists. For us it's not a big problem we just limited it with `--max`.

**Comment by SlickNik** [comment]
Not a problem at all @codesuki -- thanks for reporting the issue! 😄 

I've built a version of helm with the fix proposed in https://github.com/kubernetes/helm/pull/3514. You can find it at http://lihk.in/helm-pull-3514/. Can you give it a try when you get a chance?

**Comment by codesuki** [comment]
Not sure I can find the time, but if, I will! Thanks :)

**Comment by SlickNik** [comment]
👍Thanks @codesuki -- appreciate it!

In the meanwhile, I will close this issue since it's very likely a duplicate. Feel free to re-open if you discover that the fix doesn't work, or if the issue still persists. Cheers!
