### ISSUE TITLE
Feature Request: Support for custom description after helm release upgrade

### ISSUE THREAD

**Issue by luongvo209** [kubernetes/helm#3581]
First of all, I would like to thank you all maintainers of Helm. Helm is really great and awesome in many ways.   👍   

------ 
Currently, after an upgrade for a release, Helm update the release description with : 
`updatedRelease.Info.Description = "Upgrade complete"`
> source : https://github.com/kubernetes/helm/blob/d6da76f3cfe0dae5a01fd5fec29ce7d6f57a1a52/pkg/tiller/release_update.go .   

While this behaviour is fine for most use cases, I suggest that we should enable users to choose their own description, so that the output of `helm history....` in the future may be more informative rather than the hard coded string `Upgrade complete`.  

By the way, this also makes the documentation look outdated. Intially, this string was `Upgraded successfully` (https://github.com/kubernetes/helm/blob/master/docs/helm/helm_history.md). To sum up, my wish is that this string could be more flexible.

**Comment by adshmh** [comment]
I have started working on this.

**Comment by luongvo209** [comment]
@adshmh That sounds great! 👍
