### ISSUE TITLE
Error: grpc: received message larger than max (5841327 vs. 4194304)

### ISSUE THREAD

**Issue by nmiculinic** [kubernetes/helm#3586]
When fetching histroy for one release

**Comment by bacongobbler** [comment]
closing as a duplicate of #3322.

**Comment by bacongobbler** [comment]
Rather, https://github.com/kubernetes/helm/pull/3514 was merged so this bug should no longer be present in the canary releases. #3322 is more about what happens when the number of releases stored in tiller exceed that 20MB limit.
