### ISSUE TITLE
helm template --kube-version doesn't produce correct capabilities

### ISSUE THREAD

**Issue by sdake** [kubernetes/helm#3589]
In PR: https://github.com/istio/istio/pull/3785#issuecomment-368999791

It seems that a clunky workaround is required to use the helm template operation.  `--kube-version="1.9"` does not produce correct capabilities for `-{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1beta1" -}}`.  I understand this is a beta option, and maybe only stable options are supported in the capabilities.  Could the Istio project have clarification on this point (we use a few beta features and are going to a helm based single source of truth for our manifests).

Cheers
-steve

cc @jascott1

**Comment by bacongobbler** [comment]
IIRC `.Capabilities.APIVersions` is unavailable using `helm template` because the implementation is purely client-side. In order for that to work, we'd have to phone home to tiller to gather information about what the server's capabilities are.

**Comment by bacongobbler** [comment]
Yep! From https://github.com/technosophos/helm-template#usage,

> This does not require Tiller. However, any values that would normally be looked up or retrieved in-cluster will be faked locally. Additionally, none of the server-side testing of chart validity (e.g. whether an API is supported) is done.

**Comment by sdake** [comment]
@bacongobbler thanks for the clarification.  I think one feature that would be interesting is the ability to override the faked values, but I'm not sure how relevant that is to the original question proposed in this issue nor am I sure if that would even be technically viable.

As a result, I am closing this request for clarification.  Thanks for the clarification!
