### ISSUE TITLE
Trying to use a variable as argument to .Files.Glob to get to a subdirectory

### ISSUE THREAD

**Issue by kkehres** [kubernetes/helm#3593]
I tried this

```
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.projectName }}-secret"
type: Opaque
data:  
{{ (.Files.Glob "certs/{{ .Values.env }}/*").AsSecrets | indent 2 }}
```

and this

```
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.projectName }}-secret"
type: Opaque
data:
{{ (.Files.Glob (printf "certs/%s/*" .Values.env | quote)).AsSecrets | indent 2 }}
```
helm install --dry-run --debug . --set env=deva-fas,projectName=testing
ls certs/deva-fas/*
certs/deva-fas/keystore.jks
certs/deva-fas/truststore.jks

I don't get any errors with either of the above but data: is empty {}

I'm stuck on this for a couple days.  I couldn't find any examples on the web using a variable as an arugment to .Files.Glob

Any help is much appreciated

**Comment by kkehres** [comment]
A colleague just helped me out.

This is working.

```
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.projectName }}-secret"
type: Opaque
data:
{{- $path := printf "certs/%s/*" .Values.env }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
```

**Comment by williamhammond** [comment]
why does this need to be done outside of the .`Files.Glob` function?

**Comment by kkehres** [comment]
You need to run this for each file and the best way to do that is get an array of filenames.  I also had some issues getting secrets created for template files which I got some other help from another issue thread.

**Comment by kkehres** [comment]
also I guess I should add you can't have a directory as part of a secret unless you use a subpath. That was not my use case.
