### ISSUE TITLE
helm upgrade of mariadb application fails

### ISSUE THREAD

**Issue by sumsuns** [kubernetes/helm#3594]
Hello ,

I am trying to upgrade cmdb chart  and it fails with the below  error . i have changed nothing other then image name,chart version . if i keep the chart version same with other changes  upgrade looks fine .. pods are restarting , image change is reflected in the pods .. any help greatly appriciated . 

this application has seccret yaml ,configmaps,service yaml ,statefulsets .

$ helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
[root@helm-testing-control-03 ~/helm-cmdb/cmdb-2.4.3-17.12/cmdb/templates]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

[root@helm-testing-control-03 ~]$ helm upgrade pugnacious-deer  csf-incubator/upgradecmdb --version 2.4.8-17.12  --debug
[debug] Created tunnel using local port: '46029'

[debug] SERVER: "127.0.0.1:46029"

[debug] Fetched csf-incubator/upgradecmdb to /root/.helm/cache/archive/upgradecmdb-2.4.8-17.12.tgz

Error: UPGRADE FAILED: StatefulSet.apps "pugnacious-deer-upgradecmdb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.

my statefulsets: 

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ template "fullname" . }}
  podManagementPolicy: "Parallel"
  replicas: {{ .Values.CLUSTER_SIZE }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      initContainers:
      - name: "database-user-config"
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        {{- if .Values.metrics.enabled }}
        - name: MARIADB_METRICS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-metrics-password
        {{- end }}
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mariadb-root-password
        command:
          - bash
          - "-c"
          - |
            sed -i -e "s/root_password/$MARIADB_ROOT_PASSWORD/g" /import/database_users.json
        {{- if .Values.metrics.enabled }}
            sed -i -e "s/metrics_password/$MARIADB_METRICS_PASSWORD/g" /import/database_users.json
        {{- end }}
        volumeMounts:
        - name: import
          mountPath: /import
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 4444
          name: gsst
        - containerPort: 4567
          name: gcomm

**Comment by bacongobbler** [comment]
hey @sumsuns! Because this is a chart-specific question, we ask that all issues related to community charts be posted at https://github.com/kubernetes/charts. Would you mind opening a new issue there?

Thank you for the report!

**Comment by sumsuns** [comment]
thanks i did that
