### ISSUE TITLE
complex SemVer cannot be used in requirements.yaml

### ISSUE THREAD

**Issue by natcho** [kubernetes/helm#3600]
As a part of a continuous build pipeline, I need to add a reference to the git version from which a chart came from. I am able to successfully build such charts, however I cannot find a way to use them in requirements.yaml of other charts.

```
~> helm version
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

For example, here are several version of the same chart that I have built and published to a helm repo:

```
~/g/chart1> helm search chart1 -l
NAME                 	VERSION          	DESCRIPTION
myrepo/chart1	1.0.0            	Chart1
myrepo/chart1 	1.0.0+62_g19b0371	Chart1
myrepo/chart1 	1.0.0-62_g19b0371	Chart1
```

My base requirements.yaml for chart2 is:
```
dependencies:
  - name: chart1
    version: 1.0.0
    repository: alias:myrepo
```

When I use `version: 1.0.0` in requirements.yaml, everything works as expected. However, I cannot find a format that would allow me to require any of the charts with more complex version. I have tried `version: 1.0.0+62_g19b0371`, `version: 1.0.0-62_g19b0371`, and several variations, but in all cases I get an error:

```
Error: dependency "chart1" has an invalid version/constraint format: improper constraint: 1.0.0-62_g19b0371
```

**Comment by bacongobbler** [comment]
Because version numbers are backed by semver v2, they must conform to [the spec](https://semver.org/#spec-item-10):

> 10. Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

so the underscore won't work in this case, but dot notation will. `1.0.0+62.g19b0371` would be a valid version number.

**Comment by natcho** [comment]
Thanks for the clarification, I should have paid more attention to the spec.
