### ISSUE TITLE
`checksum/config` trick does not seem to support template value change

### ISSUE THREAD

**Issue by gsemet** [kubernetes/helm#3601]
Hello

The following trick does works well to force deployment on configmap template change:
```
checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```
But it does not seem to trigger a redeployment when the file does **not** change but one of its templated values (`{{ .Values.something }}`) change in the value file and ultimately affect the generated configmap?

In short, I guess this trick only does a checksum of the template file and not the final rendered configmap, does it ?

Is there any planed feature, something a-la [fabric8 controller](https://github.com/fabric8io/configmapcontroller/) ? I don't see much official helm template using this trick, can't this be promoted as an official kubernetes feature?

**Comment by eicnix** [comment]
The `include` function should also render the template which then should result in a different hash. 

Can you confirm that the content of the rendered configmap changed?

**Comment by gsemet** [comment]
Does it changed anythink I tested on minikube? Yes the content of the configmap did changed. For reference [here is the configmap file](https://github.com/gsemet/kube-airflow/blob/master/airflow/templates/configmaps.yaml) and the value that changed was the `.Values.airflow.config` list

**Comment by eicnix** [comment]
I checked your chart out and cannot reproduce the behaviour you are describing on minikube.

Do you use `helm upgrade` to modify the values?

**Comment by gsemet** [comment]
I will try again. Can you (or I?) add a note in the tips and trips page that the checksum should be modified when rendering change? it wasn't clear for me

**Comment by gsemet** [comment]
not reproduce with 2.9

**Comment by hmharsh** [comment]
I was trying to prevent the restart of the grafana pod after the upgrade but figure out these issues.
steps to reproduce this checksum issue with one test [helm chart](https://github.com/hmharsh/helm-issue) contains one deployment and one secret.

1. Download test chart and change directory
```
   git clone https://github.com/hmharsh/helm-issue.git
   cd helm-issue
```

2. Install the chart without any extra input (to let helm generate the random password)
`   helm install helm-issue .`

3. Store the Kubernetes yaml for future reference
`   helm get manifest helm-issue > /tmp/old.txt`

4. Grep the randomly generated password 
```
   admin_password=`kubectl get secrets secret  -o=go-template='{{index .data "admin-password"}}'`
   echo $admin_password
```

5. Upgrading helm chart when there is no change made in deployment and secret,
   also, we are supplying the existing password to prevent pods to get restarted.

`   helm upgrade helm-issue . --set="adminPassword=$admin_password"`

6. Store the Kubernetes yaml for future reference
`   helm get manifest helm-issue > /tmp/new.txt `


 _-- unexpectedly deployment replaces/restart pod even when there is no change in deployment or secret file --_     


7. The reason for pod restart 
`   diff /tmp/old.txt /tmp/new.txt`

8. cleanup
`   helm uninstall helm-issue`

**Conclusion**:
Even on no change in the content of the secret file the sha256 sum is different before and after the upgrade
this can be probably be related to the sequence when helm calculates the sha256 sum internally.

cc: @kanuahs @vadasambar
