### ISSUE TITLE
Problems connecting to GKE with TLS enabled

### ISSUE THREAD

**Issue by flimzy** [kubernetes/helm#3603]
I'm setting up helm (2.8.1) for the first time, to use with Google Kubernetes Engine.  I'm going through the Quick start guide, and have created an SSL CA, then successfully initialized helm:

    $ kubectl create serviceaccount tiller --namespace kube-system
    serviceaccount "tiller" created
    $ helm init --tiller-tls --tiller-tls-cert ./tiller.cert.pem --tiller-tls-key ./tiller.key.pem --tiller-tls-verify --tls-ca-cert ca.cert.pem --service-account=tiller
    $HELM_HOME has been configured at /home/jonhall/.helm.

    Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
    Happy Helming!

From this point on, helm is giving me a fit. Before I even tried installing a helm chart as explained in the quick start, I tried `helm ls`:

    $ helm ls
    Error: transport is closing

I added debugging:

    $ helm ls --debug
    [debug] Created tunnel using local port: '37211'

    [debug] SERVER: "127.0.0.1:37211"

    Error: transport is closing

Then I took a step back and tried installing a sample helm chart, and sporadically get one of two responses:

    $ helm install stable/mysql
    E0303 16:16:03.455813   26394 portforward.go:331] an error occurred forwarding 43201 -> 44134: 
error forwarding port 44134 to pod c84cb7ca85c6992ab20ff6fdeb75530eb048ee20844fc77dbd133acd88f59b16, uid : exit status 1: 2018/03/03 15:16:03 socat[16843] E write(5, 0x5569b6246b70, 8192): Connection reset by peer
    Error: transport is closing

or sometimes the less verbose:

    $ helm install stable/mysql
    Error: transport is closing

If I add the `--debug` flag:

    $ helm install stable/mysql --debug
    [debug] Created tunnel using local port: '46825'

    [debug] SERVER: "127.0.0.1:46825"

    [debug] Original chart version: ""
    [debug] Fetched stable/mysql to /home/jonhall/.helm/cache/archive/mysql-0.3.5.tgz

    [debug] CHART PATH: /home/jonhall/.helm/cache/archive/mysql-0.3.5.tgz

    E0303 16:28:04.918754   27764 portforward.go:331] an error occurred forwarding 46825 -> 44134: error forwarding port 44134 to pod c84cb7ca85c6992ab20ff6fdeb75530eb048ee20844fc77dbd133acd88f59b16, uid : exit status 1: 2018/03/03 15:28:04 socat[24640] E write(5, 0x55a468fa9b70, 8192): Connection reset by peer
    Error: transport is closing

I see some recent activity in github related to this `Error: transport is closing` message, including some recent bug fixes, and talk of problems with AWS. Are there known problems also with Google Kubernetes Engine? Or have I failed to do some vital step?

If I can provide additional information to aide in troubleshooting, please advise.

**Comment by eicnix** [comment]
It looks like the `kubectl port-forward` isn't successful. Can you successfully `kubectl port-forward` to another pod in the same namespace?

**Comment by flimzy** [comment]
I may not be testing properly, but it seems not to be working. To test, I first ran `kubectl get pods --all-namespaces` which listed (among others):

    kube-system   heapster-v1.5.0-6d8b5c665c-bmj8q                 3/3       Running   0          25m

So I tried: `kubectl port-forward --namespace kube-system heapster-v1.5.0-6d8b5c665c-bmj8q 9999:80`, which outputs the following, then hangs (never (I waited a few minutes) returns to the prompt)

    Forwarding from 127.0.0.1:9999 -> 80

**Comment by bacongobbler** [comment]
@flimzy you'll want to port-forward to port 44134

**Comment by bacongobbler** [comment]
@flimzy you'll want to port-forward to port 8082 as per the [chart's exposed external port](https://github.com/kubernetes/charts/blob/master/stable/heapster/values.yaml#L26). :)

**Comment by bacongobbler** [comment]
And what @eicnix is suggesting is to create a tunnel to tiller, not to the chart itself. e.g.

```
kubectl port-forward --namespace kube-system my-tiller-pod 44134:44134
```

Then in another terminal:

```
HELM_HOST=127.0.0.1:44134 helm ...
```

**Comment by flimzy** [comment]
I was just trying to forward to any random pod in the same namespace. I selected 'heapster' randomly, and tried port 80 because I saw it listed in the `get svc` output:

    heapster               ClusterIP   10.23.248.28    <none>        80/TCP          3m

But port 8082 works. So next I tried `kubectl port-forward --namespace kube-system tiller-deploy-5b48764ff7-nrndl 44134:44134` as suggested, then in another terminal `telnet localhost 44134`, and on the original terminal I see:

    $ kubectl port-forward --namespace kube-system tiller-deploy-5b48764ff7-nrndl 44134:44134
    Forwarding from 127.0.0.1:44134 -> 44134
    Handling connection for 44134

So it seems to be working this way, but still failing with `helm install` et al.

**Comment by flimzy** [comment]
I have also verified that helm works properly if I rebuild the cluster, and don't use any tls options with `helm init`.

**Comment by flimzy** [comment]
Here is the full script I'm using to create my GKE cluster and initialize helm.

    REGION=us-east1 # US South Carolina, eligible for always-free
    #REGION=europe-west4 # Netherlands

    gcloud config set compute/zone ${REGION}-b
    gcloud config set compute/region ${REGION}
    gcloud container clusters create \
        --disk-size=10 \
        --machine-type=f1-micro \
        --num-nodes=4 \
        --cluster-version 1.9.2-gke.1 \
        ${CLUSTER_NAME}

    rm ca.* tiller.* helm.*
    openssl genrsa -out ./ca.key.pem 4096
    openssl req -key ca.key.pem -batch -new -x509 -days 7300 -sha256 -out ca.cert.pem -extensions v3_ca
    openssl genrsa -out ./tiller.key.pem 4096
    openssl genrsa -out ./helm.key.pem 4096
    openssl req -key tiller.key.pem -batch -new -sha256 -out tiller.csr.pem
    openssl req -key tiller.key.pem -batch -new -sha256 -out helm.csr.pem
    openssl x509 -req -CA ca.cert.pem -CAkey ca.key.pem -CAcreateserial -in tiller.csr.pem -out tiller.cert.pem
    openssl x509 -req -CA ca.cert.pem -CAkey ca.key.pem -CAcreateserial -in tiller.csr.pem -out helm.cert.pem

    # kubectl create serviceaccount tiller --namespace kube-system
    kubectl create -f rbac-config.yaml
    helm init \
        --tiller-tls \
        --tiller-tls-cert ./tiller.cert.pem \
        --tiller-tls-key ./tiller.key.pem \
        --tiller-tls-verify \
        --tls-ca-cert ca.cert.pem \
        --service-account=tiller

And rbac-config.yaml copied verbatim from [here](https://docs.helm.sh/using_helm/#example-service-account-with-cluster-admin-role).

**Comment by flimzy** [comment]
The issue mentioned in the [troubleshooting section](https://kubernetes.io/docs/getting-started-guides/ubuntu/troubleshooting/) of the docs seems to perfectly describe my scenario, but the solution depends on juju, which I'm not using with GKE. How can I implement the same solution using `kubectl` commands?

**Comment by flimzy** [comment]
The problem I found was due to a typo in my key creation.

> openssl req -key tiller.key.pem -batch -new -sha256 -out helm.csr.pem

should have been

> openssl req -key helm.key.pem -batch -new -sha256 -out helm.csr.pem
