### ISSUE TITLE
How to set helm bin path to be part of jar file

### ISSUE THREAD

**Issue by kamesh2229** [kubernetes/helm#3604]
Hi,

I am new to helm and I have the below query.

I am automating the helm chart installation using java.

I have installed the helm binary under path /home/user/bin/helm and whenever the helm command to be executed I am giving the complete path and the command like 
/home/user/bin/helm list releasesname.

When I execute the code in my local environment it executes.Now I wanted to execute the same code in a Jenkins environment where it is not good way to have my home directory mentioned in the code.

Is there a way to set the generic path for the helm binary to execute the helm commands that the code can be executed from any environment?

**Comment by kamesh2229** [comment]
Can someone help me out ... if required will share more details ..

**Comment by eicnix** [comment]
@kamesh2229 This is more a general [path](http://www.linfo.org/path_env_var.html) issue. You probably want to add the helm binary to your path on both your machine and your Jenkins workers. Then you won't need to deal with absolute directories anymore.

**Comment by bacongobbler** [comment]
Closing as answered. I also provided a similar answer in #3630 as well that provides an example. Hope that helps!
