### ISSUE TITLE
Docs: condition issue when value is not defined

### ISSUE THREAD

**Issue by lbogdan** [kubernetes/helm#3627]
In the [If/Else section of Flow Control](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/control_structures.md#ifelse) there's a template having the line
```
{{ if eq .Values.favorite.drink "coffee" }}mug: true{{ end }}
```
and the doc reads:

> Since we commented out drink: coffee in our last example, the output should not include a mug: true flag.

However, running `helm install --dry-run --debug` when `favorite.drink` is not defined (commented out) in `values.yaml` returns this error:
```
Error: render error in "mychart/templates/configmap.yaml": template: mychart/templates/configmap.yaml:9:7: executing "my chart/templates/configmap.yaml" at <eq .Values.favorite....>: error calling eq: invalid type for comparison
```
, most probably because it tries to compare `nil` to a string.

LE: It can of course be fixed by changing it to
```
{{ if .Values.favorite.drink }}{{ if eq .Values.favorite.drink "coffee" }}mug: true{{ end }}{{ end }}
```

**Comment by jfrederickson** [comment]
Just ran into this as well; that seems reasonable to me. Maybe also worth pointing out that the parent key must be defined? If the `favorite` key isn't defined in Values at all, that check will throw an error.
