### ISSUE TITLE
make build failure

### ISSUE THREAD

**Issue by mccricardo** [kubernetes/helm#3639]
I'm trying to build helm locally using [these](https://docs.helm.sh/developers/) instructions and I get this error:

```
$ make build
GOBIN=$GOPATH/go/src/k8s.io/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=c31246467c1475bb5fe53f46035934f6e7b2f9e8 -X k8s.io/helm/pkg/version.GitTreeState=dirty' k8s.io/helm/cmd/...
# archive/tar
/usr/local/go/src/archive/tar/stat_atim.go:14:36: statAtime redeclared in this block
	previous declaration at /usr/local/go/src/archive/tar/stat_actime1.go:14:36
/usr/local/go/src/archive/tar/stat_atim.go:18:36: statCtime redeclared in this block
	previous declaration at /usr/local/go/src/archive/tar/stat_actime1.go:18:36
Makefile:28: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by bacongobbler** [comment]
Hmm... Those paths indicate that there's something wrong with your installation of Go.

> /usr/local/go/src/archive/tar/stat_atim.go:14:36

Which version of Go are you using, and how was it installed?

**Comment by mccricardo** [comment]
```
$ go version
go version go1.10 linux/amd64
```
It was installed using [these](https://golang.org/doc/install#tarball) instructions on Ubuntu.

**Comment by bacongobbler** [comment]
Odd. I'm on Go 1.10 and having no issues. I'd start troubleshooting there though!

```
><> go version
go version go1.10 linux/amd64
><> make build
GOBIN=/home/bacongobbler/go/src/k8s.io/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=c31246467c1475bb5fe53f46035934f6e7b2f9e8 -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
><> ./bin/helm version -c
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"c31246467c1475bb5fe53f46035934f6e7b2f9e8", GitTreeState:"clean"}
```

**Comment by mccricardo** [comment]
Thank you @bacongobbler. Still haven't found the issue though.

**Comment by mccricardo** [comment]
I reinstalled go and recloned the repository and now I am now able to build it without any issue.

@bacongobbler thank you again.

**Comment by vielmetti** [comment]
I ran into the same problem, and after reading https://github.com/perkeep/perkeep/issues/905 figured out why I had things go wrong. (You have to uninstall Go 1.n before installing Go 1.n+1). 

I think this is actually an issue for the Go install documentation, so I'll bring it up there.
