### ISSUE TITLE
What the purpose of --namespace in helm upgrade command?

### ISSUE THREAD

**Issue by tiukhtinvladimir** [kubernetes/helm#3657]
A chart that has been deployed once has namespace already. At the same moment we can not have releases with the same name in different namespaces. So what the purpose of ```--namespace``` in ```helm upgrade``` command? I understand why do we need it in ```helm install``` - to alter a namespace. But what about ```helm upgrade```? Thanks

**Comment by bacongobbler** [comment]
It's actually fairly useless at this point, but we need to keep it in there for backwards compatibility reasons until 3.0. If you supply a namespace that differs from the one supplied during `helm install`, you'll receive a warning message.

https://github.com/kubernetes/helm/blob/master/cmd/helm/upgrade.go#L161-L166

**Comment by michelleN** [comment]
This is one of the problems with integrating a top level command's functionality (`install`) as a flag on a different command (`upgrade`). We end up wanting smaller features and flags (like `--namespace`) from the other top level command (`install` in this case) as well and then we potentially have a never ending list of flags that don't make sense on the intended command (`upgrade`). We should definitely re-think this when we have the chance to break backwards compatibility like @bacongobbler mentioned.

Does this answer your question?

**Comment by tiukhtinvladimir** [comment]
Thanks guys. You are awesome
