### ISSUE TITLE
helm upgrade failed due to new NodeAffinity & Configmap added

### ISSUE THREAD

**Issue by bluezoe** [kubernetes/helm#3660]
The client/server version is 2.7.2

My scenario
1. installed the old version chart
    helm install -n svc ./svc-0.9.3.tgz

2. There are several changes made on the chart version 0.9.4, tried to upgrade running release
   helm upgrade svc ./svc-0.9.4.tgz

    upgrade failed w/ following error message:
Error: UPGRADE FAILED: Job.batch "svc-set-ds" is invalid: spec.template: Invalid value: core.PodTemplateSpec.......

     I compared the difference on the job "svc-set-ds" with latest version, found in 0.9.4, the job resource added a new NodeAffinity like:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
 
3. I removed the NodeAffinity section in job resource of 0.9.4 chart, tried to upgrade again. This time, failed with another problem:
     Error: UPGRADE FAILED: no ConfigMap with the name "svc-config" found
    The configmap is added in 0.9.4 and not available in 0.9.3. But after upgrade failed, I found the configmap already created.

     Not sure above problems are as design. If yes, is there a doc to describe which change will block the upgrade?

**Comment by thomastaylor312** [comment]
@bluezoe For point 2, it looks like either a value you provided, or the chart you are using isn't valid. Based on the error message you posted, it doesn't look like a Helm issue.

As for point 3, I personally have seen that happen before only when you are creating resources across multiple namespaces. Is that the case here?

**Comment by bluezoe** [comment]
@thomastaylor312 
thanks for the resp.
for point 2, the chart is valid. If I deleted old one and install the new version, everything works well. Following is the full error message, and as I mentioned, the only changes of these two versions are there is "NodeAffinity" added in the new version.

[error.txt](https://github.com/kubernetes/helm/files/1805322/error.txt)

For point 3, all resources are located in default namespace.

**Comment by thomastaylor312** [comment]
Ok, thank you for the full error. So it looks like the actual error message is that the "field is immutable." This is because you are changing a field that Kubernetes does not allow you to change. To get around this and recreate, you should be able to use the `--force` flag with `helm upgrade` to force it to recreate the resource

**Comment by bluezoe** [comment]
thanks a lot, after add "--force", the upgrade works.
One question for this option, will it lead to some risk? I cannot understand fully for this. Is there some doc for this?

**Comment by thomastaylor312** [comment]
The only risk is that it will delete and recreate any resource where the patching fails. As for docs, the only documentation for that flag is in the `--help` output.

**Comment by bluezoe** [comment]
thanks for the explanation, @thomastaylor312 
I think all my concerns already resolved and this issue can be closed.

**Comment by jiezh** [comment]
hello @thomastaylor312 , regarding the issue about newly added configmaps, if we use --force flag, will it impact on other resource? or it will only impact the configmaps. 
From my point of view, it is kind of strange that helm consider it is failure due to previous version doesn't have the configmap added in current version.
Thank you

**Comment by bacongobbler** [comment]
--force is a forced deletion of all resources, and retry installing from a fresh slate. It is considered a destructive action and it will impact other resources defined in the chart.
