### ISSUE TITLE
Is there any way to get kube context in post hook?

### ISSUE THREAD

**Issue by dotw** [kubernetes/helm#3718]
Hi, I want to use the post hook to do additional tasks after the chart is installed and these tasks may need to execute some "`kubectl`" commands.  Is there any way that I can get `kube` context in the post container? thanks.

**Comment by jascott1** [comment]
@dotw Containers should have the necessary tokens and certs to talk to the api at `/var/run/secrets/kubernetes.io/serviceaccount/`

See https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

**Comment by dotw** [comment]
thanks @jascott1 . it works for me.
