### ISSUE TITLE
get-install.sh: The specified key does not exist

### ISSUE THREAD

**Issue by gtaylor** [kubernetes/helm#372]
Apologies if this has already been accounted for, but a quick glance didn't turn anything immediately recognizable up in the issue tracker. I'm trying to install, but it looks like the zip we're attempting to retrieve doesn't exist in Google Storage.
```
$ ./get-dm.sh 
Downloading dm-v1.2-linux-x86_64.zip...
[dm-v1.2-linux-x86_64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of dm-v1.2-linux-x86_64.zip or
        dm-v1.2-linux-x86_64.zip.zip, and cannot find dm-v1.2-linux-x86_64.zip.ZIP, period.
$ cat dm-v1.2-linux-x86_64.zip 
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>
```

**Comment by jackgr** [comment]
@gtaylor: Are you trying to install from HEAD? 

If so, apologies, but HEAD is not stable for installation. Please use [release-v1.2.1](https://github.com/kubernetes/deployment-manager/releases/tag/v1.2.1), instead.

**Comment by gtaylor** [comment]
I am trying to install from HEAD in that I copy/pasted this from the README currently on HEAD:
```
curl -s https://raw.githubusercontent.com/kubernetes/deployment-manager/master/get-install.sh | sh
```
The install from v1.2.1 seems to have worked though, thanks!

**Comment by jackgr** [comment]
​Ah. We added a note advising people to install from the latest release,
but didn't catch the URL. Thanks for pointing that out. Will fix.​

**Comment by jackgr** [comment]
This is fixed now.
