### ISSUE TITLE
rpc error in large chart

### ISSUE THREAD

**Issue by samar1n** [kubernetes/helm#3720]
/kind/bug

I'm using a big chart, and when I try to get helm list to determinate what release number i'm currently on. I get the following error:

`Error: rpc error: code = ResourceExhausted desc = trying to send message larger than max (27798319 vs. 20971520)`

There are something about 96 yaml files and 8370 lines in total.

I've tried a few latest versions already with the same issue. 

Currently installed version i use:

`helm version`

```
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"4711d5b8b8283a045b0ee118a5ac450346417919", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"4711d5b8b8283a045b0ee118a5ac450346417919", GitTreeState:"clean"}
```

if you need some additional info, please let me know. Thanks

**Comment by bacongobbler** [comment]
you might be interested in #3703 which allows for a larger default message size.

**Comment by samar1n** [comment]
@bacongobbler thanks for suggestion. its works
