### ISSUE TITLE
How to get Tiller to pass the user's token thru to K8s for proper RBAC Authorization

### ISSUE THREAD

**Issue by RudyBone** [kubernetes/helm#3729]
I see there was some discussion starting almost a year ago concerning Tiller support for User impersonation.  We run a multi-tenant system, with different RBAC role/bindings for users and we would like Tiller to pass the kubectl token it receives from helm on through to the API Server in the Authorization header.  Does anyone have a branch that does this or can anyone guide on where in the Tiller source I might make this change myself

**Comment by jeffshaver** [comment]
@mumoshu Looking through your branch, it's not immediately apparent whats left to do. Can you help me understand the things that still need to be done? Thanks

**Comment by bacongobbler** [comment]
Closing in favour of the comment I made in https://github.com/kubernetes/helm/issues/1918#issuecomment-378700824. The tl;dr is that we are not planning on implementing this for Helm 2, but the use case for sending user impersonation tokens to Tiller isn't necessary in Helm 3 because Tiller is being removed.

**Comment by jeffshaver** [comment]
@bacongobbler thanks for the follow up. that helps. is there anywhere to follow v3 development? or is it only in conceptual stages right now?

**Comment by bacongobbler** [comment]
It's still in conceptual stages right now. We'll announce when development is underway on the mailing list. :)

**Comment by gsemet** [comment]
Hi. Is there any way to have authentication with a tillerless deployment? I can have tiller use a user's pem+crt, but if I wish to use a token (similar to `kubectl --token`)
