### ISSUE TITLE
How is my local helm connect to remote tiller?

### ISSUE THREAD

**Issue by shenxg13** [kubernetes/helm#3745]
Output of `helm version`:
PS D:\vscode-workspace\helm-charts\echoheaders-helm> helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
PS D:\vscode-workspace\helm-charts\echoheaders-helm> kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

**I got a local helm in my laptop and a remote tiller in a k8s cluster, i didnt setup the service nodeport for the tiller pod:**
[root@192-168-0-52-kube01 local]# kubectl get svc -n kube-system tiller-deploy
NAME            TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
tiller-deploy   ClusterIP   10.17.22.29   <none>        44134/TCP   1d

**But my local helm can connect to that tiller and install a release:**
PS D:\vscode-workspace\helm-charts\echoheaders-helm> helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
PS D:\vscode-workspace\helm-charts\echoheaders-helm> helm list
NAME            REVISION        UPDATED                         STATUS          CHART               NAMESPACE
anxious-panda   1               Fri Mar 23 15:10:39 2018        DEPLOYED        echoheaders-helm-1  default
fuzzy-sponge    1               Fri Mar 23 14:18:09 2018        DEPLOYED        echoheaders-helm-1  default
PS D:\vscode-workspace\helm-charts\echoheaders-helm> kubectl get pods -l app=echoheaders-helm
NAME                                             READY     STATUS    RESTARTS   AGE
anxious-panda-echoheaders-helm-6689896b7-8dld2   1/1       Running   0          15m
fuzzy-sponge-echoheaders-helm-667bbc846b-gpclv   1/1       Running   0          1h
PS D:\vscode-workspace\helm-charts\echoheaders-helm>

I dont kown how helm can do this.

**Comment by bacongobbler** [comment]
Magic ;)

I'll explain once I'm in the office.

**Comment by shenxg13** [comment]
Ok, thanks a lot.

**Comment by bacongobbler** [comment]
Sorry I didn't get back to this earlier. The TL;DR is that helm uses the same API endpoints as [`kubectl port-forward`](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/) to initiate a tunnel to Tiller. This works both outside and inside the cluster. You can see this in action with the `--debug` flag.

**Comment by shenxg13** [comment]
I got that, thank you very much.
