### ISSUE TITLE
Helm del --purge leaves vloumes & namespaces

### ISSUE THREAD

**Issue by anillingutla** [kubernetes/helm#3760]
I tried out many times. 
1. Lots of volumes and name spaces are left in the system. 
2. If i have 2 node kubernetes cluster. it wouldnt start 3rd member in consul.
3. Orphans are not cleaned while purging a release.

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
this is working as intended. Helm does not delete Volume claims or namespaces requested by the package. However, helm should clean up any other resources that do not have an annotation with the value `"helm.sh/resource-policy": keep`. See https://github.com/kubernetes/helm/issues/1875 for more info.
