### ISSUE TITLE
help

### ISSUE THREAD

**Issue by griddall** [kubernetes/helm#3763]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
Hey @griddall, if you could please provide more information that would be helpful. Because there's no information to go on here I'm going to assume this was either opened by a bot or by mistake, but please re-open with more information and we can take a look into your issue. Thanks!

**Comment by griddall** [comment]
No idea how this got created.  Thanks for closing
