### ISSUE TITLE
Windows back slash carry to file name after unzip

### ISSUE THREAD

**Issue by mysterytony** [kubernetes/helm#3764]
Output of `helm version`:

`Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}`

When use `helm package ./blah` command on windows, and then unpack (use `tar`) the `tgz` file under linux, I see

![image](https://user-images.githubusercontent.com/7595263/37926838-6b9edd2e-3106-11e8-9718-a8be036736c6.png)

That is, the black slashs that come from windows become the file names.

**Comment by bacongobbler** [comment]
This seems like an easy fix for someone interested in getting their feet wet with the project!

**Comment by muehlburger** [comment]
I'm not sure if I understand it correctly. 

Do you want to always use forward slash in the resulting tgz? Regardless if created on a windows or a linux machine?

**Comment by mysterytony** [comment]
Maybe I didn't word correctly, Basically, if you issue a `helm package ./blahblah` command in Windows and when you untar the tarball, the files are flattened (the directory structure does not preserve).

As you can see in the screenshot, I wrote `ls` and the files that are supposed be in the `charts` folder are at the top level of the tarball. Looks like the backslashes became part of the file name.

Hope that helps

**Comment by muehlburger** [comment]
Thanks that makes it clearer for me. Will try to come up with a fix.  :-)

**Comment by bastianeicher** [comment]
Hi guys, we (@andreasbieber, @typusomega) have also run into this issue.
I see there's been an open pull request to fix this for about a month. Anything blocking it being merged?

**Comment by thomasmey** [comment]
Hi @bacongobbler, we did ran into a issue that looks exactly like this issue. The backslashes are part of the filename when helm was run under windows. But our version is 3.1.1.
Is it possible that this bug was re-introduced into the helm 3.x branch somehow?
