### ISSUE TITLE
feature request: cluster semver via .Release object

### ISSUE THREAD

**Issue by gladiatr72** [kubernetes/helm#3765]
What do folks think about this?  It can be made part of Tiller's status data or some such.  

Since the release of last week's security updates that broke lots of things' (docker, minio, etc) ability to start if their configuration was mounted from _anyConfig_ the obvious solution has been to shove an init container definition into the manifest that copies the contents of the mounted config into a shared _emptyDir_.  (I noticed several charts in the official repository have already been updated with this)

The problem with _initContainers_ is [this](https://github.com/kubernetes/kubernetes/issues/45627).

Summary:  > 1.5.x < 1.8  You can create a deployment that creates `.spec.template.spec.initContainers[]`; however, any updates to the _Deployment_ will result in _no change_ to the deployed `...initContainers[]` definitions.  

In a nutshell, initContainers got rooked in kube v1.6 and v1.7. Deployments that require updates to the _Deployment_'s init-container definitions will fail.  At best the failure is absolute and there is some indication that Things Are Not Quite Right.  Unfortunately the outlined problem is also represented by the scheduler quietly discarding updates to `...initContainers[]`.  The result: if you want (now need) to use init-containers with kube v1.5><v1.8, and expect those _Deployment_s to work, you must continue using the `beta.kubernetes.io/init-containers` annotation.

I have a helm pattern that I've come up with (in the process of writing a blog post about it) that provides a solution--at this point whether the annotation or spec form is determined with a `.Values.initContainersAs` variable.  It works (yay!), but it occurred to me (not for the first time) that it would be extremely useful to have access to the cluster version that _Tiller_ is living on.  Right now I have to add documentation to the chart indicating to the user: Hey, you need to know what version you're running on each cluster this gets deployed to.  Set this variable to X if the kube version is A, Y if the version is B, etc.

I'm thinking of it in terms of: _Helm wants to be the package manager for Kubernetes. Packages became a real thing when they provided tooling so a user could get software onto a machine, sometimes in non-trivial configuration patterns, without having to become an expert on every component, their build systems and dependencies.  The more metadata relevant to the target cluster that helm can provide to a Chart writer , the more opportunity for the Chart to Do It Correctly. 

That's all.  Thanks for reading! :smile:

**Comment by jascott1** [comment]
Hi @gladiatr72 

it sounds like you are looking for `.Capabilities` in the [built-in objects](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/builtin_objects.md). If not could you explain more about what info you need from the server?

**Comment by gladiatr72** [comment]
Brilliant! That's exactly it. Thank you!
