### ISSUE TITLE
helm lint should fail when it can't find a Chart.yaml

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/helm#3769]
helm lint should fail when it can't find a chart to lint.

```
helm lint .
==> Skipping .
No chart found for linting (missing Chart.yaml)

0 chart(s) linted, no failures
echo $?
0
```
Output of `helm version`:
2.8.2

Output of `kubectl version`:
1.9.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

Expected:
A non-zero exit code.

**Comment by bacongobbler** [comment]
fixed via #3783.
