### ISSUE TITLE
Remove dm client from repository

### ISSUE THREAD

**Issue by sgoings** [kubernetes/helm#377]
From discussion in the helm Slack channel:

> @sgoings: @jackgr @technosophos if I can add one item/question. We really need to clean up the issue of the two clients. currently we have dm and helm. With helm used to deploy dm….it’s confusing. We need to merge dm CLI in helm cli….

We can always retrieve the dm client from the Git history and @jackgr says most of the logic in the dm client has been lifted and placed into the helm client.

**Comment by sgoings** [comment]
Ok - after a discussion in person we’ll probably remove the dm client after we've reached significant feature similarity in the helm client.

**Comment by jackgr** [comment]
AFAICT this has been done. Please reopen if that's not the case.
