### ISSUE TITLE
Repurpose push and install scripts (re: Helm)

### ISSUE THREAD

**Issue by sgoings** [kubernetes/helm#378]
Once we complete the work to remove the dm client from this repository (#377) we should repurpose the dm-push.sh (pushes cli binary to a google storage bucket) and get-install.sh (downloads cli binary from google storage bucket) scripts to be Helm specific.

**Comment by runseb** [comment]
While not totally related. I think the main Makefile needs to be updated so that we can do this push. Also it needs to include the push of the new docker images for dm (resourcifier/manager/expandybird).

**Comment by jackgr** [comment]
Whoever implements this issue may want to pull from [get-install.sh](https://github.com/kubernetes/helm/blob/release-v1.2.1/get-install.sh) and [dm/Makefile](https://github.com/kubernetes/helm/blob/release-v1.2.1/dm/Makefile) in release-v1.2.1, which are smarter than the ones at head.

Specifically, the get-install.sh is smarter about detecting the current arch and os, and the dm/Makefile contains a target that does a cross build and pushes the client binaries for all platforms to the storage bucket.

**Comment by jackgr** [comment]
#557

**Comment by jackgr** [comment]
Fixed by #556.
