### ISSUE TITLE
Docs developing charts

### ISSUE THREAD

**Issue by spacecat** [kubernetes/helm#3780]
From the docs: https://docs.helm.sh/developing_charts/

charts/             # OPTIONAL
templates/          # OPTIONAL

While the charts and templates directories are optional there must be at least one chart dependency or template file for the chart to be valid.

This is contradictory. Please elaborate.

**Comment by bacongobbler** [comment]
those directories are mandatory. I've cleared up some confusion in https://github.com/kubernetes/helm/pull/3876.
