### ISSUE TITLE
Error x509: certificate signed by unknown authority when installing chart

### ISSUE THREAD

**Issue by gzcf** [kubernetes/helm#3790]
Output of `helm version`:

Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.10", GitCommit:"6c7eb1f61f963295b53a1d86f488ec1a54da7523", GitTreeState:"clean", BuildDate:"2017-09-13T19:09:57Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.10", GitCommit:"6c7eb1f61f963295b53a1d86f488ec1a54da7523", GitTreeState:"clean", BuildDate:"2017-09-13T18:59:02Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

My on-premise machine

Error occurred  when I was installing [Polyaxon](https://docs.polyaxon.com/installation/deploy_polyaxon/).

```
gzc@ubuntu:~/polyaxon-deploy$ helm install polyaxon/polyaxon --name=polyaxon --namespace=polyaxon --timeout 3000 -f config.yml
Error: Get https://10.10.0.1:443/version: x509: certificate signed by unknown authority
```

10.10.0.1 is my kubernetes service

```
NAMESPACE     NAME                       CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
default       svc/kubernetes             10.10.0.1      <none>        443/TCP     5h
```

Logs from tiller

```
E0329 08:35:38.663295       1 config.go:330] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
E0329 08:35:38.664045       1 config.go:330] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
[main] 2018/03/29 08:35:38 Starting Tiller v2.8.2 (tls=false)
[main] 2018/03/29 08:35:38 GRPC listening on :44134
[main] 2018/03/29 08:35:38 Probes listening on :44135
[main] 2018/03/29 08:35:38 Storage driver is ConfigMap
[main] 2018/03/29 08:35:38 Max history per release is 0
[tiller] 2018/03/29 08:39:30 preparing install for polyaxon
[storage] 2018/03/29 08:39:30 getting release history for "polyaxon"
[storage/driver] 2018/03/29 08:39:30 query: failed to query with labels: Get https://10.10.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dpolyaxon%2COWNER%3DTILLER: x509: certificate signed by unknown authority
[tiller] 2018/03/29 08:39:30 failed install prepare step: Get https://10.10.0.1:443/version: x509: certificate signed by unknown authority
```

I deployed kubernetes with CA and some certs generated by myself. They are *.pem in those config:

```
cat apiserver
KUBE_API_ARGS=" --bind-address=0.0.0.0 \
 --secure-port=6443 \
 --basic_auth_file=/opt/k8s/config/userinfo \
 --etcd-servers=http://docker1:2379,http://docker2:2379,http://docker3:2379 \
 --logtostderr=false \
 --allow-privileged=true \
 --anonymous-auth=false \
 --service-cluster-ip-range=10.10.0.0/16 \
 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,SecurityContextDeny,ResourceQuota \
 --service-node-port-range=30000-32767 \
 --runtime-config=batch/v2alpha1 \
 --kubelet_port=10250 \
 --authorization-mode=RBAC \
 --service_account_key_file=/opt/k8s/auth/ca-key.pem \
 --client-ca-file=/opt/k8s/auth/ca.pem \
 --tls-cert-file=/opt/k8s/auth/apiserver.pem \
 --tls-private-key-file=/opt/k8s/auth/apiserver-key.pem \
 --log_dir=/var/log/k8s/ \
 --v=2"

cat controller-manager
KUBE_CONTROLLER_MANAGER_ARGS="--master=http://127.0.0.1:8080 --node-monitor-grace-period=18s --resource-quota-sync-period=10s --service-account-private-key-file=/opt/k8s/auth/ca-key.pem --logtostderr=false --log-dir=/var/log/k8s --v=2"
```

I guess I need to config something like `--service-account-private-key-file=/opt/k8s/auth/ca-key.pem` for tiller. But I am new to kubernetes and helm ecosystem, don't know how to do.

**Comment by bacongobbler** [comment]
seems like the client you use to communicate with kubernetes isn't working properly but isn't necesarily an issue with helm. I'll tag this as a support issue, but I don't think there's anything actionable we can do on our end to fix this.

**Comment by gzcf** [comment]
Seems like It's because that I was using newer kubectl which isn't compatible with old kubernetes and kubernetes may be too old (1.6) for helm. After upgrade kubernetes to 1.8 and use same version kubectl, this error is gone. You can close this issue.

**Comment by macknight** [comment]
how can you check your kubernetes version?
kubernetes -v ? @gzcf

**Comment by bacongobbler** [comment]
`kubectl version`

**Comment by RakeshNagarajan** [comment]
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
