### ISSUE TITLE
Upgrades failing with missing resources

### ISSUE THREAD

**Issue by jacobtomlinson** [kubernetes/helm#3791]
When upgrading a chart I am getting an error stating `Error: UPGRADE FAILED: no ServiceAccount with the name "pod-culler" found`.

When I run `kubectl get serviceaccounts` it is clearly listed there

```
$ kubectl get serviceaccounts                                                
NAME                                       SECRETS   AGE
...
pod-culler                                 1         1m
...
```

If I manually remove the service account and run the helm upgrade again it recreates the service account and then errors again on the next resource, this time a role.

I'm wondering if this error is misleading as when there truly is no service account found it gets created. So it must be finding it somehow but then that is causing an error.

### Debug info

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-29T10:10:42Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.3-gke.0", GitCommit:"a7b719f7d3463eb5431cf8a3caf5d485827b4210", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:01Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `GKE`

**Comment by majewsky** [comment]
Duplicate of #3785.

**Comment by jacobtomlinson** [comment]
Amazing! @yuvipanda beat me to it yet again 😆. I'll close this in favor of #3785.
