### ISSUE TITLE
Capabilities.KubeVersion -> string comparison instead of semver

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/helm#3801]
**Issue:**
Capabilities.KubeVersion.Minor comparison is done as strings, and "7" is greater than "10".

As explained also:
https://github.com/kubernetes/charts/issues/3002 
https://github.com/kubernetes/charts/pull/3331

**This bug makes the current helm (2.8.2) incompatible with k8s 1.10.**

Output of `helm version`:
2.8.2
Output of `kubectl version`:
1.10
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
byo

**Comment by ReSearchITEng** [comment]
looks to me it should be fixed in each chart instead.

**Comment by jamesbroadhead** [comment]
Hi @ReSearchITEng - I'm afraid that I don't follow your final comment here. 
If a Chart wants to support both kubernetes 1.9 and 1.10, but not 1.8 or below, what kubeVersion value should be used?

**Comment by ReSearchITEng** [comment]
@jamesbroadhead the comparison in the helm chart should be done not as strings, but using semverCompare: 
```
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.controller.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.controller.service.externalTrafficPolicy }}"
{{- end }}
```
(example from nginx chart: https://github.com/kubernetes/charts/blob/bc178b63c7df469f1bbccd86629f8cb573a32292/stable/nginx-ingress/templates/controller-service.yaml)

**Comment by jamesbroadhead** [comment]
@ReSearchITEng  is that possible in the top-level kubeVersion definition though? 

```
name: my-thing
description: hello
version: 0.1
kubeVersion: ">=1.9"
```
