### ISSUE TITLE
Possible duplication in unit tests of release_testing command

### ISSUE THREAD

**Issue by adshmh** [kubernetes/helm#3807]
There may be some duplication in unit tests of the `release_testing` command:

https://github.com/kubernetes/helm/blob/531deec220a2b7dc748e86f760a08248e6f39527/cmd/helm/release_testing_test.go#L85-L105

This could be refactored to utilize `runReleaseCases`.

**Comment by adshmh** [comment]
I will submit a PR to propose the refactoring.

**Comment by michelleN** [comment]
thanks!
