### ISSUE TITLE
[2.8.2] helm get manifest: Error: context deadline exceeded

### ISSUE THREAD

**Issue by bjornmagnusson** [kubernetes/helm#3833]
helm get manifest <release> does not work in 2.8.2.
Works fine in 2.8.1
Response: Error: context deadline exceeded

Output of `helm version`:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker for Windows

**Comment by michelleN** [comment]
This sounds like it's a duplicate #3658 which was resolved via #3661 and is available in 2.9.2-rc2. Could you try helm [v2.9.0-rc2](https://github.com/kubernetes/helm/releases/tag/v2.9.0-rc2) to see if your problem is fixed?

Thank you

**Comment by bjornmagnusson** [comment]
Thanks for quick response and the pointer, looks very related. Will try out the RC.

**Comment by bjornmagnusson** [comment]
Works fine in 2.9.0 for windows (Powershell) and mac. 
However, when using helm client in Bash for Windows it crashes with stacktraces related to syscalls (similar to #3834)
Can add stacktrace on Monday, if needed.

**Comment by bacongobbler** [comment]
Yes please! We can at least nail down if it's unrelated to the original issue you're seeing. :)

**Comment by bacongobbler** [comment]
This looks like either an upstream issue in k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime or in Go itself, but it doesn't look like the original issue you were seeing. Would you mind opening a new ticket upstream at https://github.com/kubernetes/apimachinery/issues?

**Comment by rvandegrift** [comment]
I was also affected by this issue on 2.8.2, upgrading to 2.9.0-rc3 fixed it.

**Comment by DanielRamosAcosta** [comment]
I think I'm having the same issue on v2.13.1 😢
