### ISSUE TITLE
more transparent tls handling

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#3841]
its not awesome UX to have to keep specifying `--tls` on each helm command. 

it'd be nice to be able to configure TLS mode in a config file in `~/.helm` or something. Maybe when you specify `--tls` in `helm init` helm should remember that setting and then use TLS from then on?

Or have an environment variable to default TLS mode?

**Comment by bacongobbler** [comment]
Dupe of https://github.com/kubernetes/helm/issues/3456
