### ISSUE TITLE
Support chart- prefix for linting folder

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/helm#3845]
Currently helm lint requires that the folder match the name of the chart.  This is fine when you have a monorepo that contains a bunch of charts or a repo that contains code and a helm chart.

I have had several situations where it would be useful to just have the chart at the top directory.

git repo - `chart-mychart` with a Chart.yaml of `mychart` at the root.  This will fail helm lint and if I want it to pass I either need to have a root folder called `mychart` or I need to do some work in the CI process to move the Chart.yaml and the the other files into a new folder called `mychart`

Recommendation helm lint should pass for a folder named `mychart` or for a folder `chart-mychart`.  This could be done through a flag or supported by default.

**Comment by bacongobbler** [comment]
I don't think this is something we want to accept given that charts with a different name than what's in Chart.yaml breaks the package format (see @technosophos's comment in #1979). Basically this would not play nicely with the rest of the tooling around chart conventions.

Is there a particular reason why having a directory structure such as `chart/mychart` wouldn't work for you? You can then just use a script around this workflow:

```
pushd chart
  for i in $(ls); do
    helm lint $i
  done
popd
```

**Comment by sstarcher** [comment]
@bacongobbler I can certainly do that and that's what I currently do.  I was just hoping for a better solution.

Git repo - `chart-mychart`
Folder structure
* chart
  * mychart

It's just odd having a root directory that contains a single folder and that folder containers another single folder.
