### ISSUE TITLE
The name helm is already taken.

### ISSUE THREAD

**Issue by daveloyall** [kubernetes/helm#3861]
See #3284, #3278, #2659, and #2297.

See https://github.com/emacs-helm/helm

...and these:
* https://www.emacswiki.org/emacs/Helm 
* https://www.youtube.com/results?search_query=emacs+helm
* https://stackexchange.com/search?q=emacs+helm
* https://emacs.stackexchange.com/questions/tagged/helm
* https://github.com/emacs-helm/helm/wiki

FYI, Emacs helm is older and has more commits.  https://github.com/emacs-helm/helm/graphs/code-frequency vs https://github.com/kubernetes/helm/graphs/code-frequency 

Cheers!

**Comment by bacongobbler** [comment]
Closing as a wontfix. The duplication in names is unfortunate but the two tools are vastly different from each other that they don't collide with one another.
