### ISSUE TITLE
Helm occasionally hangs when working with Azure AKS cluster through VSCode terminal

### ISSUE THREAD

**Issue by idelix** [kubernetes/helm#3865]
I'm using helm through terminal in vscode against the kubernetes cluster running in Azure (AKS), helm commands occasionally just hands either on rollback, upgrade, delete commands.
At this point I need to kill terminal window even ctrl+c doesn't work.

Checking current deployments works fine:

```
C:\Temp\helm-example\testapi\testapi-chart [master ≡ +3 ~1 -0 !]> helm history boisterous-duck
REVISION        UPDATED                         STATUS          CHART                   DESCRIPTION
1               Tue Apr 10 13:26:52 2018        SUPERSEDED      testapi-chart-0.1.1     Install complete
2               Tue Apr 10 15:28:50 2018        DEPLOYED        testapi-chart-0.1.2     Upgrade complete
```

The rollback hangs:

```
C:\Temp\helm-example\testapi\testapi-chart [master ≡ +3 ~1 -0 !]> helm rollback boisterous-duck 1
Rollback was a success! Happy Helming!
```
At this point it just hangs...

After I kill terminal and run history it confirm that rollback was completed:

```
C:\Temp\helm-example\testapi [master ≡ +3 ~1 -0 !]> helm history boisterous-duck
REVISION        UPDATED                         STATUS          CHART                   DESCRIPTION
1               Tue Apr 10 13:26:52 2018        SUPERSEDED      testapi-chart-0.1.1     Install complete
2               Tue Apr 10 15:28:50 2018        SUPERSEDED      testapi-chart-0.1.2     Upgrade complete
3               Tue Apr 10 15:43:42 2018        DEPLOYED        testapi-chart-0.1.1     Rollback to 1
```

Output of `helm version`:

Client: &version.Version{SemVer:"v2.9.0-rc1", GitCommit:"280863d2362345450125ce15c3db504471dde2cf", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0-rc1", GitCommit:"280863d2362345450125ce15c3db504471dde2cf", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AKS

OS: 

Windows 10 v1709

**Comment by bacongobbler** [comment]
hey @idelix! Can you try running those commands in a different terminal like powershell or [cmder](http://cmder.net/)? Curious to hear if it's a terminal issue, a Windows issue or a Helm issue. I can't tell from first glance here. Thanks!

**Comment by idelix** [comment]
Hi @bacongobbler, for some reason I no longer have this issue, Helm work every time now so indeed it must have been something locally on my machine, I think this ticket can be closed but thanks for response.
