### ISSUE TITLE
[docs] Scrolling the docs is not a pleasant stroll

### ISSUE THREAD

**Issue by thochra** [kubernetes/helm#3879]
Hello,

I have been using the docs website for only few hours and there is something that is going to make me crazy => scrolling the docs is a nightmare !!!

I don't know why but:
 - after a while or when reaching a specific page's position scroll is blocked and then after some mouse wheel rotations it works again. That behaviour is just ugly. I feel like someone tied up my two shoes' shoelaces together. (or like this http://gph.is/1Sie7un)
 - can't use arrows or page up/down for scrolling (at least firefox linux, chrome seems ok with that)

Hope you'll be able to do something for that :pray:

Thanks in advance,
Thomas

**Comment by bacongobbler** [comment]
I think I can reproduce the behaviour you're describing. It happens whenever you switch directions, from scrolling up to scrolling down or vice versa. It takes two scroll wheels to start scrolling.

Would you mind opening this issue at https://github.com/helm/helm-www? Thanks!

**Comment by thochra** [comment]
Sure ! I did not checked that you had a static website generator.

**Comment by thochra** [comment]
done https://github.com/helm/helm-www/issues/81 :wink:
