### ISSUE TITLE
values_files.md indicates null for removing a key

### ISSUE THREAD

**Issue by polettix** [kubernetes/helm#3891]
This is a documentation issue about [values_files.md](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/values_files.md).

Section [Deleting a default key](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/values_files.md#deleting-a-default-key) indicates that you should set a value to `null` to delete a key. There is also an example about it:

    helm install stable/drupal ... --set livenessProbe.httpGet=null

Doing a test, it seems to set the variable to the literal string `"null"`.

When setting it to the *empty string*, I noticed that I could trigger a `default "..."` pipeline function, maybe indicating that an empty string should be used instead of `null` in the description and in the example.

Output of `helm version`:

    Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

**Comment by michelleN** [comment]
hey @polettix! @bacongobbler and I were able to reproduce this issue and we pushed/merged a fix for it in #3912. Thank you. Let us know if you have any other issues.

**Comment by polettix** [comment]
Thanks @michelleN @bacongobbler  for taking care of it! I'll report further issues if I find them, thanks.
