### ISSUE TITLE
Need helm as tiller client in Java/Pyhton/Go

### ISSUE THREAD

**Issue by itnilesh** [kubernetes/helm#3895]
1. I want to do helm chart release using java/pyhton or go code instead of command line . Do we have such feature or ay repo doing it ?

2. If I do say 10000 charts with each of min 10 releases will k8s will sustain? is helm designed for such scale? Where data stored can I scale tiller and its storage ? How much data it store for each release ?

**Comment by koalalorenzo** [comment]
1) If you check in the source code you can reuse the Go modules. :) It works, it is doable but there is not enough documentation.

**Comment by bacongobbler** [comment]
closing as a duplicate of #3031.

**Comment by itnilesh** [comment]
I also need this for Java, as I want to deploy dynamically through code.
