### ISSUE TITLE
auto comletion fail

### ISSUE THREAD

**Issue by fffffreedom** [kubernetes/helm#3924]
Output of `helm version`:

[root@k8s-master ~]# helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:

[root@k8s-master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k8s cluster is installed using kubeadm

error msg:

-bash: _get_comp_words_by_ref: command not found

i have already run the command: source <(helm completion bash)

**Comment by bacongobbler** [comment]
Do you have bash completion installed? Seems similar to another issue reported in rails_completion. https://github.com/jweslley/rails_completion/issues/2.

**Comment by fffffreedom** [comment]
The problem is solved by installing bash-completion, thanks
