### ISSUE TITLE
https://docs.helm.sh   404

### ISSUE THREAD

**Issue by aliasmee** [kubernetes/helm#3925]
Ooops, access web site get 404 response . 
![image](https://user-images.githubusercontent.com/22883562/38982021-535d61f4-43f3-11e8-807c-8eb69728eccf.png)

**Comment by mjhopkins** [comment]
https://docs.helm.sh/using_helm works.

But all the sidebar links (e.g. "intro to charts") are 404s.

**Comment by elektronet** [comment]
I guess this is the reason I am getting `Error: failed to download...` on helm packets

**Comment by Ilyes-Hammadi** [comment]
Everything seems to work correctly on the website.

**Comment by bacongobbler** [comment]
cc @flynnduism, the site seems to be flaking out overnight the past 2 days. Possibly due to the work we've been doing with purging the CDN?

**Comment by flynnduism** [comment]
Yes, sorry folks. I was updating the CDN and there was some downtime in-between.

docs.helm.sh is updated now.
helm.sh is updated, but the SSL cert is still processing at the moment.

**Comment by bacongobbler** [comment]
both are working now. Closing!

**Comment by aliasmee** [comment]
thanks .🍺
