### ISSUE TITLE
Helm.sh website has an infinite loop redirect

### ISSUE THREAD

**Issue by sgmccli** [kubernetes/helm#3930]
Hi,

It looks as though the helm.sh website has an erroneous HTTP 301 redirect to `/www.helm.sh/` rather than `https://www.helm.sh/`. This is causing an infinite redirect and in turn, the page is not loading correctly.

![image](https://user-images.githubusercontent.com/1972162/39052287-69a7a892-44a3-11e8-8895-39df89bc9e04.png)

Simon

**Comment by flynnduism** [comment]
@sgmccli @bacongobbler there were changes earlier to cloudflare, it was looping temporarily. Should be all restored and routing correctly since this was posted 🖖

**Comment by bacongobbler** [comment]
indeed. closing!

**Comment by sgmccli** [comment]
Thanks all @bacongobbler @flynnduism
