### ISSUE TITLE
Ternary sprig function not found

### ISSUE THREAD

**Issue by saplla** [kubernetes/helm#3931]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

`helm template` complains when using the `ternary` [function](http://masterminds.github.io/sprig/defaults.html) from sprig.

**Comment by helgi** [comment]
`ternary` was added in `sprig` 2.15 whereas Helm 2.8.2 is on `sprig` 2.14.1
