### ISSUE TITLE
2.9.0-rc: helm status <release> missing information

### ISSUE THREAD

**Issue by bjornmagnusson** [kubernetes/helm#3937]
Output of helm status has changed between 2.8.2 and 2.9.0-rc.
Service and Deployment is missing details.

2.8.2: helm status ui

```
LAST DEPLOYED: Sat Apr 21 11:14:15 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                     TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)  AGE
ui-kubernetes-dashboard  ClusterIP  10.104.246.33  <none>       443/TCP  1m

==> v1beta1/Deployment
NAME                     DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
ui-kubernetes-dashboard  1        1        1           1          1m

==> v1/Pod(related)
NAME                                      READY  STATUS   RESTARTS  AGE
ui-kubernetes-dashboard-7fb76c98b5-c26n8  1/1    Running  0         1m

==> v1/Secret
NAME                     TYPE    DATA  AGE
ui-kubernetes-dashboard  Opaque  0     1m

==> v1/ServiceAccount
NAME                     SECRETS  AGE
ui-kubernetes-dashboard  1        1m

==> v1beta1/Role
NAME                     AGE
ui-kubernetes-dashboard  1m

==> v1beta1/RoleBinding
NAME                     AGE
ui-kubernetes-dashboard  1m
```

2.9.0-rc:  helm status ui

```
LAST DEPLOYED: Sat Apr 21 11:14:15 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                     AGE
ui-kubernetes-dashboard  3h

==> v1/ServiceAccount
ui-kubernetes-dashboard  3h

==> v1beta1/Role
ui-kubernetes-dashboard  3h

==> v1beta1/RoleBinding
ui-kubernetes-dashboard  3h

==> v1/Service
ui-kubernetes-dashboard  3h

==> v1beta1/Deployment
ui-kubernetes-dashboard  3h

==> v1/Pod(related)
NAME                                      READY  STATUS   RESTARTS  AGE
ui-kubernetes-dashboard-7fb76c98b5-c26n8  1/1    Running  0         3h
```

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.0-rc4", GitCommit:"030d2c066bcf5a37931e0169b7921f3758d97095", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0-rc4", GitCommit:"030d2c066bcf5a37931e0169b7921f3758d97095", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker for Mac 18.03

**Comment by technosophos** [comment]
Hunting down whether this changed in Kubernetes itself
