### ISSUE TITLE
Downloader plugins not used when downloading new repo's index.yaml

### ISSUE THREAD

**Issue by reidab** [kubernetes/helm#3938]
I've been attempting to use the [viglesiasce/helm-gcs](https://github.com/viglesiasce/helm-gcs) plugin to manage a private chart repo on Google Cloud Storage. That plugin implements a [very simple downloader](https://github.com/viglesiasce/helm-gcs/blob/master/bin/gcs-repo.sh) for the `gs://` protocol. From what I can tell, this is implemented correctly per the Helm docs on [downloader plugins](https://docs.helm.sh/using_helm/#downloader-plugins).

When I run: `helm repo add gcs-repo gs://the-dyrt-helm-charts`

It fails with: `Error: Looks like "gs://the-dyrt-helm-charts" is not a valid chart repository or cannot be reached: Get gs://the-dyrt-helm-charts/index.yaml: unsupported protocol scheme "gs"`

It seems like Helm is finding the custom `gs://` downloader, since other invalid protocol schemes fail with a different message: `Error: Could not find protocol handler for foo`

Digging around in the Helm source, I think the error is coming from trying to use an HTTP getter instead of the custom getter when fetching the index here: 
https://github.com/kubernetes/helm/blob/1a55161a53345816d724e1df9664f789113e1328/pkg/repo/chartrepo.go#L122

It looks like this always-HTTP behavior was introduced in #3206 when authentication support was added for remote repos. Before that change, the index download was done using the repo's instantiated client as expected.

---

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.0-rc4", GitCommit:"030d2c066bcf5a37931e0169b7921f3758d97095", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0-rc4", GitCommit:"030d2c066bcf5a37931e0169b7921f3758d97095", GitTreeState:"clean"}
```

* Also tested on v2.9.0-rc3 and v2.8.2.

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.0", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-03-21T19:01:20Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE

---

Mentioning https://github.com/viglesiasce/helm-gcs/issues/3 for a cross-issue link.

**Comment by reidab** [comment]
I also tried this other implementation of a GCS helm plugin (with the same name 😞), and confirmed that it fails in the same ways: https://github.com/nouney/helm-gcs

**Comment by technosophos** [comment]
Yes, you are correct @reidab . This bug was introduced by the #3206 PR. It looks like the fix should be fairly straightforward. @eyalbe4 can you please take a look? It appears that the PR referenced above skips the getter resolution and assumes HTTP(S). /cc @bacongobbler

**Comment by bacongobbler** [comment]
> Also tested on v2.9.0-rc3 and v2.8.2.

If this doesn't work on 2.8.2 then perhaps this was introduced prior to 2.8.2. #3206 is slated for 2.9 but hasn't hit an official release yet, just the RCs. We should definitely take a look at this and triage it though.

**Comment by technosophos** [comment]
For now, checking if it's an HTTP getter and then setting is okay. I'm not really clear on how plugins would implement auth using the method created by this PR.

**Comment by technosophos** [comment]
@reidab I just noticed what @bacongobbler pointed out -- that you said you tested on 2.8.2. Was it exactly the same error on that version? If so, we might have more than one place where this is a problem.

**Comment by eyalbe4** [comment]
@technosophos,
I'll soon submit a PR for setting the credentials only if the getter is an HTTTPGetter.
While working on this PR, @bacongobbler and I debated where the setCredentuals API should be placed.
I'm willing to further help in making more changes to this design, so that it is better suited for plugins.

**Comment by eyalbe4** [comment]
@technosophos,
I submitted the above PR to fix this.
It looks like a lot of code has been changed in this PR, but actually, the new approach allowed me to revert many of the changes done in https://github.com/kubernetes/helm/pull/3206, so when reviewing the code, you can also compare it to one commit before https://github.com/kubernetes/helm/pull/3206.
The main change I made is reverting back the usage of *getter.NewHTTPGetter* to the original getter resolution code. I changed it in all relevant places. 
The rest of the changes are mostly reverting the changes in https://github.com/kubernetes/helm/pull/3206, which are not necessary anymore.
I think that we should be good now.

**Comment by reidab** [comment]
@technosophos It looks like I was mistaken — I thought I'd seen this failing on a `v2.8.2` install, but trying again now it works fine.

**Comment by iorlas** [comment]
Damn guys, I feel like I'm working with node js crappy libraries. I got a plugin for gs, but still have an error you had before:

[debug] Created tunnel using local port: '62874'

[debug] SERVER: "127.0.0.1:62874"

[debug] Original chart version: ""
Error: Get gs://kubernetes-charts/nginx-ingress-0.20.1.tgz: unsupported protocol scheme "gs"

What am I supposed to do?

**Comment by bacongobbler** [comment]
What version of helm are you running? This should be fixed in 2.9.1

**Comment by iorlas** [comment]
@bacongobbler 

$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

$ helm plugin list
NAME	VERSION	DESCRIPTION
gcs 	0.2.0  	Manage repositories on Google Cloud Storage

$ helm install stable/nginx-ingress --debug
[debug] Created tunnel using local port: '64829'

[debug] SERVER: "127.0.0.1:64829"

[debug] Original chart version: ""
Error: Get gs://kubernetes-charts/nginx-ingress-0.20.1.tgz: unsupported protocol scheme "gs"


Had to install all of it manually. Sad thing is, I'm not a fan of Helm since I don't understand Tiller mission, but I've trusted it since I heard all around "just helm install, it is that easy". But it isn't that, easy, I've struck in the start.

**Comment by AndrewMorsillo** [comment]
This is happening to me as well with helm-gcs.

> Initializing helm...
> Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
> Installing helm repository gcs-repo gs://myapp-123123-helm-repo
> Error: Could not find protocol handler for: gs
