### ISSUE TITLE
https://helm.sh/ website has no stylesheet

### ISSUE THREAD

**Issue by j-bennet** [kubernetes/helm#3940]
This is how it looks:

<img width="979" alt="helm-sh" src="https://user-images.githubusercontent.com/637013/39101148-75cfe942-464a-11e8-9c19-4ad7be16cedf.png">

If I add `www.`, everything is fine.

The link to `https://helm.sh/` (without `www.`) is present in Dask documentation: https://dask.pydata.org/en/latest/setup/kubernetes-helm.html.

**Comment by jstoja** [comment]
An additional error message that I have is `The stylesheet https://www.helm.sh/ was not loaded because its MIME type, “text/html”, is not “text/css”.`.

Maybe this issue will be interesting to @flynnduism ?

**Comment by RyanHartje** [comment]
This was brought up in #helm-dev this week and it was suggested it may be a caching issue. 

> zanetworker [9:20 AM]
Hey guys, is it me or is the formatting for the Doc page broken? (edited)
> bacongobbler [9:44 AM]
Ouch, yeah I see that too after a browser refresh. Might be a caching issue. I'll bring it up this morning.
> bacongobbler [11:58 AM]
works now! must've been a flake this morning.

It appears to be resolved at current:
https://docs.helm.sh/using_helm/#quickstart
https://www.helm.sh/

**Comment by flynnduism** [comment]
Rolling back a change to restore the proper appearance.
Opened [#82](https://github.com/helm/helm-www/issues/82) to tackle the Content-Type mismatch on the CDN. 

Thanks for flagging!

**Comment by bacongobbler** [comment]
@flynnduism and I 🍐'd on this and found the issue. It turned out to be a CDN page rule error where https://helm.sh wasn't being redirected to https://www.helm.sh. All is well now. Thank you for reporting! Let us know if there's any other issues with the sites going forward, we're testing out and deploying new changes to the site :)
