### ISSUE TITLE
[Question] How to prevent templates from being rendered ?

### ISSUE THREAD

**Issue by migueleliasweb** [kubernetes/helm#3951]
Hey guys,

I'm developing a helm template and I came up with the need to prevent certain templates to be rendered if a given flag is set. Is it possible to achieve this ? If so, how ?

Ps: The only way I could think of is wrapping the whole template in a if statement. If the if is false, the whole template would be "skipped".

**Comment by bacongobbler** [comment]
Yep! That's how we handled it for individual templates. At a higher level you can also conditionally enable or disable charts through requirements.yaml.

**Comment by migueleliasweb** [comment]
Thanks @bacongobbler !!! Just to clarify: What I have said about templates was *.yaml files inside the `templates` folder and not .tpl files. Does that still applies ?

Btw, a quick example of what I was saying:

```yaml
# templates/foo.yaml
{{- if .Values.enable_template_foo }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  .
  .
  .
  .
{{- end }}
```

**Comment by bacongobbler** [comment]
Yes :)

**Comment by migueleliasweb** [comment]
:tada: :tada: :tada: :tada: 

Thanks !
