### ISSUE TITLE
helm.sh CORS headers

### ISSUE THREAD

**Issue by LeeSaferite** [kubernetes/helm#3954]
The CORS header being served by [helm.sh](https://helm.sh) does not have the correct origin header. Changing to using [www.helm.sh](https://helm.sh) fixes the CORS issue. Either you need a redirect or the CORS headers need to be fixed. None of the custom font files currently load on [helm.sh](https://helm.sh) as a result.

**Comment by flynnduism** [comment]
Thanks @LeeSaferite, I'll sort this out.

**Comment by technosophos** [comment]
Validated this morning that @flynnduism 's fix has passed through the CDN cache

**Comment by flynnduism** [comment]
The change is live but the CORS issue persists, webfonts are not rendering correctly.

**Comment by bacongobbler** [comment]
let's follow up in https://github.com/helm/helm-www/issues/86 so we're all working off one ticket :)
