### ISSUE TITLE
Helm.sh website using large amounts of CPU

### ISSUE THREAD

**Issue by brendanstennett** [kubernetes/helm#3959]
Not related to helm specifically but visiting the website causing my CPU to spike and stay there until closing it.  It's not just the home page either, other pages seem to have the same problem.

**Comment by bacongobbler** [comment]
Hmm, this might be due to the animations running on the site. I'm not quite sure how we can fix that. :/

Would you mind opening a ticket at https://github.com/helm/helm-www and follow up there instead? Thanks!

**Comment by brendanstennett** [comment]
I think it's the boat, hah! Yes I can create a ticket there instead.
