### ISSUE TITLE
Authenticated chart installation should allow password entry on stdin

### ISSUE THREAD

**Issue by HT154** [kubernetes/helm#3960]
Currently, it's not possible provide the password for authenticated chart any way other than on the command line. This is a great way to write a sensitive password to your shell history.

Helm should instead ask for a password from stdin. There are two ways that make sense to trigger this behavior:

* if `--username` is passed but no `--password` is specified, ask
* if `--username` is passed and `--password` is passed, but with no value, ask

**Comment by jstoja** [comment]
You can probably use it like this for now (with bash):
`read -s helm_pass && helm install --username user1 --password $helm_pass`
or with:
`helm install --username user1 --password $(cat .password)`
