### ISSUE TITLE
helm install /w namespace failing...

### ISSUE THREAD

**Issue by ArcticSnowman** [kubernetes/helm#3967]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  In House Kube

When I run
` helm install . --name test-fluentd --namespace test-fluentd --values ./values-test3.yaml`

Getting 
```
Error: release test-fluentd failed: namespaces "test-fluentd" already exists
```

The namespace does not exist prior and there is nothing in the template that is creating the namespace.

**Comment by bacongobbler** [comment]
relevant issue:L #3863

**Comment by ArcticSnowman** [comment]
The issue persisted even without the `--namespace` option..

Removing the tiller deploy manually and reinstalling with `helm init` seem to clear it up..

**Comment by bacongobbler** [comment]
Ah yes, nothing quite works better than "did you try rebooting it again?" ;)

Because there's not much to go on from this ticket, I'm going to close this as resolved, but let's re-open and investigate if we can figure out the root underlying issue. Thanks!
