### ISSUE TITLE
Building dependencies recursively does not work/not smooth on the given project

### ISSUE THREAD

**Issue by gintautassulskus** [kubernetes/helm#3974]
The output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"cfa4560078adb81c7a68fff1b3a7c81c3242655c", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
The client above is PR https://github.com/kubernetes/helm/pull/2278 merged into the current master.
Also checked with PR's helm 2.7.

I tried running `helm dependency build --recursive chart-recursive-deps`
on the following nested chart:
https://github.com/gintautassulskus/chart-recursive-deps

The` chart-recursive-deps` chart structure is as follows:
```
.
└── helm-charts
    ├── subchart_a
    │   ├── helm-charts
    │   │   ├── subchart_a_1
    │   │   └── subchart_a_2
    └── subchart_b
        └── helm-charts
            ├── subchart_b_1
            └── subchart_b_2
```

### First issue
On the first run I get:
```
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
```
I see that only the top level charts are packaged:
```
.
├── charts
│   ├── subchart_a-0.1.0.tgz
│   └── subchart_b-0.1.0.tgz
```
Shouldn't there be archives generated for subcharts `subchart_a_x` and `subchart_b_x`?

### Second issue

On the second run of `helm dependency build --recursive chart-recursive-deps` I get:
```
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Deleting outdated charts
Getting requirements recursively for: chart-recursive-deps/charts/subchart_a
Error: could not find chart-recursive-deps/charts/subchart_a: stat chart-recursive-deps/charts/subchart_a: no such file or directory
```

I expected the operation to be idempotent.

This issue might be related to the fact that I am forced to use directory `helm-charts` for my sub-charts instead of `charts` as stated by https://github.com/kubernetes/helm/issues/2887#issuecomment-327029980.

PS. Also, the `requirements.yaml` is kind of ugly due to https://github.com/kubernetes/helm/issues/3221.

**Comment by bacongobbler** [comment]
cc @libesz

**Comment by bacongobbler** [comment]
#2278 has not yet been merged into master. Because this is using a feature that has not yet been released into the wild we cannot support this. Sorry!
