### ISSUE TITLE
Helm upgrade fails with patch error

### ISSUE THREAD

**Issue by tdcox** [kubernetes/helm#3995]
Output of `helm version`: v2.9.0+gf6025bb

Output of `kubectl version`: v1.9.6

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE v1.9.3-gke.0

Issue:
Helm upgrade fails to upgrade a statefulset with a persistent volume, as follows:
````
helm upgrade "jx-staging" "env" --install --namespace "jx-staging" --debug --force
[debug] Created tunnel using local port: '37772'

[debug] SERVER: "127.0.0.1:37772"

Error: UPGRADE FAILED: failed to create patch: map: map[mountpath:/var/lib/openldap/openldap-data name:data-volume] does not contain declared merge key: mountPath
````

**Comment by bacongobbler** [comment]
Looks like `mountpath` in your StatefulSet should be `mountPath`. Can you verify that it is indeed the camel-cased type in your templates?

**Comment by tdcox** [comment]
You are correct. How odd, I actually checked that and hallucinated seeing the camel-case correctly because the deployment was working in K8S. Thanks!
