### ISSUE TITLE
Issues installing helm and tiller

### ISSUE THREAD

**Issue by ethron123** [kubernetes/helm#3997]
I'm trying to get Helm on our VMs that are already set up to run with K8s. Unfortunately, they are not hooked up to the internet so I am having to pull the Docker images manually, tag them and push them to the repo that the VMs read off of.

The problem is that I am unable to pull the image from gcloud. When running docker pull gcr.io/kubernetes-helm/tiller:canary the output is:

Error response from daemon: Get https://gcr.io/v2/: dial tcp 108.177.127.82:443: getsockopt: connection refused

I've checked my proxies and everything looks good there. I am sure that the image does need to be pulled though, since on the VM, the tiller pod has ImagePullBackOff, and the logs on that say: 

Error from server (BadRequest): container "tiller" in pod "tiller-deploy-8f59bfd8d-k7zkj" is waiting to start: trying and failing to pull image

Even after getting gcloud, I still can't pull. Any help would be greatly appreciated!

**Comment by bacongobbler** [comment]
Can you check the image pull policy on tiller? IIRC it's set to Always which would explain why it's still trying to pull them down even after pulling them into the VMs yourself.

**Comment by ethron123** [comment]
Thanks for the quick response!

It is set to Always. I'll change it once the rest of this is sorted out.

I believe the connection issue is due to proxy issues on my side so I've been able to get around that. There are more issues with the nodes that I'm currently working on now, but they are not Helm/Tiller related.

**Comment by bacongobbler** [comment]
ping @ethron123, any update on this ticket or is this something we can close?

**Comment by ethron123** [comment]
You can go ahead and close it

**Comment by mayankpundir27** [comment]
![Screenshot from 2019-06-11 21-26-59](https://user-images.githubusercontent.com/47808826/59287792-034bf680-8c90-11e9-88ac-152a9b231fb4.png)

**Comment by mayankpundir27** [comment]
how do i resolve this?

**Comment by bacongobbler** [comment]
check and see what image is being used for the tiller deployment.
