### ISSUE TITLE
helm doesn't work with GKE 'out of the box'

### ISSUE THREAD

**Issue by eastlondoner** [kubernetes/helm#4013]
In the helm docs here: https://docs.helm.sh/using_helm/#gke it says

> Google’s GKE hosted Kubernetes platform is known to work with Helm, and requires no additional configuration.

However if I create a new GKE cluster and then try to use helm it doesn't work:
```
gcloud container clusters get-credentials <my details>
helm init
helm repo update
helm install stable/neo4j
# Output: Error: no available release name found
```

I guess I need to do something with RBAC - it would be helpful if this was flagged up in the documentation as being *absolutely necessary* for GKE

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.0", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-04-19T17:08:34Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by bacongobbler** [comment]
Good point. IIRC GKE enabled RBAC after this was documented so a amendment to the documentation would be awesome. :)

**Comment by eastlondoner** [comment]
This fixed it for me:
```
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
```

Stolen from here: https://github.com/kubernetes/helm/issues/3055

**Comment by bacongobbler** [comment]
That's a regression in 2.9.0 and will be fixed in 2.9.1, but it doesn't affect the underlying issue raised in the original comment.

**Comment by eastlondoner** [comment]
If anything I think @atombender is highlighting the issue - if there was clear documentation then we would know what to do...

**Comment by bacongobbler** [comment]
It's good for now. We'll have to take a good long look at the docs for helm 3 but that shouldn't stop us from documenting the right things for Helm 2 users. Thanks!

**Comment by rhedgomez** [comment]
Hello, I believe I am also experiencing this.
my CI server is on a different server specifically Travis CI. I did install helm in .travis.yml and also kubecltl, using :gcloud components update kubectl.. With kubectl apply -f, i can make changes to my GKE cluster. However, when I use helm upgrade --install the deployment stage is failing: Error: "project-complex" has no deployed releases Error: UPGRADE FAILED: "project-complex" has no deployed releases

I believe, that my helm which is installed in Travis CI, can't connect to my k8s in Google

**Comment by ryanhartje** [comment]
It seems like helm is indeed installed, but not the "project-complex" release. If its not yet running, try purging the release, or investigating if and why if may be in a failed state.

At a glance, this seems unrelated to RBAC and this issue.
