### ISSUE TITLE
How to uninstall Helm on client?

### ISSUE THREAD

**Issue by donbecker** [kubernetes/helm#4016]
Working with Helm 2.9.0, and I'd like to uninstall from my client and install 2.8.2 to ensure that an issue I'm having isn't related to the specific Helm version.

**Comment by technosophos** [comment]
You can safely delete the binary manually. (If you installed with homebrew, you can use homebrew to remove it.)

To delete Helm local data and Tiller remotely, but leave all of your releases intact, you can do `helm reset`. I recommend reading the help text on that first, though.

If you want to destroy all of the local data, too, do `helm home` to find out where that data is stored, then remove that directory.

**Comment by bacongobbler** [comment]
I'm going to close this question as resolved, but please re-open if you need more assistance. Thanks!

**Comment by chugunovyar** [comment]
uname -r
4.15.0-72-generic


helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

No chance to uninstall\remove from computer helm3. Help me some one.

**Comment by bacongobbler** [comment]
When first starting out, how did you install helm on your computer?

**Comment by Sarthak2116** [comment]
> Help

Did you find a solution, I need it too.

**Comment by bacongobbler** [comment]
How did you install helm?

**Comment by technosophos** [comment]
On a UNIX-like system:

```
$ which helm
/some/path/to/helm
$ rm /some/path/to/helm
```

This is the same as removing any binary on a UNIX-like platform.

If you want platform-specific instructions, you'll need to provide info on how you installed Helm. For example, Nuget, Homebrew, Apt, and RPM all have their own ways of uninstalling things. Most of the time, you can consult the documentation for that tool and it will tell you how to remove packages.

**Comment by Sarthak2116** [comment]
Thanks!

Regards,

*Sarthak Srivastava*
*Student Placement Representative*
*General Manager-All Operations*
*OPEN COMMUNITY*

*UPES Dehradun(B.Tech CSE Open Source and Open Standards)+91- 7310251657*
Attachments area

**Comment by rajendar38** [comment]
> This is the same as removing any binary on a UNIX-like platform.
I have installed using script 
 curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
$ chmod 700 get_helm.sh
$ ./get_helm.sh
how can I uninstall Now ..
I want to downgrade helm version

**Comment by bacongobbler** [comment]
get_helm.sh installs helm into /usr/local/bin, so `rm /usr/local/bin/helm` should work.

**Comment by bha-git-123** [comment]
rm -rf /usr/local/bin/helm

**Comment by raviseerapu** [comment]
If you install using it snap, it's simple by snap remove helm

**Comment by deekonda** [comment]
Installed `brew install kubernetes-helm` on Mac

The version I see is 

------------------------------------------------------------------------------------------------------------------------

version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}"

------------------------------------------------------------------------------------------------------------------------

How can I uninstall current version and install older version **v2.11.0** ?

**Comment by HoseinGhanbari** [comment]
this is also a solution on centos 7
```
which helm | xargs -I % sh -c 'rm -rf %'
```
