### ISSUE TITLE
Hide "unauthenticated users" warning when 'helm init' is called securely

### ISSUE THREAD

**Issue by flimzy** [kubernetes/helm#4047]
After a successful run of `helm init`, the following message is displayed:

    Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
    For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation

I took this to mean that my specific installation was insecure, even after following the specified instructions.  But after reading the source, I see this message is displayed unconditionally, even if the proper security configuration is provided.  I would suggest hiding this message when the proper/secure configuration is provided.

It might also be worth clarifying the message, as it's not entirely clear to me exactly what section of the linked doc it is referring to.

For reference, my actual `helm init` command which generated the output:

    helm init \
        --tiller-tls \
        --tiller-tls-cert ${tmp}/tiller.cert.pem \
        --tiller-tls-key ${tmp}/tiller.key.pem \
        --tls-ca-cert ${HELMHOME}/ca.pem \
        --tiller-tls-verify \
        --service-account=tiller

I suggest hiding this message when `--tiller-tls-verify` is enabled (assuming my

Output of `helm version`:

    Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

**Comment by bacongobbler** [comment]
This seems like an easy issue to tackle should someone want to get their feet wet with Helm. :)

**Comment by flimzy** [comment]
I'll take a crack at it if someone can confirm which condition(s) should disable the warning. Is the `--tiler-tls-verify` the key?  That along with `--service-account`?

**Comment by bacongobbler** [comment]
Yes, I'd say that with the TLS flags enabled that should be more than enough to suppress the warning, since then only users with the TLS client cert can authorize tiller to install resources.
