### ISSUE TITLE
Concurrency issues when namespace doesn't exist

### ISSUE THREAD

**Issue by Stono** [kubernetes/helm#4086]
Please see https://github.com/roboll/helmfile/issues/149 for more information, but at a very high level it'd be great if when `helm install --namespace` results in a namespace being created, if that namespace gets created before helm attempts to execute the command, and results in a `namespace already exists`, helm shouldn't really fail.

This is replicated via concurrency of running two `helm install --namespace <thing>` at the same time, for the same namespace, that doesn't already exist.

**Comment by mattjmcnaughton** [comment]
@Stono thanks for reporting this! Happy to take a stab at fixing - will release a pr soon :)
