### ISSUE TITLE
Helm release naming can be a bit rude

### ISSUE THREAD

**Issue by Cryptophobia** [kubernetes/helm#4089]
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

```
[14:09 cryptophobia ~]$ helm install deis/workflow --namespace deis --set router.host_port.enabled=true
NAME:   ugly-monkey
NAMESPACE: deis
STATUS: DEPLOYED
```

ugly-monkey? The release is NOT an ugly monkey. This isn't the first time helm has disrespected. We don't have to take that from helm!

**Comment by RyanHartje** [comment]
While funny, this project doesn't have a short to do list. Are you jesting, or requesting that the community focus on obstructing certain randomized name combinations? If you are kidding, it would probably be appreciated if you closed this issue.

**Comment by Cryptophobia** [comment]
![infinite_monkey_typewriter](http://jeffa.tech/content/images/2014/05/ChimpAtTypewriter-2006679863.jpg)

Nothing in this life is truly random. With [infinite monkey theorem](https://en.wikipedia.org/wiki/Infinite_monkey_theorem) we will create a greater release tool then helm or maybe we will create tools that will come up with names for software releases that represent what the software actually does instead of putting random words together like monkeys. But until that day comes, we need to fix this. Let's fix this dictionary of "random" names and stop calling other people's releases "ugly". If we don't stop this now, then we are just becoming monkeys, aren't we?

I hope that some day we can laugh about this. But today is not the day and Github is definitely not the place. As I said, this isn't the first time helm has randomly picked disrespectful name. If you think this is acceptable to call other people's software ugly, then go ahead and close this issue.

**Comment by bacongobbler** [comment]
This is not the place for trolling, @Cryptophobia. Please conduct yourself in a professional manner as per the Kubernetes' Code of Conduct. You have been warned. :)

https://github.com/cncf/foundation/blob/master/code-of-conduct.md

The random name generator comes from [moniker](https://github.com/technosophos/moniker) so if someone wants to fire a quick PR upstream that'd be a good place to start.

**Comment by Cryptophobia** [comment]
I have submitted the PR to remove "smelly" and "ugly". Thanks. https://github.com/technosophos/moniker/pull/10

**Comment by Cryptophobia** [comment]
Docker is being creative and educational when naming:

https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go#L106

This is a good model to follow. Just wanted to throw this example out there.
