### ISSUE TITLE
Document using gotpl

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#4102]
In the Kubernetes Application Survey 2018 numerous people noted that gotpl + sprig isn't well known or documented anywhere. IMHO, the gotpl isn't well documented. For Go developers this is sorta ok because they know how to navigate Go. For those coming from other languages and are just using Helm this is a practical problem.

We should document using the templating system so that users who don't know Go can have a good experience.

**Comment by bacongobbler** [comment]
@omkensey already noted this in #4077 so I'm going to close this as a duplicate issue of #4077 so we can all work off one ticket. Thanks @mattfarina!
