### ISSUE TITLE
invalid version/constraint format: improper constraint

### ISSUE THREAD

**Issue by jasoncarreira** [kubernetes/helm#4109]
I'm having  a problem with what should be a simple task. I have a Helm chart with no templates and this for requirements.yaml:

dependencies:
- name: keycloak
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
  version: "0.4.0"

Running my script gives this:

```[preview] Running shell script

+ make preview

helm init --client-only

Creating /home/jenkins/.helm 

Creating /home/jenkins/.helm/repository 

Creating /home/jenkins/.helm/repository/cache 

Creating /home/jenkins/.helm/repository/local 

Creating /home/jenkins/.helm/plugins 

Creating /home/jenkins/.helm/starters 

Creating /home/jenkins/.helm/cache/archive 

Creating /home/jenkins/.helm/repository/repositories.yaml 

Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 

Adding local repo with URL: http://127.0.0.1:8879/charts 

$HELM_HOME has been configured at /home/jenkins/.helm.

Not installing Tiller due to 'client-only' flag having been set

Happy Helming!

helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator

"incubator" has been added to your repositories

helm repo add chartmuseum http://jenkins-x-chartmuseum:8080

"chartmuseum" has been added to your repositories

helm repo add chartmuseum https://chartmuseum.build.cd.jenkins-x.io

"chartmuseum" has been added to your repositories

sed -i -e "s/version:.*/version: /" Chart.yaml

sed -i -e "s/version:.*/version: /" ../*/Chart.yaml

sed -i -e "s/repository: .*/repository: 100.67.27.94:5000\/ppi-engineering\/keycloak-service/" values.yaml

sed -i -e "s/tag: .*/tag: /" values.yaml

echo "  version: " >> requirements.yaml

helm dependency build

Hang tight while we grab the latest from your chart repositories...

...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):

	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused

...Successfully got an update from the "incubator" chart repository

...Successfully got an update from the "stable" chart repository

...Successfully got an update from the "chartmuseum" chart repository

Update Complete. ⎈Happy Helming!⎈

Error: dependency "keycloak" has an invalid version/constraint format: improper constraint: 

make: *** [preview] Error 1

script returned exit code 2
```

I've tried this with the name incubator/keycloak as well and with the version quoted, not quoted, and absent.

Output of `helm version`:

Jason-PPI:dial-service jason$ helm version
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

Output of `kubectl version`:

Jason-PPI:dial-service jason$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Kops on AWS

**Comment by michelleN** [comment]
hey @jasoncarreira - that issue has to do with the version constraint specified in the Chart.yaml file of your chart. It will return that error if the version is not parseable. What does the version in the chart look like?

For more info: https://github.com/Masterminds/semver

**Comment by jasoncarreira** [comment]
It's `0.1.0-SNAPSHOT`

I guess `-SNAPSHOT` is not a valid semver?

**Comment by bacongobbler** [comment]
It's valid semver, but the hypen notes that it's a pre-release as per [section 9 under semver law](https://semver.org/#spec-item-9).

After running that command, would you mind posting the output of requirements.yaml and Chart.yaml? I noticed in the output that there's a `echo "  version: " >> requirements.yaml` under the `make preview` target. Just wanna check if something odd is being injected into requirements.yaml or Chart.yaml prior to running `helm dep build`. Thanks!

**Comment by jasoncarreira** [comment]
I've been playing with it and it's a little different now, but I'm getting the same error. Here's Chart.yaml:
```apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: preview
version: develop-24``` 
and here's requirements.yaml:
```dependencies:
- name: keycloak
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
  version: 0.4.0```

and here's the output

```+ make preview
helm init --client-only
Creating /home/jenkins/.helm 
Creating /home/jenkins/.helm/repository 
Creating /home/jenkins/.helm/repository/cache 
Creating /home/jenkins/.helm/repository/local 
Creating /home/jenkins/.helm/plugins 
Creating /home/jenkins/.helm/starters 
Creating /home/jenkins/.helm/cache/archive 
Creating /home/jenkins/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /home/jenkins/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
"incubator" has been added to your repositories
helm repo add chartmuseum http://jenkins-x-chartmuseum:8080
"chartmuseum" has been added to your repositories
helm repo add chartmuseum https://chartmuseum.build.cd.jenkins-x.io
"chartmuseum" has been added to your repositories
sed -i -e "s/version:.*/version: develop-24/" Chart.yaml
sed -i -e "s/repository: .*/repository: 100.67.27.94:5000\/ppi-engineering\/keycloak-service/" values.yaml
sed -i -e "s/tag: .*/tag: develop-24/" values.yaml
helm dependency build
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "chartmuseum" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading keycloak from repo http://storage.googleapis.com/kubernetes-charts-incubator
Deleting outdated charts
helm lint
==> Linting .
[ERROR] Chart.yaml: version 'develop-24' is not a valid SemVer
[WARNING] templates/: directory not found

Error: 1 chart(s) linted, 1 chart(s) failed
make: *** [preview] Error 1```

**Comment by jasoncarreira** [comment]
Looks like it's working for me now. Changed it so the Chart.yaml version is like this: 1.1.0-SNAPSHOT-39

**Comment by bacongobbler** [comment]
cool yeah develop-24 is definitely not valid semver so that error message seems right to me. Is there a particular action item we can extract from this ticket or does this seem good to close?

**Comment by jasoncarreira** [comment]
Should be good to close. I think the script I was using was messing up copying the version
