### ISSUE TITLE
Could i add a tag in deployment to separate which deployments would be installed to "dev" stack, which would be installed to"qa" stack.

### ISSUE THREAD

**Issue by anemptyair** [kubernetes/helm#4110]
Output of `helm version`:2.8.1

Output of `kubectl version`:1.9.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Using unique charts template , how to separate deployments from different stack, could i add a tag in deployment to separate which deployments would be installed to "dev" stack, which would be installed to"qa" stack ?

**Comment by jgleonard** [comment]
You may want to add a var into `values.yaml` and then wrap the differences in a conditional against that var...
```
{{ if eq .Values.environment "dev" }}
...
{{ else  if eq .Values.environment "qa" }}
...
{{ else if eq .Values.environment "staging" }}
...
{{ else if eq .Values.environment "prod" }}
...
{{ else }}
...
{{ end }}
```

https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/control_structures.md

**Comment by michelleN** [comment]
+1 to @jgleonard's answer. In addition to the docs that @jgleonard provided, here is an example: https://github.com/kubernetes/charts/blob/bfd531cfa1ad85de2d29c8953201ad7000000d78/stable/owncloud/templates/apache-pvc.yaml

**Comment by michelleN** [comment]
Let us know if that answers your question @anemptyair

**Comment by anemptyair** [comment]
@michelleN it's helpful,thanks.
