### ISSUE TITLE
create alpha/beta helm 3 binary downloads?

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#4112]
We'd love to move to the 3.x helm ASAP on Jenkins X. 

I wonder if its time to add a set of helm 3 release binaries so folks can try it out? Its fine to be in alpha/beta a while but still have binaries?

**Comment by jstrachan** [comment]
wonder if until helm is GA we call the binary `helm3` for now - so folks can try out helm 3.x while keeping `helm` around for their 2.x uses?

**Comment by bacongobbler** [comment]
I just ran `make` and `make build-cross` from the tip of the dev-v3 branch and it seemed to work, so I don't see why we couldn't start tossing them in CI to make it easier to test out the latest changes.

**Comment by bacongobbler** [comment]
Done. Canary releases of helm3 can be found at

- [macOS amd64](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-darwin-amd64.tar.gz) ([checksum](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-darwin-amd64.tar.gz.sha256))
- [Linux amd64](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-amd64.tar.gz) ([checksum](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-amd64.tar.gz.sha256))
- [Linux arm](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-arm.tar.gz) ([checksum](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-arm.tar.gz.sha256))
- [Linux arm64](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-arm64.tar.gz) ([checksum](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-arm64.tar.gz.sha256))
- [Linux i386](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-386.tar.gz) ([checksum](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-386.tar.gz.sha256))
- [Linux ppc64le](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-ppc64le.tar.gz) ([checksum](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-linux-ppc64le.tar.gz.sha256))
- [Windows amd64](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-windows-amd64.zip) ([checksum](https://storage.googleapis.com/kubernetes-helm/helm-dev-v3-windows-amd64.zip.sha256))

Thanks!

**Comment by jstrachan** [comment]
yay thanks!!!
