### ISSUE TITLE
any helm template to scale up storage container for "/" mount point

### ISSUE THREAD

**Issue by alnhk** [kubernetes/helm#4113]
Output of `Helm version`:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

`Issue` :
1. With our own data center , prepared and setup the clustered kubernetes (1 master+3 slave cluster kubernetes)
2. used helm to install mysql  (helm install stable/mysql)
3. after spinning up the mysql using helm install,  the container for mysql is up and running with 25GB as storage allocation to container which is default
  
`Question` : Is there any helm template in order to adjust default 25GB to 50GB  as storage container. Yes, we have PV option to store the mysql Data. However, i want to set default 25GB to 50GB for "/" root directory.

Yes, without helm and kubernetes, we can include "--storage size=120GB" to docker run command and thus sets 120GB to "/" mount point. However for helm/kubernetes, i need information. 

Please share info.

Thanks
HK

**Comment by bacongobbler** [comment]
Hey, I think this is best suited as a ticket over at kubernetes/charts as an enhancement request to the MySQL chart. Thus doesn't appear to be a  issue with helm but with the chart itself. Would you mind opening a ticket there? Thanks :)

**Comment by bacongobbler** [comment]
Closing as https://github.com/kubernetes/charts/issues/5730 has been opened
