### ISSUE TITLE
helm documentation not well rendered in non mobile context via browesr

### ISSUE THREAD

**Issue by frederic-loui** [kubernetes/helm#4168]
/kind bug

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Tested: Chrome Firefox on MACOS 10.12.6, working on mobile. (mobile is strangely rendered also) 
[INSTALLATION FAQ bug on desktop browsers](https://docs.helm.sh/using_helm/#installation-frequently-asked-questions)

**Comment by bacongobbler** [comment]
I believe this has been fixed via helm/helm-www#99. Can you confirm? If not would you mind opening a new ticket there? THanks!

**Comment by bacongobbler** [comment]
Closing as I believe this has been fixed and to follow-up in helm-www if not.
