### ISSUE TITLE
Helm Documentation is a mess

### ISSUE THREAD

**Issue by FrenchBen** [kubernetes/helm#4184]
Why is the documentation such a mess?
https://docs.helm.sh/using_helm/#installing-helm

* Layout is wrong (extra content at the bottom)
* None of the named anchor links work
* Empty titles (etc.)

Is this a deployment gone bad?

**Comment by jaygorrell** [comment]
Came to post just this. I'm almost certain it was fine within the past couple weeks. 

I also can't even scroll to the left here -- there is content that just isn't accessible at all.
![screenshot 2018-06-06 21 31 20](https://user-images.githubusercontent.com/12174604/41073377-fbe55432-69d0-11e8-8dd0-68cb8b27634d.png)

**Comment by bacongobbler** [comment]
There's something up at the CDN caching layer. From my end I see the site perfectly fine.

Let's follow up in https://github.com/helm/helm-www/issues/99
