### ISSUE TITLE
helm install Error: Looks like install/kubernetes/helm/istio is not a valid chart repository

### ISSUE THREAD

**Issue by nippip** [kubernetes/helm#4214]
I am unable to pull charts from the latest istio chart repo.  I tried to add the repo but that also failed per results below stating that **index.yaml Not Found** 
Any workaround would be appreciated.  

==> helm install istio/install/kubernetes/helm/istio --name istio --namespace istio-system
Error: failed to download "istio/install/kubernetes/helm/istio" (hint: running `helm repo update` may help)

==> helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

==> helm repo list
NAME     	URL
stable   	https://kubernetes-charts.storage.googleapis.com
local    	http://127.0.0.1:8879/charts
incubator	http://storage.googleapis.com/kubernetes-charts-incubator

**==> helm repo add** istio https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio
Error: Looks like "https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio" is not a valid chart repository or cannot be reached: Failed to fetch https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio/index.yaml : 404 Not Found

**==> helm install --repo** https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio istio
Error: Looks like "https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio" is not a valid chart repository or cannot be reached: Failed to fetch 
https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio/index.yaml : 404 Not Found

Output of `helm version`:
==> helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
==> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-06-06T00:44:24Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.3", GitCommit:"d2c7a2bd41036f9474287579a725dc54c904e92d", GitTreeState:"clean", BuildDate:"2018-05-23T00:19:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform: GKE

**Comment by bacongobbler** [comment]
it doesn't look like it's configured to be added as a repository. Are you following the instructions laid out in https://preliminary.istio.io/docs/setup/kubernetes/helm-install.html?

**Comment by nippip** [comment]
Thanks BaconGobbler.  Solved by installing istio locally.
