### ISSUE TITLE
Helm doesn't work unless run under sudo

### ISSUE THREAD

**Issue by jicowan** [kubernetes/helm#4216]
When I execute `helm init --client-only` on OSX it says: 

```
$HELM_HOME has been configured at :/Users/jicowan/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
```

But it does not create the .helm directory or any of the directories underneath.  The only way I was able to get this to work is by running helm init under sudo.

Similarly, when I run `helm repo update` I get the following error: 

```
Error: Couldn't load repositories file (:/Users/jicowan/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```
However when I run it under sudo I get this: 
```
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

Any ideas what could be wrong.  I have tried re-installing helm multiple times with the same results each time. 

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by bacongobbler** [comment]
Any idea how there's a colon any time your home directory is mentioned? :)

e.g.

```
:/Users/jicowan/.helm
```

Can you run `echo $HOME` and check the output?

**Comment by jicowan** [comment]
Had an wayward : in my .zshrc file.
