### ISSUE TITLE
helm3 regression in `helm dependency build`

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#4230]
In Jenkins X we've been putting things in place so users can use a feature flag to use helm 2.x or 3.x. We've got things working fine for doing releases with helm3; but it seems composite charts with dependencies have issues.

I seem to have found a regression where for the exact same project, using the helm 2.x binary I get:
```
$ helm dependency build
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "releases" chart repository
...Successfully got an update from the "jenkins-x" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading exposecontroller from repo https://chartmuseum.build.cd.jenkins-x.io
Downloading exposecontroller from repo https://chartmuseum.build.cd.jenkins-x.io
Downloading demo93 from repo http://jenkins-x-chartmuseum:8080
Deleting outdated charts
```
but if I try the same folder + chart immediately after with helm3 I get:
```
$ helm3 dependency build
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "releases" chart repository
...Successfully got an update from the "jenkins-x" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading exposecontroller from repo https://chartmuseum.build.cd.jenkins-x.io
Save error occurred:  could not download https://chartmuseum.build.cd.jenkins-x.io/charts/exposecontroller-2.3.58.tgz: could not find a repo containing the given URL
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://chartmuseum.build.cd.jenkins-x.io/charts/exposecontroller-2.3.58.tgz: could not find a repo containing the given URL
```
The chart was created with helm2 and it is downloadable at that URL (its the same URL in both cases) so am guessing there's some other error that happens in helm3 that causes the error?

If it helps here's the `requirements.yaml` file for this test: https://github.com/jstrachan/environment-jstrachan-test1-staging/blob/master/env/requirements.yaml

**Comment by bacongobbler** [comment]
@jstrachan I'm going to close this because we decided last dev call that we are not going to be tracking issues for Helm 3 at this point since it's still very much in-flux and things are expected to change.

If you have any further discussion points/issues/questions regarding Helm 3, if you wouldn't mind discussing in #helm-dev in Slack that would be most appreciated. Thanks!

**Comment by PsyonixBarrett** [comment]
This still seems to be an issue with this in Helm 3 Alpha using ChartMuseum. Any chance to have this opened again?
