### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by danielcb** [kubernetes/helm#4247]
Hi,
can anyone tell me when the next releases is due? We're waiting for a release containing the fix in #3984.

**Comment by bacongobbler** [comment]
Hey @danielcb!

Kubernetes 1.11 rc1 was just released so we should at least bring in support for 1.11 - which means Helm 2.10 should hold out for a few more weeks - but I agree. It's been a while. I'd just hate for us to release 2.10 then get everyone on board with a Helm 2.11 release only a week later.

Thanks for your interest!

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/kubernetes/milestone/38

**Comment by bacongobbler** [comment]
update from the dev call: from initial testing, a lot of k8s 1.11 client APIs have broken/shifted around so it'll take some time to add k8s 1.11 support at this point. We're discussing about cutting a 2.10-rc1 in #helm-dev without k8s 1.11 support.
