### ISSUE TITLE
Is there a way to manipulate(update) requirement.yaml file from command line

### ISSUE THREAD

**Issue by plokimju** [kubernetes/helm#4249]

**Comment by bacongobbler** [comment]
There's nothing out there for updating requirements.yaml through the CLI. Would you mind explaining a little bit about your use case, perhaps?

**Comment by bacongobbler** [comment]
requirements.yaml accepts semantic version ranges. For example:

```
dependencies:
  - name: postgresql
    version: ~0.7
```

The next time you run `helm dependency update`, it will update your dependencies based on the semver range you specified in your requirements.yaml. Is that what you're looking for?

There's no way to programmatically "update" the requirements file through the CLI.

**Comment by plokimju** [comment]
@bacongobbler -Thank you
