### ISSUE TITLE
helm list gives unknown flag error when using --output flag

### ISSUE THREAD

**Issue by TalkingQuickly** [kubernetes/helm#4253]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Customer Cluster (On Hetzner Cloud)

**Issue**

The documentation at: <ttps://docs.helm.sh/helm/#helm-list> suggest that `helm list` supports the `--output` flag for outputting data in json.

But the following command:

```
helm list --output json
```

Gives:

```
Error: unknown flag: --output
```

**Comment by bacongobbler** [comment]
Hey @TalkingQuickly! The documentation you see at https://docs.helm.sh is generated from master. Generally this isn't an issue, but occasionally new features pop up in master which aren't available in the latest release, such as `--output`. :)

This flag does indeed exist, but right now it only exists in the canary release. If you feel lik testing it out, feel free to follow along in https://docs.helm.sh/using_helm/#from-canary-builds to grab a canary release and give it a shot.

Thanks so much for the feedback!

**Comment by cforce** [comment]
it see this also for helm 2.14.3
