### ISSUE TITLE
Helm should recreate resources for subcharts when values are changed and they produce different templates

### ISSUE THREAD

**Issue by saplla** [kubernetes/helm#4258]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

When I installed a chart with dependencies, if I change my values file so that the subchart's templates change, helm isn't recreating pods, etc.

To reproduce this:
1. Create a new chart
2. Configure `chart museum` as a dependency
3. Update dependencies
4. Install the chart using default values
5. Create a new values.yaml file containing:
```
deployment:
  annotations:
    iam.amazonaws.com/role: "fake-role"
```
6. Redeploy passing `-f values.yaml`

Helm should have detected that it needs to redeploy the chart museum pod, but it doesn't. Even using the `--force` flag on `helm upgrade` doesn't cause it to recreate the pod. Running `helm template` after extracting the chart museum tarball shows that the above annotation is present in the generated template, but for some reason helm doesn't detect this and doesn't recreate the pod.

If I manually extract the tarball and copy out the templates and values.yaml file (renaming the values.yaml created above) and then upgrade the chart, helm correctly replaces the pod.

**Comment by jascott1** [comment]
Hi @saplla Have you tried `--re-create pods`?

**Comment by saplla** [comment]
@jascott1 thanks for the hint. The problem was in fact that I had forgotten to namespace my values, i.e. so instead of using:
```
deployment:
  annotations:
    iam.amazonaws.com/role: "fake-role"
```
I should have used:
```
chartmuseum:
  deployment:
    annotations:
      iam.amazonaws.com/role: "fake-role"
```
