### ISSUE TITLE
Can I use some external file (outside of helm zip package) to include during helm install command ?

### ISSUE THREAD

**Issue by tutaidalal** [kubernetes/helm#4267]
Can I use some external file (outside of helm zip package) to include during helm install command ?

I have created a application using {{ (tpl (.Files.Glob "configs/*").AsConfig . ) | indent 2 }}. But end user dont want to unzip and use the helm. What is the procedure to include some external files for config mao

**Comment by jascott1** [comment]
Hi @tutaidalal 

External access is not supported. Im going to close this in favor of the related issue #4265 you filed. Please use that for follow up. Thanks.
