### ISSUE TITLE
Helm fails to see changes to resources even though the templates have changed

### ISSUE THREAD

**Issue by antonosmond** [kubernetes/helm#4272]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.3", GitCommit:"d2c7a2bd41036f9474287579a725dc54c904e92d", GitTreeState:"clean", BuildDate:"2018-05-23T00:19:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `GKE`

I installed a chart with helm (which inc. a deployment & service) and it was deployed successfully. Then I updated the selector in the service resource manually using `kubectl edit`. I didn't change any of the helm/tiller values in the resource.

I then ran a helm upgrade of the release using the original chart. My expectation was that the selector I'd changed manually in the service would be set back to the value as it is defined in the helm template however this didn't happen.

Looking at the logs in tiller, it doesn't think the service resource has changed:
```
[kube] 2018/06/26 16:06:20 building resources from updated manifest
[kube] 2018/06/26 16:06:20 checking 3 resources for changes
[kube] 2018/06/26 16:06:20 Looks like there are no changes for Secret "medications"
[kube] 2018/06/26 16:06:20 Looks like there are no changes for Service "medications"
[kube] 2018/06/26 16:06:20 Created a new Deployment called "medications-6.0.0"
```
If I do a `--dry-run` of the chart with `--debug` and check the service.yaml, the values are as I'd expect and they're different from the current service in kubernetes so I'd expect helm to see the service as having changes.

Is this a bug or is my understanding of how helm would deal with this scenario incorrect?

**Comment by voxxit** [comment]
@antonosmond Why was this closed? I think this is actually a real issue.

**Comment by antonosmond** [comment]
@voxxit I thought it was my understanding of how helm works that was incorrect. 
My expectation was that helm would generate the new version of a resource from a given template and compare that with the "current" version of the resource from Kubernetes. Where I say "current" version I mean the actual resource e.g. a deployment or service and not some config map or something that helm generated when a chart was installed. I tried to find out what helm was comparing and tracked it down to [here](https://github.com/kubernetes/helm/blob/v2.9.1/pkg/kube/client.go#L434-L440) but then couldn't work out where `currentObj runtime.Object` actually came from.

**Comment by antonosmond** [comment]
To add some context, I'd made a change to a resource using `kubectl edit` to update a selector on a service as a temporary fix to a problem we were having. Once it was resolved, I wanted the selector to be put back to the value as it was declared in the chart. My expectation was that a `helm upgrade --install` of the chart would update the selector in the service bringing it back in line with the chart and that's what didn't happen.
