### ISSUE TITLE
Cannot see full error on prior revision

### ISSUE THREAD

**Issue by rcorre** [kubernetes/helm#4281]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

I know I'm on an old version, so feel free to close this if it is resolved. However, I didn't see any related issues, so I'm guessing this hasn't been mentioned yet.

I have a release that failed, but a subsequent upgrade succeeded. `history` truncates the error message and neither `status` nor `get` seem to include it:

```
[rodencor@karminac tenant]$ helm --tiller-namespace ipaas history       tenant-upgrade-test-1530219075
REVISION        UPDATED                         STATUS          CHART           DESCRIPTION
1               Thu Jun 28 16:51:27 2018        SUPERSEDED      tenant-1.7.2    Install complete
2               Thu Jun 28 16:54:19 2018        SUPERSEDED      tenant-1.8.6    Upgrade "tenant-upgrade-test-1530219075" failed: Deployme...
3               Thu Jun 28 16:54:25 2018        DEPLOYED        tenant-1.8.6    Upgrade complete
[rodencor@karminac tenant]$ helm --tiller-namespace ipaas status tenant-upgrade-test-1530219075 | grep failed
[rodencor@karminac tenant]$ helm --tiller-namespace ipaas get tenant-upgrade-test-1530219075 | grep failed
```

Note that the `history` line literally ends with `...`. If it is going to be truncated, could it at least be incuded in full in the `status` output?

In most cases you'd ideally see the error response the first time, but I can think of a few scenarios where that isn't viable:

1. Debugging after an automated test fails
2. Figuring out why a release failed after a long-runnning helm connection was killed but the operation proceeded (#3015)
3. In a devops role, where a team is asking you to help debug their failed deployment and you need to go back and look at the history.

**Comment by bacongobbler** [comment]
this was fixed in https://github.com/kubernetes/helm/pull/2836 IIRC. Can you try with a newer version of helm and confirm?

**Comment by rcorre** [comment]
Don't have ready access to a newer server, but we're updating soon. #2836 sounds like the fix, I'll reopen if not.
