### ISSUE TITLE
GKE regional cluster supported?

### ISSUE THREAD

**Issue by vshimoda** [kubernetes/helm#4286]
after helm init --service-account tiller, i got error message bellow.
```
$ helm ls
Error: forwarding ports: error upgrading connection: error dialing backend: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-xxxxxxxxxxxxxxxxx"
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Error: cannot connect to Tiller
```
i coudn't get Server version, but i can get server version via kubectl

```
 $ kubectl describe pod -l name=tiller -n kube-system
Name:           tiller-deploy-5c688d5f9b-5hb6v
Namespace:      kube-system
Node:           gke-myproject-default-pool-0a4c46b4-7st3/10.146.0.3
Start Time:     Fri, 29 Jun 2018 09:42:08 +0900
Labels:         app=helm
                name=tiller
                pod-template-hash=1724481956
Annotations:    <none>
Status:         Running
IP:             10.48.18.2
Controlled By:  ReplicaSet/tiller-deploy-5c688d5f9b
Containers:
  tiller:
    Container ID:   docker://ffa1377a06c8e53b8ae8fd6dff9ae41443992846bc16253c03d6cdd880e57c4c
    Image:          gcr.io/kubernetes-helm/tiller:v2.9.1
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:417aae19a0709075df9cc87e2fcac599b39d8f73ac95e668d9627fec9d341af2
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 29 Jun 2018 16:04:10 +0900
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-ghh7l (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  tiller-token-ghh7l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-ghh7l
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE (regional cluster)

**Comment by bacongobbler** [comment]
Under the covers, helm is initiating a short-lived `kubectl port-forward` to tiller, so if that does not work for GKE regional clusters, then you'll need to find some other way to communicate with tiller via `$HELM_HOST` or `helm --host`. I'd investigate how you can allow port-forwarded connections to pods running in the cluster as pretty much every other configuration of Kubernetes allows this, so there might be something going on with the internal networking within the GKE cluster.

Sorry that you're running into this!

**Comment by vshimoda** [comment]
sorry, i found the network trouble in my vpc, and I confirmed that it works if it is normal environment.

**Comment by 27Bslash6** [comment]
Question to @vshimoda - do you have any data on what was misconfigured in your VPC?
We've just encountered this error, randomly, with a NAT VPC created via the Terraform NAT gateway example - https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway/tree/master/examples/gke-nat-gateway
No (known) configuration changes occurred prior to the sudden failure, on a 1.11.2 GKE cluster

**Comment by sudomann** [comment]
@27Bslash6  Encountered this as well, did you guys solve it?

**Comment by l15k4** [comment]
I have the same trouble on 1.10.7.gke2  and helm `v2.12.3` ...

**Comment by l15k4** [comment]
We found the problem, k8s Master endpoint public addr, which is the proxy, had not 22 enabled in firewall rules for some reason ...

**Comment by sudomann** [comment]
Might just be GCE acting stupid sometimes. I destroyed the cluster and created another with the same name, region, parameters etc. on the same network. And I didn't get that error again. I hate to think of what a scenario I'd would be in if that was a mature cluster with contents I couldn't readily discard and reprovision :(
