### ISSUE TITLE
New GKE cluster not working with Helm

### ISSUE THREAD

**Issue by lyptt** [kubernetes/helm#4289]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

I created a new k8s cluster in GKE, but helm refuses to connect to it, even though the tiller pod installed fine, as reported below:
```
kubectl get deployments -n kube-system                         
NAME                           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
event-exporter-v0.2.1          1         1         1            1           27m
fluentd-gcp-scaler             1         1         1            1           27m
heapster-v1.5.3                1         1         1            1           27m
kube-dns                       2         2         2            2           27m
kube-dns-autoscaler            1         1         1            1           27m
l7-default-backend             1         1         1            1           27m
metadata-agent-cluster-level   1         1         1            1           27m
metrics-server-v0.2.1          1         1         1            1           27m
tiller-deploy                  1         1         1            1           9m
```

The error is below:

`Error: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused`

I can interact with k8s fine and create resources manually, no issues. I've tried refreshing my credentials with the following command:

```
gcloud container clusters get-credentials PROJECTNAME --region REGIONNAME
```

I've also tried the beta version of this command, nothing works. Helm is completely unusable in my cluster.

**Comment by lyptt** [comment]
I get the following log from the Tiller pod:

```
[storage/driver] 2018/06/30 13:11:54 list: failed to list: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
```

**Comment by bjornmagnusson** [comment]
Could it be RBAC issue?
Have you seen https://github.com/kubernetes/helm/blob/master/docs/rbac.md

**Comment by lyptt** [comment]
Yeah looks like this was the issue, I had to manually create the roles & bindings before Helm was happy.
