### ISSUE TITLE
helm repo add forbidden

### ISSUE THREAD

**Issue by magicalbanana** [kubernetes/helm#4290]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

When adding a repository found on Google Cloud Storage I am getting a `403` error. I'm guessing because it needs to authenticate. How do you authenticate adding a repository such as Google Cloud Storage that does not use a username and password?

**Comment by bacongobbler** [comment]
The [helm-gcs](https://github.com/nouney/helm-gcs) plugin handles authentication and authorization to GCS.

Hope that helps!

**Comment by magicalbanana** [comment]
Is this actively maintained or a solution that will persist?

**Comment by bacongobbler** [comment]
It's maintained by a community member, and it's open source. If it isn't actively maintained/abandoned, someone else is more than welcome to fork it and maintain the project. That's open source for ya :)
