### ISSUE TITLE
[2.10-rc1]: helm ls on fresh cluster causes panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bjornmagnusson** [kubernetes/helm#4323]
Running `helm ls` on fresh cluster with no deployed releases causes below error.
Deploying a single Helm Chart fixes the issue

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1276506]

goroutine 1 [running]:
main.(*listCmd).run(0xc4200d7290, 0xc42065a800, 0x1390a80)
        /go/src/k8s.io/helm/cmd/helm/list.go:170 +0x266
main.newListCmd.func2(0xc420946240, 0x20d41f8, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/helm/cmd/helm/list.go:117 +0x46
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc420946240, 0x20d41f8, 0x0, 0x0, 0xc420946240, 0x20d41f8)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3db
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420938000, 0xc420952480, 0xc4209526c0, 0xc420952900)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420938000, 0x1, 0x1)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /go/src/k8s.io/helm/cmd/helm/helm.go:160 +0x75

Output of `helm version`:
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Bare-metal on Centos 7.4
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

**Comment by fibonacci1729** [comment]
fixed by #4325
