### ISSUE TITLE
Why does helm use the mutable docker build label of canary rather then latest?

### ISSUE THREAD

**Issue by derekbassett** [kubernetes/helm#4333]
This is a general question about Helm.  While looking over the Makefile in Helm I noticed it uses the mutable docker build label of `canary`, rather then `latest`.  Why is that?  Why do you use `canary` rather then a more standard label like `latest`?

**Comment by bjornmagnusson** [comment]
My best guess is that there are assumptions around `latest` that makes it confusing, such that it actually not latest at all time but latest at a given point in time.

**Comment by derekbassett** [comment]
Thank you.
