### ISSUE TITLE
Write a document describing how to upload charts using gsutil command line tool.

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes/helm#476]
For the MVP, we need a way to upload charts to GCS / S3. We'll use gsutil as an example of how to do this, so write up a document showing how to do this.
#474

**Comment by sparkprime** [comment]
Is it actually easier to write a doc than it is to write the actual code to do this? :)

**Comment by vaikas-google** [comment]
to do what? To upload to gcs via server or via client? I suppose we could
also add the credential management to MVP, client side support and so on.
but my understanding was that it was out of the MVP, or am I
misunderstanding what you mean here?

**Comment by sparkprime** [comment]
Just the minimum required code to put a chart into a bucket so that a deploy can be performed.

**Comment by sparkprime** [comment]
(And it'd be in the client which is the only place where this would ever be done).

**Comment by vaikas-google** [comment]
That's not how I understood it. If you want me to write the helm client
side code that handles the credential management and talks directly to GCS
/ S3 then I can do that, but again I understood that to be outside of MVP.
And then there's the additional document of how to create these credentials
:)

**Comment by sparkprime** [comment]
Ah yes I forgot that quite a lot of credential management is involved because we're writing to the bucket and working around that by having public writable buckets would be a dumb idea.  Never mind, a doc it is then :)
