### ISSUE TITLE
helm deploy command line help inaccurate

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#479]
The help for the helm deploy command says that --name is an option, but the command requires it:

```
helm deploy --help
NAME:
   helm deploy - Deploy a chart into the cluster.

USAGE:
   helm deploy [command options] [CHART]

OPTIONS:
   --config, -c 	The configuration YAML file for this deployment.
   --name 		Name of deployment, used for deploy and update commands (defaults to template name)
   --properties, -p 	A comma-separated list of key=value pairs: 'foo=bar,foo2=baz'.
   
jackgr@jackgr-macbookpro:~/gopath/src/github.com/kubernetes/helm> helm deploy examples/charts/replicatedservice
[ERROR] Need deployed name on commandline
```

**Comment by adamreese** [comment]
The help text is correct.  Much of the code in deploy was removed by @sparkprime for the new chart format development.  It should be added back when deployments are working.

See https://github.com/kubernetes/helm/blob/master/docs/workflow/developer-workflows.md#simple-deployment

**Comment by sparkprime** [comment]
I removed    --config, -c     The configuration YAML file for this deployment.
I think I left the rest the same.

**Comment by adamreese** [comment]
The commit that introduced a mandatory name is https://github.com/kubernetes/helm/commit/7c73cd88793b5fed1ea5efa437c07501609197dc#diff-926fb6e4c69ea43047a128872013dec6L77

Prior it defaulted to the chart name

**Comment by sparkprime** [comment]
Ah yes, I had forgotten all about that :)

I think the reasoning there is that there was no-longer any support for deploying a local chart, so you don't know the chart name.

**Comment by technosophos** [comment]
It used to be able to extract the name from the YAML file, right?

**Comment by sparkprime** [comment]
yeah, we need to discuss what replaces that yaml file, and possible interactions with configmap / secrets
