### ISSUE TITLE
Two bugs in expandybird using charts

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#493]
When trying to deploy a chart, expansion fails on the schema for two reasons, both evident in the following dump.
* The schema file name is assumed to be `schema = source_file + '.schema'` on line 252 of expansion/expansion.py. However, can be seen below, `source_file` is the name of the chart zip file, not the name of the template file within the chart. In addition, the schema file name should be taken from the property in Chart.yaml, not computed from `source_file`.
* The file has not been base64 decoded.

```
2016/03/29 16:41:51 Manifest creation failed: cannot expand configuration:expandybird response:
error expanding chart: test1: Traceback (most recent call last):
  File "expansion/expansion.py", line 394, in <module>
    main()
  File "expansion/expansion.py", line 391, in main
    print Expand(template, imports, env=env, validate_schema=validate_schema)
  File "expansion/expansion.py", line 58, in Expand
    raise ExpansionError('config', str(e))
__main__.ExpansionError: Invalid schema 'gs://kubernetes-charts-testing/replicatedservice-v3.tgz.schema':
'aW5mbzoKICB0aXRsZTogUmVwbGljYXRlZCBTZXJ2aWNlCiAgZGVzY3JpcHRpb246IHwKICAgIERlZmluZXMgYSBSZXBsaWNhdGVkU2VydmljZSB0eXBlIGJ5IGNyZWF0aW5nIGJvdGggYSBTZXJ2aWNlIGFuZCBhbiBSQy4KCiAgICBUaGlzIG1vZHVsZSBjcmVhdGVzIGEgdHlwaWNhbCBhYnN0cmFjdGlvbiBmb3IgcnVubmluZyBhIHNlcnZpY2UgaW4gYQogICAgS3ViZXJuZXRlcyBjbHVzdGVyLCBuYW1lbHkgYSByZXBsaWNhdGlvbiBjb250cm9sbGVyIGFuZCBhIHNlcnZpY2UgcGFja2FnZWQKICAgIHRvZ2V0aGVyIGludG8gYSBzaW5nbGUgdW5pdC4KCnJlcXVpcmVkOgotIGltYWdlCgpwcm9wZXJ0aWVzOgogIGNvbnRhaW5lcl9uYW1lOgogICAgdHlwZTogc3RyaW5nCiAgICBkZXNjcmlwdGlvbjogTmFtZSB0byB1c2UgZm9yIGNvbnRhaW5lci4gSWYgb21pdHRlZCwgbmFtZSBpcyB1c2VkLgogIHNlcnZpY2VfbmFtZToKICAgIHR5cGU6IHN0cmluZwogICAgZGVzY3JpcHRpb246IE5hbWUgdG8gdXNlIGZvciBzZXJ2aWNlLiBJZiBvbWl0dGVkLCBuYW1lLXNlcnZpY2UgaXMgdXNlZC4KICBuYW1lc3BhY2U6CiAgICB0eXBlOiBzdHJpbmcKICAgIGRlc2NyaXB0aW9uOiBOYW1lc3BhY2UgdG8gY3JlYXRlIHJlc291cmNlcyBpbi4gSWYgb21pdHRlZCwgJ2RlZmF1bHQnIGlzCiAgICAgIHVzZWQuCiAgICBkZWZhdWx0OiBkZWZhdWx0CiAgcHJvdG9jb2w6CiAgICB0eXBlOiBzdHJpbmcKICAgIGRlc2NyaXB0aW9uOiBQcm90b2NvbCB0byB1c2UgZm9yIHRoZSBzZXJ2aWNlLgogIHNlcnZpY2VfcG9ydDoKICAgIHR5cGU6IGludAogICAgZGVzY3JpcHRpb246IFBvcnQgdG8gdXNlIGZvciB0aGUgc2VydmljZS4KICB0YXJnZXRfcG9ydDoKICAgIHR5cGU6IGludAogICAgZGVzY3JpcHRpb246IFRhcmdldCBwb3J0IHRvIHVzZSBmb3IgdGhlIHNlcnZpY2UuCiAgY29udGFpbmVyX3BvcnQ6CiAgICB0eXBlOiBpbnQKICAgIGRlc2NyaXB0aW9uOiBQb3J0IHRvIHVzZSBmb3IgdGhlIGNvbnRhaW5lci4KICByZXBsaWNhczoKICAgIHR5cGU6IGludAogICAgZGVzY3JpcHRpb246IE51bWJlciBvZiByZXBsaWNhcyB0byBjcmVhdGUgaW4gUkMuCiAgaW1hZ2U6CiAgICB0eXBlOiBzdHJpbmcKICAgIGRlc2NyaXB0aW9uOiBEb2NrZXIgaW1hZ2UgdG8gdXNlIGZvciByZXBsaWNhcy4KICBsYWJlbHM6CiAgICB0eXBlOiBvYmplY3QKICAgIGRlc2NyaXB0aW9uOiBMYWJlbHMgdG8gYXBwbHkuCiAgZW52OgogICAgdHlwZTogYXJyYXkKICAgIGRlc2NyaXB0aW9uOiBFbnZpcm9ubWVudCB2YXJpYWJsZXMgdG8gYXBwbHkuCiAgICBwcm9wZXJ0aWVzOgogICAgICBuYW1lOgogICAgICAgIHR5cGU6IHN0cmluZwogICAgICB2YWx1ZToKICAgICAgICB0eXBlOiBzdHJpbmcKICBleHRlcm5hbF9zZXJ2aWNlOgogICAgdHlwZTogYm9vbGVhbgogICAgZGVzY3JpcHRpb246IElmIHNldCB0byB0cnVlLCBlbmFibGUgZXh0ZXJuYWwgbG9hZCBiYWxhbmNlci4KICBjbHVzdGVyX2lwOgogICAgdHlwZTogc3RyaW5nCiAgICBkZXNjcmlwdGlvbjogSVAgdG8gdXNlIGZvciB0aGUgc2VydmljZQogIHByaXZpbGVnZWQ6CiAgICB0eXBlOiBib29sZWFuCiAgICBkZXNjcmlwdGlvbjogSWYgc2V0IHRvIHRydWUsIGVuYWJsZSBwcml2aWxlZ2VkIGNvbnRhaW5lcgogIHZvbHVtZXM6CiAgICB0eXBlOiBhcnJheQogICAgZGVzY3JpcHRpb246IFZvbHVtZXMgdG8gbW91bnQuCiAgICBpdGVtczoKICAgICAgdHlwZTogb2JqZWN0CiAgICAgIHByb3BlcnRpZXM6CiAgICAgICAgbW91bnRoX3BhdGg6CiAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgIGRlc2NyaXB0aW9uOiBQYXRoIHRvIG1vdW50IHZvbHVtZQogICAgICAgICMgU2VlIGh0dHBzOi8vY2xvdWQuZ29vZ2xlLmNvbS9jb250YWluZXItZW5naW5lL2RvY3Mvc3BlYy1zY2hlbWE/aGw9ZW4gZm9yIHBvc3NpYmxlIHZvbHVtZXMuIFNpbmNlIHdlIG9ubHkgdXNlIGdjZVBlcnNpc3RlbnREaXNrIGFuZCBORlMgaW4gb3VyIGV4YW1wbGVzIHdlIGhhdmUgb25seSBhZGRlZCB0aGVzZSBvbmVzLgogICAgICAgIG9uZU9mOgogICAgICAgICAgZ2NlUGVyc2lzdGVudERpc2s6CiAgICAgICAgICAgIHBkTmFtZToKICAgICAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgICAgICBkZXNjcmlwdGlvbjogUGVyc2lzdGVudCdzIGRpc2sgbmFtZQogICAgICAgICAgICBmc1R5cGU6CiAgICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgICAgZGVzY3JpcHRpb246IEZpbGVzeXN0ZW0gdHlwZSBvZiB0aGUgcGVyc2lzdGVudCBkaXNrCiAgICAgICAgICBuZnM6CiAgICAgICAgICAgIHNlcnZlcjoKICAgICAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgICAgICBkZXNjcmlwdGlvbjogVGhlIGhvc3RuYW1lIG9yIElQIGFkZHJlc3Mgb2YgdGhlIE5GUyBzZXJ2ZXIKICAgICAgICAgICAgcGF0aDoKICAgICAgICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICAgICAgICBkZXNjcmlwdGlvbjogVGhlIHBhdGggdGhhdCBpcyBleHBvcnRlZCBieSB0aGUgTkZTIHNlcnZlcgogICAgICAgICAgICByZWFkT25seToKICAgICAgICAgICAgICB0eXBlOiBib29sZWFuCiAgICAgICAgICAgICAgZGVzY3JpcHRpb246IEZvcmNlcyB0aGUgTkZTIGV4cG9ydCB0byBiZSBtb3VudGVkIHdpdGggcmVhZC1vbmx5IHBlcm1pc3Npb25zCgo=' is not of type u'object'
```

**Comment by sparkprime** [comment]
I have tests that exercise this, do you see anything that does not meet your expectations in them?  expandybird/expander/expander_test.go 
TestSchema

**Comment by sparkprime** [comment]
Basically because I wanted to avoid modifying the python code if possible, even though it was doing some weird stuff, I remapped the schema file so it can find it.  I am now thinking we should just validate schemas outside of the python code instead, using the same code that will do it for go templates and jsonnet.

That base64 encoding is weird, as it's being done implicitly for all files by the json unmarshalling logic.

**Comment by jackgr** [comment]
No, the base64 encoding is what we agreed we would with the members of a Chart when loading them with LoadContent().

**Comment by jackgr** [comment]
Not sure why your schema tests work correctly while the actual chart schema fails in the wild.

**Comment by sparkprime** [comment]
They are base64 encoded on the wire, but the encoding is done by the encoding/json marshalling, so you don't need to do it yourself on top.  If you're doing it yourself, it may be doing it twice, which would cause this.  But then it would do it for everything in templates/ right?  Maybe just the schema is the first file that it sees.

**Comment by sparkprime** [comment]
Yeah I think it's here, you don't need to do this as it's implicit: https://github.com/kubernetes/helm/blob/master/pkg/chart/chart.go#L421

**Comment by jackgr** [comment]
No, that's exactly the problem. The chart package base64 encodes as agreed, at the line you've listed above. However, the contents are never base64 decoded.

I'm therefore adding a base64 decode to ExpandChart and a base64 encode to the test data, since it isn't loaded from charts.

**Comment by jackgr** [comment]
Found the schema naming bug. It's at https://github.com/kubernetes/helm/blob/master/cmd/expandybird/expander/expander.go#L118. 

The problem is that `chartInv.Type` is the fully qualified chart name (e.g., `gs://kubernetes-charts-testing/replicatedservice-1.2.3.tgz`). Is should be the name of the template file (e.g., `templates/replicatedservice.py`).

**Comment by jackgr** [comment]
Also found where the base64 decoding should go... before this line: https://github.com/kubernetes/helm/blob/master/cmd/expandybird/expander/expander.go#L120.

**Comment by jackgr** [comment]
I'm fixing both of these.

**Comment by sparkprime** [comment]
You're still base64 encoding it twice.  Adding two decoding steps at the other side is not a solution to that.

**Comment by jackgr** [comment]
Removed base64 encoding from pkg/chart. Letting json marshaling encode/decode on the wire, and passing around in memory as an unencoded []byte.

**Comment by jackgr** [comment]
Schema problem is caused by invalid schema file `replicatedservice.py.schema` ported verbatim from [kubernetes/charts/common/replicatedservice/v2/replicatedservice.py.schema](https://github.com/kubernetes/charts/blob/master/common/replicatedservice/v2/replicatedservice.py.schema), as well as an ugly workaround that substitutes the chart name for the template file name, which probably doesn't make sense to try and back out right now, according to @sparkprime.
