### ISSUE TITLE
helm repo add should validate url 

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#501]
Right now you can add whatever repo url you want. Anything is allowed. I think we should validate the repo url to at least be well formatted (including it should have the right prefix), so I've opened PR #489. 

- We've talked about supporting google storage repos in the mvp, so we can accept "gs://", "http://" and "https://" as repo url prefixes unless someone objects

- I was originally thinking this would be a client side validation but it makes sense to put it on the server side. I don't think the current place I put it (in the route handler) is the right spot. I think it should probably be in the repo service createRepo function.

Let me know if you have any thoughts or objections. :)

**Comment by jackgr** [comment]
Fixed by #489.
