### ISSUE TITLE
Add `helm chart list`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#504]
After MVP, add `helm chart list`.

https://github.com/kubernetes/helm/blob/master/docs/workflow/developer-workflows.md#listing-all-installed-charts

**Comment by jackgr** [comment]
This functionality is available on the server side already and the client side is similar to deployment list, which is already implemented, so it should be quick. More importantly, it's one of the DM features that people value. Let's consider it a stretch goal for MVP.
