### ISSUE TITLE
Add `helm chart package`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#505]
Removed this for MVP.

```
			{
				Name:      "deployments",
				Usage:     "given a chart, show all the deployments that reference it.",
				ArgsUsage: "CHART",
			},
```

There is no accompanying design description for this in the workflow doc.

**Comment by jackgr** [comment]
@technosophos `helm chart package` appears to work correctly. In addition, the comment above does not appear to be related to `helm chart package`. Is this issue mislabelled perhaps?

**Comment by jackgr** [comment]
Closing this issue, since it appears to be resolved. Please reopen if it isn't resolved.
