### ISSUE TITLE
Add `helm credential *` commands

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#506]
The credential commands need to be added at some point after MVP. See https://github.com/kubernetes/helm/blob/master/docs/workflow/developer-workflows.md#adding-credentials

**Comment by technosophos** [comment]
This is probably the right place to raise the concern that treating credentials as a separate entity may not be a good idea.

First, what is the use case? Some small percentage of users will want to add repositories that require credentials for access. Of those, some smaller percentage may have more than one repository that share the same credentials. So the theory is that for that tiny use case, we should add a series of endpoints and commands.

But this is a security problem.

Case:

- Alice wants to add one of her two private chart repos. Both repos share the same credentials. She has no intent of adding the other repo.
- Alice adds credentials
- Alice adds the first repo

Now along comes Bob.

- Bob wants to access the charts in Alice's other repo. He does not know what Alice's credentials are.
- Bob lists Alice's credentials
- Bob adds the repo he is not supposed to be able to access, and uses Alice's credentials to do it.

If instead we make credentials an attribute of a repository and don't return the credentials from the REST endpoint, then Bob cannot hijack Alice's credentials.

**Comment by michelleN** [comment]
@technosophos definitely fair points and I'd agree.
