### ISSUE TITLE
Add `helm dep config`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#508]
Post-MVP, we need to add `helm deployment config`. There is no description of this in the workflow document, but this was the code I removed:

```
			{
				Name:      "config",
				Usage:     "Dump the configuration file for this deployment.",
				ArgsUsage: "DEPLOYMENT",
			},

```

**Comment by jackgr** [comment]
This functionality is available on the server side already and the client side is similar to describe, which is already implemented, so it should be quick. More importantly, it's one of the DM features that people value. Let's consider it a stretch goal for MVP.
