### ISSUE TITLE
Add `helm dep manifest`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#509]
After MVP, add `helm deployment manifest`.

https://github.com/kubernetes/helm/blob/master/docs/workflow/developer-workflows.md#get-fully-generated-manifest-files

**Comment by jackgr** [comment]
This functionality is available on the server side already and the client side is similar to describe, which is already implemented, so it should be quick. More importantly, it's one of the DM features that people value. Let's consider it a stretch goal for MVP.
