### ISSUE TITLE
Add `helm chart release`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#513]
After MVP, add `helm chart release`.

https://github.com/kubernetes/helm/blob/master/docs/workflow/developer-workflows.md#packaging-and-releasing-packages

I have removed the front-end for the existing `helm release`.

**Comment by technosophos** [comment]
This is another issue that we should revisit.

Having surveyed a number of similar tools, I am not seeing this particular feature implemented by other clients. And I can see why. The process of releasing a package has a very different set of security constraints than all of the other operations.

For example, all other operations require only read access to remote chart repositories, this one requires write access, and possible ACL support as well.

As a further example, either the client must be able to publish to an arbitrary number of chart repositories directly, _or_ we need a proxy configuration for the server (which substantially complicates the credential handling and permissions model of the server).

Finally, this feature is not actually a feature we are planning to use for the official chart repo. We're talking about having charts automatically generated from a CI/CD pipeline and then pushed into the repo from there.

It seems to me to be perfectly reasonable to require that a developer configure a separate client to be able to access their chosen backend. There are an abundance of tools already well suited for this, from CLIs to FUSE filesystems to specialized GUI clients.

**Comment by jackgr** [comment]
Don't want to throw the baby out with the bath water here. The signing and provenance are valuable features. Let's remove the storage push from this command and implement those features for MVP.
