### ISSUE TITLE
Client and server use different chart tarball formats

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#516]
The tarball format generated by `helm chart package` is different from the one assumed by `pkg/chart`. The former generates:

```
drwxr-xr-x  0 247269  5000        0 Mar 29 19:20 .
-rw-r--r--  0 247269  5000      196 Mar 29 21:15 Chart.yaml
drwxr-xr-x  0 247269  5000        0 Mar 29 11:31 docs
drwxr-xr-x  0 247269  5000        0 Mar 29 11:31 hooks
drwxr-xr-x  0 247269  5000        0 Mar 29 21:00 templates
-rw-r--r--  0 247269  5000     6455 Mar 29 21:12 templates/replicatedservice.py
-rw-r--r--  0 247269  5000     2690 Mar 29 15:54 templates/replicatedservice.py.schema
```

but the latter expects:

```
drwxr-xr-x  0 jackgr 5000        0 Mar 29 19:20 replicatedservice/
-rw-r--r--  0 jackgr 5000      196 Mar 29 21:15 replicatedservice/Chart.yaml
drwxr-xr-x  0 jackgr 5000        0 Mar 29 11:31 replicatedservice/docs/
drwxr-xr-x  0 jackgr 5000        0 Mar 29 11:31 replicatedservice/hooks/
drwxr-xr-x  0 jackgr 5000        0 Mar 29 21:00 replicatedservice/templates/
-rw-r--r--  0 jackgr 5000     6455 Mar 29 21:12 replicatedservice/templates/replicatedservice.py
-rw-r--r--  0 jackgr 5000     2690 Mar 29 15:54 replicatedservice/templates/replicatedservice.py.schema
```

@sparkprime did a quick survey of rpm and deb packages and found that there is no convention there for including a prefix, even in the tar.gz inside the deb package. rpm is a cpmioball, deb is an arball containing two tarballs, and none of these things have any prefixes.

That said, a prefix is useful to avoid tarbombing, where files unpacked from an archive overwrite local files. 

For now, we should fix this problem by adding a prefix in the packaging process, rather than by removing the prefix assumption from the unpackaging process, since that's cleaner, although it means departing with precedent.

**Comment by technosophos** [comment]
`helm chart pack` uses `chart.Save()`:
https://github.com/kubernetes/helm/blob/master/cmd/helm/chart.go#L106

**Comment by jackgr** [comment]
So it does... thanks for looking. I'm just getting to this now.

**Comment by technosophos** [comment]
I think `loadTar` is the broken function. It'll be a pretty nice simplification to remove the extra directory.

**Comment by jackgr** [comment]
Went the other way.

`loadTar` is checking the prefix to make sure it doesn't unpack things outside the chart. Seems useful.

`Save` was attempting to make the paths in the tar header include the prefix, but falsely assumed that the chart directory was clean and absolute. Result was that computation of parent directory yielded ".", and that's what all header entries were relative to.
