### ISSUE TITLE
Outstanding design decisions requiring consensus

### ISSUE THREAD

**Issue by sparkprime** [kubernetes/helm#520]
This is just a brain dump from me.  There is not enough info here to start a productive discussion.  I propose we have this discussion on a Monday meeting soon.

Things required to be implemented for MVP and cannot be changed in backwards compatible ways
------------------------------------------------------------------------------------------------------------------------------------

**Inconsistency capitalization in chart files**
LICENSE README.md Chart.yaml icon.svg
What is the rationale behind the choice of capitalization?  Can we be more consistent?  Should we be case-insensitive?

**Chart schema field**
Should it be implicit like LICENSE, icon.svg, README.md? What should its filename be?
Should it be restricted to JSONschema for all generator backends? Swagger? Intersection(JSONschema, swagger)?

**Expander entrypoint**
Are we ok with Chart.yaml's current expander field?  Do we want a more general way of passing extra info to the expander (beyond the current entrypoint, which is not used by go templates).

**Expansion returning "wrapped objects"**
In order to support multiple provider backends and subcharts, the resources returned by expansion need an extra header to say whether they are kubernetes objects, recursive helm charts, or other provider resources (e.g. GCP, AWS).  Note that there is prior art here -- Both DM and Terraform have an extra layer of wrapping in order to allow subcharts (DM) and multiple providers & subcharts (Terraform).  Do we want to mitigate this for the likely case where a chart only contains kubernetes objects (and is a leaf chart), by having some provider: kubernetes field in the Chart.yaml to automatically wrap such objects?  (This will also work for GCP but not AWS as AWS resources do not have names).

What about charts with no expander field?  Should they returned wrapped objects or not?

**Should packages be tarbombs**
Should there be a chartname/ prefix on all filenames in the tarball?
Should the tarball have a different file extension (to warn people off assuming they are not tarbombs).

Other:
--------

**Package administration**
Does the client or server upload to the bucket?

**Deployment API**
Do we want to restrict the API to only deploy one chart?  What is the difference in semantics between deploy([a, b]) and deploy(a); deploy(b); ?

**Comment by technosophos** [comment]
Chart naming:
The conventions for that are pretty common across projects, and have mainly to do with the sorting employed by `ls` and GitHub. Visually, all-caps come first, initial caps come second, and lowercase come third. Gems, Grunt, and a number of other package managers use the initial caps notation for manifests and lock files: https://github.com/twbs/bootstrap

**Comment by technosophos** [comment]
Package Tarbombs:
Given that we currently require a named directory at the top level of a chart's tgz file (`e.g. frobnitz/Chart.yaml`), I'd be reluctant to change this unless there was a good reason.

I have no strong opinion about a special extension. Seems that package managers do different things in this regard.

**Comment by technosophos** [comment]
Package administration:

Having surveyed a number of package managers, I now think that neither the Helm CLI nor the server should be involved in pushing charts into object storage.

1. Nobody else seems to handle the upload case inline with the package manager (examples: apt, yum, homebrew)
2. It introduces some substantial security and permissions requirements
3. It introduces the danger of a user accidentally uploading write credentials instead of read credentials, and then exposing those to all users
4. It forces us to just re-implement (probably badly) a wide variety of existing tools (gsutil, mc, s3, etc)
5. There are already lots and lots and existing tools that securely upload files to object storage

**Comment by sparkprime** [comment]
Looks like github and ls just sort using lexical ordering via unicode codepoint, so README is after Qzzz.

**Comment by sparkprime** [comment]
On package tarbombs, even if the package is a black box (in which case we should lose the .tgz extension) changing the format later will invalidate all existing charts and require an expensive migration (i.e. it's very unlikely to be worth the trouble).  However, changing it now would only take a few minutes.  So I don't think the fact that it's done a particular way in the codebase right now should influence our discussion on what it should be, a decision that will have impact for years to come.

**Comment by jackgr** [comment]
@technosophos 👍 re: not pushing charts to repos.

**Comment by jackgr** [comment]
The remaining items in the list seem to be of relatively minor significance.
