### ISSUE TITLE
Error trying to deploy the Guestbook Example

### ISSUE THREAD

**Issue by jason-riddle** [kubernetes/helm#534]
Getting the following message after trying to deploy the guestbook example (https://github.com/kubernetes/helm/tree/master/examples/guestbook).

```bash
$ bin/helm --host "http://localhost:8001/" deploy -n guestbook guestbook.yaml
[ERROR]
```

Any idea on how to debug this?

**Comment by technosophos** [comment]
IIRC, guestbook has not been updated to the new format. So that YAML file is not valid for the new chart format.

Clearly, we need some better error messages on this (in addition to fixing the chart). ;-)

**Comment by jason-riddle** [comment]
No problem. Is there a valid example that exists that I can take a look at?

**Comment by michelleN** [comment]
@jason-riddle - yeah check out the updated README.md --> ` https://github.com/kubernetes/helm/blob/master/README.md `
and examples/charts at ` https://github.com/kubernetes/helm/tree/master/examples/charts `

**Comment by jackgr** [comment]
We need a working Guestbook for MVP.
