### ISSUE TITLE
Output parameters

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#54]
As a Kubernetes user, I can write DM templates that bind output parameters from a resource into input parameters in dependent resources.

**Comment by jackgr** [comment]
Depends on #53.

**Comment by bmelville** [comment]
I'm going to propose we collapse these into just #53, given that there is one syntax for both dependencies and references.

**Comment by jackgr** [comment]
Actually, they are two different pieces of work. This issue is about implementing value propagation from output parameters to input parameters. #53 is about making the workflow respect dependency order. Yes, there's just one syntax. However, I'm pretty sure they will be implemented in different parts of the code base. So, I think it helps to break out the implementation tasks involved. If you want to collapse them, then I'd suggest that you add a checkbox task list to the issue that enumerates these two pieces of implementation.
