### ISSUE TITLE
Use statically compiled amd64 kubectl v1.2

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#547]
Install a statically compiled version of the kubectl amd64 version. Somewhere between kubectl 1.1.7 and 1.2.0, the build process changed. The 1.1.7 versions are dynamically linked with libc (which doesn't work on Alpine).

Switching to the amd64 version of kubectl 1.2.0 will fix the problem. This can be verified by using `kubectl exec -it manager-XXXX sh` and then running `/bin/kubectl` manually. That will when the manager instance has 1.1.7, but succeed if the manager has 1.2.0.

**Comment by jackgr** [comment]
Yes, good catch. That issue was exposed by the move to alpine:3.3 base images.

Already fixed it yesterday, however, in #543 by using i386 version of selected ${KUBE_VERSION}, which is statically linked, and pushed the updated images.

**Comment by jackgr** [comment]
Is this issue redundant with #542?

**Comment by jackgr** [comment]
I'm thinking that we should move to k8s 1.2, including this change. Before we do, however, we should confirm that all works as it does now (i.e., no regressions). Suggest that we continue waiting for the e2e tests to run clean before moving, just to keep the number of moving pieces down. When they're in, then let's move to 1.2 across the board, including kubectl.
