### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jason-riddle** [kubernetes/helm#551]
Trying to deploy to a GKE cluster is giving me the following error.

```bash
$ helm deploy --name test --properties "workers=2" gs://kubernetes-charts-testing/redis-2.tgz
[ERROR] Post https://XXX.XXX.XX.XXX/api/v1/proxy/namespaces/helm/services/manager-service:manager/deployments: x509: certificate signed by unknown authority
```

Is there any way to disable TLS verification or to trust the self-signed cert?

**Comment by runseb** [comment]
@jason-riddle if you run a `kubectl proxy --port=8001` locally, and set your HELM_HOST to `http://localhost:8001/api/v1/proxy/namespaces/helm/services/manager-service:manager`

it should properly forward the request.

**Comment by jason-riddle** [comment]
Alright so now upon running the proxy before trying to add kubernetes-charts-testing, I get the following.

```
$ helm repo add kubernetes-charts-testing gs://kubernetes-charts-testing
[ERROR] 404 page not found

```

When I visit <code>http://localhost:8001/</code> in my browser, I literally get the following text.

```
<h3>Unauthorized</h3>
```

While visiting the <code>https://XXX.XXX.XX.XXX</code> master url works fine.

Maybe I don't understand proxying, but how would helm be able to validate the certificate, if there is just forwarding from <code>http://</code> to <code>https://</code>? Wouldn't it see this as an issue? It can't just blindly be okay with the fact that it was expecting <code>http</code> but instead got <code>https</code>?

**Comment by runseb** [comment]
Can you try the latest version of `helm`. I am not sure how you are getting it installed. But I believe the error you are seeing is because the images running the services are out of date.
Try getting the latest helm and redeploy with `helm server install`.

As far as the proxy. `kubectl proxy` proxies all API requests to the secure endpoint (using the certs and tokens of your secured k8s server). A service running in your k8s cluster can be reached as if running locally thanks to the proxy. 

With a working helm you will be able to curl the helm manager API at the HELM_HOST URL.

**Comment by jason-riddle** [comment]
Upgraded and still getting the same issue.

```bash
$ helm --version
helm version v1.2+0af0856

$ helm server uninstall
namespace "helm" deleted

$ helm server install
## <snip>


$ export HELM_HOST=http://localhost:8001/api/v1/proxy/namespaces/helm/services/manager-service:manager

$ helm repo add kubernetes-charts-testing gs://kubernetes-charts-testing
[ERROR] 404 page not found

```

**Comment by jason-riddle** [comment]
Running <code>curl http://localhost:8001/api/v1/proxy/namespaces/helm/services/manager-service:manager</code> returns nothing.

**Comment by runseb** [comment]
is your proxy running ? `kubectl proxy --port 8001`

**Comment by jason-riddle** [comment]
Yes it is. Up above I've listed the commands to reproduce what I've done.

**Comment by technosophos** [comment]
This should no longer be a problem with the new version.

**Comment by erikbgithub** [comment]
@jason-riddle You may have already learned this, but the better way to debug with curl is using `-vvvv` to see what happens in the http communication.
