### ISSUE TITLE
Make charts without parameterized values pass through the expander

### ISSUE THREAD

**Issue by runseb** [kubernetes/helm#570]
this is related to the conversation in #561 .

charts from helm/charts that will be merged in kubernetes/charts need to be deployable in new helm.

**Comment by michelleN** [comment]
:+1: examples/charts/nginx is an example that should work

**Comment by runseb** [comment]
I tried it yesterday and it did not work because there is a new `expander` field in the chartfile struct.

**Comment by jackgr** [comment]
This PR will be overtaken by the pluggable services PR coming shortly.
