### ISSUE TITLE
Improve CLI stdout writer

### ISSUE THREAD

**Issue by runseb** [kubernetes/helm#571]
Currently the output of

```
helm charts list
helm deployment list
helm deployment describe <test>
```

are really poorly formatted, we need to improve this for MVP to create a better user experience.

**Comment by michelleN** [comment]
absolutely. I'd add `helm repo list` on this list too.

**Comment by technosophos** [comment]
This references an old version of `helm`. I believe Michelle's new version uses uitable to do some formatting.
