### ISSUE TITLE
Timestamp on `deployment rm` is unset

### ISSUE THREAD

**Issue by runseb** [kubernetes/helm#580]
```
$ helm deployment rm test
[INFO] Deleted "test" at 0001-01-01 00:00:00 +0000 UTC
```

might want to generate a proper timestamp

**Comment by runseb** [comment]
the time is set in

```
cmd/manager/repository/persistent/persistent.go
cmd/manager/repository/transient/transient.go
```
and type of a deployment is declared in:

`pkg/common/types.go`

Seems fine to me, not sure why it returns zero...

**Comment by jackgr** [comment]
We should fix this.

**Comment by technosophos** [comment]
No longer applicable to the current product.
