### ISSUE TITLE
test chart package names are not formatted using semver

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#581]
How come our test package names look like this: gs://kubernetes-charts-testing/redis-2.tgz and not
gs://kubernetes-charts-testing/redis-2.0.0.tgz (using semver) like in https://github.com/kubernetes/helm/blob/master/docs/design/chart_format.md#the-chart-repository

```
https://helm.sh/charts/
        apache-2.3.4.tgz
        apache-2.3.4.prov
        nginx-1.1.1.tgz
        nginx-1.1.1.prov
        nginx-1.1.2.tgz
        nginx-1.1.2.prov
        redis-0.4.0-alpha.1.tgz
        redis-0.4.0-alpha.1.prov
```

**Comment by runseb** [comment]
I think the redis and the replicated service one must have been tarred by hand by @jackgr 
the others look fine, including one that I used earlier today:

https://console.cloud.google.com/storage/browser/kubernetes-charts-testing/

**Comment by michelleN** [comment]
Gotchya. We should re-package the redis one and refer to the well-formatted chart in the README.

**Comment by jackgr** [comment]
That's what `helm chart package` produced.

**Comment by runseb** [comment]
Ah well, looks like the replicated service example has a version set to "3"

and redis is set to "2"

so that explains it.

**Comment by jackgr** [comment]
What's invalid about those version numbers?

**Comment by michelleN** [comment]
yep. So in the future we'll have a linter to validate the chart format and fields, but for now, I went ahead and updated the version fields in the in the example charts to reflect semver format. I also repackaged and uploaded the redis-2.0.0.tgz chart to kubernetes-charts-testing (and updated the readme).
