### ISSUE TITLE
Clean up docs/ directory

### ISSUE THREAD

**Issue by sparkprime** [kubernetes/helm#582]
Currently it's a mixture of future-looking ideas / designs / proposals and concrete documentation for the existing code.  I propose we separate these cleanly to avoid confusing casual users.  Here's an example of the sort of structure I'd like to see in docs/

* chart_format.md:   A versioned formal spec describing the expectations the current code has about what charts look like.  We will develop this from release to release, ideally in a backwards-compatible fashion, e.g. by adding provenance.

* chart writing tutorial:  How to create / store charts, best practices.  Discussive documentation.

* tutorials on using the tools provided -- how to build / install / set them up.  Examples of user flows, etc.

* proposals/ directory for future stuff, which can be a bit chaotic and a dumping ground

* attic/ directory for older versions of the specs, and design docs that have been superseded by actual implementations but are being kept for posterity in order to keep a record of the rationale for various decisions (although maybe that stuff actually belongs in some digested form in the current docs, so perhaps we don't want this).

**Comment by jackgr** [comment]
:+1:

**Comment by michelleN** [comment]
Definitely agree the directory needs to be cleaned up. I probably wouldn't want the attic/ directory around forever but it seems sane for now for sure.

**Comment by michelleN** [comment]
Do you think the chart writing tutorial should be in this repo? I thought Matt was putting it in the kubernetes/charts repo. Maybe we should just link to it? @sparkprime

**Comment by sparkprime** [comment]
I feel that if it's a tutorial for all chart repos then it probably doesn't belong in that specific one (and we should link to it from there, since that repo is a special instance of the general kind of repo).

**Comment by sparkprime** [comment]
If we look really long term, we'll probably have a web site driven from gh-pages using something like jekyll, and then we'll have centralized documentation in doc/.  In the mean time, users are going to have to go to that doc/ directory to find what they're looking for.
