### ISSUE TITLE
remove replicatedservice-3.tgz and redis-2.tgz + references in code

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#584]
#581 / #583 led to updating charts to reflect proper semantic versioning. Here are the next steps:

1. Remove/update references to replicatedservice-3.tgz and redis-2.tgz in code base
2. Remove replicatedservice-3.tgz and redis-2.tgz from kubernetes-charts-testing bucket

Let me know if you think there might be issues with this.

**Comment by jackgr** [comment]
@michelleN there are no references that I can find to replicatedservice-3.tgz in the code, other than in the examples, which seems appropriate. Likewise, the only references to redis-2.tgz are in examples and as dummy data in a test. Are these the references you're looking to remove?

**Comment by jackgr** [comment]
@michelleN it's convenient to have replicatedservice-3.tgz and redis-2.tgz in the kubernetes-charts-testing bucket. What's the motivation for removing them?
