### ISSUE TITLE
kubernetes-charts-testing is not a public bucket

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#585]
I tried to view this bucket as a non-deis/non-helm user on google cloud storage, and got a permissions issue (see screenshot). We're pointing to the charts in this bucket in the README, so if it is indeed not public, we should make it publicly readable.

![gcs-kubernetes-charts-testing](https://cloud.githubusercontent.com/assets/1497123/14362439/c4a77686-fcbc-11e5-8743-114d0375e368.png)

**Comment by michelleN** [comment]
getting the same on kubernetes-charts
![gcs-kubernetes-chart](https://cloud.githubusercontent.com/assets/1497123/14362446/cbf04a12-fcbc-11e5-86e4-78bebfd45cea.png)

Would appreciated a sanity check.

**Comment by michelleN** [comment]
cc/ @jackgr

**Comment by jackgr** [comment]
They claim to be public...

![image](https://cloud.githubusercontent.com/assets/5607565/14369093/10faccd0-fcd7-11e5-9b9b-5744d955e5ed.png)

**Comment by jackgr** [comment]
Perhaps access was denied because you were not using *any* Google account?

**Comment by michelleN** [comment]
hmm it indeed does look public and I was on my personal gmail account. _strange_. If this isn't a problem for anyone, we can just close it.
