### ISSUE TITLE
Kubernetes object parsing is too aggressive

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#589]
I've been thinking about the decision we took last minute to pass all Kubernetes API object parse errors on to the user, failing the chart deployment, in ExpandConfiguration. 

While it prevents false positives, it also creates significant potential for false negatives. We say in the chart_format.md document that Chart authors are encouraged to put all kinds of files in the `templates/` directory, and we give the examples of schema files and display markup files. If those files carry `yaml` or `json` extensions, they won't parse, and the Chart will fail to load.

This seems overly aggressive to me. True, authors could give such files more specific extensions, such as `.schema`. However, they will then have the burden of adding/removing those extensions as they work with those files during chart development, without any smart automation from tools that could offload that burden.

I'd rather expose the parse error to the user if and only if the file appears by all rights to be a Kubernetes API object, as determined by the presence of a valid ObjectMeta (i.e., `apiVersion` and `kind` properties).  
Thoughts?

/cc @sparkprime

**Comment by sparkprime** [comment]
How much validation is currently performed?  Looks like it's just this, which isn't much more than you're proposing: 

```
type KubernetesObject struct {
        Kind       string                 `json:"kind"`
        APIVersion string                 `json:"apiVersion"`
        Metadata   map[string]interface{} `json:"metadata"`
        Spec       map[string]interface{} `json:"spec"`
}
```

**Comment by sparkprime** [comment]
I don't think we do say you can put whatever you like in templates/.  I think we say:

* You can put whatever you like in the chart in addition to the files / dirs that are well defined.
* The contents of /templates are consumed by the expander, and constraints on what files can / must exist, their contents, etc are defined by the particular expander.

In this case we're defining a default expander that doesn't do any expanding, so I think we're free to require files to not end in .yaml or .json unless they contain actual resources.  Also from the PoV of a user browsing through templates/, a simple rule like that makes it easy to tell what the files are for.

**Comment by jackgr** [comment]
OK. I'm sold.
