### ISSUE TITLE
More documentation to explain how to use or learn more about a chart

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/helm#590]
The README provides an example using Redis but there is no guidance on why this command's properties are necessary to deploy this Chart:

    bin/helm deploy --name test --properties "workers=2" gs://kubernetes-charts-testing/redis-2.0.0.tgz

Clearly, the deployment contains 2 slaves (aka "workers") but how would I infer this?

**Comment by technosophos** [comment]
This relates to an old version of Helm, but we should still make sure we address it in the current version
