### ISSUE TITLE
Document (or fix) the Nginx charts

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/helm#591]
gsutil ls gs://kubernetes-charts-testing

List several charts. How would a Helm user learn how to deploy any of these? Or, do they need to be documented?

gs://kubernetes-charts-testing/frobnitz-0.0.1.tgz
gs://kubernetes-charts-testing/nginx-0.0.1.tgz
gs://kubernetes-charts-testing/nginx-0.2.0.tgz
gs://kubernetes-charts-testing/redis-2.0.0.tgz
gs://kubernetes-charts-testing/redis-2.tgz
gs://kubernetes-charts-testing/replicatedservice-3.0.0.tgz
gs://kubernetes-charts-testing/replicatedservice-3.tgz

I tried:

    bin/helm deploy --name nginx gs://kubernetes-charts-testing/nginx-0.0.1.tgz
```
[ERROR] cannot expand configuration:expandybird response:
error expanding chart: nginx: Chart JSON does not have expander field
&{[0xc820412150]}
```
    bin/helm deploy --name nginx gs://kubernetes-charts-testing/nginx-0.2.0.tgz
```
bin/helm deploy --name nginx gs://kubernetes-charts-testing/nginx-0.2.0.tgz
[ERROR] cannot expand configuration:expandybird response:
error expanding chart: nginx: The entrypoint in the chart.yaml cannot be found: 
&{[0xc820413d10]}
```

Gave up :-(

**Comment by runseb** [comment]
@DazWilkin you are right, the nginx chart does not work right now. We added a GoTemplate expander to helm and this broke basic charts.

We are working on it.

**Comment by technosophos** [comment]
Relates to an old version of Helm
