### ISSUE TITLE
Provide a way to enumerate the charts in a repository

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/helm#593]
There appears to be no way to introspect the charts in a repository.

```
COMMANDS:
    chart	Perform chart-centered operations.
    deploy	Deploy a chart into the cluster.
    deployment	Perform deployment-centered operations.
    doctor	Run a series of checks for necessary prerequisites.
    repository	Perform chart repository operations.
    server	Manage Helm server-side components
```

I kinda want 'repository' to do this but it appears to list the repos and there's no (obvious) way to list the charts in a repo [short of gsutil ls]

**Comment by jackgr** [comment]
Should we consider implementing this for MVP?

**Comment by runseb** [comment]
@jackgr check #605 that is a WIP for this. But it seems the google storage SDK requires an account even though the bucket is publicly readable.

**Comment by DazWilkin** [comment]
@runseb if it does, that is a bug (if you give me a repro, I'll file it for you)

https://cloud.google.com/storage/docs/gsutil/addlhelp/AccessingPublicDataWithoutCredentials

I'm interested to know why Helm (appears to) take(s) GCS as a dependency.

Is GCS the first repo and there are plans to make repos pluggable?

**Comment by vaikas-google** [comment]
As per the design document, it's absolutely not only meant to be used only with GCS and an explicit goal of supporting multiple object stores is where we're headed.
https://github.com/kubernetes/helm/blob/master/docs/design/chart_format.md#the-chart-repository

The gcs is actually the second one, the first was 'in-mem' :)
So, definitely plans for multiple implementations, PRs welcome.

**Comment by technosophos** [comment]
In the new version of Helm, this is done with `helm search`, and can also be done using simple filesystem commands like `ls $(helm home)/cache`.
