### ISSUE TITLE
Provide command consistency between Kubernetes and Helm

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/helm#594]
kubectl verb pluralized-noun
    kubectl get pods

But

    helm singular-noun verb
    helm deployment list

Propose 

    helm verb pluralized-noun
    helm get deployments

**Comment by runseb** [comment]
@DazWilkin can we close this as duplicate of #555 ?

**Comment by DazWilkin** [comment]
Sure

**Comment by jackgr** [comment]
Closing as duplicate.
