### ISSUE TITLE
tiller pod not fronted by a kubernetes service

### ISSUE THREAD

**Issue by sgoings** [kubernetes/helm#648]
After running a `helm init` I see:

```
$ kubectl get svc,rc,po --namespace=helm
NAME              DESIRED   CURRENT   AGE
tiller-rc         1         1         29m
NAME              READY     STATUS    RESTARTS   AGE
tiller-rc-32koc   1/1       Running   0          29m
```

But the rc is not fronted by a service so if this is a remote kubernetes cluster, there's no way for the `helm` cli to talk to the tiller server. 😢

**Comment by technosophos** [comment]
Status update: We are debating whether we need to do this right now. @adamreese is approaching things differently: as connecting to a pod via a tunnel, rather than via a service.
