### ISSUE TITLE
Store Tiller's releases in ConfigMap

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#656]
Tiller should store each release inside of a ConfigMap object that is in Tiller's namespace (default `helm`) and uses a predictable label pattern.

We need to be able to re-construct the history of a release, so as a release is upgraded, we need to store a snapshot of the release. We might be able to do this by treating the ConfigMap as a series of immutable records, and just use labels and annotations to fetch the current ones.

**Comment by technosophos** [comment]
Per the community stand-up meeting today, moving this to Alpha.3.

**Comment by chancez** [comment]
Wouldn't this make more sense as third-party resource perhaps? It would seem that would be more flexible, as you can define your own schema, rather than being limited to a `map[string]string`.
