### ISSUE TITLE
re-structure $HELM_HOME

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#659]
Change init to create config directories under $HELM_HOME/repository instead of $HELM_HOME/ to make the migration from github.com/helm/helm to kubernetes/helm as smooth as possible.

- cache/, local/ and repositories.yaml should all be created under $HELM_HOME/repository
- update any commands that are using the old path to use the new structure

**Comment by technosophos** [comment]
Is this done?

**Comment by vaikas-google** [comment]
Yep.
