### ISSUE TITLE
Report security issue?

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#662]
Where is the proper place to report a security issue? If I follow the [k8s policy it's to Google](http://kubernetes.io/docs/reporting-security-issues/). But, k8s is now part of the CNCF and Helm (through Helm Classic) wasn't a Google product.

Is the proper place to report a Helm security issue to Google?

Of course, security issues like this *should* never happen.

**Comment by technosophos** [comment]
In your experience, would setting up a designated email address be the best for this?
