### ISSUE TITLE
Is CLA still needed?

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#663]
The Helm docs note that Helm (along with k8s) is now part of the [CNCF](https://cncf.io/). Is the Google CLA needed to contribute to CNCF projects?

**Comment by technosophos** [comment]
Great question. I have no idea, so I am asking around now.

**Comment by technosophos** [comment]
I believe @mattfarina did some hunting, and the current answer to the question is "Yes, until CNCF and Google finish the IP transfer"

**Comment by michelleN** [comment]
👍

**Comment by mattfarina** [comment]
I believe there will be a change once the IP handling with the CNCF is complete. At that time it will change. Whether it's a CLA to the CNCF or a DCO is still yet to be completely determined. So, a change will happen at some point.

Does that mean we can close this?

**Comment by michelleN** [comment]
I believe so. Thanks @mattfarina.
