### ISSUE TITLE
rename cache to index

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#665]
cache.yaml -> index.yaml

**Comment by vaikas-google** [comment]
Do we also want to rename the files of the form: <repo>-cache.yaml to: <repo>-index.yaml? Or: <repo>-cache-index.yaml to indicate they are not authoritative?

**Comment by michelleN** [comment]
good question. I think we should leave the cache directory's name the same in $HELM_HOME... they'll probably store charts as well eventually so that we don't have to make unnecessary requests.

As for the files, -index.yaml make sense to me. I'm not sure I understand why we would do a -cache-index.yaml name
