### ISSUE TITLE
helm upgrade

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#690]
We need to figure out how we are going to handle updating a release from one chart version to another.

**Comment by sstarcher** [comment]
Would this also constitute updating of just the docker image or is that outside of the scope?

**Comment by mboersma** [comment]
The quick-and-dirty solution in Helm classic is this: helm/helm-classic#474. I doubt that is applicable to new Helm, but it meets the basic upgrade needs for the workflow-dev Chart and may be useful to compare.

**Comment by errordeveloper** [comment]
I think that adding an equivalent of `kubectl apply` for deployments would be just fine. It'd be nice to be able to pass new values (e.g. `fooImageTag=v2`) and use current template of a deployment definition, or otherwise pick up what's latest in the repo and apply that. I do not see a major need for supporting `kubectl rolling-update` at this point in time, and would be happy if Helm embraces the latest API.

**Comment by technosophos** [comment]
The current thought on this (for Alpha.3) is that:

- Helm will support in-place upgrades for `deployments`
- Helm will support naive adding of resources that appear in later versions of a chart
  - Example: Chart version 1.1.0 defines a pod, chart 1.2.0 defines the same pod and a new service; helm adds the new service
- Helm will **not** delete resources that disappear out of a chart
  - Example: Chart version 1.1.0 defines a pod and a service; chart 1.2.0  defines only a pod. The service will **not** be deleted
- Helm will essentially `kubectl apply` all other changes
  - Example: Chart version 1.1.0 defines a pod; chart 1.2.0 modifies that pod. Tiller will replace the version 1.1.0 pod with the 1.2.0 pod using a methodology similar to or identical to `kubectl apply`.
- Helm will expose two "hooks" that will be able to run custom Kubernetes jobs(_?_). "pre-upgrade" will accept a job definition to be run before an upgrade, and "post-upgrade" will accept a job definition to be run after an upgrade. These will allow for things like dumping and loading the contents of a database.

More complex cases have been deferred, though if you have some good use cases, we'd love to catalog them on this ticket.

**Comment by michelleN** [comment]
This looks good to me @technosophos 🎉

**Comment by hunter** [comment]
I really like the idea of pre/post upgrade hooks as a way of running tests, validations or triggering notifications. Is this something that can also be added for pre/post install?

**Comment by technosophos** [comment]
@hunter Good idea. Seems like if we are doing it for upgrade, we should do it for install. Would `helm delete` also be a place to add hooks?

**Comment by technosophos** [comment]
@gabrtv suggested adding a `Version` field on release, which would be a simple integer. This is much easier for comparison operations than parsing and using the Date field as planned.

**Comment by michelleN** [comment]
I've been under the assumption that we're doing an upgrade of the same chart but from one version to another version like from alpine-1.0.0 to alpine-2.0.0 but I had not thought about going from alpine-1.0.0 to some-random-chart-1.0.0. Is there a reason we might need the latter case?

**Comment by kfox1111** [comment]
what about daemonsets/petsets? do you delete/replace the daemonset? what about the use case where you may want to delete the daemonset but not the existing pods during the upgrade?
