### ISSUE TITLE
META: Roadmap

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#694]
**Edit: This has been moved to https://github.com/kubernetes/helm/wiki/Roadmap**

This ticket is for commenting on the Roadmap, which is now in the Wiki.

**Comment by alialaee** [comment]
Is there any plan for other storage backends for releases within Tiller? Such as etcd or kubernetes itself (labels and annotations)?

**Comment by philips** [comment]
@technosophos #874 seems mis-milestoned.

**Comment by technosophos** [comment]
#874 is now correctly set to 2.0 Alpha.5

**Comment by gugahoi** [comment]
The roadmap is quite old now and missing info from 2.2.0 to current 2.5.1. Has it been moved somewhere else? The README still points to the wiki.

**Comment by bacongobbler** [comment]
We have been planning the roadmap using [github milestones](https://github.com/kubernetes/helm/milestones) and the weekly dev calls.

We should probably update the README. Thanks for pointing this out!

**Comment by bacongobbler** [comment]
closed via #2974. Anyone wanting to comment on the roadmap should either file a new ticket or file a PR. Thanks!
