### ISSUE TITLE
helm init fails when namespace already exists

### ISSUE THREAD

**Issue by wstrange** [kubernetes/helm#699]
When running helm init on an existing namespace, I get:

```
helm init --namespace default
$HELM_HOME has been configured at $HOME/.helm.
Error: error installing: [namespaces "default" already exists, the namespace from the provided object "default" does not match the namespace "helm". You must pass '--namespace=default' to perform this operation.]
```

I think helm should skip namespace creation if it already exists

**Comment by technosophos** [comment]
I agree with this. It doesn't seem like we should force users to create a new namespace just to use Helm.

**Comment by michelleN** [comment]
+1

**Comment by Anmorata** [comment]
I'm having the same problem

`Error: release funky-buffoon failed: namespaces "default" already exists`

when running helm install. 
version:
```
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
@Anmorata can you please open a new ticket for this? Also we'd need the following information:

- what chart you were deploying
- how is your kubernetes cluster set up
- how you installed tiller (assuming `helm init`)

**Comment by Anmorata** [comment]
cluster is set up in azure cloud by azure wizard. kubernetes version is 1.6.6 and tiller version is 2.6.0.
I'm deploying my custom build chart, which I build from `helm create` template. just added few my lines.
helm came with azure, I just upgraded

**Comment by bacongobbler** [comment]
Thank you. Please open a new ticket. This looks like a different issue than what's described in the OP.
