### ISSUE TITLE
helm search should handle empty index files gracefully

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#705]
might be my fault :0

**Comment by michelleN** [comment]
so it was a problem with my local configuration set up. I've been messing with index file generation stuff and the index files I had in my cache were empty so I was getting a panic.
So if you download an index file and it is empty, we'll see problems :(

**Comment by vaikas-google** [comment]
I still think we should handle it gracefully? I'll add a check for that, or what do you think?

**Comment by michelleN** [comment]
I’m thinking we should add a safeguard for empty or ill-formed index files in the code?

**Comment by michelleN** [comment]
yes @vaikas-google thanks!

**Comment by vaikas-google** [comment]
So, I just did this:
touch ~/.helm/cache/foo-cache.yaml
and did a search and it just said no matches, then I put garbage into that file: asdf
and it still didn't fail.
So, I guess I can't repro, or something else has changed in the meanwhile. Let me know if you can still repro this though and reopen?

**Comment by michelleN** [comment]
Yeah, I was just looking at this and now I can't reproduce it either!
