### ISSUE TITLE
Document Developer Workflow and best practices

### ISSUE THREAD

**Issue by wstrange** [kubernetes/helm#719]
It would be nice to have a short document that explains a recommended chart developer workflow.

For example, during development I want to update my main chart and several nested charts, what is the recommended workflow when updating nested charts? 

This could be in the form of an example

helm create my-db-chart
...

helm create master-chart
cd master-chart
helm fetch my-db-chart

... now I want to change my-db-chart
cd ../my-db-chart. Make changes, etc..

**Comment by hunter** [comment]
Perhaps out of scope but we'd be interested in seeing/discussing how testing fits as part of the developer workflow (outside of linting and running a local server mentioned in the docs).

Is there a workflow & best practices from source code to a full tested running app? Building images, testing and resource manifests are not directly related to Helm but are fundamental to the process of building charts. On top of that the deployment and testing of a main chart and nested charts ensuring that they work together with config values, launch/connect correctly, etc.

**Comment by technosophos** [comment]
Related to #715

**Comment by technosophos** [comment]
With the merging of the nginx chart and documentation, everything on the Alpha.2 portion is done. leaving this open so we can go back and see what else needs to be done in the future.
