### ISSUE TITLE
`helm list` does not support TILLER_HOST envVAr

### ISSUE THREAD

**Issue by runseb** [kubernetes/helm#724]
if we use a TILLER_HOST reachable over NodePort or potentiall port-forwarding, the `helm install` command works fine, but `helm list` fails.

https://github.com/kubernetes/helm/blob/master/pkg/helm/helm.go does not support TILLER_HOST like https://github.com/kubernetes/helm/blob/master/cmd/helm/install.go does.

**Comment by technosophos** [comment]
I'm going to move that config to the top-level Helm command. Seems like there should be one configuration step instead of having each command do its own.

**Comment by runseb** [comment]
fixed by https://github.com/kubernetes/helm/commit/0cbb6c6e86b39ed4c311c7c4a54c53837d93a44f

closing this
