### ISSUE TITLE
Creating a release `helm install` uses helm namespace

### ISSUE THREAD

**Issue by runseb** [kubernetes/helm#727]
I was expecting the releases to be deployed by default  in the _default_ namespace but they end up in the _helm_ namespace.

I have not tried setting up the namespace on the chart directly.

It seems charts will be deployed in the namespace specified on tiller startup. And that deploying releases on a different namespace than the tiller namespace is not supported.

**Comment by technosophos** [comment]
Yes, this is accurate.

The idea goes something like this:

- Tiller manages the resources _for its namespace_. It does not manage apps outside of its namespace, though we're planning on adding an option to configure that in the future.
- Tiller's default namespace is `helm` (following the old Helm/DM model)
- Tiller can be installed into `default`, but you have to use the `-n -s` flags: `helm init -n default -s`.

The design intent was to allow users to really segregate their namespaces the way the Kubernetes authors seem to have intended. So different namespaces can be completely firewalled off from each other, and multiple instances of tiller could be run in the same k8s cluster without causing confusion. Security is then handled by Kubernetes itself.

**Comment by runseb** [comment]
closing this
