### ISSUE TITLE
Why `helm status` and `helm list`

### ISSUE THREAD

**Issue by runseb** [kubernetes/helm#728]
To get the status you need to run _list_.

How about returning the status in a separate column of the _list_ output ?

**Comment by runseb** [comment]
Adding to that. The default `helm list` is a bit boring :) could make set --long to true by default at:
https://github.com/kubernetes/helm/blob/master/cmd/helm/list.go#L57

feels more user friendly.

**Comment by runseb** [comment]
Basically something like this:

```
$ bin/helm list -l
NAME            	UPDATED                 	STATUS 	CHART       
errant-goose    	Wed May 18 23:02:48 2016	DELETED	alpine-0.1.0
exciting-tarsier	Thu May 19 09:08:04 2016	DELETED	alpine-0.1.0
washed-otter    	Thu May 19 11:44:24 2016	DELETED	alpine-0.1.0
```

which we easily get with the following in cmd/helm/list.go:

```
func formatList(rels []*release.Release) error {
	table := uitable.New()
	table.MaxColWidth = 30
	table.AddRow("NAME", "UPDATED", "STATUS", "CHART")
	for _, r := range rels {
		res, err := helm.GetReleaseStatus(r.Name)
		if err != nil {
			return prettyError(err)
		}
		c := fmt.Sprintf("%s-%s", r.Chart.Metadata.Name, r.Chart.Metadata.Version)
		t := timeconv.String(r.Info.LastDeployed)
		s := fmt.Sprintf("%s", res.Info.Status.Code)
		table.AddRow(r.Name, t, s, c)
	}
	fmt.Println(table)

	return nil
}
```

**Comment by technosophos** [comment]
I will add the status column to the list output.

The `helm status` command is rather worthless at the moment. In the future, it's supposed to query Kubernetes and return the status of the various Kubernetes resources (real time). But we are not that far along yet.
