### ISSUE TITLE
helm status: Should query Kubernetes for status of resources

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#739]
Ideally, `helm status` should also query Kubernetes and get the status of the resources in "real time". Otherwise, this command is sort of a dumbed-down version of `helm get`.

**Comment by technosophos** [comment]
I think that all we really want for this command is something like this:

```console
$ helm status imprecise-hedgehog
replication-controller/foo
service/foo
secret/access-token
```

Or something like that.

The idea would be to make it possible for someone to query a release and find out what Kubernetes resources are associated with it.

Now, we could completely forgo this and assume that labels are done correctly. With good labels, `kubectl` can do this without our help.

**Comment by michelleN** [comment]
+1 It'd be nice to see all the resources associated with a release and how they're doing in real time.

**Comment by technosophos** [comment]
Superseded by #993
