### ISSUE TITLE
`helm package <chart>` packages `.git` metadata 

### ISSUE THREAD

**Issue by sameersbn** [kubernetes/helm#748]
Consider, 

```
helm create mariadb
cd mariadb
git init
# hack and commit
cd ../
helm package mariadb
```

The `.git` metadata ends up being packaged in the chart release. Maybe an optional `.helmignore` file can be defined in the chart directory to indicate files that should not be package in releases similar to `.gitignore` or `.dockerignore`.

What do you think?

**Comment by technosophos** [comment]
I do like the idea of a `.helmignore`.
