### ISSUE TITLE
PROPOSAL: Deprecate TOML in favor of YAML

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#768]
When we set up `values.toml`, we picked TOML because we felt like it was super simple to use. I had done a semi-formal poll of a broad community of developers, and that seemed to bolster the conclusion. So we implemented the values file as TOML.

But we are getting very strong feedback from the Kubernetes community that they would prefer YAML, since a wide variety of tools already use it. The arguments for YAML, against TOML:

- The TOML spec is in flux
- TOML is less familiar to many people
- We're the only ones using TOML in the immediate Kubernetes community
- YAML is just as easy to read
- YAML has broader editor/tooling support

So this proposal is that we immediately deprecated values.toml in favor of values.yaml

**Comment by chancez** [comment]
I would prefer having parity with how Kubernetes does this. Use a restricted subset of yaml that is compatible with JSON, and also support JSON.

This is fairly easy to accomplish if you have a well known schema of what things should look like which avoids using any JSON incompatible YAML-isms. Kubernetes has `pkg/util/yaml` which can readily convert between the formats, so it shouldn't be hard to have both.

If not JSON, I'd suggest using YAML but also restricting the features used to those that would allow compatibility with JSON.

**Comment by technosophos** [comment]
What would be the use case for JSON?

We for sure do not have a schema for the `values` files, since basically it carries freeform data that is sent directly to the templates. Expressiveness-wise, YAML is more expressive than JSON, which in turn is (slightly) more expressive than TOML. So the main technical reason for not using YAML is that we cannot possibly implement the entire spec (it simply doesn't fit the problem space). That's a tough one to educate users on.

**Comment by chancez** [comment]
@technosophos You can have a schema with free form values, it just has to be limited to something like a normal map. I just meant we should avoid things like keys which are arrays (`[1,2,3]: "this is valid yaml but not JSON"`

The schema of values could be as simple as a `map[string]interface{}`, but I'm certainly saying don't want a `map[interface{}]interface{}`.

**Comment by technosophos** [comment]
Okay. I'm convinced. I'm going to add support for YAML, keep support for TOML, but "mark TOML as deprecated" (whatever that means for an Alpha release).

**Comment by brunoborges** [comment]
So... after 4 years in and how much we know YAML can kill productivity, can we go back and undeprecate TOML?

**Comment by slamgundam** [comment]
TOML is way easier to understand than YAML, please undeprecate TOML and deprecate YAML
