### ISSUE TITLE
helm search raises a runtime error unless helm has been initialized

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#778]
After installing helm from source, if I execute `helm search redis` I get:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x40dfd0]

goroutine 1 [running]:
panic(0x1905e80, 0xc82000e120)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.searchCacheForPattern.func1(0xc8203df680, 0x26, 0x0, 0x0, 0x7f53d2f6f2d0, 0xc8203df800, 0x0, 0x0)
	/home/migmartri/work/gocode/src/github.com/kubernetes/helm/cmd/helm/search.go:63 +0x40
```

Problem that seems to be related to the fact that I have not initialized helm yet.

So executing `helm init` fixed the issue.

```
$ helm search redis
kubernetes-charts/redis-2.0.0.tgz
```

I have noticed that for some other commands there is a guard statement that tells you that the file does not exist, for example:

```
$helm fetch foo
Error: open /home/migmartri/.helm/repository/repositories.yaml: no such file or directory
```

We might want to implement the same approach for the search command. Ideally with a message a little bit more actionable that says something about executing helm init first (although this could be moved to another issue)

What do you think?

**Comment by michelleN** [comment]
Hey @migmartri. You're absolutely right. You have to run init to configure your local environment and that's why you're getting a panic. I agree; there should be some type of guard or actionable message.
