### ISSUE TITLE
Cobra command with no results output #usability

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#779]
Hi,

The behavior of the search command among others (i.e list) when returns no values seems strange to me. 

For example, if I execute `helm search nginx` I get a message that no matches found but also Cobra's usage information which made me think a couple of times that I was using a wrong command format since the "no matches found" message was buried and hidden after the terminal scrolled down.

```
Error: No matches found
Usage:
  helm search [keyword] [flags]

Global Flags:
      --alsologtostderr value    log to standard error as well as files
      --debug                    enable verbose output
      --home string              location of your Helm config. Overrides $HELM_HOME. (default "$HOME/.helm")
      --host string              address of tiller. Overrides $HELM_HOST.
      --log_backtrace_at value   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir value            If non-empty, write log files in this directory
      --logtostderr value        log to standard error instead of files (default true)
      --stderrthreshold value    logs at or above this threshold go to stderr (default 2)
  -v, --v value                  log level for V logs
      --vmodule value            comma-separated list of pattern=N settings for file-filtered logging

```

I think that if the command is valid but the response is empty we should not show the usage information as some other CLIs do. 
```
$ kubectl get svc foo
Error from server: services "foo" not found

```

Thoughts?

Regards,
Miguel

**Comment by michelleN** [comment]
hey @migmartri - I believe @technosophos is looking at changing a similar behavior on `helm list` to not return an error and all of this extra output. We should change this too.
Thanks for your feedback.

@vaikas-google - do you or @technosophos want to grab this one?

**Comment by vaikas-google** [comment]
Right, that was my worry earlier as well, I'll fix this. @migmartri there's a previous discussion somewhere in the issues / PRs :)

**Comment by technosophos** [comment]
I'll leave these to @vaikas-google. It's my fault that we ended up here, though. I was trying to match the behavior of `grep`, but returning an error causes Cobra to get all verbose and helpful. After looking at `find`, I see that not all UNIX commands return an error when there are no matches, so we'll do that for Helm.
