### ISSUE TITLE
Chart directory name constraint

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#782]
Hi,

According to the documentation found in [charts.md]( https://github.com/kubernetes/helm/blob/master/docs/charts.md)

> The directory name is the name of the chart (without versioning information).

In my tests, this does not seem to be enforced, being able to install releases both from a directory or tar chart.

For example, using the doc/examples/alpine renamed to alpine2, I was able to:

```
$ ls 
alpine2  README.md
```
Name of the chart is different than the directory.
```
$ cat alpine2/Chart.yaml 
name: alpine
description: Deploy a basic Alpine Linux pod
version: 0.1.0
home: https://github.com/kubernetes/helm
```

Release created based on the chart name not the directory.
```
$ helm install alpine2/
stultified-mole

$ helm list -l
NAME            UPDATED                         STATUS  CHART       
stultified-mole Wed Jun  1 14:26:36 2016        UNKNOWN alpine-0.1.0
```

Using a packaged chart.

```
$ helm package alpine2/
```

Package is created using the name of the chart and different directory

```
$ ls
alpine-0.1.0.tgz  alpine2  README.md
$ tar -tf alpine-0.1.0.tgz 
alpine2
alpine2/Chart.yaml
alpine2/README.md
alpine2/templates
alpine2/templates/alpine-pod.yaml
alpine2/values.toml
```

This package can be installed.

```
$ helm install alpine-0.1.0.tgz 
mothy-marsupial
```
 
Is the directory/chart naming constraint still in the  kube Helm specification or it is a documentation error?  

Miguel.

**Comment by technosophos** [comment]
Good catch. We're basically ignoring the directory name for any semantic purposes. This is definitely something we should catch during packaging and linting.

**Comment by technosophos** [comment]
@migmartri with the changes introduced in #818, do you think there's more we should do (other than issuing an error in `helm lint`)? I figure that `helm install` should be lenient on these things, but `helm package` and `helm create` should be strict.

**Comment by migmartri** [comment]
I think we are good for now. 

I am wondering if in the future and for the use case in which an user retrieves a Chart and modifies it, we should run the linter before `helm install`. Maybe run it only on unpackaged charts?

It will also depend on how much time the lint suite will take.

**Comment by technosophos** [comment]
Marking this one as closed.
