### ISSUE TITLE
Invalid chart package breaks search functionality

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#786]
Hi,

I am running into some issues with the local cache:

Let's say I want to install Redis, so I search for it.

```console
$ helm search redis
kubernetes-charts/redis-2.0.0.tgz
```

I fetch it

```console
helm fetch kubernetes-charts/redis-2.0.0.tgz
migmartri ~/.helm/repository/cache $ ls
kubernetes-charts-index.yaml  local-index.yaml  redis-2.0.0.tgz
```

Then I try searching again and the command will return the error.

```console
$ helm search redis
Error: index /home/migmartri/.helm/repository/cache/redis-2.0.0.tgz corrupted: yaml: control characters are not allowed
```

It seems that the problem is related to the package to be invalid or not compatible with the new chart spec.

```console
cat redis/Chart.yaml 
name: redis
description: Port of the replicatedservice template from kubernetes/charts
version: 2.0.0
home: ""
expander:
  name: foobar-service
  entrypoint: templates/redis.jinja

```

I know that the official repository has (or will have) validation tests before publishing a package so this might not be a problem in that case, but this might not be true for 3rd party repository providers, in that case, if one of those parties upload a corrupted/invalid package it might break the client code.  

I am wondering if we should make the search functionality more robust and ignore non valid artifacts existing in the cache. Or create some kind of format validation at the time of fetching the package. 
 
Thoughts? 
Miguel.

**Comment by michelleN** [comment]
Hey @migmartri - the cache directory should only contain index files not an actual copy of the chart. We don't have a concept of a workspace, so you can fetch and work on charts anywhere (except $HELM_HOME since that is just for config setup).

Did you fetch the chart into your cache directory or did you move it there or was it just there after you fetched?

Thanks!

**Comment by migmartri** [comment]
@michelleN good point, you are right, the problem is that I was fetching the chart inside the cache directory, for some reason I still have helm classic mindset. My bad, I am sorry :(

Feel free to close the issue and mark it as invalid since the problem is not related to the chart format.

Thanks,
Miguel

**Comment by michelleN** [comment]
No worries @migmartri . That makes total sense! 
It's good to see and note the change in mindset from helm-classic to kubernetes/helm. We have a line about not having a dedicated workspace anymore in the README but if you see another place we can make that more clear, feel free to add.
