### ISSUE TITLE
Chart proto: Add engine information to chart proto

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#801]
The format for the `engine:` directive in the `Chart.yaml` is:

```yaml
engine: gotpl
```

I forgot to put this in the requirements for the `chart.proto`, so it's not there. The value should just be `string`, since it will be possible in the future for users to define their own engine.

**Comment by fibonacci1729** [comment]
hapi/chart/metadata.proto contains "engine" property. (tag: 8).
