### ISSUE TITLE
Get an error to use the repo command

### ISSUE THREAD

**Issue by Ladicle** [kubernetes/helm#804]
I use repo command to add a helm/charts repository on github, but the following error has occurred.
```
$ helm repo add charts https://github.com/helm/charts
Error: Oops! Looks like https://github.com/helm/charts is not a valid chart repository or cannot be reached

Usage:
  helm repo add [flags] [NAME] [URL]

Global Flags:
      --home string   location of your Helm config. Overrides $HELM_HOME. (default "$HOME/.helm")
      --host string   address of tiller. Overrides $HELM_HOST.
  -v, --verbose       enable verbose output
```

**Comment by runseb** [comment]
@Ladicle a chart repo is a basic http server with package charts (.tgz) and an index file.
The `github.com/helm/charts` is the source of the former helm-classic charts that we are transitioning to new helm.

Try to add `https://console.cloud.google.com/storage/browser/kubernetes-charts-testing/` but I am still working on it and the index file may not be working yet.

**Comment by Ladicle** [comment]
@runseb 
I see. I didn't know that the repository architecture has changed.
Try to add `https://console.cloud.google.com/storage/browser/kubernetes-charts-testing/` but I also failed.

And try to read a little more code :)

**Comment by runseb** [comment]
@Ladicle so my bad with the url `https://console.cloud.google.com/storage/browser/kubernetes-charts-testing/` you can browse the packaged charts on your browser.

To add it to your repo list do:

```
$ helm repo add kubernetes-charts-testing http://storage.googleapis.com/kubernetes-charts-testing
$ helm repo list
NAME                     	URL                                               
kubernetes-charts        	http://storage.googleapis.com/kubernetes-charts   
kubernetes-charts-testing	http://storage.googleapis.com/kubernetes-charts...
local-charts             	http://localhost:8879
```

This is very much in flux right now, so be aware your are working with alpha releases and a fast moving target.

**Comment by Ladicle** [comment]
hmm, 

```
$ git rev-parse HEAD
57c9861116ab2146f84996941493279f64225541

$ make bootstrap build

$ helm repo add kubernetes-charts-testing http://storage.googleapis.com/kubernetes-charts-testing
Error: Oops! Looks like http://storage.googleapis.com/kubernetes-charts-testing is not a valid chart repository or cannot be reached

Usage:
  helm repo add [flags] [NAME] [URL]

Global Flags:
      --home string   location of your Helm config. Overrides $HELM_HOME. (default "$HOME/.helm")
      --host string   address of tiller. Overrides $HELM_HOST.
  -v, --verbose       enable verbose output
```

**Comment by runseb** [comment]
can you rebase your master branch, I don't think you are at the latest commit.

**Comment by runseb** [comment]
strange, can you try this one

```
$ helm repo add kubernetes-charts http://storage.googleapis.com/kubernetes-charts
```

**Comment by Ladicle** [comment]
Thank you! I have added.
