### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by jbowen93** [kubernetes/helm#809]
Found a broken links.

- On line 81 of https://github.com/kubernetes/helm/edit/master/docs/chart_repository.md the link should be `chart_repository_sync_example.md`.

I'd do a PR but my company is being slow about signing the CLA.

**Comment by michelleN** [comment]
alrighty thanks!

**Comment by jbowen93** [comment]
Another one:

- Line 76 of https://github.com/kubernetes/helm/edit/master/docs/developers.md should be `https://github.com/kubernetes/helm/blob/master/CONTRIBUTING.md`
