### ISSUE TITLE
Helm fetch requires .tgz after the valid chart-name

### ISSUE THREAD

**Issue by jbowen93** [kubernetes/helm#812]
`helm fetch <repo-name>/<chart-name>` returns a `404 Not found` however `helm fetch <repo/name>/<chart-name>.tgz` properly downloads the chart. The `.tgz` feels unnecesarry since the index.yaml file has the <chart-name> with the url field containing the fully formed path.

**Comment by technosophos** [comment]
I am going to toss this onto the Alpha.2 milestone unless anyone has objections.
