### ISSUE TITLE
Question: Isolation

### ISSUE THREAD

**Issue by colonelmo** [kubernetes/helm#813]
What path is meant to be taken for isolating different sets of releases? Is tiller supposed to be installed in multiple namespaces and only deploy manage releases in that particular namespace?

Edit:
As the above is not the case, may I suggest using namespaces as a means of encapsulating different helm environments?
This would make life a lot easier when managing deployments from multiple teams, and without having to deal with say, ```nodePort``` for connecting to a tiller on a custom namespace through a service.

Would have been nice if one were able to do e.g. ```helm list --namespace=mynamespace```. Is anything other than [this](https://github.com/kubernetes/helm/blob/master/cmd/helm/tunnel.go#L16) making this not a possibility?

**Comment by technosophos** [comment]
The design is that Tiller (the server) manages the namespace that it was installed into. So if you `helm init --namespace=foo`, tiller is installed into `foo` and then manages that namespace. Its default namespace is `helm`.

We're planning on adding some flags later to allow `tiller` to manage things in other namespaces, but that code hasn't been written yet. We imagine that it will work like this: `helm install --namespace=bar mychart`, which will install `mychart` into the namespace `bar` even if Tiller's namespace is `foo`.

The reason for:

We think that the emerging pattern with namespaces is that they are used to isolate a particular team or app. Namespaces are being used to set security constraints between an "app" (or set of resources) and the rest of the cluster. So Tiller runs in, and manages, just one namespace. You can add security constraints at the namespace level (including things like Calico firewall rules) and Helm charts won't have to be aware of those constraints.

It is inexpensive to run multiple Tiller servers, so you should be able to run separate instances of Tiller in separate namespaces, and use your `.kube/config` to tell `helm` how to talk to each of those.

**Comment by colonelmo** [comment]
Thanks.
What changes do I need to make in ```.kube/config``` to specify the tiller server that I want helm to talk to? And how can one specify this in a more "script-friendly" fashion for say, automated installs e.g. using only the ```helm``` cli?

**Comment by technosophos** [comment]
We're discussing this. I think we may add some CLI options for this. I'll CC @adamreese, whose looking at the connection code this week.

**Comment by colonelmo** [comment]
Very well. I guess it would be quite useful for helm to be "machine friendly" so higher level third party tools (e.g. [dashboard](https://www.github.com/kubernetes/dashboard)) would be able to use helm conveniently as a cli or a library.

**Comment by technosophos** [comment]
See #838 for the current proposal, and please feel free to comment on that. It's a rough sketch of an idea.

**Comment by colonelmo** [comment]
Thanks, I appreciate it. I'll just close this then.
