### ISSUE TITLE
'helm lint': emit a warning when `namespace:` is set on a resource

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#814]
Since Helm manages namespaces, charts should not have the `namespace: ` attribute explicitly set. The linter should warn (or maybe error) on that.

**Comment by migmartri** [comment]
`charts should not have the namespace:` is this something that has ever being supported? The chart struct marshaller will just ignore this field no?

Maybe we should be strict on the fields that are contained in the Chart.yaml and "lint error" if there is any field that is not supported in the `Chartfile` struct. What do you think?

Today I pasted a comment [here](https://kubernetes.slack.com/archives/helm/p1465941216000061) that might be related to the reason I am still confused.

**Comment by technosophos** [comment]
Helm Classic allowed users to install into specific namespaces, and it allowed the `namespace:` item in a resource metadata heading. Yesterday, we tested an old helm chart with Kubernetes Helm and it failed because of the namespace metadata item.

**Comment by migmartri** [comment]
Hi,

Just to double check. We are talking about the namespace field in the k8s manifest files right?

I am aware of `--namespace`  option in the classic CLI but there is not such option in the Chart.yaml format right?

I'll take care of this as soon as I start working on the templates linter.

**Comment by migmartri** [comment]
@technosophos I added a linter rule that raises an error for now in this PR https://github.com/kubernetes/helm/pull/857

**Comment by errordeveloper** [comment]
Has this behaviour changed with 573e5aa7fc00da16c3a443d9e2046c5be6140511?

**Comment by technosophos** [comment]
I don't think so, @errordeveloper. If I understand it correctly, we're just emitting an error when a chart contains a `namespace:` directive. We are still supporting using multiple namespaces and installing Helm into any given namespace.

But we might have to revisit this issue with the recent changes in perspective about how Tiller will handle namespaces.

**Comment by technosophos** [comment]
@adamreese Given the new namespace rules, what do we want to do about this issue?

**Comment by adamreese** [comment]
I think we can allow for namespaces to be defined in a chart.  I'll do some tests to make sure the client doesn't do anything weird.

**Comment by adamreese** [comment]
There will need to be some changes to the kubernetes client.  I will open a separate ticket.

**Comment by technosophos** [comment]
I am going to close this if it's okay with you, @adamreese

**Comment by adamreese** [comment]
close away
