### ISSUE TITLE
Non-template files should have a separate directory

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#815]
Currently even if the the file is not going to be templated we are going to keep it in the template directory.Having a separate directory(like manifests similar to helm-classic) to store them will be a good thing to have as it doesn't make sense to keep them in templates directory.

**Comment by technosophos** [comment]
It sounds like the consensus is that it is easier to store all of the manifests inside of the `templates` directory, even if they don't have any template directives. So I'm marking this as closed. If we want to re-visit this after the 2.0 release, we can.
