### ISSUE TITLE
PROPOSAL: Namespace handling and Helm/Tiller

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#838]
There are three options for namespace support in Helm/Tiller:

1. Tiller is installed into a namespace, and it then manages that namespace. Users can install many tillers in many namespaces on the same cluster.
2. Tiller is installed into a given namespace (e.g. `helm`), and it then manages all namespaces.
3. Idea (1) is the primary case, but we support also managing other namespaces.

While any of the three is technically possible, the user experience will be different for each. For example, a `helm --namespace=foo` in (1) would point to the namespace where tiller is installed, while a `helm --namespace=foo` in (2) would point to the namespace where the operations should happen (but not where Tiller lives). Obviously, this makes (3) the trickiest UX.

There are a few considerations to keep in mind:

- Some apps (notably Deis) require that they be running in a fixed namespace (`namespace: deis`). We need to adequately provide a solution for that case.
- The tunnel needs to know at initialization time which namespace it should connect to.
- RBAC, when it comes in ~1.5, will allow roles-by-namespace. We should consider how best to facilitate Tiller roles.

I suggest that we shoot for (1) for the Helm 2.0.0 final release. I propose that:

- We run one Tiller per supported namespace
- We provide a `--namespace, -n` flag and a `$HELM_NAMESPACE` to allow the client to target a namespace.
    - This is used to set up the tunnel and to find the Tiller server
    - The default namespace, if unspecified, comes from `.kube/config`
- We disallow or warn on manifests that contain a `namespace:` in the metadata.

Post-2.0.0, I suggest that we look into whether (3) can be done without sacrificing usability.

**UPDATE:** The consensus as of June 23, 2016 is that we will start by solving (2), and then work our way into  (3). The reasoning is primarily that this solves the most common use cases and imposes the least "opinion" out of the gate.

**Comment by colonelmo** [comment]
@technosophos  Looks pretty good in my opinion. (1) is pretty consistent compared to the other two which may cause ambiguities in code or cli, and it's kind of more backward-compatible than the others.

**Comment by colonelmo** [comment]
@technosophos By the way I gladly volunteer to work on this starting from next week.

**Comment by technosophos** [comment]
Sounds great. I know that @adamreese is working on the tunnel connection bit already. He's hanging out in Kubernetes Slack in the Helm room. I think we're all sort of leaning toward (1) because it feels straightforward to the user.

**Comment by errordeveloper** [comment]
I've been investigating whether Helm can be used to manage cluster addons (https://github.com/kubernetes/kubernetes-anywhere/issues/126), which would require it to run in `kube-system` namespace... I've been able to run `helm init --namespace kube-system --skip-namespace`, but didn't manage to do much else. In any case, if we could use of Helm for managing addons, user should be able to either install another instance of Helm in it's own namespace, or somehow use the one in `kube-system` namespace.

_(cc @mikedanese)_

**Comment by errordeveloper** [comment]
Now that I understand this a bit better, I have few more specific thoughts, and basically I am leaning towards (3), but making the behaviour a hard choice during installation of tiller.

I think that delegating tiller to single namespace should be an option, for those who wish to enforce stronger isolation, but this should have a separate flag. Basically, what I mean is that the current behaviour of `helm init --namespace=foo` should really be `helm init --delegate-namespace=foo`.

I think it'd be a reasonable default to install tiller in `kube-system`, and allow it to manage all other namespaces, and `helm install --namespace=foo bar` would behave just like `kubelet create --namespace=foo`, user can provide some default for this via an environment variable, setting it to be the name of some project they are working on, or an app composed of a few charts, if you like, or whatever, like their first name, in the case each developer runs a copy of the stack on a shared cluster.
This implies that user who installed it has write access to `kube-system`, and user who installs charts has at least read access to find tiller in `kube-system`. However, this would obviously imply that any user installing charts can do so agains any namespace, but I don't think it's helm's problem, and users who care about that can go for delegated namespace option above.

General take aways:
- `--namespace` flag behave like it does in `kubectl`, default should probably be `default` (or `helm` for backwards compatibility) with environment variable to set the default
- tiller should probably run in `kube-system` by default and be able to manage other namespaces
- if tiller is installed into a dedicated namespace (i.e. not `kube-system`), it can only manage that namespace

**Comment by errordeveloper** [comment]
As for 2.0, I think it may be a good idea to simply rename `--namespace` flag to `--deligate-namespace` for `helm init`, and not bother with adding such a flag to other commands, and only expose and environment variable one can set for other commands, `$HELM_NAMESPACE` is probably an okay choice.

**Comment by technosophos** [comment]
Okay, in the open developer planning meeting today, we decided that for Alpha.3, we'd do this:

- Support installing Tiller into whatever namespace you want, with the default being `default`
- Support installing _from_ that Tiller into _any_ namespace

We haven't addressed the question of whether charts will be allowed to create namespaces, but I don't see why we'd disallow this.

Post-Alpha.3, we will then work on:

- Running multiple Tillers in a cluster, with each Tiller defaulting to managing its own namespace
- Integrating with the (still experimental) RBAC system

We tried very hard to meet the requirements we have heard from the community. So if you feel like this route will really hinder your usage of Helm/Tiller, please let us know. Our goal is to solve the most common use case first, and work our way into other use cases.

Thanks, by the way, for all of the input you've sent us.

**Comment by technosophos** [comment]
I believe it is now safe to close this issue, right @adamreese ?

**Comment by adamreese** [comment]
yes, closing

**Comment by mariusgrigoriu** [comment]
What's the current state? Looks like with the recent commit Tiller can be run in multiple namespaces, and it installs to its own namespace, but it still relies on kube-system to store its configmaps. `helm ls` shows everything installed across all Tiller instances and namespaces. That's problematic for those of us using RBAC to lock down kube-system and other namespaces a user isn't supposed to access.
