### ISSUE TITLE
Document coding standards and conventions

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#840]
Currently, we sort of send people all over the place regarding developer guidelines. We should update the CONTRIBUTING doc to contain the following:

- Info about the CLA
- Info about this being a CNCF project
- A pointer to the Semantic Commit Messages (http://karma-runner.github.io/0.13/dev/git-commit-msg.html)
- A note about Go and Proto coding conventions
- Something about a code of conduct, which we don't currently talk about at all

**Comment by michelleN** [comment]
+1

**Comment by colonelmo** [comment]
+1 for info about the CLA.

**Comment by technosophos** [comment]
I think I will open a separate issue for the Code of Conduct thing, since it's bigger than just a minor doc change.
