### ISSUE TITLE
Duplicate resources

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/helm#851]
Background info:
```
> helm version
v2.0.0-alpha.1+e36647d

> kubectl get pods --namespace helm
NAME              READY     STATUS    RESTARTS   AGE
tiller-rc-nk3wq   1/1       Running   0          3h

> cd docs/examples/alpine

> git status .
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

> helm list 

```
This may be an edge-case, however it happen to be the first thing I've tried after reading the example.
```
> cp templates/alpine-pod.yaml templates/alpine2-pod.yaml
```
Trying to install yielded an error as well as the usage message, for some strange reason:
```
> helm install .
/Users/ilya/Code/.gopath/src/k8s.io/helm/docs/examples/alpine/.helmignore
Error: release ugly-gerbil failed: pods "ugly-gerbil-alpine" already exists
Usage:
  helm install [CHART] [flags]

Flags:
      --dry-run         simulate an install
  -n, --name string     the release name. If unspecified, it will autogenerate one for you.
  -f, --values string   path to a values YAML file

Global Flags:
      --debug         enable verbose output
      --home string   location of your Helm config. Overrides $HELM_HOME. (default "$HOME/.helm")
      --host string   address of tiller. Overrides $HELM_HOST.

````
Now, listing charts doesn't show anything:
```
> env KUBECONFIG=/Users/ilya/Code/service/infra/local/kubeconfig helm list

```
However, there is a pod running:
```
> kubectl get pods --namespace helm
NAME                 READY     STATUS    RESTARTS   AGE
tiller-rc-nk3wq      1/1       Running   0          3h
ugly-gerbil-alpine   1/1       Running   0          9s
```

I've also tried `heml lint` and `helm install --dry-run`, neither of which detected any issues...
```
> helm lint .

> helm install --dry-run .
/Users/ilya/Code/.gopath/src/k8s.io/helm/docs/examples/alpine/.helmignore
kissing-fox
```
It's not exactly okay that lint didn't detect this, but I'm not sure how robust is it at this point in time. In any case, at the very least, `--dry-run` could have detected the issue...

**Comment by technosophos** [comment]
It appears that you tried to install two identical copies of the same pod with the same name (`cp templates/alpine-pod.yaml templates/alpine2-pod.yaml`). You duplicated a template, and then installed both of those templates. But since they were identical, you tried to create two pods with exactly the same name.

It does look like one of the pods was created, but the release was not saved (which is why `helm ls` doesn't print anything). I'll see if I can find and fix that.

**Comment by technosophos** [comment]
Okay, here's the update on the issue.

The release is now saved as a failed release.

```
⇒  helm --host localhost:44134 install alpine
/Users/mattbutcher/Code/Go/src/k8s.io/helm/docs/examples/alpine/.helmignore
Error: release braided-cow failed: pods "braided-cow-alpine" already exists
Usage:
  helm install [CHART] [flags]

Flags:
      --dry-run         simulate an install
  -n, --name string     the release name. If unspecified, it will autogenerate one for you.
  -f, --values string   path to a values YAML file

Global Flags:
      --debug              enable verbose output
      --home string        location of your Helm config. Overrides $HELM_HOME. (default "/Users/mattbutcher/Code/helm_home")
      --host string        address of tiller. Overrides $HELM_HOST.
      --namespace string   kubernetes namespace
⇒  helm --host localhost:44134 ls -l
NAME            	UPDATED                 	STATUS 	CHART
braided-cow     	Tue Jun 21 14:02:00 2016	FAILED 	alpine-0.1.0
limping-cardinal	Tue Jun 21 14:01:23 2016	UNKNOWN	nginx-0.1.0
```

FAILED releases can be deleted, but we don't automatically delete so that you can debug first. We log the failures in Tiller's log.

```
⇒  kh get po
NAME                                             READY     STATUS    RESTARTS   AGE
braided-cow-alpine                               1/1       Running   0          2m
limping-cardinal-nginx-673783279-xzrrt           1/1       Running   0          2m
oldfashioned-salamander-nginx-2735090007-ddwh0   1/1       Running   0          1h
tiller-rc-qzk14                                  1/1       Running   0          1h
⇒  helm --host localhost:44134 delete braided-cow
⇒  kh get po
NAME                                             READY     STATUS        RESTARTS   AGE
braided-cow-alpine                               1/1       Terminating   0          2m
limping-cardinal-nginx-673783279-xzrrt           1/1       Running       0          3m
oldfashioned-salamander-nginx-2735090007-ddwh0   1/1       Running       0          1h
tiller-rc-qzk14                                  1/1       Running       0          1h
```

**Comment by errordeveloper** [comment]
My point is being that this kind of user error should be caught earlier,
whether through a dry run or lint steps, or even pre-validation in the
install step. I was just testing how Helm treats whatever you through into
the templates directory. Also, I am saying that the way it failed with a
usage string seems a bit buggy.

**Comment by technosophos** [comment]
- All errors fail with a usage message. I believe that is a default of the Cobra library. You can file a proposal issue to change that behavior. I'm kind of curious how people feel about the current behavior.
- Linting is in its infancy. But I'm sure the devs on that would appreciate help and/or feature requests. /cc @migmartri 
- `--dry-run` doesn't execute anything against Kubernetes, so it doesn't detect Kubernetes errors. I suppose at some point we might have it more aware of the contents of manifests, but the intent was not to have it detect runtime errors before install.

As I'm sure you can appreciate, pre-validating every single variant of all of Kubernetes' types isn't a trivial task (especially given the possibility of 3rd party API). I don't think we could prevent all errors before install. But if we came up with a fixed and logical set of rules, that'd be a good starting point for improved linting.

**Comment by technosophos** [comment]
Re-opened after a PR merge auto-closed.

**Comment by errordeveloper** [comment]
@technosophos thanks for fixing this!! I've created #864 regarding the usage message thing. Regarding linter, I think duplicate resource names would be a sort of generic thing. I don't think any non-trivial types or uncommon attributes would need to be taken into account. Should I create an issue regarding linter improvements, or we build the discussion from here? I'm also happy to share a simple Python linter we have written for K8s, if that may be of any use.

**Comment by errordeveloper** [comment]
Ok, for the record, I've checked out Python script, and it's something that essentially enforces a certain usage pattern (e.g. things like "`version" label should be the same as what's in image tag" and dozen similar kind of things), so I don't think it would be of much use here.

**Comment by technosophos** [comment]
Alright, at this point, I think that we fixed all of the things in this issue. The error handling is much improved, and fails earlier. Linting is much better. we Dropped the auto-display of help text.

If there are still some new linting rule ideas that you have, please do file some new issues for those.

Finally, sorry it took me so long to make it back to this issue.
