### ISSUE TITLE
proto: add tiller version endpoint

### ISSUE THREAD

**Issue by adamreese** [kubernetes/helm#858]
required for second part of https://github.com/kubernetes/helm/issues/761

**Comment by ngtuna** [comment]
anyone working on it ? If not I will.

**Comment by vaikas-google** [comment]
@ngtuna Are you working on this? If not I was going to tackle this next. Need it for the other bug as well (client should output client/server versions).

**Comment by ngtuna** [comment]
I'd love to take it but can't make it this week due to vacation. If it's no rush, I can solve it next week. Otherwise can you help?
