### ISSUE TITLE
Copyright notices are missing

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/helm#866]
I think the license should state:
```
   Copyright 2016 The Kubernetes Authors All rights reserved.
```

Also, the Kuybernetes project itself mandates copyright headers in all files, except for docs and peripheral stuff like makefiles (IIRC).

**Comment by technosophos** [comment]
Yeah, we need to find out whether a license header is necessary on every source file. Anyone know who to ask?

**Comment by runseb** [comment]
@technosophos most definitely. if you read the LICENSE file it explains how to apply the license, and that means put a header in every source file...

**Comment by technosophos** [comment]
You are right. I'll go run licenseybird on the codebase and do a PR.
