### ISSUE TITLE
index function should handle deleted charts correctly

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#872]
`$ helm repo index` currently does not correctly regenerate the index.yaml file in the case where you remove a chart from your local chart repository directory.

- [ ] `helm repo index` should handle the updated index.yaml file correctly
  * when you delete a chart from a repository, the index.yaml file should not delete the entry, instead it should update the `removed` key by setting it to true. 
- [ ] `helm search` should only display only those charts with a remove boolean that is set to false
- [ ] `helm update` should correctly be updating the index files. I found that it did not replace the cached kubernetes-charts index.yaml file in the $HELM_HOME/repository/cache dir in this instance -_-

**Comment by ngtuna** [comment]
I'm doing on it.
