### ISSUE TITLE
Makefile: `docker tag -f` doesn't exist for docker >= 1.10.0

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/helm#880]
https://github.com/kubernetes/helm/pull/579 put the `-f` back, but I didn't quite understand why.  Happy to PR if it's as simple as removing that flag, in the meantime I'm forced to keep a copy of docker 1.9.1 around if I want to build helm

```
aaron@cloudtop:~$ for v in 1.9.1 1.10.3 1.11.2 system; do dvm use $v; docker tag --help | grep force; done
Now using Docker 1.9.1
  -f, --force=false    Force
Now using Docker 1.10.3
Now using Docker 1.11.2
Now using Docker system (1.12.0-rc2)
```

/cc @jackgr @adamreese @sparkprime (since you all may have more context on #579)

**Comment by bacongobbler** [comment]
fwiw we have been using Docker 1.10 as our development baseline without issues at https://github.com/deis/workflow. We had to remove the `-f` flag for users on docker 1.12 because of the reasons stated above.

**Comment by technosophos** [comment]
We can definitely remove that flag.
