### ISSUE TITLE
Questions about linter quoting rules

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#882]
I have a few questions about linting:

- can we relax the `| quote` requirement to also allow `| squote`? The escape rules are different.
- If we force an int to be placed in quotes, is it evaluated as a string? That could cause problems with arithmetic operations.

**Comment by migmartri** [comment]
> can we relax the | quote requirement to also allow | squote? The escape rules are different.

In theory this is supported but it is not listed in the test examples.

**Comment by migmartri** [comment]
> If we force an int to be placed in quotes, is it evaluated as a string? That could cause problems with arithmetic operations.

I have not looked into this yet which I think it is an important concern. Should I create another issue to look into it?
