### ISSUE TITLE
Templates: get rid of <no value>

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#887]
When a Go template references a value that was not supplied in the Values object, it prints `<no value>`, which then trips up the YAML parser, and breaks in unfortunate ways.

We should either:

- Error out and die if a value is not specified
- Emit an empty value ("") if it is not specified

I would opt for the later because the former may just move the burden to the user. Making it configurable would be best.

**Comment by technosophos** [comment]
It's also better to not error by default because developers can use `{{ .Foo | default "bar"}}` to set defaults.

**Comment by errordeveloper** [comment]
@technosophos I agree with your reasons, I'd lean towards throwing an error, but then you are saying that `{{ .Foo | default "bar" }}` would throw an error too... so I am not sure, but may be that shouldn't be allowed and people should use `{{default "bar" .Foo}}`?  I suppose if `{{ .Foo | default "bar" }}` had thrown an error, Helm could simply suggest them to use  `{{default "bar" .Foo}}` instead... In any case `<no value>` is very bad.

**Comment by technosophos** [comment]
I think we can definitely allow both variations of `default`, and just verify that the output is never `<no value>`
