### ISSUE TITLE
docs: Suggest using 'minikube' for dev environment

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#889]
It seems that the script assumes that you have a docker-machine configured [1]. This is not always true in barebone linux hosts.

It would be great if linux users could take advantage of this script. 

[1]
```
[[ -n "${DOCKER_MACHINE_NAME:-}" ]] || return
```

**Comment by migmartri** [comment]
It seems that Kubernetes just released https://github.com/kubernetes/minikube which works on mac and linux.

It might be a good idea to point to it from our documentation instead of local-cluster.sh

What do you think?

**Comment by technosophos** [comment]
Yeah, I think that should be the preferred route. Changing the issue title accordingly.
