### ISSUE TITLE
Hooks for Helm

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#901]
Broken out from #690

Define a hook system for helm supporting at least the following hooks:

- pre-install: fires before the templates for a chart are created during a `helm install CHART`. The release information will be available to the hook, but the release itself will not be created in Kubernetes.
- post-install: fires after the helm templates are pushed into Kubernetes (but possibly before the resources are all running, since we don't wait for those)
- pre-upgrade: fires before the templates for a chart are evaluated during a `helm upgrade RELEASE`.
- post-upgrade: first after the release's updated resources have been loaded into Kubernetes.
- pre-delete: fires before `helm delete RELEASE` actually sends a delete operation
- post-delete: fires after the list of deleted resources has been sent to Kubernetes

Charts will be able to declare Kubernetes jobs that run at these hook points.

**Comment by michelleN** [comment]
would `pre-rollback` and `post-rollback` make sense here? Or is that adding to much to the scope of things? @technosophos

**Comment by technosophos** [comment]
Yes, they would.
