### ISSUE TITLE
PROPOSAL: Chart preview Mode

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#903]
Hi,

I have been doing some modifications lately to example and custom charts and I have noticed that it does not seem to be a simple way to preview how the templates will look like after executing and interpolating the values.

The linter today does a full template rendering, taking your values from `Values.yaml` and `Chart.yaml` and letting you know if any of your functions returns nothing, but I think we should go an step further showing what the full output will look like.

I think that this is important because:
 
* Template rendering has become an important part of the chart lifecycle, happening for every chart install.
* We support piped sprig functions. It would be great to know not just that they do not crash but that they are doing what we expect them to do.
* Namespaces (`Global`, `Values.`, `Charts.`, `dependency charts`) has added great features but also complexity in terms of overrides.
* Partial templates are flexible but (in my opinion) prone to errors during conception.

I do not propose to add it as part of the linter command, it might make sense to have something like:

`helm preview [chartName]` which could:

* Output to STDOUT the file name and its rendered output.
* or, output into another directory. I think we should not do this because it can be confusing since helm classic used to work this way.

What's your workflow today to test that the modifications in your chart make sense?  (using dry-run? checking pod definitions via kubectl?)

Thoughts?

Regards,
Miguel

**Comment by michelleN** [comment]
I believe the --dry-run and --debug flags on the install command do just that! @migmartri 
```
helm [master]$ bin/helm install docs/examples/nginx/ --dry-run --debug
Created tunnel using local port: '58818'
Server: ":58818"
Chart path: /Users/michellenoorali/gocode/src/k8s.io/helm/docs/examples/nginx
NAME:   wise-lizzard
INFO:   Tue Jun 28 13:03:04 2016
CHART:  nginx 0.1.0
MANIFEST:
---
# Source: templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This uses a "fullname" template (see _helpers)
  # Basing names on .Release.Name means that the same chart can be installed
  # multiple times into the same namespace.
  name: wise-lizzard-nginx
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: "Tiller"
    # This makes it easy to search for all components of a release using kubectl.
    release: "wise-lizzard"
    # This makes it easy to audit chart usage.
    chart: "nginx-0.1.0"
spec:
  replicas: "1"
  template:
    metadata:
      labels:
        app: wise-lizzard-nginx
        release: "wise-lizzard"
    spec:
      containers:
      - name: wise-lizzard-nginx
        # Making image configurable is not necessary. Making imageTag configurable
        # is a nice option for the user. Especially in the strange cases like
        # nginx where the base distro is determined by the tag. Using :latest
        # is frowned upon, using :stable isn't that great either.
        image: "nginx:1.11.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        # This (and the volumes section below) mount the config map as a volume.
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: wwwdata-volume
      volumes:
        - name: wwwdata-volume
          configMap:
            name: wise-lizzard-nginx

---
# Source: templates/svc.yaml
# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: wise-lizzard-nginx
  labels:
    heritage: "Tiller"
    release: "wise-lizzard"
    chart: "nginx-0.1.0"
spec:
  ports:
  - port: "8888"
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: wise-lizzard-nginx

---
# Source: templates/configmap.yaml
# This is a simple example of using a config map to create a single page
# static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name: wise-lizzard-nginx
  labels:
    release: "wise-lizzard"
    app: wise-lizzard-nginx
    heritage: "Tiller"
data:
  # When the config map is mounted as a volume, these will be created as
  # files.
  index.html: "<h1>Hello</h1> <p>This is a test</p>"
  test.txt: test

helm [master]$
```

**Comment by migmartri** [comment]
Awesome, that's exactly what I wanted! 

I am wondering if we should either document it at a higher level (I have just found it in the [Nginx](https://github.com/kubernetes/helm/blob/2378a250707aef76e875d399a6bdaea7ce3dad5a/docs/examples/nginx/README.md) example), encapsulate it into its own command or integrate it with the linter.

**Comment by michelleN** [comment]
Sweet. Glad it helps!

On documenting at a higher level: were you thinking on the [quickstart](https://github.com/kubernetes/helm/blob/master/docs/quickstart.md) guide or maybe having a more advanced user scenario document? Those flags are very useful. How can we make them more apparent?

On encapsulating it into its own command: For this case, I think keeping the functionality on install as flags makes the most sense from a user perspective rather than having to learn/remember an additional command. What do you think? Do you think the flags are confusing or straightforward? Do you think 

On integrating it with linter: could you expand a little more on that? 


cc/ @technosophos

**Comment by migmartri** [comment]
I think it might make more sense to be added to the `charts` document under the "using help to manage charts" section.

https://github.com/kubernetes/helm/blob/master/docs/charts.md#using-helm-to-manage-charts

**Comment by technosophos** [comment]
One thing to note about `--dry-run` is that it still goes to the server for resolution.

**Comment by migmartri** [comment]
In my opinion, and taking into account the early stage of the project, it would be enough to just add some visibility to this command/flags combo in the current documentation as suggested above in the comments.

Eventually, I'd prefer a separated command or sub-command so in that way it gets explicitly-documented. It will also avoid people to install a wip chart when what they wanted was to just debug it (if you miss the ---dry-run).  

> One thing to note about --dry-run is that it still goes to the server for resolution.

It is true that adds some latency, but from that perspective I think it is fine (for now). I am wondering if you have other concerns related to hitting the server, like system overload, bottleneck, etc.

**Comment by michelleN** [comment]
Yeah, I can definitely see the value in a separate command or sub command and avoiding installing a wip chart is a really good point.

**Comment by prydonius** [comment]
@technosophos @vaikas-google now that we have the `helm inspect` command, an option like `--render/generate/full` could render the chart client-side. What do you think?

**Comment by prydonius** [comment]
Closing in favour of #978
