### ISSUE TITLE
ptypes.TimestampProto vs timecov.Timestamp

### ISSUE THREAD

**Issue by migmartri** [kubernetes/helm#914]
Hi,

It seems that in some parts of the code we are using `timecov.Timestamp` function to create a protobuf timestamp from a `time.time`. Function that is available as well in `ptypes.TimestampProto`.

Which one should we use? Since it seems that most of the functions seem related to protoc type transformation, are we going to move away from the `timeconv` package anytime soon?

More info here https://github.com/kubernetes/helm/pull/899#discussion_r69030839

**Comment by technosophos** [comment]
Yes, we should get rid of `timeconv`. For a while, we were stuck on an older version of protobuf that did not have the timestamp conversion functions. But with Kubernetes updated, we can use the protobuf library instead.

**Comment by technosophos** [comment]
To get rid of `timeconv` completely, we need support for `timeconv.Now()` and `timeconv.Format()`. I opened an upstream PR for these in the protobuf library (https://github.com/golang/protobuf/pull/207). If that doesn't go through, I'll try a half-way refactor of `timeconv` and at least get some of the functions removed or replaced.
