### ISSUE TITLE
Unused overrides in chartutil.CoalesceValues

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#920]
In #912 I noticed that the last parameter in chartutil.CoalesceValues doesn't seem to be used anywhere other than tests anymore. Should we remove the option, or do you see a need for it in a future change to the values?

https://github.com/kubernetes/helm/blob/master/pkg/chartutil/values.go#L142

/cc @technosophos

**Comment by technosophos** [comment]
Yeah, since the refactor I did on `{{.Template}}`, there is only one place that uses that third option, and it's a unit tests. So we should probably just remove the third arg.
