### ISSUE TITLE
add a "Why Helm" doc

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#926]
Some people have come in with questions around why they would use helm, so maybe a section or doc on why someone would use helm. Why is it helpful? How is different from kubeclt and other tools? Core values and direction and goals might be helpful?

If anyone from the community has something they'd like to add to this section, please feel free to drop a few lines in this issue.

**Comment by technosophos** [comment]
Given #965, can we call this good for now?

**Comment by technosophos** [comment]
I'm going to close this, based on #965 being merged.
