### ISSUE TITLE
Dependent chart template helpers are not evaluated

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#933]
I was setting up a chart that used a MariaDB chart and created a `name` function in `./templates/_helpers.tpl` and `./charts/mariadb/templates/_helpers.tpl`. When doing a dry-run install I found that the MariaDB chart would ignore the definition of `name` in it's helpers and use the parent's instead. This was a weird side-effect, and since functions are not namespaced it would be easy to accidentally override.

After digging into it further though, I renamed `name` in MariaDB's helper to `mariadbName` and that caused this error:
```
Error: render error in "templates/mariadb-svc.yaml": template: templates/mariadb-svc.yaml:4:19: executing "templates/mariadb-svc.yaml" at <{{template "mariadbN...>: template "mariadbName" not defined
```

So it seems that MariaDB's helpers are not being evaluated. Any ideas?

**Comment by technosophos** [comment]
The names of templates go into a global namespace. So if two templates declare themselves as `name`, then which ever one is evaluated last will own that name. I'm trying to reproduce the situation you described above.

What I've been doing (and this is just a suggestion) is naming templates with a dotted namespace syntax. So if I create a helper in my `mariadb` chart, I'll call it `define "mariadb.name"`.

Here's an example of the crazy stuff I've been playing with: https://github.com/kubernetes/charts/pull/16/files

**Comment by technosophos** [comment]
Oh! I think I reproduced it! Looking into the issue now.

**Comment by prydonius** [comment]
> What I've been doing (and this is just a suggestion) is naming templates with a dotted namespace syntax. So if I create a helper in my mariadb chart, I'll call it define "mariadb.name".

Agreed, wondering if this could be something we can also catch in the linter. I guess all functions should have a namespace, even at the top level, in case the top-level chart is pulled in as a dependency elsewhere.
