### ISSUE TITLE
support for editing of the chart  before install

### ISSUE THREAD

**Issue by kmala** [kubernetes/helm#943]
Most people would like to do some customization before installing a charts once the chart has been fetched.This can be done currently but i want it to be supported in native way.To support it natively i suggest following changes:
1) helm fetch should download to the $HELM_HOME instead of making the local directory dirty.
2) have a command something like helm edit <chart>.

PS: i might be totally wrong and din't understand the helm architecture properly.

**Comment by technosophos** [comment]
I think I am going to mark this "wontfix" . There are two reasons for this:

(1) When we switched from the `helmc` workspace-oriented approach to Kubernetes Helm, we decided that we would always treat the current directory as the work directory. While this is definitely confusing coming from Helm Classic, we feel like this is our opportunity to correct something we weren't particularly happy with in Helm Classic.

(2) While we could re-introduce `helm edit`, we don't really have the workflow story we did with Helm Classic. The `helm edit` command in Helm Classic was always sorta buggy. So I'm not eager to re-introduce it unless someone can provide a really solid implementation that is sensitive to different OS/shell considerations.

Thanks, though, for hanging in there with us as we try to make some of these rough transitions from Helm Classic to Kubernetes Helm. I know it hasn't been easy.
