### ISSUE TITLE
ref: pkg/helm envar configuation

### ISSUE THREAD

**Issue by adamreese** [kubernetes/helm#953]
Configuration should be passed to the helm client rather than the client checking environment variables.

**Comment by technosophos** [comment]
The code block in question is here: https://github.com/kubernetes/helm/blob/master/pkg/helm/client.go#L28-L40

**Comment by nhlfr** [comment]
@technosophos the code block you linked wasn't used anywhere.

The logic about environment variables for helm client is here:
https://github.com/kubernetes/helm/blob/master/cmd/helm/helm.go#L77-L85

**Comment by technosophos** [comment]
I think this issue is now closed, given what @nhlfr just pointed out. Does that sound right, @adamreese, or am I misunderstanding the issue?
