### ISSUE TITLE
helm install should report which template file caused an error 

### ISSUE THREAD

**Issue by wstrange** [kubernetes/helm#957]
If a yaml template has an issue when deployed  to k8s, helm install will print something like:

 yaml: line 27: mapping values are not allowed in this context

It would be really helpful if the name of the template was printed as well, so you can figure out what needs to be fixed

**Comment by technosophos** [comment]
That error comes from kubernetes, so we might not be able to recover the template. We should, however, be able to print out the YAML that failed. I'll take a look into it and see what we can do. 

If you have a snippet of a chart template that you know will cause that error, would you mind dropping it in here so I can make sure I'm testing with representative data?

Thanks!

**Comment by wstrange** [comment]
Hmm, I fixed my template errors, so I can't recall the exact issue :-)

I think it was yaml error where I tried to use a map where k8s wanted an array (ports, or some such thing)

**Comment by technosophos** [comment]
Okay. Testing this today.
