### ISSUE TITLE
feature: add --name-template for 'helm install'

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#975]
This idea occurred to me while chatting with @viglesias

We could expose some basic client-side naming sugar to allow semi-automated version naming, e.g. `helm install --name-template="my-name-{{randAscii 6}}" nginx`. This would allow end users to semi-name their stuff, but not have to worry about naming collisions. CI/CD systems might benefit from something like this.

**Comment by viglesiasce** [comment]
Yep something that allows the same command to work repeatedly would be beneficial. This should also be able to output the chosen name in a script parseable format so that CI/CD can benefit.

**Comment by technosophos** [comment]
I'm going to be "proactive" and "assign" this to @vaikas-google, since it looks like #977 might have been done by the community. (Feel free to push back if you don't want to work on this, Ville)
