### ISSUE TITLE
feature: Add `helm inspect values CHART` and `helm inspect chart CHART`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#977]
Right now, `helm inspect CHART` shows both values and the Chart.yaml file. There have been requests to make each of these displayable separately. One way would be to add flags (--chart and --values). Another would be to add subcommands like in the title. I don't really have a preference. But doing this would allow people to do stuff like this:

```
$ helm inspect values docs/example/nginx > newvals.yaml
$ edit newvals.yaml
$ helm install -f newvals.yaml docs/example/nginx
```

**Comment by GrantSeltzer** [comment]
#984 :)

**Comment by vaikas-google** [comment]
No worries, was on my todo to get this finished today. Can we close this issue then?

**Comment by GrantSeltzer** [comment]
The PR got merged, so I would say yes.
