### ISSUE TITLE
feature: Add `helm inspect manifest CHART`

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#978]
One feature that has been requested a few times is the ability to render templates into manifest files _on the client side_. Currently, to see your values rendered into the templates, you have to do `helm install --dry-run --debug -f myvalues.yaml mychart`.

The request is to make it possible to do:

```
$ helm inspect manifest mychart
```

And for output, get back the generated manifest.

**Comment by technosophos** [comment]
This is fairly low priority right now.

**Comment by technosophos** [comment]
This is now implemented as an external plugin: https://github.com/technosophos/helm-template

**Comment by dalvizu** [comment]
Anyone else running into this: helm-template is now part of helm
