### ISSUE TITLE
deployed-instances does not work for template URLs

### ISSUE THREAD

**Issue by bmelville** [kubernetes/helm#99]
From investigation by @vaikas-google it looks like the gorilla HTTP framework does not handle encoded URLs in the standard way, such that the path we generate (types/<encoded template URL>/instances) is decoded before matching the handler path in the manager.

Until this is resolved, "dm deployed-instances" does not work for non-primitive types

**Comment by jackgr** [comment]
Not as import if we implement #25.

**Comment by vaikas-google** [comment]
I have a possible solution here, but it involves changes to gorilla/mux code and a small change to our code.

 dm --service=http://localhost:8080 list
[
  "guestbook.yaml"
]

dm --service=http://localhost:8080 deployed-types guestbook.yaml
[
  "Service",
  "ReplicationController",
  "https://raw.githubusercontent.com/kubernetes/deployment-manager/master/templates/redis/v1/redis.jinja",
  "https://raw.githubusercontent.com/kubernetes/deployment-manager/master/templates/replicatedservice/v1/replicatedservice.py"
]
 dm --service=http://localhost:8080 deployed-instances 'https://raw.githubusercontent.com/kubernetes/deployment-manager/master/templates/redis/v1/redis.jinja'
[
  {
    "name": "redis",
    "type": "https://raw.githubusercontent.com/kubernetes/deployment-manager/master/templates/redis/v1/redis.jinja",
    "deployment": "guestbook.yaml",
    "manifest": "manifest-1448408124665684960",
    "path": "$.resources[1]"
  }
]

************* Details for the changes to gorilla/mux are here...

https://github.com/gorilla/mux/compare/master...vaikas-google:master


I'll see if they are willing to take this patch, or if there's a reason why this won't be accepted.

**Comment by vaikas-google** [comment]
Tacked on my question to this bug.
https://github.com/gorilla/mux/issues/132

**Comment by jackgr** [comment]
Nice follow up. Tough answer re: earlier versions of go. Didn't see that
one coming.

Jack Greenfield | Google

**Comment by jackgr** [comment]
Is this still a P0, now that #25 is implemented?
