### ISSUE TITLE
Tiller tries to parse partials with blocks in them as YAML

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#991]
Getting the following error when trying to install a chart with a partial that defines a block:
```
Error: YAML parse error on block-test/templates/_helpers.tpl: error unmarshaling JSON: json: cannot unmarshal string into Go value of type main.simpleHead
```

If I remove the block, or replace it with a `define` it works fine. This also seems to be a recent regression, as I was able to deploy the chart successfully before.

To reproduce, you can do:

```
helm create block-test
cd block-test

cat > templates/_helpers.tpl <<EOF
{{block "test" .}}test block{{end}}
EOF

helm install . --dry-run --debug
```

**Comment by prydonius** [comment]
> This also seems to be a recent regression, as I was able to deploy the chart successfully before.

To elaborate, I'm assuming this was caused by an update to tiller:canary, since I deleted and re-created my cluster.

**Comment by technosophos** [comment]
The bug is in the new Hooks code. I'm tracking it down right now.
