### ISSUE TITLE
Extend status command to show information about resources and chart install notes

### ISSUE THREAD

**Issue by prydonius** [kubernetes/helm#993]
The `helm status` command currently takes in a chart release and displays the status of the release and the deployment date. It would be useful to extend the command, or create a new command (`info`) that goes through all the manifests deployed and outputs information (`kubectl get`) about a deployment/service/configmap etc. This way, a user can see the progress of the release with multiple `helm info` calls.

In addition to this, a short `notes.txt` file could be printed that explains how to use the chart (think caveats from Homebrew, or README.md from Helm Classic). Even better, this file could be rendered as a template with access to the resources and states, which would allow developers to print out commands specific to a release (e.g. a mariadb client command that plugs in the service name).

Following the Homebrew model, this info should also be printed after a successful chart installation.

Example:

```
$ helm info ignorant-skunk
Last Deployed: Tue Jul 26 16:35:58 2016
Status: DEPLOYED

==> DEPLOYMENTS
NAME                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
ignorant-skunk-lamp   1         1         1            0           6s

==> SERVICES
NAME                     CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
ignorant-skunk-lamp      10.0.0.205   <none>        9000/TCP   49s
ignorant-skunk-mariadb   10.0.0.13    <none>        3306/TCP   50s

==> NOTES 
You will be able to access your application once an external IP address has been assigned.

To connect to MariaDB, run the following command:
kubectl run mariadb-client -i --tty --rm --image bitnami/mariadb --command -- mysql -h ignorant-skunk-mariadb -u lamp-user -p
```

notes.txt
```
{{ if .Services.lamp.external-ip }}
Visit https://{{ .Services.lamp.external-ip }} to access your application.
{{ else }}
You will be able to access your application once an external IP address has been assigned.
{{ end }}

To connect to MariaDB, run the following command:
kubectl run mariadb-client -i --tty --rm --image bitnami/mariadb --command -- mysql -h {{ .Services.mariadb.name }} -u {{ .Values.mariadb.mariadbUser }}
```

**Comment by technosophos** [comment]
This is in line with what I had originally envisioned for `helm status`, which is currently basically useless. So I'd be cool with implementing this. I'm always reluctant to get too close to re-implementing kubectl in Helm, but the functionality sketched above feels distinct and useful.

It is, btw, fine with me if we ditched `helm status` and went with `helm info`

**Comment by prydonius** [comment]
@technosophos is it at all possible to re-use the underlying logic kubectl has for displaying that output? Or is the problem that kubectl isn't really implemented as a library?

**Comment by vaikas-google** [comment]
I started to look at this, and if I understand the state of the world currently, we'd basically need to look at the manifest and unmarshal it to raw k8s resources? Am I missing something that would have a structured list of release->k8s resources?

**Comment by technosophos** [comment]
You are correct. As things are now, Tiller doesn't really track the k8s resources. So you'd have to load the manifest off of the Release record, and then query the k8s API based on that manifest.

If you wanted to do this in phases, the short-term goal would be to get the `NOTES` section displayed. Then separately add the feature to query the k8s API.

@adamreese has ended up doing quite a bit of work on the k8s API stuff, so if you need to bounce ideas off of him, I'm sure he'd be happy to share.

**Comment by vaikas-google** [comment]
Phew :) Ok, that is what I had in mind but just wanted to make sure I wasn't missing anything obvious. Another option that we could do is to persist the manifest in a more structure way (proto), say type->name or something like that, but for now I'll proceed with unmarshaling to k8s resources and querying the client for deets. In any case I can proceed now that I know I wasn't missing anything obvious. Client stuff looks pretty straightforward, but I'll probably bug @adamreese just for fun :)

**Comment by technosophos** [comment]
I think there are proto defs for all of the Kinds now in the Kubernetes core. It could be really powerful to store those as serialized protos. We should check that idea out after Alpha.3 is done!

**Comment by adamreese** [comment]
bugging @areese is always fun

**Comment by vaikas-google** [comment]
Well, would you like me to take a crack at storing them as protos now? If not, I'll just proceed with unmarshaling on the fly? Hi @areese :)

**Comment by vaikas-google** [comment]
And is the notes.txt part of the chart? As in not-yet-existent file that we're adding now to chart spec?

**Comment by technosophos** [comment]
@prydonius is it `notes.txt`?

**Comment by prydonius** [comment]
`notes.txt` was just a suggestion, and I'd be open to other ideas. The `.txt` is to suggest that this is just a plain text file (i.e. not markdown), another option would be to have no extension, or maybe `.tpl` if we want to go down the templating route. What do you think? Maybe it makes sense to discuss this in another issue, and leave this one to just printing out the state of the resources?

**Comment by technosophos** [comment]
I think txt makes sense. I'm just a little frazzled and wanted to make sure that we were implementing according to the way you and Sameer had initially suggested.

**Comment by prydonius** [comment]
sounds good to me @technosophos, let's go with adding `notes.txt` to the chart spec

**Comment by vaikas-google** [comment]
But is the point that this is notes.txt that's part of the chart and when it gets released, we'd stash the notes.txt as part of the chart.

**Comment by vaikas-google** [comment]
Ok, so it is changing the Chart Spec, that's what I wanted to verify :)

**Comment by technosophos** [comment]
Yeah. It had been suggested that this file would be sent through the template engine at the same time as the other template files. So that would change the chart spec.

**Comment by vaikas-google** [comment]
Does this look about what you wanted?


Ok, with templates/NOTES.txt like so:
vaikas@vaikas-glaptop:~/projects/go/src/k8s.io/helm$ cat docs/examples/alpine/templates/NOTES.txt 
 this is my notes file, it may look like others, but it's mine...
{{.Release.Name}}-{{.Values.Name}} 

thseadsa 
dasdf 
asdfas



vaikas@vaikas-glaptop:~/projects/go/src/k8s.io/helm$ ./bin/helm --host localhost:44134 install docs/examples/alpine/
ill-whippet
vaikas@vaikas-glaptop:~/projects/go/src/k8s.io/helm$ ./bin/helm --host localhost:44134 status ill-whippet
Last Deployed: Mon Aug 22 16:32:09 2016
Status: DEPLOYED
Resources:
==> v1/Pod
NAME                      READY     STATUS    RESTARTS   AGE
ill-whippet-my-alpine-2   0/1       Running   0          6s
ill-whippet-my-alpine   1/1       Running   0         6s

==> v1/Service
NAME             CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
alpine-service   10.119.241.134   <pending>     82/TCP    6s


Notes:
 this is my notes file, it may look like others, but it's mine...
ill-whippet-my-alpine 

thseadsa 
dasdf 
asdfas


And then upgrading:
vaikas@vaikas-glaptop:~/projects/go/src/k8s.io/helm$ ./bin/helm --host localhost:44134 upgrade ill-whippet docs/examples/alpine/
ill-whippet has been upgraded. Happy Helming!
vaikas@vaikas-glaptop:~/projects/go/src/k8s.io/helm$ ./bin/helm --host localhost:44134 status ill-whippet
Last Deployed: Mon Aug 22 16:32:26 2016
Status: DEPLOYED
Resources:
==> v1/Pod
NAME                      READY     STATUS    RESTARTS   AGE
ill-whippet-my-alpine-2   1/1       Running   0          20s
ill-whippet-my-alpine   1/1       Running   0         20s

==> v1/Service
NAME             CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
alpine-service   10.119.241.134   <pending>     82/TCP    20s


Notes:
 this is my notes file, it may look like others, but it's mine...
ill-whippet-my-alpine 

thseadsa 
dasdf 
asdfas

**Comment by prydonius** [comment]
@vaikas-google awesome! Can I suggest that Notes also uses the `==>` heading, like `==> Notes`.

I also think it would be good to show the status after `helm install/upgrade` what do you think?

**Comment by vaikas-google** [comment]
You mean right after you run the command, in effect do a status command behind the scenes?

**Comment by vaikas-google** [comment]
And, Yeah, I'll change the formatting :)

**Comment by prydonius** [comment]
> You mean right after you run the command, in effect do a status command behind the scenes?

Yeah, I think this will be really useful, because I suspect most people will forget to run `helm status`, and the notes may contain some important next steps.

**Comment by vaikas-google** [comment]
I'll tackle that in a follow on CL. How's this format?
vaikas@vaikas-glaptop:~/projects/go/src/k8s.io/helm$ ./bin/helm --host localhost:44134 status gaudy-toucan
Last Deployed: Tue Aug 23 08:59:49 2016
Status: DEPLOYED

Resources:
==> v1/Service
NAME             CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
alpine-service   10.119.250.219   <pending>     82/TCP    21s

==> v1/Pod
NAME                     READY     STATUS    RESTARTS   AGE
gaudy-toucan-my-alpine   1/1       Running   0          21s
gaudy-toucan-my-alpine-2   1/1       Running   0         21s


==> Notes:
 this is my notes file, it may look like others, but it's mine...
gaudy-toucan-my-alpine 

thseadsa 
dasdf 
asdfas

**Comment by technosophos** [comment]
That looks like what I would expect.

**Comment by vaikas-google** [comment]
Ok, it's finally merged :) Please reopen if there's something missing.

**Comment by prydonius** [comment]
@vaikas-google did you want to create a new task for printing status after install/upgrade, or just use this one and reference the PR?

**Comment by vaikas-google** [comment]
I'll just use this one. So, like this?
vaikas@vaikas-glaptop:~/projects/go/src/k8s.io/helm$ ./bin/helm --host localhost:44134 install docs/examples/alpi
ne/
jumpy-wolf
Last Deployed: Mon Aug 29 17:07:01 2016
Namespace: default
Status: DEPLOYED

Resources:
==> v1/Pod
NAME                   READY     STATUS    RESTARTS   AGE
jumpy-wolf-my-alpine   0/1       Pending   0          1s
jumpy-wolf-my-alpine-2   0/1       Pending   0         1s

==> v1/Service
NAME             CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
alpine-service   10.119.249.86   <pending>     82/TCP    1s


Notes:
 this is my notes file, it may look like others, but it's mine...
jumpy-wolf-my-alpine 

thseadsa 
dasdf 
asdfas

**Comment by prydonius** [comment]
Yep, that looks great!
