### ISSUE TITLE
what should the 'dry-run' for a `helm upgrade` look like?

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#995]

**Comment by technosophos** [comment]
I would expect this:

1. If there is not an existing release that this would upgrade, return an error
1. Run through the template logic, return an error if that fails
1. Otherwise, return the release from Tiller

For client output, follow `helm install --dry-run [--debug]`

**Comment by technosophos** [comment]
@michelleN Did this feature make it in for Alpha.3? Is there anything left to do here?

**Comment by michelleN** [comment]
looks like neither debug nor dry-run work as expected. I'll look into & fix this.
