### ISSUE TITLE
feat: rollback across --replace (and make sure that to append to release history)

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#998]
Once the new storage backend is complete, we should support the following scenario:

1. run `helm install -n foo`
1. run `helm delete foo`
1. run `helm install -n foo --replace`

From there, any history operation (like `helm rollback`) should be able to access both the first release of `foo` and the re-used `foo`.

In other words, when a `--replace` operation is done, it should _append_ to the history for `foo`, not delete and replace it.

**Comment by fibonacci1729** [comment]
#1456
