### ISSUE TITLE
create helm binary and tiller docker image

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/helm#999]
I realise its early days for Kubernetes Helm and things are iterating fast; but its gonna be easier for folks to take Helm 2.x for a spin if there's a binary folks can download for helm and a docker image for tiller we can use inside Kubernetes

**Comment by technosophos** [comment]
The Docker image is there already, but you're right about a binary build for Helm. I think the Makefile even has a gox cross-compile target right now, so it might just be a matter of wiring up CI to generate something for us.

**Comment by pwittrock** [comment]
cc @erictune

Having a binary release of the helm client is pretty important for some of the work being done as part of Kubernetes 1.4.  Is there anything we can do to get this done sooner rather than later?

**Comment by pwittrock** [comment]
subscribe @pwittrock

**Comment by sgoings** [comment]
Helm binaries were provided in the alpha.3 release... But to make them easier to consume I've filed: #1046 and it sounds like that plus @adamreese's plans to automate the binary production packaging and uplaoding (in tar.gz format instead of just .tar format) will give better accessibility for helm users.

**Comment by pwittrock** [comment]
@sgoings That is great to hear.  I will try them out.

@janetkuo What are the os + architectures we recommend projects publish for go binaries?

**Comment by jstrachan** [comment]
thanks for the new binaries btw! just tried them on my mac and they work great!

**Comment by pwittrock** [comment]
Quick follow up.  There are currently a number of cool go tools being developed as part of the Kubernetes ecosystem.  I start to put together this wikipage to provide guidance on how we recommend tools are packaged (provide a consistent install experience across ecosystem).  Still a work in progress, but would be helpful to get your input:

https://github.com/kubernetes/community/wiki/Contributor-Guide:-Building-your-Kubernetes-Tool

**Comment by adamreese** [comment]
closed with #1049
